import ClassFieldTheory.AlgebraicNumberTheory.Idele.ClassGroup.Tower

set_option autoImplicit false

/-!
# A prime-degree intermediate field of a finite cyclic extension

This file supplies an induction field for finite cyclic extensions.
If `L / K` is a nontrivial finite cyclic Galois extension, choose a
prime `p ∣ [L : K]`.  For a generator `σ` of its Galois group, the
subgroup generated by `σ ^ p` has index `p`.  Its fixed field is
therefore an actual cyclic Galois extension of `K` of degree `p`, while
the remaining extension has degree `[L : K] / p`.
-/

noncomputable section

variable {K L : Type}
    [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [IsGalois K L]
    [IsCyclic (L ≃ₐ[K] L)]

local notation "G" => L ≃ₐ[K] L

/-- A fixed generator of the cyclic Galois group. -/
noncomputable def cyclicGaloisGenerator : G :=
  (IsCyclic.exists_generator (α := G)).choose

omit [FiniteDimensional K L] [IsGalois K L] in
theorem mem_zpowers_cyclicGaloisGenerator (σ : G) :
    σ ∈ Subgroup.zpowers
      (cyclicGaloisGenerator (K := K) (L := L)) :=
  (IsCyclic.exists_generator (α := G)).choose_spec σ

theorem orderOf_cyclicGaloisGenerator :
    orderOf (cyclicGaloisGenerator (K := K) (L := L)) =
      Module.finrank K L := by
  rw [orderOf_eq_card_of_forall_mem_zpowers
    (mem_zpowers_cyclicGaloisGenerator (K := K) (L := L))]
  exact IsGalois.card_aut_eq_finrank K L

/-- A prime divisor of the degree of a nontrivial cyclic extension. -/
noncomputable def cyclicDegreePrime
    (hdegree : 1 < Module.finrank K L) : ℕ :=
  (Nat.exists_prime_and_dvd
    (ne_of_gt hdegree)).choose

omit [FiniteDimensional K L] [IsGalois K L]
    [IsCyclic (L ≃ₐ[K] L)] in
theorem cyclicDegreePrime_prime
    (hdegree : 1 < Module.finrank K L) :
    (cyclicDegreePrime (K := K) (L := L) hdegree).Prime :=
  (Nat.exists_prime_and_dvd
    (ne_of_gt hdegree)).choose_spec.1

omit [FiniteDimensional K L] [IsGalois K L]
    [IsCyclic (L ≃ₐ[K] L)] in
theorem cyclicDegreePrime_dvd_finrank
    (hdegree : 1 < Module.finrank K L) :
    cyclicDegreePrime (K := K) (L := L) hdegree ∣
      Module.finrank K L :=
  (Nat.exists_prime_and_dvd
    (ne_of_gt hdegree)).choose_spec.2

/-- The subgroup generated by `σ ^ p`; it has index `p`. -/
noncomputable def cyclicPrimeDegreeSubgroup
    (hdegree : 1 < Module.finrank K L) :
    Subgroup G :=
  Subgroup.zpowers
    ((cyclicGaloisGenerator (K := K) (L := L)) ^
      cyclicDegreePrime (K := K) (L := L) hdegree)

theorem cyclicPrimeDegreeSubgroup_card
    (hdegree : 1 < Module.finrank K L) :
    Nat.card
        (cyclicPrimeDegreeSubgroup
          (K := K) (L := L) hdegree) =
      Module.finrank K L /
        cyclicDegreePrime (K := K) (L := L) hdegree := by
  rw [cyclicPrimeDegreeSubgroup, Nat.card_zpowers,
    orderOf_pow_of_dvd
      (cyclicDegreePrime_prime
        (K := K) (L := L) hdegree).ne_zero
      (by
        rw [orderOf_cyclicGaloisGenerator]
        exact cyclicDegreePrime_dvd_finrank
          (K := K) (L := L) hdegree),
    orderOf_cyclicGaloisGenerator]

theorem cyclicPrimeDegreeSubgroup_index
    (hdegree : 1 < Module.finrank K L) :
    (cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree).index =
        cyclicDegreePrime (K := K) (L := L) hdegree := by
  let P :=
    cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree
  let p :=
    cyclicDegreePrime (K := K) (L := L) hdegree
  have hp : p.Prime :=
    cyclicDegreePrime_prime
      (K := K) (L := L) hdegree
  have hpDvd : p ∣ Module.finrank K L :=
    cyclicDegreePrime_dvd_finrank
      (K := K) (L := L) hdegree
  have hcardP :
      Nat.card P = Module.finrank K L / p :=
    cyclicPrimeDegreeSubgroup_card
      (K := K) (L := L) hdegree
  have hcardG :
      Nat.card G = Module.finrank K L :=
    IsGalois.card_aut_eq_finrank K L
  have hmul :
      (Module.finrank K L / p) * P.index =
        Module.finrank K L := by
    simpa only [hcardP, ← Nat.card_eq_fintype_card, hcardG] using
      P.card_mul_index
  have hdivpos :
      0 < Module.finrank K L / p :=
    Nat.div_pos
      (Nat.le_of_dvd Module.finrank_pos hpDvd)
      hp.pos
  apply Nat.mul_left_cancel hdivpos
  calc
    (Module.finrank K L / p) * P.index =
        Module.finrank K L := hmul
    _ = (Module.finrank K L / p) * p :=
      (Nat.div_mul_cancel hpDvd).symm

noncomputable instance cyclicPrimeDegreeSubgroup_normal
    (hdegree : 1 < Module.finrank K L) :
    (cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree).Normal :=
  inferInstance

/-- The fixed field of the chosen index-prime subgroup. -/
noncomputable def cyclicPrimeDegreeIntermediate
    (hdegree : 1 < Module.finrank K L) :
    IntermediateField K L :=
  IntermediateField.fixedField
    (cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree)

noncomputable instance cyclicPrimeDegreeIntermediate_isGalois
    (hdegree : 1 < Module.finrank K L) :
    IsGalois K
      (cyclicPrimeDegreeIntermediate
        (K := K) (L := L) hdegree) := by
  unfold cyclicPrimeDegreeIntermediate
  infer_instance

theorem cyclicPrimeDegreeIntermediate_finrank
    (hdegree : 1 < Module.finrank K L) :
    Module.finrank K
        (cyclicPrimeDegreeIntermediate
          (K := K) (L := L) hdegree) =
      cyclicDegreePrime (K := K) (L := L) hdegree := by
  let P :=
    cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree
  let M :=
    cyclicPrimeDegreeIntermediate
      (K := K) (L := L) hdegree
  let : P.Normal :=
    cyclicPrimeDegreeSubgroup_normal
      (K := K) (L := L) hdegree
  let : IsGalois K M :=
    cyclicPrimeDegreeIntermediate_isGalois
      (K := K) (L := L) hdegree
  calc
    Module.finrank K M =
        Nat.card (M ≃ₐ[K] M) :=
      (IsGalois.card_aut_eq_finrank K M).symm
    _ = Nat.card (G ⧸ P) :=
      Nat.card_congr
        (IsGalois.normalAutEquivQuotient P).symm.toEquiv
    _ = P.index := by
      rw [P.index_eq_card]
    _ = cyclicDegreePrime (K := K) (L := L) hdegree :=
      cyclicPrimeDegreeSubgroup_index
        (K := K) (L := L) hdegree

theorem cyclicPrimeDegreeIntermediate_top_finrank
    (hdegree : 1 < Module.finrank K L) :
    Module.finrank
        (cyclicPrimeDegreeIntermediate
          (K := K) (L := L) hdegree)
        L =
      Module.finrank K L /
        cyclicDegreePrime (K := K) (L := L) hdegree := by
  unfold cyclicPrimeDegreeIntermediate
  rw [IntermediateField.finrank_fixedField_eq_card,
    cyclicPrimeDegreeSubgroup_card]

noncomputable instance cyclicPrimeDegreeIntermediate_top_isGalois
    (hdegree : 1 < Module.finrank K L) :
    IsGalois
      (cyclicPrimeDegreeIntermediate
        (K := K) (L := L) hdegree)
      L := by
  unfold cyclicPrimeDegreeIntermediate
  exact
    IsGalois.of_fixed_field L
      (cyclicPrimeDegreeSubgroup
        (K := K) (L := L) hdegree)

noncomputable instance cyclicPrimeDegreeIntermediate_base_isCyclic
    (hdegree : 1 < Module.finrank K L) :
    IsCyclic
      (cyclicPrimeDegreeIntermediate
          (K := K) (L := L) hdegree ≃ₐ[K]
        cyclicPrimeDegreeIntermediate
          (K := K) (L := L) hdegree) := by
  let P :=
    cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree
  let : P.Normal :=
    cyclicPrimeDegreeSubgroup_normal
      (K := K) (L := L) hdegree
  exact
    (IsGalois.normalAutEquivQuotient P).isCyclic.mp
      (isCyclic_of_surjective
        (QuotientGroup.mk' P)
        (QuotientGroup.mk'_surjective P))

noncomputable instance cyclicPrimeDegreeIntermediate_top_isCyclic
    (hdegree : 1 < Module.finrank K L) :
    IsCyclic
      (L ≃ₐ[
        cyclicPrimeDegreeIntermediate
          (K := K) (L := L) hdegree] L) := by
  let P :=
    cyclicPrimeDegreeSubgroup
      (K := K) (L := L) hdegree
  exact
    (IntermediateField.subgroupEquivAlgEquiv P).isCyclic.mp
      (inferInstance : IsCyclic P)
