import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.Construction.MainFiniteReciprocity

set_option autoImplicit false

universe u

namespace ClassFormation

open KummerTheory

open CyclicCohomology

open CategoryTheory


/-!
# The abstract reciprocity construction, norm--conjugation naturality: naturality of reciprocity

The two vertical maps are constructed here on the actual finite
Galois quotients and the actual finite norm quotients.  Their defining
commutativities are proved from norm transitivity and conjugation, so the
eventual the finite reciprocity equivalence reciprocity homomorphisms can be connected without
any additional comparison datum.
-/

noncomputable section

open scoped BigOperators

section GroupOnly

variable {G : Type u} [Group G] [TopologicalSpace G]

/-- The left vertical map in the first diagram of norm--conjugation naturality:
restriction from `G(L'/K')` to `G(L/K)`. -/
def finiteReciprocityNaturalityRestriction
    (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup K L hLK).Normal]
    [hL'normal : (extensionSubgroup K' L' hL'K').Normal] :
    (K'.toSubgroup ⧸ extensionSubgroup K' L' hL'K') →*
      (K.toSubgroup ⧸ extensionSubgroup K L hLK) := by
  apply QuotientGroup.map
    (extensionSubgroup K' L' hL'K')
    (extensionSubgroup K L hLK)
    (Subgroup.inclusion hK'K)
  intro k' hk'L'
  change k'.1 ∈ L'.toSubgroup at hk'L'
  change (Subgroup.inclusion hK'K k').1 ∈ L.toSubgroup
  exact hL'L hk'L'

/-- Restriction sends a represented finite reciprocity class to the corresponding
lower-level class. -/
@[simp]
theorem finiteReciprocityNaturalityRestriction_mk
    (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup K L hLK).Normal]
    [hL'normal : (extensionSubgroup K' L' hL'K').Normal]
    (k' : K'.toSubgroup) :
    finiteReciprocityNaturalityRestriction K K' L L' hLK hL'K' hK'K hL'L
        (QuotientGroup.mk k') =
      QuotientGroup.mk (Subgroup.inclusion hK'K k') :=
  rfl

namespace DegreeData

/-- Restriction on the infinite Frobenius quotients underlying the first
diagram of norm--conjugation naturality. -/
def finiteReciprocityNaturalityFrobeniusTowerMap
    (D : DegreeData G) [IsTopologicalGroup G]
    (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup K L hLK).Normal]
    [hL'normal : (extensionSubgroup K' L' hL'K').Normal] :
    (K'.toSubgroup ⧸ D.extensionInertiaWithin K' L' hL'K') →*
      (K.toSubgroup ⧸ D.extensionInertiaWithin K L hLK) := by
  apply QuotientGroup.map
    (D.extensionInertiaWithin K' L' hL'K')
    (D.extensionInertiaWithin K L hLK)
    (Subgroup.inclusion hK'K)
  rintro k' ⟨hk'L', hk'I⟩
  constructor
  · change k'.1 ∈ L'.toSubgroup at hk'L'
    change (Subgroup.inclusion hK'K k').1 ∈ L.toSubgroup
    exact hL'L hk'L'
  · exact hk'I

/-- The Frobenius tower map has the expected value on a quotient representative. -/
@[simp]
theorem finiteReciprocityNaturalityFrobeniusTowerMap_mk
    (D : DegreeData G) [IsTopologicalGroup G]
    (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup K L hLK).Normal]
    [hL'normal : (extensionSubgroup K' L' hL'K').Normal]
    (k' : K'.toSubgroup) :
    D.finiteReciprocityNaturalityFrobeniusTowerMap K K' L L'
        hLK hL'K' hK'K hL'L (QuotientGroup.mk k') =
      QuotientGroup.mk (Subgroup.inclusion hK'K k') := rfl

/-- Continuous form of `finiteReciprocityNaturalityFrobeniusTowerMap`, used to transport
the closed cyclic subgroup generated by a Frobenius lift. -/
def finiteReciprocityNaturalityFrobeniusTowerMapContinuous
    (D : DegreeData G) [IsTopologicalGroup G]
    (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup K L hLK).Normal]
    [hL'normal : (extensionSubgroup K' L' hL'K').Normal] :
    (K'.toSubgroup ⧸ D.extensionInertiaWithin K' L' hL'K') →ₜ*
      (K.toSubgroup ⧸ D.extensionInertiaWithin K L hLK) where
  toMonoidHom := D.finiteReciprocityNaturalityFrobeniusTowerMap
    K K' L L' hLK hL'K' hK'K hL'L
  continuous_toFun := by
    rw [← QuotientGroup.isOpenQuotientMap_mk.continuous_comp_iff]
    change Continuous (fun k' : K'.toSubgroup =>
      QuotientGroup.mk (Subgroup.inclusion hK'K k'))
    apply QuotientGroup.continuous_mk.comp
    exact continuous_subtype_val.subtype_mk _

/-- Frobenius residue-degree compatibility's normalized-degree square on the two infinite
Frobenius quotients. -/
theorem finiteReciprocityNaturalityFrobeniusTowerMap_degree
    (D : DegreeData G) [IsTopologicalGroup G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    (q : E.field.toSubgroup ⧸
      D.extensionInertiaWithin E.field.field L' hL'K') :
    (D.extensionNormalizedDegree E.base L hLK
      (D.finiteReciprocityNaturalityFrobeniusTowerMap
        E.base.field E.field.field L L'
        hLK hL'K' E.below hL'L q)).toAdd =
      (E.residueDegree : ℕ) •
        (D.extensionNormalizedDegree E.field L' hL'K' q).toAdd := by
  refine Quotient.inductionOn' q ?_
  intro k'
  change (D.normalizedDegree E.base (Subgroup.inclusion E.below k')).toAdd =
    (E.residueDegree : ℕ) • (D.normalizedDegree E.field k').toAdd
  exact D.frobeniusRestrictionNaturality_normalizedDegree E k'

/-- A positive Frobenius lift over `K'` remains a positive Frobenius lift
over `K`; its exponent is multiplied by `f_{K'/K}`. -/
def finiteReciprocityNaturalityFrobeniusTowerLift
    (D : DegreeData G) [IsTopologicalGroup G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    (σ : D.FrobeniusElements E.field L' hL'K') :
    D.FrobeniusElements E.base L hLK := by
  let f := (E.residueDegree : ℕ)
  let n := D.frobeniusExponent E.field L' hL'K' σ
  refine ⟨D.finiteReciprocityNaturalityFrobeniusTowerMap
      E.base.field E.field.field L L' hLK hL'K' E.below hL'L σ.1,
    f * n, Nat.mul_pos E.residueDegree.property
      (D.frobeniusExponent_pos E.field L' hL'K' σ), ?_⟩
  apply Multiplicative.ext
  rw [D.finiteReciprocityNaturalityFrobeniusTowerMap_degree E L L'
    hLK hL'K' hL'L σ.1]
  rw [D.extensionNormalizedDegree_frobenius_eq_pow E.field L' hL'K' σ]
  change f • (n • (1 : ZHat)) = (f * n) • (1 : ZHat)
  rw [smul_smul]

/-- The chosen Frobenius tower lift coerces to the represented ambient automorphism. -/
@[simp]
theorem finiteReciprocityNaturalityFrobeniusTowerLift_coe
    (D : DegreeData G) [IsTopologicalGroup G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    (σ : D.FrobeniusElements E.field L' hL'K') :
    (D.finiteReciprocityNaturalityFrobeniusTowerLift
      E L L' hLK hL'K' hL'L σ).1 =
      D.finiteReciprocityNaturalityFrobeniusTowerMap
        E.base.field E.field.field L L' hLK hL'K' E.below hL'L σ.1 := by
  simp [finiteReciprocityNaturalityFrobeniusTowerLift]

/-- The Frobenius tower lift has the prescribed Frobenius exponent. -/
@[simp]
theorem finiteReciprocityNaturalityFrobeniusTowerLift_exponent
    (D : DegreeData G) [IsTopologicalGroup G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    (σ : D.FrobeniusElements E.field L' hL'K') :
    D.frobeniusExponent E.base L hLK
        (D.finiteReciprocityNaturalityFrobeniusTowerLift
          E L L' hLK hL'K' hL'L σ) =
      (E.residueDegree : ℕ) *
        D.frobeniusExponent E.field L' hL'K' σ := by
  apply proCIntegerOne_pow_nat_injective
  let f := (E.residueDegree : ℕ)
  let n := D.frobeniusExponent E.field L' hL'K' σ
  calc
    (Multiplicative.ofAdd (1 : ZHat)) ^
        D.frobeniusExponent E.base L hLK
          (D.finiteReciprocityNaturalityFrobeniusTowerLift
            E L L' hLK hL'K' hL'L σ) =
      D.extensionNormalizedDegree E.base L hLK
        (D.finiteReciprocityNaturalityFrobeniusTowerLift
          E L L' hLK hL'K' hL'L σ).1 :=
      (D.extensionNormalizedDegree_frobenius_eq_pow E.base L hLK _).symm
    _ = (Multiplicative.ofAdd (1 : ZHat)) ^ (f * n) := by
      apply Multiplicative.ext
      rw [D.finiteReciprocityNaturalityFrobeniusTowerLift_coe]
      rw [D.finiteReciprocityNaturalityFrobeniusTowerMap_degree E L L'
        hLK hL'K' hL'L σ.1]
      rw [D.extensionNormalizedDegree_frobenius_eq_pow
        E.field L' hL'K' σ]
      change f • (n • (1 : ZHat)) = (f * n) • (1 : ZHat)
      rw [smul_smul]
    _ = (Multiplicative.ofAdd (1 : ZHat)) ^
        ((E.residueDegree : ℕ) *
          D.frobeniusExponent E.field L' hL'K' σ) := by rfl

/-- Restriction of the transported lift is the restriction of the original
lift along the left vertical map of norm--conjugation naturality. -/
theorem finiteReciprocityNaturalityRestriction_frobeniusTowerLift
    (D : DegreeData G) [IsTopologicalGroup G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    (σ : D.FrobeniusElements E.field L' hL'K') :
    finiteReciprocityNaturalityRestriction
        E.base.field E.field.field L L' hLK hL'K' E.below hL'L
        (D.frobeniusRestriction E.field L' hL'K' σ) =
      D.frobeniusRestriction E.base L hLK
        (D.finiteReciprocityNaturalityFrobeniusTowerLift
          E L L' hLK hL'K' hL'L σ) := by
  change finiteReciprocityNaturalityRestriction
      E.base.field E.field.field L L' hLK hL'K' E.below hL'L
      (D.extensionRestriction E.field.field L' hL'K' σ.1) =
    D.extensionRestriction E.base.field L hLK
      (D.finiteReciprocityNaturalityFrobeniusTowerLift
        E L L' hLK hL'K' hL'L σ).1
  rw [D.finiteReciprocityNaturalityFrobeniusTowerLift_coe]
  refine Quotient.inductionOn' σ.1 ?_
  intro k'
  rfl

/-- The fixed field of a transported Frobenius lift contains the original
fixed field, i.e. `Σ' / Σ` is an intermediate extension. -/
theorem finiteReciprocityNaturalityFrobeniusFixedField_le
    (D : DegreeData G) [IsTopologicalGroup G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    (σ : D.FrobeniusElements E.field L' hL'K') :
    (D.frobeniusFixedField E.field L' hL'K' σ).toSubgroup ≤
      (D.frobeniusFixedField E.base L hLK
        (D.finiteReciprocityNaturalityFrobeniusTowerLift
          E L L' hLK hL'K' hL'L σ)).toSubgroup := by
  rintro g ⟨k', hk', rfl⟩
  let k : E.base.field.toSubgroup := Subgroup.inclusion E.below k'
  refine ⟨k, ?_, rfl⟩
  change QuotientGroup.mk k ∈
    (D.frobeniusClosure E.base L hLK
      (D.finiteReciprocityNaturalityFrobeniusTowerLift
        E L L' hLK hL'K' hL'L σ)).toSubgroup
  change QuotientGroup.mk k' ∈
    (D.frobeniusClosure E.field L' hL'K' σ).toSubgroup at hk'
  have hmap := map_mem_closedSubgroupGenerated_singleton
    (D.finiteReciprocityNaturalityFrobeniusTowerMapContinuous
      E.base.field E.field.field L L' hLK hL'K' E.below hL'L) σ.1 (by
        simpa [DegreeData.frobeniusClosure] using hk')
  let f := D.finiteReciprocityNaturalityFrobeniusTowerMap
    E.base.field E.field.field L L' hLK hL'K' E.below hL'L
  change f (QuotientGroup.mk k') ∈
    (closedSubgroupGenerated ({f σ.1} : Set _) : Subgroup _) at hmap
  simp [DegreeData.frobeniusClosure]
  change f (QuotientGroup.mk k') ∈
    (closedSubgroupGenerated ({f σ.1} : Set _) : Subgroup _)
  exact hmap

/-- The intermediate extension `Σ' / Σ` attached to a transported
Frobenius lift is totally ramified. -/
theorem finiteReciprocityNaturalityFrobeniusFixedField_isTotallyRamified
    (D : DegreeData G) [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (E : DegreeData.FiniteResidueAbstractExtension D)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    [Finite
      (E.base.toSubgroup ⧸ extensionSubgroup E.base.field L hLK)]
    [hL'K'finite : Finite
      (E.field.toSubgroup ⧸ extensionSubgroup E.field.field L' hL'K')]
    (σ : D.FrobeniusElements E.field L' hL'K') :
    (DegreeData.AbstractExtension.mk
      (D.frobeniusFixedField E.field L' hL'K' σ)
      (D.frobeniusFixedField E.base L hLK
        (D.finiteReciprocityNaturalityFrobeniusTowerLift
          E L L' hLK hL'K' hL'L σ))
      (D.finiteReciprocityNaturalityFrobeniusFixedField_le
        E L L' hLK hL'K' hL'L σ)).IsTotallyRamified D := by
  let τ := D.finiteReciprocityNaturalityFrobeniusTowerLift
    E L L' hLK hL'K' hL'L σ
  let S' := D.frobeniusFixedField E.field L' hL'K' σ
  let S := D.frobeniusFixedField E.base L hLK τ
  let hS'S := D.finiteReciprocityNaturalityFrobeniusFixedField_le
    E L L' hLK hL'K' hL'L σ
  let FS := D.frobeniusFixedResidueField E.base L hLK τ
  let FS' := D.frobeniusFixedResidueField E.field L' hL'K' σ
  have hresidue : (FS.residueDegree : ℕ) = (FS'.residueDegree : ℕ) := by
    calc
      (FS.residueDegree : ℕ) =
          D.frobeniusExponent E.base L hLK τ *
            (E.base.residueDegree : ℕ) :=
        D.frobeniusFixedResidueField_residueDegree E.base L hLK τ
      _ = ((E.residueDegree : ℕ) *
            D.frobeniusExponent E.field L' hL'K' σ) *
          (E.base.residueDegree : ℕ) := by
        rw [D.finiteReciprocityNaturalityFrobeniusTowerLift_exponent]
      _ = D.frobeniusExponent E.field L' hL'K' σ *
          ((E.residueDegree : ℕ) * (E.base.residueDegree : ℕ)) := by
        ac_rfl
      _ = D.frobeniusExponent E.field L' hL'K' σ *
          (E.field.residueDegree : ℕ) := by
        rw [E.residueDegree_mul_absoluteResidueDegree D]
      _ = (FS'.residueDegree : ℕ) :=
        (D.frobeniusFixedResidueField_residueDegree E.field L' hL'K' σ).symm
  let hS'K' := D.frobeniusFixedField_le E.field L' hL'K' σ
  let hSK := D.frobeniusFixedField_le E.base L hLK τ
  let : Finite (E.field.toSubgroup ⧸
      extensionSubgroup E.field.field S' hS'K') :=
    D.frobeniusFixedField_finite E.field L' hL'K' σ
  let : Finite (E.base.toSubgroup ⧸
      extensionSubgroup E.base.field S hSK) :=
    D.frobeniusFixedField_finite E.base L hLK τ
  let : Finite (E.base.toSubgroup ⧸
      extensionSubgroup E.base.field S' (hS'K'.trans E.below)) :=
    relativeTowerQuotientFinite E.base.field E.field.field S' hS'K' E.below
  let hS'Sfinite : Finite
      (S.toSubgroup ⧸ extensionSubgroup S S' hS'S) :=
    FiniteIntermediateField.finite_extension_of_le
      (hS'S.trans hSK) hSK hS'S
  let ES'S : DegreeData.FiniteResidueAbstractExtension D :=
    { field := FS'
      base := FS
      below := hS'S
      finiteQuotient := hS'Sfinite }
  have hrelative : (ES'S.residueDegree : ℕ) = 1 := by
    change (ES'S.base.residueDegree : ℕ) =
      (ES'S.field.residueDegree : ℕ) at hresidue
    have hmul := ES'S.residueDegree_mul_absoluteResidueDegree D
    rw [← hresidue] at hmul
    have hpos : 0 < (ES'S.base.residueDegree : ℕ) :=
      ES'S.base.residueDegree.property
    nlinarith
  exact ES'S.toFiniteAbstractExtension.isTotallyRamified_of_residueDegree_eq_one
    D hrelative

end DegreeData

/-- Finiteness of the upper-left-to-lower-right composite extension in the
first diagram. -/
private theorem finiteReciprocityNaturality_tower_finite
    (K K' L' : ClosedSubgroup G)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    [Finite (K.toSubgroup ⧸ extensionSubgroup K K' hK'K)]
    [Finite (K'.toSubgroup ⧸ extensionSubgroup K' L' hL'K')] :
    Finite (K.toSubgroup ⧸
      extensionSubgroup K L' (hL'K'.trans hK'K)) :=
  relativeTowerQuotientFinite K K' L' hL'K' hK'K

end GroupOnly

section Representation

/-! Mathlib's `Rep ℤ G` forces its representation-bearing group `G` to `Type 0`. -/
variable {G : IntegralRepGroupType} [Group G] [TopologicalSpace G]

/-- The right vertical map in the first diagram of norm--conjugation naturality.  It is
the actual norm `N_{K'/K}`, descended to the actual finite norm quotients. -/
def finiteReciprocityNaturalityNormMap
    (A : Rep ℤ G) (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLKfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K L hLK)]
    [hL'K'finite : Finite
      (K'.toSubgroup ⧸ extensionSubgroup K' L' hL'K')]
    [hK'Kfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K K' hK'K)] :
    FiniteNormQuotient A K' L' hL'K' →+
      FiniteNormQuotient A K L hLK := by
  letI hL'Kfinite : Finite (K.toSubgroup ⧸
      extensionSubgroup K L' (hL'K'.trans hK'K)) :=
    finiteReciprocityNaturality_tower_finite K K' L' hK'K hL'K'
  letI hL'Lfinite : Finite
      (L.toSubgroup ⧸ extensionSubgroup L L' hL'L) :=
    FiniteIntermediateField.finite_extension_of_le
      (hL'L.trans hLK) hLK hL'L
  let f : ambientFixedAddSubgroup A K' →+ FiniteNormQuotient A K L hLK :=
    (finiteNormClassHom A K L hLK).comp (relativeNorm A K K' hK'K)
  apply finiteNormQuotientLift A K' L' hL'K' f
  rintro _ ⟨a, rfl⟩
  let TLL' : DegreeData.FiniteTower G :=
    { top := L'
      middle := L
      base := K
      top_le_middle := hL'L
      middle_le_base := hLK
      finiteTopQuotient := hL'Lfinite
      finiteBaseQuotient := hLKfinite }
  let TKK' : DegreeData.FiniteTower G :=
    { top := L'
      middle := K'
      base := K
      top_le_middle := hL'K'
      middle_le_base := hK'K
      finiteTopQuotient := hL'K'finite
      finiteBaseQuotient := hK'Kfinite }
  apply (finiteNormClass_eq_zero_iff A K L hLK _).2
  refine ⟨relativeNorm A L L' hL'L a, ?_⟩
  calc
    relativeNorm A K L hLK (relativeNorm A L L' hL'L a) =
        relativeNorm A K L' (hL'L.trans hLK) a :=
      TLL'.norm_trans_apply A a
    _ = relativeNorm A K L' (hL'K'.trans hK'K) a := by
      congr 2
    _ = relativeNorm A K K' hK'K (relativeNorm A K' L' hL'K' a) :=
      (TKK'.norm_trans_apply A a).symm

/-- The norm map carries a finite norm class to the corresponding class over the base. -/
@[simp]
theorem finiteReciprocityNaturalityNormMap_finiteNormClass
    (A : Rep ℤ G) (K K' L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLKfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K L hLK)]
    [Finite
      (K'.toSubgroup ⧸ extensionSubgroup K' L' hL'K')]
    [hK'Kfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K K' hK'K)]
    (a : ambientFixedAddSubgroup A K') :
    finiteReciprocityNaturalityNormMap A K K' L L' hLK hL'K' hK'K hL'L
        (finiteNormClass A K' L' hL'K' a) =
      finiteNormClass A K L hLK (relativeNorm A K K' hK'K a) :=
  by
    simp [finiteReciprocityNaturalityNormMap]
    rfl

/-- The additive map `a ↦ a^s` between the two actual fixed subgroups. -/
def conjugateFixedElementHom [ContinuousMul G]
    (A : Rep ℤ G) (K : ClosedSubgroup G) (s : G) :
    ambientFixedAddSubgroup A K →+
      ambientFixedAddSubgroup A (conjugateClosedSubgroup K s) where
  toFun := conjugateFixedElement A K s
  map_zero' := by
    apply Subtype.ext
    exact map_zero (A.ρ s⁻¹)
  map_add' a b := by
    apply Subtype.ext
    exact map_add (A.ρ s⁻¹) a.1 b.1

/-- The homomorphism on conjugate-fixed elements evaluates by the underlying conjugation map. -/
@[simp]
theorem conjugateFixedElementHom_apply [ContinuousMul G]
    (A : Rep ℤ G) (K : ClosedSubgroup G) (s : G)
    (a : ambientFixedAddSubgroup A K) :
    conjugateFixedElementHom A K s a = conjugateFixedElement A K s a :=
  rfl

/-- The right vertical map in the conjugation diagram of norm--conjugation naturality,
descended to the actual finite norm quotients. -/
def finiteReciprocityNaturalityConjugationNormMap
    [ContinuousMul G] (A : Rep ℤ G)
    (K L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup) (s : G)
    [hLfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K L hLK)] :
    letI : Finite ((conjugateClosedSubgroup K s).toSubgroup ⧸
        extensionSubgroup (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) :=
      finite_conjugateExtension K L hLK s
    FiniteNormQuotient A K L hLK →+
      FiniteNormQuotient A (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s) := by
  letI hConjFinite : Finite ((conjugateClosedSubgroup K s).toSubgroup ⧸
      extensionSubgroup (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)) :=
    finite_conjugateExtension K L hLK s
  let f : ambientFixedAddSubgroup A K →+
      FiniteNormQuotient A (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s) :=
    (finiteNormClassHom A (conjugateClosedSubgroup K s)
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).comp
        (conjugateFixedElementHom A K s)
  apply finiteNormQuotientLift A K L hLK f
  rintro _ ⟨a, rfl⟩
  apply (finiteNormClass_eq_zero_iff A (conjugateClosedSubgroup K s)
    (conjugateClosedSubgroup L s) (conjugateClosedSubgroup_mono hLK s) _).2
  refine ⟨conjugateFixedElement A L s a, ?_⟩
  exact relativeNorm_conjugate_apply A K L hLK s a

/-- The conjugation norm map preserves canonical finite norm classes. -/
@[simp]
theorem finiteReciprocityNaturalityConjugationNormMap_finiteNormClass
    [ContinuousMul G] (A : Rep ℤ G)
    (K L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup) (s : G)
    [Finite (K.toSubgroup ⧸ extensionSubgroup K L hLK)]
    (a : ambientFixedAddSubgroup A K) :
    letI : Finite ((conjugateClosedSubgroup K s).toSubgroup ⧸
        extensionSubgroup (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) :=
      finite_conjugateExtension K L hLK s
    finiteReciprocityNaturalityConjugationNormMap A K L hLK s
        (finiteNormClass A K L hLK a) =
      finiteNormClass A (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s) (conjugateClosedSubgroup_mono hLK s)
        (conjugateFixedElement A K s a) := by
  let hConjFinite : Finite ((conjugateClosedSubgroup K s).toSubgroup ⧸
      extensionSubgroup (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)) :=
    finite_conjugateExtension K L hLK s
  simp [finiteReciprocityNaturalityConjugationNormMap]
  rfl

/-- The norm identity used for the first diagram of norm--conjugation naturality,
already expressed in the target finite norm quotient.  Taking `S = Σ` and
`S' = Σ'` gives the calculation. -/
theorem finiteReciprocityNaturality_norm_tower_class
    (A : Rep ℤ G)
    (K K' L L' S S' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ K'.toSubgroup)
    (hK'K : K'.toSubgroup ≤ K.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    (hSK : S.toSubgroup ≤ K.toSubgroup)
    (hS'K' : S'.toSubgroup ≤ K'.toSubgroup)
    (hS'S : S'.toSubgroup ≤ S.toSubgroup)
    [hLKfinite : Finite (K.toSubgroup ⧸ extensionSubgroup K L hLK)]
    [hL'K'finite : Finite (K'.toSubgroup ⧸ extensionSubgroup K' L' hL'K')]
    [hK'Kfinite : Finite (K.toSubgroup ⧸ extensionSubgroup K K' hK'K)]
    [hSKfinite : Finite (K.toSubgroup ⧸ extensionSubgroup K S hSK)]
    [hS'K'finite : Finite (K'.toSubgroup ⧸ extensionSubgroup K' S' hS'K')]
    [hS'Sfinite : Finite (S.toSubgroup ⧸ extensionSubgroup S S' hS'S)]
    (π : ambientFixedAddSubgroup A S') :
    finiteReciprocityNaturalityNormMap A K K' L L' hLK hL'K' hK'K hL'L
        (finiteNormClass A K' L' hL'K'
          (relativeNorm A K' S' hS'K' π)) =
      finiteNormClass A K L hLK
        (relativeNorm A K S hSK (relativeNorm A S S' hS'S π)) := by
  let hS'Kfinite : Finite (K.toSubgroup ⧸
      extensionSubgroup K S' (hS'K'.trans hK'K)) :=
    finiteReciprocityNaturality_tower_finite K K' S' hK'K hS'K'
  let TKK' : DegreeData.FiniteTower G :=
    { top := S'
      middle := K'
      base := K
      top_le_middle := hS'K'
      middle_le_base := hK'K
      finiteTopQuotient := hS'K'finite
      finiteBaseQuotient := hK'Kfinite }
  let TSS' : DegreeData.FiniteTower G :=
    { top := S'
      middle := S
      base := K
      top_le_middle := hS'S
      middle_le_base := hSK
      finiteTopQuotient := hS'Sfinite
      finiteBaseQuotient := hSKfinite }
  rw [finiteReciprocityNaturalityNormMap_finiteNormClass]
  apply congrArg (finiteNormClass A K L hLK)
  calc
    relativeNorm A K K' hK'K (relativeNorm A K' S' hS'K' π) =
        relativeNorm A K S' (hS'K'.trans hK'K) π :=
      TKK'.norm_trans_apply A π
    _ = relativeNorm A K S' (hS'S.trans hSK) π := by
      congr 2
    _ = relativeNorm A K S hSK (relativeNorm A S S' hS'S π) :=
      (TSS'.norm_trans_apply A π).symm

namespace DegreeData

/-- **norm--conjugation naturality, first diagram.** Restriction on finite Galois groups
corresponds under the finite reciprocity equivalence to the norm `N_{K'/K}` on finite norm
quotients. -/
theorem finiteReciprocityNaturality_restriction_norm_commutes
    (D : DegreeData G) (A : Rep ℤ G) (v : ValuationData D A)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (hAxiom : v.SatisfiesUnramifiedUnitCohomology D)
    (E : FiniteAbstractFieldExtension G)
    (L L' : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ E.base.field.toSubgroup)
    (hL'K' : L'.toSubgroup ≤ E.field.field.toSubgroup)
    (hL'L : L'.toSubgroup ≤ L.toSubgroup)
    [hLnormal : (extensionSubgroup E.base.field L hLK).Normal]
    [hL'normal : (extensionSubgroup E.field.field L' hL'K').Normal]
    [hLKfinite : Finite
      (E.base.field.toSubgroup ⧸ extensionSubgroup E.base.field L hLK)]
    [hL'K'finite : Finite
      (E.field.field.toSubgroup ⧸
        extensionSubgroup E.field.field L' hL'K')] :
    (finiteReciprocityNaturalityNormMap A E.base.field E.field.field L L'
      hLK hL'K' E.below hL'L).comp
        (D.finiteReciprocityHom A v hAxiom E.field L' hL'K') =
      (D.finiteReciprocityHom A v hAxiom E.base L hLK).comp
      (finiteReciprocityNaturalityRestriction
          E.base.field E.field.field L L'
          hLK hL'K' E.below hL'L).toAdditive := by
  let ER := E.toFiniteResidueAbstractExtension D
  let hL'K'finiteER : Finite
      (ER.field.field.toSubgroup ⧸
        extensionSubgroup ER.field.field L' hL'K') := by
    change Finite
      (ER.field.field.toSubgroup ⧸
        extensionSubgroup ER.field.field L' hL'K') at hL'K'finite
    exact hL'K'finite
  let hLKfiniteER : Finite
      (ER.base.field.toSubgroup ⧸
        extensionSubgroup ER.base.field L hLK) := by
    change Finite
      (ER.base.field.toSubgroup ⧸
        extensionSubgroup ER.base.field L hLK) at hLKfinite
    exact hLKfinite
  let hLnormalERbase :
      (extensionSubgroup ER.base.field L hLK).Normal := by
    change (extensionSubgroup ER.base.field L hLK).Normal at hLnormal
    exact hLnormal
  let hL'normalERfield :
      (extensionSubgroup ER.field.field L' hL'K').Normal := by
    change (extensionSubgroup ER.field.field L' hL'K').Normal at hL'normal
    exact hL'normal
  apply AddMonoidHom.ext
  intro q
  let σ := D.chosenFiniteReciprocityFrobeniusLift ER.field L' hL'K' q.toMul
  let τ := D.finiteReciprocityNaturalityFrobeniusTowerLift
    ER L L' hLK hL'K' hL'L σ
  have hσ : D.frobeniusRestriction ER.field L' hL'K' σ = q.toMul :=
    D.frobeniusRestriction_chosenFiniteReciprocityFrobeniusLift
      ER.field L' hL'K' q.toMul
  have hτ : D.frobeniusRestriction ER.base L hLK τ =
      ((finiteReciprocityNaturalityRestriction
        E.base.field E.field.field L L'
        hLK hL'K' E.below hL'L).toAdditive q).toMul := by
    rw [← D.finiteReciprocityNaturalityRestriction_frobeniusTowerLift
      ER L L' hLK hL'K' hL'L σ, hσ]
    rfl
  let S' := D.frobeniusFixedField ER.field L' hL'K' σ
  let S := D.frobeniusFixedField ER.base L hLK τ
  let hS'K' := D.frobeniusFixedField_le ER.field L' hL'K' σ
  let hSK := D.frobeniusFixedField_le ER.base L hLK τ
  let hS'S := D.finiteReciprocityNaturalityFrobeniusFixedField_le
    ER L L' hLK hL'K' hL'L σ
  let hS'K'finite : Finite
      (E.field.field.toSubgroup ⧸
        extensionSubgroup E.field.field S' hS'K') :=
    D.frobeniusFixedField_finite ER.field L' hL'K' σ
  let hSKfinite : Finite
      (E.base.field.toSubgroup ⧸
        extensionSubgroup E.base.field S hSK) :=
    D.frobeniusFixedField_finite ER.base L hLK τ
  let hS'Kfinite : Finite
      (E.base.field.toSubgroup ⧸
        extensionSubgroup E.base.field S' (hS'K'.trans E.below)) :=
    finiteReciprocityNaturality_tower_finite
      E.base.field E.field.field S' E.below hS'K'
  let hS'Sfinite : Finite
      (S.toSubgroup ⧸ extensionSubgroup S S' hS'S) :=
    FiniteIntermediateField.finite_extension_of_le
      (K := E.base.field) (hS'S.trans hSK) hSK hS'S
  let hSabsolute : Finite ((baseField G).toSubgroup ⧸
      extensionSubgroup (baseField G) S (le_baseField S)) :=
    D.frobeniusFixedField_absoluteFinite E.base L hLK τ
  let hS'absolute : Finite ((baseField G).toSubgroup ⧸
      extensionSubgroup (baseField G) S' (le_baseField S')) :=
    D.frobeniusFixedField_absoluteFinite E.field L' hL'K' σ
  let Sfinite : FiniteAbstractField G := ⟨S, hSabsolute⟩
  let S'finite : FiniteAbstractField G := ⟨S', hS'absolute⟩
  let ES'S : FiniteAbstractFieldExtension G :=
    { field := S'finite
      base := Sfinite
      below := hS'S
      finiteQuotient := hS'Sfinite }
  let π : ambientFixedAddSubgroup A S' := v.chosenPrimeElement S'finite
  have hπ : v.IsPrimeElement S'finite π := v.chosenPrimeElement_isPrime S'finite
  let πS : ambientFixedAddSubgroup A S := relativeNorm A S S' hS'S π
  have hTot : ES'S.IsTotallyRamified D := by
    have hTot' :=
      D.finiteReciprocityNaturalityFrobeniusFixedField_isTotallyRamified
        ER L L' hLK hL'K' hL'L σ
    change ES'S.IsTotallyRamified D at hTot'
    exact hTot'
  have hπS : v.IsPrimeElement Sfinite πS :=
    v.norm_prime_of_totallyRamified ES'S hTot π hπ
  change finiteReciprocityNaturalityNormMap
      A E.base.field E.field.field L L' hLK hL'K' E.below hL'L
      (D.finiteReciprocityHom A v hAxiom E.field L' hL'K' q) =
    D.finiteReciprocityHom A v hAxiom E.base L hLK
      ((finiteReciprocityNaturalityRestriction
        E.base.field E.field.field L L'
        hLK hL'K' E.below hL'L).toAdditive q)
  calc
    finiteReciprocityNaturalityNormMap
        A E.base.field E.field.field L L' hLK hL'K' E.below hL'L
        (D.finiteReciprocityHom A v hAxiom E.field L' hL'K' q) =
      finiteReciprocityNaturalityNormMap
        A E.base.field E.field.field L L' hLK hL'K' E.below hL'L
        (finiteNormClass A E.field.field L' hL'K'
          (relativeNorm A E.field.field S' hS'K' π)) := by
      apply congrArg (finiteReciprocityNaturalityNormMap
        A E.base.field E.field.field L L' hLK hL'K' E.below hL'L)
      have hprime :=
        D.finiteReciprocityHom_apply_eq_primeNormClass
          A v hAxiom E.field L' hL'K' q σ hσ π hπ
      change D.finiteReciprocityHom A v hAxiom E.field L' hL'K' q =
        finiteNormClass A E.field.field L' hL'K'
          (relativeNorm A E.field.field S' hS'K' π) at hprime
      exact hprime
    _ = finiteNormClass A E.base.field L hLK
        (relativeNorm A E.base.field S hSK πS) := by
      exact finiteReciprocityNaturality_norm_tower_class
        A E.base.field E.field.field L L' S S'
        hLK hL'K' E.below hL'L hSK hS'K' hS'S π
    _ = D.finiteReciprocityHom A v hAxiom E.base L hLK
        ((finiteReciprocityNaturalityRestriction
          E.base.field E.field.field L L'
          hLK hL'K' E.below hL'L).toAdditive q) := by
      symm
      have hprime :=
        D.finiteReciprocityHom_apply_eq_primeNormClass
          A v hAxiom E.base L hLK _ τ hτ πS hπS
      change D.finiteReciprocityHom A v hAxiom E.base L hLK _ =
        finiteNormClass A E.base.field L hLK
          (relativeNorm A E.base.field S hSK πS) at hprime
      exact hprime

end DegreeData

/-- The norm identity used for the second diagram of norm--conjugation naturality,
expressed in the conjugate finite norm quotient. -/
theorem finiteReciprocityNaturality_conjugation_norm_class
    [ContinuousMul G] (A : Rep ℤ G)
    (K L S : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (hSK : S.toSubgroup ≤ K.toSubgroup) (s : G)
    [Finite (K.toSubgroup ⧸ extensionSubgroup K L hLK)]
    [Finite (K.toSubgroup ⧸ extensionSubgroup K S hSK)]
    (π : ambientFixedAddSubgroup A S) :
    let hConjLK := conjugateClosedSubgroup_mono hLK s
    let hConjSK := conjugateClosedSubgroup_mono hSK s
    letI : Finite ((conjugateClosedSubgroup K s).toSubgroup ⧸
        extensionSubgroup (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup L s) hConjLK) :=
      finite_conjugateExtension K L hLK s
    letI : Finite ((conjugateClosedSubgroup K s).toSubgroup ⧸
        extensionSubgroup (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup S s) hConjSK) :=
      finite_conjugateExtension K S hSK s
    finiteReciprocityNaturalityConjugationNormMap A K L hLK s
        (finiteNormClass A K L hLK
          (relativeNorm A K S hSK π)) =
      finiteNormClass A (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s) hConjLK
        (relativeNorm A (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup S s) hConjSK
          (conjugateFixedElement A S s π)) := by
  dsimp only
  rw [finiteReciprocityNaturalityConjugationNormMap_finiteNormClass,
    relativeNorm_conjugate_apply]

end Representation

section GroupOnly

variable {G : Type u} [Group G] [TopologicalSpace G]

namespace DegreeData

/-- The global degree is invariant under conjugation. -/
theorem finiteReciprocityNaturalityDegree_conjugateSubgroupEquiv
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : ClosedSubgroup G) (s : G) (k : K.toSubgroup) :
    D.degree (conjugateSubgroupEquiv K s k).1 = D.degree k.1 := by
  rw [conjugateSubgroupEquiv_apply_coe, map_mul, map_mul, map_inv]
  simp [mul_comm]

/-- The normalized degree is invariant under the conjugation equivalence
of field subgroups. -/
theorem finiteReciprocityNaturalityNormalizedDegree_conjugateSubgroupEquiv
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (s : G)
    (k : K.field.toSubgroup) :
    D.normalizedDegree (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateSubgroupEquiv K.field s k) =
      D.normalizedDegree K k := by
  apply Multiplicative.ext
  apply zHatMulNat_injective K.residueDegree.property
  change (K.residueDegree : ℕ) •
      (D.normalizedDegree (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateSubgroupEquiv K.field s k)).toAdd =
    (K.residueDegree : ℕ) • (D.normalizedDegree K k).toAdd
  rw [D.residueDegree_nsmul_normalizedDegree K k]
  rw [← K.residueDegree_conjugate s]
  exact (D.residueDegree_nsmul_normalizedDegree
    (K.conjugate s : D.FiniteResidueAbstractField)
    (show (K.conjugate s).field.toSubgroup from
      conjugateSubgroupEquiv K.field s k)).trans
    (congrArg Multiplicative.toAdd
      (D.finiteReciprocityNaturalityDegree_conjugateSubgroupEquiv K.field s k))

/-- Conjugation carries `I_L` inside `G_K` exactly to the corresponding
inertia subgroup for `L^s / K^s`. -/
theorem finiteReciprocityNaturalityMap_extensionInertiaWithin_conjugate
    (D : DegreeData G) [IsTopologicalGroup G]
    (K L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup) (s : G) :
    (D.extensionInertiaWithin K L hLK).map
        (conjugateSubgroupEquiv K s).toMonoidHom =
      D.extensionInertiaWithin (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s) := by
  ext x
  constructor
  · rintro ⟨k, ⟨hkL, hkI⟩, rfl⟩
    constructor
    · rw [← map_extensionSubgroup_conjugate K L hLK s]
      exact ⟨k, hkL, rfl⟩
    · change conjugateSubgroupEquiv K s k ∈
        D.fieldInertiaWithin (conjugateClosedSubgroup K s)
      rw [D.mem_fieldInertiaWithin_iff,
        D.finiteReciprocityNaturalityDegree_conjugateSubgroupEquiv K s,
        ← D.mem_fieldInertiaWithin_iff]
      exact hkI
  · intro hx
    let k := (conjugateSubgroupEquiv K s).symm x
    refine ⟨k, ?_, (conjugateSubgroupEquiv K s).apply_symm_apply x⟩
    constructor
    · have hxL : x ∈ extensionSubgroup (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s) := hx.1
      rw [← map_extensionSubgroup_conjugate K L hLK s] at hxL
      rcases hxL with ⟨k', hk'L, hk'eq⟩
      have : k' = k := by
        apply (conjugateSubgroupEquiv K s).injective
        exact hk'eq.trans
          ((conjugateSubgroupEquiv K s).apply_symm_apply x).symm
      simpa [this] using hk'L
    · change k ∈ D.fieldInertiaWithin K
      rw [D.mem_fieldInertiaWithin_iff]
      rw [← D.finiteReciprocityNaturalityDegree_conjugateSubgroupEquiv K s k]
      rw [(conjugateSubgroupEquiv K s).apply_symm_apply x]
      exact (D.mem_fieldInertiaWithin_iff _ _).mp hx.2

/-- Conjugation as a continuous multiplicative equivalence on the infinite
Frobenius quotients. -/
noncomputable def finiteReciprocityNaturalityFrobeniusConjugationEquiv
    (D : DegreeData G) [IsTopologicalGroup G]
    (K L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K L hLK).Normal] :
    (K.toSubgroup ⧸ D.extensionInertiaWithin K L hLK) ≃ₜ*
      ((conjugateClosedSubgroup K s).toSubgroup ⧸
        D.extensionInertiaWithin (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) := by
  let e : (K.toSubgroup ⧸ D.extensionInertiaWithin K L hLK) ≃*
      ((conjugateClosedSubgroup K s).toSubgroup ⧸
        D.extensionInertiaWithin (conjugateClosedSubgroup K s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) :=
    QuotientGroup.congr
      (D.extensionInertiaWithin K L hLK)
      (D.extensionInertiaWithin (conjugateClosedSubgroup K s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s))
      (conjugateSubgroupEquiv K s)
      (D.finiteReciprocityNaturalityMap_extensionInertiaWithin_conjugate K L hLK s)
  refine { e with
    continuous_toFun := ?_
    continuous_invFun := ?_ }
  · rw [← QuotientGroup.isOpenQuotientMap_mk.continuous_comp_iff]
    change Continuous (fun k : K.toSubgroup =>
      QuotientGroup.mk (conjugateSubgroupEquiv K s k))
    apply QuotientGroup.continuous_mk.comp
    change Continuous (fun k : K.toSubgroup =>
      (⟨s⁻¹ * k.1 * s, by
        change s⁻¹ * k.1 * s ∈ conjugateClosedSubgroup K s
        rw [conjugateClosedSubgroup_mem]
        simp [mul_assoc]⟩ :
          (conjugateClosedSubgroup K s).toSubgroup))
    exact ((continuous_const.mul continuous_subtype_val).mul
      continuous_const).subtype_mk _
  · rw [← QuotientGroup.isOpenQuotientMap_mk.continuous_comp_iff]
    change Continuous (fun x : (conjugateClosedSubgroup K s).toSubgroup =>
      QuotientGroup.mk ((conjugateSubgroupEquiv K s).symm x))
    apply QuotientGroup.continuous_mk.comp
    change Continuous (fun x : (conjugateClosedSubgroup K s).toSubgroup =>
      (⟨s * x.1 * s⁻¹,
        (conjugateClosedSubgroup_mem K s x.1).mp x.2⟩ : K.toSubgroup))
    exact ((continuous_const.mul continuous_subtype_val).mul
      continuous_const).subtype_mk _

/-- The Frobenius conjugation equivalence has the expected value on quotient representatives. -/
@[simp]
theorem finiteReciprocityNaturalityFrobeniusConjugationEquiv_mk
    (D : DegreeData G) [IsTopologicalGroup G]
    (K L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup) (s : G)
    [(extensionSubgroup K L hLK).Normal]
    (k : K.toSubgroup) :
    D.finiteReciprocityNaturalityFrobeniusConjugationEquiv K L hLK s
        (QuotientGroup.mk k) =
      QuotientGroup.mk (conjugateSubgroupEquiv K s k) := by
  exact QuotientGroup.congr_mk
    (D.extensionInertiaWithin K L hLK)
    (D.extensionInertiaWithin (conjugateClosedSubgroup K s)
      (conjugateClosedSubgroup L s) (conjugateClosedSubgroup_mono hLK s))
    (conjugateSubgroupEquiv K s)
    (D.finiteReciprocityNaturalityMap_extensionInertiaWithin_conjugate K L hLK s) k

/-- The normality transported by conjugation is exposed at the
residue-finite field boundary.  Keeping this bridge as an instance prevents
clients from unfolding the bundled conjugate merely to recover the existing
normality instance for the literal conjugate subgroup. -/
instance finiteReciprocityNaturalityFiniteResidueConjugate_normal
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal] :
    (extensionSubgroup (K.conjugate s).field
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).Normal := by
  change
    (extensionSubgroup (conjugateClosedSubgroup K.field s)
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).Normal
  infer_instance

/-- The conjugation equivalence preserves normalized degree. -/
theorem finiteReciprocityNaturalityFrobeniusConjugationEquiv_degree
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (q : K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) :
    D.extensionNormalizedDegree
        (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (D.finiteReciprocityNaturalityFrobeniusConjugationEquiv K.field L hLK s q) =
      D.extensionNormalizedDegree K L hLK q := by
  refine Quotient.inductionOn' q ?_
  intro k
  change D.normalizedDegree (K.conjugate s)
      (conjugateSubgroupEquiv K.field s k) =
    D.normalizedDegree K k
  exact D.finiteReciprocityNaturalityNormalizedDegree_conjugateSubgroupEquiv
    K s k

/-- Conjugation transports positive Frobenius lifts without changing their
exponent. -/
def finiteReciprocityNaturalityFrobeniusConjugationLift
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.FrobeniusElements (K.conjugate s : D.FiniteResidueAbstractField)
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s) := by
  let n := D.frobeniusExponent K L hLK σ
  refine ⟨D.finiteReciprocityNaturalityFrobeniusConjugationEquiv K.field L hLK s σ.1,
    n, D.frobeniusExponent_pos K L hLK σ, ?_⟩
  rw [D.finiteReciprocityNaturalityFrobeniusConjugationEquiv_degree]
  exact D.extensionNormalizedDegree_frobenius_eq_pow K L hLK σ

/-- The Frobenius conjugation lift has the stated ambient coercion. -/
@[simp]
theorem finiteReciprocityNaturalityFrobeniusConjugationLift_coe
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ).1 =
      D.finiteReciprocityNaturalityFrobeniusConjugationEquiv K.field L hLK s σ.1 := by
  rfl

/-- The Frobenius conjugation lift preserves the selected exponent. -/
@[simp]
theorem finiteReciprocityNaturalityFrobeniusConjugationLift_exponent
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusExponent (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ) =
      D.frobeniusExponent K L hLK σ := by
  apply proCIntegerOne_pow_nat_injective
  calc
    (Multiplicative.ofAdd (1 : ZHat)) ^
        D.frobeniusExponent
          (K.conjugate s : D.FiniteResidueAbstractField)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)
          (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ) =
      D.extensionNormalizedDegree
        (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ).1 :=
      (D.extensionNormalizedDegree_frobenius_eq_pow
        (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        _).symm
    _ = D.extensionNormalizedDegree K L hLK σ.1 := by
      rw [D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe,
        D.finiteReciprocityNaturalityFrobeniusConjugationEquiv_degree]
    _ = (Multiplicative.ofAdd (1 : ZHat)) ^
        D.frobeniusExponent K L hLK σ :=
      D.extensionNormalizedDegree_frobenius_eq_pow K L hLK σ

section ConjugateFrobeniusQuotients

private theorem finiteReciprocityNaturalityConjugateInertia_normal
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal] :
    (D.extensionInertiaWithin (K.conjugate s).field
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).Normal :=
  D.extensionInertiaWithin_normal
    (K.conjugate s).field (conjugateClosedSubgroup L s)
    (conjugateClosedSubgroup_mono hLK s)
    (hLnormal := D.finiteReciprocityNaturalityFiniteResidueConjugate_normal
      K L hLK s (hLnormal := hLnormal))

attribute [local instance] finiteReciprocityNaturalityConjugateInertia_normal


/-- The continuous conjugation equivalence identifies the two closed cyclic
subgroups generated by corresponding Frobenius lifts. -/
theorem finiteReciprocityNaturalityFrobeniusConjugationEquiv_mem_closure_iff
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (σ : D.FrobeniusElements K L hLK)
    (q : K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) :
    q ∈ (D.frobeniusClosure K L hLK σ).toSubgroup ↔
      D.finiteReciprocityNaturalityFrobeniusConjugationEquiv K.field L hLK s q ∈
        (D.frobeniusClosure
          (K.conjugate s : D.FiniteResidueAbstractField)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)
          (D.finiteReciprocityNaturalityFrobeniusConjugationLift
            K L hLK s σ)).toSubgroup := by
  let e := D.finiteReciprocityNaturalityFrobeniusConjugationEquiv K.field L hLK s
  constructor
  · intro hq
    have hmap := map_mem_closedSubgroupGenerated_singleton
      (ContinuousMonoidHom.toContinuousMonoidHom e) σ.1 (by
        simpa [DegreeData.frobeniusClosure] using hq)
    unfold DegreeData.frobeniusClosure
    unfold DegreeData.FiniteResidueAbstractField.conjugate
    rw [D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe]
    simpa [e] using hmap
  · intro hq
    have hq' : e q ∈ closedSubgroupGenerated {e σ.1} := by
      unfold DegreeData.frobeniusClosure at hq
      unfold DegreeData.FiniteResidueAbstractField.conjugate at hq
      rw [D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe] at hq
      change e q ∈ (closedSubgroupGenerated {e σ.1}).toSubgroup
      simpa [e] using hq
    have hmap := map_mem_closedSubgroupGenerated_singleton
      (ContinuousMonoidHom.toContinuousMonoidHom e.symm)
      (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ).1
      (by
        rw [D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe]
        exact hq')
    simpa [DegreeData.frobeniusClosure,
      D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe, e] using hmap

/-- Conjugation of a Frobenius lift commutes with restriction to the finite
Galois quotient. -/
theorem finiteReciprocityNaturalityConjugation_frobeniusRestriction
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    finiteReciprocityNaturalityConjugation K.field L hLK s
        (D.frobeniusRestriction K L hLK σ) =
      D.frobeniusRestriction
        (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ) := by
  change finiteReciprocityNaturalityConjugation K.field L hLK s
      (D.extensionRestriction K.field L hLK σ.1) =
    D.extensionRestriction
      (K.conjugate s : D.FiniteResidueAbstractField).field
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)
      (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ).1
  rw [D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe]
  refine Quotient.inductionOn' σ.1 ?_
  intro k
  rfl

/-- The fixed field of the conjugated Frobenius lift is the conjugate of
the original fixed field. -/
theorem finiteReciprocityNaturalityFrobeniusFixedField_conjugate
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    conjugateClosedSubgroup (D.frobeniusFixedField K L hLK σ) s =
      D.frobeniusFixedField
        (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ) := by
  ext g
  change (g ∈ conjugateClosedSubgroup
      (D.frobeniusFixedField K L hLK σ) s) ↔
    g ∈ D.frobeniusFixedField
      (K.conjugate s : D.FiniteResidueAbstractField)
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)
      (D.finiteReciprocityNaturalityFrobeniusConjugationLift K L hLK s σ)
  rw [conjugateClosedSubgroup_mem]
  constructor
  · rintro ⟨k, hk, hkg⟩
    let ks : (K.conjugate s : D.FiniteResidueAbstractField).field.toSubgroup :=
      conjugateSubgroupEquiv K.field s k
    have hksg : ks.1 = g := by
      dsimp [ks]
      change (k : G) = s * g * s⁻¹ at hkg
      rw [hkg]
      simp [mul_assoc]
    have hkClosure : QuotientGroup.mk k ∈
        (D.frobeniusClosure K L hLK σ).toSubgroup :=
      (D.mem_frobeniusFixedSubgroupWithin_iff K L hLK σ k).1 hk
    have hksClosure : QuotientGroup.mk ks ∈
        (D.frobeniusClosure
          (K.conjugate s : D.FiniteResidueAbstractField)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)
          (D.finiteReciprocityNaturalityFrobeniusConjugationLift
            K L hLK s σ)).toSubgroup := by
      have hmap :=
        (D.finiteReciprocityNaturalityFrobeniusConjugationEquiv_mem_closure_iff
          K L hLK s σ (QuotientGroup.mk k)).1 hkClosure
      have hmk :
          D.finiteReciprocityNaturalityFrobeniusConjugationEquiv
              K.field L hLK s (QuotientGroup.mk k) =
            QuotientGroup.mk ks := by
        apply QuotientGroup.eq_iff_div_mem.mpr
        simp [ks]
      rw [hmk] at hmap
      exact hmap
    refine ⟨ks, ?_, hksg⟩
    exact (D.mem_frobeniusFixedSubgroupWithin_iff
      (K.conjugate s : D.FiniteResidueAbstractField)
      (conjugateClosedSubgroup L s) (conjugateClosedSubgroup_mono hLK s)
      (D.finiteReciprocityNaturalityFrobeniusConjugationLift
        K L hLK s σ) ks).2 hksClosure
  · rintro ⟨ks, hks, hksg⟩
    let k : K.field.toSubgroup :=
      (conjugateSubgroupEquiv K.field s).symm ks
    have hkValue : k.1 = s * g * s⁻¹ := by
      dsimp [k]
      change (ks : G) = g at hksg
      change s * (ks : G) * s⁻¹ = s * g * s⁻¹
      rw [hksg]
    have hksClosure : QuotientGroup.mk ks ∈
        (D.frobeniusClosure
          (K.conjugate s : D.FiniteResidueAbstractField)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)
          (D.finiteReciprocityNaturalityFrobeniusConjugationLift
            K L hLK s σ)).toSubgroup :=
      (D.mem_frobeniusFixedSubgroupWithin_iff
        (K.conjugate s : D.FiniteResidueAbstractField)
        (conjugateClosedSubgroup L s) (conjugateClosedSubgroup_mono hLK s)
        (D.finiteReciprocityNaturalityFrobeniusConjugationLift
          K L hLK s σ) ks).1 hks
    have hkClosure : QuotientGroup.mk k ∈
        (D.frobeniusClosure K L hLK σ).toSubgroup := by
      apply (D.finiteReciprocityNaturalityFrobeniusConjugationEquiv_mem_closure_iff
        K L hLK s σ (QuotientGroup.mk k)).2
      have hmk :
          D.finiteReciprocityNaturalityFrobeniusConjugationEquiv
              K.field L hLK s (QuotientGroup.mk k) =
            QuotientGroup.mk ks := by
        exact congrArg
          (QuotientGroup.mk' (D.extensionInertiaWithin
            (conjugateClosedSubgroup K.field s)
            (conjugateClosedSubgroup L s)
            (conjugateClosedSubgroup_mono hLK s)))
          ((conjugateSubgroupEquiv K.field s).apply_symm_apply ks)
      rw [hmk]
      exact hksClosure
    refine ⟨k, ?_, hkValue⟩
    exact (D.mem_frobeniusFixedSubgroupWithin_iff K L hLK σ k).2 hkClosure

end ConjugateFrobeniusQuotients

end DegreeData

end GroupOnly

section Representation

/-! Mathlib's `Rep ℤ G` forces its representation-bearing group `G` to `Type 0`. -/
variable {G : IntegralRepGroupType} [Group G] [TopologicalSpace G]

namespace DegreeData

/-- Normality of a conjugated finite abstract field is available without
unfolding the finite-field bundle. -/
instance finiteReciprocityNaturalityFiniteAbstractConjugate_normal
    [IsTopologicalGroup G]
    (K : FiniteAbstractField G) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal] :
    (extensionSubgroup (K.conjugate s).field
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).Normal := by
  change
    (extensionSubgroup (conjugateClosedSubgroup K.field s)
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).Normal
  infer_instance

private theorem finiteReciprocityNaturality_isPrimeElement_transport
    (D : DegreeData G) {A : Rep ℤ G} (v : ValuationData D A)
    (S T : FiniteAbstractField G) (hST : S.field = T.field)
    (π : ambientFixedAddSubgroup A S.field) (hπ : v.IsPrimeElement S π) :
    v.IsPrimeElement T (hST ▸ π) := by
  cases S
  cases T
  cases hST
  simpa only using hπ

private theorem finiteReciprocityNaturality_relativeNorm_right_transport
    (A : Rep ℤ G) (K S T : ClosedSubgroup G) (hST : S = T)
    (hSK : S.toSubgroup ≤ K.toSubgroup)
    (hTK : T.toSubgroup ≤ K.toSubgroup)
    [hKSfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K S hSK)]
    [hKTfinite : Finite
      (K.toSubgroup ⧸ extensionSubgroup K T hTK)]
    (π : ambientFixedAddSubgroup A S) :
    relativeNorm A K S hSK π =
      relativeNorm A K T hTK (hST ▸ π) := by
  subst T
  rfl

section ConjugateFiniteNormQuotient

@[instance_reducible]
private def finiteReciprocityNaturalityConjugateNormAddZero
    (A : Rep ℤ G) [IsTopologicalGroup G]
    (K : FiniteAbstractField G) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLfinite : Finite
      (K.field.toSubgroup ⧸ extensionSubgroup K.field L hLK)] :=
  letI : Finite
      ((K.conjugate s).field.toSubgroup ⧸
        extensionSubgroup (K.conjugate s).field (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) :=
    finite_conjugateExtension K.field L hLK s (hLfinite := hLfinite)
  show AddZero (FiniteNormQuotient A (K.conjugate s).field
    (conjugateClosedSubgroup L s) (conjugateClosedSubgroup_mono hLK s)) from
    (finiteNormQuotientAddCommGroup A (K.conjugate s).field
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)).toAddZeroClass.toAddZero

attribute [local instance] finiteReciprocityNaturalityConjugateNormAddZero


/-- **norm--conjugation naturality, second diagram.** Conjugation of finite Galois
groups corresponds under the finite reciprocity equivalence to conjugation of finite norm
classes. -/
theorem finiteReciprocityNaturality_conjugation_commutes
    (D : DegreeData G) (A : Rep ℤ G) (v : ValuationData D A)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (hAxiom : v.SatisfiesUnramifiedUnitCohomology D)
    (K : FiniteAbstractField G) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) (s : G)
    [hLnormal : (extensionSubgroup K.field L hLK).Normal]
    [hLfinite : Finite
      (K.field.toSubgroup ⧸ extensionSubgroup K.field L hLK)] :
    let Ks : FiniteAbstractField G := K.conjugate s
    let Ls := conjugateClosedSubgroup L s
    let hLsKs := conjugateClosedSubgroup_mono hLK s
    letI : Finite
        (Ks.field.toSubgroup ⧸ extensionSubgroup Ks.field Ls hLsKs) :=
      finite_conjugateExtension K.field L hLK s
    (finiteReciprocityNaturalityConjugationNormMap A K.field L hLK s).comp
        (D.finiteReciprocityHom A v hAxiom K L hLK) =
      (D.finiteReciprocityHom A v hAxiom Ks Ls hLsKs).comp
        (finiteReciprocityNaturalityConjugation K.field L hLK s).toMonoidHom.toAdditive := by
  dsimp only
  let hLsfinite : Finite
      ((conjugateClosedSubgroup K.field s).toSubgroup ⧸
        extensionSubgroup (conjugateClosedSubgroup K.field s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) :=
    finite_conjugateExtension K.field L hLK s
  let KR : D.FiniteResidueAbstractField :=
    K.toFiniteResidueAbstractField D
  let Ks : FiniteAbstractField G := K.conjugate s
  let KRs : D.FiniteResidueAbstractField :=
    Ks.toFiniteResidueAbstractField D
  have hKRs_conjugate : KR.conjugate s = KRs := by
    dsimp [KRs, Ks, KR]
    unfold FiniteAbstractField.toFiniteResidueAbstractField
    unfold FiniteAbstractField.conjugate
    unfold DegreeData.FiniteResidueAbstractField.conjugate
    rfl
  let hLsfiniteKs : Finite
      (Ks.field.toSubgroup ⧸
        extensionSubgroup Ks.field (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) := by
    change Finite
      ((conjugateClosedSubgroup K.field s).toSubgroup ⧸
        extensionSubgroup (conjugateClosedSubgroup K.field s)
          (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s))
    exact hLsfinite
  let hLsfiniteKRs : Finite
      (KRs.field.toSubgroup ⧸
        extensionSubgroup KRs.field (conjugateClosedSubgroup L s)
          (conjugateClosedSubgroup_mono hLK s)) := by
    simpa only [KRs, FiniteAbstractField.toFiniteResidueAbstractField] using
      hLsfiniteKs
  let hLnormalKR : (extensionSubgroup KR.field L hLK).Normal := by
    simpa only [KR, FiniteAbstractField.toFiniteResidueAbstractField] using
      hLnormal
  let hLsnormalKs :
      (extensionSubgroup Ks.field (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)).Normal := by
    change
      (extensionSubgroup (conjugateClosedSubgroup K.field s)
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)).Normal
    infer_instance
  let hLsnormalKRs :
      (extensionSubgroup KRs.field (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)).Normal := by
    simpa only [KRs, FiniteAbstractField.toFiniteResidueAbstractField] using
      hLsnormalKs
  apply AddMonoidHom.ext
  intro q
  let σ := D.chosenFiniteReciprocityFrobeniusLift KR L hLK q.toMul
  let σs : D.FrobeniusElements KRs
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s) := by
    subst KRs
    exact D.finiteReciprocityNaturalityFrobeniusConjugationLift
      KR L hLK s σ
  have hσ : D.frobeniusRestriction KR L hLK σ = q.toMul :=
    D.frobeniusRestriction_chosenFiniteReciprocityFrobeniusLift
      KR L hLK q.toMul
  have hσs : D.frobeniusRestriction KRs
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s) σs =
      ((finiteReciprocityNaturalityConjugation
        K.field L hLK s).toMonoidHom.toAdditive q).toMul := by
    change D.frobeniusRestriction KRs
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s) σs =
      finiteReciprocityNaturalityConjugation K.field L hLK s q.toMul
    rw [← hσ]
    symm
    change finiteReciprocityNaturalityConjugation K.field L hLK s
        (D.extensionRestriction KR.field L hLK σ.1) =
      D.extensionRestriction KRs.field
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s) σs.1
    unfold σs
    cases hKRs_conjugate
    dsimp only [id]
    rw [D.finiteReciprocityNaturalityFrobeniusConjugationLift_coe]
    refine Quotient.inductionOn' σ.1 ?_
    intro k
    rfl
  let S := D.frobeniusFixedField KR L hLK σ
  let Ss := D.frobeniusFixedField KRs
    (conjugateClosedSubgroup L s)
    (conjugateClosedSubgroup_mono hLK s) σs
  let hSK := D.frobeniusFixedField_le KR L hLK σ
  let hSsKs := D.frobeniusFixedField_le KRs
    (conjugateClosedSubgroup L s)
    (conjugateClosedSubgroup_mono hLK s) σs
  have hConjS : conjugateClosedSubgroup S s = Ss := by
    exact D.finiteReciprocityNaturalityFrobeniusFixedField_conjugate
      KR L hLK s σ
  let hSKfinite : Finite
      (K.field.toSubgroup ⧸ extensionSubgroup K.field S hSK) :=
    D.frobeniusFixedField_finite KR L hLK σ
  let hConjSKfinite : Finite
      (Ks.field.toSubgroup ⧸
        extensionSubgroup Ks.field
          (conjugateClosedSubgroup S s)
          (conjugateClosedSubgroup_mono hSK s)) :=
    by
      change Finite
        ((conjugateClosedSubgroup K.field s).toSubgroup ⧸
          extensionSubgroup (conjugateClosedSubgroup K.field s)
            (conjugateClosedSubgroup S s)
            (conjugateClosedSubgroup_mono hSK s))
      exact finite_conjugateExtension K.field S hSK s
  let hSsKsfinite : Finite
      (Ks.field.toSubgroup ⧸ extensionSubgroup Ks.field Ss hSsKs) :=
    D.frobeniusFixedField_finite KRs
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s) σs
  let Sfinite : FiniteAbstractField G :=
    { field := S
      finite := D.frobeniusFixedField_absoluteFinite K L hLK σ }
  let Ssfinite : FiniteAbstractField G :=
    { field := Ss
      finite := D.frobeniusFixedField_absoluteFinite Ks
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s) σs }
  let π : ambientFixedAddSubgroup A S := v.chosenPrimeElement Sfinite
  have hπ : v.IsPrimeElement Sfinite π := v.chosenPrimeElement_isPrime Sfinite
  let πs0 : ambientFixedAddSubgroup A (conjugateClosedSubgroup S s) :=
    conjugateFixedElement A S s π
  have hπs0 : v.IsPrimeElement (Sfinite.conjugate s) πs0 := by
    change v.valuationAt (Sfinite.conjugate s) πs0 = v.oneValue
    rw [show v.valuationAt (Sfinite.conjugate s) πs0 =
        v.valuationAt Sfinite π by
      simpa [Sfinite, πs0] using
        v.normalizedValuation_conjugate Sfinite s π]
    exact hπ
  let πs : ambientFixedAddSubgroup A Ss := hConjS ▸ πs0
  have hπs : v.IsPrimeElement Ssfinite πs := by
    have htransport :=
      D.finiteReciprocityNaturality_isPrimeElement_transport v
        (Sfinite.conjugate s) Ssfinite (by exact hConjS) πs0 hπs0
    unfold πs
    exact htransport
  change finiteReciprocityNaturalityConjugationNormMap A K.field L hLK s
      (D.finiteReciprocityHom A v hAxiom K L hLK q) =
    D.finiteReciprocityHom A v hAxiom Ks
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)
      ((finiteReciprocityNaturalityConjugation
        K.field L hLK s).toMonoidHom.toAdditive q)
  have hprimeNorm :
      finiteReciprocityNaturalityConjugationNormMap A K.field L hLK s
        (D.finiteReciprocityHom A v hAxiom K L hLK q) =
      finiteReciprocityNaturalityConjugationNormMap A K.field L hLK s
        (finiteNormClass A K.field L hLK
          (relativeNorm A K.field S hSK π)) := by
    rw [D.finiteReciprocityHom_apply_eq_primeNormClass
      A v hAxiom K L hLK q σ hσ π hπ]
  have hconjugateNorm :
      finiteReciprocityNaturalityConjugationNormMap A K.field L hLK s
        (finiteNormClass A K.field L hLK
          (relativeNorm A K.field S hSK π)) =
      finiteNormClass A Ks.field
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (relativeNorm A Ks.field
          (conjugateClosedSubgroup S s)
          (conjugateClosedSubgroup_mono hSK s) πs0) := by
    exact finiteReciprocityNaturality_conjugation_norm_class
      A K.field L S hLK hSK s π
  have htransportNorm :
      finiteNormClass A Ks.field
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (relativeNorm A Ks.field
          (conjugateClosedSubgroup S s)
          (conjugateClosedSubgroup_mono hSK s) πs0) =
      finiteNormClass A Ks.field
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (relativeNorm A Ks.field Ss hSsKs πs) := by
    apply congrArg (finiteNormClass A Ks.field
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s))
    have htransport :=
      finiteReciprocityNaturality_relativeNorm_right_transport A
        Ks.field (conjugateClosedSubgroup S s) Ss
        hConjS (conjugateClosedSubgroup_mono hSK s) hSsKs πs0
    simpa [πs] using htransport
  have hconjugatePrimeNorm :
      finiteNormClass A Ks.field
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        (relativeNorm A Ks.field Ss hSsKs πs) =
      D.finiteReciprocityHom A v hAxiom Ks
        (conjugateClosedSubgroup L s)
        (conjugateClosedSubgroup_mono hLK s)
        ((finiteReciprocityNaturalityConjugation
          K.field L hLK s).toMonoidHom.toAdditive q) := by
    rw [D.finiteReciprocityHom_apply_eq_primeNormClass
      A v hAxiom Ks
      (conjugateClosedSubgroup L s)
      (conjugateClosedSubgroup_mono hLK s)
      _ σs hσs πs hπs]
  exact hprimeNorm.trans (hconjugateNorm.trans (htransportNorm.trans hconjugatePrimeNorm))

end ConjugateFiniteNormQuotient

end DegreeData

end Representation

end

end ClassFormation
