import GaloisCohomology.ProfiniteIntegers.TopologicalGeneration
import Mathlib.GroupTheory.Transfer
import Mathlib.Topology.Algebra.Group.ClosedSubgroup

set_option autoImplicit false

namespace ClassFormation

/-!
# The closed cyclic subgroup attached to one transfer orbit

For a finite-index subgroup `H` and an element `g`, the intersection of
the closed cyclic subgroup generated by `g` with the stabilizer of a coset
is generated by the power whose exponent is that orbit's minimal period.
This is the topological group calculation used in transfer--norm naturality.
-/

noncomputable section

open MulAction

/-- The closed cyclic subgroup generated by the transfer power is the
intersection of the original closed cyclic subgroup with the stabilizer of
the chosen coset. -/
theorem closedSubgroupGenerated_pow_eq_inf_stabilizer
    {Q : Type*} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    (H : Subgroup Q) [H.FiniteIndex]
    (hHclosed : IsClosed (H : Set Q)) (g : Q) (x : Q ⧸ H) :
    (closedSubgroupGenerated
        ({g ^ Function.minimalPeriod (g • ·) x} : Set Q) : Subgroup Q) =
      (closedSubgroupGenerated ({g} : Set Q) : Subgroup Q) ⊓
        MulAction.stabilizer Q x := by
  let m := Function.minimalPeriod (g • ·) x
  let V := MulAction.stabilizer Q x
  let t := x.out
  have hx : x = t • (QuotientGroup.mk 1 : Q ⧸ H) := by
    symm
    change QuotientGroup.mk (t * 1) = x
    rw [mul_one]
    exact Quotient.out_eq' x
  have hVeq : V = H.map (MulAut.conj t).toMonoidHom := by
    change MulAction.stabilizer Q x = _
    rw [hx, stabilizer_smul_eq_stabilizer_map_conj,
      MulAction.stabilizer_quotient]
  have hVclosed : IsClosed (V : Set Q) := by
    rw [hVeq, Subgroup.map_equiv_eq_comap_symm'
      (MulAut.conj t) H]
    change IsClosed ((fun y : Q => t⁻¹ * y * t) ⁻¹' (H : Set Q))
    simpa only [inv_inv] using
      hHclosed.preimage (IsTopologicalGroup.continuous_conj t⁻¹)
  let : V.FiniteIndex := by
    rw [Subgroup.finiteIndex_iff, hVeq,
      Subgroup.index_map_of_bijective (MulAut.conj t).bijective H]
    exact Subgroup.FiniteIndex.index_ne_zero
  have hVopen : IsOpen (V : Set Q) :=
    V.isOpen_of_isClosed_of_finiteIndex hVclosed
  have halg : Subgroup.zpowers g ⊓ V = Subgroup.zpowers (g ^ m) := by
    ext y
    constructor
    · rintro ⟨hy, hyV⟩
      obtain ⟨z, rfl⟩ := Subgroup.mem_zpowers_iff.mp hy
      have hfix : g ^ z • x = x :=
        (mem_stabilizer_iff (G := Q)).mp hyV
      have hdvd : (m : ℤ) ∣ z :=
        zpow_smul_eq_iff_minimalPeriod_dvd.mp hfix
      obtain ⟨k, rfl⟩ := hdvd
      apply Subgroup.mem_zpowers_iff.mpr
      refine ⟨k, ?_⟩
      rw [zpow_mul, zpow_natCast]
    · intro hy
      obtain ⟨z, hz⟩ := Subgroup.mem_zpowers_iff.mp hy
      rw [← hz]
      constructor
      · apply Subgroup.mem_zpowers_iff.mpr
        refine ⟨(m : ℤ) * z, ?_⟩
        rw [zpow_mul, zpow_natCast]
      · apply (mem_stabilizer_iff (G := Q)).mpr
        rw [← zpow_natCast g m, ← zpow_mul]
        apply zpow_smul_eq_iff_minimalPeriod_dvd.mpr
        exact dvd_mul_right (m : ℤ) z
  have hpow_le : Subgroup.zpowers (g ^ m) ≤ Subgroup.zpowers g :=
    Subgroup.zpowers_le_of_mem (Subgroup.npow_mem_zpowers g m)
  have hpowV : Subgroup.zpowers (g ^ m) ≤ V := by
    rw [← halg]
    exact inf_le_right
  have hsets : ((Subgroup.zpowers g : Set Q) ∩ (V : Set Q)) =
      (Subgroup.zpowers (g ^ m) : Set Q) :=
    congrArg (fun U : Subgroup Q => (U : Set Q)) halg
  change (Subgroup.closure ({g ^ m} : Set Q)).topologicalClosure =
    (Subgroup.closure ({g} : Set Q)).topologicalClosure ⊓ V
  rw [← Subgroup.zpowers_eq_closure, ← Subgroup.zpowers_eq_closure]
  ext y
  change y ∈ closure (Subgroup.zpowers (g ^ m) : Set Q) ↔
    y ∈ closure (Subgroup.zpowers g : Set Q) ∧ y ∈ V
  constructor
  · intro hy
    exact ⟨closure_mono hpow_le hy,
      closure_minimal hpowV hVclosed hy⟩
  · rintro ⟨hyg, hyV⟩
    have hyInter : y ∈ closure
        ((Subgroup.zpowers g : Set Q) ∩ (V : Set Q)) :=
      hVopen.closure_inter ⟨hyg, hyV⟩
    rwa [hsets] at hyInter

/-- Conjugation carries membership in the closed cyclic subgroup generated by
`x` to membership in the closed cyclic subgroup generated by the conjugate of
`x`. -/
theorem mem_closedSubgroupGenerated_conjugate_iff
    {Q : Type*} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    (q x c : Q) :
    c ∈ (closedSubgroupGenerated ({x} : Set Q)).toSubgroup ↔
      q * c * q⁻¹ ∈
        (closedSubgroupGenerated ({q * x * q⁻¹} : Set Q)).toSubgroup := by
  let conjugationHom (g : Q) : Q →ₜ* Q :=
    { toMonoidHom := (MulAut.conj g).toMonoidHom
      continuous_toFun := IsTopologicalGroup.continuous_conj g }
  constructor
  · intro hc
    exact map_mem_closedSubgroupGenerated_singleton
      (conjugationHom q) x hc
  · intro hc
    have h := map_mem_closedSubgroupGenerated_singleton
      (conjugationHom q⁻¹) (q * x * q⁻¹) hc
    change q⁻¹ * (q * c * q⁻¹) * (q⁻¹)⁻¹ ∈
      (closedSubgroupGenerated
        ({q⁻¹ * (q * x * q⁻¹) * (q⁻¹)⁻¹} : Set Q)).toSubgroup at h
    simpa [mul_assoc] using h

end
end ClassFormation
