import Mathlib.SetTheory.Cardinal.Finite
import ClassFieldTheory.LubinTate.Padic.CompletedChangedUniformizerPrimitive
import ClassFieldTheory.LubinTate.Padic.CompletedChangedUniformizerThetaFixed
import ClassFieldTheory.LubinTate.Padic.CompletedUnramifiedFrobeniusFixed

set_option autoImplicit false

/-!
# The changed p-adic Lubin--Tate level as a completed Frobenius fixed field

The completed Frobenius lift whose action on the standard primitive point is
indexed by `u⁻¹` is an actual `ℚ_[p]`-automorphism.  Its fixed field is
exactly the finite changed-uniformizer Lubin--Tate level generated by the
genuine theta value.

The key reverse inclusion is coefficient descent in the theta power basis:
fixedness makes every completed-unramified coefficient Frobenius-fixed, and
the fixed-field theorem for Witt Frobenius puts that coefficient in
`ℚ_[p]`.  The final norm formula is therefore transported from the actual
finite changed level, with no comparison hypothesis.
-/

noncomputable section

open scoped Polynomial

namespace LubinTate

open LocalFieldTheory.DiscreteValuationField
open LocalFieldTheory.DiscreteValuationField.Examples.Qp

/-- The inverse-unit completed Frobenius lift, regarded as an actual
automorphism over `ℚ_[p]`. -/
noncomputable def padicCompletedChangedUniformizerFrobeniusAlgEquiv
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    padicCompletedLevelField p n ≃ₐ[ℚ_[p]]
      padicCompletedLevelField p n :=
  AlgEquiv.ofRingEquiv (by
    intro b
    change
      padicCompletedUnitFrobeniusLiftEquiv p n u⁻¹
          (algebraMap (padicCompletedUnramifiedField p)
            (padicCompletedLevelField p n)
            (algebraMap ℚ_[p]
              (padicCompletedUnramifiedField p) b)) =
        algebraMap (padicCompletedUnramifiedField p)
          (padicCompletedLevelField p n)
          (algebraMap ℚ_[p]
            (padicCompletedUnramifiedField p) b)
    rw [padicCompletedUnitFrobeniusLiftEquiv_algebraMap,
      (padicCompletedUnramifiedFrobenius p).commutes])

/-- The underlying action of the changed-uniformizer Frobenius
automorphism is the actual completed inverse-unit lift. -/
@[simp]
theorem padicCompletedChangedUniformizerFrobeniusAlgEquiv_apply
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ)
    (x : padicCompletedLevelField p n) :
    padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n x =
      padicCompletedUnitFrobeniusLiftEquiv p n u⁻¹ x :=
  rfl

/-- The cyclic subgroup generated by the completed changed-uniformizer
Frobenius automorphism. -/
noncomputable def padicCompletedChangedUniformizerFrobeniusSubgroup
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Subgroup
      (padicCompletedLevelField p n ≃ₐ[ℚ_[p]]
        padicCompletedLevelField p n) :=
  Subgroup.zpowers
    (padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n)

/-- The field fixed by the actual inverse-unit completed Frobenius lift. -/
noncomputable def padicCompletedChangedUniformizerFixedField
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    IntermediateField ℚ_[p] (padicCompletedLevelField p n) :=
  IntermediateField.fixedField
    (padicCompletedChangedUniformizerFrobeniusSubgroup p u n)

/-- The genuine theta value belongs to the completed Frobenius fixed field. -/
theorem padicChangedUniformizerThetaValue_mem_completedFixedField
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    ((padicChangedUniformizerThetaValue p u n :
        (padicCompletedLevelCompleteDVF p n).valuationSubring) :
          padicCompletedLevelField p n) ∈
      padicCompletedChangedUniformizerFixedField p u n := by
  rw [padicCompletedChangedUniformizerFixedField,
    IntermediateField.mem_fixedField_iff]
  intro σ hσ
  obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hσ
  have hfixed :
      (((padicChangedUniformizerThetaValue p u n :
          (padicCompletedLevelCompleteDVF p n).valuationSubring) :
            padicCompletedLevelField p n)) ∈
        MulAction.fixedBy
          (padicCompletedLevelField p n)
          (padicCompletedChangedUniformizerFrobeniusAlgEquiv
            p u n) := by
    rw [MulAction.mem_fixedBy]
    change
      padicCompletedUnitFrobeniusLiftEquiv p n u⁻¹
          ((padicChangedUniformizerThetaValue p u n :
            (padicCompletedLevelCompleteDVF p n).valuationSubring) :
              padicCompletedLevelField p n) =
        _
    exact
      padicCompletedChangedUniformizerThetaValue_fixed_by_diagonalFrobenius
        p u n
  exact MulAction.mem_fixedBy_zpow hfixed j

/-- The completed changed-level embedding is pointwise fixed by the
inverse-unit Frobenius lift. -/
theorem padicChangedUniformizerLevelEmbedding_mem_completedFixedField
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ)
    (x :
      standardLubinTateChangedLevelField
        (padicMultiplicativeLubinTateSeries_isUniformizer p) u n) :
    padicChangedUniformizerLevelEmbedding p u n x ∈
      padicCompletedChangedUniformizerFixedField p u n := by
  let hπ :=
    standardLubinTateChangedUniformizer_isUniformizer
      (padicMultiplicativeLubinTateSeries_isUniformizer p) u
  let L := standardLubinTateLevelField hπ n
  let E := padicCompletedLevelField p n
  let ι : L →ₐ[ℚ_[p]] E :=
    padicChangedUniformizerLevelEmbedding p u n
  let δ : E ≃ₐ[ℚ_[p]] E :=
    padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n
  have hintertwine : δ.toAlgHom.comp ι = ι := by
    apply (standardLubinTateLevelPowerBasis hπ n).algHom_ext
    change
      δ (ι (standardLubinTateLevelPowerBasis hπ n).gen) =
        ι (standardLubinTateLevelPowerBasis hπ n).gen
    rw [show
      ι (standardLubinTateLevelPowerBasis hπ n).gen =
        ((padicChangedUniformizerThetaValue p u n :
          (padicCompletedLevelCompleteDVF p n).valuationSubring) :
            padicCompletedLevelField p n) by
          exact padicChangedUniformizerLevelEmbedding_apply_gen p u n]
    exact
      padicCompletedChangedUniformizerThetaValue_fixed_by_diagonalFrobenius
        p u n
  rw [padicCompletedChangedUniformizerFixedField,
    IntermediateField.mem_fixedField_iff]
  intro σ hσ
  obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hσ
  have hfixed :
      ι x ∈ MulAction.fixedBy E δ := by
    rw [MulAction.mem_fixedBy]
    exact DFunLike.congr_fun hintertwine x
  exact MulAction.mem_fixedBy_zpow hfixed j

/-- The finite changed Lubin--Tate level embedded directly into the
completed Frobenius fixed field. -/
noncomputable def padicChangedUniformizerLevelToCompletedFixedField
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    standardLubinTateChangedLevelField
        (padicMultiplicativeLubinTateSeries_isUniformizer p) u n
      →ₐ[ℚ_[p]]
        padicCompletedChangedUniformizerFixedField p u n :=
  (padicChangedUniformizerLevelEmbedding p u n).codRestrict
    (padicCompletedChangedUniformizerFixedField p u n).toSubalgebra
    (padicChangedUniformizerLevelEmbedding_mem_completedFixedField
      p u n)

/-- The fixed-field embedding sends the finite changed-level generator to
the genuine theta value. -/
@[simp]
theorem padicChangedUniformizerLevelToCompletedFixedField_apply_gen
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    let hπ :=
      standardLubinTateChangedUniformizer_isUniformizer
        (padicMultiplicativeLubinTateSeries_isUniformizer p) u
    padicChangedUniformizerLevelToCompletedFixedField p u n
        (standardLubinTateLevelPowerBasis hπ n).gen =
      ⟨((padicChangedUniformizerThetaValue p u n :
          (padicCompletedLevelCompleteDVF p n).valuationSubring) :
            padicCompletedLevelField p n),
        padicChangedUniformizerThetaValue_mem_completedFixedField
          p u n⟩ := by
  apply Subtype.ext
  exact padicChangedUniformizerLevelEmbedding_apply_gen p u n

/-- A Frobenius-fixed element of the completed level belongs to the
`ℚ_[p]`-field generated by the theta value. -/
theorem padicCompletedChangedUniformizerFrobenius_fixed_mem_adjoin_theta
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ)
    (x : padicCompletedLevelField p n)
    (hx :
      padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n x = x) :
    x ∈ IntermediateField.adjoin ℚ_[p]
      ({((padicChangedUniformizerThetaValue p u n :
        (padicCompletedLevelCompleteDVF p n).valuationSubring) :
          padicCompletedLevelField p n)} :
        Set (padicCompletedLevelField p n)) := by
  let A := padicCompletedUnramifiedField p
  let E := padicCompletedLevelField p n
  let φ := padicCompletedUnramifiedFrobenius p
  let δ :=
    padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n
  let y : E :=
    ((padicChangedUniformizerThetaValue p u n :
      (padicCompletedLevelCompleteDVF p n).valuationSubring) : E)
  let pb : PowerBasis A E :=
    padicChangedUniformizerThetaPowerBasis p u n
  let S : IntermediateField ℚ_[p] E :=
    IntermediateField.adjoin ℚ_[p] ({y} : Set E)
  have hδCoeff (c : A) :
      δ (algebraMap A E c) =
        algebraMap A E (φ c) := by
    change
      padicCompletedUnitFrobeniusLiftEquiv p n u⁻¹
          (algebraMap A E c) =
        algebraMap A E
          (padicCompletedUnramifiedFrobenius p c)
    exact
      padicCompletedUnitFrobeniusLiftEquiv_algebraMap p n u⁻¹ c
  have hδY : δ y = y := by
    change
      padicCompletedUnitFrobeniusLiftEquiv p n u⁻¹
          ((padicChangedUniformizerThetaValue p u n :
            (padicCompletedLevelCompleteDVF p n).valuationSubring) : E) =
        _
    exact
      padicCompletedChangedUniformizerThetaValue_fixed_by_diagonalFrobenius
        p u n
  have hδBasis (i : Fin pb.dim) :
      δ (pb.basis i) = pb.basis i := by
    rw [pb.coe_basis, map_pow, show pb.gen = y by
      exact padicChangedUniformizerThetaPowerBasis_gen p u n, hδY]
  have hsemisum :
      (∑ i : Fin pb.dim, φ (pb.basis.repr x i) • pb.basis i) =
        x := by
    calc
      (∑ i : Fin pb.dim, φ (pb.basis.repr x i) • pb.basis i) =
          δ (∑ i : Fin pb.dim,
            pb.basis.repr x i • pb.basis i) := by
        rw [map_sum]
        apply Finset.sum_congr rfl
        intro i hi
        rw [Algebra.smul_def, Algebra.smul_def, map_mul,
          hδCoeff, hδBasis]
      _ = δ x := by rw [pb.basis.sum_repr]
      _ = x := hx
  have hcoeff (i : Fin pb.dim) :
      φ (pb.basis.repr x i) = pb.basis.repr x i := by
    have hrepr := congrArg pb.basis.repr hsemisum
    have hi := congrArg (fun c ↦ c i) hrepr
    simp only [map_sum, map_smul, Module.Basis.repr_self,
      Finsupp.smul_single', mul_one] at hi
    rw [Finsupp.finsetSum_apply] at hi
    rw [Finset.sum_eq_single i] at hi
    · simpa only [Finsupp.single_eq_same] using hi
    · intro j hj hji
      exact Finsupp.single_eq_of_ne hji.symm
    · simp
  change x ∈ S
  rw [← pb.basis.sum_repr x]
  apply S.sum_mem
  intro i hi
  rw [pb.coe_basis, Algebra.smul_def]
  apply S.mul_mem
  · obtain ⟨c, hc⟩ :=
      (padicCompletedUnramifiedFrobenius_fixed_iff
        p (pb.basis.repr x i)).1 (hcoeff i)
    change algebraMap A E (pb.basis.repr x i) ∈ S
    rw [← hc, ← IsScalarTower.algebraMap_apply ℚ_[p] A E]
    exact S.algebraMap_mem c
  · have hgen : pb.gen ∈ S := by
      rw [show pb.gen = y by
        exact padicChangedUniformizerThetaPowerBasis_gen p u n]
      exact IntermediateField.mem_adjoin_simple_self ℚ_[p] y
    simpa using S.pow_mem hgen i.val

/-- The completed inverse-unit Frobenius fixed field is exactly the
`ℚ_[p]`-field generated by the theta value. -/
theorem padicCompletedChangedUniformizerFixedField_eq_adjoin_theta
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    padicCompletedChangedUniformizerFixedField p u n =
      IntermediateField.adjoin ℚ_[p]
        ({((padicChangedUniformizerThetaValue p u n :
          (padicCompletedLevelCompleteDVF p n).valuationSubring) :
            padicCompletedLevelField p n)} :
          Set (padicCompletedLevelField p n)) := by
  apply le_antisymm
  · intro x hx
    apply
      padicCompletedChangedUniformizerFrobenius_fixed_mem_adjoin_theta
        p u n x
    change x ∈ IntermediateField.fixedField
      (padicCompletedChangedUniformizerFrobeniusSubgroup p u n) at hx
    exact
      (IntermediateField.mem_fixedField_iff
        (H := padicCompletedChangedUniformizerFrobeniusSubgroup
          p u n) x).1 hx
        (padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n)
        (Subgroup.mem_zpowers _)
  · apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact
      padicChangedUniformizerThetaValue_mem_completedFixedField p u n

/-- The theta value is integral over `ℚ_[p]`. -/
theorem padicChangedUniformizerThetaValue_isIntegral_padicBase
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    IsIntegral ℚ_[p]
      ((padicChangedUniformizerThetaValue p u n :
        (padicCompletedLevelCompleteDVF p n).valuationSubring) :
          padicCompletedLevelField p n) := by
  let πu :=
    standardLubinTateChangedUniformizer
      (padicLocalField p)
      (padicIntEquivValuationSubring p (p : ℤ_[p])) u
  refine
    ⟨standardLubinTatePrimitivePolynomialOverField
        (padicLocalField p) πu n,
      standardLubinTatePrimitivePolynomialOverField_monic
        (padicLocalField p) πu n, ?_⟩
  rw [← Polynomial.eval_map]
  exact padicChangedUniformizerThetaValue_field_isRoot p u n

/-- Over `ℚ_[p]`, the theta value has the actual changed Lubin--Tate
primitive polynomial as its minimal polynomial. -/
theorem padicChangedUniformizerThetaValue_minpoly_padicBase
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    minpoly ℚ_[p]
        ((padicChangedUniformizerThetaValue p u n :
          (padicCompletedLevelCompleteDVF p n).valuationSubring) :
            padicCompletedLevelField p n) =
      standardLubinTatePrimitivePolynomialOverField
        (padicLocalField p)
        (standardLubinTateChangedUniformizer
          (padicLocalField p)
          (padicIntEquivValuationSubring p (p : ℤ_[p])) u) n := by
  let hπ :=
    standardLubinTateChangedUniformizer_isUniformizer
      (padicMultiplicativeLubinTateSeries_isUniformizer p) u
  let P :=
    standardLubinTatePrimitivePolynomialOverField
      (padicLocalField p)
      (standardLubinTateChangedUniformizer
        (padicLocalField p)
        (padicIntEquivValuationSubring p (p : ℤ_[p])) u) n
  have hroot :
      Polynomial.aeval
          ((padicChangedUniformizerThetaValue p u n :
            (padicCompletedLevelCompleteDVF p n).valuationSubring) :
              padicCompletedLevelField p n) P =
        0 := by
    rw [Polynomial.aeval_def, ← Polynomial.eval_map]
    exact padicChangedUniformizerThetaValue_field_isRoot p u n
  have hmin :=
    minpoly.eq_of_irreducible
      (standardLubinTatePrimitivePolynomialOverField_irreducible
        hπ n) hroot
  rw [(standardLubinTatePrimitivePolynomialOverField_monic
    (padicLocalField p)
    (standardLubinTateChangedUniformizer
      (padicLocalField p)
      (padicIntEquivValuationSubring p (p : ℤ_[p])) u) n).leadingCoeff,
    inv_one, Polynomial.C_1, mul_one] at hmin
  exact hmin.symm

noncomputable local instance
    padicCompletedChangedUniformizerFixedFieldAlgebra
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Algebra ℚ_[p]
      (padicCompletedChangedUniformizerFixedField p u n) :=
  Subalgebra.algebra
    (padicCompletedChangedUniformizerFixedField p u n).toSubalgebra

noncomputable local instance
    padicCompletedChangedUniformizerFixedFieldSMul
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    SMul ℚ_[p]
      (padicCompletedChangedUniformizerFixedField p u n) :=
  @Algebra.toSMul _ _ _ _
    (padicCompletedChangedUniformizerFixedFieldAlgebra p u n)

noncomputable local instance
    padicCompletedChangedUniformizerFixedFieldModule
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Module ℚ_[p]
      (padicCompletedChangedUniformizerFixedField p u n) :=
  @Algebra.toModule _ _ _ _
    (padicCompletedChangedUniformizerFixedFieldAlgebra p u n)

/-- The completed changed-uniformizer fixed field has degree
`(p - 1) * p ^ n` over `ℚ_[p]`. -/
theorem padicCompletedChangedUniformizerFixedField_finrank
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Module.finrank ℚ_[p]
        (padicCompletedChangedUniformizerFixedField p u n) =
      (p - 1) * p ^ n := by
  let y : padicCompletedLevelField p n :=
    ((padicChangedUniformizerThetaValue p u n :
      (padicCompletedLevelCompleteDVF p n).valuationSubring) :
        padicCompletedLevelField p n)
  let S := IntermediateField.adjoin ℚ_[p] ({y} :
    Set (padicCompletedLevelField p n))
  let SAlgebra : Algebra ℚ_[p] S :=
    Subalgebra.algebra S.toSubalgebra
  let SSMul : SMul ℚ_[p] S :=
    @Algebra.toSMul _ _ _ _ SAlgebra
  let SModule : Module ℚ_[p] S :=
    @Algebra.toModule _ _ _ _ SAlgebra
  have hfield :
      padicCompletedChangedUniformizerFixedField p u n = S :=
    padicCompletedChangedUniformizerFixedField_eq_adjoin_theta p u n
  have hcard :
      Nat.card (padicLocalField p).residueField = p := by
    simpa [padicLocalField] using
      padicCompleteDVF_residueField_card p
  calc
    Module.finrank ℚ_[p]
        (padicCompletedChangedUniformizerFixedField p u n) =
      Module.finrank ℚ_[p] S :=
        (IntermediateField.equivOfEq hfield).toLinearEquiv.finrank_eq
    _ = (p - 1) * p ^ n := by
      dsimp only [S, y]
      rw [IntermediateField.adjoin.finrank
          (padicChangedUniformizerThetaValue_isIntegral_padicBase
            p u n),
        padicChangedUniformizerThetaValue_minpoly_padicBase,
        standardLubinTatePrimitivePolynomialOverField_natDegree,
        hcard]

/-- The actual finite changed Lubin--Tate level is algebraically equivalent
to the completed inverse-unit Frobenius fixed field. -/
noncomputable def padicChangedUniformizerLevelEquivCompletedFixedField
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    standardLubinTateChangedLevelField
        (padicMultiplicativeLubinTateSeries_isUniformizer p) u n
      ≃ₐ[ℚ_[p]]
        padicCompletedChangedUniformizerFixedField p u n := by
  let hπ :=
    standardLubinTateChangedUniformizer_isUniformizer
      (padicMultiplicativeLubinTateSeries_isUniformizer p) u
  let f :=
    padicChangedUniformizerLevelToCompletedFixedField p u n
  letI : FiniteDimensional ℚ_[p]
      (standardLubinTateLevelField hπ n) :=
    standardLubinTateLevelField_finiteDimensional hπ n
  letI : FiniteDimensional ℚ_[p]
      (padicCompletedChangedUniformizerFixedField p u n) :=
    FiniteDimensional.of_finrank_pos (by
      rw [padicCompletedChangedUniformizerFixedField_finrank]
      exact Nat.mul_pos
        (Nat.sub_pos_of_lt (Fact.out : p.Prime).one_lt)
        (Nat.pow_pos (Fact.out : p.Prime).pos))
  apply AlgEquiv.ofBijective f
  refine ⟨f.injective, ?_⟩
  have hcard :
      Nat.card (padicLocalField p).residueField = p := by
    simpa [padicLocalField] using
      padicCompleteDVF_residueField_card p
  have hdim :
      Module.finrank ℚ_[p]
          (standardLubinTateLevelField hπ n) =
        Module.finrank ℚ_[p]
          (padicCompletedChangedUniformizerFixedField p u n) := by
    rw [standardLubinTateLevelField_finrank,
      padicCompletedChangedUniformizerFixedField_finrank, hcard]
  exact
    (LinearMap.injective_iff_surjective_of_finrank_eq_finrank
      (f := f.toLinearMap) hdim).mp f.injective

/-- The fixed-field equivalence sends the changed finite-level generator
to the genuine theta value. -/
@[simp]
theorem
    padicChangedUniformizerLevelEquivCompletedFixedField_apply_generator
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    padicChangedUniformizerLevelEquivCompletedFixedField p u n
        (standardLubinTateChangedLevelGenerator
          (padicMultiplicativeLubinTateSeries_isUniformizer p) u n) =
      ⟨((padicChangedUniformizerThetaValue p u n :
          (padicCompletedLevelCompleteDVF p n).valuationSubring) :
            padicCompletedLevelField p n),
        padicChangedUniformizerThetaValue_mem_completedFixedField
          p u n⟩ := by
  simp only [padicChangedUniformizerLevelEquivCompletedFixedField]
  exact
    padicChangedUniformizerLevelToCompletedFixedField_apply_gen p u n

/-- The theta value, regarded as an element of the completed Frobenius
fixed field. -/
noncomputable def padicCompletedChangedUniformizerPrimeElement
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    padicCompletedChangedUniformizerFixedField p u n :=
  ⟨((padicChangedUniformizerThetaValue p u n :
      (padicCompletedLevelCompleteDVF p n).valuationSubring) :
        padicCompletedLevelField p n),
    padicChangedUniformizerThetaValue_mem_completedFixedField
      p u n⟩

/-- The fixed-field prime element is the image of the changed finite-level
generator. -/
theorem
    padicCompletedChangedUniformizerPrimeElement_eq_equiv_generator
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    padicCompletedChangedUniformizerPrimeElement p u n =
      padicChangedUniformizerLevelEquivCompletedFixedField p u n
        (standardLubinTateChangedLevelGenerator
          (padicMultiplicativeLubinTateSeries_isUniformizer p) u n) := by
  rw [
    padicChangedUniformizerLevelEquivCompletedFixedField_apply_generator]
  rfl

/-- The completed changed-uniformizer norm formula:
`N(-theta) = u * p`. -/
theorem padicCompletedChangedUniformizer_norm_neg_primeElement
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Algebra.norm ℚ_[p]
        (-padicCompletedChangedUniformizerPrimeElement p u n) =
      (standardLubinTateChangedUniformizer
        (padicLocalField p)
        (padicIntEquivValuationSubring p (p : ℤ_[p])) u :
          ℚ_[p]) := by
  rw [
    padicCompletedChangedUniformizerPrimeElement_eq_equiv_generator,
    ← map_neg, Algebra.norm_eq_of_algEquiv]
  exact
    standardLubinTateChanged_norm_neg_levelGenerator
      (padicMultiplicativeLubinTateSeries_isUniformizer p) u n

end LubinTate

end
