import ClassFieldTheory.LubinTate.Padic.CompletedChangedStandardCompositum

set_option autoImplicit false

/-!
# Fixed field of the finite changed-uniformizer Artin candidate

Inside the finite standard/changed compositum, the cyclic subgroup generated
by the inverse completed Frobenius has fixed field exactly the changed
Lubin--Tate factor.  Thus the automorphisms over the changed factor are
precisely the powers of the finite Artin candidate.
-/

noncomputable section

namespace LubinTate

open LocalFieldTheory.DiscreteValuationField
open LocalFieldTheory.DiscreteValuationField.Examples.Qp

/-- The changed fixed field, now regarded as an intermediate field of the
finite standard/changed compositum. -/
def padicCompletedChangedFieldInStandardChangedCompositum
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    IntermediateField ℚ_[p]
      (padicCompletedStandardChangedCompositum p u n) :=
  (padicCompletedChangedUniformizerFixedField p u n).restrict
    (show
      padicCompletedChangedUniformizerFixedField p u n ≤
        padicCompletedStandardChangedCompositum p u n from
      le_sup_right)

/-- The fixed field of the cyclic finite Artin candidate is the actual
changed-uniformizer factor. -/
theorem
    padicCompletedChangedUniformizerArtinCandidate_fixedField_eq_changed
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    IntermediateField.fixedField
        (Subgroup.zpowers
          (padicCompletedChangedUniformizerArtinCandidate p u n)) =
      padicCompletedChangedFieldInStandardChangedCompositum p u n := by
  let E := padicCompletedLevelField p n
  let T := padicCompletedChangedUniformizerFixedField p u n
  let M := padicCompletedStandardChangedCompositum p u n
  let δ :=
    padicCompletedChangedUniformizerFrobeniusAlgEquiv p u n
  let τ :=
    padicCompletedChangedUniformizerArtinCandidate p u n
  apply le_antisymm
  · intro x hx
    have hτ :
        τ x = x := by
      exact
        (IntermediateField.mem_fixedField_iff
          (H := Subgroup.zpowers τ) x).1 hx τ
          (Subgroup.mem_zpowers τ)
    have hτAmbient :
        δ.symm (x : E) = (x : E) := by
      have hcoe := congrArg (fun z : M => (z : E)) hτ
      change δ.symm (x : E) = (x : E) at hcoe
      exact hcoe
    have hδAmbient :
        δ (x : E) = (x : E) := by
      have h := congrArg δ hτAmbient
      simpa only [δ, AlgEquiv.apply_symm_apply] using h.symm
    rw [padicCompletedChangedFieldInStandardChangedCompositum,
      IntermediateField.mem_restrict]
    change
      (x : E) ∈ IntermediateField.fixedField
        (padicCompletedChangedUniformizerFrobeniusSubgroup p u n)
    rw [IntermediateField.mem_fixedField_iff]
    intro σ hσ
    obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hσ
    have hfixed :
        (x : E) ∈ MulAction.fixedBy E δ := by
      rw [MulAction.mem_fixedBy]
      exact hδAmbient
    exact MulAction.mem_fixedBy_zpow hfixed j
  · intro x hx
    rw [IntermediateField.mem_fixedField_iff]
    intro σ hσ
    obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hσ
    have hxT : (x : E) ∈ T := by
      simpa only [padicCompletedChangedFieldInStandardChangedCompositum,
        IntermediateField.mem_restrict] using hx
    let y : T := ⟨(x : E), hxT⟩
    have hτ :
        τ x = x := by
      have hy :=
        padicCompletedChangedUniformizerArtinCandidate_fixedField
          p u n y
      apply Subtype.ext
      exact congrArg
        (fun z : M => (z : E)) hy
    have hfixed :
        x ∈ MulAction.fixedBy M τ := by
      rw [MulAction.mem_fixedBy]
      exact hτ
    exact MulAction.mem_fixedBy_zpow hfixed j

/-- The relative Galois group of the finite standard/changed compositum over
the changed factor is cyclic and generated by the finite Artin candidate. -/
theorem
    padicCompletedChangedUniformizerArtinCandidate_zpowers_eq_fixingSubgroup
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Subgroup.zpowers
        (padicCompletedChangedUniformizerArtinCandidate p u n) =
      (padicCompletedChangedFieldInStandardChangedCompositum
        p u n).fixingSubgroup := by
  let τ :=
    padicCompletedChangedUniformizerArtinCandidate p u n
  calc
    Subgroup.zpowers τ =
        (IntermediateField.fixedField
          (Subgroup.zpowers τ)).fixingSubgroup :=
      (IntermediateField.fixingSubgroup_fixedField
        (Subgroup.zpowers τ)).symm
    _ =
        (padicCompletedChangedFieldInStandardChangedCompositum
          p u n).fixingSubgroup := by
      rw [
        padicCompletedChangedUniformizerArtinCandidate_fixedField_eq_changed]

/-- Over the changed field itself, the relative finite Artin candidate
generates the full relative Galois group. -/
theorem
    padicCompletedChangedUniformizerRelativeArtinCandidate_zpowers_eq_top
    (p : ℕ) [Fact p.Prime]
    (u : (padicLocalField p).valuationSubringˣ) (n : ℕ) :
    Subgroup.zpowers
        (padicCompletedChangedUniformizerRelativeArtinCandidate p u n) =
      ⊤ := by
  let D := padicCompletedChangedUniformizerFixedField p u n
  let M := padicCompletedStandardChangedCompositum p u n
  let Dinside :=
    padicCompletedChangedFieldInStandardChangedCompositum p u n
  let τ :=
    padicCompletedChangedUniformizerRelativeArtinCandidate p u n
  let σ :=
    padicCompletedChangedUniformizerArtinCandidate p u n
  let forget : Gal(M / D) →* Gal(M / ℚ_[p]) :=
    AlgEquiv.restrictScalarsHom ℚ_[p]
  apply top_unique
  intro g _
  have hfix : forget g ∈ Dinside.fixingSubgroup := by
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro z hz
    have hzD :
        (((z : M) : padicCompletedLevelField p n)) ∈ D := by
      simpa only [Dinside,
        padicCompletedChangedFieldInStandardChangedCompositum,
        IntermediateField.mem_restrict] using hz
    let x : D :=
      ⟨((z : M) :
          padicCompletedLevelField p n), hzD⟩
    have hx : algebraMap D M x = z := by
      apply Subtype.ext
      rfl
    change g z = z
    rw [← hx]
    exact g.commutes x
  have hpower : forget g ∈ Subgroup.zpowers σ := by
    rw [
      padicCompletedChangedUniformizerArtinCandidate_zpowers_eq_fixingSubgroup]
    exact hfix
  obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp hpower
  apply Subgroup.mem_zpowers_iff.mpr
  refine ⟨j, ?_⟩
  apply AlgEquiv.restrictScalars_injective ℚ_[p]
  change forget (τ ^ j) = forget g
  rw [map_zpow]
  change σ ^ j = forget g
  exact hj

end LubinTate

end
