import ProCGroups.FoxDifferential.Completed.ProCIntegerCoefficients.Core
import Mathlib.RingTheory.Ideal.Basic

set_option autoImplicit false

/-!
# Fox differential: completed — \(\mathbb{Z}_C\) coefficients — augmentation ideal — basic

The principal declarations in this module are:

- `zcCompletedGroupAlgebraStandardAugmentationIdeal`
  The algebraic ideal generated by the standard completed augmentation generators \([h]-1\). The
  completed augmentation ideal itself is the kernel of the completed augmentation map, defined in
  the completed augmentation construction with \(\mathbb{Z}_C\)-coefficients.
- `zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal`
  The completed Fox boundary, with codomain restricted to the algebraic standard
  augmentation-generator ideal.
- `zcCompletedGroupAlgebraStandardAugmentationIdeal_eq_span`
  The standard completed augmentation-generator ideal, viewed as a submodule, is the submodule span
  of the standard generators.
- `zcGroupLike_sub_one_mem_standardAugmentationIdeal`
  Each completed group-like generator \([h]-1\) lies in the algebraic standard
  augmentation-generator ideal.
-/

namespace FoxDifferential

noncomputable section

universe u

section AugmentationIdeal

variable (C : ProCGroups.FiniteGroupClass.{u})
variable (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/--
The algebraic ideal generated by the standard completed augmentation generators \([h]-1\). The
completed augmentation ideal itself is the kernel of the completed augmentation map, defined in
the completed augmentation construction with \(\mathbb{Z}_C\)-coefficients.
-/
def zcCompletedGroupAlgebraStandardAugmentationIdeal :
    Ideal (ZCCompletedGroupAlgebra C H) :=
  Ideal.span (Set.range fun h : H => zcGroupLike C H h - 1)

/--
The standard completed augmentation-generator ideal, viewed as a submodule, is the submodule
span of the standard generators.
-/
theorem zcCompletedGroupAlgebraStandardAugmentationIdeal_eq_span :
    ((zcCompletedGroupAlgebraStandardAugmentationIdeal C H :
      Ideal (ZCCompletedGroupAlgebra C H)) :
      Submodule (ZCCompletedGroupAlgebra C H) (ZCCompletedGroupAlgebra C H)) =
      Submodule.span (ZCCompletedGroupAlgebra C H)
        (Set.range fun h : H => zcGroupLike C H h - 1) :=
  rfl

/--
Each completed group-like generator \([h]-1\) lies in the algebraic standard
augmentation-generator ideal.
-/
theorem zcGroupLike_sub_one_mem_standardAugmentationIdeal (h : H) :
    zcGroupLike C H h - 1 ∈ zcCompletedGroupAlgebraStandardAugmentationIdeal C H :=
  Ideal.subset_span (Set.mem_range_self h)

variable {G : Type u} [Group G]

/-- The completed Fox boundary lies in the algebraic standard augmentation-generator ideal. -/
theorem zcCompletedGroupAlgebraBoundary_mem_standardAugmentationIdeal
    (ψ : G →* H) (g : G) :
    zcCompletedGroupAlgebraBoundary C ψ g ∈
      zcCompletedGroupAlgebraStandardAugmentationIdeal C H := by
  change zcGroupLike C H (ψ g) - 1 ∈
    zcCompletedGroupAlgebraStandardAugmentationIdeal C H
  exact zcGroupLike_sub_one_mem_standardAugmentationIdeal C H (ψ g)

/--
The completed Fox boundary, with codomain restricted to the algebraic standard
augmentation-generator ideal.
-/
def zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal
    (ψ : G →* H) :
    ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ)
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H) where
  toFun g :=
    ⟨zcCompletedGroupAlgebraBoundary C ψ g,
      zcCompletedGroupAlgebraBoundary_mem_standardAugmentationIdeal C H ψ g⟩
  map_mul' g h := by
    apply Subtype.ext
    exact (zcCompletedGroupAlgebraBoundary C ψ).map_mul g h

/--
The completed Fox tail is restricted to the algebraic standard augmentation ideal as its
codomain.
-/
def zcToStdAugIdeal
    (ψ : G →* H) :
    ZCCompletedDifferentialModule C ψ →ₗ[ZCCompletedGroupAlgebra C H]
      zcCompletedGroupAlgebraStandardAugmentationIdeal C H :=
  crossedHomModuleLift
    (A := zcCompletedGroupAlgebraStandardAugmentationIdeal C H)
    (zcCompletedGroupAlgebraScalar C ψ)
    (zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal C H ψ)

/--
The value of the standard-augmentation-ideal-valued completed Fox tail is the underlying
completed group-algebra tail.
-/
@[simp]
theorem zcToStdAugIdeal_val
    (ψ : G →* H) (x : ZCCompletedDifferentialModule C ψ) :
    ((zcToStdAugIdeal C H ψ x :
      ZCCompletedGroupAlgebra C H)) =
      zcToCompletedGroupAlgebra C ψ x := by
  let L := zcToStdAugIdeal C H ψ
  have hL :
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H).subtype.comp L =
        zcToCompletedGroupAlgebra C ψ := by
    apply crossedDifferentialModuleHom_ext
      (A := ZCCompletedGroupAlgebra C H)
      (zcCompletedGroupAlgebraScalar C ψ)
    intro g
    simp only [zcToStdAugIdeal, LinearMap.coe_comp, Submodule.coe_subtype,
      Function.comp_apply, crossedHomModuleLift_universal,
      zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal, L]
    exact (zcToCompletedGroupAlgebra_universal C ψ g).symm
  simpa [L] using congrArg (fun f => f x) hL

/-- The completed Fox tail lands in the algebraic standard augmentation-generator ideal. -/
theorem zcToCompletedGroupAlgebra_mem_standardAugmentationIdeal
    (ψ : G →* H) (x : ZCCompletedDifferentialModule C ψ) :
    zcToCompletedGroupAlgebra C ψ x ∈
      zcCompletedGroupAlgebraStandardAugmentationIdeal C H := by
  simpa [zcToStdAugIdeal_val] using
    (zcToStdAugIdeal C H ψ x).2

/--
The range of the completed Fox tail is contained in the algebraic standard
augmentation-generator ideal.
-/
theorem zcToCompletedGroupAlgebra_range_le_standardAugmentationIdeal
    (ψ : G →* H) :
    LinearMap.range (zcToCompletedGroupAlgebra C ψ) ≤
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H :
        Submodule (ZCCompletedGroupAlgebra C H) (ZCCompletedGroupAlgebra C H)) := by
  rintro x ⟨m, rfl⟩
  exact zcToCompletedGroupAlgebra_mem_standardAugmentationIdeal C H ψ m

/--
If \(\psi\) is surjective, the completed Fox tail has range exactly the algebraic standard
augmentation-generator ideal.
-/
theorem zcToCompletedGroupAlgebra_range_eq_standardAugmentationIdeal_of_surjective
    (ψ : G →* H) (hψ : Function.Surjective ψ) :
    LinearMap.range (zcToCompletedGroupAlgebra C ψ) =
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H :
        Submodule (ZCCompletedGroupAlgebra C H) (ZCCompletedGroupAlgebra C H)) := by
  refine le_antisymm
    (zcToCompletedGroupAlgebra_range_le_standardAugmentationIdeal C H ψ) ?_
  rw [zcCompletedGroupAlgebraStandardAugmentationIdeal_eq_span]
  refine Submodule.span_le.2 ?_
  rintro _ ⟨h, rfl⟩
  rcases hψ h with ⟨g, rfl⟩
  refine ⟨zcUniversalDifferential C ψ g, ?_⟩
  rw [zcToCompletedGroupAlgebra_universal]
  rfl

/--
If \(\psi\) is surjective, the standard-augmentation-ideal-valued completed Fox tail is
surjective.
-/
theorem zcToStdAugIdeal_surjective_of_surjective
    (ψ : G →* H) (hψ : Function.Surjective ψ) :
    Function.Surjective
      (zcToStdAugIdeal C H ψ) := by
  intro y
  have hy :
      (y : ZCCompletedGroupAlgebra C H) ∈
        LinearMap.range (zcToCompletedGroupAlgebra C ψ) := by
    rw [zcToCompletedGroupAlgebra_range_eq_standardAugmentationIdeal_of_surjective
      C H ψ hψ]
    exact y.2
  rcases hy with ⟨x, hx⟩
  refine ⟨x, Subtype.ext ?_⟩
  simpa [zcToStdAugIdeal_val] using hx

end AugmentationIdeal

end

end FoxDifferential
