import Mathlib.SetTheory.Cardinal.Finite
import ValuedFieldTheory.LocalField.NonarchimedeanLocalField.PrincipalUnitQuotients

set_option autoImplicit false

namespace LocalFieldTheory

noncomputable section

universe u

open scoped ValuativeRel

/-! ### Residue and maximal-ideal successive quotients -/

/-- Additive identification of the residue field with `𝒪[K]/𝓂[K]`.

This is definitional for mathlib's local-ring residue field, but we expose it as
part of the local CFT boundary so later files do not depend on unfolding the
residue-field definition. -/
def integerRingModMaximalIdealAddEquivResidue
    (K : Type u) [Field K] [ValuativeRel K] :
    (𝒪[K] ⧸ (𝓂[K] : Ideal 𝒪[K])) ≃+ 𝓀[K] :=
  AddEquiv.refl _

/-- The additive equivalence from the integer ring modulo its maximal ideal sends a representative
to its residue class. -/
@[simp]
theorem integerRingModMaximalIdealAddEquivResidue_mk
    (K : Type u) [Field K] [ValuativeRel K] (x : 𝒪[K]) :
    integerRingModMaximalIdealAddEquivResidue K
        (Ideal.Quotient.mk (𝓂[K] : Ideal 𝒪[K]) x) =
      IsLocalRing.residue 𝒪[K] x :=
  rfl

/-- An integer-ring element has zero residue exactly when it belongs to the maximal ideal. -/
theorem residue_eq_zero_iff_mem_maximalIdeal
    (K : Type u) [Field K] [ValuativeRel K] (x : 𝒪[K]) :
    IsLocalRing.residue 𝒪[K] x = 0 ↔ x ∈ (𝓂[K] : Ideal 𝒪[K]) :=
  IsLocalRing.residue_eq_zero_iff x

/-- A chosen DVR uniformizer of the valuation ring of a nonarchimedean local
field, viewed as an irreducible element of `𝒪[K]`. -/
def chosenIntegerRingUniformizer
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] : 𝒪[K] :=
  Classical.choose (IsDiscreteValuationRing.exists_irreducible 𝒪[K])

/-- The chosen integer-ring uniformizer is irreducible in the discrete valuation ring. -/
theorem chosenIntegerRingUniformizer_irreducible
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    Irreducible (chosenIntegerRingUniformizer K) :=
  Classical.choose_spec (IsDiscreteValuationRing.exists_irreducible 𝒪[K])

/-- The maximal ideal is the principal ideal generated by the chosen integer-ring uniformizer. -/
theorem chosenIntegerRingUniformizer_maximalIdeal_eq
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    (𝓂[K] : Ideal 𝒪[K]) = Ideal.span ({chosenIntegerRingUniformizer K} : Set 𝒪[K]) :=
  (chosenIntegerRingUniformizer_irreducible K).maximalIdeal_eq

/-- The chosen DVR uniformizer of `𝒪[K]`, viewed as a nonzero field unit.

This is the source object for the local class-field decomposition by powers of
a prime element.  Valuation normalization is proved separately; it is not an
extra argument of this definition. -/
def integerRingUniformizerFieldUnit
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] : Kˣ :=
  Units.mk0 (((chosenIntegerRingUniformizer K : 𝒪[K]) : K)) (by
    intro h
    exact (chosenIntegerRingUniformizer_irreducible K).ne_zero (Subtype.ext h))

/-- The field unit associated to the chosen integer-ring uniformizer has the same underlying field
element. -/
@[simp]
theorem integerRingUniformizerFieldUnit_coe
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    ((integerRingUniformizerFieldUnit K : Kˣ) : K) =
      (((chosenIntegerRingUniformizer K : 𝒪[K]) : K)) :=
  rfl

/-- The inverse of the chosen DVR uniformizer, as a field unit.

With the normalized additive valuation used by `valuationMap`, this is the
element expected to have value `1`.  The proof of that normalization is the next
source-producing frontier. -/
def inverseIntegerRingUniformizerFieldUnit
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] : Kˣ :=
  (integerRingUniformizerFieldUnit K)⁻¹

/-- The inverse uniformizer field unit coerces to the inverse of the chosen uniformizer. -/
@[simp]
theorem inverseIntegerRingUniformizerFieldUnit_coe
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    ((inverseIntegerRingUniformizerFieldUnit K : Kˣ) : K) =
      (((chosenIntegerRingUniformizer K : 𝒪[K]) : K))⁻¹ :=
  rfl

private lemma withZeroMultiplicativeInt_le_of_lt_one
    (δ : WithZero (Multiplicative Int)) (hδ : δ < 1) :
    δ ≤ ((Multiplicative.ofAdd (-1 : Int) : Multiplicative Int) :
      WithZero (Multiplicative Int)) := by
  cases δ using WithZero.recZeroCoe with
  | zero => exact bot_le
  | coe d =>
      rw [WithZero.coe_le_coe]
      rw [← Multiplicative.toAdd_le]
      change Multiplicative.toAdd d ≤ (-1 : Int)
      have hdlt : Multiplicative.toAdd d < (0 : Int) := by
        have h' : d < (1 : Multiplicative Int) := by
          simpa using hδ
        change Multiplicative.toAdd d < Multiplicative.toAdd (1 : Multiplicative Int)
        exact Multiplicative.toAdd_lt.mpr h'
      omega

private lemma withZeroMultiplicativeInt_maximal_lt_one_eq_ofAdd_neg_one
    {a : WithZero (Multiplicative Int)} (ha : a < 1)
    (hmax : ∀ δ : WithZero (Multiplicative Int), δ < 1 → δ ≤ a) :
    a = ((Multiplicative.ofAdd (-1 : Int) : Multiplicative Int) :
      WithZero (Multiplicative Int)) := by
  apply le_antisymm
  · exact withZeroMultiplicativeInt_le_of_lt_one a ha
  · apply hmax
    rw [← WithZero.coe_one, WithZero.coe_lt_coe]
    change (-1 : Int) < 0
    omega

private theorem valueGroupWithZeroIsoInt_eq_of_maximal_lt_one
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    {a : ValuativeRel.ValueGroupWithZero K} (ha : a < 1)
    (hmax : ∀ δ : ValuativeRel.ValueGroupWithZero K, δ < 1 → δ ≤ a) :
    IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K a =
      ((Multiplicative.ofAdd (-1 : Int) : Multiplicative Int) :
        WithZero (Multiplicative Int)) := by
  let φ := IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K
  apply withZeroMultiplicativeInt_maximal_lt_one_eq_ofAdd_neg_one
  · simpa using φ.strictMono ha
  · intro δ hδ
    let ε : ValuativeRel.ValueGroupWithZero K := φ.symm δ
    have hε : ε < 1 := by
      have h := φ.symm.strictMono hδ
      simpa using h
    have hle : ε ≤ a := hmax ε hε
    have hle' := φ.strictMono.monotone hle
    dsimp [ε, φ] at hle'
    simpa using hle'

/-- any prime element of the valuation ring has
multiplicative value `ofAdd (-1)` under the local-field normalization.

The proof is the DVR argument used in this construction: `𝓂 = (ϖ)`, so every
valuation value below `1` is bounded by the value of `ϖ`; in the normalized
value group this maximal element below `1` is `ofAdd (-1)`. -/
theorem valueGroupWithZeroIsoInt_of_integerRing_irreducible
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ) :
    IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K
        (ValuativeRel.valuation K ((ϖ : 𝒪[K]) : K)) =
      ((Multiplicative.ofAdd (-1 : Int) : Multiplicative Int) :
        WithZero (Multiplicative Int)) := by
  apply valueGroupWithZeroIsoInt_eq_of_maximal_lt_one K
  · simpa using (Valuation.integer.v_irreducible_lt_one
      (v := ValuativeRel.valuation K) hϖ)
  · intro δ hδ
    obtain ⟨x, hx⟩ := ValuativeRel.valuation_surjective (K := K) δ
    by_cases hx0 : x = 0
    · have hδ0 : δ = 0 := by
        simpa [hx0] using hx.symm
      rw [hδ0]
      exact bot_le
    · let y : 𝒪[K] := ⟨x, by
        change ValuativeRel.valuation K x ≤ 1
        rw [hx]
        exact le_of_lt hδ⟩
      have hylt : ValuativeRel.valuation K (y : K) < 1 := by
        change ValuativeRel.valuation K x < 1
        simpa [hx]
      have hynot : ¬ IsUnit y := by
        rw [Valuation.Integer.not_isUnit_iff_valuation_lt_one
          (v := ValuativeRel.valuation K)]
        exact hylt
      have hym : y ∈ (𝓂[K] : Ideal 𝒪[K]) := by
        rw [IsLocalRing.mem_maximalIdeal]
        simpa [nonunits] using hynot
      have hyspan : y ∈
          (Ideal.span ({ϖ} : Set 𝒪[K]) : Ideal 𝒪[K]) := by
        simpa [hϖ.maximalIdeal_eq] using hym
      have hset := Valuation.integer.coe_span_singleton_eq_setOfPred_le_v_coe
        (v := ValuativeRel.valuation K) ϖ
      have hyle : ValuativeRel.valuation K (y : K) ≤
          ValuativeRel.valuation K ((ϖ : 𝒪[K]) : K) := by
        have hyspanSet : y ∈
            ((Ideal.span ({ϖ} : Set 𝒪[K]) : Ideal 𝒪[K]) : Set 𝒪[K]) := hyspan
        rw [hset] at hyspanSet
        exact hyspanSet
      simpa [y, hx] using hyle

/-- A field unit whose value is represented by a valuation-ring prime element
has normalized additive value `-1`. -/
theorem v_integerRingIrreducibleFieldUnit
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (u : Kˣ) (hu : (u : K) = ((ϖ : 𝒪[K]) : K)) :
    LocalFieldTheory.IsNonarchimedeanLocalField.v K (Additive.ofMul u) = -1 := by
  dsimp [LocalFieldTheory.IsNonarchimedeanLocalField.v]
  have hne :
      IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K
          (ValuativeRel.valuation K ((u : Kˣ) : K)) ≠ 0 := by
    rw [hu]
    simp [hϖ.ne_zero]
  have hunzero :
      WithZero.unzero
        (x := IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K
          (ValuativeRel.valuation K ((u : Kˣ) : K))) hne =
        (Multiplicative.ofAdd (-1 : Int) : Multiplicative Int) := by
    apply WithZero.coe_injective
    rw [WithZero.coe_unzero]
    rw [hu]
    simpa using valueGroupWithZeroIsoInt_of_integerRing_irreducible K ϖ hϖ
  rw [hunzero]
  simp

/-- The inverse of a field unit represented by a valuation-ring prime element
has normalized additive value `1`. -/
theorem v_integerRingIrreducibleFieldUnit_inv
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (u : Kˣ) (hu : (u : K) = ((ϖ : 𝒪[K]) : K)) :
    LocalFieldTheory.IsNonarchimedeanLocalField.v K (Additive.ofMul u⁻¹) = 1 := by
  rw [LocalFieldTheory.IsNonarchimedeanLocalField.v_inv]
  rw [v_integerRingIrreducibleFieldUnit K ϖ hϖ u hu]
  norm_num

/-- The chosen prime element of the valuation ring has
multiplicative value `ofAdd (-1)` under the local-field normalization.

This is the source-producing normalization for the later decomposition
`x = u * π^m`; it is proved from the DVR fact `𝓂 = (π)`, not assumed as a
separate uniformizer-value input. -/
theorem valueGroupWithZeroIsoInt_chosenIntegerRingUniformizer
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    IsNonarchimedeanLocalField.valueGroupWithZeroIsoInt K
        (ValuativeRel.valuation K ((chosenIntegerRingUniformizer K : 𝒪[K]) : K)) =
      ((Multiplicative.ofAdd (-1 : Int) : Multiplicative Int) :
        WithZero (Multiplicative Int)) :=
  valueGroupWithZeroIsoInt_of_integerRing_irreducible K
    (chosenIntegerRingUniformizer K) (chosenIntegerRingUniformizer_irreducible K)

/-- The chosen valuation-ring prime element has normalized additive value `-1`
as a field unit.  We use the inverse convention for a positive
uniformizer in the exact sequence. -/
theorem v_integerRingUniformizerFieldUnit
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    LocalFieldTheory.IsNonarchimedeanLocalField.v K
      (Additive.ofMul (integerRingUniformizerFieldUnit K)) = -1 := by
  exact v_integerRingIrreducibleFieldUnit K
    (chosenIntegerRingUniformizer K) (chosenIntegerRingUniformizer_irreducible K)
    (integerRingUniformizerFieldUnit K) rfl

/-- The inverse of the chosen valuation-ring prime element has normalized
additive value `1`.  This is the source object needed before using powers of a
uniformizer in the local class-field calculation. -/
theorem v_inverseIntegerRingUniformizerFieldUnit
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    LocalFieldTheory.IsNonarchimedeanLocalField.v K
      (Additive.ofMul (inverseIntegerRingUniformizerFieldUnit K)) = 1 := by
  rw [inverseIntegerRingUniformizerFieldUnit]
  exact v_integerRingIrreducibleFieldUnit_inv K
    (chosenIntegerRingUniformizer K) (chosenIntegerRingUniformizer_irreducible K)
    (integerRingUniformizerFieldUnit K) rfl

/-- Denominator clearing in the valuation ring:
every element of `K` becomes integral after multiplying by a sufficiently high
power of the chosen prime element of `𝒪[K]`.

This local-DVR denominator-clearing theorem supports normal-basis lattice bounds; the
proof uses the fraction representation over `𝒪[K]` and the DVR factorization of
the denominator into a unit times a power of the prime element. -/
theorem exists_chosenIntegerRingUniformizer_pow_mul_mem_integerRing
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (x : K) :
    ∃ n : Nat,
      (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n) * x ∈ 𝒪[K] := by
  obtain ⟨a, b, hb, hfrac⟩ := IsFractionRing.div_surjective (A := 𝒪[K]) x
  have hb_ne : b ≠ 0 := nonZeroDivisors.ne_zero hb
  obtain ⟨n, u, hb_factor⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hb_ne
      (chosenIntegerRingUniformizer_irreducible K)
  refine ⟨n, ?_⟩
  rw [← hfrac, hb_factor]
  have hϖ_ne : (((chosenIntegerRingUniformizer K : 𝒪[K]) : K)) ≠ 0 := by
    intro h
    exact (chosenIntegerRingUniformizer_irreducible K).ne_zero
      ((IsFractionRing.injective 𝒪[K] K) h)
  have hϖ_pow_ne :
      (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n) ≠ 0 :=
    pow_ne_zero n hϖ_ne
  have hu_ne : (((u : 𝒪[K]) : K)) ≠ 0 := by
    intro h
    exact u.ne_zero ((IsFractionRing.injective 𝒪[K] K) h)
  have hclear :
      (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n) *
          ((a : K) /
            (((u : 𝒪[K]) * chosenIntegerRingUniformizer K ^ n : 𝒪[K]) : K)) =
        ((a * ↑u⁻¹ : 𝒪[K]) : K) := by
    calc
      (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n) *
          ((a : K) /
            (((u : 𝒪[K]) * chosenIntegerRingUniformizer K ^ n : 𝒪[K]) : K))
          =
          (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n) *
            ((a : K) / (((u : 𝒪[K]) : K) *
              (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n))) := by
            simp
      _ = (a : K) * (((u : 𝒪[K]) : K))⁻¹ := by
            field_simp [hu_ne, hϖ_pow_ne]
      _ = ((a * ↑u⁻¹ : 𝒪[K]) : K) := by
            have hu_inv :
                (((↑u⁻¹ : 𝒪[K]) : K)) = (((u : 𝒪[K]) : K))⁻¹ := by
              exact map_units_inv (algebraMap 𝒪[K] K) u
            rw [← hu_inv]
            simp
  change (((chosenIntegerRingUniformizer K : 𝒪[K]) : K) ^ n) *
      ((a : K) /
        (((u : 𝒪[K]) * chosenIntegerRingUniformizer K ^ n : 𝒪[K]) : K)) ∈ 𝒪[K]
  rw [hclear]
  exact (a * ↑u⁻¹ : 𝒪[K]).2

/-- If a uniformizer is irreducible, each maximal-ideal power is generated by the corresponding
power of that uniformizer. -/
theorem maximalIdeal_pow_eq_span_uniformizer_pow_of_irreducible
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ) (n : Nat) :
    (𝓂[K] ^ n : Ideal 𝒪[K]) = Ideal.span ({ϖ ^ n} : Set 𝒪[K]) := by
  rw [hϖ.maximalIdeal_eq, Ideal.span_singleton_pow]

/-- Each power of the maximal ideal is generated by the matching power of the chosen uniformizer. -/
theorem maximalIdeal_pow_eq_span_uniformizer_pow
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) :
    (𝓂[K] ^ n : Ideal 𝒪[K]) =
      Ideal.span ({chosenIntegerRingUniformizer K ^ n} : Set 𝒪[K]) :=
  maximalIdeal_pow_eq_span_uniformizer_pow_of_irreducible K
    (chosenIntegerRingUniformizer K) (chosenIntegerRingUniformizer_irreducible K) n

/-- Multiplying an integer by the `n`-th uniformizer power places it in the `n`-th maximal-ideal
power. -/
theorem mul_uniformizer_pow_mem_maximalIdeal_pow
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (r : 𝒪[K]) :
    r * ϖ ^ n ∈ (𝓂[K] ^ n : Ideal 𝒪[K]) := by
  rw [maximalIdeal_pow_eq_span_uniformizer_pow_of_irreducible K ϖ hϖ n]
  rw [Ideal.mem_span_singleton]
  exact ⟨r, by rw [mul_comm]⟩

/-- A multiple of the `n`-th uniformizer power lies in the next ideal power exactly when its
coefficient lies in the maximal ideal. -/
theorem mul_uniformizer_pow_mem_maximalIdeal_pow_succ_iff
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (r : 𝒪[K]) :
    r * ϖ ^ n ∈ (𝓂[K] ^ (n + 1) : Ideal 𝒪[K]) ↔
      r ∈ (𝓂[K] : Ideal 𝒪[K]) := by
  rw [hϖ.maximalIdeal_eq, Ideal.span_singleton_pow]
  rw [Ideal.mem_span_singleton, Ideal.mem_span_singleton]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    have hne : ϖ ^ n ≠ 0 := pow_ne_zero n hϖ.ne_zero
    have hcancel : r * ϖ ^ n = (ϖ * c) * ϖ ^ n := by
      calc
        r * ϖ ^ n = ϖ ^ (n + 1) * c := hc
        _ = (ϖ * c) * ϖ ^ n := by
          rw [pow_succ']
          ring
    exact mul_right_cancel₀ hne hcancel
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    rw [hc]
    rw [pow_succ']
    ring

/-- Multiplication by `ϖ^n`, landing in the ideal `𝓂^n`. -/
def maximalIdealPowMulUniformizerPowMap
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) :
    𝒪[K] →ₗ[𝒪[K]] ((𝓂[K] ^ n : Ideal 𝒪[K]) : Type u) where
  toFun r := ⟨r * ϖ ^ n, mul_uniformizer_pow_mem_maximalIdeal_pow K ϖ hϖ n r⟩
  map_add' r s := by
    ext
    simp [add_mul]
  map_smul' a r := by
    ext
    simp [mul_assoc]

/-- The map into a maximal-ideal power multiplies its input by the corresponding uniformizer power.
The map into a maximal-ideal power multiplies its input by the corresponding uniformizer power. -/
@[simp]
theorem maximalIdealPowMulUniformizerPowMap_apply
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (r : 𝒪[K]) :
    (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r : 𝒪[K]) =
      r * ϖ ^ n :=
  rfl

/-- The map `𝒪[K] → 𝓂^n/𝓂^(n+1)` induced by multiplication by `ϖ^n`. -/
def maximalIdealPowSuccQuotMulUniformizerPowMap
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) :
    𝒪[K] →ₗ[𝒪[K]] MaximalIdealPowSuccQuot K n :=
  (maximalIdealPowSuccQuotMk K n).comp
    (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n)

/-- On successive ideal quotients, multiplication by a uniformizer power sends a residue
representative to its ideal-quotient class. -/
@[simp]
theorem maximalIdealPowSuccQuotMulUniformizerPowMap_apply
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (r : 𝒪[K]) :
    maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n r =
      maximalIdealPowSuccQuotMk K n
        (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r) :=
  rfl

/-- The kernel of multiplication into a successive ideal quotient is the maximal ideal. -/
theorem maximalIdealPowSuccQuotMulUniformizerPowMap_ker
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) :
    LinearMap.ker (maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n) =
      (𝓂[K] : Ideal 𝒪[K]) := by
  ext r
  rw [LinearMap.mem_ker]
  change maximalIdealPowSuccQuotMk K n
      (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r) = 0 ↔
    r ∈ (𝓂[K] : Ideal 𝒪[K])
  rw [maximalIdealPowSuccQuotMk_eq_zero_iff]
  change r * ϖ ^ n ∈ (𝓂[K] ^ (n + 1) : Ideal 𝒪[K]) ↔
    r ∈ (𝓂[K] : Ideal 𝒪[K])
  exact mul_uniformizer_pow_mem_maximalIdeal_pow_succ_iff K ϖ hϖ n r

/-- Every class in a successive maximal-ideal quotient is represented by a uniformizer power times
an integer. -/
theorem maximalIdealPowSuccQuotMulUniformizerPowMap_surjective
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) :
    Function.Surjective (maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n) := by
  intro x
  refine MaximalIdealPowSuccQuot.inductionOn n
    (motive := fun x' =>
      ∃ r, maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n r = x')
    x ?_
  intro a
  have ha_span : (a : 𝒪[K]) ∈ Ideal.span ({ϖ ^ n} : Set 𝒪[K]) := by
    simpa [maximalIdeal_pow_eq_span_uniformizer_pow_of_irreducible K ϖ hϖ n] using a.2
  rcases (Ideal.mem_span_singleton.mp ha_span) with ⟨r, hr⟩
  refine ⟨r, ?_⟩
  change maximalIdealPowSuccQuotMk K n
      (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r) =
    maximalIdealPowSuccQuotMk K n a
  have hrep : maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r = a := by
    ext
    simp [maximalIdealPowMulUniformizerPowMap, hr, mul_comm]
  rw [hrep]

/-- The DVR comparison `𝒪[K]/𝓂[K] ≃ 𝓂^n/𝓂^(n+1)` attached to an irreducible
uniformizer `ϖ`. -/
def residueLinearEquivMaximalIdealPowSuccQuotOfIrreducible
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) :
    𝓀[K] ≃ₗ[𝒪[K]] MaximalIdealPowSuccQuot K n :=
  (Submodule.quotEquivOfEq (𝓂[K] : Submodule 𝒪[K] 𝒪[K])
      (LinearMap.ker (maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n))
      (maximalIdealPowSuccQuotMulUniformizerPowMap_ker K ϖ hϖ n).symm).trans
    ((maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n).quotKerEquivOfSurjective
      (maximalIdealPowSuccQuotMulUniformizerPowMap_surjective K ϖ hϖ n))

/-- Additive form of `𝒪[K]/𝓂[K] ≃ 𝓂^n/𝓂^(n+1)`. -/
def residueAddEquivMaximalIdealPowSuccQuotOfIrreducible
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) :
    𝓀[K] ≃+ MaximalIdealPowSuccQuot K n :=
  (residueLinearEquivMaximalIdealPowSuccQuotOfIrreducible K ϖ hϖ n).toAddEquiv

/-- The residue-to-ideal-quotient equivalence sends a residue class to the class of its lift times
the uniformizer power. -/
@[simp]
theorem residueAddEquivMaximalIdealPowSuccQuotOfIrreducible_residue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (r : 𝒪[K]) :
    residueAddEquivMaximalIdealPowSuccQuotOfIrreducible K ϖ hϖ n
        (IsLocalRing.residue 𝒪[K] r) =
    maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n r := by
  let f := maximalIdealPowSuccQuotMulUniformizerPowMap K ϖ hϖ n
  let hker : (𝓂[K] : Submodule 𝒪[K] 𝒪[K]) = LinearMap.ker f :=
    (maximalIdealPowSuccQuotMulUniformizerPowMap_ker K ϖ hϖ n).symm
  change (Submodule.quotEquivOfEq (𝓂[K] : Submodule 𝒪[K] 𝒪[K])
        (LinearMap.ker f) hker).trans
      (f.quotKerEquivOfSurjective
        (maximalIdealPowSuccQuotMulUniformizerPowMap_surjective K ϖ hϖ n))
      (Submodule.Quotient.mk r) = f r
  rw [LinearEquiv.trans_apply]
  have hquot :
      Submodule.quotEquivOfEq (𝓂[K] : Submodule 𝒪[K] 𝒪[K])
          (LinearMap.ker f) hker (Submodule.Quotient.mk r) =
        (Submodule.Quotient.mk r : 𝒪[K] ⧸ LinearMap.ker f) := by
    exact Submodule.quotEquivOfEq_mk
      (p := (𝓂[K] : Submodule 𝒪[K] 𝒪[K])) (p' := LinearMap.ker f) hker r
  rw [hquot]
  rw [LinearMap.quotKerEquivOfSurjective_apply_mk]

/-- The version of `𝒪[K]/𝓂[K] ≃ 𝓂^n/𝓂^(n+1)` determined by the library's
chosen integer-ring uniformizer. -/
def chosenResidueLinearEquivMaximalIdealPowSuccQuot
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) :
    𝓀[K] ≃ₗ[𝒪[K]] MaximalIdealPowSuccQuot K n :=
  residueLinearEquivMaximalIdealPowSuccQuotOfIrreducible K
    (chosenIntegerRingUniformizer K) (chosenIntegerRingUniformizer_irreducible K) n

/-- Additive equivalence determined by the library's chosen integer-ring
uniformizer. -/
def chosenResidueAddEquivMaximalIdealPowSuccQuot
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) :
    𝓀[K] ≃+ MaximalIdealPowSuccQuot K n :=
  (chosenResidueLinearEquivMaximalIdealPowSuccQuot K n).toAddEquiv

/-- A successive maximal-ideal quotient over a local field is finite. -/
instance maximalIdealPowSuccQuot_finite
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) :
    Finite (MaximalIdealPowSuccQuot K n) :=
  Finite.of_equiv 𝓀[K] (chosenResidueAddEquivMaximalIdealPowSuccQuot K n)

/-- Every successive maximal-ideal quotient has the same cardinality as the residue field. -/
theorem maximalIdealPowSuccQuot_card_eq_residue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) :
    Nat.card (MaximalIdealPowSuccQuot K n) = Nat.card 𝓀[K] := by
  exact Nat.card_congr
    (chosenResidueAddEquivMaximalIdealPowSuccQuot K n).symm.toEquiv

/-- The unit-quotient coordinate theorem in additive form:
`U^n/U^(n+1) ≃ 𝓀[K]`, for `n ≥ 1`. -/
def principalUnitsSuccQuotAddEquivResidue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) (hn : 1 ≤ n) :
    Additive (PrincipalUnitsSuccQuot K n) ≃+ 𝓀[K] :=
  (maximalIdealPowSuccQuotAddEquivPrincipalUnitsSuccQuot K n hn).symm.trans
    (chosenResidueAddEquivMaximalIdealPowSuccQuot K n).symm

/-- The unit-quotient coordinate theorem in additive form, using a specified
irreducible uniformizer.  This avoids the independent canonical-uniformizer
choice when comparing an unramified extension with the image of a base
uniformizer upstairs. -/
def principalUnitsSuccQuotAddEquivResidueOfIrreducible
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) :
    Additive (PrincipalUnitsSuccQuot K n) ≃+ 𝓀[K] :=
  (maximalIdealPowSuccQuotAddEquivPrincipalUnitsSuccQuot K n hn).symm.trans
    (residueAddEquivMaximalIdealPowSuccQuotOfIrreducible K ϖ hϖ n).symm

/-- The inverse residue equivalence extracts the residue coordinate of a successive principal-unit
class. -/
@[simp]
theorem principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_apply
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (x : 𝓀[K]) :
    (principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn).symm x =
      principalUnitsSuccQuotOfMaximalIdealPowSuccQuotAdd K n hn
        (residueAddEquivMaximalIdealPowSuccQuotOfIrreducible K ϖ hϖ n x) :=
  rfl

/-- Applying the inverse principal-unit quotient equivalence to a residue representative recovers
that residue. -/
@[simp]
theorem principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    (principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn).symm
        (IsLocalRing.residue 𝒪[K] r) =
      Additive.ofMul
        (principalUnitsSuccQuotMk K n
          (principalUnitOneAddOfMemPowSubgroup K hn
            ((maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r :
              (𝓂[K] ^ n : Ideal 𝒪[K])) : 𝒪[K])
            (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r).2)) := by
  rw [principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_apply]
  rw [residueAddEquivMaximalIdealPowSuccQuotOfIrreducible_residue]
  rw [principalUnitsSuccQuotOfMaximalIdealPowSuccQuotAdd_apply]
  rw [maximalIdealPowSuccQuotMulUniformizerPowMap_apply]
  rw [principalUnitsSuccQuotOfMaximalIdealPowSuccQuot_mk]
  rfl

/-- The class of `1 + rϖ^n` in `U^n/U^(n+1)`, for a DVR uniformizer `ϖ`.

This is the concrete coordinate used in the unit-quotient coordinate theorem:
successive principal-unit quotients are residue-field additive quotients. -/
noncomputable def principalUnitsSuccQuotUniformizerCoord
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    PrincipalUnitsSuccQuot K n :=
  principalUnitsSuccQuotMk K n
    (principalUnitOneAddOfMemPowSubgroup K hn
      ((maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r :
        (𝓂[K] ^ n : Ideal 𝒪[K])) : 𝒪[K])
      (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r).2)

/-- The zero coordinate gives the trivial class in `U^n/U^(n+1)`. -/
@[simp]
theorem principalUnitsSuccQuotUniformizerCoord_zero
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) :
    principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn 0 = 1 := by
  change principalUnitsSuccQuotOfIdealPow K n hn
      (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n 0) = 1
  rw [map_zero]
  exact principalUnitsSuccQuotOfIdealPow_zero K n hn

/-- Uniformizer coordinates add as expected in the successive principal-unit
quotient: `1 + (r+s)ϖ^n` and `(1+rϖ^n)(1+sϖ^n)` have the same class modulo
`U^(n+1)`. -/
theorem principalUnitsSuccQuotUniformizerCoord_add
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r s : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn (r + s) =
      principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r *
        principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s := by
  change principalUnitsSuccQuotOfIdealPow K n hn
      (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n (r + s)) =
    principalUnitsSuccQuotOfIdealPow K n hn
        (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r) *
      principalUnitsSuccQuotOfIdealPow K n hn
        (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n s)
  rw [map_add]
  exact principalUnitsSuccQuotOfIdealPow_add K n hn
    (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r)
    (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n s)

/-- Additive homomorphism form of the uniformizer coordinate
`r ↦ [1 + rϖ^n]` into the successive principal-unit quotient. -/
noncomputable def principalUnitsSuccQuotUniformizerCoordAddHom
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) :
    𝒪[K] →+ Additive (PrincipalUnitsSuccQuot K n) where
  toFun r := Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r)
  map_zero' := by
    change Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn 0) = 0
    rw [principalUnitsSuccQuotUniformizerCoord_zero]
    rfl
  map_add' r s := by
    change Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn (r + s)) =
      Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) +
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s)
    rw [principalUnitsSuccQuotUniformizerCoord_add]
    rfl

/-- The uniformizer-coordinate homomorphism sends a principal-unit class to its residue-field
coordinate. -/
@[simp]
theorem principalUnitsSuccQuotUniformizerCoordAddHom_apply
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoordAddHom K ϖ hϖ n hn r =
      Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) :=
  rfl

/-- The inverse of the additive equivalence `U^n/U^(n+1) ≃ 𝓀[K]` sends the
residue of `r` to the uniformizer coordinate class `[1 + rϖ^n]`. -/
theorem principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue_coord
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    (principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn).symm
        (IsLocalRing.residue 𝒪[K] r) =
      Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) := by
  exact principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue
    K ϖ hϖ n hn r

/-- The additive equivalence `U^n/U^(n+1) ≃ 𝓀[K]` sends the uniformizer
coordinate class `[1 + rϖ^n]` to the residue of `r`. -/
theorem principalUnitsSuccQuotAddEquivResidueOfIrreducible_coord
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn
        (Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r)) =
      IsLocalRing.residue 𝒪[K] r := by
  let E := principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn
  have hcoord :
      E.symm (IsLocalRing.residue 𝒪[K] r) =
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) := by
    simpa [E] using
      principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue_coord
        K ϖ hϖ n hn r
  change E (Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r)) =
    IsLocalRing.residue 𝒪[K] r
  rw [← hcoord]
  exact E.apply_symm_apply (IsLocalRing.residue 𝒪[K] r)

/-- The coordinate homomorphism factors through reduction to the residue field,
pointwise. -/
theorem principalUnitsSuccQuotUniformizerCoordAddHom_eq_symm_residue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoordAddHom K ϖ hϖ n hn r =
      (principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn).symm
        (IsLocalRing.residue 𝒪[K] r) := by
  rw [principalUnitsSuccQuotUniformizerCoordAddHom_apply]
  exact (principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue_coord
    K ϖ hϖ n hn r).symm

/-- The coordinate homomorphism is the composite of residue reduction and the
inverse of the additive equivalence `U^n/U^(n+1) ≃ 𝓀[K]`. -/
theorem principalUnitsSuccQuotUniformizerCoordAddHom_eq_symm_comp_residue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) :
    principalUnitsSuccQuotUniformizerCoordAddHom K ϖ hϖ n hn =
      (principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn).symm.toAddMonoidHom.comp
        (IsLocalRing.residue 𝒪[K]).toAddMonoidHom := by
  ext r
  exact principalUnitsSuccQuotUniformizerCoordAddHom_eq_symm_residue K ϖ hϖ n hn r

/-- Every class in `U^n/U^(n+1)` has a uniformizer-coordinate representative
`[1 + rϖ^n]`, in additive homomorphism form. -/
theorem principalUnitsSuccQuotUniformizerCoordAddHom_surjective
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) :
    Function.Surjective (principalUnitsSuccQuotUniformizerCoordAddHom K ϖ hϖ n hn) := by
  intro y
  let E := principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn
  obtain ⟨r, hr⟩ := Ideal.Quotient.mk_surjective (E y)
  refine ⟨r, ?_⟩
  apply E.injective
  rw [principalUnitsSuccQuotUniformizerCoordAddHom_apply,
    principalUnitsSuccQuotAddEquivResidueOfIrreducible_coord]
  change Ideal.Quotient.mk (𝓂[K] : Ideal 𝒪[K]) r = E y
  exact hr

/-- Every class in `U^n/U^(n+1)` has a uniformizer-coordinate representative
`[1 + rϖ^n]`. -/
theorem principalUnitsSuccQuotUniformizerCoord_surjective
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) :
    Function.Surjective (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn) := by
  intro y
  obtain ⟨r, hr⟩ :=
    principalUnitsSuccQuotUniformizerCoordAddHom_surjective K ϖ hϖ n hn
      (Additive.ofMul y)
  refine ⟨r, ?_⟩
  change Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) =
    Additive.ofMul y at hr
  exact Additive.ofMul.injective hr

/-- In uniformizer coordinates, equality in `U^n/U^(n+1)` is exactly equality
of residues of the coefficients. -/
theorem principalUnitsSuccQuotUniformizerCoord_eq_iff_residue_eq
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r s : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r =
        principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s ↔
      IsLocalRing.residue 𝒪[K] r = IsLocalRing.residue 𝒪[K] s := by
  let E := principalUnitsSuccQuotAddEquivResidueOfIrreducible K ϖ hϖ n hn
  have hr :
      E.symm (IsLocalRing.residue 𝒪[K] r) =
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) := by
    exact principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue_coord
      K ϖ hϖ n hn r
  have hs :
      E.symm (IsLocalRing.residue 𝒪[K] s) =
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s) := by
    exact principalUnitsSuccQuotAddEquivResidueOfIrreducible_symm_residue_coord
      K ϖ hϖ n hn s
  constructor
  · intro h
    have hcoords :
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) =
          Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s) :=
      congrArg Additive.ofMul h
    have hres :
        E.symm (IsLocalRing.residue 𝒪[K] r) =
          E.symm (IsLocalRing.residue 𝒪[K] s) := by
      calc
        E.symm (IsLocalRing.residue 𝒪[K] r) =
            Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) := hr
        _ = Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s) :=
            hcoords
        _ = E.symm (IsLocalRing.residue 𝒪[K] s) := hs.symm
    exact E.symm.injective hres
  · intro h
    have hres :
        E.symm (IsLocalRing.residue 𝒪[K] r) =
          E.symm (IsLocalRing.residue 𝒪[K] s) :=
      congrArg E.symm h
    have hcoords :
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) =
          Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s) := by
      calc
        Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) =
            E.symm (IsLocalRing.residue 𝒪[K] r) := hr.symm
        _ = E.symm (IsLocalRing.residue 𝒪[K] s) := hres
        _ = Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn s) := hs
    simpa using congrArg Additive.toMul hcoords

/-- In uniformizer coordinates, the class of `1 + rϖ^n` is trivial exactly
when the coefficient has zero residue. -/
theorem principalUnitsSuccQuotUniformizerCoord_eq_one_iff_residue_eq_zero
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r = 1 ↔
      IsLocalRing.residue 𝒪[K] r = 0 := by
  rw [principalUnitsSuccQuotUniformizerCoord]
  change principalUnitsSuccQuotOfIdealPow K n hn
      (maximalIdealPowMulUniformizerPowMap K ϖ hϖ n r) = 1 ↔
    IsLocalRing.residue 𝒪[K] r = 0
  rw [principalUnitsSuccQuotOfIdealPow_eq_one_iff]
  rw [maximalIdealPowMulUniformizerPowMap_apply]
  rw [mul_uniformizer_pow_mem_maximalIdeal_pow_succ_iff K ϖ hϖ n r]
  exact (residue_eq_zero_iff_mem_maximalIdeal K r).symm

/-- In uniformizer coordinates, the class `[1 + rϖ^n]` is trivial exactly
when the coefficient lies in the maximal ideal. -/
theorem principalUnitsSuccQuotUniformizerCoord_eq_one_iff_mem_maximalIdeal
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r = 1 ↔
      r ∈ (𝓂[K] : Ideal 𝒪[K]) := by
  rw [principalUnitsSuccQuotUniformizerCoord_eq_one_iff_residue_eq_zero]
  exact residue_eq_zero_iff_mem_maximalIdeal K r

/-- Kernel criterion for the additive uniformizer-coordinate homomorphism:
`r ↦ [1 + rϖ^n]` kills exactly the maximal ideal. -/
theorem principalUnitsSuccQuotUniformizerCoordAddHom_eq_zero_iff_mem_maximalIdeal
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (ϖ : 𝒪[K]) (hϖ : Irreducible ϖ)
    (n : Nat) (hn : 1 ≤ n) (r : 𝒪[K]) :
    principalUnitsSuccQuotUniformizerCoordAddHom K ϖ hϖ n hn r = 0 ↔
      r ∈ (𝓂[K] : Ideal 𝒪[K]) := by
  constructor
  · intro h
    rw [principalUnitsSuccQuotUniformizerCoordAddHom_apply] at h
    change Additive.ofMul (principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r) =
      Additive.ofMul (1 : PrincipalUnitsSuccQuot K n) at h
    have hcoord :
        principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r = 1 :=
      Additive.ofMul.injective h
    exact (principalUnitsSuccQuotUniformizerCoord_eq_one_iff_mem_maximalIdeal
      K ϖ hϖ n hn r).1 hcoord
  · intro hr
    have hcoord :
        principalUnitsSuccQuotUniformizerCoord K ϖ hϖ n hn r = 1 :=
      (principalUnitsSuccQuotUniformizerCoord_eq_one_iff_mem_maximalIdeal
        K ϖ hϖ n hn r).2 hr
    rw [principalUnitsSuccQuotUniformizerCoordAddHom_apply, hcoord]
    rfl

/-- Every successive principal-unit quotient has cardinality equal to that of the residue field. -/
theorem principalUnitsSuccQuot_card_eq_residue
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) (hn : 1 ≤ n)
    [Finite (PrincipalUnitsSuccQuot K n)] :
    Nat.card (PrincipalUnitsSuccQuot K n) = Nat.card 𝓀[K] := by
  exact Nat.card_congr
    (Additive.ofMul.trans (principalUnitsSuccQuotAddEquivResidue K n hn).toEquiv)

/-- Successive principal-unit quotients over a local field are finite. -/
theorem finite_principalUnitsSuccQuot
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] (n : Nat) (hn : 1 ≤ n) :
    Finite (PrincipalUnitsSuccQuot K n) :=
  Finite.of_equiv 𝓀[K]
    ((Additive.ofMul.trans (principalUnitsSuccQuotAddEquivResidue K n hn).toEquiv).symm)

end
end LocalFieldTheory
