import ValuedFieldTheory.LocalField.NonarchimedeanLocalField.PrincipalUnitQuotients

set_option autoImplicit false

/-!
# Standard open subgroups of a nonarchimedean local field

An open finite-index subgroup of a nonarchimedean local field multiplicative group
contains a standard subgroup built from a uniformizer and a sufficiently deep
principal-unit group.
-/

noncomputable section

namespace LocalFieldTheory

open scoped ValuativeRel

open LocalFieldTheory
open LocalFieldTheory.IsNonarchimedeanLocalField

universe u

/-- The `n`-th principal-unit group, viewed as a subgroup of the field's
multiplicative group. -/
def fieldPrincipalUnits
    (K : Type u) [Field K] [ValuativeRel K] (n : ℕ) : Subgroup Kˣ :=
  (principalUnits K n).map (integerUnitsToFieldUnits K)

/-- The standard subgroup `(ϖ^d) · U^n` used in the existence theorem.
The product of the two commuting subgroups is written as their supremum. -/
def uniformizerPrincipalSubgroup
    (K : Type u) [Field K] [ValuativeRel K]
    (ϖ : Kˣ) (d n : ℕ) : Subgroup Kˣ :=
  Subgroup.zpowers (ϖ ^ d) ⊔ fieldPrincipalUnits K n

/-- Every open subgroup of the multiplicative group of a nonarchimedean local
field contains a sufficiently deep positive principal-unit group. -/
theorem exists_fieldPrincipalUnits_le_of_isOpen
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (H : Subgroup Kˣ) (hH : IsOpen (H : Set Kˣ)) :
    ∃ n : ℕ, 1 ≤ n ∧ fieldPrincipalUnits K n ≤ H := by
  rcases Units.isEmbedding_val₀.isOpen_iff.mp hH with
    ⟨V : Set K, hVopen, hV⟩
  have hOneV : (1 : K) ∈ V := by
    have hOneH : (1 : Kˣ) ∈ H := H.one_mem
    have hOnePre : (1 : Kˣ) ∈ Units.val ⁻¹' V := hV.symm ▸ hOneH
    exact hOnePre
  let s : Set 𝒪[K] := {a | (((a : 𝒪[K]) : K) + 1) ∈ V}
  have hs : s ∈ nhds (0 : 𝒪[K]) := by
    have hsOpen : IsOpen s := by
      exact hVopen.preimage (continuous_subtype_val.add continuous_const)
    apply hsOpen.mem_nhds
    simpa [s] using hOneV
  obtain ⟨N, hN⟩ := exists_maximalIdeal_pow_subset_nhds_zero K s hs
  refine ⟨N + 1, Nat.succ_pos N, ?_⟩
  rintro x ⟨u, hu, rfl⟩
  have huPowSucc :
      (((u : 𝒪[K]ˣ) : 𝒪[K]) - 1) ∈
        (𝓂[K] ^ (N + 1) : Ideal 𝒪[K]) :=
    (mem_principalUnits_iff K u (N + 1)).1 hu
  have huPow :
      (((u : 𝒪[K]ˣ) : 𝒪[K]) - 1) ∈
        (𝓂[K] ^ N : Ideal 𝒪[K]) :=
    Ideal.pow_le_pow_right (Nat.le_succ N) huPowSucc
  have huV : (((u : 𝒪[K]ˣ) : 𝒪[K]) : K) ∈ V := by
    have hus := hN huPow
    change (((((u : 𝒪[K]ˣ) : 𝒪[K]) - 1 : 𝒪[K]) : K) + 1) ∈ V at hus
    simpa using hus
  have huPre : integerUnitsToFieldUnits K u ∈ Units.val ⁻¹' V := huV
  have huH : integerUnitsToFieldUnits K u ∈ (H : Set Kˣ) := by
    rw [← hV]
    exact huPre
  exact huH

/-- An open finite-index subgroup contains a standard subgroup generated by a
uniformizer power and a sufficiently deep principal-unit group. -/
theorem exists_uniformizerPrincipalSubgroup_le_of_isOpen_finiteIndex
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (H : Subgroup Kˣ) [H.FiniteIndex] (hH : IsOpen (H : Set Kˣ)) :
    ∃ (ϖ : Kˣ) (d n : ℕ),
      v K (Additive.ofMul ϖ) = 1 ∧
      0 < d ∧ 1 ≤ n ∧
      uniformizerPrincipalSubgroup K ϖ d n ≤ H := by
  obtain ⟨ϖ, hϖ⟩ := v_uniformiser K
  obtain ⟨n, hn, hUn⟩ :=
    exists_fieldPrincipalUnits_le_of_isOpen K H hH
  have hd : 0 < H.index :=
    Nat.pos_of_ne_zero Subgroup.FiniteIndex.index_ne_zero
  refine ⟨ϖ, H.index, n, hϖ, hd, hn, ?_⟩
  apply sup_le
  · exact (Subgroup.zpowers_le).2 (H.pow_index_mem ϖ)
  · exact hUn

end LocalFieldTheory

end
