import ValuedFieldTheory.LocalField.NonarchimedeanLocalField.StandardOpenSubgroups
import ValuedFieldTheory.LocalField.NonarchimedeanLocalField.ValuationExactSequence

set_option autoImplicit false

open scoped ValuativeRel

/-!
# Quotients by a uniformizer and principal units

For a nonarchimedean local field, quotienting the field-unit group by the
standard subgroup generated by a normalized uniformizer and `U^n` is
canonically equivalent to quotienting the integer-unit group by `U^n`.
-/

namespace LocalFieldTheory

open LocalFieldTheory
open LocalFieldTheory.IsNonarchimedeanLocalField

private theorem integerUnitsToFieldUnits_injective
    (L : Type*) [Field L] [ValuativeRel L] :
    Function.Injective (integerUnitsToFieldUnits L) := by
  intro x y hxy
  ext
  exact congrArg (fun z : Lˣ => (z : L)) hxy

/-- The unit factor associated with a normalized uniformizer sends one to
the trivial integer unit. -/
theorem uniformizerUnitFactor_one
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1) :
    LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi 1 = 1 := by
  apply integerUnitsToFieldUnits_injective K
  rw [LocalFieldTheory.IsNonarchimedeanLocalField.integerUnitsToFieldUnits_uniformizerUnitFactor]
  rw [LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap_ofMul_one]
  simp

/-- The unit factor associated with a normalized uniformizer is
multiplicative. -/
theorem uniformizerUnitFactor_mul
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1)
    (x y : Kˣ) :
    LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi (x * y) =
      LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi x *
        LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi y := by
  apply integerUnitsToFieldUnits_injective K
  rw [map_mul]
  simp only [LocalFieldTheory.IsNonarchimedeanLocalField.integerUnitsToFieldUnits_uniformizerUnitFactor]
  rw [LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap_ofMul_mul, zpow_add]
  simp only [div_eq_mul_inv, mul_inv_rev]
  ac_rfl

/-- Extracting the unit factor of an embedded integer unit recovers the
original integer unit. -/
theorem uniformizerUnitFactor_integerUnit
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1)
    (u : 𝒪[K]ˣ) :
    LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi
        (integerUnitsToFieldUnits K u) = u := by
  apply integerUnitsToFieldUnits_injective K
  rw [LocalFieldTheory.IsNonarchimedeanLocalField.integerUnitsToFieldUnits_uniformizerUnitFactor]
  have hv : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K
      (Additive.ofMul (integerUnitsToFieldUnits K u)) = 0 := by
    rw [LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap_apply]
    exact v_integerUnitsToFieldUnits K u
  rw [hv]
  simp

/-- Extract the unit factor and reduce it modulo the `n`-th principal-unit
subgroup. -/
noncomputable def fieldUnitsToIntegerUnitsPrincipalQuotientHom
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1)
    (n : ℕ) : Kˣ →* IntegerUnitsPrincipalQuot K n where
  toFun x := integerUnitsPrincipalQuotMk K n
    (LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi x)
  map_one' := by rw [uniformizerUnitFactor_one]; exact map_one _
  map_mul' x y := by
    rw [uniformizerUnitFactor_mul]
    exact map_mul _ _ _

/-- Reduction of normalized unit factors modulo principal units is
surjective. -/
theorem fieldUnitsToIntegerUnitsPrincipalQuotientHom_surjective
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1)
    (n : ℕ) :
    Function.Surjective (fieldUnitsToIntegerUnitsPrincipalQuotientHom K pi hpi n) := by
  intro q
  obtain ⟨u, rfl⟩ := integerUnitsPrincipalQuotMk_surjective K n q
  refine ⟨integerUnitsToFieldUnits K u, ?_⟩
  change integerUnitsPrincipalQuotMk K n
      (LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi
        (integerUnitsToFieldUnits K u)) = integerUnitsPrincipalQuotMk K n u
  rw [uniformizerUnitFactor_integerUnit]

/-- The kernel is generated by the normalized uniformizer together with the
`n`-th field principal-unit subgroup. -/
theorem fieldUnitsToIntegerUnitsPrincipalQuotientHom_ker
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1)
    (n : ℕ) :
    MonoidHom.ker (fieldUnitsToIntegerUnitsPrincipalQuotientHom K pi hpi n) =
      uniformizerPrincipalSubgroup K pi 1 n := by
  apply le_antisymm
  · intro x hx
    have hfactor : LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi x ∈
        principalUnits K n := by
      rw [← integerUnitsPrincipalQuotMk_ker K n]
      exact hx
    rw [← LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor_mul_uniformizer_zpow
      K pi hpi x]
    apply (uniformizerPrincipalSubgroup K pi 1 n).mul_mem
    · exact (show fieldPrincipalUnits K n ≤
          uniformizerPrincipalSubgroup K pi 1 n from le_sup_right)
        ⟨IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi x,
          hfactor, rfl⟩
    · exact (show Subgroup.zpowers (pi ^ 1) ≤
          uniformizerPrincipalSubgroup K pi 1 n from le_sup_left)
        (by
          rw [pow_one]
          exact (Subgroup.zpowers pi).zpow_mem
            (Subgroup.mem_zpowers pi)
            (LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul x)))
  · apply sup_le
    · rw [Subgroup.zpowers_le]
      change fieldUnitsToIntegerUnitsPrincipalQuotientHom K pi hpi n (pi ^ 1) = 1
      rw [pow_one]
      change integerUnitsPrincipalQuotMk K n
        (LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi pi) = 1
      have hfactor : LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi pi = 1 := by
        apply integerUnitsToFieldUnits_injective K
        rw [LocalFieldTheory.IsNonarchimedeanLocalField.integerUnitsToFieldUnits_uniformizerUnitFactor,
          hpi]
        simp
      rw [hfactor]
      exact map_one _
    · rintro x ⟨u, hu, rfl⟩
      change integerUnitsPrincipalQuotMk K n
        (LocalFieldTheory.IsNonarchimedeanLocalField.uniformizerUnitFactor K pi hpi
          (integerUnitsToFieldUnits K u)) = 1
      rw [uniformizerUnitFactor_integerUnit]
      exact (QuotientGroup.eq_one_iff u).2 hu

/-- Quotienting field units by a normalized uniformizer and `U^n` is
canonically equivalent to quotienting integer units by `U^n`. -/
noncomputable def uniformizerPrincipalQuotientEquivIntegerUnitsPrincipalQuotient
    (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (pi : Kˣ)
    (hpi : LocalFieldTheory.IsNonarchimedeanLocalField.valuationMap K (Additive.ofMul pi) = 1)
    (n : ℕ) :
    Kˣ ⧸ uniformizerPrincipalSubgroup K pi 1 n ≃*
      IntegerUnitsPrincipalQuot K n :=
  (QuotientGroup.quotientMulEquivOfEq
    (fieldUnitsToIntegerUnitsPrincipalQuotientHom_ker K pi hpi n).symm).trans
      (QuotientGroup.quotientKerEquivOfSurjective
        (fieldUnitsToIntegerUnitsPrincipalQuotientHom K pi hpi n)
        (fieldUnitsToIntegerUnitsPrincipalQuotientHom_surjective K pi hpi n))

end LocalFieldTheory
