name = "SawinTotallyRealTowers"
version = "1.0.0"
defaultTargets = ["SawinTotallyRealTowers.All", "SawinTotallyRealTowers.MartinetCorollary"]
enableArtifactCache = false
restoreAllArtifacts = false

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "SawinTotallyRealTowers"
srcDir = "Lean4"
roots = []
globs = ["SawinTotallyRealTowers.+"]

[[lean_lib]]
name = "ClassFieldTheory"
srcDir = "Lean4"
roots = []
globs = ["ClassFieldTheory.+"]
leanOptions = {linter.missingDocs = true}

[[lean_lib]]
name = "ProCGroups"
srcDir = "Lean4"
roots = []
globs = ["ProCGroups.+"]
leanOptions = {linter.missingDocs = true}

[[lean_lib]]
name = "GaloisCohomology"
srcDir = "Lean4"
roots = []
globs = ["GaloisCohomology.+"]

[[lean_lib]]
name = "ValuedFieldTheory"
srcDir = "Lean4"
roots = []
globs = ["ValuedFieldTheory.+"]
