import GaloisCohomology.ProP.TrivialZModP
import ProCGroups.ProP.ContinuousH1

set_option autoImplicit false
/-!
# Continuous degree-one cohomology bridge

This file identifies continuous additive `ZMod p`-characters with Mathlib's degree-one
continuous cohomology for the trivial coefficient representation.  It supplies both the
small-universe coefficient API and the universe-polymorphic API whose coefficient carrier is
`ULift (ZMod p)`.  The construction is explicit: a character `χ` is sent to the homogeneous
cocycle `(g, h) ↦ χ(g⁻¹h)`, and the inverse evaluates a homogeneous cocycle at `(1, g)`.
-/

open CategoryTheory TopRep ContRepresentation
open ClassFieldTower.ProP
open scoped Topology

namespace ClassFieldTower.Cohomology

noncomputable section

universe u

variable {p : ℕ}
variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

local instance continuousSMulULiftZMod :
    ContinuousSMul (ZMod p) (ULift.{u} (ZMod p)) :=
  ContinuousSMul.induced ULift.moduleEquiv.toLinearMap

local instance continuousH1ZModModuleInstanceLifted :
    Module (ZMod p) (ContinuousH1ZMod (p := p) (G := G)) :=
  continuousH1ZModModule

/-- The continuous linear map from the lifted scalar line generated by `x`. -/
def topModuleLineLifted {M : TopModuleCat.{u} (ZMod p)} (x : M) :
    TopModuleCat.of (ZMod p) (ULift.{u} (ZMod p)) ⟶ M :=
  TopModuleCat.ofHom
    { toLinearMap :=
        { toFun := fun a ↦ a.down • x
          map_add' := by
            intro a b
            rw [show (a + b).down = a.down + b.down by rfl, add_smul]
          map_smul' := by
            intro a b
            rw [show (a • b).down = a * b.down by rfl, mul_smul]
            simp }
      cont := Continuous.smul
        ((ContinuousLinearEquiv.ulift :
          ULift.{u} (ZMod p) ≃L[ZMod p] ZMod p).continuous) continuous_const }

theorem topModule_mono_injective_lifted
    {M N : TopModuleCat.{u} (ZMod p)} (f : M ⟶ N) [Mono f] :
    Function.Injective f := by
  intro x y hxy
  have hline : topModuleLineLifted x ≫ f = topModuleLineLifted y ≫ f := by
    apply ConcreteCategory.ext
    apply ContinuousLinearMap.ext
    intro a
    simp only [TopModuleCat.hom_comp, ContinuousLinearMap.comp_apply]
    change f (a.down • x) = f (a.down • y)
    rw [map_smul, map_smul, hxy]
  have hline' : topModuleLineLifted x = topModuleLineLifted y := by
    rw [← cancel_mono f]
    exact hline
  have h1 := ConcreteCategory.congr_hom hline' (ULift.up (1 : ZMod p))
  simpa [topModuleLineLifted] using h1

/-- The homogeneous one-cochain `(g, h) ↦ χ(g⁻¹h)` with lifted values. -/
def homogeneousOneCochainOfH1Lifted
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).X 1 := by
  let σ : C(G, C(G, ULift.{u} (ZMod p))) := ContinuousMap.curry
    ⟨fun (x : G × G) ↦ ULift.up (χ (Additive.ofMul (x.1⁻¹ * x.2))),
      ((ContinuousLinearEquiv.ulift :
        ULift.{u} (ZMod p) ≃L[ZMod p] ZMod p).symm.continuous).comp <|
        χ.continuous_toFun.comp (by
        change Continuous (fun x : G × G ↦ x.1⁻¹ * x.2)
        fun_prop)⟩
  exact ⟨σ, by
    intro g
    apply ContinuousMap.ext
    intro x
    apply ContinuousMap.ext
    intro y
    apply ULift.ext
    change χ (Additive.ofMul ((g⁻¹ * x)⁻¹ * (g⁻¹ * y))) =
      χ (Additive.ofMul (x⁻¹ * y))
    congr 2
    group⟩

@[simp]
theorem homogeneousOneCochainOfH1Lifted_apply
    (χ : ContinuousH1ZMod (p := p) (G := G)) (g h : G) :
    (homogeneousOneCochainOfH1Lifted χ).1 g h =
      ULift.up (χ (Additive.ofMul (g⁻¹ * h))) :=
  rfl

theorem homogeneousOneCochainOfH1Lifted_mem_cycles
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 1 2).hom
      (homogeneousOneCochainOfH1Lifted χ) = 0 := by
  change _ =
    (0 : (TopRep.resolutionX
      (ClassFieldTower.Cohomology.trivialZModPLifted p G) 3).ρ.invariants)
  apply Subtype.ext
  ext g h k
  have hd := TopRep.homogeneousCochains.d_apply
    (ClassFieldTower.Cohomology.trivialZModPLifted p G) 1
      (homogeneousOneCochainOfH1Lifted χ)
  have hdh := congrArg (fun τ => τ g h k) hd
  rw [hdh]
  simp [TopRep.d_succ, TopRep.d_zero, TopRep.hom_sub,
    ContIntertwiningMap.sub_apply, coind₁ι_toFun, coind₁Map_toFun]
  apply ULift.ext
  change χ (Additive.ofMul (h⁻¹ * k)) -
      (χ (Additive.ofMul (g⁻¹ * k)) - χ (Additive.ofMul (g⁻¹ * h))) = 0
  have hχ := χ.map_add
    (Additive.ofMul (g⁻¹ * h)) (Additive.ofMul (h⁻¹ * k))
  change χ (Additive.ofMul ((g⁻¹ * h) * (h⁻¹ * k))) =
    χ (Additive.ofMul (g⁻¹ * h)) + χ (Additive.ofMul (h⁻¹ * k)) at hχ
  rw [show (g⁻¹ * h) * (h⁻¹ * k) = g⁻¹ * k by group] at hχ
  rw [hχ]
  abel

/-- The lifted scalar line through the homogeneous cocycle attached to `χ`. -/
def homogeneousOneCochainLineOfH1Lifted
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    TopModuleCat.of (ZMod p) (ULift.{u} (ZMod p)) ⟶
      (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).X 1 :=
  topModuleLineLifted (homogeneousOneCochainOfH1Lifted χ)

theorem homogeneousOneCochainLineOfH1Lifted_comp_d
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    homogeneousOneCochainLineOfH1Lifted χ ≫
        (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 1 2 = 0 := by
  apply ConcreteCategory.ext
  apply ContinuousLinearMap.ext
  intro a
  change ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 1 2).hom
    (a.down • homogeneousOneCochainOfH1Lifted χ) = 0
  rw [map_smul, homogeneousOneCochainOfH1Lifted_mem_cycles]
  simp

/-- Regard a continuous additive character as a lifted homogeneous one-cocycle. -/
def cocycleOfH1Lifted (χ : ContinuousH1ZMod (p := p) (G := G)) :
    ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1 := by
  exact ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).liftCycles
    (homogeneousOneCochainLineOfH1Lifted χ) 2 (by simp)
      (homogeneousOneCochainLineOfH1Lifted_comp_d χ)) 1

/-- The homogeneous one-cochain underlying a lifted one-cocycle. -/
def homogeneousOneCochainOfCocycleLifted
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1) :
    (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).X 1 :=
  (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1 z

theorem homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted χ) =
      homogeneousOneCochainOfH1Lifted χ := by
  change (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1
    (((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).liftCycles
      (homogeneousOneCochainLineOfH1Lifted χ) 2 (by simp)
        (homogeneousOneCochainLineOfH1Lifted_comp_d χ)) 1) = _
  rw [← ConcreteCategory.comp_apply,
    (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).liftCycles_i]
  change ((1 : ULift.{u} (ZMod p)).down : ZMod p) •
    homogeneousOneCochainOfH1Lifted χ = _
  simp

theorem homogeneousOneCochainOfCocycleLifted_mem_cycles
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1) :
    ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 1 2).hom
      (homogeneousOneCochainOfCocycleLifted z) = 0 := by
  have h := (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles_d 1 2
  have hz := ConcreteCategory.congr_hom h z
  change ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 1 2).hom
    (((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1).hom z) = 0 at hz
  exact hz

theorem homogeneousOneCochainOfCocycleLifted_cocycle_identity
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1)
    (g h k : G) :
    (homogeneousOneCochainOfCocycleLifted z).1 h k -
        ((homogeneousOneCochainOfCocycleLifted z).1 g k -
          (homogeneousOneCochainOfCocycleLifted z).1 g h) = 0 := by
  have hd := TopRep.homogeneousCochains.d_apply
    (ClassFieldTower.Cohomology.trivialZModPLifted p G) 1
      (homogeneousOneCochainOfCocycleLifted z)
  have hdh := congrArg (fun τ => τ g h k) hd
  have hz := congrArg (fun τ => τ.1 g h k)
    (homogeneousOneCochainOfCocycleLifted_mem_cycles z)
  change (((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 1 2).hom
    (homogeneousOneCochainOfCocycleLifted z)).1 g h k = 0 at hz
  rw [hdh] at hz
  simpa [TopRep.d_succ, TopRep.d_zero, TopRep.hom_sub,
    ContIntertwiningMap.sub_apply, coind₁ι_toFun, coind₁Map_toFun] using hz

theorem homogeneousOneCochainOfCocycleLifted_invariant
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1)
    (a g h : G) :
    (homogeneousOneCochainOfCocycleLifted z).1 (a⁻¹ * g) (a⁻¹ * h) =
      (homogeneousOneCochainOfCocycleLifted z).1 g h := by
  have hz := (homogeneousOneCochainOfCocycleLifted z).2 a
  have hzh := congrArg (fun τ => τ g h) hz
  have hzh' :
      (ClassFieldTower.Cohomology.trivialZModPLifted p G).ρ a
          ((homogeneousOneCochainOfCocycleLifted z).1 (a⁻¹ * g) (a⁻¹ * h)) =
        (homogeneousOneCochainOfCocycleLifted z).1 g h := by
    simpa only [ContRepresentation.coind₁_apply_apply] using hzh
  exact
    (ClassFieldTower.Cohomology.trivialZModPLifted_action p G a _).symm.trans hzh'

theorem homogeneousOneCochainOfCocycleLifted_cocycle_identity_down
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1)
    (g h k : G) :
    ((homogeneousOneCochainOfCocycleLifted z).1 h k).down -
        (((homogeneousOneCochainOfCocycleLifted z).1 g k).down -
          ((homogeneousOneCochainOfCocycleLifted z).1 g h).down) = 0 := by
  have hz := congrArg (fun x : ULift.{u} (ZMod p) ↦ x.down)
    (homogeneousOneCochainOfCocycleLifted_cocycle_identity z g h k)
  exact hz

theorem homogeneousOneCochainOfCocycleLifted_invariant_down
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1)
    (a g h : G) :
    ((homogeneousOneCochainOfCocycleLifted z).1 (a⁻¹ * g) (a⁻¹ * h)).down =
      ((homogeneousOneCochainOfCocycleLifted z).1 g h).down :=
  congrArg (fun x : ULift.{u} (ZMod p) ↦ x.down)
    (homogeneousOneCochainOfCocycleLifted_invariant z a g h)

/-- Recover a continuous additive character from a lifted homogeneous one-cocycle. -/
def h1OfCocycleLifted
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1) :
    ContinuousH1ZMod (p := p) (G := G) where
  toFun g := ((homogeneousOneCochainOfCocycleLifted z).1 1 g.toMul).down
  map_zero' := by
    change ((homogeneousOneCochainOfCocycleLifted z).1 1 1).down = 0
    have hz := homogeneousOneCochainOfCocycleLifted_cocycle_identity_down z 1 1 1
    have hz' := sub_eq_zero.mp hz
    abel_nf at hz'
    exact hz'
  map_add' := by
    intro g h
    have hz := homogeneousOneCochainOfCocycleLifted_cocycle_identity_down
      z 1 g.toMul (g.toMul * h.toMul)
    have hinv := homogeneousOneCochainOfCocycleLifted_invariant_down
      z g.toMul g.toMul (g.toMul * h.toMul)
    have hinv' :
        ((homogeneousOneCochainOfCocycleLifted z).1 1 h.toMul).down =
          ((homogeneousOneCochainOfCocycleLifted z).1 g.toMul
            (g.toMul * h.toMul)).down := by
      convert hinv using 1; group
    rw [← hinv'] at hz
    change ((homogeneousOneCochainOfCocycleLifted z).1 1
        (g.toMul * h.toMul)).down =
      ((homogeneousOneCochainOfCocycleLifted z).1 1 g.toMul).down +
        ((homogeneousOneCochainOfCocycleLifted z).1 1 h.toMul).down
    have heq := sub_eq_zero.mp hz
    have hadd := (eq_sub_iff_add_eq).mp heq
    simpa only [add_comm] using hadd.symm
  continuous_toFun := ((ContinuousLinearEquiv.ulift :
      ULift.{u} (ZMod p) ≃L[ZMod p] ZMod p).continuous).comp
    ((homogeneousOneCochainOfCocycleLifted z).1 1 |>.continuous)

theorem h1OfCocycleLifted_cocycleOfH1Lifted
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    h1OfCocycleLifted (cocycleOfH1Lifted χ) = χ := by
  ext g
  simp only [h1OfCocycleLifted]
  change ((homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted χ)).1 1 g.toMul).down = χ g
  rw [homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted,
    homogeneousOneCochainOfH1Lifted_apply]
  simp

theorem cocycleOfH1Lifted_h1OfCocycleLifted
    (z : ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1) :
    cocycleOfH1Lifted (h1OfCocycleLifted z) = z := by
  apply topModule_mono_injective_lifted
    ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1)
  change homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted (h1OfCocycleLifted z)) =
    homogeneousOneCochainOfCocycleLifted z
  rw [homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted]
  apply Subtype.ext
  ext g h
  simp only [h1OfCocycleLifted]
  change ULift.up (((homogeneousOneCochainOfCocycleLifted z).1 1 (g⁻¹ * h)).down) =
    (homogeneousOneCochainOfCocycleLifted z).1 g h
  apply ULift.ext
  have hz := homogeneousOneCochainOfCocycleLifted_invariant_down z g g h
  simpa using hz

theorem cocycleOfH1Lifted_add
    (χ ψ : ContinuousH1ZMod (p := p) (G := G)) :
    cocycleOfH1Lifted (χ + ψ) = cocycleOfH1Lifted χ + cocycleOfH1Lifted ψ := by
  apply topModule_mono_injective_lifted
    ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1)
  change homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted (χ + ψ)) =
    homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted χ + cocycleOfH1Lifted ψ)
  rw [homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted]
  change homogeneousOneCochainOfH1Lifted (χ + ψ) =
    (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1
      (cocycleOfH1Lifted χ + cocycleOfH1Lifted ψ)
  rw [map_add]
  change homogeneousOneCochainOfH1Lifted (χ + ψ) =
    homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted χ) +
      homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted ψ)
  rw [homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted,
    homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted]
  apply Subtype.ext
  ext g h
  apply ULift.ext
  change (χ + ψ) (Additive.ofMul (g⁻¹ * h)) =
    χ (Additive.ofMul (g⁻¹ * h)) + ψ (Additive.ofMul (g⁻¹ * h))
  rfl

theorem cocycleOfH1Lifted_smul
    (a : ZMod p) (χ : ContinuousH1ZMod (p := p) (G := G)) :
    cocycleOfH1Lifted (a • χ) = a • cocycleOfH1Lifted χ := by
  apply topModule_mono_injective_lifted
    ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1)
  change homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted (a • χ)) =
    homogeneousOneCochainOfCocycleLifted (a • cocycleOfH1Lifted χ)
  rw [homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted]
  change homogeneousOneCochainOfH1Lifted (a • χ) =
    (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).iCycles 1
      (a • cocycleOfH1Lifted χ)
  rw [map_smul]
  change homogeneousOneCochainOfH1Lifted (a • χ) =
    a • homogeneousOneCochainOfCocycleLifted (cocycleOfH1Lifted χ)
  rw [homogeneousOneCochainOfCocycleLifted_cocycleOfH1Lifted]
  apply Subtype.ext
  ext g h
  apply ULift.ext
  let ev : ContinuousH1ZMod (p := p) (G := G) →+ ZMod p :=
    { toFun := fun eta ↦ eta (Additive.ofMul (g⁻¹ * h))
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  exact ZMod.map_smul ev a χ

/-- Continuous additive characters are linearly equivalent to lifted homogeneous one-cocycles. -/
def continuousH1ZModEquivCocyclesLifted :
    ContinuousH1ZMod (p := p) (G := G) ≃ₗ[ZMod p]
      ClassFieldTower.Cohomology.trivialZModPCocyclesLifted p G 1 where
  toFun := cocycleOfH1Lifted
  invFun := h1OfCocycleLifted
  map_add' := cocycleOfH1Lifted_add
  map_smul' := cocycleOfH1Lifted_smul
  left_inv := h1OfCocycleLifted_cocycleOfH1Lifted
  right_inv := cocycleOfH1Lifted_h1OfCocycleLifted

/-- For trivial lifted coefficients, every homogeneous zero-cochain has zero differential. -/
theorem trivialZModPCochainsLifted_d_zero_one :
    (ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 0 1 = 0 := by
  apply ConcreteCategory.ext
  apply ContinuousLinearMap.ext
  intro sigma
  change ((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).d 0 1).hom sigma = 0
  apply Subtype.ext
  ext g h
  have hd := TopRep.homogeneousCochains.d_apply
    (ClassFieldTower.Cohomology.trivialZModPLifted p G) 0 sigma
  have hdh := congrArg (fun tau => tau g h) hd
  rw [hdh]
  simp [TopRep.d_succ, TopRep.d_zero, TopRep.hom_sub,
    ContIntertwiningMap.sub_apply, coind₁ι_toFun, coind₁Map_toFun]
  change sigma.1 h - sigma.1 g = 0
  have hg := congrArg (fun tau => tau g) (sigma.2 g)
  have hh := congrArg (fun tau => tau h) (sigma.2 h)
  have hg' : sigma.1 1 = sigma.1 g := by
    have hg'' :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModPLifted p G) 0).ρ g)
            (sigma.1 1) = sigma.1 g := by
      simpa only [ContRepresentation.coind₁_apply_apply, inv_mul_cancel] using hg
    have htriv :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModPLifted p G) 0).ρ g)
            (sigma.1 1) = sigma.1 1 := by
      change (ClassFieldTower.Cohomology.trivialZModPLifted p G).ρ g
        (sigma.1 1) = sigma.1 1
      exact ClassFieldTower.Cohomology.trivialZModPLifted_action p G g _
    exact htriv.symm.trans hg''
  have hh' : sigma.1 1 = sigma.1 h := by
    have hh'' :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModPLifted p G) 0).ρ h)
            (sigma.1 1) = sigma.1 h := by
      simpa only [ContRepresentation.coind₁_apply_apply, inv_mul_cancel] using hh
    have htriv :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModPLifted p G) 0).ρ h)
            (sigma.1 1) = sigma.1 1 := by
      change (ClassFieldTower.Cohomology.trivialZModPLifted p G).ρ h
        (sigma.1 1) = sigma.1 1
      exact ClassFieldTower.Cohomology.trivialZModPLifted_action p G h _
    exact htriv.symm.trans hh''
  rw [← hg', ← hh']
  exact sub_self _

/-- The canonical `ZMod p`-linear equivalence from continuous additive characters to
degree-one continuous cohomology with universe-lifted trivial coefficients. -/
def continuousH1ZModEquivContinuousCohomologyLifted :
    ContinuousH1ZMod (p := p) (G := G) ≃ₗ[ZMod p]
      ClassFieldTower.Cohomology.continuousCohomologyZModPLifted p G 1 :=
  continuousH1ZModEquivCocyclesLifted.trans
    (((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).isoHomologyπ
      0 1 (CochainComplex.prev_nat_succ 0)
        trivialZModPCochainsLifted_d_zero_one).toContinuousLinearEquiv.toLinearEquiv)

@[simp]
theorem continuousH1ZModEquivContinuousCohomologyLifted_apply
    (χ : ContinuousH1ZMod (p := p) (G := G)) :
    continuousH1ZModEquivContinuousCohomologyLifted χ =
      ContinuousCohomology.π
        (ClassFieldTower.Cohomology.trivialZModPLifted p G) 1 (cocycleOfH1Lifted χ) :=
  rfl

@[simp]
theorem continuousH1ZModEquivContinuousCohomologyLifted_symm_apply
    (x : ClassFieldTower.Cohomology.continuousCohomologyZModPLifted p G 1) :
    continuousH1ZModEquivContinuousCohomologyLifted.symm x =
      h1OfCocycleLifted
        (((ClassFieldTower.Cohomology.trivialZModPCochainsLifted p G).isoHomologyπ
          0 1 (CochainComplex.prev_nat_succ 0)
            trivialZModPCochainsLifted_d_zero_one).inv x) :=
  rfl

section SmallUniverse

variable {p : ℕ}
variable {G₀ : Type} [Group G₀] [TopologicalSpace G₀] [IsTopologicalGroup G₀]

local instance continuousH1ZModModuleInstance :
    Module (ZMod p) (ContinuousH1ZMod (p := p) (G := G₀)) :=
  continuousH1ZModModule

/-- The continuous linear map from the scalar line generated by `x`. -/
def topModuleLine {M : TopModuleCat.{0} (ZMod p)} (x : M) :
    TopModuleCat.of (ZMod p) (ZMod p) ⟶ M :=
  TopModuleCat.ofHom
    { toLinearMap :=
        { toFun := fun a ↦ a • x
          map_add' := fun a b ↦ add_smul a b x
          map_smul' := fun a b ↦ mul_smul a b x }
      cont := continuous_id.smul continuous_const }

theorem topModule_mono_injective
    {M N : TopModuleCat.{0} (ZMod p)} (f : M ⟶ N) [Mono f] :
    Function.Injective f := by
  intro x y hxy
  have hline : topModuleLine x ≫ f = topModuleLine y ≫ f := by
    apply ConcreteCategory.ext
    apply ContinuousLinearMap.ext
    intro a
    change f (a • x) = f (a • y)
    rw [map_smul, map_smul, hxy]
  have hline' : topModuleLine x = topModuleLine y := by
    rw [← cancel_mono f]
    exact hline
  have h1 := ConcreteCategory.congr_hom hline' (1 : ZMod p)
  simpa [topModuleLine] using h1

/-- The homogeneous one-cochain `(g, h) ↦ χ(g⁻¹h)` with small-universe values. -/
def homogeneousOneCochainOfH1
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).X 1 := by
  let σ : C(G₀, C(G₀, ZMod p)) := ContinuousMap.curry
    ⟨fun (x : G₀ × G₀) ↦ χ (Additive.ofMul (x.1⁻¹ * x.2)),
      χ.continuous_toFun.comp (by
        change Continuous (fun x : G₀ × G₀ ↦ x.1⁻¹ * x.2)
        fun_prop)⟩
  exact ⟨σ, by
    intro g
    apply ContinuousMap.ext
    intro x
    apply ContinuousMap.ext
    intro y
    change χ (Additive.ofMul ((g⁻¹ * x)⁻¹ * (g⁻¹ * y))) =
      χ (Additive.ofMul (x⁻¹ * y))
    congr 2
    group⟩

@[simp]
theorem homogeneousOneCochainOfH1_apply
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) (g h : G₀) :
    (homogeneousOneCochainOfH1 χ).1 g h =
      χ (Additive.ofMul (g⁻¹ * h)) :=
  rfl

theorem homogeneousOneCochainOfH1_mem_cycles
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 1 2).hom
      (homogeneousOneCochainOfH1 χ) = 0 := by
  change _ =
    (0 : (TopRep.resolutionX
      (ClassFieldTower.Cohomology.trivialZModP p G₀) 3).ρ.invariants)
  apply Subtype.ext
  ext g h k
  have hd := TopRep.homogeneousCochains.d_apply
    (ClassFieldTower.Cohomology.trivialZModP p G₀) 1
      (homogeneousOneCochainOfH1 χ)
  have hdh := congrArg (fun τ => τ g h k) hd
  rw [hdh]
  simp [TopRep.d_succ, TopRep.d_zero, TopRep.hom_sub,
    ContIntertwiningMap.sub_apply, coind₁ι_toFun, coind₁Map_toFun]
  change χ (Additive.ofMul (h⁻¹ * k)) -
      (χ (Additive.ofMul (g⁻¹ * k)) - χ (Additive.ofMul (g⁻¹ * h))) = 0
  have hχ := χ.map_add
    (Additive.ofMul (g⁻¹ * h)) (Additive.ofMul (h⁻¹ * k))
  change χ (Additive.ofMul ((g⁻¹ * h) * (h⁻¹ * k))) =
    χ (Additive.ofMul (g⁻¹ * h)) + χ (Additive.ofMul (h⁻¹ * k)) at hχ
  rw [show (g⁻¹ * h) * (h⁻¹ * k) = g⁻¹ * k by group] at hχ
  rw [hχ]
  abel

/-- The scalar line through the small-universe homogeneous cocycle attached to `χ`. -/
def homogeneousOneCochainLineOfH1
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    TopModuleCat.of (ZMod p) (ZMod p) ⟶
      (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).X 1 :=
  TopModuleCat.ofHom
    { toLinearMap :=
        { toFun := fun a ↦ a • homogeneousOneCochainOfH1 χ
          map_add' := fun a b ↦ (add_smul a b _)
          map_smul' := fun a b ↦ mul_smul a b _ }
      cont := continuous_of_discreteTopology }

theorem homogeneousOneCochainLineOfH1_comp_d
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    homogeneousOneCochainLineOfH1 χ ≫
        (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 1 2 = 0 := by
  apply ConcreteCategory.ext
  apply ContinuousLinearMap.ext
  intro a
  change ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 1 2).hom
    (a • homogeneousOneCochainOfH1 χ) = 0
  rw [map_smul, homogeneousOneCochainOfH1_mem_cycles]
  simp

/-- Regard a continuous additive character as a small-universe homogeneous one-cocycle. -/
def cocycleOfH1 (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1 := by
  exact ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).liftCycles
    (homogeneousOneCochainLineOfH1 χ) 2 (by simp)
      (homogeneousOneCochainLineOfH1_comp_d χ)) 1

/-- The homogeneous one-cochain underlying a small-universe one-cocycle. -/
def homogeneousOneCochainOfCocycle
    (z : ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1) :
    (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).X 1 :=
  (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1 z

theorem homogeneousOneCochainOfCocycle_cocycleOfH1
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    homogeneousOneCochainOfCocycle (cocycleOfH1 χ) =
      homogeneousOneCochainOfH1 χ := by
  change (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1
    (((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).liftCycles
      (homogeneousOneCochainLineOfH1 χ) 2 (by simp)
        (homogeneousOneCochainLineOfH1_comp_d χ)) 1) = _
  rw [← ConcreteCategory.comp_apply,
    (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).liftCycles_i]
  change (1 : ZMod p) • homogeneousOneCochainOfH1 χ = _
  simp

theorem homogeneousOneCochainOfCocycle_mem_cycles
    (z : ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1) :
    ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 1 2).hom
      (homogeneousOneCochainOfCocycle z) = 0 := by
  have h := (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles_d 1 2
  have hz := ConcreteCategory.congr_hom h z
  change ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 1 2).hom
    (((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1).hom z) = 0 at hz
  exact hz

theorem homogeneousOneCochainOfCocycle_cocycle_identity
    (z : ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1)
    (g h k : G₀) :
    (homogeneousOneCochainOfCocycle z).1 h k -
        ((homogeneousOneCochainOfCocycle z).1 g k -
          (homogeneousOneCochainOfCocycle z).1 g h) = 0 := by
  have hd := TopRep.homogeneousCochains.d_apply
    (ClassFieldTower.Cohomology.trivialZModP p G₀) 1
      (homogeneousOneCochainOfCocycle z)
  have hdh := congrArg (fun τ => τ g h k) hd
  have hz := congrArg (fun τ => τ.1 g h k)
    (homogeneousOneCochainOfCocycle_mem_cycles z)
  change (((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 1 2).hom
    (homogeneousOneCochainOfCocycle z)).1 g h k = 0 at hz
  rw [hdh] at hz
  simpa [TopRep.d_succ, TopRep.d_zero, TopRep.hom_sub,
    ContIntertwiningMap.sub_apply, coind₁ι_toFun, coind₁Map_toFun] using hz

theorem homogeneousOneCochainOfCocycle_invariant
    (z : ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1)
    (a g h : G₀) :
    (homogeneousOneCochainOfCocycle z).1 (a⁻¹ * g) (a⁻¹ * h) =
      (homogeneousOneCochainOfCocycle z).1 g h := by
  have hz := (homogeneousOneCochainOfCocycle z).2 a
  have hzh := congrArg (fun τ => τ g h) hz
  have hzh' :
      (ClassFieldTower.Cohomology.trivialZModP p G₀).ρ a
          ((homogeneousOneCochainOfCocycle z).1 (a⁻¹ * g) (a⁻¹ * h)) =
        (homogeneousOneCochainOfCocycle z).1 g h := by
    simpa only [ContRepresentation.coind₁_apply_apply] using hzh
  exact
    (ClassFieldTower.Cohomology.trivialZModP_action p G₀ a _).symm.trans hzh'

/-- Recover a continuous additive character from a small-universe homogeneous one-cocycle. -/
def h1OfCocycle
    (z : ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1) :
    ContinuousH1ZMod (p := p) (G := G₀) where
  toFun g := (homogeneousOneCochainOfCocycle z).1 1 g.toMul
  map_zero' := by
    change (homogeneousOneCochainOfCocycle z).1 1 1 = (0 : ZMod p)
    have hz := homogeneousOneCochainOfCocycle_cocycle_identity z 1 1 1
    change (homogeneousOneCochainOfCocycle z).1 1 1 -
      ((homogeneousOneCochainOfCocycle z).1 1 1 -
        (homogeneousOneCochainOfCocycle z).1 1 1) = (0 : ZMod p) at hz
    have hz' := sub_eq_zero.mp hz
    simp only [ClassFieldTower.Cohomology.trivialZModP] at hz'
    abel_nf at hz'
    exact hz'
  map_add' := by
    intro g h
    have hz := homogeneousOneCochainOfCocycle_cocycle_identity
      z 1 g.toMul (g.toMul * h.toMul)
    change (homogeneousOneCochainOfCocycle z).1 g.toMul
        (g.toMul * h.toMul) -
      ((homogeneousOneCochainOfCocycle z).1 1 (g.toMul * h.toMul) -
        (homogeneousOneCochainOfCocycle z).1 1 g.toMul) = (0 : ZMod p) at hz
    have hinv := homogeneousOneCochainOfCocycle_invariant
      z g.toMul g.toMul (g.toMul * h.toMul)
    have hinv' :
        (homogeneousOneCochainOfCocycle z).1 1 h.toMul =
          (homogeneousOneCochainOfCocycle z).1 g.toMul
            (g.toMul * h.toMul) := by
      convert hinv using 1; group
    rw [← hinv'] at hz
    change (homogeneousOneCochainOfCocycle z).1 1 (g.toMul * h.toMul) =
      (homogeneousOneCochainOfCocycle z).1 1 g.toMul +
        (homogeneousOneCochainOfCocycle z).1 1 h.toMul
    have heq := sub_eq_zero.mp hz
    have hadd := (eq_sub_iff_add_eq).mp heq
    simpa only [add_comm] using hadd.symm
  continuous_toFun := (homogeneousOneCochainOfCocycle z).1 1 |>.continuous

theorem h1OfCocycle_cocycleOfH1
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    h1OfCocycle (cocycleOfH1 χ) = χ := by
  ext g
  change (homogeneousOneCochainOfCocycle (cocycleOfH1 χ)).1 1 g.toMul = χ g
  rw [homogeneousOneCochainOfCocycle_cocycleOfH1]
  change χ (Additive.ofMul (1⁻¹ * g.toMul)) = χ g
  simp

theorem cocycleOfH1_h1OfCocycle
    (z : ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1) :
    cocycleOfH1 (h1OfCocycle z) = z := by
  apply topModule_mono_injective
    ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1)
  change homogeneousOneCochainOfCocycle (cocycleOfH1 (h1OfCocycle z)) =
    homogeneousOneCochainOfCocycle z
  rw [homogeneousOneCochainOfCocycle_cocycleOfH1]
  apply Subtype.ext
  ext g h
  change (homogeneousOneCochainOfCocycle z).1 1 (g⁻¹ * h) =
    (homogeneousOneCochainOfCocycle z).1 g h
  have hz := homogeneousOneCochainOfCocycle_invariant z g g h
  convert hz using 1; group

theorem cocycleOfH1_add
    (χ ψ : ContinuousH1ZMod (p := p) (G := G₀)) :
    cocycleOfH1 (χ + ψ) = cocycleOfH1 χ + cocycleOfH1 ψ := by
  apply topModule_mono_injective
    ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1)
  change homogeneousOneCochainOfCocycle (cocycleOfH1 (χ + ψ)) =
    homogeneousOneCochainOfCocycle (cocycleOfH1 χ + cocycleOfH1 ψ)
  rw [homogeneousOneCochainOfCocycle_cocycleOfH1]
  change homogeneousOneCochainOfH1 (χ + ψ) =
    (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1
      (cocycleOfH1 χ + cocycleOfH1 ψ)
  rw [map_add]
  change homogeneousOneCochainOfH1 (χ + ψ) =
    homogeneousOneCochainOfCocycle (cocycleOfH1 χ) +
      homogeneousOneCochainOfCocycle (cocycleOfH1 ψ)
  rw [homogeneousOneCochainOfCocycle_cocycleOfH1,
    homogeneousOneCochainOfCocycle_cocycleOfH1]
  apply Subtype.ext
  ext g h
  rfl

theorem cocycleOfH1_smul
    (a : ZMod p) (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    cocycleOfH1 (a • χ) = a • cocycleOfH1 χ := by
  apply topModule_mono_injective
    ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1)
  change homogeneousOneCochainOfCocycle (cocycleOfH1 (a • χ)) =
    homogeneousOneCochainOfCocycle (a • cocycleOfH1 χ)
  rw [homogeneousOneCochainOfCocycle_cocycleOfH1]
  change homogeneousOneCochainOfH1 (a • χ) =
    (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).iCycles 1
      (a • cocycleOfH1 χ)
  rw [map_smul]
  change homogeneousOneCochainOfH1 (a • χ) =
    a • homogeneousOneCochainOfCocycle (cocycleOfH1 χ)
  rw [homogeneousOneCochainOfCocycle_cocycleOfH1]
  apply Subtype.ext
  ext g h
  let ev : ContinuousH1ZMod (p := p) (G := G₀) →+ ZMod p :=
    { toFun := fun eta ↦ eta (Additive.ofMul (g⁻¹ * h))
      map_zero' := rfl
      map_add' := fun _ _ ↦ rfl }
  exact ZMod.map_smul ev a χ

/-- Continuous additive characters are linearly equivalent to homogeneous one-cocycles. -/
def continuousH1ZModEquivCocycles :
    ContinuousH1ZMod (p := p) (G := G₀) ≃ₗ[ZMod p]
      ClassFieldTower.Cohomology.trivialZModPCocycles p G₀ 1 where
  toFun := cocycleOfH1
  invFun := h1OfCocycle
  map_add' := cocycleOfH1_add
  map_smul' := cocycleOfH1_smul
  left_inv := h1OfCocycle_cocycleOfH1
  right_inv := cocycleOfH1_h1OfCocycle

/-- For trivial small-universe coefficients, every homogeneous zero-cochain has zero differential. -/
theorem trivialZModPCochains_d_zero_one :
    (ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 0 1 = 0 := by
  apply ConcreteCategory.ext
  apply ContinuousLinearMap.ext
  intro sigma
  change ((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).d 0 1).hom sigma = 0
  apply Subtype.ext
  ext g h
  have hd := TopRep.homogeneousCochains.d_apply
    (ClassFieldTower.Cohomology.trivialZModP p G₀) 0 sigma
  have hdh := congrArg (fun tau => tau g h) hd
  rw [hdh]
  simp [TopRep.d_succ, TopRep.d_zero, TopRep.hom_sub,
    ContIntertwiningMap.sub_apply, coind₁ι_toFun, coind₁Map_toFun]
  change sigma.1 h - sigma.1 g = 0
  have hg := congrArg (fun tau => tau g) (sigma.2 g)
  have hh := congrArg (fun tau => tau h) (sigma.2 h)
  have hg' : sigma.1 1 = sigma.1 g := by
    have hg'' :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModP p G₀) 0).ρ g)
            (sigma.1 1) = sigma.1 g := by
      simpa only [ContRepresentation.coind₁_apply_apply, inv_mul_cancel] using hg
    have htriv :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModP p G₀) 0).ρ g)
            (sigma.1 1) = sigma.1 1 := by
      change (ClassFieldTower.Cohomology.trivialZModP p G₀).ρ g
        (sigma.1 1) = sigma.1 1
      exact ClassFieldTower.Cohomology.trivialZModP_action p G₀ g _
    exact htriv.symm.trans hg''
  have hh' : sigma.1 1 = sigma.1 h := by
    have hh'' :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModP p G₀) 0).ρ h)
            (sigma.1 1) = sigma.1 h := by
      simpa only [ContRepresentation.coind₁_apply_apply, inv_mul_cancel] using hh
    have htriv :
        ((TopRep.resolutionX
          (ClassFieldTower.Cohomology.trivialZModP p G₀) 0).ρ h)
            (sigma.1 1) = sigma.1 1 := by
      change (ClassFieldTower.Cohomology.trivialZModP p G₀).ρ h
        (sigma.1 1) = sigma.1 1
      exact ClassFieldTower.Cohomology.trivialZModP_action p G₀ h _
    exact htriv.symm.trans hh''
  rw [← hg', ← hh']
  exact sub_self _

/-- The canonical `ZMod p`-linear equivalence from continuous additive characters to
degree-one continuous cohomology with small-universe trivial coefficients. -/
def continuousH1ZModEquivContinuousCohomology :
    ContinuousH1ZMod (p := p) (G := G₀) ≃ₗ[ZMod p]
      ClassFieldTower.Cohomology.continuousCohomologyZModP p G₀ 1 :=
  continuousH1ZModEquivCocycles.trans
    (((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).isoHomologyπ
      0 1 (CochainComplex.prev_nat_succ 0)
        trivialZModPCochains_d_zero_one).toContinuousLinearEquiv.toLinearEquiv)

@[simp]
theorem continuousH1ZModEquivContinuousCohomology_apply
    (χ : ContinuousH1ZMod (p := p) (G := G₀)) :
    continuousH1ZModEquivContinuousCohomology χ =
      ContinuousCohomology.π
        (ClassFieldTower.Cohomology.trivialZModP p G₀) 1 (cocycleOfH1 χ) :=
  rfl

@[simp]
theorem continuousH1ZModEquivContinuousCohomology_symm_apply
    (x : ClassFieldTower.Cohomology.continuousCohomologyZModP p G₀ 1) :
    continuousH1ZModEquivContinuousCohomology.symm x =
      h1OfCocycle
        (((ClassFieldTower.Cohomology.trivialZModPCochains p G₀).isoHomologyπ
          0 1 (CochainComplex.prev_nat_succ 0)
            trivialZModPCochains_d_zero_one).inv x) :=
  rfl


end SmallUniverse

end


end ClassFieldTower.Cohomology
