import ProCGroups.ProP.FrattiniPowers
import ProCGroups.ProP.Zassenhaus.GroupLike

set_option autoImplicit false
/-!
# Basic mod-`p` Zassenhaus subgroups

The `n`-th subgroup consists of group elements whose completed group-like
difference lies in the closure of the `n`-th augmentation power.  This leaf
establishes the subgroup, topology, degree-one, and the easy inclusion of the
closed power--commutator core in degree two.
-/

open scoped Topology commutatorElement

namespace ClassFieldTower.ProP

open CompletedGroupAlgebra

noncomputable section

universe u

variable (p : ℕ) [Fact p.Prime]
variable (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The mod-`p` Zassenhaus subgroup defined by the closed augmentation filtration. -/
def zassenhausSubgroup (n : ℕ) : Subgroup G where
  carrier := {g | groupLikeDifference p G g ∈ closedAugmentationPower p G n}
  one_mem' := by simp [groupLikeDifference_one]
  mul_mem' := by
    intro g h hg hh
    change groupLikeDifference p G g ∈ closedAugmentationPower p G n at hg
    change groupLikeDifference p G h ∈ closedAugmentationPower p G n at hh
    change groupLikeDifference p G (g * h) ∈ closedAugmentationPower p G n
    rw [groupLikeDifference_mul]
    exact (closedAugmentationPower p G n).add_mem
      ((closedAugmentationPower p G n).add_mem hg hh)
      ((closedAugmentationPower p G n).mul_mem_left _ hh)
  inv_mem' := by
    intro g hg
    change groupLikeDifference p G g ∈ closedAugmentationPower p G n at hg
    change groupLikeDifference p G g⁻¹ ∈ closedAugmentationPower p G n
    rw [groupLikeDifference_inv]
    exact (closedAugmentationPower p G n).mul_mem_left _ hg

/-- The Zassenhaus filtration is decreasing. -/
theorem zassenhausSubgroup_antitone : Antitone (zassenhausSubgroup p G) := by
  intro m n hmn g hg
  exact closedAugmentationPower_antitone (p := p) (G := G) hmn hg

/-- The first Zassenhaus subgroup is the whole group. -/
@[simp] theorem zassenhausSubgroup_one : zassenhausSubgroup p G 1 = ⊤ := by
  apply le_antisymm le_top
  intro g _
  change groupLikeDifference p G g ∈ closedAugmentationPower p G 1
  rw [closedAugmentationPower]
  apply subset_closure
  rw [Submodule.pow_one]
  exact groupLikeDifference_mem_augmentationIdeal p G g

/-- Every Zassenhaus subgroup is topologically closed. -/
theorem isClosed_zassenhausSubgroup (n : ℕ) :
    IsClosed ((zassenhausSubgroup p G n : Subgroup G) : Set G) := by
  change IsClosed ((groupLikeDifference p G) ⁻¹'
    closure (((modPAugmentationIdeal p G) ^ n :
      Ideal (ModPCompletedGroupAlgebra p G)) : Set (ModPCompletedGroupAlgebra p G)))
  exact isClosed_closure.preimage (continuous_groupLikeDifference p G)

/-- A `p`-th power belongs to the second Zassenhaus layer. -/
theorem pow_mem_zassenhausSubgroup_two (g : G) :
    g ^ p ∈ zassenhausSubgroup p G 2 := by
  have hg1 : groupLikeDifference p G g ∈ closedAugmentationPower p G 1 := by
    rw [closedAugmentationPower]
    apply subset_closure
    rw [Submodule.pow_one]
    exact groupLikeDifference_mem_augmentationIdeal p G g
  have hgp : groupLikeDifference p G g ^ p ∈ closedAugmentationPower p G (1 * p) :=
    pow_mem_closedAugmentationPower (p := p) (G := G) hg1 p
  change groupLikeDifference p G (g ^ p) ∈ closedAugmentationPower p G 2
  rw [groupLikeDifference_pow_prime]
  exact closedAugmentationPower_antitone (p := p) (G := G)
    (show 2 ≤ 1 * p by simpa using (Fact.out : Nat.Prime p).two_le) hgp

/-- A commutator belongs to the second Zassenhaus layer. -/
theorem commutator_mem_zassenhausSubgroup_two (g h : G) :
    ⁅g, h⁆ ∈ zassenhausSubgroup p G 2 := by
  have hg : groupLikeDifference p G g ∈ closedAugmentationPower p G 1 := by
    rw [closedAugmentationPower]
    apply subset_closure
    rw [Submodule.pow_one]
    exact groupLikeDifference_mem_augmentationIdeal p G g
  have hh : groupLikeDifference p G h ∈ closedAugmentationPower p G 1 := by
    rw [closedAugmentationPower]
    apply subset_closure
    rw [Submodule.pow_one]
    exact groupLikeDifference_mem_augmentationIdeal p G h
  change groupLikeDifference p G ⁅g, h⁆ ∈ closedAugmentationPower p G 2
  rw [groupLikeDifference_commutator]
  have hgh :
      groupLikeDifference p G g * groupLikeDifference p G h ∈
        closedAugmentationPower p G 2 := by
    simpa using closedAugmentationPower_mul_mem (p := p) (G := G) hg hh
  have hhg :
      groupLikeDifference p G h * groupLikeDifference p G g ∈
        closedAugmentationPower p G 2 := by
    simpa using closedAugmentationPower_mul_mem (p := p) (G := G) hh hg
  have hsub := (closedAugmentationPower p G 2).sub_mem hgh hhg
  let _ : (closedAugmentationPower p G 2).IsTwoSided :=
    closedAugmentationPower_isTwoSided p G 2
  exact (closedAugmentationPower p G 2).mul_mem_right _
    ((closedAugmentationPower p G 2).mul_mem_right _ hsub)

/-- The closed subgroup generated by `p`-th powers and commutators is contained
in the second Zassenhaus subgroup. -/
theorem closedPowerCommutator_le_zassenhausSubgroup_two :
    closedPowerCommutator p G ≤ zassenhausSubgroup p G 2 := by
  apply Subgroup.topologicalClosure_minimal
  · apply sup_le
    · rw [powerSubgroup, Subgroup.closure_le]
      rintro _ ⟨g, rfl⟩
      exact pow_mem_zassenhausSubgroup_two p G g
    · rw [commutator_def, Subgroup.commutator_le]
      intro g _ h _
      exact commutator_mem_zassenhausSubgroup_two p G g h
  · exact isClosed_zassenhausSubgroup p G 2

end

end ClassFieldTower.ProP
