import ProCGroups.ProP.Zassenhaus.Basic

set_option autoImplicit false
/-!
# Commutator and power laws for the Zassenhaus filtration

The completed group-like commutator identity sends elements of filtration
degrees `i` and `j` to degree `i + j`.  In characteristic `p`, the completed
group-like difference of a `p`-th power is a `p`-th power, giving degree
`p * i`.  The elementwise statements are promoted to the corresponding
subgroup inclusions.
-/

open scoped Topology commutatorElement

namespace ClassFieldTower.ProP

noncomputable section

universe u

variable (p : ℕ) [Fact p.Prime]
variable (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- A commutator of elements of Zassenhaus degrees `i` and `j` has degree
`i + j`. -/
theorem commutator_mem_zassenhausSubgroup_add
    {i j : ℕ} {g h : G}
    (hg : g ∈ zassenhausSubgroup p G i)
    (hh : h ∈ zassenhausSubgroup p G j) :
    ⁅g, h⁆ ∈ zassenhausSubgroup p G (i + j) := by
  change groupLikeDifference p G g ∈ closedAugmentationPower p G i at hg
  change groupLikeDifference p G h ∈ closedAugmentationPower p G j at hh
  change groupLikeDifference p G ⁅g, h⁆ ∈ closedAugmentationPower p G (i + j)
  rw [groupLikeDifference_commutator]
  have hgh : groupLikeDifference p G g * groupLikeDifference p G h ∈
      closedAugmentationPower p G (i + j) :=
    closedAugmentationPower_mul_mem (p := p) (G := G) hg hh
  have hhg : groupLikeDifference p G h * groupLikeDifference p G g ∈
      closedAugmentationPower p G (i + j) := by
    simpa only [Nat.add_comm] using
      closedAugmentationPower_mul_mem (p := p) (G := G) hh hg
  have hsub := (closedAugmentationPower p G (i + j)).sub_mem hgh hhg
  let _ : (closedAugmentationPower p G (i + j)).IsTwoSided :=
    closedAugmentationPower_isTwoSided p G (i + j)
  exact (closedAugmentationPower p G (i + j)).mul_mem_right _
    ((closedAugmentationPower p G (i + j)).mul_mem_right _ hsub)

/-- The commutator subgroup of the `i`-th and `j`-th Zassenhaus subgroups is
contained in degree `i + j`. -/
theorem commutator_zassenhausSubgroup_le_add (i j : ℕ) :
    ⁅zassenhausSubgroup p G i, zassenhausSubgroup p G j⁆ ≤
      zassenhausSubgroup p G (i + j) := by
  rw [Subgroup.commutator_le]
  intro g hg h hh
  exact commutator_mem_zassenhausSubgroup_add p G hg hh

/-- The `p`-th power of an element of Zassenhaus degree `i` has degree
`p * i`. -/
theorem pow_mem_zassenhausSubgroup_mul
    {i : ℕ} {g : G} (hg : g ∈ zassenhausSubgroup p G i) :
    g ^ p ∈ zassenhausSubgroup p G (p * i) := by
  change groupLikeDifference p G g ∈ closedAugmentationPower p G i at hg
  change groupLikeDifference p G (g ^ p) ∈ closedAugmentationPower p G (p * i)
  rw [groupLikeDifference_pow_prime]
  simpa only [Nat.mul_comm] using
    pow_mem_closedAugmentationPower (p := p) (G := G) hg p

/-- The subgroup generated by `p`-th powers in the `i`-th Zassenhaus
subgroup, mapped into the ambient group, is contained in degree `p * i`. -/
theorem powerSubgroup_map_le_zassenhausSubgroup_mul (i : ℕ) :
    (powerSubgroup p (zassenhausSubgroup p G i)).map
        (zassenhausSubgroup p G i).subtype ≤
      zassenhausSubgroup p G (p * i) := by
  rw [powerSubgroup, MonoidHom.map_closure, Subgroup.closure_le]
  rintro _ ⟨x, ⟨g, rfl⟩, rfl⟩
  change (g : G) ^ p ∈ zassenhausSubgroup p G (p * i)
  exact pow_mem_zassenhausSubgroup_mul p G g.2

end

end ClassFieldTower.ProP
