import Mathlib.GroupTheory.FreeGroup.Basic
import Mathlib.Topology.Algebra.Group.Basic
import Mathlib.Topology.Order.Basic
import ProCGroups.Completion.Construction
import ProCGroups.FiniteGeneration.Basic
import ProCGroups.FreeProC.Basic
import ProCGroups.ProC.Category.Basic

set_option autoImplicit false

/-!
# Constructing free pro-C groups of finite rank

Complete the abstract free group, then take its pro-C residual quotient. The
constructed source carries the universal property, rather than assuming one.
-/

namespace ProCGroups.FreeProC

universe u

/-- A free pro-C group on a finite basis, constructed from the abstract free group. -/
noncomputable def finiteFreeProCSource
    (C : FiniteGroupClass.{u}) (hForm : FiniteGroupClass.Formation C)
    (hHer : FiniteGroupClass.Hereditary C)
    (X : Type u) [Finite X] :
    EpimorphicallyFreeProCGroupOnConvergingSetData.{u, u} C := by
  letI : TopologicalSpace (FreeGroup X) := ⊥
  letI : DiscreteTopology (FreeGroup X) := ⟨rfl⟩
  let ι := Completion.proCCompletionMap C hForm (FreeGroup X)
  exact
    { basis := X
      carrier := Completion.proCCompletion C hForm (FreeGroup X)
      inclusion := fun x => ι (FreeGroup.of x)
      isEpimorphicallyFree :=
        proCCompletionOfAbstractFreeGroup_is_free
          (Completion.proCCompletion_isProCCompletion C hForm hHer (FreeGroup X)) }

/-- A group generated by at most d elements is a quotient of the constructed free source. -/
theorem exists_finiteFreeProCSource_surjection
    (C : FiniteGroupClass.{u}) (hForm : FiniteGroupClass.Formation C)
    (hHer : FiniteGroupClass.Hereditary C)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
    (hG : ProC.HasOpenNormalBasisInClass C G) {d : ℕ}
    (hd : FiniteGeneration.TopologicallyGeneratedByAtMost d G) :
    ∃ ψ : (finiteFreeProCSource C hForm hHer (ULift.{u} (Fin d))).carrier →ₜ* G,
      Function.Surjective ψ := by
  have hfg : FiniteGeneration.TopologicallyFinitelyGenerated G :=
    (FiniteGeneration.topologicallyFinitelyGenerated_iff_exists_topologicallyGeneratedByAtMost).2
      ⟨d, hd⟩
  obtain ⟨φ, hφ⟩ := FiniteGeneration.exists_generatingTuple_of_topologicalRank_le_of_finite
    hfg (FiniteGeneration.topologicalRank_le_of_topologicallyGeneratedByAtMost hd)
  let φ' : ULift.{u} (Fin d) → G := fun i => φ i.down
  have hrange : Set.range φ' = Set.range φ := by
    ext g
    constructor
    · rintro ⟨i, rfl⟩
      exact ⟨i.down, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨ULift.up i, rfl⟩
  have hφ' : Generation.TopologicallyGenerates (Set.range φ') := by
    rw [hrange]
    exact hφ
  obtain ⟨ψ, hcont, hsurj, _⟩ :=
    exists_epimorphicallyFreeProCGroupOnConvergingSet_surjecting
      (finiteFreeProCSource C hForm hHer (ULift.{u} (Fin d))).isEpimorphicallyFree
      hG φ' (FamilyConvergesToOneAlongOpenSubgroups.of_finite_domain φ') hφ'
  exact ⟨⟨ψ, hcont⟩, hsurj⟩

end ProCGroups.FreeProC
