import ProCGroups.FoxDifferential.Completed.Continuous.Free.DiscreteGenerators
import ProCGroups.FoxDifferential.Completed.Continuous.Free.Rules
import ProCGroups.FoxDifferential.Completed.Continuous.Topology

set_option autoImplicit false

/-!
# Fox differential: completed — continuous — universal — basic

The principal declarations in this module are:

- `zcUniversalDifferentialFinalTopology`
  The final topology on the completed universal differential module generated by the universal
  crossed differential \(G \to d_{\mathbb{Z}_C\llbracket H\rrbracket}G\). Unlike the finite-rank
  free-coordinate topology, this topology is available for an arbitrary source group and states the
  genuine topological universal property: a map out is continuous exactly when its composite with
  the universal differential is continuous.
- `zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap`
  The representing universal lift as a continuous linear map for the final universal topology, from
  a continuous crossed differential.
- `continuous_zcUniversalDifferential_universalTopology`
  The universal crossed differential is continuous for the final universal topology.
- `continuous_zcCompletedDifferentialModuleLift_universalTopology_iff`
  The completed differential-module criterion is equivalent to the corresponding finite-stage
  coordinate condition.
-/

namespace FoxDifferential

noncomputable section

open scoped BigOperators

universe u v

section UniversalTopology

variable (C : ProCGroups.FiniteGroupClass.{v})
variable {G : Type u} [Group G] [TopologicalSpace G]
variable {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/--
The final topology on the completed universal differential module generated by the universal
crossed differential \(G \to d_{\mathbb{Z}_C\llbracket H\rrbracket}G\). Unlike the finite-rank
free-coordinate topology, this topology is available for an arbitrary source group and states
the genuine topological universal property: a map out is continuous exactly when its composite
with the universal differential is continuous.
-/
@[reducible] def zcUniversalDifferentialFinalTopology (ψ : G →* H) :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  TopologicalSpace.coinduced (zcUniversalDifferential C ψ) inferInstance

/-- The universal crossed differential is continuous for the final universal topology. -/
theorem continuous_zcUniversalDifferential_universalTopology
    (ψ : G →* H) :
    @Continuous G (ZCCompletedDifferentialModule C ψ) inferInstance
      (zcUniversalDifferentialFinalTopology C ψ)
      (zcUniversalDifferential C ψ) :=
  continuous_coinduced_rng

variable {A : Type*} [AddCommGroup A] [Module (ZCCompletedGroupAlgebra C H) A]
variable [TopologicalSpace A]

/--
The completed differential-module criterion is equivalent to the corresponding finite-stage
coordinate condition.
-/
theorem continuous_zcCompletedDifferentialModuleLift_universalTopology_iff
    {ψ : G →* H}
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A) :
    @Continuous (ZCCompletedDifferentialModule C ψ) A
        (zcUniversalDifferentialFinalTopology C ψ) inferInstance
        (crossedHomModuleLift (A := A)
          (zcCompletedGroupAlgebraScalar C ψ) delta) ↔
      Continuous delta := by
  change @Continuous (ZCCompletedDifferentialModule C ψ) A
      (TopologicalSpace.coinduced (zcUniversalDifferential C ψ) inferInstance) inferInstance
      (crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta) ↔
    Continuous delta
  rw [continuous_coinduced_dom]
  have hcomp :
      (crossedHomModuleLift (A := A)
          (zcCompletedGroupAlgebraScalar C ψ) delta) ∘
          (zcUniversalDifferential C ψ) = delta := by
    funext g
    exact crossedHomModuleLift_universal
      (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta g
  rw [hcomp]

section ContinuousLinearMapPackaging

variable (ψ : G →* H)

/-- The completed differential module carries the universal finite-stage topology. -/
instance zcCompletedDifferentialModuleUniversalTopologyInst :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  zcUniversalDifferentialFinalTopology C ψ

/--
The representing universal lift as a continuous linear map for the final universal topology,
from a continuous crossed differential.
-/
def zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcont : Continuous delta) :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A where
  toLinearMap :=
    crossedHomModuleLift (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta
  cont :=
    (continuous_zcCompletedDifferentialModuleLift_universalTopology_iff
      (C := C) (G := G) (H := H) (A := A) (ψ := ψ) delta).2 hcont

/-- Evaluation of the universal-topology continuous lift. -/
@[simp]
theorem zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap_apply
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcont : Continuous delta)
    (m : ZCCompletedDifferentialModule C ψ) :
    zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap
        (C := C) (G := G) (H := H) (A := A) ψ delta hcont m =
      crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta m :=
  rfl

/--
Topological universal representation theorem for completed crossed differentials. With the final
universal topology on the completed differential module, continuous crossed differentials \(G
\to A\) are equivalent to continuous \(\mathbb{Z}_C\llbracket H\rrbracket\)-linear maps out of
the completed universal differential module.
-/
def zcCompletedContinuousCrossedDifferentialEquivContinuousLinearMap :
    {delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A //
        Continuous delta} ≃
      (ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A) where
  toFun delta :=
    zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap
      (C := C) (G := G) (H := H) (A := A) ψ delta.1 delta.2
  invFun f :=
    ⟨{ toFun := fun g => f (zcUniversalDifferential C ψ g)
       map_mul' := by
        intro g h
        change f (zcUniversalDifferential C ψ (g * h)) =
          f (zcUniversalDifferential C ψ g) +
            zcCompletedGroupAlgebraScalar C ψ g •
              f (zcUniversalDifferential C ψ h)
        rw [ScalarCrossedHom.map_mul (zcUniversalDifferential C ψ)]
        simp only [zcCompletedGroupAlgebraScalar_apply, map_add, map_smul] },
      f.cont.comp (continuous_zcUniversalDifferential_universalTopology C ψ)⟩
  left_inv delta := by
    apply Subtype.ext
    apply CrossedHom.ext
    intro g
    exact crossedHomModuleLift_universal
      (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta.1 g
  right_inv f := by
    apply ContinuousLinearMap.ext
    intro m
    let delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A :=
      { toFun := fun g => f (zcUniversalDifferential C ψ g)
        map_mul' := by
          intro g h
          change f (zcUniversalDifferential C ψ (g * h)) =
            f (zcUniversalDifferential C ψ g) +
              zcCompletedGroupAlgebraScalar C ψ g •
                f (zcUniversalDifferential C ψ h)
          rw [ScalarCrossedHom.map_mul (zcUniversalDifferential C ψ)]
          simp only [zcCompletedGroupAlgebraScalar_apply, map_add, map_smul] }
    have hlin :
        f.toLinearMap =
          crossedHomModuleLift (A := A)
            (zcCompletedGroupAlgebraScalar C ψ) delta := by
      apply crossedHomModuleLift_unique
        (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta
      intro g
      rfl
    exact congrFun (congrArg DFunLike.coe hlin.symm) m

end ContinuousLinearMapPackaging

/-- The universal boundary map from the completed differential module to `Z_C[[H]]` is continuous
for the final universal topology whenever the target homomorphism is continuous. -/
theorem continuous_zcToCompletedGroupAlgebra_universalTopology
    (ψ : G →* H) (hψ : Continuous ψ) :
    @Continuous (ZCCompletedDifferentialModule C ψ) (ZCCompletedGroupAlgebra C H)
      (zcUniversalDifferentialFinalTopology C ψ) inferInstance
      (zcToCompletedGroupAlgebra C ψ) := by
  exact
    (continuous_zcCompletedDifferentialModuleLift_universalTopology_iff
      (C := C) (G := G) (H := H) (A := ZCCompletedGroupAlgebra C H)
      (ψ := ψ) (zcCompletedGroupAlgebraBoundary C ψ)).2
      (continuous_zcCompletedGroupAlgebraBoundary (C := C) (G := H) ψ hψ)

end UniversalTopology

section FreeGroupUniversalTopology

variable (C : ProCGroups.FiniteGroupClass.{v})
variable {X : Type u} [Fintype X] [DecidableEq X]
variable {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/--
The finite-rank topology on the completed universal module, induced by completed Fox
coordinates. This is intentionally a named topology, not a global instance.
-/
@[reducible] def zcCompletedDifferentialModuleFreeTopology (ψ : FreeGroup X →* H) :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  TopologicalSpace.induced (zcDifferentialToFreeFoxCoordinates C ψ) inferInstance

omit [Fintype X] in
/--
The coordinate map out of the completed universal module is continuous for the finite-rank
coordinate-induced topology.
-/
theorem continuous_zcDifferentialToFreeFoxCoordinates_freeTopology
    (ψ : FreeGroup X →* H) :
    @Continuous (ZCCompletedDifferentialModule C ψ)
      (ZCFreeFoxCoordinates C (X := X) (H := H))
      (zcCompletedDifferentialModuleFreeTopology C ψ) inferInstance
      (zcDifferentialToFreeFoxCoordinates C ψ) :=
  continuous_induced_dom

/--
The coordinate-to-universal-module map is continuous for the finite-rank coordinate-induced
topology.
-/
theorem continuous_zcFreeFoxCoordinatesLinearMap_freeTopology
    (ψ : FreeGroup X →* H) :
    @Continuous (ZCFreeFoxCoordinates C (X := X) (H := H))
      (ZCCompletedDifferentialModule C ψ) inferInstance
      (zcCompletedDifferentialModuleFreeTopology C ψ)
      (zcFreeFoxCoordinatesLinearMap C ψ) := by
  change @Continuous (ZCFreeFoxCoordinates C (X := X) (H := H))
      (ZCCompletedDifferentialModule C ψ) inferInstance
      (TopologicalSpace.induced (zcDifferentialToFreeFoxCoordinates C ψ) inferInstance)
      (zcFreeFoxCoordinatesLinearMap C ψ)
  rw [continuous_induced_rng]
  have hcomp :
      (zcDifferentialToFreeFoxCoordinates C ψ) ∘
        (zcFreeFoxCoordinatesLinearMap C ψ) =
        id := by
    funext v
    exact congrFun
      (congrArg DFunLike.coe
        (zcDifferentialToFreeFoxCoordinates_comp_zcFreeFoxCoordinatesLinearMap C ψ)) v
  simpa only [hcomp] using continuous_id

/-- The coordinate module `Z_C[[H]]^X` has continuous scalar multiplication. -/
instance instContinuousSMulZCFreeFoxCoordinates :
    ContinuousSMul (ZCCompletedGroupAlgebra C H)
      (ZCFreeFoxCoordinates C (X := X) (H := H)) :=
  inferInstance

/-- The finite-rank completed universal module has continuous scalar multiplication for the
coordinate-induced topology. -/
instance instContinuousSMulZCCompletedDifferentialModuleFreeTopology
    (ψ : FreeGroup X →* H) :
    @ContinuousSMul (ZCCompletedGroupAlgebra C H)
      (ZCCompletedDifferentialModule C ψ)
      inferInstance inferInstance (zcCompletedDifferentialModuleFreeTopology C ψ) :=
  ContinuousSMul.induced (zcDifferentialToFreeFoxCoordinates C ψ)

variable {A : Type*} [AddCommGroup A] [Module (ZCCompletedGroupAlgebra C H) A]

/--
The finite coordinate linear map attached to the generator values of a completed crossed
differential.
-/
def zcFreeCrossedDifferentialCoordinateLift
    {ψ : FreeGroup X →* H}
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A) :
    ZCFreeFoxCoordinates C (X := X) (H := H) →ₗ[ZCCompletedGroupAlgebra C H] A where
  toFun v := ∑ x : X, v x • delta (FreeGroup.of x)
  map_add' v w := by
    simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
  map_smul' r v := by
    simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply, Finset.smul_sum, smul_smul]

omit [DecidableEq X] in
/-- Evaluation formula for the coordinate lift attached to generator values. -/
theorem zcFreeCrossedDifferentialCoordinateLift_apply
    {ψ : FreeGroup X →* H}
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (v : ZCFreeFoxCoordinates C (X := X) (H := H)) :
    zcFreeCrossedDifferentialCoordinateLift (H := H) C delta v =
      ∑ x : X, v x • delta (FreeGroup.of x) :=
  rfl

/--
The coordinate lift applied to the completed free derivative vector recovers the crossed
differential it represents.
-/
theorem zcFreeCrossedDifferentialCoordinateLift_derivativeVector
    (ψ : FreeGroup X →* H)
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (w : FreeGroup X) :
    zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
        (zcFreeGroupFoxDerivativeVector C ψ w) =
      delta w := by
  let L := zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
  let beta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A :=
    (zcFreeGroupFoxDerivativeVector C ψ).mapLinear L
  have hbasis : ∀ x : X, beta (FreeGroup.of x) = delta (FreeGroup.of x) := by
    intro x
    change L (zcFreeGroupFoxDerivativeVector C ψ (FreeGroup.of x)) =
      delta (FreeGroup.of x)
    rw [zcFreeGroupFoxDerivativeVector_of]
    change (∑ y : X,
        ((Pi.single x (1 : ZCCompletedGroupAlgebra C H) :
          ZCFreeFoxCoordinates C (X := X) (H := H)) y) •
          delta (FreeGroup.of y)) =
      delta (FreeGroup.of x)
    rw [Finset.sum_eq_single x]
    · simp only [Pi.single_eq_same, one_smul]
    · intro y _ hy
      simp only [Pi.single_eq_of_ne hy, zero_smul]
    · simp only [Finset.mem_univ, not_true_eq_false, Pi.single_eq_same, one_smul,
        IsEmpty.forall_iff]
  have hbeta_eq :=
    freeCrossedHomWithCoeff_unique
      (A := A) (zcCompletedGroupAlgebraScalar C ψ)
      (fun x : X => delta (FreeGroup.of x)) beta hbasis
  have hdelta_eq :=
    freeCrossedHomWithCoeff_unique
      (A := A) (zcCompletedGroupAlgebraScalar C ψ)
      (fun x : X => delta (FreeGroup.of x)) delta (by intro x; rfl)
  simpa [beta, L] using
    congrArg (fun d : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A => d w)
      (hbeta_eq.trans hdelta_eq.symm)

omit [DecidableEq X] in
/-- The coordinate lift is the representing universal-module lift composed with the
coordinate-to-module map. -/
theorem zcFreeCrossedDifferentialCoordinateLift_eq_completedLift_comp_coordinates
    (ψ : FreeGroup X →* H)
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A) :
    zcFreeCrossedDifferentialCoordinateLift (H := H) C delta =
      (crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta).comp
        (zcFreeFoxCoordinatesLinearMap C ψ) := by
  ext v
  change (∑ x : X, v x • delta (FreeGroup.of x)) =
    crossedHomModuleLift (A := A)
      (zcCompletedGroupAlgebraScalar C ψ) delta
      (∑ x : X, v x • zcUniversalDifferential C ψ (FreeGroup.of x))
  have hlift : ∀ x : X,
      crossedHomModuleLift (A := A)
          (zcCompletedGroupAlgebraScalar C ψ) delta
          (zcUniversalDifferential C ψ (FreeGroup.of x)) =
        delta (FreeGroup.of x) := by
    intro x
    exact crossedHomModuleLift_universal
      (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta (FreeGroup.of x)
  rw [map_sum]
  simp only [map_smul, hlift]

/-- The representing universal-module lift factors through completed Fox coordinates. -/
theorem zcCompletedDifferentialModuleLift_eq_coordinateLift_comp
    (ψ : FreeGroup X →* H)
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A) :
    crossedHomModuleLift (A := A)
      (zcCompletedGroupAlgebraScalar C ψ) delta =
      (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta).comp
        (zcDifferentialToFreeFoxCoordinates C ψ) := by
  apply crossedDifferentialModuleHom_ext
    (A := A) (zcCompletedGroupAlgebraScalar C ψ)
  intro w
  change
    crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta
        (zcUniversalDifferential C ψ w) =
      zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
        (zcDifferentialToFreeFoxCoordinates C ψ
          (zcUniversalDifferential C ψ w))
  have hlift :
      crossedHomModuleLift (A := A)
          (zcCompletedGroupAlgebraScalar C ψ) delta
          (zcUniversalDifferential C ψ w) =
        delta w :=
    crossedHomModuleLift_universal
      (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta w
  rw [hlift, zcDifferentialToFreeFoxCoordinates_universal,
    zcFreeCrossedDifferentialCoordinateLift_derivativeVector]

variable [TopologicalSpace A]

variable {C} in
/-- Continuous representation theorem for finite-rank completed universal modules.

With the coordinate-induced topology on `ZCCompletedDifferentialModule`, the universal linear map
representing a completed crossed differential is continuous exactly when the finite coordinate
linear map determined by its generator values is continuous. -/
theorem continuous_zcCompletedDifferentialModuleLift_freeTopology_iff
    {ψ : FreeGroup X →* H}
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A) :
    @Continuous (ZCCompletedDifferentialModule C ψ) A
        (zcCompletedDifferentialModuleFreeTopology C ψ) inferInstance
        (crossedHomModuleLift (A := A)
          (zcCompletedGroupAlgebraScalar C ψ) delta) ↔
      Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta) := by
  constructor
  · intro h
    let : TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
      zcCompletedDifferentialModuleFreeTopology C ψ
    have h' : Continuous (crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta) := h
    have hcoord :=
      continuous_zcFreeFoxCoordinatesLinearMap_freeTopology (X := X) (H := H) C ψ
    have heq :=
      zcFreeCrossedDifferentialCoordinateLift_eq_completedLift_comp_coordinates
        (A := A) C ψ delta
    simpa [heq, LinearMap.comp_apply] using h'.comp hcoord
  · intro h
    let : TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
      zcCompletedDifferentialModuleFreeTopology C ψ
    have hcoord :=
      continuous_zcDifferentialToFreeFoxCoordinates_freeTopology (X := X) (H := H) C ψ
    have heq :=
      zcCompletedDifferentialModuleLift_eq_coordinateLift_comp
        (A := A) C ψ delta
    simpa [heq, LinearMap.comp_apply] using h.comp hcoord

section ContinuousLinearMapPackaging

variable (ψ : FreeGroup X →* H)

/--
The free completed differential pre-module carries the finite-stage topology used before
quotienting by crossed-differential relations.
-/
@[reducible] def zcCompletedDifferentialModuleFreeTopologyInst :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  zcCompletedDifferentialModuleFreeTopology C ψ

attribute [local instance] zcCompletedDifferentialModuleFreeTopologyInst

/-- The completed coordinate map as a continuous linear map for the coordinate-induced topology. -/
def zcDifferentialToFreeFoxCoordinatesContinuousLinearMap :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H]
      ZCFreeFoxCoordinates C (X := X) (H := H) where
  toLinearMap := zcDifferentialToFreeFoxCoordinates C ψ
  cont := continuous_zcDifferentialToFreeFoxCoordinates_freeTopology (X := X) (H := H) C ψ

omit [Fintype X] in
/-- Evaluation of the continuous completed coordinate map. -/
@[simp]
theorem zcDifferentialToFreeFoxCoordinatesContinuousLinearMap_apply
    (m : ZCCompletedDifferentialModule C ψ) :
    zcDifferentialToFreeFoxCoordinatesContinuousLinearMap (X := X) (H := H) C ψ m =
      zcDifferentialToFreeFoxCoordinates C ψ m :=
  rfl

/--
The coordinate-to-universal map as a continuous linear map for the coordinate-induced topology.
-/
def zcFreeFoxCoordinatesContinuousLinearMap :
    ZCFreeFoxCoordinates C (X := X) (H := H) →L[ZCCompletedGroupAlgebra C H]
      ZCCompletedDifferentialModule C ψ where
  toLinearMap := zcFreeFoxCoordinatesLinearMap C ψ
  cont := continuous_zcFreeFoxCoordinatesLinearMap_freeTopology (X := X) (H := H) C ψ

/-- Evaluation of the continuous coordinate-to-universal map. -/
@[simp]
theorem zcFreeFoxCoordinatesContinuousLinearMap_apply
    (v : ZCFreeFoxCoordinates C (X := X) (H := H)) :
    zcFreeFoxCoordinatesContinuousLinearMap (X := X) (H := H) C ψ v =
      zcFreeFoxCoordinatesLinearMap C ψ v :=
  rfl

/-- A finite coordinate lift bundled as a continuous linear map, once its continuity is known. -/
def zcFreeCrossedDifferentialCoordinateContinuousLinearMap
    {ψ : FreeGroup X →* H}
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcont : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta)) :
    ZCFreeFoxCoordinates C (X := X) (H := H) →L[ZCCompletedGroupAlgebra C H] A where
  toLinearMap := zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
  cont := hcont

omit [DecidableEq X] in
/-- Evaluation of the continuous coordinate lift attached to generator values. -/
@[simp]
theorem zcFreeCrossedDifferentialCoordinateContinuousLinearMap_apply
    {ψ : FreeGroup X →* H}
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcont : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta))
    (v : ZCFreeFoxCoordinates C (X := X) (H := H)) :
    zcFreeCrossedDifferentialCoordinateContinuousLinearMap
        (X := X) (H := H) (A := A) C delta hcont v =
      ∑ x : X, v x • delta (FreeGroup.of x) :=
  rfl

/-- The representing universal lift bundled as a continuous linear map, once its continuity for
the coordinate-induced topology is known. -/
def zcCompletedDifferentialModuleLiftContinuousLinearMap
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcont : Continuous (crossedHomModuleLift (A := A)
      (zcCompletedGroupAlgebraScalar C ψ) delta)) :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A where
  toLinearMap :=
    crossedHomModuleLift (A := A) (zcCompletedGroupAlgebraScalar C ψ) delta
  cont := hcont

omit [Fintype X] in
/-- Evaluation of the continuous representing universal lift. -/
@[simp]
theorem zcCompletedDifferentialModuleLiftContinuousLinearMap_apply
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcont : Continuous (crossedHomModuleLift (A := A)
      (zcCompletedGroupAlgebraScalar C ψ) delta))
    (m : ZCCompletedDifferentialModule C ψ) :
    zcCompletedDifferentialModuleLiftContinuousLinearMap
        (X := X) (H := H) (A := A) C ψ delta hcont m =
      crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta m :=
  rfl

/-- Continuous representation theorem packaged as a continuous linear map under continuity of the
finite coordinate lift. -/
def zcCompletedDifferentialModuleLiftContinuousLinearMapOfCoordinate
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcoord : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta)) :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A :=
  zcCompletedDifferentialModuleLiftContinuousLinearMap
    (X := X) (H := H) (A := A) C ψ delta
    ((continuous_zcCompletedDifferentialModuleLift_freeTopology_iff
      (X := X) (H := H) (A := A) (ψ := ψ) delta).2 hcoord)

/--
Evaluation of the continuous universal lift obtained from a continuous finite coordinate lift.
-/
@[simp]
theorem zcCompletedDifferentialModuleLiftContinuousLinearMapOfCoordinate_apply
    (delta : ScalarCrossedHom (zcCompletedGroupAlgebraScalar C ψ) A)
    (hcoord : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta))
    (m : ZCCompletedDifferentialModule C ψ) :
    zcCompletedDifferentialModuleLiftContinuousLinearMapOfCoordinate
        (X := X) (H := H) (A := A) C ψ delta hcoord m =
      crossedHomModuleLift (A := A)
        (zcCompletedGroupAlgebraScalar C ψ) delta m :=
  rfl

end ContinuousLinearMapPackaging

end FreeGroupUniversalTopology

end

end FoxDifferential
