import ClassFieldTheory.LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusBaseEquiv
import ClassFieldTheory.LubinTate.EqualCharacteristic.CompletedLevel.DirectThetaFrobeniusFixed
import ClassFieldTheory.LubinTate.EqualCharacteristic.CompletedLevel.DirectTargetLevelEmbedding

set_option autoImplicit false

/-!
# The completed theta-intertwining theorem: the fixed field of the prescribed completed lift

Let `delta` be the completed lift whose action on the standard primitive
point is `[u⁻¹]`.  This file defines the Frobenius fixed field `Sigma`, places
the fixed analytic value `theta(lambda)` in it, and factors the finite
target `uT` Lubin--Tate level through `Sigma`.
-/

noncomputable section

open scoped LaurentSeries PowerSeries


universe u v

namespace LubinTate
namespace EqualCharacteristic

open LocalFieldTheory.DiscreteValuationField

variable {K : Type u} [Field K]

noncomputable local instance equalCharacteristicCompletedFrobeniusFixedBaseAlgebra
    (F : LocalField.{u, v} K) :
    Algebra F.residueField⸨X⸩
      (equalCharacteristicCompletedUnramifiedField F.residueField) :=
  laurentSeriesCoefficientAlgebra

noncomputable local instance equalCharacteristicCompletedFrobeniusFixedLevelAlgebra
    (F : LocalField.{u, v} K) (n : ℕ) :
    Algebra F.residueField⸨X⸩
      (equalCharacteristicCompletedLevelField F n) :=
  RingHom.toAlgebra
    ((algebraMap (equalCharacteristicCompletedUnramifiedField F.residueField)
        (equalCharacteristicCompletedLevelField F n)).comp
      (algebraMap F.residueField⸨X⸩
        (equalCharacteristicCompletedUnramifiedField F.residueField)))

local instance equalCharacteristicCompletedFrobeniusFixedScalarTower
    (F : LocalField.{u, v} K) (n : ℕ) :
    IsScalarTower F.residueField⸨X⸩
      (equalCharacteristicCompletedUnramifiedField F.residueField)
      (equalCharacteristicCompletedLevelField F n) :=
  IsScalarTower.of_algebraMap_eq' rfl

/-- The cyclic subgroup generated by the completed theta-intertwining theorem completed Frobenius lift. -/
noncomputable def equalCharacteristicCompletedFrobeniusSubgroup
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ) :
    Subgroup
      (equalCharacteristicCompletedLevelField F n ≃ₐ[F.residueField⸨X⸩]
        equalCharacteristicCompletedLevelField F n) :=
  Subgroup.zpowers
    (equalCharacteristicCompletedFrobeniusAlgEquiv F a n)

/-- The field `Sigma` fixed by the prescribed lift in the completed theta-intertwining theorem. -/
noncomputable def equalCharacteristicCompletedFrobeniusFixedField
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ) :
    IntermediateField F.residueField⸨X⸩
      (equalCharacteristicCompletedLevelField F n) :=
  IntermediateField.fixedField
    (equalCharacteristicCompletedFrobeniusSubgroup F a n)

/-- Fixedness under the generator puts `theta(lambda)` in the fixed field
of every integral power of the generator. -/
theorem equalCharacteristicDirectThetaAtCompletedPrimitiveRoot_mem_fixedField
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ) :
    (equalCharacteristicDirectThetaAtCompletedPrimitiveRoot F a n :
        equalCharacteristicCompletedLevelField F n) ∈
      equalCharacteristicCompletedFrobeniusFixedField F a n := by
  rw [equalCharacteristicCompletedFrobeniusFixedField,
    IntermediateField.mem_fixedField_iff]
  intro σ hσ
  obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hσ
  have hfixed :
      (equalCharacteristicDirectThetaAtCompletedPrimitiveRoot F a n :
          equalCharacteristicCompletedLevelField F n) ∈
        MulAction.fixedBy
          (equalCharacteristicCompletedLevelField F n)
          (equalCharacteristicCompletedFrobeniusAlgEquiv F a n) := by
    rw [MulAction.mem_fixedBy]
    change equalCharacteristicCompletedFrobeniusAlgEquiv F a n
        (equalCharacteristicDirectThetaAtCompletedPrimitiveRoot F a n :
          equalCharacteristicCompletedLevelField F n) = _
    rw [equalCharacteristicCompletedFrobeniusAlgEquiv_apply]
    exact
      equalCharacteristicCompletedFrobeniusLift_directThetaFixed F a n
  exact MulAction.mem_fixedBy_zpow hfixed j

private theorem algHom_adjoin_singleton_mem_intermediateField
    {k Omega L : Type*} [Field k] [Field Omega] [Field L]
    [Algebra k Omega] [Algebra k L]
    (r : Omega)
    (ι : (IntermediateField.adjoin k ({r} : Set Omega)) →ₐ[k] L)
    (S : IntermediateField k L)
    (hr : ι
        (⟨r, IntermediateField.subset_adjoin k ({r} : Set Omega)
          (Set.mem_singleton r)⟩ :
          IntermediateField.adjoin k ({r} : Set Omega)) ∈ S)
    (x : IntermediateField.adjoin k ({r} : Set Omega)) :
    ι x ∈ S := by
  let M := IntermediateField.adjoin k ({r} : Set Omega)
  have hall : ∀ y : Omega, ∀ hy : y ∈ M, ι ⟨y, hy⟩ ∈ S := by
    intro y hy
    induction hy using IntermediateField.adjoin_induction with
    | mem y hy =>
        rw [Set.mem_singleton_iff] at hy
        subst y
        exact hr
    | algebraMap c =>
        have hmem : ι (algebraMap k M c) ∈ S := by
          rw [ι.commutes]
          exact S.algebraMap_mem c
        exact hmem
    | add y z hy hz ihy ihz =>
        have hmem : ι ((⟨y, hy⟩ : M) + ⟨z, hz⟩) ∈ S := by
          change ι.toRingHom ((⟨y, hy⟩ : M) + ⟨z, hz⟩) ∈ S
          rw [ι.toRingHom.map_add (⟨y, hy⟩ : M) (⟨z, hz⟩ : M)]
          exact S.add_mem ihy ihz
        exact hmem
    | inv y hy ihy =>
        have hmem : ι ((⟨y, hy⟩ : M)⁻¹) ∈ S := by
          change ι.toRingHom ((⟨y, hy⟩ : M)⁻¹) ∈ S
          rw [map_inv₀ ι.toRingHom (⟨y, hy⟩ : M)]
          exact S.inv_mem ihy
        exact hmem
    | mul y z hy hz ihy ihz =>
        have hmem : ι ((⟨y, hy⟩ : M) * ⟨z, hz⟩) ∈ S := by
          change ι.toRingHom ((⟨y, hy⟩ : M) * ⟨z, hz⟩) ∈ S
          rw [ι.toRingHom.map_mul (⟨y, hy⟩ : M) (⟨z, hz⟩ : M)]
          exact S.mul_mem ihy ihz
        exact hmem
  exact hall x.1 x.2

/-- Every element of the embedded finite target level is fixed by the
prescribed completed lift. -/
theorem equalCharacteristicDirectTargetLevelFieldToCompleted_mem_fixedField
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ)
    (x : equalCharacteristicChangedLevelField F a n) :
    equalCharacteristicDirectTargetLevelFieldToCompleted F a n x ∈
      equalCharacteristicCompletedFrobeniusFixedField F a n := by
  let M := equalCharacteristicChangedLevelField F a n
  let S := equalCharacteristicCompletedFrobeniusFixedField F a n
  let ι := equalCharacteristicDirectTargetLevelFieldToCompleted F a n
  have hrootmem : chosenEqualCharacteristicChangedPrimitiveRoot F a n ∈ M := by
    exact IntermediateField.subset_adjoin F.residueField⸨X⸩
      {chosenEqualCharacteristicChangedPrimitiveRoot F a n} (Set.mem_singleton _)
  have hgen :
      (⟨chosenEqualCharacteristicChangedPrimitiveRoot F a n, hrootmem⟩ : M) =
        equalCharacteristicChangedLevelGenerator F a n := by
    apply Subtype.ext
    rfl
  have hroot : ι
      (⟨chosenEqualCharacteristicChangedPrimitiveRoot F a n, hrootmem⟩ : M) ∈ S := by
    rw [hgen, equalCharacteristicDirectTargetLevelFieldToCompleted_generator]
    exact equalCharacteristicDirectThetaAtCompletedPrimitiveRoot_mem_fixedField
      F a n
  exact algHom_adjoin_singleton_mem_intermediateField
    (chosenEqualCharacteristicChangedPrimitiveRoot F a n) ι S hroot x

/-- The target Lubin--Tate level as an algebra inside the canonical fixed
field `Sigma`. -/
noncomputable def equalCharacteristicDirectTargetLevelFieldToFixedField
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ) :
    equalCharacteristicChangedLevelField F a n
      →ₐ[F.residueField⸨X⸩]
        equalCharacteristicCompletedFrobeniusFixedField F a n :=
  (equalCharacteristicDirectTargetLevelFieldToCompleted F a n).codRestrict
    (equalCharacteristicCompletedFrobeniusFixedField F a n).toSubalgebra
    (equalCharacteristicDirectTargetLevelFieldToCompleted_mem_fixedField
      F a n)

/-- States the theorem `equalCharacteristicDirectTargetLevelFieldToFixedField_generator`. -/
@[simp]
theorem equalCharacteristicDirectTargetLevelFieldToFixedField_generator
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ) :
    equalCharacteristicDirectTargetLevelFieldToFixedField F a n
        (equalCharacteristicChangedLevelGenerator F a n) =
      ⟨(equalCharacteristicDirectThetaAtCompletedPrimitiveRoot F a n :
          equalCharacteristicCompletedLevelField F n),
        equalCharacteristicDirectThetaAtCompletedPrimitiveRoot_mem_fixedField
          F a n⟩ := by
  apply Subtype.ext
  exact equalCharacteristicDirectTargetLevelFieldToCompleted_generator F a n

end EqualCharacteristic
end LubinTate
