import ClassFieldTheory.LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldCoefficientDescent

set_option autoImplicit false

/-!
# The completed theta-intertwining theorem: generation of the completed Frobenius fixed field

The coefficient-descent inclusion and the already proved fixedness of the
direct theta value identify the fixed field with its simple Laurent-base
extension.
-/

noncomputable section

open scoped LaurentSeries Polynomial PowerSeries


universe u v

namespace LubinTate
namespace EqualCharacteristic

open LocalFieldTheory.DiscreteValuationField

variable {K : Type u} [Field K]

noncomputable local instance
    equalCharacteristicCompletedFrobeniusFixedFieldGenerationBaseAlgebra
    (F : LocalField.{u, v} K) :
    Algebra F.residueField⸨X⸩
      (equalCharacteristicCompletedUnramifiedField F.residueField) :=
  laurentSeriesCoefficientAlgebra

noncomputable local instance
    equalCharacteristicCompletedFrobeniusFixedFieldGenerationLevelAlgebra
    (F : LocalField.{u, v} K) (n : ℕ) :
    Algebra F.residueField⸨X⸩
      (equalCharacteristicCompletedLevelField F n) :=
  RingHom.toAlgebra
    ((algebraMap (equalCharacteristicCompletedUnramifiedField F.residueField)
        (equalCharacteristicCompletedLevelField F n)).comp
      (algebraMap F.residueField⸨X⸩
        (equalCharacteristicCompletedUnramifiedField F.residueField)))

local instance
    equalCharacteristicCompletedFrobeniusFixedFieldGenerationScalarTower
    (F : LocalField.{u, v} K) (n : ℕ) :
    IsScalarTower F.residueField⸨X⸩
      (equalCharacteristicCompletedUnramifiedField F.residueField)
      (equalCharacteristicCompletedLevelField F n) :=
  IsScalarTower.of_algebraMap_eq' rfl

/-- The Frobenius fixed field is exactly the finite target Lubin--Tate level
generated by `theta(lambda)` inside the completed field. -/
theorem equalCharacteristicCompletedFrobeniusFixedField_eq_adjoin_directTheta
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (a : F.residueField⟦X⟧ˣ) (n : ℕ) :
    equalCharacteristicCompletedFrobeniusFixedField F a n =
      IntermediateField.adjoin F.residueField⸨X⸩
        ({(equalCharacteristicDirectThetaAtCompletedPrimitiveRoot F a n :
          equalCharacteristicCompletedLevelField F n)} :
          Set (equalCharacteristicCompletedLevelField F n)) := by
  apply le_antisymm
  · intro x hx
    apply equalCharacteristicCompletedFrobenius_fixed_mem_adjoin_directTheta F a n x
    change x ∈ IntermediateField.fixedField
      (equalCharacteristicCompletedFrobeniusSubgroup F a n) at hx
    exact (IntermediateField.mem_fixedField_iff
      (H := equalCharacteristicCompletedFrobeniusSubgroup F a n) x).1 hx
      (equalCharacteristicCompletedFrobeniusAlgEquiv F a n)
      (Subgroup.mem_zpowers _)
  · apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact
      equalCharacteristicDirectThetaAtCompletedPrimitiveRoot_mem_fixedField
        F a n

end EqualCharacteristic
end LubinTate
