import ProCGroups.FiniteGroups.StandardClasses
import ProCGroups.Generation.QuotientCriteria
import ProCGroups.ProC.InverseLimits.FiniteQuotients

set_option autoImplicit false

/-!
# Finite-quotient predicates for profinite groups

This file defines cyclic, abelian, and \(p\)-group open-normal quotient bases. It derives the
cyclic basis associated with a single topological generator and the basic implications between
these predicates.
-/

open Set
open scoped Topology Pointwise

namespace ProCGroups.ProC

universe u v

open InverseSystems

section

variable {G : Type u} [Group G] [TopologicalSpace G]

/-- The identity-neighborhood basis property for open normal subgroups with cyclic quotients. -/
def HasCyclicOpenNormalBasis
    (G : Type u) [Group G] [TopologicalSpace G] : Prop :=
  HasOpenNormalBasisInClass FiniteGroupClass.cyclic G

/-- The identity-neighborhood basis property for open normal subgroups with abelian quotients. -/
def HasAbelianOpenNormalBasis
    (G : Type u) [Group G] [TopologicalSpace G] : Prop :=
  HasOpenNormalBasisInClass FiniteGroupClass.abelian G

/-- The identity-neighborhood basis property for open normal subgroups with finite
\(p\)-group quotients. -/
def HasPGroupOpenNormalBasis (p : ℕ) [Fact (Nat.Prime p)]
    (G : Type u) [Group G] [TopologicalSpace G] : Prop :=
  HasOpenNormalBasisInClass (FiniteGroupClass.pGroup p) G

namespace HasCyclicOpenNormalBasis

/-- A cyclic open-normal quotient basis is also an abelian open-normal quotient basis. -/
theorem hasAbelianOpenNormalBasis (hG : HasCyclicOpenNormalBasis G) : HasAbelianOpenNormalBasis
    G := by
  exact hG.mono (fun {Q} [Group Q] hQ => by
    rcases hQ with ⟨hfin, hcyc⟩
    refine ⟨hfin, ?_⟩
    exact (isMulCommutative_iff (M := Q)).mp (IsCyclic.isMulCommutative (α := Q)))

end HasCyclicOpenNormalBasis

/-- A profinite group topologically generated by one element has a cyclic open-normal quotient
basis. -/
theorem hasCyclicOpenNormalBasis_of_topologicallyGenerates_singleton
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G] {g : G}
    (hg : Generation.TopologicallyGenerates (G := G) ({g} : Set G)) :
    HasCyclicOpenNormalBasis G := by
  refine HasOpenNormalBasisInClass.of_allOpenNormalQuotients (C := FiniteGroupClass.cyclic) ?_
  intro U
  let qg : G ⧸ (U : Subgroup G) := QuotientGroup.mk' (U : Subgroup G) g
  have hquot :
      Generation.TopologicallyGenerates (G := G ⧸ (U : Subgroup G))
        ({qg} : Set (G ⧸ (U : Subgroup G))) := by
    have hmap := Generation.topologicallyGenerates_quotient_image
      (G := G) (N := (U : Subgroup G)) (X := ({g} : Set G)) hg
    simpa only [Set.image_singleton] using hmap
  have hdense :
      Dense (((Subgroup.closure ({qg} : Set (G ⧸ (U : Subgroup G))) : Subgroup
        (G ⧸ (U : Subgroup G))) : Set (G ⧸ (U : Subgroup G)))) :=
    (Generation.topologicallyGenerates_iff_dense
      (G := G ⧸ (U : Subgroup G)) (X := ({qg} : Set (G ⧸ (U : Subgroup G))))).1 hquot
  have htop : Subgroup.zpowers qg = ⊤ := by
    apply SetLike.ext'
    rw [Subgroup.zpowers_eq_closure]
    exact dense_discrete.1 hdense
  have hcyc : IsCyclic (G ⧸ (U : Subgroup G)) :=
    (isCyclic_iff_exists_zpowers_eq_top).2 ⟨qg, htop⟩
  exact ⟨inferInstance, hcyc⟩

end

end ProCGroups.ProC
