import ValuedFieldTheory.LocalField.DiscreteValuationField.FieldNorm

set_option autoImplicit false

/-!
# Base-unit norm images in field towers

This file isolates the purely algebraic source for the Abhyankar norm-image
argument: embedded base units, their powered image in a lower branch, and the
image obtained after applying the lower norm.  The only theorem used is field
norm transitivity.
-/

noncomputable section

universe u

namespace LocalFieldTheory.DiscreteValuationField

open LocalFieldTheory.DiscreteValuationField

section BaseUnits

variable {K L : Type u}
variable [Field K] [Field L] [Algebra K L]

/-- The unit-group map induced by the algebra map. -/
noncomputable def baseUnitsMap : Kˣ →* Lˣ :=
  Units.map (algebraMap K L).toMonoidHom

/--
The defining evaluation formula for `baseUnitsMap` is `baseUnitsMap (K := K) (L := L) x =
Units.map (algebraMap K L).toMonoidHom x`.
-/
@[simp] theorem baseUnitsMap_apply (x : Kˣ) :
    baseUnitsMap (K := K) (L := L) x =
      Units.map (algebraMap K L).toMonoidHom x :=
  rfl

/--
The defining evaluation formula for `coe_baseUnitsMap` is `((baseUnitsMap (K := K) (L := L) x :
Lˣ) : L) = algebraMap K L (x : K)`.
-/
@[simp] theorem coe_baseUnitsMap_apply (x : Kˣ) :
    ((baseUnitsMap (K := K) (L := L) x : Lˣ) : L) =
      algebraMap K L (x : K) :=
  rfl

/-- The subgroup of extension units generated by embedded base units. -/
noncomputable def baseUnitsImageSubgroup : Subgroup Lˣ :=
  (baseUnitsMap (K := K) (L := L)).range

/--
Characterizes `x ∈ baseUnitsImageSubgroup (K := K) (L := L)` by the equivalent condition `∃ y :
Kˣ, baseUnitsMap (K := K) (L := L) y = x`.
-/
@[simp] theorem mem_baseUnitsImageSubgroup_iff (x : Lˣ) :
    x ∈ baseUnitsImageSubgroup (K := K) (L := L) ↔
      ∃ y : Kˣ, baseUnitsMap (K := K) (L := L) y = x :=
  Iff.rfl

/--
Establishes the membership statement `baseUnitsMap (K := K) (L := L) x ∈ baseUnitsImageSubgroup (K
:= K) (L := L)`.
-/
theorem baseUnitsMap_mem_baseUnitsImageSubgroup (x : Kˣ) :
    baseUnitsMap (K := K) (L := L) x ∈
      baseUnitsImageSubgroup (K := K) (L := L) :=
  ⟨x, rfl⟩

end BaseUnits

section Tower

variable {K L M : Type u}
variable [Field K] [Field L] [Field M]
variable [Algebra K L] [Algebra K M] [Algebra L M]
variable [IsScalarTower K L M]

/-- Embedded base units are compatible with field towers. -/
theorem baseUnitsMap_tower (x : Kˣ) :
    baseUnitsMap (K := L) (L := M)
        (baseUnitsMap (K := K) (L := L) x) =
      baseUnitsMap (K := K) (L := M) x := by
  ext
  simpa [baseUnitsMap] using
    (IsScalarTower.algebraMap_apply K L M (x : K)).symm

/-- Elementwise tower transport for the subgroup of embedded base units. -/
theorem baseUnitsMap_mem_baseUnitsImageSubgroup_tower
    {x : Lˣ} (hx : x ∈ baseUnitsImageSubgroup (K := K) (L := L)) :
    baseUnitsMap (K := L) (L := M) x ∈
      baseUnitsImageSubgroup (K := K) (L := M) := by
  rcases hx with ⟨y, hy⟩
  refine ⟨y, ?_⟩
  rw [← hy]
  exact (baseUnitsMap_tower (K := K) (L := L) (M := M) y).symm

/-- Subgroup-level tower transport for embedded base units. -/
theorem baseUnitsImageSubgroup_map_le_tower :
    (baseUnitsImageSubgroup (K := K) (L := L)).map
        (baseUnitsMap (K := L) (L := M)) ≤
      baseUnitsImageSubgroup (K := K) (L := M) := by
  intro x hx
  rcases hx with ⟨y, hyS, hyx⟩
  rw [← hyx]
  exact baseUnitsMap_mem_baseUnitsImageSubgroup_tower
    (K := K) (L := L) (M := M) hyS

end Tower

section LowerNormTower

variable {K L M : Type u}
variable [Field K] [Field L] [Field M]
variable [Algebra K L] [Algebra L M]

/-- The `[M : L]`-power endomorphism on lower-branch units. -/
noncomputable def finrankPowerUnitsHom : Lˣ →* Lˣ where
  toFun x := x ^ Module.finrank L M
  map_one' := by
    simp
  map_mul' x y := by
    simpa using mul_pow x y (Module.finrank L M)

/-- The subgroup of lower-branch units obtained by taking `[M : L]`-th powers
of embedded base units. -/
noncomputable def poweredBaseUnitsImageSubgroup : Subgroup Lˣ :=
  (baseUnitsImageSubgroup (K := K) (L := L)).map
    (finrankPowerUnitsHom (L := L) (M := M))

/-- A powered embedded base unit lies in the powered image subgroup. -/
theorem pow_mem_poweredBaseUnitsImageSubgroup_of_mem
    {x : Lˣ} (hx : x ∈ baseUnitsImageSubgroup (K := K) (L := L)) :
    x ^ Module.finrank L M ∈
      poweredBaseUnitsImageSubgroup (K := K) (L := L) (M := M) :=
  ⟨x, hx, rfl⟩

/-- A base unit embedded from `K` to `L` has its `[M : L]`-th power in the norm
subgroup for `M/L`. -/
theorem baseUnitsMap_pow_finrank_mem_fieldNormSubgroup_tower
    (x : Kˣ) :
    baseUnitsMap (K := K) (L := L) x ^ Module.finrank L M ∈
      fieldNormSubgroup L M :=
  fieldNormSubgroup_pow_finrank_mem L M
    (baseUnitsMap (K := K) (L := L) x)

/-- Elementwise comparison with the norm subgroup: every element of the
`K`-base-unit image inside `L` becomes a norm from `M/L` after taking the
`[M : L]`-th power. -/
theorem pow_finrank_mem_fieldNormSubgroup_of_mem_baseUnitsImage_tower
    {x : Lˣ} (hx : x ∈ baseUnitsImageSubgroup (K := K) (L := L)) :
    x ^ Module.finrank L M ∈ fieldNormSubgroup L M := by
  rcases hx with ⟨y, hy⟩
  rw [← hy]
  exact baseUnitsMap_pow_finrank_mem_fieldNormSubgroup_tower
    (K := K) (L := L) (M := M) y

/-- The powered embedded-base-unit image is contained in the field-norm
subgroup for `M/L`. -/
theorem poweredBaseUnitsImageSubgroup_le_fieldNormSubgroup :
    poweredBaseUnitsImageSubgroup (K := K) (L := L) (M := M) ≤
      fieldNormSubgroup L M := by
  intro x hx
  rcases hx with ⟨y, hyS, hyx⟩
  rw [← hyx]
  exact pow_finrank_mem_fieldNormSubgroup_of_mem_baseUnitsImage_tower
    (K := K) (L := L) (M := M) hyS

end LowerNormTower

section NormDownTower

variable {K L M : Type u}
variable [Field K] [Field L] [Field M]
variable [Algebra K L] [Algebra L M]

/-- The `K`-norm image of the powered embedded-base-unit subgroup in the lower
branch. -/
noncomputable def normPoweredBaseUnitsImageSubgroup : Subgroup Kˣ :=
  (poweredBaseUnitsImageSubgroup (K := K) (L := L) (M := M)).map
    (normUnits K L)

/-- A powered embedded base unit, after applying `N_{L/K}`, lies in the normed
powered image subgroup. -/
theorem fieldNormUnits_pow_mem_normPoweredBaseUnitsImageSubgroup_of_mem
    {x : Lˣ} (hx : x ∈ baseUnitsImageSubgroup (K := K) (L := L)) :
    normUnits K L (x ^ Module.finrank L M) ∈
      normPoweredBaseUnitsImageSubgroup (K := K) (L := L) (M := M) :=
  ⟨x ^ Module.finrank L M,
    pow_mem_poweredBaseUnitsImageSubgroup_of_mem
      (K := K) (L := L) (M := M) hx,
    rfl⟩

variable [Algebra K M] [IsScalarTower K L M] [Module.Free L M]

/-- Norm transitivity sends the normed powered embedded-base-unit image into
the common-top field-norm subgroup `N_{M/K}(Mˣ)`. -/
theorem normPoweredBaseUnitsImageSubgroup_le_fieldNormSubgroup_top :
    normPoweredBaseUnitsImageSubgroup (K := K) (L := L) (M := M) ≤
      fieldNormSubgroup K M := by
  intro x hx
  rcases hx with ⟨y, hyS, hyx⟩
  have hyNorm :
      y ∈ fieldNormSubgroup L M :=
    poweredBaseUnitsImageSubgroup_le_fieldNormSubgroup
      (K := K) (L := L) (M := M) hyS
  rcases hyNorm with ⟨z, hz⟩
  refine ⟨z, ?_⟩
  calc
    normUnits K M z =
        normUnits K L (normUnits L M z) := by
      exact (normUnits_tower K L M z).symm
    _ = normUnits K L y := by
      rw [hz]
    _ = x := hyx

end NormDownTower

end LocalFieldTheory.DiscreteValuationField

end
