import Mathlib.Algebra.Group.Int.TypeTags
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.Tactic

/-!
# Integer multiple subgroups

Pure group-theoretic infrastructure for the subgroup of multiplicative
integers divisible by a fixed integer and its cyclic quotient. It lives below
the discrete-valuation-field layer so generic power-index code does not depend
on valued-field norm modules.

The declarations retain the established
`LocalFieldTheory.DiscreteValuationField` namespace because the same value
group is used by the valuation API; their implementation has no valued-field
hypotheses.
-/

set_option autoImplicit false

namespace LocalFieldTheory.DiscreteValuationField

/-- The subgroup of `Multiplicative ℤ` consisting of elements whose additive
integer is divisible by `d`. -/
def integerMultipleSubgroup (d : ℤ) : Subgroup (Multiplicative ℤ) where
  carrier := {n | d ∣ Multiplicative.toAdd n}
  one_mem' := by
    change d ∣ (0 : ℤ)
    exact dvd_zero d
  mul_mem' := by
    intro x y hx hy
    change d ∣ Multiplicative.toAdd (x * y)
    rw [toAdd_mul]
    exact dvd_add hx hy
  inv_mem' := by
    intro x hx
    change d ∣ Multiplicative.toAdd x⁻¹
    rw [toAdd_inv]
    exact dvd_neg.mpr hx

/-- An integer lies in the subgroup generated by multiples of `n` exactly when `n` divides it. -/
@[simp] theorem mem_integerMultipleSubgroup_iff
    (d : ℤ) (n : Multiplicative ℤ) :
    n ∈ integerMultipleSubgroup d ↔ d ∣ Multiplicative.toAdd n :=
  Iff.rfl

/-- Membership of a multiplicative integer in the multiple subgroup is equivalent to divisibility of
its additive value. -/
@[simp] theorem ofAdd_mem_integerMultipleSubgroup_iff (d n : ℤ) :
    Multiplicative.ofAdd n ∈ integerMultipleSubgroup d ↔ d ∣ n := by
  rw [mem_integerMultipleSubgroup_iff, toAdd_ofAdd]

/-- Multiplying two multiplicative integers from the multiple subgroup remains in that subgroup. -/
theorem ofAdd_mul_mem_integerMultipleSubgroup (d n : ℤ) :
    Multiplicative.ofAdd (d * n) ∈ integerMultipleSubgroup d := by
  rw [ofAdd_mem_integerMultipleSubgroup_iff]
  exact dvd_mul_right d n

/-- The multiple subgroup is closed under multiplication in either order. -/
theorem ofAdd_mul_comm_mem_integerMultipleSubgroup (d n : ℤ) :
    Multiplicative.ofAdd (n * d) ∈ integerMultipleSubgroup d := by
  rw [mul_comm]
  exact ofAdd_mul_mem_integerMultipleSubgroup d n

/-- Divisibility of generators reverses inclusion between their integer-multiple subgroups. -/
theorem integerMultipleSubgroup_le_of_dvd {a b : ℤ} (hab : a ∣ b) :
    integerMultipleSubgroup b ≤ integerMultipleSubgroup a := by
  intro n hn
  rw [mem_integerMultipleSubgroup_iff] at hn ⊢
  exact dvd_trans hab hn

/-- Every multiplicative integer belongs to the subgroup of multiples of one. -/
@[simp] theorem integerMultipleSubgroup_one_eq_top :
    integerMultipleSubgroup (1 : ℤ) = ⊤ := by
  ext n
  rw [mem_integerMultipleSubgroup_iff]
  simp

/-- Reduction of multiplicative integers modulo the subgroup of multiples of
`d`, written as a homomorphism to `Multiplicative (ZMod |d|)`. -/
def multiplicativeIntToZModHom (d : ℤ) :
    Multiplicative ℤ →* Multiplicative (ZMod d.natAbs) :=
  AddMonoidHom.toMultiplicative (Int.castAddHom (ZMod d.natAbs))

/-- Reduction modulo `n` sends a multiplicative integer to the residue class of its additive value.
Reduction modulo `n` sends a multiplicative integer to the residue class of its additive value. -/
@[simp] theorem multiplicativeIntToZModHom_apply
    (d : ℤ) (n : Multiplicative ℤ) :
    multiplicativeIntToZModHom d n =
      Multiplicative.ofAdd ((n.toAdd : ZMod d.natAbs)) :=
  rfl

/-- The kernel of reduction modulo `n` is precisely the subgroup of integer multiples of `n`. -/
theorem multiplicativeIntToZModHom_ker_eq_integerMultipleSubgroup (d : ℤ) :
    (multiplicativeIntToZModHom d).ker = integerMultipleSubgroup d := by
  ext n
  change ((n.toAdd : ZMod d.natAbs) = 0) ↔ d ∣ n.toAdd
  rw [ZMod.intCast_zmod_eq_zero_iff_dvd]
  exact Int.natAbs_dvd

/-- Every residue class modulo `n` is represented by a multiplicative integer. -/
theorem multiplicativeIntToZModHom_surjective (d : ℤ) :
    Function.Surjective (multiplicativeIntToZModHom d) := by
  intro q
  rcases ZMod.intCast_surjective q.toAdd with ⟨n, hn⟩
  refine ⟨Multiplicative.ofAdd n, ?_⟩
  change Multiplicative.ofAdd ((n : ZMod d.natAbs)) = q
  rw [hn]
  rfl

/-- The quotient of multiplicative integers by multiples of `d` is the
standard cyclic value group `Multiplicative (ZMod |d|)`. -/
noncomputable def valueModIntegerMultipleSubgroupEquivZMod (d : ℤ) :
    Multiplicative ℤ ⧸ integerMultipleSubgroup d ≃*
      Multiplicative (ZMod d.natAbs) :=
  (QuotientGroup.quotientMulEquivOfEq
      (multiplicativeIntToZModHom_ker_eq_integerMultipleSubgroup d).symm).trans
    (QuotientGroup.quotientKerEquivOfSurjective
      (multiplicativeIntToZModHom d)
      (multiplicativeIntToZModHom_surjective d))

/-- The quotient-to-`ZMod` equivalence sends a quotient class to reduction of its representative
modulo `n`. -/
@[simp] theorem valueModIntegerMultipleSubgroupEquivZMod_mk
    (d n : ℤ) :
    valueModIntegerMultipleSubgroupEquivZMod d
        (QuotientGroup.mk' (integerMultipleSubgroup d)
          (Multiplicative.ofAdd n)) =
      Multiplicative.ofAdd ((n : ZMod d.natAbs)) := by
  change
    (QuotientGroup.quotientKerEquivOfSurjective
        (multiplicativeIntToZModHom d)
        (multiplicativeIntToZModHom_surjective d))
      (QuotientGroup.mk' (multiplicativeIntToZModHom d).ker
        (Multiplicative.ofAdd n)) =
      Multiplicative.ofAdd ((n : ZMod d.natAbs))
  unfold QuotientGroup.quotientKerEquivOfSurjective
    QuotientGroup.quotientKerEquivOfRightInverse
  change
    QuotientGroup.kerLift (multiplicativeIntToZModHom d)
      (QuotientGroup.mk' (multiplicativeIntToZModHom d).ker
        (Multiplicative.ofAdd n)) =
      Multiplicative.ofAdd ((n : ZMod d.natAbs))
  rfl

end LocalFieldTheory.DiscreteValuationField
