import ClassFieldTheory.LocalClassFieldTheory.Kummer.MaximalLocalKummerPairing
import ClassFieldTheory.LocalClassFieldTheory.Kummer.LocalHilbertSymbolLaws
import ClassFieldTheory.LocalClassFieldTheory.Finite.LocalReciprocity.NormResidueNaturality
import GaloisCohomology.Kummer.Concrete.SimpleExtensionNorm

set_option autoImplicit false

/-!
# Comparison of maximal and simple local Kummer pairings

The chosen simple Kummer extension attached to one radical lies in the maximal
finite Kummer extension.  Restriction of the maximal local Artin automorphism
to that simple extension, together with functoriality of root quotients,
identifies the maximal pairing with the existing local Hilbert symbol.
-/

noncomputable section

namespace KummerTheory

open RamificationTheory

universe u v

variable {K : Type u} {Omega : Type v}
  [Field K] [Field Omega] [Algebra K Omega]

/-- Root quotients commute with inclusion between normal intermediate
fields in a common ambient extension. -/
theorem rootQuotient_map_intermediateFieldInclusion
    (E F : IntermediateField K Omega) (hEF : E ≤ F)
    [Normal K E] (beta : Eˣ) (sigma : Gal(F / K)) :
    rootQuotient (K := K) (L := F)
        (Units.map (IntermediateField.inclusion hEF).toMonoidHom beta) sigma =
      Units.map (IntermediateField.inclusion hEF).toMonoidHom
        (rootQuotient (K := K) (L := E) beta
          (intermediateFieldRestrictNormalHom E F hEF sigma)) := by
  have hcomm :
      IntermediateField.inclusion hEF
          (intermediateFieldRestrictNormalHom E F hEF sigma (beta : E)) =
        sigma (IntermediateField.inclusion hEF (beta : E)) := by
    apply F.val.injective
    exact intermediateFieldRestrictNormalHom_apply_val E F hEF sigma beta
  apply Units.ext
  simp only [rootQuotient, AlgEquiv.smul_units_def,
    Units.val_div_eq_div_val, Units.coe_map]
  calc
    sigma (IntermediateField.inclusion hEF (beta : E)) /
        IntermediateField.inclusion hEF (beta : E) =
      IntermediateField.inclusion hEF
          (intermediateFieldRestrictNormalHom E F hEF sigma (beta : E)) /
        IntermediateField.inclusion hEF (beta : E) :=
      congrArg
        (fun x : F => x / IntermediateField.inclusion hEF (beta : E))
        hcomm.symm
    _ = IntermediateField.inclusion hEF
        (intermediateFieldRestrictNormalHom E F hEF sigma (beta : E) /
          (beta : E)) :=
      (map_div₀ (IntermediateField.inclusion hEF).toRingHom
        (intermediateFieldRestrictNormalHom E F hEF sigma (beta : E))
        (beta : E)).symm

end KummerTheory

namespace LocalClassFieldTheory
namespace Kummer

open KummerTheory LocalFieldTheory RamificationTheory

variable (K : Type) [Field K]
variable [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- Restricting the maximal Kummer Artin automorphism to the simple Kummer
extension gives its defining simple-extension Artin automorphism. -/
theorem maximalLocalArtin_restrict_chosenSimpleKummer
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a b : Kˣ) :
    letI : IsAbelianGalois K (chosenSimpleKummerExtension K n hnK b) :=
      chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
    intermediateFieldRestrictNormalHom
        (chosenSimpleKummerExtension K n hnK b)
        (maximalLocalKummerExtension K n)
        (chosenSimpleKummerExtension_le_maximalKummerExtension K n hnK b)
        (maximalLocalKummerNormResidueAutomorphism K n hnK hmu a) =
      chosenSimpleKummerNormResidueAutomorphism K n hnK hmu b a := by
  let E := chosenSimpleKummerExtension K n hnK b
  let F := maximalLocalKummerExtension K n
  let hEF : E ≤ F :=
    chosenSimpleKummerExtension_le_maximalKummerExtension K n hnK b
  let Delta := maximalKummerSubgroup K n
  let : FiniteDimensional K E :=
    chosenSimpleKummerExtension_finiteDimensional K n hnK b
  let : IsAbelianGalois K E :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  let : FiniteDimensional K F :=
    maximalKummerRadicalExtension_finiteDimensional K n hnK hmu
  let : IsAbelianGalois K F :=
    kummerRadicalExtension_isAbelianGalois
      (K := K) (Omega := SeparableClosure K) n hmu Delta.1
  change intermediateFieldRestrictNormalHom E F hEF
      (abelianLocalArtinMonoidHom K F a) =
    abelianLocalArtinMonoidHom K E a
  exact DFunLike.congr_fun
    (abelianLocalArtinMonoidHom_restrict K E F hEF) a

/-- The maximal pairing evaluated at `(a,b)` agrees with the local Hilbert
symbol homomorphism for the simple extension generated by `b`. -/
theorem maximalLocalKummerPairingRightHom_eq_localHilbertSymbolHom
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a b : Kˣ) :
    maximalLocalKummerPairingRightHom K n hnK hmu a b =
      localHilbertSymbolHom K n hnK hmu b a := by
  let E := chosenSimpleKummerExtension K n hnK b
  let F := maximalLocalKummerExtension K n
  let hEF : E ≤ F :=
    chosenSimpleKummerExtension_le_maximalKummerExtension K n hnK b
  let betaE : Eˣ := chosenSimpleKummerRootUnit K n hnK b
  let betaF : Fˣ :=
    Units.map (IntermediateField.inclusion hEF).toMonoidHom betaE
  let sigmaF : Gal(F / K) :=
    maximalLocalKummerNormResidueAutomorphism K n hnK hmu a
  let sigmaE : Gal(E / K) :=
    chosenSimpleKummerNormResidueAutomorphism K n hnK hmu b a
  let : FiniteDimensional K E :=
    chosenSimpleKummerExtension_finiteDimensional K n hnK b
  let : IsAbelianGalois K E :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  have hbetaF :
      betaF ^ (n : ℕ) = Units.map (algebraMap K F).toMonoidHom b := by
    change
      (Units.map (IntermediateField.inclusion hEF).toMonoidHom betaE) ^
          (n : ℕ) =
        Units.map (algebraMap K F).toMonoidHom b
    rw [← map_pow, show betaE ^ (n : ℕ) =
      Units.map (algebraMap K E).toMonoidHom b by
        exact chosenSimpleKummerRootUnit_pow K n hnK b]
    apply Units.ext
    rfl
  have hrestrict :
      intermediateFieldRestrictNormalHom E F hEF sigmaF = sigmaE := by
    simpa only [E, F, hEF, sigmaF, sigmaE] using
      maximalLocalArtin_restrict_chosenSimpleKummer K n hnK hmu a b
  have hmaxVal :
      Units.map (algebraMap K F).toMonoidHom
          (maximalLocalKummerPairingRightHom K n hnK hmu a b).1 =
        rootQuotient (K := K) (L := F) betaF sigmaF := by
    have h := congrArg Subtype.val
      (maximalLocalKummerPairingRightHom_map_eq_rootQuotient_of_pow
        K n hnK hmu a b betaF hbetaF)
    exact h
  have hlocalVal :
      Units.map (algebraMap K E).toMonoidHom
          (localHilbertSymbolHom K n hnK hmu b a).1 =
        rootQuotient (K := K) (L := E) betaE sigmaE := by
    have h := congrArg Subtype.val
      (localHilbertSymbol_map_eq_rootQuotient K n hnK hmu a b)
    change
      Units.map
          (algebraMap K (chosenSimpleKummerExtension K n hnK b)).toMonoidHom
          (localHilbertSymbol K n hnK hmu a b).1 =
        rootQuotient
          (K := K) (L := chosenSimpleKummerExtension K n hnK b)
          (chosenSimpleKummerRootUnit K n hnK b)
          (chosenSimpleKummerNormResidueAutomorphism K n hnK hmu b a) at h
    simpa only [localHilbertSymbolHom_apply, E, betaE, sigmaE] using h
  apply nthRootsSubgroupMap_injective K F (n : ℕ)
  apply Subtype.ext
  change
    Units.map (algebraMap K F).toMonoidHom
        (maximalLocalKummerPairingRightHom K n hnK hmu a b).1 =
      Units.map (algebraMap K F).toMonoidHom
        (localHilbertSymbolHom K n hnK hmu b a).1
  calc
    Units.map (algebraMap K F).toMonoidHom
        (maximalLocalKummerPairingRightHom K n hnK hmu a b).1 =
        rootQuotient (K := K) (L := F) betaF sigmaF := hmaxVal
    _ = Units.map (IntermediateField.inclusion hEF).toMonoidHom
          (rootQuotient (K := K) (L := E) betaE
            (intermediateFieldRestrictNormalHom E F hEF sigmaF)) := by
      exact rootQuotient_map_intermediateFieldInclusion E F hEF betaE sigmaF
    _ = Units.map (IntermediateField.inclusion hEF).toMonoidHom
          (rootQuotient (K := K) (L := E) betaE sigmaE) := by
      rw [hrestrict]
    _ = Units.map (algebraMap K F).toMonoidHom
          (localHilbertSymbolHom K n hnK hmu b a).1 := by
      rw [← hlocalVal]
      apply Units.ext
      rfl

/-- The local Hilbert symbol is multiplicative in its second argument. -/
@[simp]
theorem localHilbertSymbol_mul_right
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a b c : Kˣ) :
    localHilbertSymbol K n hnK hmu a (b * c) =
      localHilbertSymbol K n hnK hmu a b *
        localHilbertSymbol K n hnK hmu a c := by
  calc
    localHilbertSymbol K n hnK hmu a (b * c) =
        maximalLocalKummerPairingRightHom K n hnK hmu a (b * c) := by
      exact (maximalLocalKummerPairingRightHom_eq_localHilbertSymbolHom
        K n hnK hmu a (b * c)).symm
    _ = maximalLocalKummerPairingRightHom K n hnK hmu a b *
        maximalLocalKummerPairingRightHom K n hnK hmu a c :=
      maximalLocalKummerPairing_mul_right K n hnK hmu a b c
    _ = localHilbertSymbol K n hnK hmu a b *
        localHilbertSymbol K n hnK hmu a c := by
      rw [maximalLocalKummerPairingRightHom_eq_localHilbertSymbolHom,
        maximalLocalKummerPairingRightHom_eq_localHilbertSymbolHom]
      simp only [localHilbertSymbolHom_apply]

/-- The local Hilbert symbol of a unit and its nonzero complement is one. -/
@[simp]
theorem localHilbertSymbol_steinberg
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (a : Kˣ) (h_one_sub : 1 - (a : K) ≠ 0) :
    localHilbertSymbol K n hnK hmu a
        (Units.mk0 (1 - (a : K)) h_one_sub) = 1 := by
  apply
    (localHilbertSymbol_eq_one_iff_mem_localNormSubgroup
      K n hnK hmu a (Units.mk0 (1 - (a : K)) h_one_sub)).2
  exact
    unit_mem_localNormSubgroup_chosenSimpleKummerExtension_one_sub
      K n hnK hmu a h_one_sub

/-- The local Hilbert symbol of a unit and its negative is one. -/
@[simp]
theorem localHilbertSymbol_neg_self
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a : Kˣ) :
    localHilbertSymbol K n hnK hmu a (-a) = 1 := by
  let B : Kˣ → Kˣ → nthRootsSubgroup K (n : ℕ) :=
    fun x y => localHilbertSymbol K n hnK hmu x y
  have hmul_right (x y z : Kˣ) :
      B x (y * z) = B x y * B x z := by
    exact localHilbertSymbol_mul_right K n hnK hmu x y z
  have hinv_left (x y : Kˣ) : B x⁻¹ y = (B x y)⁻¹ := by
    change
      localHilbertSymbolHom K n hnK hmu y x⁻¹ =
        (localHilbertSymbolHom K n hnK hmu y x)⁻¹
    exact map_inv (localHilbertSymbolHom K n hnK hmu y) x
  have hone_left (y : Kˣ) : B 1 y = 1 := by
    change localHilbertSymbolHom K n hnK hmu y 1 = 1
    exact map_one (localHilbertSymbolHom K n hnK hmu y)
  have hone_right (x : Kˣ) : B x 1 = 1 := by
    calc
      B x 1 = maximalLocalKummerPairingRightHom K n hnK hmu x 1 := by
        exact
          (maximalLocalKummerPairingRightHom_eq_localHilbertSymbolHom
            K n hnK hmu x 1).symm
      _ = 1 := map_one (maximalLocalKummerPairingRightHom K n hnK hmu x)
  have hinv_right (x y : Kˣ) : B x y⁻¹ = (B x y)⁻¹ := by
    have hmul := hmul_right x y y⁻¹
    rw [mul_inv_cancel, hone_right] at hmul
    exact eq_inv_of_mul_eq_one_right hmul.symm
  change B a (-a) = 1
  by_cases ha : a = 1
  · subst a
    exact hone_left (-1)
  · have ha_val : (a : K) ≠ 1 := by
      intro h
      apply ha
      apply Units.ext
      exact h
    have hc0 : 1 - (a : K) ≠ 0 := by
      intro h
      exact ha_val (sub_eq_zero.mp h).symm
    have hd0 : 1 - ((a⁻¹ : Kˣ) : K) ≠ 0 := by
      intro h
      apply inv_ne_one.mpr ha_val
      simpa only [Units.val_inv_eq_inv_val] using (sub_eq_zero.mp h).symm
    let c : Kˣ := Units.mk0 (1 - (a : K)) hc0
    let d : Kˣ := Units.mk0 (1 - ((a⁻¹ : Kˣ) : K)) hd0
    have hd : d = (-c) * a⁻¹ := by
      apply Units.ext
      simp only [d, c, Units.val_mk0, Units.val_mul, Units.val_neg,
        Units.val_inv_eq_inv_val]
      change 1 - (a : K)⁻¹ = -(1 - (a : K)) * (a : K)⁻¹
      calc
        1 - (a : K)⁻¹ = ((a : K) - 1) * (a : K)⁻¹ := by
          rw [sub_mul, mul_inv_cancel₀ (Units.ne_zero a), one_mul]
        _ = -(1 - (a : K)) * (a : K)⁻¹ := by ring
    have hs1 : B a c = 1 := by
      exact localHilbertSymbol_steinberg K n hnK hmu a hc0
    have hs2 : B a⁻¹ d = 1 := by
      exact localHilbertSymbol_steinberg K n hnK hmu a⁻¹ hd0
    have hs2' : B a d = 1 := by
      rw [hinv_left] at hs2
      exact inv_eq_one.mp hs2
    have hdiag : B a (-c) = B a a := by
      rw [hd, hmul_right, hinv_right] at hs2'
      exact mul_inv_eq_one.mp hs2'
    have hc : c = (-1 : Kˣ) * (-c) := by simp
    have hneg_diag : B a (-1) * B a a = 1 := by
      rw [hc, hmul_right, hdiag] at hs1
      exact hs1
    rw [show -a = (-1 : Kˣ) * a by simp, hmul_right]
    exact hneg_diag

/-- The local Hilbert symbol is skew-symmetric. -/
theorem localHilbertSymbol_skew
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a b : Kˣ) :
    localHilbertSymbol K n hnK hmu a b =
      (localHilbertSymbol K n hnK hmu b a)⁻¹ := by
  let B : Kˣ → Kˣ → nthRootsSubgroup K (n : ℕ) :=
    fun x y => localHilbertSymbol K n hnK hmu x y
  have hmul_left (x y z : Kˣ) :
      B (x * y) z = B x z * B y z := by
    change
      localHilbertSymbolHom K n hnK hmu z (x * y) =
        localHilbertSymbolHom K n hnK hmu z x *
          localHilbertSymbolHom K n hnK hmu z y
    exact map_mul (localHilbertSymbolHom K n hnK hmu z) x y
  have hmul_right (x y z : Kˣ) :
      B x (y * z) = B x y * B x z := by
    exact localHilbertSymbol_mul_right K n hnK hmu x y z
  have hneg_self (x : Kˣ) : B x (-x) = 1 := by
    exact localHilbertSymbol_neg_self K n hnK hmu x
  have hexpand :
      B (a * b) (-(a * b)) =
        (B a (-a) * B a b) * (B b (-b) * B b a) := by
    rw [hmul_left]
    congr 1
    · rw [show -(a * b) = (-a) * b by simp, hmul_right]
    · rw [show -(a * b) = (-b) * a by simp [mul_comm], hmul_right]
  have hprod : B a b * B b a = 1 := by
    calc
      B a b * B b a =
          (B a (-a) * B a b) * (B b (-b) * B b a) := by
        simp only [hneg_self, one_mul]
      _ = B (a * b) (-(a * b)) := hexpand.symm
      _ = 1 := hneg_self (a * b)
  exact (eq_inv_iff_mul_eq_one).2 hprod

end Kummer
end LocalClassFieldTheory
