import ProCGroups.ProP.Fox.Derivative

set_option autoImplicit false
/-!
# Completed Fox rows of displayed relators

The displayed finite relation family and the whole presentation kernel are
mapped into the same completed Fox-coordinate module.  The closed coefficient
span below is the finite relation module used by the filtered construction.
-/

open scoped Topology

namespace ClassFieldTower.ProP

open ProCGroups

noncomputable section

universe u

variable {p d r : ℕ} [Fact p.Prime]
variable {sourceData :
  FreeProC.EpimorphicallyFreeProCGroupOnConvergingSetData.{u, u}
    (FiniteGroupClass.pGroup p)}
variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]

/-- A displayed relator bundled as a point of the presentation kernel. -/
def displayedRelatorInKernel
    (P : FiniteProPPresentation p d r sourceData G) (i : Fin r) :
    P.quotient.toMonoidHom.ker :=
  ⟨P.relator i, P.relator_mem_kernel i⟩

/-- The completed Fox row produced by one displayed relator. -/
def displayedRelatorFoxRow
    (P : FiniteProPPresentation p d r sourceData G) (i : Fin r) :
    PresentationFoxCoordinates (p := p) (d := d) (G := G) :=
  presentationFoxDerivative P (P.relator i)

/-- The completed Fox row produced by an arbitrary kernel element. -/
def kernelFoxRow
    (P : FiniteProPPresentation p d r sourceData G)
    (x : P.quotient.toMonoidHom.ker) :
    PresentationFoxCoordinates (p := p) (d := d) (G := G) :=
  presentationFoxDerivative P x.1

/-- Displayed rows are the restriction of the full kernel-row family. -/
@[simp] theorem kernelFoxRow_displayedRelator
    (P : FiniteProPPresentation p d r sourceData G) (i : Fin r) :
    kernelFoxRow P (displayedRelatorInKernel P i) =
      displayedRelatorFoxRow P i :=
  rfl

/-- The kernel is the closed normal closure of the displayed family at the
completed-Fox interface. -/
theorem kernel_eq_displayed_closedNormalClosure
    (P : FiniteProPPresentation p d r sourceData G) :
    P.quotient.toMonoidHom.ker =
      ProCGroups.Presentations.closedNormalClosure (Set.range P.relator) :=
  P.kernel_eq_closedNormalClosure

/-- Closed coefficient submodule generated by the finite displayed rows. -/
def displayedRelatorFoxRowClosedSpan
    (P : FiniteProPPresentation p d r sourceData G) :
    Submodule
      (PresentationFoxCoefficientRing (p := p) (G := G))
      (PresentationFoxCoordinates (p := p) (d := d) (G := G)) :=
  (Submodule.span
    (PresentationFoxCoefficientRing (p := p) (G := G))
    (Set.range (displayedRelatorFoxRow P))).topologicalClosure

end

end ClassFieldTower.ProP
