import Mathlib.NumberTheory.Padics.RingHoms
import Mathlib.Topology.Algebra.OpenSubgroup

set_option autoImplicit false

/-!
# Closed additive subgroups of the p-adic integers

A nonzero closed additive subgroup of `ℤ_[p]` contains a nonzero principal
ideal.  Since every nonzero ideal of `ℤ_[p]` is generated by a power of `p`,
such a subgroup is open.
-/

open scoped Topology

namespace PadicInt

/-- A nonzero closed additive subgroup of the `p`-adic integers is open. -/
theorem addSubgroup_isOpen_of_isClosed_of_ne_bot
    (p : ℕ) [hp : Fact p.Prime]
    (H : AddSubgroup ℤ_[p])
    (hclosed : IsClosed (H : Set ℤ_[p]))
    (hne : H ≠ ⊥) :
    IsOpen (H : Set ℤ_[p]) := by
  obtain ⟨⟨x, hxH⟩, hx⟩ :=
    AddSubgroup.ne_bot_iff_exists_ne_zero.mp hne
  have hx0 : x ≠ 0 := fun h ↦ hx (Subtype.ext h)
  have hmul (a : ℤ_[p]) : x * a ∈ H := by
    refine PadicInt.denseRange_intCast.induction_on a ?_ ?_
    · change IsClosed ((fun y : ℤ_[p] ↦ x * y) ⁻¹' (H : Set ℤ_[p]))
      exact hclosed.preimage (continuous_const.mul continuous_id)
    · intro z
      simpa only [zsmul_eq_mul, mul_comm] using H.zsmul_mem hxH z
  have hspan_le :
      (Ideal.span ({x} : Set ℤ_[p])).toAddSubgroup ≤ H := by
    intro y hy
    change y ∈ Ideal.span ({x} : Set ℤ_[p]) at hy
    rw [Ideal.mem_span_singleton] at hy
    obtain ⟨a, rfl⟩ := hy
    exact hmul a
  have hspan_ne :
      (Ideal.span ({x} : Set ℤ_[p]) : Ideal ℤ_[p]) ≠ ⊥ := by
    intro hzero
    have hxmem :
        x ∈ (Ideal.span ({x} : Set ℤ_[p]) : Ideal ℤ_[p]) :=
      Ideal.subset_span (by simp)
    rw [hzero] at hxmem
    exact hx0 (by simpa using hxmem)
  obtain ⟨n, hn⟩ := PadicInt.ideal_eq_span_pow_p hspan_ne
  have hpow_open :
      IsOpen
        ((Ideal.span ({(p : ℤ_[p]) ^ n} : Set ℤ_[p]) :
            Ideal ℤ_[p]) :
          Set ℤ_[p]) := by
    have hset :
        ((Ideal.span ({(p : ℤ_[p]) ^ n} : Set ℤ_[p]) :
            Ideal ℤ_[p]) :
          Set ℤ_[p]) =
          Metric.closedBall 0 ((p : ℝ) ^ (-n : ℤ)) := by
      ext y
      change y ∈
          (Ideal.span ({(p : ℤ_[p]) ^ n} : Set ℤ_[p]) :
            Ideal ℤ_[p]) ↔
        dist y 0 ≤ (p : ℝ) ^ (-n : ℤ)
      rw [dist_zero_right,
        PadicInt.norm_le_pow_iff_mem_span_pow]
    rw [hset]
    exact IsUltrametricDist.isOpen_closedBall
      (0 : ℤ_[p]) (by
        apply zpow_ne_zero
        exact_mod_cast hp.out.ne_zero)
  have hspan_open :
      IsOpen
        ((Ideal.span ({x} : Set ℤ_[p]) : Ideal ℤ_[p]) :
          Set ℤ_[p]) := by
    rw [hn]
    exact hpow_open
  exact AddSubgroup.isOpen_mono hspan_le hspan_open

/-- Every additive coset of an open subgroup of the `p`-adic integers
contains the cast of a positive natural number.

The positive natural numbers are dense because they are the translate
by one of the dense image of `ℕ` in `ℤ_[p]`. -/
theorem exists_positive_natCast_sub_mem_of_isOpen_addSubgroup
    (p : ℕ) [Fact p.Prime]
    (H : AddSubgroup ℤ_[p])
    (hopen : IsOpen (H : Set ℤ_[p]))
    (z : ℤ_[p]) :
    ∃ n : ℕ, 0 < n ∧ z - (n : ℤ_[p]) ∈ H := by
  have htranslate :
      Function.Surjective (fun y : ℤ_[p] ↦ y + 1) := by
    intro y
    exact ⟨y - 1, sub_add_cancel y 1⟩
  have hdense :
      DenseRange (fun n : ℕ ↦ (n : ℤ_[p]) + 1) := by
    exact
      htranslate.denseRange.comp
        PadicInt.denseRange_natCast
        (continuous_id.add continuous_const)
  let U : Set ℤ_[p] := {y | z - y ∈ H}
  have hUopen : IsOpen U := by
    exact hopen.preimage (continuous_const.sub continuous_id)
  have hUne : U.Nonempty := by
    refine ⟨z, ?_⟩
    change z - z ∈ H
    simpa only [sub_self] using H.zero_mem
  obtain ⟨n, hn⟩ := hdense.exists_mem_open hUopen hUne
  refine ⟨n + 1, Nat.zero_lt_succ n, ?_⟩
  simpa only [U, Set.mem_ofPred_eq, Nat.cast_add, Nat.cast_one] using hn

/-- A positive integral degree is nontrivial in the multiplicative
copy of the additive group of `ℤ_p`. -/
theorem multiplicative_positiveNatDegree_ne_one
    (p : ℕ) [Fact p.Prime]
    (n : ℕ) (hn : 0 < n) :
    (Multiplicative.ofAdd (1 : ℤ_[p])) ^ n ≠ 1 := by
  intro h
  have h' := congrArg Multiplicative.toAdd h
  change n • (1 : ℤ_[p]) = 0 at h'
  have hn0 : (n : ℤ_[p]) = 0 := by
    simpa only [nsmul_one] using h'
  have : n = 0 := by
    exact_mod_cast hn0
  exact (Nat.ne_of_gt hn) this

end PadicInt
