import SawinTotallyRealTowers.SixPrimeQuadraticCompositum
import SawinTotallyRealTowers.MultiquadraticAdjoin
import Mathlib.FieldTheory.IntermediateField.Adjoin.Defs
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Finset.Lattice.Fold

set_option autoImplicit false

/-!
# Degree of the initial multiquadratic layer

The concrete finite Galois compositum equals the field generated by its
five square roots. Independence of their rational square classes gives
its degree by the general finite-adjoin induction.
-/

namespace ClassFieldTower.Sawin

/-- The finite compositum is the intermediate field generated by the five
chosen roots in the fixed algebraic closure. -/
theorem sawinQuadraticCompositum_eq_adjoin_roots :
    sawinQuadraticCompositum.toIntermediateField =
      IntermediateField.adjoin ℚ
        (Set.range (fun i : Fin 5 ↦ quadraticClosureRoot (sawinQuadraticRadicand i : ℚ))) := by
  let M : IntermediateField ℚ (AlgebraicClosure ℚ) :=
    IntermediateField.adjoin ℚ
      (Set.range (fun i : Fin 5 ↦ quadraticClosureRoot (sawinQuadraticRadicand i : ℚ)))
  change sawinQuadraticCompositum.toIntermediateField = M
  apply le_antisymm
  · have hLayer : ∀ i : Fin 5, (sawinQuadraticLayer i).toIntermediateField ≤ M := by
      intro i
      apply IntermediateField.adjoin_simple_le_iff.mpr
      exact IntermediateField.subset_adjoin ℚ _ ⟨i, rfl⟩
    exact Finset.sup_induction
      (p := fun E : FiniteGaloisIntermediateField ℚ (AlgebraicClosure ℚ) ↦
        E.toIntermediateField ≤ M)
      bot_le
      (fun E hE F hF ↦
        (show E.toIntermediateField ⊔ F.toIntermediateField ≤ M from sup_le hE hF))
      (fun i _hi ↦ hLayer i)
  · apply IntermediateField.adjoin_le_iff.mpr
    rintro x ⟨i, rfl⟩
    apply sawinQuadraticLayer_le_compositum i
    exact IntermediateField.mem_adjoin_simple_self ℚ
      (quadraticClosureRoot (sawinQuadraticRadicand i : ℚ))

/-- The five independent square classes generate an extension of degree
thirty-two over the rationals. -/
theorem sawinQuadraticCompositum_finrank :
    Module.finrank ℚ sawinQuadraticCompositum = 32 := by
  rw [sawinQuadraticCompositum_eq_adjoin_roots]
  have h : Module.finrank ℚ (IntermediateField.adjoin ℚ
      ((fun i : Fin 5 ↦ quadraticClosureRoot (sawinQuadraticRadicand i : ℚ)) ''
        ((Finset.univ : Finset (Fin 5)) : Set (Fin 5)))) = 2 ^ (Finset.univ : Finset (Fin 5)).card :=
    (finrank_and_squareClasses_adjoin_independent_squareRoots
    ℚ (AlgebraicClosure ℚ)
    (fun i : Fin 5 ↦ (sawinQuadraticRadicand i : ℚ))
    (fun i : Fin 5 ↦ quadraticClosureRoot (sawinQuadraticRadicand i : ℚ))
    (by decide : (2 : ℚ) ≠ 0) Finset.univ
    (fun i _hi ↦ quadraticClosureRoot_sq (sawinQuadraticRadicand i : ℚ))
    (fun s _hs hNonempty ↦ sawinQuadraticRadicand_product_nonsquare s hNonempty)).1
  have hSet :
      (fun i : Fin 5 ↦ quadraticClosureRoot (sawinQuadraticRadicand i : ℚ)) ''
          ((Finset.univ : Finset (Fin 5)) : Set (Fin 5)) =
        Set.range (fun i : Fin 5 ↦ quadraticClosureRoot (sawinQuadraticRadicand i : ℚ)) := by
    rw [Finset.coe_univ, Set.image_univ]
  have hField := congrArg (IntermediateField.adjoin ℚ) hSet
  have hRank := congrArg (fun E : IntermediateField ℚ (AlgebraicClosure ℚ) ↦
    Module.finrank ℚ E) hField
  exact hRank.symm.trans (by
    simpa only [Finset.card_univ, Fintype.card_fin,
      show (2 : ℕ) ^ 5 = 32 by decide] using h)

end ClassFieldTower.Sawin
