import SawinTotallyRealTowers.AbsoluteRealKernelField
import SawinTotallyRealTowers.QuadraticClosure
import SawinTotallyRealTowers.QuadraticFieldDiscriminant
import SawinTotallyRealTowers.RamificationSupport
import SawinTotallyRealTowers.RationalRamificationSupport
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Local.FinitePlaceH2Localization
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Local.FinitePlaceUnramifiedH1
import SawinTotallyRealTowers.UnramifiedProPRelationRank.RelationRank.FinitePlaceAbsoluteInertiaKernel
import ClassFieldTheory.GlobalClassFieldTheory.Reciprocity.InfinitePlaceArtin
import ClassFieldTheory.AlgebraicNumberTheory.Completion.ExtensionIndex
import ClassFieldTheory.AlgebraicNumberTheory.Galois.CyclicPrimeSubextension
import ClassFieldTheory.AlgebraicNumberTheory.Idele.Cohomology.SPlaces.LocalBlocks
import ValuedFieldTheory.Ramification.HilbertRamification.Dedekind.CompositumUnramified
import Mathlib.Algebra.Algebra.Rat
import Mathlib.Algebra.Group.Even
import Mathlib.Data.Int.Basic
import Mathlib.Data.Nat.Prime.Defs
import Mathlib.Data.Nat.Squarefree
import Mathlib.Data.Rat.Cast.Order
import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.FieldTheory.Galois.Profinite
import Mathlib.FieldTheory.KrullTopology
import Mathlib.FieldTheory.Normal.Defs
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.NumberTheory.NumberField.Basic
import Mathlib.NumberTheory.NumberField.InfinitePlace.Embeddings
import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.NumberTheory.Padics.HeightOneSpectrum
import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.Tactic.NormNum
import Mathlib.Topology.Algebra.ContinuousMonoidHom
import Mathlib.Topology.Order

set_option autoImplicit false

/-!
# The quadratic character of negative three

Restriction to the actual field generated by a square root of negative three
gives a continuous character of the absolute Galois group of the rationals.
Its discriminant proves that it kills finite inertia away from three. Its
imaginary generator proves that its real Artin value is nontrivial. These
properties provide a sign correction without changing inertia away from three.
-/

open scoped NumberField
open NumberField IsDedekindDomain

noncomputable section

namespace ClassFieldTower.Sawin

open ClassFieldTower.Martinet.Shafarevich
open GlobalClassFieldTheory.Reciprocity AlgebraicNumberTheory.Valuations

-- Keep the canonical intermediate-field scalar structure generic until
-- restriction and its finite cyclic coordinate have both been constructed.
private def quadraticCharacterCoordinate (F : Type) [Field F]
    (E : FiniteGaloisIntermediateField F (AlgebraicClosure F))
    (hd : Module.finrank F E = 2) :
    Gal(E/F) ≃* Multiplicative (ZMod 2) := by
  apply mulEquivOfPrimeCardEq (p := 2)
  · exact (IsGalois.card_aut_eq_finrank F E).trans hd
  · change Nat.card (ZMod 2) = 2
    exact Nat.card_zmod 2

private def quadraticAbsoluteCharacter (F : Type) [Field F]
    (E : FiniteGaloisIntermediateField F (AlgebraicClosure F))
    (hd : Module.finrank F E = 2) :
    Field.absoluteGaloisGroup F →ₜ* Multiplicative (ZMod 2) := by
  let e := quadraticCharacterCoordinate F E hd
  let r : Field.absoluteGaloisGroup F →ₜ* Gal(E/F) :=
    { toMonoidHom := AlgEquiv.restrictNormalHom (F := F) (K₁ := AlgebraicClosure F) E.toIntermediateField
      continuous_toFun := InfiniteGalois.restrictNormalHom_continuous E.toIntermediateField }
  have he : Continuous e := continuous_of_discreteTopology
  exact
    { toMonoidHom := e.toMonoidHom.comp r.toMonoidHom
      continuous_toFun := he.comp r.continuous_toFun }

private theorem quadraticAbsoluteCharacter_eq_one_iff (F : Type) [Field F]
    (E : FiniteGaloisIntermediateField F (AlgebraicClosure F))
    (hd : Module.finrank F E = 2) (σ : Field.absoluteGaloisGroup F) :
    quadraticAbsoluteCharacter F E hd σ = 1 ↔ AlgEquiv.restrictNormalHom (F := F) (K₁ := AlgebraicClosure F) E.toIntermediateField σ = 1 := by
  change quadraticCharacterCoordinate F E hd (AlgEquiv.restrictNormalHom (F := F) (K₁ := AlgebraicClosure F) E.toIntermediateField σ) = 1 ↔ _
  exact (quadraticCharacterCoordinate F E hd).map_eq_one_iff

private theorem quadraticAbsoluteCharacter_inertia
    (F : Type) [Field F] [NumberField F]
    (E : FiniteGaloisIntermediateField F (AlgebraicClosure F)) [NumberField E]
    (hd : Module.finrank F E = 2) (T : Set (HeightOneSpectrum (𝓞 F)))
    (hUnramified : IsUnramifiedAtFinitePlacesOutside F E T)
    (v : HeightOneSpectrum (𝓞 F)) (hv : v ∉ T)
    (σ : finitePlaceAbsoluteInertiaSubgroup F v) :
    quadraticAbsoluteCharacter F E hd
      (finitePlaceAbsoluteDecompositionInclusion F v
        (finitePlaceAbsoluteInertiaInclusion F v σ)) = 1 := by
  apply (quadraticAbsoluteCharacter_eq_one_iff F E hd _).mpr
  let w := restrictAbsoluteValueExtensionToIntermediate
    (HeightOneSpectrum.adicAbv F v) (finitePlaceAbsoluteValueExtension F v)
      E.toIntermediateField
  let P := finitePlaceExtensionCentre (K := F) (L := E) v w
  have hP : Algebra.IsUnramifiedAt (𝓞 F) P.asIdeal := by
    apply hUnramified P
    rw [finitePlaceBelow_finitePlaceExtensionCentre v w]
    exact hv
  have hmem : (σ.1.1 : Gal(AlgebraicClosure F/F)).restrictNormal E ∈
      HilbertRamification.Dedekind.inertiaGroup P.asIdeal Gal(E/F) :=
    finitePlaceAbsoluteInertia_restrictNormal_mem_finiteInertia F E.toIntermediateField v σ
  have hbot : HilbertRamification.Dedekind.inertiaGroup P.asIdeal Gal(E/F) = ⊥ :=
    HilbertRamification.Dedekind.inertiaGroup_eq_bot_of_isUnramifiedAt P.asIdeal hP
  have hRestricted : (σ.1.1 : Gal(AlgebraicClosure F/F)).restrictNormal E = 1 := by
    simpa only [hbot, Subgroup.mem_bot] using hmem
  rw [finitePlaceAbsoluteInertiaInclusion_apply, finitePlaceAbsoluteDecompositionInclusion_apply]
  change (σ.1.1 : Gal(AlgebraicClosure F/F)).restrictNormal E.toIntermediateField = 1
  exact hRestricted

private theorem quadraticAbsoluteCharacter_infinite
    (F : Type) [Field F] [CharZero F] [IsTotallyReal F]
    (E : FiniteGaloisIntermediateField F (AlgebraicClosure F))
    (hd : Module.finrank F E = 2)
    (hNoReal : ∀ φ : E →+* ℂ, ¬ ComplexEmbedding.IsReal φ)
    (v : InfinitePlace F) :
    quadraticAbsoluteCharacter F E hd (absoluteInfinitePlaceArtinNegOne F v) ≠ 1 := by
  intro h
  let c : Gal(AlgebraicClosure F/F) :=
    chosenInfinitePlaceArtinMonoidHom (K := F) (L := AlgebraicClosure F)
      v (-1 : v.Completionˣ)
  have hRestrict : AlgEquiv.restrictNormalHom
      (F := F) (K₁ := AlgebraicClosure F) E.toIntermediateField c = 1 :=
    (quadraticAbsoluteCharacter_eq_one_iff F E hd
      (absoluteInfinitePlaceArtinNegOne F v)).mp h
  let w : InfinitePlace (AlgebraicClosure F) :=
    chosenInfinitePlaceAbove (L := AlgebraicClosure F) v
  let φ : E →+* ℂ := w.embedding.comp (algebraMap E (AlgebraicClosure F))
  have hwComplex : w.IsComplex := by
    apply InfinitePlace.not_isReal_iff_isComplex.mp
    intro hw
    exact hNoReal φ ((InfinitePlace.isReal_iff.mp hw).comp
      (algebraMap E (AlgebraicClosure F)))
  have hwRamified : w.IsRamified F :=
    InfinitePlace.isRamified_iff.mpr ⟨hwComplex,
      IsTotallyReal.isReal (w.comap (algebraMap F (AlgebraicClosure F)))⟩
  have hConj : ComplexEmbedding.IsConj w.embedding c :=
    chosenInfinitePlaceArtinMonoidHom_neg_one_isConj_of_ramified
      (K := F) (L := AlgebraicClosure F) v hwRamified
  apply hNoReal φ
  apply ComplexEmbedding.isReal_iff.mpr
  ext x
  change star (w.embedding (algebraMap E (AlgebraicClosure F) x)) =
    w.embedding (algebraMap E (AlgebraicClosure F) x)
  rw [← hConj.eq]
  have hFixed := AlgEquiv.restrictNormal_commutes c E x
  change algebraMap E (AlgebraicClosure F)
      ((AlgEquiv.restrictNormalHom (F := F) (K₁ := AlgebraicClosure F)
        E.toIntermediateField c) x) =
    c (algebraMap E (AlgebraicClosure F) x) at hFixed
  rw [hRestrict] at hFixed
  exact congrArg w.embedding hFixed.symm

private theorem negativeThree_nonsquare : ¬ IsSquare (-3 : ℚ) := by
  intro h
  have hNonneg := h.nonneg
  norm_num at hNonneg

private abbrev negativeThreeField : FiniteGaloisIntermediateField ℚ (AlgebraicClosure ℚ) :=
  quadraticClosure (-3 : ℚ) negativeThree_nonsquare

/-- The continuous quadratic character cut out by the actual field ℚ(√−3). -/
def negativeThreeCharacter : Field.absoluteGaloisGroup ℚ →ₜ* Multiplicative (ZMod 2) :=
  quadraticAbsoluteCharacter ℚ negativeThreeField
    (quadraticClosure_finrank (-3 : ℚ) negativeThree_nonsquare)

/-- The character of negative three kills absolute inertia at every finite
place other than the rational prime three, including the prime two. -/
theorem negativeThreeCharacter_inertia
    (v : HeightOneSpectrum (𝓞 ℚ))
    (hv : v ≠ (Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes))
    (σ : finitePlaceAbsoluteInertiaSubgroup ℚ v) :
    negativeThreeCharacter
      (finitePlaceAbsoluteDecompositionInclusion ℚ v
        (finitePlaceAbsoluteInertiaInclusion ℚ v σ)) = 1 := by
  let E := negativeThreeField
  let : NumberField E := NumberField.of_module_finite ℚ E
  let : Algebra.IsQuadraticExtension ℚ E :=
    quadraticClosure_isQuadraticExtension (-3 : ℚ) negativeThree_nonsquare
  let T : Set (HeightOneSpectrum (𝓞 ℚ)) :=
    {(Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes)}
  have hDiscr : NumberField.discr E = -3 :=
    numberField_discr_of_mod_four_eq_one E (-3) (by
      change Squarefree 3
      exact Nat.prime_three.squarefree)
      (quadraticClosureGenerator (-3 : ℚ) negativeThree_nonsquare)
      (quadraticClosureGenerator_sq (-3 : ℚ) negativeThree_nonsquare)
      (quadraticClosureGenerator_adjoin (-3 : ℚ) negativeThree_nonsquare) (by norm_num)
  have hUnramified : IsUnramifiedAtFinitePlacesOutside ℚ E T := by
    apply (isUnramifiedAtFinitePlacesOutside_rat_iff_discr E T).mpr
    intro q hq
    rw [hDiscr] at hq
    have hqInt : (q : ℤ) ∣ (3 : ℤ) := (dvd_neg).mp hq
    have hqNat : (q : ℕ) ∣ 3 := Int.natCast_dvd_natCast.mp hqInt
    have hqEq : q = (⟨3, Nat.prime_three⟩ : Nat.Primes) := by
      apply Subtype.ext
      exact (Nat.prime_dvd_prime_iff_eq q.property Nat.prime_three).mp hqNat
    exact Set.mem_singleton_iff.mpr (congrArg
      (Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm hqEq)
  exact quadraticAbsoluteCharacter_inertia ℚ E
    (quadraticClosure_finrank (-3 : ℚ) negativeThree_nonsquare) T hUnramified v hv σ

/-- Its value on the actual real Artin element of negative one is nontrivial. -/
theorem negativeThreeCharacter_infinite (v : InfinitePlace ℚ) :
    negativeThreeCharacter (absoluteInfinitePlaceArtinNegOne ℚ v) ≠ 1 := by
  let E := negativeThreeField
  apply quadraticAbsoluteCharacter_infinite ℚ E
    (quadraticClosure_finrank (-3 : ℚ) negativeThree_nonsquare)
  intro φ hReal
  let ρ : E →+* ℝ := hReal.embedding
  let β : E := quadraticClosureGenerator (-3 : ℚ) negativeThree_nonsquare
  have hSquare : ρ β ^ 2 = (-3 : ℝ) := by
    calc
      ρ β ^ 2 = ρ (β ^ 2) := (map_pow ρ β 2).symm
      _ = ρ (algebraMap ℚ E (-3 : ℚ)) :=
        congrArg ρ (quadraticClosureGenerator_sq (-3 : ℚ) negativeThree_nonsquare)
      _ = (-3 : ℝ) := by rw [RingHom.map_rat_algebraMap]; norm_num
  have hNonneg := sq_nonneg (ρ β)
  rw [hSquare] at hNonneg
  norm_num at hNonneg

end ClassFieldTower.Sawin
