/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import Mathlib.Algebra.Group.Even
import Mathlib.Algebra.Polynomial.Monic
import Mathlib.Algebra.Polynomial.Degree.Operations
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.FieldTheory.Galois.GaloisClosure
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.FieldTheory.KummerPolynomial
import Mathlib.FieldTheory.Minpoly.Field
import Mathlib.RingTheory.PowerBasis

set_option autoImplicit false

/-!
# Quadratic fields inside the algebraic closure of ℚ

A chosen square root of a nonsquare rational number generates an actual
finite Galois intermediate field of degree two. Its internal generator,
square relation, and generation theorem let later arithmetic constructions
supply reality and ramification conditions without assuming an extension.
-/

open Polynomial

namespace ClassFieldTower.Sawin

/-- A square root of a rational number in the fixed algebraic closure. -/
noncomputable def quadraticClosureRoot (d : ℚ) : AlgebraicClosure ℚ :=
  Classical.choose (IsAlgClosed.exists_pow_nat_eq
    (algebraMap ℚ (AlgebraicClosure ℚ) d) (by decide : 0 < 2))

/-- The chosen element has the prescribed square. -/
theorem quadraticClosureRoot_sq (d : ℚ) :
    quadraticClosureRoot d ^ 2 = algebraMap ℚ (AlgebraicClosure ℚ) d :=
  Classical.choose_spec (IsAlgClosed.exists_pow_nat_eq
    (algebraMap ℚ (AlgebraicClosure ℚ) d) (by decide : 0 < 2))

private theorem quadraticClosureRoot_isIntegral (d : ℚ) :
    IsIntegral ℚ (quadraticClosureRoot d) := by
  refine ⟨X ^ 2 - C d, monic_X_pow_sub_C d (by decide : (2 : ℕ) ≠ 0), ?_⟩
  rw [eval₂_sub, eval₂_pow, eval₂_X, eval₂_C, quadraticClosureRoot_sq, sub_self]

/-- Nonsquareness identifies the minimal polynomial of the chosen root. -/
theorem minpoly_quadraticClosureRoot (d : ℚ) (hd : ¬ IsSquare d) :
    minpoly ℚ (quadraticClosureRoot d) = X ^ 2 - C d := by
  apply Eq.symm
  apply minpoly.eq_of_irreducible_of_monic
  · apply X_pow_sub_C_irreducible_of_prime Nat.prime_two
    intro b hb
    exact hd ((isSquare_iff_exists_sq d).mpr ⟨b, hb.symm⟩)
  · rw [map_sub, map_pow, aeval_X, aeval_C, quadraticClosureRoot_sq, sub_self]
  · exact monic_X_pow_sub_C d (by decide : (2 : ℕ) ≠ 0)

private theorem finrank_adjoin_quadraticClosureRoot (d : ℚ) (hd : ¬ IsSquare d) :
    Module.finrank ℚ
      (IntermediateField.adjoin ℚ ({quadraticClosureRoot d} : Set (AlgebraicClosure ℚ))) = 2 := by
  rw [IntermediateField.adjoin.finrank (quadraticClosureRoot_isIntegral d),
    minpoly_quadraticClosureRoot d hd, natDegree_X_pow_sub_C]

/-- The quadratic Galois subfield of the fixed algebraic closure obtained
by adjoining a square root of a nonsquare rational number. -/
noncomputable def quadraticClosure (d : ℚ) (hd : ¬ IsSquare d) :
    FiniteGaloisIntermediateField ℚ (AlgebraicClosure ℚ) where
  toIntermediateField := IntermediateField.adjoin ℚ {quadraticClosureRoot d}
  finiteDimensional := IntermediateField.adjoin.finiteDimensional
    (quadraticClosureRoot_isIntegral d)
  isGalois := by
    let : Algebra.IsQuadraticExtension ℚ
        (IntermediateField.adjoin ℚ ({quadraticClosureRoot d} : Set (AlgebraicClosure ℚ))) :=
      { finrank_eq_two' := finrank_adjoin_quadraticClosureRoot d hd }
    exact Algebra.IsQuadraticExtension.isGalois ℚ
      (IntermediateField.adjoin ℚ ({quadraticClosureRoot d} : Set (AlgebraicClosure ℚ)))

/-- The underlying intermediate field is the field generated by the chosen root. -/
theorem quadraticClosure_toIntermediateField (d : ℚ) (hd : ¬ IsSquare d) :
    (quadraticClosure d hd).toIntermediateField =
      IntermediateField.adjoin ℚ ({quadraticClosureRoot d} : Set (AlgebraicClosure ℚ)) := rfl

/-- The constructed field has degree two over ℚ. -/
theorem quadraticClosure_finrank (d : ℚ) (hd : ¬ IsSquare d) :
    Module.finrank ℚ (quadraticClosure d hd) = 2 :=
  finrank_adjoin_quadraticClosureRoot d hd

/-- The constructed field is a quadratic extension, for use at arithmetic
boundaries requiring Mathlib's quadratic-extension class. -/
theorem quadraticClosure_isQuadraticExtension (d : ℚ) (hd : ¬ IsSquare d) :
    Algebra.IsQuadraticExtension ℚ (quadraticClosure d hd) where
  finrank_eq_two' := quadraticClosure_finrank d hd

/-- The chosen square root viewed inside its quadratic field. -/
noncomputable def quadraticClosureGenerator (d : ℚ) (hd : ¬ IsSquare d) :
    quadraticClosure d hd :=
  IntermediateField.AdjoinSimple.gen ℚ (quadraticClosureRoot d)

/-- The internal generator satisfies the same square equation. -/
theorem quadraticClosureGenerator_sq (d : ℚ) (hd : ¬ IsSquare d) :
    quadraticClosureGenerator d hd ^ 2 = algebraMap ℚ (quadraticClosure d hd) d := by
  apply (algebraMap (quadraticClosure d hd) (AlgebraicClosure ℚ)).injective
  rw [map_pow, ← IsScalarTower.algebraMap_apply ℚ (quadraticClosure d hd) (AlgebraicClosure ℚ)]
  change quadraticClosureRoot d ^ 2 = algebraMap ℚ (AlgebraicClosure ℚ) d
  exact quadraticClosureRoot_sq d

/-- The internal square root generates the whole constructed field. -/
theorem quadraticClosureGenerator_adjoin (d : ℚ) (hd : ¬ IsSquare d) :
    IntermediateField.adjoin ℚ
      ({quadraticClosureGenerator d hd} : Set (quadraticClosure d hd)) = ⊤ := by
  apply IntermediateField.adjoin_eq_top_of_algebra
  have h := (IntermediateField.adjoin.powerBasis
    (quadraticClosureRoot_isIntegral d)).adjoin_gen_eq_top
  rw [IntermediateField.adjoin.powerBasis_gen] at h
  exact h

end ClassFieldTower.Sawin
