import Mathlib.Algebra.Group.Even
import Mathlib.FieldTheory.KummerExtension
import Mathlib.FieldTheory.KummerPolynomial

set_option autoImplicit false

/-!
# A nonsquare rational generator for a quadratic extension

The nontrivial square root of unity in ℚ makes every quadratic extension
a Kummer extension. The resulting generator has irreducible polynomial
`X ^ 2 - C d`, which forces its rational square `d` to be nonzero and
nonsquare. No ramification or reality assumption is involved.
-/

universe u

namespace ClassFieldTower.Sawin

/-- Every quadratic extension of ℚ is generated by a square root of a
nonzero nonsquare rational number. -/
theorem exists_nonsquare_rat_generator_of_isQuadraticExtension
    (L : Type u) [Field L] [Algebra ℚ L]
    [Algebra.IsQuadraticExtension ℚ L] :
    ∃ (d : ℚ) (α : L), α ^ 2 = algebraMap ℚ L d ∧
      IntermediateField.adjoin ℚ ({α} : Set L) = ⊤ ∧
      ¬ IsSquare d ∧ d ≠ 0 := by
  have hroots : (primitiveRoots (Module.finrank ℚ L) ℚ).Nonempty := by
    rw [Algebra.IsQuadraticExtension.finrank_eq_two ℚ L]
    refine ⟨-1, (mem_primitiveRoots (by decide : 0 < 2)).mpr ?_⟩
    exact IsPrimitiveRoot.neg_one 0 (by decide)
  obtain ⟨α, ⟨d, hd⟩, hα⟩ :=
    exists_root_adjoin_eq_top_of_isCyclic ℚ L hroots
  have hαsq : α ^ 2 = algebraMap ℚ L d := by
    simpa only [Algebra.IsQuadraticExtension.finrank_eq_two ℚ L] using hd.symm
  have hirred : Irreducible (Polynomial.X ^ 2 - Polynomial.C d) := by
    simpa only [Algebra.IsQuadraticExtension.finrank_eq_two ℚ L] using
      (irreducible_X_pow_sub_C_of_root_adjoin_eq_top hd.symm hα)
  refine ⟨d, α, hαsq, hα, ?_, ?_⟩
  · intro hsq
    obtain ⟨r, hr⟩ := hsq.exists_sq
    exact (pow_ne_of_irreducible_X_pow_sub_C hirred
      (dvd_refl 2) (by decide : (2 : ℕ) ≠ 1) r) hr.symm
  · exact ne_zero_of_irreducible_X_pow_sub_C'
      (by decide : (2 : ℕ) ≠ 1) hirred

end ClassFieldTower.Sawin
