/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.Group.Even
import Mathlib.Data.Fin.SuccPred
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.LinearAlgebra.Basis.Defs
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.RingTheory.Adjoin.PowerBasis
import Mathlib.RingTheory.PowerBasis
import Mathlib.Tactic.LinearCombination

set_option autoImplicit false

/-!
# Square classes that become squares in a quadratic extension

In a quadratic extension generated by a square root of `a`, an element
of the base field becomes a square precisely when its square class is
trivial or that of `a`. The basis `1, α` makes the cross coefficient of
a square explicit. In characteristic different from two, that coefficient
vanishes only when one of the two coordinates vanishes.
-/

universe u v

namespace ClassFieldTower.Sawin

/-- A quadratic extension generated by a square root kills exactly the
trivial square class and the square class of its radicand. -/
theorem isSquare_algebraMap_iff_of_quadraticGenerator
    (F : Type u) (E : Type v) [Field F] [Field E] [Algebra F E]
    [Algebra.IsQuadraticExtension F E] (hTwo : (2 : F) ≠ 0)
    (a b : F) (α : E) (hSquare : α ^ 2 = algebraMap F E a)
    (hGenerate : IntermediateField.adjoin F ({α} : Set E) = ⊤) :
    IsSquare (algebraMap F E b) ↔ IsSquare b ∨ ∃ q : F, b = a * q ^ 2 := by
  constructor
  · intro hSquareB
    let pb : PowerBasis F E := PowerBasis.ofAdjoinEqTop
      (IsIntegral.of_finite F α)
      ((IntermediateField.adjoin_simple_eq_top_iff_of_isAlgebraic
        (IsAlgebraic.of_finite F α)).mp hGenerate)
    let B : Module.Basis (Fin 2) F E := pb.basis.reindex
      (finCongr (pb.finrank.symm.trans (Algebra.IsQuadraticExtension.finrank_eq_two F E)))
    have hB (i : Fin 2) : B i = α ^ (i : ℕ) := by
      dsimp only [B]
      rw [Module.Basis.reindex_apply, PowerBasis.basis_eq_pow,
        finCongr_symm_apply_coe]
      rw [show pb.gen = α from PowerBasis.ofAdjoinEqTop_gen _ _]
    have hB0 : B 0 = 1 := by rw [hB, Fin.val_zero, pow_zero]
    have hB1 : B 1 = α := by rw [hB, Fin.val_one, pow_one]
    obtain ⟨β, hβ⟩ := hSquareB.exists_sq
    let x : F := B.repr β 0
    let y : F := B.repr β 1
    have hCoordinates : β = algebraMap F E x + algebraMap F E y * α := by
      simpa only [Fin.sum_univ_two, hB0, hB1, Algebra.smul_def, mul_one] using
        (B.sum_repr β).symm
    have hLinearField : algebraMap F E (x ^ 2 + a * y ^ 2 - b) +
        algebraMap F E (2 * x * y) * α = 0 := by
      have hSquareβ : (algebraMap F E x + algebraMap F E y * α) ^ 2 =
          algebraMap F E b := by rw [← hCoordinates, ← hβ]
      simp only [map_sub, map_add, map_mul, map_pow, map_ofNat]
      linear_combination hSquareβ - algebraMap F E y ^ 2 * hSquare
    have hLinear : (x ^ 2 + a * y ^ 2 - b) • B 0 + (2 * x * y) • B 1 = 0 := by
      simpa only [hB0, hB1, Algebra.smul_def, mul_one] using hLinearField
    have hCross := congrArg (fun z : E ↦ B.repr z 1) hLinear
    simp only [map_add, map_smul, map_zero, Finsupp.add_apply, Finsupp.smul_apply,
      Module.Basis.repr_self_apply, zero_ne_one, ↓reduceIte, eq_self,
      smul_eq_mul, mul_zero, mul_one, zero_add, Finsupp.zero_apply] at hCross
    have hxy : x * y = 0 :=
      (mul_eq_zero.mp (show (2 : F) * (x * y) = 0 by
        simpa only [mul_assoc] using hCross)).resolve_left hTwo
    rcases mul_eq_zero.mp hxy with hx | hy
    · right
      refine ⟨y, (algebraMap F E).injective ?_⟩
      rw [hβ, hCoordinates, hx, map_zero, zero_add, map_mul, map_pow, mul_pow, hSquare]
      exact mul_comm (algebraMap F E y ^ 2) (algebraMap F E a)
    · left
      apply (isSquare_iff_exists_sq b).mpr
      refine ⟨x, (algebraMap F E).injective ?_⟩
      rw [hβ, hCoordinates, hy, map_zero, zero_mul, add_zero, map_pow]
  · rintro (hBase | ⟨q, hClass⟩)
    · obtain ⟨q, hq⟩ := hBase.exists_sq
      apply (isSquare_iff_exists_sq (algebraMap F E b)).mpr
      exact ⟨algebraMap F E q, by rw [hq, map_pow]⟩
    · apply (isSquare_iff_exists_sq (algebraMap F E b)).mpr
      refine ⟨α * algebraMap F E q, ?_⟩
      rw [hClass, map_mul, map_pow, mul_pow, hSquare]

end ClassFieldTower.Sawin
