import Mathlib.Algebra.Algebra.Rat
import Mathlib.Algebra.Ring.Commute
import Mathlib.Analysis.Real.Sqrt
import Mathlib.Data.Rat.Cast.Order
import Mathlib.FieldTheory.IntermediateField.Adjoin.Defs
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex

set_option autoImplicit false

/-!
# Reality of an extension generated by a rational square root

A square root of a nonnegative rational number has real image under every
complex embedding. If it generates the extension, conjugation fixes the
whole image. Conversely, a rational number that is a square in a totally
real number field must be nonnegative.
-/

open scoped ComplexConjugate
open NumberField

universe u

namespace ClassFieldTower.Sawin

/-- An extension of ℚ generated by a square root of a nonnegative rational
number is totally real. No degree or nonsquare hypothesis is needed. -/
theorem isTotallyReal_of_sq_nonneg_adjoin
    (L : Type u) [Field L] [Algebra ℚ L] {d : ℚ} {α : L}
    (hα : α ^ 2 = algebraMap ℚ L d)
    (hgen : IntermediateField.adjoin ℚ ({α} : Set L) = ⊤)
    (hd : 0 ≤ d) : IsTotallyReal L := by
  refine ⟨fun w ↦ ?_⟩
  apply InfinitePlace.isReal_iff.mpr
  apply ComplexEmbedding.isReal_iff.mpr
  let φ : L →+* ℂ := w.embedding
  have hφsq : φ α ^ 2 = (d : ℂ) := by
    calc
      φ α ^ 2 = φ (α ^ 2) := (map_pow φ α 2).symm
      _ = φ (algebraMap ℚ L d) := congrArg φ hα
      _ = (d : ℂ) := φ.map_rat_algebraMap d
  have hsqrt : (Real.sqrt (d : ℝ) : ℂ) ^ 2 = (d : ℂ) := by
    rw [← Complex.ofReal_pow, Real.sq_sqrt (Rat.cast_nonneg.mpr hd),
      Complex.ofReal_ratCast]
  have hαreal : (ComplexEmbedding.conjugate φ) α = φ α := by
    change conj (φ α) = φ α
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp (hφsq.trans hsqrt.symm) with h | h
    · rw [h, Complex.conj_ofReal]
    · rw [h, map_neg, Complex.conj_ofReal]
  change ComplexEmbedding.conjugate φ = φ
  apply RingHom.ext
  intro x
  have hx : x ∈ IntermediateField.adjoin ℚ ({α} : Set L) := by
    rw [hgen]
    exact IntermediateField.mem_top
  refine IntermediateField.adjoin_induction ℚ
    (p := fun y _ ↦ (ComplexEmbedding.conjugate φ) y = φ y)
    ?_ ?_ ?_ ?_ ?_ hx
  · intro y hy
    obtain rfl := Set.mem_singleton_iff.mp hy
    exact hαreal
  · intro q
    rw [RingHom.map_rat_algebraMap, RingHom.map_rat_algebraMap]
  · intro y z _ _ hy hz
    rw [map_add, map_add, hy, hz]
  · intro y _ hy
    rw [map_inv₀, map_inv₀, hy]
  · intro y z _ _ hy hz
    rw [map_mul, map_mul, hy, hz]

/-- A rational number that is a square in a totally real number field is
nonnegative. This direction does not require a generating element. -/
theorem rat_nonneg_of_sq_of_isTotallyReal
    (L : Type u) [Field L] [NumberField L] [IsTotallyReal L]
    {d : ℚ} {α : L} (hα : α ^ 2 = algebraMap ℚ L d) : 0 ≤ d := by
  let φ : L →+* ℂ := Classical.choice inferInstance
  let ρ : L →+* ℝ := (IsTotallyReal.complexEmbedding_isReal φ).embedding
  have hρ : ρ α ^ 2 = (d : ℝ) := by
    calc
      ρ α ^ 2 = ρ (α ^ 2) := (map_pow ρ α 2).symm
      _ = ρ (algebraMap ℚ L d) := congrArg ρ hα
      _ = (d : ℝ) := ρ.map_rat_algebraMap d
  have hdReal : 0 ≤ (d : ℝ) := by
    rw [← hρ]
    exact sq_nonneg (ρ α)
  exact Rat.cast_nonneg.mp hdReal

end ClassFieldTower.Sawin
