import SawinTotallyRealTowers.RealProPFrobenius
import SawinTotallyRealTowers.MaximalRealProPGroup
import ProCGroups.Presentations.Profinite
import ProCGroups.Topologies.ContinuousMonoidHom

set_option autoImplicit false

/-!
# Killing a countable family of actual Frobenius elements

The closed normal subgroup generated by the chosen arithmetic Frobenii
has a Hausdorff group quotient. At primes outside the allowed ramification
support, its projection kills the whole absolute decomposition group.
-/

open NumberField IsDedekindDomain
open scoped NumberField
noncomputable section

namespace ClassFieldTower.Sawin

open ProCGroups.Presentations
open ClassFieldTower.Martinet.Shafarevich

variable (p : ℕ) (T : Set (HeightOneSpectrum (𝓞 ℚ)))
variable (v : ℕ → HeightOneSpectrum (𝓞 ℚ))

/-- The closed normal subgroup generated by actual arithmetic Frobenii. -/
abbrev realProPFrobeniusCutKernel :
    Subgroup (maximalRealProPOutside p T ≃ₐ[ℚ] maximalRealProPOutside p T) :=
  closedNormalClosure (Set.range (fun n ↦ maximalRealProPArithmeticFrobenius p T (v n)))

/-- The actual maximal real group after the selected Frobenii are killed. -/
abbrev RealProPFrobeniusCut :=
  (maximalRealProPOutside p T ≃ₐ[ℚ] maximalRealProPOutside p T) ⧸
    realProPFrobeniusCutKernel p T v

/-- The continuous projection to the actual Frobenius quotient. -/
def realProPFrobeniusCutProjection :
    (maximalRealProPOutside p T ≃ₐ[ℚ] maximalRealProPOutside p T) →ₜ*
      RealProPFrobeniusCut p T v :=
  ProCGroups.ContinuousMonoidHom.quotientMk (realProPFrobeniusCutKernel p T v)

/-- Every selected arithmetic Frobenius is killed by the quotient projection. -/
theorem realProPFrobeniusCutProjection_frobenius (n : ℕ) :
    realProPFrobeniusCutProjection p T v
      (maximalRealProPArithmeticFrobenius p T (v n)) = 1 := by
  exact (QuotientGroup.eq_one_iff _).2
    (subset_closedNormalClosure _ ⟨n, rfl⟩)

/-- At a selected prime outside T the entire actual decomposition image is killed. -/
theorem realProPFrobeniusCutProjection_decomposition (n : ℕ) (hv : v n ∉ T)
    (sigma : finitePlaceAbsoluteDecompositionGroup ℚ (v n)) :
    realProPFrobeniusCutProjection p T v
      (maximalRealProPDecompositionMap p T (v n) sigma) = 1 := by
  let : IsClosed ((realProPFrobeniusCutKernel p T v) :
      Set (maximalRealProPOutside p T ≃ₐ[ℚ] maximalRealProPOutside p T)) :=
    closedNormalClosure_isClosed _
  exact maximalRealProPDecomposition_killed_of_frobenius p T (v n) hv
    (realProPFrobeniusCutProjection p T v)
    (realProPFrobeniusCutProjection_frobenius p T v n) sigma

/-- The actual Frobenius quotient is the image of its arithmetic parent group. -/
theorem realProPFrobeniusCutProjection_surjective :
    Function.Surjective (realProPFrobeniusCutProjection p T v) :=
  QuotientGroup.mk'_surjective _

end ClassFieldTower.Sawin
