import ValuedFieldTheory.Ramification.HilbertRamification.FixedFieldValuationRing
import ValuedFieldTheory.Ramification.HilbertRamification.RealLowerGroups
import ValuedFieldTheory.Valuation.LocalRingEquiv
import ValuedFieldTheory.Valuation.DiscreteValuationField.AddVal

set_option autoImplicit false

/-!
# Canonical ramification numbers on an actual fixed field

For `M = L ^ H`, this file works with the literal restricted valuation ring
`O_M = O_L ∩ M`.  The ramification number of an actual element of
`Gal(M/K)` is the value of the principal ideal generated by all of its
integral displacements.  Thus the public definition is independent of a
monogenic generator.
-/

noncomputable section

universe u v w x

namespace RamificationTheory.HilbertRamification
namespace Higher


variable {K : Type u} {L : Type w} [Field K] [Field L] [Algebra K L]
variable {base : ValuationTheory.DiscreteValuationField.DVF.{u, v} K}
variable {target : ValuationTheory.DiscreteValuationField.DVF.{w, x} L}
variable [base.valuation.HasExtension target.valuation]
variable [FiniteDimensional K L] [IsGalois K L]

/-- The displacement ideal in the literal restricted valuation ring of the
actual fixed field. -/
def fixedFieldDisplacementIdealDVF
    (huniq :
      RamificationTheory.DiscreteValuationField.DVF.HasUniqueValuationExtension.{u, v, w, x, x}
        base target)
    (H : Subgroup Gal(L/K)) [H.Normal]
    (q : Gal((fixedFieldDVF (K := K) H)/K)) :
    Ideal (fixedFieldValuationSubringDVF (K := K) (target := target) H) :=
  Ideal.span
    {d | ∃ a : fixedFieldValuationSubringDVF
        (K := K) (target := target) H,
      d = fixedFieldValuationSubringAutDVF
          (base := base) (target := target) huniq H q a - a}

/-- The canonical fixed-field ramification number.  Since the restricted
valuation ring is a DVR, its displacement ideal is principal; the additive
value of an ideal generator is independent of the chosen generator. -/
def fixedFieldRamificationNumber
    (huniq :
      RamificationTheory.DiscreteValuationField.DVF.HasUniqueValuationExtension.{u, v, w, x, x}
        base target)
    (H : Subgroup Gal(L/K)) [H.Normal]
    (q : Gal((fixedFieldDVF (K := K) H)/K)) : ℕ∞ := by
  let B := fixedFieldValuationSubringDVF (K := K) (target := target) H
  letI : IsDiscreteValuationRing B :=
    fixedFieldValuationSubringDVF_isDiscreteValuationRing
      (base := base) (target := target) huniq H
  exact IsDiscreteValuationRing.addVal B
    (Submodule.IsPrincipal.generator
      (fixedFieldDisplacementIdealDVF
        (base := base) (target := target) huniq H q))

/-- The real-index ideal on the actual restricted valuation ring. -/
def fixedFieldRamificationIdealDVF
    (H : Subgroup Gal(L/K)) (s : ℝ) :
    Ideal (fixedFieldValuationSubringDVF (K := K) (target := target) H) :=
  IsLocalRing.maximalIdeal
      (fixedFieldValuationSubringDVF (K := K) (target := target) H) ^
    realRamificationExponent s

/-- The real lower ramification group of the actual Galois extension
`(L ^ H)/K`, formed using the literal restricted valuation ring. -/
def fixedFieldLowerRamificationGroup
    (huniq :
      RamificationTheory.DiscreteValuationField.DVF.HasUniqueValuationExtension.{u, v, w, x, x}
        base target)
    (H : Subgroup Gal(L/K)) [H.Normal]
    (s : ℝ) : Subgroup Gal((fixedFieldDVF (K := K) H)/K) where
  carrier :=
    {q | ∀ a : fixedFieldValuationSubringDVF
        (K := K) (target := target) H,
      fixedFieldValuationSubringAutDVF
          (base := base) (target := target) huniq H q a - a ∈
        fixedFieldRamificationIdealDVF
          (K := K) (target := target) H s}
  one_mem' := by
    intro a
    simp [fixedFieldValuationSubringAutDVF]
  mul_mem' := by
    intro q r hq hr a
    let eqv := fixedFieldValuationSubringAutDVF
      (base := base) (target := target) huniq H q
    have hra := hr a
    have hmap : eqv
        (fixedFieldValuationSubringAutDVF
            (base := base) (target := target) huniq H r a - a) ∈
        fixedFieldRamificationIdealDVF
          (K := K) (target := target) H s :=
      (ValuationTheory.ringEquiv_mem_maximalIdeal_pow_iff eqv
        (realRamificationExponent s) _).2 hra
    have hqa := hq a
    have hdecomp :
        fixedFieldValuationSubringAutDVF
              (base := base) (target := target) huniq H (q * r) a - a =
          eqv
              (fixedFieldValuationSubringAutDVF
                (base := base) (target := target) huniq H r a - a) +
            (eqv a - a) := by
      rw [fixedFieldValuationSubringAutDVF_mul_apply, map_sub]
      ring
    rw [hdecomp]
    exact Ideal.add_mem _ hmap hqa
  inv_mem' := by
    intro q hq a
    let b := fixedFieldValuationSubringAutDVF
      (base := base) (target := target) huniq H q⁻¹ a
    have hb := hq b
    have hqb :
        fixedFieldValuationSubringAutDVF
          (base := base) (target := target) huniq H q b = a := by
      rw [show b = fixedFieldValuationSubringAutDVF
        (base := base) (target := target) huniq H q⁻¹ a by rfl]
      rw [← fixedFieldValuationSubringAutDVF_mul_apply]
      simp [fixedFieldValuationSubringAutDVF]
    have hab : a - b ∈ fixedFieldRamificationIdealDVF
        (K := K) (target := target) H s := by
      simpa [hqb] using hb
    have hba : b - a ∈ fixedFieldRamificationIdealDVF
        (K := K) (target := target) H s := by
      simpa [sub_eq_add_neg, add_comm] using
        (fixedFieldRamificationIdealDVF
          (K := K) (target := target) H s).neg_mem hab
    simpa [b] using hba

/-- States the theorem `mem_fixedFieldLowerRamificationGroup_iff`. -/
@[simp] theorem mem_fixedFieldLowerRamificationGroup_iff
    (huniq :
      RamificationTheory.DiscreteValuationField.DVF.HasUniqueValuationExtension.{u, v, w, x, x}
        base target)
    (H : Subgroup Gal(L/K)) [H.Normal]
    (s : ℝ) (q : Gal((fixedFieldDVF (K := K) H)/K)) :
    q ∈ fixedFieldLowerRamificationGroup
        (base := base) (target := target) huniq H s ↔
      ∀ a : fixedFieldValuationSubringDVF
          (K := K) (target := target) H,
        fixedFieldValuationSubringAutDVF
            (base := base) (target := target) huniq H q a - a ∈
          fixedFieldRamificationIdealDVF
            (K := K) (target := target) H s :=
  Iff.rfl

/-- Real lower-group membership is exactly the threshold imposed by the
canonical fixed-field ramification number. -/
theorem mem_fixedFieldLowerRamificationGroup_iff_ramificationNumber
    (huniq :
      RamificationTheory.DiscreteValuationField.DVF.HasUniqueValuationExtension.{u, v, w, x, x}
        base target)
    (H : Subgroup Gal(L/K)) [H.Normal]
    (s : ℝ) (q : Gal((fixedFieldDVF (K := K) H)/K)) :
    q ∈ fixedFieldLowerRamificationGroup
        (base := base) (target := target) huniq H s ↔
      (realRamificationExponent s : ℕ∞) ≤
        fixedFieldRamificationNumber
          (base := base) (target := target) huniq H q := by
  let B := fixedFieldValuationSubringDVF (K := K) (target := target) H
  let J := fixedFieldDisplacementIdealDVF
    (base := base) (target := target) huniq H q
  let : IsDiscreteValuationRing B :=
    fixedFieldValuationSubringDVF_isDiscreteValuationRing
      (base := base) (target := target) huniq H
  let g : B := Submodule.IsPrincipal.generator J
  have hspan : Ideal.span ({g} : Set B) = J :=
    Submodule.IsPrincipal.span_singleton_generator J
  rw [mem_fixedFieldLowerRamificationGroup_iff]
  simp only [fixedFieldRamificationIdealDVF]
  unfold fixedFieldRamificationNumber
  dsimp only
  change
    (∀ a : B,
      fixedFieldValuationSubringAutDVF
            (base := base) (target := target) huniq H q a - a ∈
        IsLocalRing.maximalIdeal B ^ realRamificationExponent s) ↔
      (realRamificationExponent s : ℕ∞) ≤
        IsDiscreteValuationRing.addVal B g
  constructor
  · intro hall
    rw [← IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge]
    have hJle : J ≤
        IsLocalRing.maximalIdeal B ^ realRamificationExponent s := by
      simp only [J, fixedFieldDisplacementIdealDVF, Ideal.span_le]
      rintro d ⟨a, rfl⟩
      exact hall a
    exact hJle (Submodule.IsPrincipal.generator_mem J)
  · intro hgen
    have hg : g ∈ IsLocalRing.maximalIdeal B ^ realRamificationExponent s :=
      (IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge g
        (realRamificationExponent s)).2 hgen
    have hJle : J ≤
        IsLocalRing.maximalIdeal B ^ realRamificationExponent s := by
      rw [← hspan, Ideal.span_le]
      simpa using hg
    intro a
    apply hJle
    exact Ideal.subset_span ⟨a, rfl⟩


/-- At integral lower indices, actual fixed-field group membership is
equivalent to the canonical ramification-number inequality. -/
theorem mem_fixedFieldLowerRamificationGroup_nat_iff
    (huniq :
      RamificationTheory.DiscreteValuationField.DVF.HasUniqueValuationExtension.{u, v, w, x, x}
        base target)
    (H : Subgroup Gal(L/K)) [H.Normal]
    (n : ℕ) (q : Gal((fixedFieldDVF (K := K) H)/K)) :
    q ∈ fixedFieldLowerRamificationGroup
        (base := base) (target := target) huniq H (n : ℝ) ↔
      ((n + 1 : ℕ) : ℕ∞) ≤
        fixedFieldRamificationNumber
          (base := base) (target := target) huniq H q := by
  let B := fixedFieldValuationSubringDVF (K := K) (target := target) H
  let J := fixedFieldDisplacementIdealDVF
    (base := base) (target := target) huniq H q
  let : IsDiscreteValuationRing B :=
    fixedFieldValuationSubringDVF_isDiscreteValuationRing
      (base := base) (target := target) huniq H
  let g : B := Submodule.IsPrincipal.generator J
  have hspan : Ideal.span ({g} : Set B) = J := by
    exact Submodule.IsPrincipal.span_singleton_generator J
  rw [mem_fixedFieldLowerRamificationGroup_iff]
  simp only [fixedFieldRamificationIdealDVF,
    realRamificationExponent_nat]
  unfold fixedFieldRamificationNumber
  dsimp only
  change
    (∀ a : B,
      fixedFieldValuationSubringAutDVF
            (base := base) (target := target) huniq H q a - a ∈
        IsLocalRing.maximalIdeal B ^ (n + 1)) ↔
      ((n + 1 : ℕ) : ℕ∞) ≤ IsDiscreteValuationRing.addVal B g
  constructor
  · intro hall
    rw [← IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge]
    have hJle : J ≤ IsLocalRing.maximalIdeal B ^ (n + 1) := by
      simp only [J, fixedFieldDisplacementIdealDVF, Ideal.span_le]
      rintro d ⟨a, rfl⟩
      exact hall a
    exact hJle (Submodule.IsPrincipal.generator_mem J)
  · intro hgen
    have hg : g ∈ IsLocalRing.maximalIdeal B ^ (n + 1) :=
      (IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge g
        (n + 1)).2 hgen
    have hJle : J ≤ IsLocalRing.maximalIdeal B ^ (n + 1) := by
      rw [← hspan, Ideal.span_le]
      simpa using hg
    intro a
    apply hJle
    exact Ideal.subset_span ⟨a, rfl⟩

end Higher
end RamificationTheory.HilbertRamification
