import ClassFieldTheory.AlgebraicNumberTheory.Galois.CyclicPrimeSubextension
import ClassFieldTheory.AlgebraicNumberTheory.NormalClosure
import Mathlib.FieldTheory.Normal.Closure

set_option autoImplicit false

/-!
# Complete splitting and normal closures

This file formalizes the normal-closure reduction for complete splitting.
For a finite Galois extension `M / K`, an intermediate field `L`, a
nontrivial absolute value `v` of `K`, and an extension `w` to `M`, put

* `G = Gal(M / K)`,
* `H = Gal(M / L)`, and
* `D = D(w / v)`.

Restriction of the conjugates of `w` gives an equivalence

`H \ G / D ≃ { extensions of v to L }`.

Thus the intrinsic complete-splitting condition for the possibly
non-Galois extension `L / K` is exactly the equality between the number
of double cosets and the number of left cosets.  If `M` is generated by
the `K`-conjugates of `L`, then `H` has trivial normal core.
`SplittingGroupTheory` consequently forces `D = 1`, so the place splits
completely already in `M`.
-/

open scoped NumberField Classical
open NumberField IsDedekindDomain

noncomputable section

open AlgebraicNumberTheory.Valuations
open HilbertRamification

section AbsoluteValueExtensions

variable {K M : Type}
    [Field K] [Field M] [Algebra K M]

/-- Extend an actual extension of `v` from an intermediate field to the
ambient finite Galois extension.  The source is the absolute-value
extension theorem, applied to the algebraic extension `M / L`. -/
noncomputable def extendAbsoluteValueExtensionFromIntermediate
    [FiniteDimensional K M]
    (vK : AbsoluteValue K ℝ)
    (hvK : vK.IsNontrivial)
    (L : IntermediateField K M)
    (u : AbsoluteValueExtension vK L) :
    AbsoluteValueExtension vK M := by
  let : Module.IsTorsionFree L
      (absoluteValueExtension_algebraicCompletionClosure u.1) :=
    DivisionSemiring.to_moduleIsTorsionFree
  let hu : u.1.IsNontrivial :=
    u.isNontrivial hvK
  let wL : AbsoluteValueExtension u.1 M :=
    pullbackAbsoluteValueExtension
      u.1 hu IsAlgClosed.lift
  exact
    { val := wL.1
      property := by
        intro x
        rw [IsScalarTower.algebraMap_apply K L M,
          wL.2, u.2] }

@[simp]
theorem extendAbsoluteValueExtensionFromIntermediate_apply
    [FiniteDimensional K M]
    (vK : AbsoluteValue K ℝ)
    (hvK : vK.IsNontrivial)
    (L : IntermediateField K M)
    (u : AbsoluteValueExtension vK L)
    (x : L) :
    (extendAbsoluteValueExtensionFromIntermediate
      vK hvK L u).1 x = u.1 x := by
  let : Module.IsTorsionFree L
      (absoluteValueExtension_algebraicCompletionClosure u.1) :=
    DivisionSemiring.to_moduleIsTorsionFree
  change
    (pullbackAbsoluteValueExtension
      u.1 (u.isNontrivial hvK)
        IsAlgClosed.lift).1
      (algebraMap L M x) = u.1 x
  exact
    (pullbackAbsoluteValueExtension
      u.1 (u.isNontrivial hvK)
        IsAlgClosed.lift).2 x

variable (vK : AbsoluteValue K ℝ)
    (hvK : vK.IsNontrivial)
    (w : AbsoluteValueExtension vK M)
    (L : IntermediateField K M)

local notation "G" => M ≃ₐ[K] M
local notation "H" => L.fixingSubgroup
local notation "D" => absoluteValueDecompositionGroup K w.val

/-- The extension of `v` to `L` attached to a representative of
`H \ G / D`.  Inversion changes the natural `D \ G / H` convention for
the right action `w ↦ w ∘ σ` into the convention used for the normal-closure reduction. -/
noncomputable def doubleCosetExtension :
    DoubleCoset.Quotient (H : Set G) D →
      AbsoluteValueExtension vK L :=
  Quotient.lift
    (fun g : G ↦
      restrictAbsoluteValueExtensionToIntermediate
        vK
        (absoluteValueExtensionConjugate
          vK w g⁻¹)
        L)
    (by
      intro g r hgr
      change
        DoubleCoset.setoid (H : Set G) (D : Set G) g r
        at hgr
      rw [DoubleCoset.rel_iff] at hgr
      obtain ⟨h, hh, d, hd, rfl⟩ := hgr
      apply Subtype.ext
      ext x
      change
        w.1 (g⁻¹ (x : M)) =
          w.1 (d⁻¹ (g⁻¹ (h⁻¹ (x : M))))
      have hhInv : h⁻¹ ∈ H :=
        L.fixingSubgroup.inv_mem hh
      have hfix : h⁻¹ (x : M) = (x : M) :=
        hhInv x
      rw [hfix]
      have hdInv : d⁻¹ ∈ D :=
        (absoluteValueDecompositionGroup K w.val).inv_mem hd
      have hdEq :=
        (mem_absoluteValueDecompositionGroup_iff_extensionConjugate_eq
          vK hvK w d⁻¹).mp hdInv
      have hvalue :=
        congrArg
          (fun z : AbsoluteValueExtension vK M ↦
            z.1 (g⁻¹ (x : M)))
          hdEq
      exact hvalue.symm)

@[simp]
theorem doubleCosetExtension_mk
    (g : G) :
    doubleCosetExtension vK hvK w L
        (DoubleCoset.mk H D g) =
      restrictAbsoluteValueExtensionToIntermediate
        vK
        (absoluteValueExtensionConjugate
          vK w g⁻¹)
        L :=
  rfl

/-- Every extension of `v` to the intermediate field occurs by
restricting a conjugate of `w`. -/
theorem doubleCosetExtension_surjective
    [FiniteDimensional K M] [IsGalois K M] :
    Function.Surjective
      (doubleCosetExtension vK hvK w L) := by
  intro u
  let w' : AbsoluteValueExtension vK M :=
    extendAbsoluteValueExtensionFromIntermediate
      vK hvK L u
  obtain ⟨g : G, hg⟩ :=
    absoluteValueConjugacy vK hvK w w'
  refine
    ⟨DoubleCoset.mk H D g⁻¹, ?_⟩
  rw [doubleCosetExtension_mk]
  apply Subtype.ext
  ext x
  change w.1 (g (x : M)) = u.1 x
  have hvalue :=
    congrArg
      (fun z : AbsoluteValueExtension vK M ↦
        z.1 (x : M))
      hg
  change w'.1 (x : M) = w.1 (g (x : M))
    at hvalue
  rw [← hvalue]
  exact
    extendAbsoluteValueExtensionFromIntermediate_apply
      vK hvK L u x

/-- Equality after restriction to `L` is precisely equality of the
corresponding double cosets. The proof applies valuation-extension counting over
`L` and then reads the resulting `L`-automorphism as an element of
`H = Gal(M / L)`. -/
theorem doubleCosetExtension_injective
    [IsGalois K M] :
    Function.Injective
      (doubleCosetExtension vK hvK w L) := by
  intro q r hqr
  let g : G := q.out
  let s : G := r.out
  have hrestr :
      restrictAbsoluteValueExtensionToIntermediate
          vK
          (absoluteValueExtensionConjugate
            vK w g⁻¹)
          L =
        restrictAbsoluteValueExtensionToIntermediate
          vK
          (absoluteValueExtensionConjugate
            vK w s⁻¹)
          L := by
    calc
      _ = doubleCosetExtension vK hvK w L q := by
        rw [← DoubleCoset.out_eq' H D q]
        exact
          (doubleCosetExtension_mk
            vK hvK w L g).symm
      _ = doubleCosetExtension vK hvK w L r :=
        hqr
      _ = _ := by
        rw [← DoubleCoset.out_eq' H D r]
        exact
          doubleCosetExtension_mk
            vK hvK w L s
  let u :
      AbsoluteValueExtension vK L :=
    restrictAbsoluteValueExtensionToIntermediate
      vK
      (absoluteValueExtensionConjugate
        vK w g⁻¹)
      L
  let wG : AbsoluteValueExtension u.1 M :=
    absoluteValueExtensionOverIntermediate
      vK
      (absoluteValueExtensionConjugate
        vK w g⁻¹)
      L
  let wS : AbsoluteValueExtension u.1 M :=
    { val :=
        (absoluteValueExtensionConjugate
          vK w s⁻¹).1
      property := by
        intro x
        have hx :=
          congrArg
            (fun z : AbsoluteValueExtension vK L ↦
              z.1 x)
            hrestr
        change
          w.1 (s⁻¹ (x : M)) =
            w.1 (g⁻¹ (x : M))
        exact hx.symm }
  let hu : u.1.IsNontrivial :=
    u.isNontrivial hvK
  obtain ⟨η : M ≃ₐ[L] M, hη⟩ :=
    absoluteValueConjugacy u.1 hu wG wS
  let h : G :=
    η.restrictScalars K
  have hh : h ∈ H := by
    intro x
    exact η.commutes x
  let d : G :=
    s⁻¹ * h⁻¹ * g
  have hdEq :
      absoluteValueExtensionConjugate
          vK w d = w := by
    apply Subtype.ext
    ext x
    have hx :=
      congrArg
        (fun z : AbsoluteValueExtension u.1 M ↦
          z.1 (η⁻¹ (g x)))
        hη
    change
      w.1 (s⁻¹ (η⁻¹ (g x))) =
        w.1 (g⁻¹ (η (η⁻¹ (g x))))
      at hx
    change
      w.1 (s⁻¹ (η⁻¹ (g x))) = w.1 x
    simpa using hx
  have hd : d ∈ D :=
    (mem_absoluteValueDecompositionGroup_iff_extensionConjugate_eq
      vK hvK w d).mpr hdEq
  rw [← DoubleCoset.out_eq' H D q,
    ← DoubleCoset.out_eq' H D r,
    DoubleCoset.eq]
  refine
    ⟨h⁻¹, L.fixingSubgroup.inv_mem hh,
      d⁻¹,
      (absoluteValueDecompositionGroup K w.val).inv_mem hd,
      ?_⟩
  simp [d, g, s, mul_assoc]

/-- The place-counting equivalence in the orientation needed for the
normal-closure reduction. -/
noncomputable def doubleCosetExtensionEquiv
    [FiniteDimensional K M] [IsGalois K M] :
    DoubleCoset.Quotient (H : Set G) D ≃
      AbsoluteValueExtension vK L :=
  Equiv.ofBijective
    (doubleCosetExtension vK hvK w L)
    ⟨doubleCosetExtension_injective
        vK hvK w L,
      doubleCosetExtension_surjective
        vK hvK w L⟩

end AbsoluteValueExtensions

section CompleteSplitting

variable {K E : Type}
    [Field K] [Field E] [Algebra K E]
    [FiniteDimensional K E]

/-- Intrinsic complete splitting for an arbitrary finite extension:
the number of actual extensions of the absolute value is the full
degree.  Unlike a decomposition-group definition, this remains correct
when `E / K` is not Galois. -/
def AbsoluteValueSplitsCompletelyInExtension
    (vK : AbsoluteValue K ℝ) : Prop :=
  Nat.card (AbsoluteValueExtension vK E) =
    Module.finrank K E

variable [NumberField K]

/-- Intrinsic complete splitting of a finite place in a possibly
non-Galois finite extension. -/
def FinitePlaceSplitsCompletelyInExtension
    (v : HeightOneSpectrum (𝓞 K)) : Prop :=
  AbsoluteValueSplitsCompletelyInExtension
    (E := E)
    (NumberField.HeightOneSpectrum.adicAbv K v)

end CompleteSplitting

section DoubleCosetCount

variable {K M : Type}
    [Field K] [Field M] [Algebra K M]
    [IsGalois K M]

local notation "G" => M ≃ₐ[K] M

/-- The left-coset space `H \ G = H \ G / 1` has cardinality
`[L : K]` for `H = Gal(M / L)`. -/
theorem leftCosetDoubleCoset_card_eq_finrank
    (L : IntermediateField K M) :
    Nat.card
        (DoubleCoset.Quotient
          (L.fixingSubgroup : Set G)
          (⊥ : Subgroup G)) =
      Module.finrank K L := by
  calc
    Nat.card
        (DoubleCoset.Quotient
          (L.fixingSubgroup : Set G)
          (⊥ : Subgroup G)) =
        Nat.card
          (Quotient
            (QuotientGroup.rightRel
              L.fixingSubgroup)) := by
      rw [DoubleCoset.right_bot_eq_right_quot]
    _ = Nat.card (G ⧸ L.fixingSubgroup) :=
      Nat.card_congr
        (QuotientGroup.quotientRightRelEquivQuotientLeftRel
          L.fixingSubgroup)
    _ = L.fixingSubgroup.index :=
      L.fixingSubgroup.index_eq_card.symm
    _ = Module.finrank K L :=
      (IntermediateField.finrank_eq_fixingSubgroup_index
        (F := K) (E' := M) L).symm

variable [FiniteDimensional K M]

variable (vK : AbsoluteValue K ℝ)
    (w : AbsoluteValueExtension vK M)
    (L : IntermediateField K M)

/-- Place counting plus the definition of complete
splitting: `v` splits completely in `L` exactly when the double-coset
count equals the left-coset count. -/
theorem absoluteValueSplitsCompletelyInExtension_iff_doubleCoset_card_eq
    (hvK : vK.IsNontrivial) :
    AbsoluteValueSplitsCompletelyInExtension
        (E := L) vK ↔
      Nat.card
          (DoubleCoset.Quotient
            (L.fixingSubgroup : Set G)
            (absoluteValueDecompositionGroup K w.1)) =
        Nat.card
          (DoubleCoset.Quotient
            (L.fixingSubgroup : Set G)
            (⊥ : Subgroup G)) := by
  unfold AbsoluteValueSplitsCompletelyInExtension
  rw [Nat.card_congr
      (doubleCosetExtensionEquiv
        vK hvK w L),
    leftCosetDoubleCoset_card_eq_finrank]

/-- The actual decomposition group is trivial as soon as an
intermediate field with core-free fixing subgroup is completely split.
This is the reusable source-producing form of the normal-closure
normal-closure splitting argument. -/
theorem absoluteValueDecompositionGroup_eq_bot_of_splitsCompletelyInIntermediate
    (hvK : vK.IsNontrivial)
    (hcore :
      L.fixingSubgroup.normalCore = ⊥)
    (hsplit :
      AbsoluteValueSplitsCompletelyInExtension
        (E := L) vK) :
    absoluteValueDecompositionGroup K w.1 = ⊥ := by
  have hcard :=
    (absoluteValueSplitsCompletelyInExtension_iff_doubleCoset_card_eq
      vK w L hvK).mp hsplit
  exact
    (doubleCoset_card_eq_leftCoset_iff_of_normalCore_eq_bot
      L.fixingSubgroup
      (absoluteValueDecompositionGroup K w.1)
      hcore).mp hcard

/-- Fixed-field spelling of the preceding source theorem.  This is the
literal `L = M^H` formulation used in the normal-closure reduction. -/
theorem absoluteValueDecompositionGroup_eq_bot_of_splitsCompletelyInFixedField
    (hvK : vK.IsNontrivial)
    (H : Subgroup G)
    (hcore : H.normalCore = ⊥)
    (hsplit :
      AbsoluteValueSplitsCompletelyInExtension
        (E := IntermediateField.fixedField H) vK) :
    absoluteValueDecompositionGroup K w.1 = ⊥ := by
  apply
    absoluteValueDecompositionGroup_eq_bot_of_splitsCompletelyInIntermediate
      vK w (IntermediateField.fixedField H)
      hvK
  · simpa only
      [IntermediateField.fixingSubgroup_fixedField H]
      using hcore
  · exact hsplit

end DoubleCosetCount

section NormalClosure

variable {K M : Type}
    [Field K] [Field M] [Algebra K M]
    [FiniteDimensional K M] [IsGalois K M]

/-- If the conjugates of `L` generate the ambient Galois extension,
then `Gal(M / L)` is core-free.  This derives the group-theoretic
normal-closure condition from the actual field-theoretic normal
closure, rather than taking it as an additional hypothesis. -/
theorem fixingSubgroup_normalCore_eq_bot_of_normalClosure_eq_top
    (L : IntermediateField K M)
    (hclosure :
      IntermediateField.normalClosure K L M = ⊤) :
    L.fixingSubgroup.normalCore = ⊥ := by
  let N : Subgroup (M ≃ₐ[K] M) :=
    L.fixingSubgroup.normalCore
  let : N.Normal :=
    L.fixingSubgroup.normalCore_normal
  have hLle :
      L ≤ IntermediateField.fixedField N := by
    rw [← IsGalois.fixedField_fixingSubgroup L]
    exact
      IntermediateField.fixedField_le
        L.fixingSubgroup.normalCore_le
  let :
      IsGalois K (IntermediateField.fixedField N) :=
    IsGalois.of_fixedField_normal_subgroup N
  have hclosureLe :
      IntermediateField.normalClosure K L M ≤
        IntermediateField.fixedField N :=
    (IntermediateField.normalClosure_le_iff_of_normal).2
      hLle
  have htop :
      IntermediateField.fixedField N = ⊤ :=
    top_unique (hclosure ▸ hclosureLe)
  change N = ⊥
  rw [← IntermediateField.fixingSubgroup_fixedField N,
    htop, IntermediateField.fixingSubgroup_top]

/-- Class-valued normal-closure form of the preceding theorem. -/
theorem fixingSubgroup_normalCore_eq_bot_of_isNormalClosure
    (L : IntermediateField K M)
    [IsNormalClosure K L M] :
    L.fixingSubgroup.normalCore = ⊥ := by
  apply
    fixingSubgroup_normalCore_eq_bot_of_normalClosure_eq_top
      L
  exact
    (Algebra.IsAlgebraic.isNormalClosure_iff.mp
      (show IsNormalClosure K L M from inferInstance)).2

end NormalClosure

section FinitePlaces

variable {K M : Type}
    [Field K] [NumberField K]
    [Field M] [Algebra K M]
    [FiniteDimensional K M] [IsGalois K M]

local notation "G" => M ≃ₐ[K] M

/-- The double-coset criterion for an actual finite place and
the decomposition group attached to the standard chosen extension to
`M`. -/
theorem finitePlaceSplitsCompletelyInExtension_iff_doubleCoset_card_eq
    (L : IntermediateField K M)
    (v : HeightOneSpectrum (𝓞 K)) :
    FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := L) v ↔
      Nat.card
          (DoubleCoset.Quotient
            (L.fixingSubgroup : Set G)
            (finitePlaceDecompositionGroup
              (K := K) (L := M) v)) =
        Nat.card
          (DoubleCoset.Quotient
            (L.fixingSubgroup : Set G)
            (⊥ : Subgroup G)) := by
  exact
    absoluteValueSplitsCompletelyInExtension_iff_doubleCoset_card_eq
      (NumberField.HeightOneSpectrum.adicAbv K v)
      (chosenFinitePlaceExtension (L := M) v)
      L
      (RayClass.adicAbv_isNontrivial v)

/-- Literal fixed-field form: if `H` is core-free and the finite place
splits completely in `M^H`, then it splits completely in `M`. -/
theorem finitePlaceSplitsCompletely_in_ambient_of_fixedField
    (H : Subgroup G)
    (hcore : H.normalCore = ⊥)
    (v : HeightOneSpectrum (𝓞 K))
    (hsplit :
      FinitePlaceSplitsCompletelyInExtension
        (K := K)
        (E := IntermediateField.fixedField H) v) :
    FinitePlaceSplitsCompletely
      (K := K) (L := M) v := by
  exact
    absoluteValueDecompositionGroup_eq_bot_of_splitsCompletelyInFixedField
      (NumberField.HeightOneSpectrum.adicAbv K v)
      (chosenFinitePlaceExtension (L := M) v)
      (RayClass.adicAbv_isNontrivial v)
      H hcore hsplit

/-- Source-producing normal-closure reduction for a finite place.

The hypothesis says that `M` is generated by the `K`-conjugates of
`L`.  Complete splitting in the possibly non-Galois intermediate
extension gives the double-coset cardinality equality, the normal
closure makes the fixing subgroup core-free, and the actual chosen
decomposition group in `M / K` is therefore trivial. -/
theorem finitePlaceSplitsCompletely_in_normalClosure
    (L : IntermediateField K M)
    (hclosure :
      IntermediateField.normalClosure K L M = ⊤)
    (v : HeightOneSpectrum (𝓞 K))
    (hsplit :
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := L) v) :
    FinitePlaceSplitsCompletely
      (K := K) (L := M) v := by
  apply
    absoluteValueDecompositionGroup_eq_bot_of_splitsCompletelyInIntermediate
      (NumberField.HeightOneSpectrum.adicAbv K v)
      (chosenFinitePlaceExtension (L := M) v)
      L
      (RayClass.adicAbv_isNontrivial v)
      (fixingSubgroup_normalCore_eq_bot_of_normalClosure_eq_top
        L hclosure)
  exact hsplit

/-- Complete splitting ascends to an ambient field carrying the actual
`IsNormalClosure` instance. -/
theorem finitePlaceSplitsCompletely_in_isNormalClosure
    (L : IntermediateField K M)
    [IsNormalClosure K L M]
    (v : HeightOneSpectrum (𝓞 K))
    (hsplit :
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := L) v) :
    FinitePlaceSplitsCompletely
      (K := K) (L := M) v := by
  apply
    finitePlaceSplitsCompletely_in_normalClosure
      L
      ((Algebra.IsAlgebraic.isNormalClosure_iff.mp
        (show IsNormalClosure K L M from
          inferInstance)).2)
      v
  exact hsplit

/-- The same result displayed together with the intermediate
double-coset equality that drives the proof. -/
theorem finitePlace_normalClosure_doubleCoset_source
    (L : IntermediateField K M)
    (hclosure :
      IntermediateField.normalClosure K L M = ⊤)
    (v : HeightOneSpectrum (𝓞 K))
    (hsplit :
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := L) v) :
    (Nat.card
          (DoubleCoset.Quotient
            (L.fixingSubgroup : Set G)
            (finitePlaceDecompositionGroup
              (K := K) (L := M) v)) =
        Nat.card
          (DoubleCoset.Quotient
            (L.fixingSubgroup : Set G)
            (⊥ : Subgroup G))) ∧
      FinitePlaceSplitsCompletely
        (K := K) (L := M) v := by
  exact
    ⟨(finitePlaceSplitsCompletelyInExtension_iff_doubleCoset_card_eq
        L v).mp hsplit,
      finitePlaceSplitsCompletely_in_normalClosure
        L hclosure v hsplit⟩

end FinitePlaces

section SplittingTransport

variable
    {K E E' : Type}
    [Field K]
    [Field E] [Algebra K E]
    [Field E'] [Algebra K E']

/-- Transport extensions of an absolute value through an algebra
equivalence of finite extensions. -/
noncomputable def absoluteValueExtensionEquivOfAlgEquiv
    (v : AbsoluteValue K ℝ)
    (e : E ≃ₐ[K] E') :
    AbsoluteValueExtension v E ≃
      AbsoluteValueExtension v E' where
  toFun w :=
    { val :=
        w.1.comp (f := e.symm.toRingHom)
          e.symm.injective
      property := by
        intro x
        change w.1 (e.symm (algebraMap K E' x)) = v x
        rw [e.symm.commutes]
        exact w.2 x }
  invFun w :=
    { val :=
        w.1.comp (f := e.toRingHom)
          e.injective
      property := by
        intro x
        change w.1 (e (algebraMap K E x)) = v x
        rw [e.commutes]
        exact w.2 x }
  left_inv w := by
    apply Subtype.ext
    ext x
    change w.1 (e.symm (e x)) = w.1 x
    rw [e.symm_apply_apply]
  right_inv w := by
    apply Subtype.ext
    ext x
    change w.1 (e (e.symm x)) = w.1 x
    rw [e.apply_symm_apply]

variable [FiniteDimensional K E]
    [FiniteDimensional K E']

omit [FiniteDimensional K E] [FiniteDimensional K E'] in
/-- Intrinsic complete splitting is invariant under replacing the
extension by an isomorphic `K`-algebra. -/
theorem absoluteValueSplitsCompletelyInExtension_algEquiv
    (v : AbsoluteValue K ℝ)
    (e : E ≃ₐ[K] E') :
    AbsoluteValueSplitsCompletelyInExtension
        (E := E) v ↔
      AbsoluteValueSplitsCompletelyInExtension
        (E := E') v := by
  unfold AbsoluteValueSplitsCompletelyInExtension
  rw [Nat.card_congr
      (absoluteValueExtensionEquivOfAlgEquiv v e),
    e.toLinearEquiv.finrank_eq]

variable [NumberField K]

omit [FiniteDimensional K E] [FiniteDimensional K E'] in
/-- Finite-place complete splitting is invariant under a
`K`-algebra equivalence. -/
theorem finitePlaceSplitsCompletelyInExtension_algEquiv
    (e : E ≃ₐ[K] E')
    (v : HeightOneSpectrum (𝓞 K)) :
    FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := E) v ↔
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := E') v :=
  absoluteValueSplitsCompletelyInExtension_algEquiv
    (NumberField.HeightOneSpectrum.adicAbv K v) e

end SplittingTransport

section GaloisSplittingBridge

variable
    {K E : Type}
    [Field K] [NumberField K]
    [Field E] [Algebra K E]
    [FiniteDimensional K E]
    [IsGalois K E]

/-- For a finite Galois extension, complete splitting defined by the
chosen decomposition group is equivalent to intrinsic complete
splitting by the number of extensions of the place. -/
theorem finitePlaceSplitsCompletely_iff_inExtension
    (v : HeightOneSpectrum (𝓞 K)) :
    FinitePlaceSplitsCompletely
        (K := K) (L := E) v ↔
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := E) v := by
  let T : IntermediateField K E := ⊤
  let e : T ≃ₐ[K] E := by
    simpa only [T] using
      (IntermediateField.topEquiv :
        (⊤ : IntermediateField K E) ≃ₐ[K] E)
  have htransport :
      FinitePlaceSplitsCompletelyInExtension
          (K := K) (E := T) v ↔
        FinitePlaceSplitsCompletelyInExtension
          (K := K) (E := E) v :=
    finitePlaceSplitsCompletelyInExtension_algEquiv e v
  constructor
  · intro hsplit
    apply htransport.mp
    apply
      (finitePlaceSplitsCompletelyInExtension_iff_doubleCoset_card_eq
        (K := K) (M := E) T v).2
    rw [hsplit]
  · intro hsplit
    have hcard :=
      (finitePlaceSplitsCompletelyInExtension_iff_doubleCoset_card_eq
        (K := K) (M := E) T v).mp
        (htransport.mpr hsplit)
    change
      finitePlaceDecompositionGroup
          (K := K) (L := E) v =
        ⊥
    exact
      (doubleCoset_card_eq_leftCoset_iff_of_normalCore_eq_bot
        T.fixingSubgroup
        (finitePlaceDecompositionGroup
          (K := K) (L := E) v)
        (by
          simpa only
            [T, IntermediateField.fixingSubgroup_top]
            using
              (Subgroup.normalCore_eq_self
                (⊥ : Subgroup (E ≃ₐ[K] E))))).mp hcard

end GaloisSplittingBridge

section SplittingThroughRestriction

variable
    {K E N : Type}
    [Field K] [NumberField K]
    [Field E] [Algebra K E]
    [FiniteDimensional K E] [IsGalois K E]
    [Field N] [Algebra K N] [Algebra E N]
    [IsScalarTower K E N]
    [FiniteDimensional K N] [IsGalois K N]

/-- If the decomposition group upstairs acts trivially on a normal
subextension, then the finite place splits completely in that
subextension. -/
theorem
    finitePlaceSplitsCompletely_of_decompositionGroup_le_restrictNormalHom_ker
    (v : HeightOneSpectrum (𝓞 K))
    (h :
      finitePlaceDecompositionGroup (K := K) (L := N) v ≤
        (AlgEquiv.restrictNormalHom
          (F := K) (K₁ := N) (E := E)).ker) :
    FinitePlaceSplitsCompletely (K := K) (L := E) v := by
  let M : IntermediateField K N :=
    (IsScalarTower.toAlgHom K E N).fieldRange
  let e : E ≃ₐ[K] M :=
    (IsScalarTower.toAlgHom K E N).equivFieldRange
  let : FiniteDimensional K M :=
    e.toLinearEquiv.finiteDimensional
  let : IsGalois K M :=
    IsGalois.of_algEquiv e
  let vK :=
    NumberField.HeightOneSpectrum.adicAbv K v
  let hvK : vK.IsNontrivial :=
    RayClass.adicAbv_isNontrivial v
  let wN :=
    chosenFinitePlaceExtension (L := N) v
  let wM :=
    restrictAbsoluteValueExtensionToIntermediate
      vK wN M
  have hFix :
      finitePlaceDecompositionGroup (K := K) (L := N) v ≤
        M.fixingSubgroup := by
    intro sigma hsigma
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro y hy
    rcases hy with ⟨x, rfl⟩
    have hsigmaKer :
        AlgEquiv.restrictNormalHom
            (F := K) (K₁ := N) (E := E) sigma =
          1 :=
      MonoidHom.mem_ker.mp (h hsigma)
    have hx :
        sigma.restrictNormal E x = x := by
      change
        (AlgEquiv.restrictNormalHom
          (F := K) (K₁ := N) (E := E) sigma) x =
            (1 : Gal(E/K)) x
      rw [hsigmaKer]
    calc
      sigma (algebraMap E N x) =
          algebraMap E N (sigma.restrictNormal E x) :=
        (AlgEquiv.restrictNormal_commutes sigma E x).symm
      _ = algebraMap E N x :=
        congrArg (algebraMap E N) hx
  have hMap :
      (finitePlaceDecompositionGroup
          (K := K) (L := N) v).map
          (AlgEquiv.restrictNormalHom
            (F := K) (K₁ := N) M) =
        ⊥ := by
    rw [Subgroup.map_eq_bot_iff,
      IntermediateField.restrictNormalHom_ker]
    exact hFix
  have hwMbot :
      absoluteValueDecompositionGroup K wM.1 = ⊥ := by
    change
      absoluteValueDecompositionGroup K
        (wN.1.comp (f := algebraMap M N)
          (algebraMap M N).injective) = ⊥
    rw [← absoluteValueDecompositionGroup_map_restrictNormalHom
      (M := M) vK hvK wN]
    exact hMap
  have hM :
      FinitePlaceSplitsCompletely
        (K := K) (L := M) v := by
    change
      absoluteValueDecompositionGroup K
          (chosenFinitePlaceExtension (L := M) v).1 =
        ⊥
    exact
      absoluteValueDecompositionGroup_eq_bot_independent_extension
        vK hvK wM
        (chosenFinitePlaceExtension (L := M) v)
        hwMbot
  have hMIntrinsic :
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := M) v :=
    (finitePlaceSplitsCompletely_iff_inExtension
      (K := K) (E := M) v).mp hM
  have hEIntrinsic :
      FinitePlaceSplitsCompletelyInExtension
        (K := K) (E := E) v :=
    (finitePlaceSplitsCompletelyInExtension_algEquiv e v).mpr
      hMIntrinsic
  exact
    (finitePlaceSplitsCompletely_iff_inExtension
      (K := K) (E := E) v).mpr hEIntrinsic

end SplittingThroughRestriction

section FiniteNormalClosure

variable
    (K L : Type)
    [Field K] [NumberField K]
    [Field L] [NumberField L] [Algebra K L]

/-- The fixing subgroup of the distinguished copy of `L` is
core-free in the Galois group of its finite normal closure. -/
theorem finiteNormalClosureOriginalField_fixingSubgroup_normalCore :
    (finiteNormalClosureOriginalField K L).fixingSubgroup.normalCore =
      ⊥ := by
  exact
    fixingSubgroup_normalCore_eq_bot_of_normalClosure_eq_top
      (finiteNormalClosureOriginalField K L)
      (finiteNormalClosureOriginalField_normalClosure_eq_top K L)

/-- Complete splitting in the original extension forces complete
splitting in its finite normal closure. -/
theorem finitePlaceSplitsCompletely_in_finiteNormalClosure
    (v : HeightOneSpectrum (𝓞 K))
    (hsplit :
      FinitePlaceSplitsCompletelyInExtension
        (K := K)
        (E := finiteNormalClosureOriginalField K L) v) :
    FinitePlaceSplitsCompletely
      (K := K) (L := finiteNormalClosure K L) v := by
  exact
    finitePlaceSplitsCompletely_in_normalClosure
      (finiteNormalClosureOriginalField K L)
      (finiteNormalClosureOriginalField_normalClosure_eq_top K L)
      v hsplit

/-- If only finitely many finite places fail to split completely in
`L`, the same is true in the finite normal closure. -/
theorem finite_nonSplittingPlaces_finiteNormalClosure
    (hfinite :
      {v : HeightOneSpectrum (𝓞 K) |
        ¬ FinitePlaceSplitsCompletelyInExtension
          (K := K)
          (E := finiteNormalClosureOriginalField K L) v}.Finite) :
    {v : HeightOneSpectrum (𝓞 K) |
      ¬ FinitePlaceSplitsCompletely
        (K := K) (L := finiteNormalClosure K L) v}.Finite := by
  apply hfinite.subset
  intro v hv hsplit
  exact hv
    (finitePlaceSplitsCompletely_in_finiteNormalClosure
      K L v hsplit)

/-- Finiteness of the nonsplitting set in the original field
transports to its distinguished copy in the finite normal closure. -/
theorem finite_nonSplittingPlaces_originalField
    (hfinite :
      {v : HeightOneSpectrum (𝓞 K) |
        ¬ FinitePlaceSplitsCompletelyInExtension
          (K := K) (E := L) v}.Finite) :
    {v : HeightOneSpectrum (𝓞 K) |
      ¬ FinitePlaceSplitsCompletelyInExtension
        (K := K)
        (E := finiteNormalClosureOriginalField K L) v}.Finite := by
  simpa only [
    finitePlaceSplitsCompletelyInExtension_algEquiv
      (finiteNormalClosureOriginalFieldEquiv K L)] using hfinite

/-- Finiteness of the nonsplitting set in `L / K` implies finiteness
of the nonsplitting set in its finite normal closure. -/
theorem finite_nonSplittingPlaces_normalClosure_of_original
    (hfinite :
      {v : HeightOneSpectrum (𝓞 K) |
        ¬ FinitePlaceSplitsCompletelyInExtension
          (K := K) (E := L) v}.Finite) :
    {v : HeightOneSpectrum (𝓞 K) |
      ¬ FinitePlaceSplitsCompletely
        (K := K) (L := finiteNormalClosure K L) v}.Finite :=
  finite_nonSplittingPlaces_finiteNormalClosure K L
    (finite_nonSplittingPlaces_originalField K L hfinite)

end FiniteNormalClosure
