import ClassFieldTheory.AlgebraicNumberTheory.Ramification.Splitting.NormalClosure

set_option autoImplicit false

/-!
# Prime-order fixed fields and complete splitting

This file formalizes a prime-order fixed-field reduction.
From a nontrivial finite Galois extension `L / K` we choose an
automorphism `σ` of prime order `p` and form

`K' = L ^ ⟨σ⟩`.

The extension `L / K'` is an actual cyclic Galois extension of prime
degree.  We also prove the finite-place bridge used immediately before
applying the cyclic prime-power splitting criterion: if a finite place of `K` splits completely in `L`
and a finite place of `K'` lies above it, then the latter splits
completely in `L / K'`.
-/

open scoped NumberField Classical
open NumberField IsDedekindDomain

noncomputable section

open AlgebraicNumberTheory.Valuations
open HilbertRamification

section PrimeOrderConstruction

variable {K L : Type}
    [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [IsGalois K L]

local notation "G" => L ≃ₐ[K] L

/-- A nontrivial finite Galois extension has an automorphism of prime
order.  Nontriviality is supplied by the actual degree inequality. -/
theorem exists_prime_order_automorphism_of_one_lt_finrank
    (hdegree : 1 < Module.finrank K L) :
    ∃ (p : ℕ) (σ : G),
      p.Prime ∧ orderOf σ = p := by
  have hcard : 1 < Nat.card G := by
    rw [IsGalois.card_aut_eq_finrank K L]
    exact hdegree
  let : Nontrivial G :=
    Finite.one_lt_card_iff_nontrivial.mp hcard
  exact exists_element_of_prime_order G

/-- The chosen prime order in the nontrivial Galois group. -/
noncomputable def fixedFieldPrime
    (hdegree : 1 < Module.finrank K L) : ℕ :=
  (exists_prime_order_automorphism_of_one_lt_finrank
    (K := K) (L := L) hdegree).choose

/-- The chosen automorphism of prime order. -/
noncomputable def primeOrderAutomorphism
    (hdegree : 1 < Module.finrank K L) : G :=
  (exists_prime_order_automorphism_of_one_lt_finrank
    (K := K) (L := L) hdegree).choose_spec.choose

theorem fixedFieldPrime_prime
    (hdegree : 1 < Module.finrank K L) :
    (fixedFieldPrime
      (K := K) (L := L) hdegree).Prime :=
  (exists_prime_order_automorphism_of_one_lt_finrank
    (K := K) (L := L) hdegree).choose_spec.choose_spec.1

theorem primeOrderAutomorphism_orderOf
    (hdegree : 1 < Module.finrank K L) :
    orderOf
        (primeOrderAutomorphism
          (K := K) (L := L) hdegree) =
      fixedFieldPrime
        (K := K) (L := L) hdegree :=
  (exists_prime_order_automorphism_of_one_lt_finrank
    (K := K) (L := L) hdegree).choose_spec.choose_spec.2

/-- The cyclic subgroup generated by the chosen prime-order
automorphism. -/
noncomputable def primeOrderSubgroup
    (hdegree : 1 < Module.finrank K L) :
    Subgroup G :=
  Subgroup.zpowers
    (primeOrderAutomorphism
      (K := K) (L := L) hdegree)

theorem primeOrderSubgroup_card
    (hdegree : 1 < Module.finrank K L) :
    Nat.card
        (primeOrderSubgroup
          (K := K) (L := L) hdegree) =
      fixedFieldPrime
        (K := K) (L := L) hdegree := by
  rw [primeOrderSubgroup, Nat.card_zpowers,
    primeOrderAutomorphism_orderOf]

/-- The actual intermediate field `K' = L ^ ⟨σ⟩`. -/
noncomputable def primeOrderFixedField
    (hdegree : 1 < Module.finrank K L) :
    IntermediateField K L :=
  IntermediateField.fixedField
    (primeOrderSubgroup
      (K := K) (L := L) hdegree)

/-- The ambient field is Galois over the fixed field of the chosen
finite subgroup. -/
noncomputable instance primeOrderFixedField_isGalois
    (hdegree : 1 < Module.finrank K L) :
    IsGalois
      (primeOrderFixedField
        (K := K) (L := L) hdegree)
      L := by
  unfold primeOrderFixedField
  exact
    IsGalois.of_fixed_field L
      (primeOrderSubgroup
        (K := K) (L := L) hdegree)

/-- The constructed relative extension has prime degree `p`. -/
theorem primeOrderFixedField_finrank
    (hdegree : 1 < Module.finrank K L) :
    Module.finrank
        (primeOrderFixedField
          (K := K) (L := L) hdegree)
        L =
      fixedFieldPrime
        (K := K) (L := L) hdegree := by
  unfold primeOrderFixedField
  rw [IntermediateField.finrank_fixedField_eq_card,
    primeOrderSubgroup_card]

/-- The relative Galois group is cyclic, transported from the
generating subgroup through the finite Galois correspondence. -/
noncomputable instance primeOrderFixedField_isCyclic
    (hdegree : 1 < Module.finrank K L) :
    IsCyclic
      (L ≃ₐ[
        primeOrderFixedField
          (K := K) (L := L) hdegree] L) := by
  let P :=
    primeOrderSubgroup
      (K := K) (L := L) hdegree
  have hP : IsCyclic P := by
    dsimp [P, primeOrderSubgroup]
    exact
      Subgroup.isCyclic_zpowers
        (primeOrderAutomorphism
          (K := K) (L := L) hdegree)
  exact
    (IntermediateField.subgroupEquivAlgEquiv P).isCyclic.mp
      hP

/-- The order of the relative Galois group is the chosen prime.  In
particular it is a prime-power order with exponent one, exactly the
input expected by the cyclic prime-power splitting criterion. -/
theorem primeOrderFixedField_card_aut
    (hdegree : 1 < Module.finrank K L) :
    Nat.card
        (L ≃ₐ[
          primeOrderFixedField
            (K := K) (L := L) hdegree] L) =
      fixedFieldPrime
        (K := K) (L := L) hdegree := by
  rw [IsGalois.card_aut_eq_finrank,
    primeOrderFixedField_finrank]

end PrimeOrderConstruction

section FinitePlaceAscent

variable {K M : Type}
    [Field K] [NumberField K]
    [Field M] [NumberField M]
    [Algebra K M]

/-- A finite place of `M` lies above a finite place of `K` when its
normalized adic absolute value is an exact extension. -/
def FinitePlaceLiesAbove
    (v : HeightOneSpectrum (𝓞 K))
    (v' : HeightOneSpectrum (𝓞 M)) : Prop :=
  AbsoluteValue.Extends
    (NumberField.HeightOneSpectrum.adicAbv K v)
    (NumberField.HeightOneSpectrum.adicAbv M v')

variable {L : Type}
    [Field L] [NumberField L]
    [Algebra K L] [Algebra M L]
    [IsScalarTower K M L]
    [FiniteDimensional K L] [IsGalois K L]
    [IsGalois M L]

/-- Complete splitting ascends from a base finite place to every
finite place of an intermediate field lying above it.

The proof uses the chosen extension above `v'`, regards it as an
extension above `v`, changes from the standard chosen extension over
`K` by valuation-extension counting, and finally restricts the trivial
decomposition group from `K` to `M`. -/
theorem finitePlaceSplitsCompletely_over_intermediate_of_liesAbove
    (v : HeightOneSpectrum (𝓞 K))
    (v' : HeightOneSpectrum (𝓞 M))
    (hAbove : FinitePlaceLiesAbove (K := K) (M := M) v v')
    (hsplit :
      FinitePlaceSplitsCompletely
        (K := K) (L := L) v) :
    FinitePlaceSplitsCompletely
      (K := M) (L := L) v' := by
  let vK :=
    NumberField.HeightOneSpectrum.adicAbv K v
  let vM :=
    NumberField.HeightOneSpectrum.adicAbv M v'
  let hvK : vK.IsNontrivial :=
    RayClass.adicAbv_isNontrivial v
  let wM : AbsoluteValueExtension vM L :=
    chosenFinitePlaceExtension (L := L) v'
  let wK : AbsoluteValueExtension vK L :=
    { val := wM.1
      property := by
        intro x
        rw [IsScalarTower.algebraMap_apply K M L,
          wM.2]
        exact hAbove x }
  have hKbot :
      absoluteValueDecompositionGroup K wK.1 = ⊥ := by
    exact
      absoluteValueDecompositionGroup_eq_bot_independent_extension
        vK hvK
        (chosenFinitePlaceExtension (L := L) v)
        wK hsplit
  change
    absoluteValueDecompositionGroup M wM.1 = ⊥
  exact
    absoluteValueDecompositionGroup_eq_bot_over_intermediate
      (K := K) (M := M) (L := L)
      wM.1 hKbot

end FinitePlaceAscent

section PrimeOrderFinitePlaces

variable {K L : Type}
    [Field K] [NumberField K]
    [Field L] [NumberField L]
    [Algebra K L]
    [FiniteDimensional K L] [IsGalois K L]

omit [NumberField K] [NumberField L] in
/-- The chosen fixed field supplies all algebraic data needed to apply
the cyclic prime-power case with exponent one. -/
theorem primeOrderFixedField_threeSeven_data
    (hdegree : 1 < Module.finrank K L) :
    let K' :=
      primeOrderFixedField
        (K := K) (L := L) hdegree
    let p :=
      fixedFieldPrime
        (K := K) (L := L) hdegree
    p.Prime ∧
      IsGalois K' L ∧
      IsCyclic (L ≃ₐ[K'] L) ∧
      Nat.card (L ≃ₐ[K'] L) = p := by
  dsimp
  exact
    ⟨fixedFieldPrime_prime
        (K := K) (L := L) hdegree,
      inferInstance,
      inferInstance,
      primeOrderFixedField_card_aut
        (K := K) (L := L) hdegree⟩

/-- The finite-place ascent bridge specialized to the chosen
prime-order fixed field `K'`. -/
theorem finitePlaceSplitsCompletely_over_primeOrderFixedField_of_liesAbove
    (hdegree : 1 < Module.finrank K L)
    (v : HeightOneSpectrum (𝓞 K))
    (v' :
      HeightOneSpectrum
        (𝓞 (primeOrderFixedField
          (K := K) (L := L) hdegree)))
    (hAbove :
      FinitePlaceLiesAbove
        (K := K)
        (M := primeOrderFixedField
          (K := K) (L := L) hdegree)
        v v')
    (hsplit :
      FinitePlaceSplitsCompletely
        (K := K) (L := L) v) :
    FinitePlaceSplitsCompletely
      (K := primeOrderFixedField
        (K := K) (L := L) hdegree)
      (L := L) v' := by
  exact
    finitePlaceSplitsCompletely_over_intermediate_of_liesAbove
      (K := K)
      (M := primeOrderFixedField
        (K := K) (L := L) hdegree)
      (L := L)
      v v' hAbove hsplit

end PrimeOrderFinitePlaces
