import Mathlib.NumberTheory.Cyclotomic.Basic

set_option autoImplicit false

/-!
# The rational cyclotomic closure

This file constructs the actual field `ℚ(μ∞)` inside `SeparableClosure ℚ`.
It uses mathlib's general `IsCyclotomicExtension` API, so the infinite
field and its finite cyclotomic levels are not replaced by abstract copies
of their expected Galois groups.

The finite levels form the divisibility-directed system whose supremum is
the whole cyclotomic field.  This supplies the field-theoretic source for
the rational cyclotomic calculation.
-/

noncomputable section

namespace KummerTheory

/-- The actual field `ℚ(μ∞)` in a fixed separable closure of `ℚ`. -/
def rationalCyclotomicField :
    IntermediateField ℚ (SeparableClosure ℚ) :=
  IntermediateField.adjoin ℚ
    {ζ : SeparableClosure ℚ |
      ∃ n ∈ (Set.univ : Set ℕ), n ≠ 0 ∧ ζ ^ n = 1}

/-- The field `ℚ(μ∞)` is the cyclotomic extension generated by roots of
unity of all positive orders. -/
noncomputable instance rationalCyclotomicField_isCyclotomicExtension :
    IsCyclotomicExtension (Set.univ : Set ℕ) ℚ
      rationalCyclotomicField := by
  exact
    IntermediateField.isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot
      (Set.univ : Set ℕ) ℚ (SeparableClosure ℚ)
      (fun n _hn hn0 =>
        IsCyclotomicExtension.exists_isPrimitiveRoot
          (S := (Set.univ : Set ℕ))
          (SeparableClosure ℚ) (SeparableClosure ℚ)
          (Set.mem_univ n) hn0)

/-- The actual infinite rational cyclotomic extension is abelian Galois. -/
noncomputable instance rationalCyclotomicField_isAbelianGalois :
    IsAbelianGalois ℚ rationalCyclotomicField :=
  IsCyclotomicExtension.isAbelianGalois
    (Set.univ : Set ℕ) ℚ rationalCyclotomicField

/-- The `n`-th finite cyclotomic level inside `ℚ(μ∞)`.  Positive naturals
are used so that the zero-order degeneracy cannot enter the directed
system. -/
def rationalCyclotomicLevel (n : ℕ+) :
    IntermediateField ℚ rationalCyclotomicField :=
  IntermediateField.adjoin ℚ
    {ζ : rationalCyclotomicField |
      ∃ m ∈ ({(n : ℕ)} : Set ℕ),
        m ≠ 0 ∧ ζ ^ m = 1}

/-- Each internal finite level is the standard singleton cyclotomic
extension. -/
noncomputable instance rationalCyclotomicLevel_isCyclotomicExtension
    (n : ℕ+) :
    IsCyclotomicExtension {(n : ℕ)} ℚ
      (rationalCyclotomicLevel n) := by
  exact
    IntermediateField.isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot
      {(n : ℕ)} ℚ rationalCyclotomicField
      (fun m _hm _hm0 =>
        IsCyclotomicExtension.exists_isPrimitiveRoot
          (S := (Set.univ : Set ℕ))
          ℚ rationalCyclotomicField
          (Set.mem_univ m) _hm0)

/-- Every finite internal cyclotomic level is Galois over `ℚ`. -/
noncomputable instance rationalCyclotomicLevel_isGalois
    (n : ℕ+) :
    IsGalois ℚ (rationalCyclotomicLevel n) :=
  IsCyclotomicExtension.isGalois
    {(n : ℕ)} ℚ (rationalCyclotomicLevel n)

/-- A finite level of `ℚ(μ∞)` carries mathlib's standard number-field
structure coming from its singleton cyclotomic presentation. -/
noncomputable instance rationalCyclotomicLevel_numberField
    (n : ℕ+) :
    NumberField (rationalCyclotomicLevel n) :=
  IsCyclotomicExtension.numberField
    {(n : ℕ)} ℚ (rationalCyclotomicLevel n)

/-- Divisibility of orders gives the canonical inclusion between internal
cyclotomic levels. -/
theorem rationalCyclotomicLevel_mono
    {m n : ℕ+}
    (h : (m : ℕ) ∣ (n : ℕ)) :
    rationalCyclotomicLevel m ≤
      rationalCyclotomicLevel n :=
  IntermediateField.isCyclotomicExtension_le_of_dvd
    ℚ rationalCyclotomicField (m : ℕ) (n : ℕ)
    (rationalCyclotomicLevel m)
    (rationalCyclotomicLevel n)
    (h₁ := rationalCyclotomicLevel_isCyclotomicExtension m)
    (h₂ := rationalCyclotomicLevel_isCyclotomicExtension n)
    h

/-- The internal finite cyclotomic levels exhaust `ℚ(μ∞)`. -/
theorem iSup_rationalCyclotomicLevel :
    (⨆ n : ℕ+, rationalCyclotomicLevel n) = ⊤ := by
  have htop :
      IntermediateField.adjoin ℚ
          {ζ : rationalCyclotomicField |
            ∃ n : ℕ, n ∈ (Set.univ : Set ℕ) ∧
              n ≠ 0 ∧ ζ ^ n = 1} =
        ⊤ :=
    IntermediateField.adjoin_eq_top_of_algebra ℚ _
      ((IsCyclotomicExtension.iff_adjoin_eq_top
        (Set.univ : Set ℕ) ℚ rationalCyclotomicField).1
          inferInstance).2
  apply le_antisymm le_top
  rw [← htop, IntermediateField.adjoin_le_iff]
  rintro ζ ⟨n, _hn, hn0, hpow⟩
  let npos : ℕ+ := ⟨n, Nat.pos_of_ne_zero hn0⟩
  exact
    (le_iSup
      (fun m : ℕ+ => rationalCyclotomicLevel m) npos)
      (IntermediateField.subset_adjoin ℚ
        {x : rationalCyclotomicField |
          ∃ m ∈ ({(npos : ℕ)} : Set ℕ),
            m ≠ 0 ∧ x ^ m = 1}
        (by
          refine
            ⟨(npos : ℕ), by simp, npos.ne_zero, ?_⟩
          change ζ ^ n = 1
          exact hpow))

end KummerTheory
