import Mathlib.GroupTheory.Index
import Mathlib.SetTheory.Cardinal.Finite
import ClassFieldTheory.LubinTate.FiniteLevel.StandardLocalField
import ValuedFieldTheory.LocalField.NonarchimedeanLocalField.UniformizerPrincipalQuotient
import ClassFieldTheory.LubinTate.FiniteLevel.FiniteParameters
import ClassFieldTheory.LubinTate.FiniteLevel.NormSubgroup

set_option autoImplicit false

/-!
# The canonical standard subgroup index

For the topology-first nonarchimedean local field `K`, the canonical
Lubin--Tate uniformizer and the `(n + 1)`-st principal units generate a
subgroup of `Kˣ` of index

`(Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n`.

The proof passes from field units to integer units, transports the latter
through the canonical packaged local-field equivalence, and then uses the
finite standard Lubin--Tate unit-parameter count.
-/

noncomputable section

open scoped ValuativeRel

namespace LubinTate

open LocalFieldTheory
open LocalFieldTheory
open LocalFieldTheory.DiscreteValuationField
open LocalFieldTheory.DiscreteValuationField.CompleteDVF
open LocalFieldTheory.IsNonarchimedeanLocalField

variable (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- The canonical packaged Lubin--Tate uniformizer is the topology-first
chosen integer-ring uniformizer, viewed as a field unit. -/
@[simp]
theorem standardLubinTateCanonicalBaseUniformizerUnit_eq_integerRingUniformizerFieldUnit :
    standardLubinTateBaseUniformizerUnit
        (standardLocalFieldUniformizer_isUniformizer K) =
      integerRingUniformizerFieldUnit K := by
  apply Units.ext
  rfl

/-- The inverse of the canonical packaged Lubin--Tate uniformizer has
positive normalized additive valuation. -/
theorem standardLubinTateCanonicalBaseUniformizerUnit_inv_valuationMap :
    valuationMap K
        (Additive.ofMul
          (standardLubinTateBaseUniformizerUnit
            (standardLocalFieldUniformizer_isUniformizer K))⁻¹) =
      1 := by
  rw [valuationMap_apply,
    standardLubinTateCanonicalBaseUniformizerUnit_eq_integerRingUniformizerFieldUnit]
  exact v_inverseIntegerRingUniformizerFieldUnit K

/-- The canonical integer-unit equivalence identifies the standard finite
Lubin--Tate unit parameters with the topology-first principal-unit
quotient. -/
noncomputable def
    standardLubinTateUnitParameterEquivIntegerUnitsPrincipalQuotient
    (n : ℕ) :
    standardLubinTateUnitParameter (standardLocalField K) n ≃*
      IntegerUnitsPrincipalQuot K (n + 1) :=
  QuotientGroup.congr _ _
    (standardLocalFieldIntegerUnitsEquiv K).symm
    (standardLocalFieldHigherPrincipalUnitGroup_map_eq_principalUnits
      K (n + 1))

/-- The subgroup generated by the canonical Lubin--Tate uniformizer and
`U^(n+1)` has the expected standard finite-level index. -/
theorem standardLubinTateCanonicalUniformizerPrincipalSubgroup_index
    (n : ℕ) :
    (LocalFieldTheory.uniformizerPrincipalSubgroup K
        (standardLubinTateBaseUniformizerUnit
          (standardLocalFieldUniformizer_isUniformizer K))
        1 (n + 1)).index =
      (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n := by
  let pi : Kˣ :=
    standardLubinTateBaseUniformizerUnit
      (standardLocalFieldUniformizer_isUniformizer K)
  change
    (LocalFieldTheory.uniformizerPrincipalSubgroup K pi 1 (n + 1)).index =
      (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n
  have hpi : valuationMap K (Additive.ofMul pi⁻¹) = 1 := by
    simpa only [pi] using
      standardLubinTateCanonicalBaseUniformizerUnit_inv_valuationMap K
  have hinv :
      LocalFieldTheory.uniformizerPrincipalSubgroup K pi 1 (n + 1) =
        LocalFieldTheory.uniformizerPrincipalSubgroup K pi⁻¹ 1 (n + 1) := by
    simp [LocalFieldTheory.uniformizerPrincipalSubgroup, Subgroup.zpowers_inv]
  rw [hinv, Subgroup.index_eq_card]
  calc
    Nat.card
        (Kˣ ⧸ LocalFieldTheory.uniformizerPrincipalSubgroup K pi⁻¹ 1 (n + 1)) =
        Nat.card (IntegerUnitsPrincipalQuot K (n + 1)) :=
      Nat.card_congr
        (LocalFieldTheory.uniformizerPrincipalQuotientEquivIntegerUnitsPrincipalQuotient
          K pi⁻¹ hpi (n + 1)).toEquiv
    _ =
        Nat.card
          (standardLubinTateUnitParameter (standardLocalField K) n) :=
      Nat.card_congr
        (standardLubinTateUnitParameterEquivIntegerUnitsPrincipalQuotient
          K n).symm.toEquiv
    _ = (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n := by
      simpa only [standardLocalField_residueField_natCard] using
        standardLubinTateUnitParameter_natCard
          (standardLocalField K) n

/-- A finite-index subgroup contained in another subgroup with the same
index is already equal to it.  The nonzero-index hypothesis excludes the
infinite-index convention `index = 0`. -/
theorem subgroup_eq_of_le_of_index_eq_of_ne_zero
    {G : Type*} [Group G] {H N : Subgroup G}
    (hHN : H ≤ N) (hindex : H.index = N.index)
    (hindex_ne : H.index ≠ 0) :
    H = N := by
  let _ : H.FiniteIndex := ⟨hindex_ne⟩
  apply le_antisymm hHN
  by_contra hNH
  have hne : H ≠ N := by
    intro heq
    apply hNH
    rw [heq]
  have hstrict : H < N := lt_of_le_of_ne hHN hne
  have hi := Subgroup.index_strictAnti hstrict
  rw [hindex] at hi
  exact Nat.lt_irrefl _ hi

end LubinTate

end
