import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardNormIndex
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardSubgroupIndex
import ClassFieldTheory.LubinTate.FiniteLevel.HigherUnitLevelEquiv

set_option autoImplicit false

/-!
# The norm subgroup of a standard Lubin--Tate level

The changed-uniformizer comparison shows that every `(n + 1)`-st
principal unit is a norm from the standard level `n`.  Together with the
known norm of the chosen uniformizer, this contains the canonical standard
open subgroup in the norm subgroup.  Their independently computed,
nonzero indices are equal, so the containment is an equality.
-/

noncomputable section

open scoped ValuativeRel

namespace LubinTate

open LocalClassFieldTheory
open LocalFieldTheory
open LocalFieldTheory.DiscreteValuationField
open LocalFieldTheory.DiscreteValuationField.CompleteDVF
open LocalFieldTheory.IsNonarchimedeanLocalField

variable (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- The topology-first inclusion of packaged valuation-ring units agrees
with the inclusion used in the changed-uniformizer norm calculation. -/
@[simp]
theorem
    standardLocalFieldValuationUnitsToFieldUnits_eq_standardLubinTateUnitFactorFieldUnit
    (u : (standardLocalField K).valuationSubringˣ) :
    standardLocalFieldValuationUnitsToFieldUnits K u =
      standardLubinTateUnitFactorFieldUnit (standardLocalField K) u := by
  apply Units.ext
  simp only [
    standardLocalFieldValuationUnitsToFieldUnits_apply_coe,
    standardLubinTateUnitFactorFieldUnit_coe]

/-- Every `(n + 1)`-st field principal unit is a norm from the standard
Lubin--Tate level `n`. -/
theorem standardLubinTateFieldPrincipalUnits_le_normSubgroup
    {π : (standardLocalField K).valuationSubring}
    (hπ :
      (standardLocalField K).toCompleteDVF.valuation.IsUniformizer
        (π : K))
    (n : ℕ) :
    LocalFieldTheory.fieldPrincipalUnits K (n + 1) ≤
      standardLubinTateNormSubgroup hπ n := by
  rw [
    ← standardLocalFieldHigherPrincipalUnitGroup_map_eq_fieldPrincipalUnits
      K (n + 1)]
  rintro x ⟨u, hu, rfl⟩
  rw [
    standardLocalFieldValuationUnitsToFieldUnits_eq_standardLubinTateUnitFactorFieldUnit]
  exact
    standardLubinTateUnitFactorFieldUnit_mem_standardNormSubgroup_of_mem_higher
      hπ u n hu

/-- The subgroup generated by the chosen uniformizer and
`U_K^(n+1)` is contained in the norm subgroup of the standard level `n`. -/
theorem standardLubinTateUniformizerPrincipalSubgroup_le_normSubgroup
    {π : (standardLocalField K).valuationSubring}
    (hπ :
      (standardLocalField K).toCompleteDVF.valuation.IsUniformizer
        (π : K))
    (n : ℕ) :
    LocalFieldTheory.uniformizerPrincipalSubgroup K
        (standardLubinTateBaseUniformizerUnit hπ) 1 (n + 1) ≤
      standardLubinTateNormSubgroup hπ n := by
  unfold LocalFieldTheory.uniformizerPrincipalSubgroup
  apply sup_le
  · simpa only [pow_one] using
      standardLubinTateBaseUniformizerUnit_zpowers_le_normSubgroup hπ n
  · exact
      standardLubinTateFieldPrincipalUnits_le_normSubgroup K hπ n

/-- For the canonical local-field package, the norm subgroup of standard
level `n` is exactly the subgroup generated by the canonical uniformizer
and `U_K^(n+1)`. -/
theorem
    standardLubinTateCanonicalUniformizerPrincipalSubgroup_eq_normSubgroup
    (n : ℕ) :
    LocalFieldTheory.uniformizerPrincipalSubgroup K
        (standardLubinTateBaseUniformizerUnit
          (standardLocalFieldUniformizer_isUniformizer K))
        1 (n + 1) =
      standardLubinTateNormSubgroup
        (standardLocalFieldUniformizer_isUniformizer K) n := by
  apply subgroup_eq_of_le_of_index_eq_of_ne_zero
  · exact
      standardLubinTateUniformizerPrincipalSubgroup_le_normSubgroup
        K (standardLocalFieldUniformizer_isUniformizer K) n
  · rw [
      standardLubinTateCanonicalUniformizerPrincipalSubgroup_index,
      standardLubinTateCanonicalNormSubgroup_index]
  · rw [standardLubinTateCanonicalUniformizerPrincipalSubgroup_index]
    have hq : 1 < Nat.card 𝓀[K] := Finite.one_lt_card
    exact
      Nat.ne_of_gt
        (Nat.mul_pos
          (Nat.sub_pos_of_lt hq)
          (Nat.pow_pos (Nat.zero_lt_one.trans hq)))

/-- With the normalized positive-valuation convention, the same norm
subgroup is generated by the inverse canonical uniformizer and
`U_K^(n+1)`. -/
theorem
    standardLubinTateCanonicalNormSubgroup_eq_normalizedUniformizerPrincipalSubgroup
    (n : ℕ) :
    standardLubinTateNormSubgroup
        (standardLocalFieldUniformizer_isUniformizer K) n =
      LocalFieldTheory.uniformizerPrincipalSubgroup K
        (inverseIntegerRingUniformizerFieldUnit K) 1 (n + 1) := by
  rw [
    ←
      standardLubinTateCanonicalUniformizerPrincipalSubgroup_eq_normSubgroup
        K n]
  simp only [
    LocalFieldTheory.uniformizerPrincipalSubgroup,
    standardLubinTateCanonicalBaseUniformizerUnit_eq_integerRingUniformizerFieldUnit,
    inverseIntegerRingUniformizerFieldUnit,
    pow_one,
    Subgroup.zpowers_inv]

end LubinTate

end
