import Mathlib.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Hilbert90
import GaloisCohomology.Cyclic.TateComparison

set_option autoImplicit false

namespace CyclicCohomology

/-!
# Cyclic Tate low-degree boundary

For a finite cyclic group generated by `g`, mathlib computes odd group
cohomology using `Rep.FiniteCyclicGroup.subCompNormHom A g`.  The canonical
boundary comparison identifies that short-complex homology with
`tateCohomology A (-1)`.

This file applies that comparison to unit representations.  The resulting
objects are mathlib's Tate cohomology objects directly; no parallel
low-degree model is introduced.
-/

noncomputable section

open CategoryTheory

private theorem zpowers_eq_top_of_forall_mem_zpowers {G : Type} [Group G] (g : G)
    (hg : ∀ x : G, x ∈ Subgroup.zpowers g) :
    Subgroup.zpowers g = ⊤ := by
  ext x
  constructor
  · intro _
    exact Subgroup.mem_top x
  · intro _
    exact hg x

private theorem isCyclic_of_forall_mem_zpowers {G : Type} [Group G] (g : G)
    (hg : ∀ x : G, x ∈ Subgroup.zpowers g) :
    IsCyclic G := by
  rw [isCyclic_iff_exists_zpowers_eq_top]
  exact ⟨g, zpowers_eq_top_of_forall_mem_zpowers g hg⟩

/-- Low-degree Tate periodicity in degree one:
for a finite cyclic group, `H¹(G,A)` is canonically isomorphic to mathlib's
degree-minus-one Tate cohomology. -/
noncomputable def cyclic_H1_iso_HminusOne {k G : Type} [CommRing k] [Group G]
    [Fintype G] (A : Rep k G) (g : G)
    (hg : ∀ x : G, x ∈ Subgroup.zpowers g) :
    groupCohomology A 1 ≅ tateCohomology A (-1) := by
  letI : IsCyclic G := isCyclic_of_forall_mem_zpowers g hg
  letI : CommGroup G := IsCyclic.commGroup (α := G)
  exact Rep.FiniteCyclicGroup.groupCohomologyIsoOdd A g hg 1 (by decide) ≪≫
    (TateCohomology.isoFiniteCyclicNegOne A g hg).symm

/-- The cyclic low-degree comparison for the unit representation. -/
noncomputable def unitsH1IsoTateHminusOne (K L : Type) [Field K] [Field L]
    [Algebra K L] [FiniteDimensional K L] (g : Gal(L / K))
    (hg : ∀ x : Gal(L / K), x ∈ Subgroup.zpowers g) :
    groupCohomology.H1 (Rep.ofAlgebraAutOnUnits K L) ≅
      tateCohomology (Rep.ofAlgebraAutOnUnits K L) (-1) :=
  cyclic_H1_iso_HminusOne (Rep.ofAlgebraAutOnUnits K L) g hg

/-- Hilbert 90 transported through the cyclic `H¹ ≅ H^{-1}` comparison.
This is low-degree cyclic Tate cohomology for the coefficient group `Lˣ`: the vanishing of
`H¹(G,Lˣ)` gives the vanishing of `H^{-1}(G,Lˣ)`. -/
theorem hilbert90_unitsTateHminusOne_isZero (K L : Type) [Field K]
    [Field L] [Algebra K L] [FiniteDimensional K L] (g : Gal(L / K))
    (hg : ∀ x : Gal(L / K), x ∈ Subgroup.zpowers g) :
    CategoryTheory.Limits.IsZero
      (tateCohomology (Rep.ofAlgebraAutOnUnits K L) (-1)) := by
  have hzero :
      CategoryTheory.Limits.IsZero
        (groupCohomology.H1 (Rep.ofAlgebraAutOnUnits K L)) := by
    let _ := groupCohomology.H1ofAutOnUnitsUnique K L
    exact ModuleCat.isZero_of_subsingleton _
  exact hzero.of_iso
    (unitsH1IsoTateHminusOne K L g hg).symm

end
end CyclicCohomology
