/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.IdealPowerRadicalExact
import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed

set_option autoImplicit false
/-!
# The ideal radical over a cyclotomic base

For a number field `F` and a prime `p`, this file chooses a primitive `p`-th root in
`AlgebraicClosure F`, names `F(μ_p)`, and maps the empty-support ideal `p`-power radical into an
admissible Kummer subgroup over that cyclotomic base.  Its restricted radical quotient is finite,
by a source-proved surjection from the base-field ideal radical quotient.
-/

open scoped NumberField

namespace ClassFieldTower.Martinet.Shafarevich

open NumberField
open KummerTheory

noncomputable section

variable (F : Type*) [Field F] [NumberField F]
variable (p : ℕ) (hp : p.Prime)

/-- A chosen primitive `p`-th root of unity in the fixed algebraic closure. -/
noncomputable def idealRadicalPrimitiveRoot : AlgebraicClosure F := by
  let _ : NeZero (p : F) := ⟨by exact_mod_cast hp.ne_zero⟩
  exact Classical.choose
    (HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure F) p)

theorem idealRadicalPrimitiveRoot_isPrimitiveRoot :
    IsPrimitiveRoot (idealRadicalPrimitiveRoot F p hp) p := by
  let _ : NeZero (p : F) := ⟨by exact_mod_cast hp.ne_zero⟩
  exact Classical.choose_spec
    (HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure F) p)

/-- The cyclotomic base `F(μ_p)` inside `AlgebraicClosure F`. -/
noncomputable def IdealRadicalCyclotomicBase :
    IntermediateField F (AlgebraicClosure F) :=
  IntermediateField.adjoin F {idealRadicalPrimitiveRoot F p hp}

theorem finiteDimensional_idealRadicalCyclotomicBase :
    FiniteDimensional F (IdealRadicalCyclotomicBase F p hp) := by
  let : NeZero p := ⟨hp.ne_zero⟩
  exact IntermediateField.adjoin.finiteDimensional
    ((idealRadicalPrimitiveRoot_isPrimitiveRoot F p hp).isIntegral hp.pos).tower_top

/-- The named cyclotomic base contains a primitive `p`-th root. -/
theorem idealRadicalCyclotomicBase_primitiveRoots_nonempty :
    (primitiveRoots p (IdealRadicalCyclotomicBase F p hp)).Nonempty := by
  let zeta : IdealRadicalCyclotomicBase F p hp :=
    ⟨idealRadicalPrimitiveRoot F p hp,
      IntermediateField.subset_adjoin F
        {idealRadicalPrimitiveRoot F p hp} (Set.mem_singleton _)⟩
  refine ⟨zeta, (mem_primitiveRoots hp.pos).2 ?_⟩
  let hroot := idealRadicalPrimitiveRoot_isPrimitiveRoot F p hp
  refine ⟨?_, ?_⟩
  · exact Subtype.ext hroot.pow_eq_one
  · intro l hl
    apply hroot.dvd_of_pow_eq_one l
    exact congrArg Subtype.val hl

/-- Map the base-field ideal radical into the unit group of `F(μ_p)`. -/
noncomputable def idealRadicalToCyclotomicBase :
    (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos)).1 →*
      (IdealRadicalCyclotomicBase F p hp)ˣ :=
  (Units.map
    (algebraMap F (IdealRadicalCyclotomicBase F p hp)).toMonoidHom).comp
      (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos)).1.subtype

/-- The Kummer subgroup over `F(μ_p)` generated by the mapped ideal radical and all ambient
`p`-th powers. -/
noncomputable def idealRadicalCyclotomicKummerSubgroup :
    KummerSubgroup (IdealRadicalCyclotomicBase F p hp) (p.toPNat hp.pos) :=
  ⟨MonoidHom.range (idealRadicalToCyclotomicBase F p hp) ⊔
      unitNthPowersSubgroup (IdealRadicalCyclotomicBase F p hp) (p.toPNat hp.pos),
    le_sup_right⟩

/-- The base-field ideal radical, with codomain restricted to the cyclotomic Kummer subgroup. -/
noncomputable def idealRadicalToCyclotomicKummerSubgroup :
    (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos)).1 →*
      (idealRadicalCyclotomicKummerSubgroup F p hp).1 :=
  (idealRadicalToCyclotomicBase F p hp).codRestrict
    (idealRadicalCyclotomicKummerSubgroup F p hp).1 fun a ↦
      (le_sup_left : MonoidHom.range (idealRadicalToCyclotomicBase F p hp) ≤
        (idealRadicalCyclotomicKummerSubgroup F p hp).1) ⟨a, rfl⟩

private noncomputable def idealRadicalToCyclotomicQuotientRaw :
    (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos)).1 →*
      RestrictedRadicalQuotient (p.toPNat hp.pos)
        (idealRadicalCyclotomicKummerSubgroup F p hp) :=
  (restrictedRadicalQuotientMk (p.toPNat hp.pos)
    (idealRadicalCyclotomicKummerSubgroup F p hp)).comp
      (idealRadicalToCyclotomicKummerSubgroup F p hp)

/-- The induced map from the base-field ideal radical quotient to the cyclotomic Kummer
quotient. -/
noncomputable def idealRadicalQuotientToCyclotomicQuotient :
    IdealNthPowerRadicalQuotient F (p.toPNat hp.pos) →*
      RestrictedRadicalQuotient (p.toPNat hp.pos)
        (idealRadicalCyclotomicKummerSubgroup F p hp) := by
  apply restrictedRadicalQuotientLift (p.toPNat hp.pos)
    (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos))
    (idealRadicalToCyclotomicQuotientRaw F p hp)
  intro a ha
  rw [MonoidHom.mem_ker]
  change restrictedRadicalQuotientMk (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp)
        (idealRadicalToCyclotomicKummerSubgroup F p hp a) = 1
  rw [restrictedRadicalQuotientMk_eq_one_iff]
  obtain ⟨b, hb⟩ :=
    (mem_restrictedNthPowersSubgroup_iff (p.toPNat hp.pos)
      (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos))).1 ha
  apply (mem_restrictedNthPowersSubgroup_iff (p.toPNat hp.pos)
    (idealRadicalCyclotomicKummerSubgroup F p hp)).2
  refine ⟨Units.map
    (algebraMap F (IdealRadicalCyclotomicBase F p hp)).toMonoidHom b, ?_⟩
  change (Units.map
      (algebraMap F (IdealRadicalCyclotomicBase F p hp)).toMonoidHom b) ^ p =
    Units.map
      (algebraMap F (IdealRadicalCyclotomicBase F p hp)).toMonoidHom a.1
  rw [← map_pow]
  exact congrArg
    (Units.map
      (algebraMap F (IdealRadicalCyclotomicBase F p hp)).toMonoidHom) hb

/-- Every cyclotomic Kummer class is represented by a mapped base-field ideal radical class. -/
theorem idealRadicalQuotientToCyclotomicQuotient_surjective :
    Function.Surjective (idealRadicalQuotientToCyclotomicQuotient F p hp) := by
  intro q
  obtain ⟨d, rfl⟩ := restrictedRadicalQuotientMk_surjective
    (p.toPNat hp.pos) (idealRadicalCyclotomicKummerSubgroup F p hp) q
  obtain ⟨x, hx, y, hy, hxy⟩ := Subgroup.mem_sup.mp d.2
  obtain ⟨a, rfl⟩ := hx
  let aDelta := idealRadicalToCyclotomicKummerSubgroup F p hp a
  let yDelta : (idealRadicalCyclotomicKummerSubgroup F p hp).1 :=
    ⟨y, (le_sup_right : unitNthPowersSubgroup
      (IdealRadicalCyclotomicBase F p hp) (p.toPNat hp.pos) ≤
        (idealRadicalCyclotomicKummerSubgroup F p hp).1) hy⟩
  have hyOne : restrictedRadicalQuotientMk (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp) yDelta = 1 := by
    apply (restrictedRadicalQuotientMk_eq_one_iff (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp) yDelta).2
    exact (mem_restrictedNthPowersSubgroup_iff (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp)).2 hy
  refine ⟨restrictedRadicalQuotientMk (p.toPNat hp.pos)
    (idealNthPowerRadicalKummerSubgroup F (p.toPNat hp.pos)) a, ?_⟩
  rw [idealRadicalQuotientToCyclotomicQuotient,
    restrictedRadicalQuotientLift_mk]
  change restrictedRadicalQuotientMk (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp) aDelta =
    restrictedRadicalQuotientMk (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp) d
  calc
    _ = restrictedRadicalQuotientMk (p.toPNat hp.pos)
        (idealRadicalCyclotomicKummerSubgroup F p hp) (aDelta * yDelta) := by
      rw [map_mul, hyOne, mul_one]
    _ = _ := congrArg _ (Subtype.ext hxy)

/-- The cyclotomic Kummer quotient generated by the ideal radical is finite. -/
theorem finite_idealRadicalCyclotomicRestrictedQuotient :
    Finite (RestrictedRadicalQuotient (p.toPNat hp.pos)
      (idealRadicalCyclotomicKummerSubgroup F p hp)) :=
  Finite.of_surjective (idealRadicalQuotientToCyclotomicQuotient F p hp)
    (idealRadicalQuotientToCyclotomicQuotient_surjective F p hp)

end

end ClassFieldTower.Martinet.Shafarevich
