import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.PClassGroup
import GaloisCohomology.Kummer.Concrete.RestrictedFinite
import ClassFieldTheory.AlgebraicNumberTheory.Idele.ClassGroup.Core
import ValuedFieldTheory.LocalField.GroupTheory.PowerIndex

set_option autoImplicit false
/-!
# The empty-support Shafarevich radical

This file defines the field elements whose principal fractional ideals are
positive powers, quotients them by field powers, and maps the resulting
radical onto the matching torsion subgroup of the ordinary ideal class group.
-/

open scoped NumberField nonZeroDivisors
open NumberField IsDedekindDomain

noncomputable section

namespace ClassFieldTower.Martinet.Shafarevich

open ClassFieldTower.Martinet
open KummerTheory

variable (K : Type*) [Field K] [NumberField K]

/-- The field elements whose principal fractional ideal is an `n`-th power. -/
def idealNthPowerRadicalKummerSubgroup (n : ℕ+) :
    KummerSubgroup K n :=
  ⟨Subgroup.comap (toPrincipalIdeal (𝓞 K) K)
      (powMonoidHom (n : ℕ) : FractionalIdealGroup K →*
        FractionalIdealGroup K).range,
    by
      intro a ha
      obtain ⟨b, rfl⟩ := (mem_unitNthPowersSubgroup_iff n).mp ha
      exact ⟨toPrincipalIdeal (𝓞 K) K b, by simp⟩⟩

/-- Membership in the ideal-power radical is exactly the existence of an
`n`-th root for the principal fractional ideal. -/
theorem mem_idealNthPowerRadicalKummerSubgroup_iff
    (n : ℕ+) (a : Kˣ) :
    a ∈ (idealNthPowerRadicalKummerSubgroup K n).1 ↔
      ∃ I : FractionalIdealGroup K,
        I ^ (n : ℕ) = toPrincipalIdeal (𝓞 K) K a :=
  Iff.rfl

/-- The empty-support Shafarevich radical `V_{K,n}/K×^n`. -/
abbrev IdealNthPowerRadicalQuotient (n : ℕ+) :=
  RestrictedRadicalQuotient n (idealNthPowerRadicalKummerSubgroup K n)

private theorem fractionalIdealGroup_pow_injective (n : ℕ+) :
    Function.Injective
      (fun I : FractionalIdealGroup K ↦ I ^ (n : ℕ)) := by
  intro I J hIJ
  apply FractionalIdealGroup.ext_count
  intro v
  have hcount := congrArg
    (fun L : FractionalIdealGroup K ↦
      FractionalIdeal.count K v
        (L : FractionalIdeal (nonZeroDivisors (𝓞 K)) K)) hIJ
  have hcount' :
      FractionalIdeal.count K v
          ((I : FractionalIdeal (nonZeroDivisors (𝓞 K)) K) ^ (n : ℕ)) =
        FractionalIdeal.count K v
          ((J : FractionalIdeal (nonZeroDivisors (𝓞 K)) K) ^ (n : ℕ)) := by
    simpa only [Units.val_pow_eq_pow_val] using hcount
  rw [FractionalIdeal.count_pow, FractionalIdeal.count_pow] at hcount'
  exact mul_left_cancel₀ (by exact_mod_cast n.ne_zero) hcount'

/-- The unique fractional-ideal `n`-th root of a radical element's
principal ideal. -/
noncomputable def idealNthRoot
    (n : ℕ+)
    (a : (idealNthPowerRadicalKummerSubgroup K n).1) :
    FractionalIdealGroup K :=
  Classical.choose
    ((MonoidHom.mem_range (G := FractionalIdealGroup K)).mp a.property)

@[simp]
theorem idealNthRoot_pow
    (n : ℕ+)
    (a : (idealNthPowerRadicalKummerSubgroup K n).1) :
    idealNthRoot K n a ^ (n : ℕ) =
      toPrincipalIdeal (𝓞 K) K a.1 := by
  unfold idealNthRoot
  exact Classical.choose_spec
    ((MonoidHom.mem_range (G := FractionalIdealGroup K)).mp a.property)

/-- The chosen ideal root agrees with any ideal having the required power. -/
theorem idealNthRoot_eq_of_pow_eq
    (n : ℕ+)
    (a : (idealNthPowerRadicalKummerSubgroup K n).1)
    (I : FractionalIdealGroup K)
    (hI : I ^ (n : ℕ) = toPrincipalIdeal (𝓞 K) K a.1) :
    idealNthRoot K n a = I := by
  apply fractionalIdealGroup_pow_injective K n
  change idealNthRoot K n a ^ (n : ℕ) = I ^ (n : ℕ)
  rw [idealNthRoot_pow K n a, hI]

/-- Taking the unique ideal root is multiplicative. -/
noncomputable def idealNthRootHom (n : ℕ+) :
    (idealNthPowerRadicalKummerSubgroup K n).1 →*
      FractionalIdealGroup K where
  toFun := idealNthRoot K n
  map_one' := by
    apply idealNthRoot_eq_of_pow_eq K n 1 1
    simp
  map_mul' a b := by
    apply idealNthRoot_eq_of_pow_eq K n (a * b)
      (idealNthRoot K n a * idealNthRoot K n b)
    rw [mul_pow, idealNthRoot_pow K n a, idealNthRoot_pow K n b]
    change
      toPrincipalIdeal (𝓞 K) K a.1 *
          toPrincipalIdeal (𝓞 K) K b.1 =
        toPrincipalIdeal (𝓞 K) K (a.1 * b.1)
    exact (map_mul (toPrincipalIdeal (𝓞 K) K) a.1 b.1).symm

/-- The `n`-torsion subgroup of the ordinary ideal class group. -/
abbrev ClassGroupNthPowerTorsion (n : ℕ) :=
  (powMonoidHom n : ClassGroup (𝓞 K) →* ClassGroup (𝓞 K)).ker

omit [NumberField K] in
/-- For the abelian ideal class group, the subgroup generated by `n`-th
powers is exactly the range of the power endomorphism. -/
theorem pClassPowerSubgroup_eq_nthPowerRange (n : ℕ) :
    pClassPowerSubgroup K n =
      (powMonoidHom n : ClassGroup (𝓞 K) →* ClassGroup (𝓞 K)).range := by
  apply le_antisymm
  · rw [pClassPowerSubgroup, ClassFieldTower.ProP.powerSubgroup,
      Subgroup.closure_le]
    rintro x ⟨y, rfl⟩
    exact ⟨y, rfl⟩
  · rintro x ⟨y, rfl⟩
    exact ClassFieldTower.ProP.pow_mem_powerSubgroup n
      (ClassGroup (𝓞 K)) y

/-- The `n`-class quotient is the cokernel of the class-group power map. -/
noncomputable def pClassGroupEquivNthPowerQuotient (n : ℕ) :
    PClassGroup K n ≃*
      ClassGroup (𝓞 K) ⧸
        (powMonoidHom n : ClassGroup (𝓞 K) →*
          ClassGroup (𝓞 K)).range :=
  QuotientGroup.quotientMulEquivOfEq
    (pClassPowerSubgroup_eq_nthPowerRange K n)

/-- The class-group `n`-torsion and the `n`-class quotient have equal
cardinality.  This avoids asserting a nonexistent canonical map between
them. -/
theorem card_classGroupNthPowerTorsion_eq_card_pClassGroup (n : ℕ) :
    Nat.card (ClassGroupNthPowerTorsion K n) =
      Nat.card (PClassGroup K n) := by
  rw [← LocalFieldTheory.card_nthPowerQuotient_eq_nthPowerKernel
    (G := ClassGroup (𝓞 K)) n]
  exact Nat.card_congr (pClassGroupEquivNthPowerQuotient K n).symm.toEquiv

/-- Send a radical element to the class of the unique ideal root of its
principal ideal. -/
noncomputable def idealNthRootClassHom (n : ℕ+) :
    (idealNthPowerRadicalKummerSubgroup K n).1 →*
      ClassGroup (𝓞 K) :=
  (ClassGroup.mk K).comp (idealNthRootHom K n)

/-- The ideal-root class is killed by `n`. -/
theorem idealNthRootClassHom_mem_torsion
    (n : ℕ+)
    (a : (idealNthPowerRadicalKummerSubgroup K n).1) :
    idealNthRootClassHom K n a ∈ ClassGroupNthPowerTorsion K (n : ℕ) := by
  rw [MonoidHom.mem_ker]
  change (ClassGroup.mk K (idealNthRoot K n a)) ^ (n : ℕ) = 1
  rw [← map_pow, idealNthRoot_pow K n a]
  exact (IdeleGroup.classGroup_mk_eq_one_iff _).2 ⟨a.1, rfl⟩

/-- The ideal-root class map with codomain restricted to class-group
`n`-torsion. -/
noncomputable def idealNthRootClassTorsionHom (n : ℕ+) :
    (idealNthPowerRadicalKummerSubgroup K n).1 →*
      ClassGroupNthPowerTorsion K (n : ℕ) :=
  (idealNthRootClassHom K n).codRestrict
    (ClassGroupNthPowerTorsion K (n : ℕ))
    (idealNthRootClassHom_mem_torsion K n)

private theorem restrictedNthPowers_le_ker_idealNthRootClassTorsionHom
    (n : ℕ+) :
    restrictedNthPowersSubgroup n
        (idealNthPowerRadicalKummerSubgroup K n) ≤
      MonoidHom.ker (idealNthRootClassTorsionHom K n) := by
  intro a ha
  rw [MonoidHom.mem_ker]
  obtain ⟨b, hb⟩ :=
    (mem_restrictedNthPowersSubgroup_iff n
      (idealNthPowerRadicalKummerSubgroup K n)).mp ha
  apply Subtype.ext
  change ClassGroup.mk K (idealNthRoot K n a) = 1
  rw [idealNthRoot_eq_of_pow_eq K n a (toPrincipalIdeal (𝓞 K) K b)]
  · exact (IdeleGroup.classGroup_mk_eq_one_iff _).2 ⟨b, rfl⟩
  · rw [← map_pow, hb]

/-- The canonical ideal-root class map from the Shafarevich radical. -/
noncomputable def idealNthPowerRadicalToClassTorsion
    (n : ℕ+) :
    IdealNthPowerRadicalQuotient K n →*
      ClassGroupNthPowerTorsion K (n : ℕ) :=
  restrictedRadicalQuotientLift n
    (idealNthPowerRadicalKummerSubgroup K n)
    (idealNthRootClassTorsionHom K n)
    (restrictedNthPowers_le_ker_idealNthRootClassTorsionHom K n)

@[simp]
theorem idealNthPowerRadicalToClassTorsion_mk
    (n : ℕ+)
    (a : (idealNthPowerRadicalKummerSubgroup K n).1) :
    idealNthPowerRadicalToClassTorsion K n
        (restrictedRadicalQuotientMk n
          (idealNthPowerRadicalKummerSubgroup K n) a) =
      idealNthRootClassTorsionHom K n a :=
  restrictedRadicalQuotientLift_mk n
    (idealNthPowerRadicalKummerSubgroup K n)
    (idealNthRootClassTorsionHom K n)
    (restrictedNthPowers_le_ker_idealNthRootClassTorsionHom K n) a

/-- Every `n`-torsion ideal class is represented by an ideal whose `n`-th
power supplies a radical element. -/
theorem idealNthPowerRadicalToClassTorsion_surjective
    (n : ℕ+) :
    Function.Surjective (idealNthPowerRadicalToClassTorsion K n) := by
  intro c
  let motive : ClassGroup (𝓞 K) → Prop := fun d ↦
    ∀ hd : d ^ (n : ℕ) = 1,
      ∃ q : IdealNthPowerRadicalQuotient K n,
        idealNthPowerRadicalToClassTorsion K n q = ⟨d, hd⟩
  suffices h : motive c.1 by
    exact h c.property
  refine ClassGroup.induction K (P := motive) ?_ c.1
  intro I
  dsimp only [motive]
  intro hIpow
  have hprincipal : ClassGroup.mk K (I ^ (n : ℕ)) = 1 := by
    rw [map_pow, hIpow]
  obtain ⟨a, ha⟩ :=
    (IdeleGroup.classGroup_mk_eq_one_iff (I ^ (n : ℕ))).mp hprincipal
  let aRad : (idealNthPowerRadicalKummerSubgroup K n).1 :=
    ⟨a, ⟨I, ha.symm⟩⟩
  refine ⟨restrictedRadicalQuotientMk n
      (idealNthPowerRadicalKummerSubgroup K n) aRad, ?_⟩
  rw [idealNthPowerRadicalToClassTorsion_mk]
  apply Subtype.ext
  change ClassGroup.mk K (idealNthRoot K n aRad) = ClassGroup.mk K I
  rw [idealNthRoot_eq_of_pow_eq K n aRad I ha.symm]

end ClassFieldTower.Martinet.Shafarevich
