import ProCGroups.ProP.FinitePGroupMaximal
import ProCGroups.ProP.FrattiniQuotient
import Mathlib.Algebra.Field.ZMod
import Mathlib.Algebra.Module.ZMod
import Mathlib.LinearAlgebra.Basis.VectorSpace
import ProCGroups.Frattini

set_option autoImplicit false
/-!
# The finite p-group Frattini inclusion

For a finite Hausdorff `p`-group, the Frattini subgroup is exactly the closed
subgroup generated by `p`th powers and commutators.  The forward inclusion
uses maximal subgroups.  For the reverse inclusion, the power--commutator
quotient is an elementary abelian `p`-group, so a vector-space complement and
the nongenerating property force its Frattini subgroup to be trivial.
-/

open Set
open scoped IsMulCommutative

namespace ClassFieldTower.ProP

universe u

/-- The subgroup generated by `p`th powers lies in every maximal subgroup of a finite `p`-group. -/
theorem powerSubgroup_le_isCoatom_of_isPGroup
    {p : ℕ} {G : Type u} [Group G] [Finite G] [Fact (Nat.Prime p)]
    (hG : IsPGroup p G) {M : Subgroup G} (hM : IsCoatom M) :
    powerSubgroup p G ≤ M := by
  let _ : M.Normal := isCoatom_normal_of_isPGroup hG hM
  have hcard : Nat.card (G ⧸ M) = p :=
    card_quotient_eq_prime_of_isCoatom_isPGroup hG hM
  rw [powerSubgroup, Subgroup.closure_le]
  rintro _ ⟨g, rfl⟩
  apply (QuotientGroup.eq_one_iff (N := M) (g ^ p)).mp
  change (QuotientGroup.mk' M) (g ^ p) = 1
  rw [map_pow, ← hcard, pow_card_eq_one']

/-- The commutator subgroup lies in every maximal subgroup of a finite `p`-group. -/
theorem commutator_le_isCoatom_of_isPGroup
    {p : ℕ} {G : Type u} [Group G] [Finite G] [Fact (Nat.Prime p)]
    (hG : IsPGroup p G) {M : Subgroup G} (hM : IsCoatom M) :
    commutator G ≤ M := by
  let _ : M.Normal := isCoatom_normal_of_isPGroup hG hM
  let : IsCyclic (G ⧸ M) := quotient_isCyclic_of_isCoatom hM
  exact Subgroup.Normal.quotient_commutative_iff_commutator_le.mp inferInstance

/-- The closed power--commutator subgroup lies in every maximal subgroup of a finite `p`-group. -/
theorem closedPowerCommutator_le_isCoatom_of_isPGroup
    {p : ℕ} {G : Type u} [TopologicalSpace G] [Group G] [IsTopologicalGroup G]
    [T1Space G] [Finite G] [Fact (Nat.Prime p)]
    (hG : IsPGroup p G) {M : Subgroup G} (hM : IsCoatom M) :
    closedPowerCommutator p G ≤ M := by
  rw [closedPowerCommutator]
  apply Subgroup.topologicalClosure_minimal
  · exact sup_le (powerSubgroup_le_isCoatom_of_isPGroup hG hM)
      (commutator_le_isCoatom_of_isPGroup hG hM)
  · exact (M : Set G).toFinite.isClosed

/-- In a finite Hausdorff `p`-group, the closed power--commutator subgroup lies in the Frattini
subgroup. -/
theorem closedPowerCommutator_le_frattini_of_isPGroup
    {p : ℕ} {G : Type u} [TopologicalSpace G] [Group G] [IsTopologicalGroup G]
    [T1Space G] [Finite G] [Fact (Nat.Prime p)]
    (hG : IsPGroup p G) :
    closedPowerCommutator p G ≤ frattini G := by
  rw [frattini, Order.radical]
  refine le_iInf fun M => le_iInf fun hM => ?_
  exact closedPowerCommutator_le_isCoatom_of_isPGroup hG hM

/-- The Frattini subgroup of a finite power--commutator quotient is trivial. -/
theorem powerCommutatorQuotient_frattini_eq_bot
    {p : ℕ} {G : Type u} [TopologicalSpace G] [Group G] [IsTopologicalGroup G]
    [T1Space G] [Finite G] [Fact (Nat.Prime p)] :
    letI : (closedPowerCommutator p G).Normal :=
      closedPowerCommutator_normal p G
    frattini (powerCommutatorQuotient p G) = ⊥ := by
  let _ : (closedPowerCommutator p G).Normal :=
    closedPowerCommutator_normal p G
  let : IsMulCommutative (powerCommutatorQuotient p G) :=
    powerCommutatorQuotient_isMulCommutative p G
  have hpow (x : Additive (powerCommutatorQuotient p G)) : p • x = 0 := by
    change (Additive.toMul x) ^ p = 1
    exact powerCommutatorQuotient_pow_eq_one p G (Additive.toMul x)
  let : Module (ZMod p) (Additive (powerCommutatorQuotient p G)) :=
    AddCommGroup.zmodModule hpow
  let Fadd : AddSubgroup (Additive (powerCommutatorQuotient p G)) :=
    Subgroup.toAddSubgroup (frattini (powerCommutatorQuotient p G))
  let Fmod : Submodule (ZMod p) (Additive (powerCommutatorQuotient p G)) :=
    AddSubgroup.toZModSubmodule p Fadd
  obtain ⟨Kmod, hKmod⟩ := Fmod.exists_isCompl
  obtain ⟨hdisjmod, hcodisjmod⟩ := hKmod
  let Kadd : AddSubgroup (Additive (powerCommutatorQuotient p G)) :=
    Kmod.toAddSubgroup
  let K : Subgroup (powerCommutatorQuotient p G) :=
    AddSubgroup.toSubgroup' Kadd
  have hsup : frattini (powerCommutatorQuotient p G) ⊔ K = ⊤ := by
    apply top_unique
    intro x _
    obtain ⟨a, b, ha, hb, hab⟩ :=
      Submodule.codisjoint_iff_exists_add_eq.mp hcodisjmod (Additive.ofMul x)
    have haF : Additive.toMul a ∈ frattini (powerCommutatorQuotient p G) := by
      simpa [Fmod, Fadd] using ha
    have hbK : Additive.toMul b ∈ K := by
      simpa [K, Kadd] using hb
    change Additive.toMul a * Additive.toMul b = x at hab
    rw [← hab]
    exact Subgroup.mul_mem _
      ((le_sup_left : frattini (powerCommutatorQuotient p G) ≤
        frattini (powerCommutatorQuotient p G) ⊔ K) haF)
      ((le_sup_right : K ≤ frattini (powerCommutatorQuotient p G) ⊔ K) hbK)
  have hKtop : K = ⊤ :=
    frattini_nongenerating (by simpa [sup_comm] using hsup)
  rw [Subgroup.eq_bot_iff_forall]
  intro x hx
  have hxK : x ∈ K := by rw [hKtop]; exact Subgroup.mem_top x
  have hz : Additive.ofMul x = 0 :=
    (Submodule.disjoint_def.mp hdisjmod) (Additive.ofMul x)
      (by simpa [Fmod, Fadd] using hx)
      (by simpa [K, Kadd] using hxK)
  change x = 1 at hz
  exact hz

/-- For a finite Hausdorff group, its Frattini subgroup lies in the closed subgroup generated by
`p`th powers and commutators. -/
theorem frattini_le_closedPowerCommutator_of_finite
    {p : ℕ} {G : Type u} [TopologicalSpace G] [Group G] [IsTopologicalGroup G]
    [T1Space G] [Finite G] [Fact (Nat.Prime p)] :
    frattini G ≤ closedPowerCommutator p G := by
  let _ : (closedPowerCommutator p G).Normal :=
    closedPowerCommutator_normal p G
  have hfrattini :=
    frattini_le_comap_frattini_of_surjective
      (powerCommutatorQuotientMk_surjective p G)
  rw [powerCommutatorQuotient_frattini_eq_bot] at hfrattini
  intro g hg
  have hgq := hfrattini hg
  change (powerCommutatorQuotientMk p G) g = 1 at hgq
  exact (QuotientGroup.eq_one_iff (N := closedPowerCommutator p G) g).mp hgq

/-- The finite Burnside--Frattini formula for Hausdorff `p`-groups. -/
theorem frattini_eq_closedPowerCommutator_of_isPGroup
    {p : ℕ} {G : Type u} [TopologicalSpace G] [Group G] [IsTopologicalGroup G]
    [T1Space G] [Finite G] [Fact (Nat.Prime p)]
    (hG : IsPGroup p G) :
    frattini G = closedPowerCommutator p G := by
  apply le_antisymm
  · exact frattini_le_closedPowerCommutator_of_finite
  · exact closedPowerCommutator_le_frattini_of_isPGroup hG

end ClassFieldTower.ProP
