/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ProCGroups.ProP.FrattiniQuotient
import Mathlib.GroupTheory.Abelianization.Defs
import ProCGroups.Topologies.QuotientMaps

set_option autoImplicit false
/-!
# Universal property of the power--commutator quotient

The quotient by the closed subgroup generated by `p`th powers and commutators
is universal for continuous homomorphisms into commutative exponent-`p`
topological groups with closed identity.
-/

namespace ClassFieldTower.ProP

universe u v

section

variable {p : ℕ}
variable {G : Type u} {A : Type v}
variable [TopologicalSpace G] [Group G] [IsTopologicalGroup G]
variable [TopologicalSpace A] [CommGroup A] [T1Space A]

local instance : (closedPowerCommutator p G).Normal :=
  closedPowerCommutator_normal p G

/-- Universal lift from the power--commutator quotient to a commutative
exponent-`p` target. -/
noncomputable def powerCommutatorQuotientLift
    (f : G →ₜ* A) (hA : ∀ a : A, a ^ p = 1) :
    powerCommutatorQuotient p G →ₜ* A := by
  apply ProCGroups.QuotientGroup.liftₜ (closedPowerCommutator p G) f
  apply Subgroup.topologicalClosure_minimal
  · apply sup_le
    · rw [powerSubgroup, Subgroup.closure_le]
      rintro _ ⟨g, rfl⟩
      change f (g ^ p) = 1
      rw [map_pow, hA]
    · exact Abelianization.commutator_subset_ker f.toMonoidHom
  · change IsClosed (f ⁻¹' ({1} : Set A))
    exact isClosed_singleton.preimage f.continuous_toFun

@[simp] theorem powerCommutatorQuotientLift_apply_mk
    (f : G →ₜ* A) (hA : ∀ a : A, a ^ p = 1) (g : G) :
    powerCommutatorQuotientLift f hA (powerCommutatorQuotientMk p G g) = f g :=
  rfl

/-- The universal lift is the unique continuous homomorphism whose composite
with the quotient map is the given homomorphism. -/
theorem powerCommutatorQuotientLift_unique
    (f : G →ₜ* A) (hA : ∀ a : A, a ^ p = 1)
    (φ : powerCommutatorQuotient p G →ₜ* A)
    (hφ : φ.comp (powerCommutatorQuotientMk p G) = f) :
    φ = powerCommutatorQuotientLift f hA := by
  apply ContinuousMonoidHom.toMonoidHom_injective
  apply MonoidHom.ext
  intro q
  obtain ⟨g, rfl⟩ := powerCommutatorQuotientMk_surjective p G q
  change φ (powerCommutatorQuotientMk p G g) = f g
  exact DFunLike.congr_fun hφ g

end

end ClassFieldTower.ProP
