import ClassFieldTheory.LocalClassFieldTheory.Finite.LocalReciprocity.LocalResidueDatum
import ClassFieldTheory.LocalClassFieldTheory.Finite.LocalReciprocity.FiniteAbstractFixedField

set_option autoImplicit false

namespace LocalClassFieldTheory
open CyclicCohomology RamificationTheory ClassFormation

open LocalFieldTheory

/-!
# Finite local reciprocity: residue degree of a finite abstract field

This file compares the residue action used by localResidueDatum with the
same residue action after changing the ground field to the fixed field of a
closed subgroup.  The comparison is made on the common selected
residue field, so it also applies when the fixed field is not normal over the
original local field.
-/

noncomputable section

open scoped Pointwise ValuativeRel
open HilbertRamification.ValuationSubring
open Field.absoluteGaloisGroup

variable (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- The residue subfield inside the selected residue algebraic closure which
is generated by the residue field attached to the fixed field of `H`.

We use `adjoin` rather than imposing a scalar-tower instance between the two
intrinsic residue-action quotient presentations. -/
noncomputable def localAbstractFixedResidueIntermediateField
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    IntermediateField
      (decompositionResidueField K (localSeparableValuationSubring K))
      (selectedResidueField (localSeparableValuationSubring K)) := by
  let E := abstractFixedField K (SeparableClosure K) H
  let A := localSeparableValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let kE := decompositionResidueField E A
  exact IntermediateField.adjoin k
    (Set.range (algebraMap kE Omega))

/-- The canonical scalar structure on the selected fixed residue field.
Naming these instances keeps typeclass search from unfolding the fixed-field
and residue-action constructions in finite-dimensionality statements. -/
noncomputable local instance localAbstractFixedResidueIntermediateFieldAlgebra
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    Algebra
      (decompositionResidueField K (localSeparableValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) :=
  (localAbstractFixedResidueIntermediateField K H).algebra

noncomputable local instance localAbstractFixedResidueIntermediateFieldSMul
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    SMul
      (decompositionResidueField K (localSeparableValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) :=
  @Algebra.toSMul _ _ _ _
    (localAbstractFixedResidueIntermediateFieldAlgebra K H)

noncomputable local instance localAbstractFixedResidueIntermediateFieldModule
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    Module
      (decompositionResidueField K (localSeparableValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) :=
  @Algebra.toModule _ _ _ _
    (localAbstractFixedResidueIntermediateFieldAlgebra K H)

/-- Every automorphism over the fixed field preserves the selected extension
valuation.  This is the base-change form of the full decomposition-group
statement proved for `K`. -/
theorem localAbstractFixedDecompositionGroup_eq_top
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    decompositionGroup (abstractFixedField K (SeparableClosure K) H)
      (localSeparableValuationSubring K) = ⊤ := by
  let E := abstractFixedField K (SeparableClosure K) H
  let A := localSeparableValuationSubring K
  apply top_unique
  intro tau _htau
  let sigma : Gal(SeparableClosure K / K) := tau.restrictScalars K
  have hsigma : sigma • A = A := by
    change sigma ∈ decompositionGroup K A
    rw [localSeparableDecompositionGroup_eq_top K]
    exact Subgroup.mem_top sigma
  change tau • A = A
  exact hsigma

/-- Restricting the local residue action to `H` gives the same underlying
automorphism of the selected residue field as applying the residue-action map
over the fixed field of `H`. -/
theorem localAbstractFixedResidueAction_apply
    (H : ClosedSubgroup (Gal(SeparableClosure K / K)))
    (sigma : H.toSubgroup)
    (x : selectedResidueField (localSeparableValuationSubring K)) :
    localSeparableResidueAlgAction K sigma.1 x =
      residueAlgActionOfEqTop
        (abstractFixedField K (SeparableClosure K) H)
        (localSeparableValuationSubring K)
        (localAbstractFixedDecompositionGroup_eq_top K H)
        (abstractSubgroupEquivGaloisGroup K (SeparableClosure K) H sigma) x := by
  let A := localSeparableValuationSubring K
  obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective x
  change IsLocalRing.residue A
      ((toDecompositionGroupOfEqTop K A
        (localSeparableDecompositionGroup_eq_top K) sigma.1) • a) =
    IsLocalRing.residue A
      ((toDecompositionGroupOfEqTop
        (abstractFixedField K (SeparableClosure K) H) A
        (localAbstractFixedDecompositionGroup_eq_top K H)
        (abstractSubgroupEquivGaloisGroup K (SeparableClosure K) H sigma)) • a)
  congr 1

/-- The image of `H` under the local residue action is exactly the subgroup
fixing the residue subfield of its fixed field.  The reverse inclusion is the
surjectivity of the residue-action map after changing the base to that
fixed field. -/
theorem localAbstractFixedResidueAction_map_eq_fixingSubgroup
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    H.toSubgroup.map (localSeparableResidueAlgAction K).toMonoidHom =
      (localAbstractFixedResidueIntermediateField K H).fixingSubgroup := by
  let E := abstractFixedField K (SeparableClosure K) H
  let A := localSeparableValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let kE := decompositionResidueField E A
  let rhoK := localSeparableResidueAlgAction K
  let hE := localAbstractFixedDecompositionGroup_eq_top K H
  let rhoE := residueAlgActionOfEqTop E A hE
  let F := localAbstractFixedResidueIntermediateField K H
  ext tau
  constructor
  · rintro ⟨sigma, hsigma, rfl⟩
    let sigmaH : H.toSubgroup := ⟨sigma, hsigma⟩
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    let T : IntermediateField k Omega :=
      { carrier := {y | rhoK sigma y = y}
        zero_mem' := by simp
        one_mem' := by simp
        add_mem' := by
          intro y z hy hz
          change rhoK sigma y = y at hy
          change rhoK sigma z = z at hz
          change rhoK sigma (y + z) = y + z
          rw [map_add]
          exact congrArg₂ (fun a b : Omega => a + b) hy hz
        mul_mem' := by
          intro y z hy hz
          change rhoK sigma y = y at hy
          change rhoK sigma z = z at hz
          change rhoK sigma (y * z) = y * z
          rw [map_mul]
          exact congrArg₂ (fun a b : Omega => a * b) hy hz
        algebraMap_mem' := fun y => (rhoK sigma).commutes y
        inv_mem' := by
          intro y hy
          change rhoK sigma y = y at hy
          simp [hy] }
    have hrange : Set.range (algebraMap kE Omega) ⊆ T := by
      rintro y ⟨z, rfl⟩
      have hbase : rhoK sigma (algebraMap kE Omega z) =
          algebraMap kE Omega z := by
        rw [localAbstractFixedResidueAction_apply K H sigmaH]
        exact (rhoE (abstractSubgroupEquivGaloisGroup
          K (SeparableClosure K) H sigmaH)).commutes z
      change rhoK sigma (algebraMap kE Omega z) =
        algebraMap kE Omega z
      exact hbase
    have hFT : F ≤ T := by
      apply IntermediateField.adjoin_le_iff.mpr
      exact hrange
    have hxT : x ∈ T := hFT hx
    change rhoK sigma x = x
    change rhoK sigma x = x at hxT
    exact hxT
  · intro htau
    let tauE : Omega ≃ₐ[kE] Omega :=
      { tau.toRingEquiv with
        commutes' := fun z => by
          have hzF : algebraMap kE Omega z ∈ F := by
            apply IntermediateField.subset_adjoin
            exact ⟨z, rfl⟩
          exact (IntermediateField.mem_fixingSubgroup_iff F tau).mp
            htau (algebraMap kE Omega z) hzF }
    obtain ⟨sigmaE, hsigmaE⟩ :=
      residueAlgActionOfEqTop_surjective E A hE tauE
    let sigmaH : H.toSubgroup :=
      (abstractSubgroupEquivGaloisGroup K (SeparableClosure K) H).symm sigmaE
    refine ⟨sigmaH.1, sigmaH.2, ?_⟩
    apply AlgEquiv.ext
    intro x
    change localSeparableResidueAlgAction K sigmaH.1 x = tau x
    rw [localAbstractFixedResidueAction_apply K H sigmaH]
    have hsigmaH : abstractSubgroupEquivGaloisGroup
        K (SeparableClosure K) H sigmaH = sigmaE :=
      (abstractSubgroupEquivGaloisGroup
        K (SeparableClosure K) H).apply_symm_apply sigmaE
    rw [hsigmaH, hsigmaE]
    rfl

/-- The residue action of an element of `H` fixes the finite residue
subfield attached to the fixed field of `H`. -/
theorem localAbstractFixedResidueAction_mem_fixingSubgroup
    (H : ClosedSubgroup (Gal(SeparableClosure K / K)))
    (sigma : H.toSubgroup) :
    localSeparableResidueAlgAction K sigma.1 ∈
      (localAbstractFixedResidueIntermediateField K H).fixingSubgroup := by
  rw [← localAbstractFixedResidueAction_map_eq_fixingSubgroup K H]
  exact ⟨sigma.1, sigma.2, rfl⟩

/-- The residue action of `H`, with scalars restricted to the actual finite
residue subfield selected by `H` inside the common residue algebraic
closure. -/
noncomputable def localAbstractFixedResidueActionOverIntermediateField
    (H : ClosedSubgroup (Gal(SeparableClosure K / K))) :
    H.toSubgroup →*
      (selectedResidueField (localSeparableValuationSubring K) ≃ₐ[
        localAbstractFixedResidueIntermediateField K H]
        selectedResidueField (localSeparableValuationSubring K)) := by
  let F := localAbstractFixedResidueIntermediateField K H
  let rhoH : H.toSubgroup →*
      (selectedResidueField (localSeparableValuationSubring K) ≃ₐ[
        decompositionResidueField K (localSeparableValuationSubring K)]
        selectedResidueField (localSeparableValuationSubring K)) :=
    (localSeparableResidueAlgAction K).toMonoidHom.comp H.toSubgroup.subtype
  let rhoF : H.toSubgroup →* F.fixingSubgroup :=
    rhoH.codRestrict F.fixingSubgroup
      (localAbstractFixedResidueAction_mem_fixingSubgroup K H)
  exact
    (IntermediateField.fixingSubgroupEquiv F).toMonoidHom.comp rhoF

/-- Restricting residue scalars changes only the scalar-linearity proof,
not the underlying automorphism of the selected residue field. -/
@[simp]
theorem localAbstractFixedResidueActionOverIntermediateField_apply
    (H : ClosedSubgroup (Gal(SeparableClosure K / K)))
    (sigma : H.toSubgroup)
    (x : selectedResidueField (localSeparableValuationSubring K)) :
    localAbstractFixedResidueActionOverIntermediateField K H sigma x =
      localSeparableResidueAlgAction K sigma.1 x := by
  rfl

/-- A finite abstract field has a genuinely finite residue subfield inside
the selected residue algebraic closure.  Finiteness is deduced from the
finite index of `H`: surjectivity of the absolute residue action makes the
index of its image divide the index of `H`. -/
theorem localAbstractFixedResidueIntermediateField_finiteDimensional
    (H : ClosedSubgroup (Gal(SeparableClosure K / K)))
    [Finite
      ((baseField (Gal(SeparableClosure K / K))).toSubgroup ⧸
        extensionSubgroup
          (baseField (Gal(SeparableClosure K / K))) H
          (le_baseField H))] :
    FiniteDimensional
      (decompositionResidueField K (localSeparableValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) := by
  let G := Gal(SeparableClosure K / K)
  let A := localSeparableValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let rho := (localSeparableResidueAlgAction K).toMonoidHom
  let F := localAbstractFixedResidueIntermediateField K H
  let : Finite (G ⧸ H.toSubgroup) :=
    ambientQuotientFiniteOfAbstractFinite
      K (SeparableClosure K) H inferInstance
  have hHindex : H.toSubgroup.index ≠ 0 :=
    Subgroup.index_ne_zero_of_finite
  have hmapIndex : (H.toSubgroup.map rho).index ≠ 0 := by
    intro hzero
    have hdiv : (H.toSubgroup.map rho).index ∣ H.toSubgroup.index :=
      H.toSubgroup.index_map_dvd (localSeparableResidueAlgAction_surjective K)
    rw [hzero] at hdiv
    exact hHindex (eq_zero_of_zero_dvd hdiv)
  let : Finite
      ((Omega ≃ₐ[k] Omega) ⧸ H.toSubgroup.map rho) :=
    (Subgroup.index_ne_zero_iff_finite (H := H.toSubgroup.map rho)).mp
      hmapIndex
  have himage : H.toSubgroup.map rho = F.fixingSubgroup :=
    localAbstractFixedResidueAction_map_eq_fixingSubgroup K H
  let : Finite ((Omega ≃ₐ[k] Omega) ⧸ F.fixingSubgroup) := by
    rw [← himage]
    infer_instance
  let : Subgroup.FiniteIndex F.fixingSubgroup :=
    F.fixingSubgroup.finiteIndex_of_finite_quotient
  apply (InfiniteGalois.isOpen_iff_finite (K := Omega) F).1
  exact Subgroup.isOpen_of_isClosed_of_finiteIndex
    F.fixingSubgroup (InfiniteGalois.fixingSubgroup_isClosed F)

/-- The finite residue subfield, packaged in the form used by the intrinsic
finite-field residue datum. -/
noncomputable def localAbstractFixedResidueFiniteGaloisIntermediateField
    (H : ClosedSubgroup (Gal(SeparableClosure K / K)))
    [Finite
      ((baseField (Gal(SeparableClosure K / K))).toSubgroup ⧸
        extensionSubgroup
          (baseField (Gal(SeparableClosure K / K))) H
          (le_baseField H))] :
    FiniteGaloisIntermediateField
      (decompositionResidueField K (localSeparableValuationSubring K))
      (selectedResidueField (localSeparableValuationSubring K)) := by
  let A := localSeparableValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let F := localAbstractFixedResidueIntermediateField K H
  letI : Algebra k F := F.algebra
  letI : FiniteDimensional k F :=
    localAbstractFixedResidueIntermediateField_finiteDimensional K H
  letI : Finite F := Module.finite_of_finite k
  letI : Fintype F := Fintype.ofFinite F
  letI : IsGalois k F := by
    obtain ⟨p, hp⟩ := CharP.exists k
    let : CharP k p := hp
    let : CharP F p :=
      charP_of_injective_algebraMap (R := k) (A := F)
        (algebraMap k F).injective p
    exact IsGalois.of_separable_splitting_field
      (galois_poly_separable p (Fintype.card F)
        (let ⟨n, _, hn⟩ := FiniteField.card F p
        hn.symm ▸ dvd_pow_self p n.ne_zero))
  exact { toIntermediateField := F }

/-- **Finite local reciprocity, finite-field index form.**  The residue degree attached
by `localResidueDatum` to a finite abstract field is the degree of the actual
residue subfield selected by the residue action. -/
theorem localResidueDatum_residueDegree_eq_selectedResidueFinrank
    (H : FiniteAbstractField (Gal(SeparableClosure K / K))) :
    (H.residueDegree (localResidueDatum K) : ℕ) =
      Module.finrank
        (decompositionResidueField K (localSeparableValuationSubring K))
        (localAbstractFixedResidueIntermediateField K H.field) := by
  let A := localSeparableValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let rho := (localSeparableResidueAlgAction K).toMonoidHom
  let R := localAbstractFixedResidueIntermediateField K H.field
  let : Algebra k R := R.algebra
  let : FiniteDimensional k R :=
    localAbstractFixedResidueIntermediateField_finiteDimensional K H.field
  let F := localAbstractFixedResidueFiniteGaloisIntermediateField K H.field
  let HR := H.toFiniteResidueAbstractField (localResidueDatum K)
  let : Finite ((localResidueDatum K).residueQuotient H.field) :=
    HR.finiteResidueQuotient
  have himage : H.field.toSubgroup.map rho =
      F.toIntermediateField.fixingSubgroup := by
    change H.field.toSubgroup.map
        (localSeparableResidueAlgAction K).toMonoidHom =
      (localAbstractFixedResidueIntermediateField K H.field).fixingSubgroup
    exact localAbstractFixedResidueAction_map_eq_fixingSubgroup K H.field
  have hindex :
      ((localResidueDatum K).fieldImage HR.field).index =
        Module.finrank k R := by
    rw [(localResidueDatum K).fieldImage_eq_map]
    change
      (H.field.toSubgroup.map
        ((residueAbsoluteDegreeIn k Omega).toMonoidHom.comp rho)).index =
          Module.finrank k R
    exact residueDegreeImage_index_eq_finrank_of_map_eq_fixingSubgroup
      k Omega rho H.field.toSubgroup F himage
  let : ((localResidueDatum K).fieldImage HR.field).IsFiniteRelIndex
      (⊤ : Subgroup ZHatMul) :=
    ⟨by
      rw [Subgroup.relIndex_top_right, hindex]
      let : Module.IsTorsionFree k R :=
        (Module.isTorsionFree_iff_algebraMap_injective (R := k) (A := R)).mpr
          (algebraMap k R).injective
      exact (Module.finrank_pos (R := k) (M := R)).ne'⟩
  apply Nat.cast_injective (R := Cardinal)
  change ((H.residueDegree (localResidueDatum K) : ℕ) : Cardinal) =
    (Module.finrank k R : Cardinal)
  rw [show H.residueDegree (localResidueDatum K) = HR.residueDegree from rfl,
    ← HR.residueDegreeCardinal_eq_coe,
    DegreeData.residueDegreeCardinal,
    relativeIndexCardinal_eq_index_of_finite
      (show (localResidueDatum K).fieldImage HR.field ≤
        (⊤ : Subgroup ZHatMul) from le_top)]
  norm_cast
  simpa only [Subgroup.relIndex_top_right] using hindex

/-- **Finite local reciprocity, pointwise fixed-field degree comparison.**
The normalized degree on a finite abstract field is the ordinary intrinsic
absolute residue degree after changing the finite residue base to the
residue subfield selected by that fixed field. -/
theorem localResidueDatum_normalizedDegree_eq_residueAbsoluteDegreeIn
    (H : FiniteAbstractField (Gal(SeparableClosure K / K)))
    (sigma : H.field.toSubgroup) :
    let F := localAbstractFixedResidueIntermediateField K H.field
    letI : Algebra
        (decompositionResidueField K (localSeparableValuationSubring K))
        F := F.algebra
    letI : Module
        (decompositionResidueField K (localSeparableValuationSubring K))
        F := Algebra.toModule
    letI : FiniteDimensional
        (decompositionResidueField K (localSeparableValuationSubring K))
        F :=
      localAbstractFixedResidueIntermediateField_finiteDimensional K H.field
    letI : Finite F := Module.finite_of_finite
      (decompositionResidueField K (localSeparableValuationSubring K))
    letI : Fintype F := Fintype.ofFinite F
    (localResidueDatum K).normalizedDegree
        (H.toFiniteResidueAbstractField (localResidueDatum K)) sigma =
      residueAbsoluteDegreeIn F
        (selectedResidueField (localSeparableValuationSubring K))
        (localAbstractFixedResidueActionOverIntermediateField
          K H.field sigma) := by
  let A := localSeparableValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let F := localAbstractFixedResidueIntermediateField K H.field
  let : Algebra k F := F.algebra
  let : FiniteDimensional k F :=
    localAbstractFixedResidueIntermediateField_finiteDimensional K H.field
  let : Finite F := Module.finite_of_finite k
  let : Fintype F := Fintype.ofFinite F
  let HF := H.toFiniteResidueAbstractField (localResidueDatum K)
  let tau : Omega ≃ₐ[F] Omega :=
    localAbstractFixedResidueActionOverIntermediateField K H.field sigma
  have htau :
      tau.restrictScalars k =
        localSeparableResidueAlgAction K sigma.1 := by
    apply AlgEquiv.ext
    intro x
    rfl
  have hbase :=
    residueAbsoluteDegreeIn_restrictScalars k Omega F tau
  rw [htau] at hbase
  have hdegree :
      (HF.residueDegree : ℕ) =
        Module.finrank k F :=
    localResidueDatum_residueDegree_eq_selectedResidueFinrank K H
  apply Multiplicative.ext
  apply zHatMulNat_injective
    HF.residueDegree.property
  change
    (HF.residueDegree : ℕ) •
        ((localResidueDatum K).normalizedDegree HF sigma).toAdd =
      (HF.residueDegree : ℕ) •
        (residueAbsoluteDegreeIn F Omega tau).toAdd
  rw [(localResidueDatum K).residueDegree_nsmul_normalizedDegree HF,
    hdegree]
  change
    (residueAbsoluteDegreeIn k Omega
      (localSeparableResidueAlgAction K sigma.1)).toAdd =
        Module.finrank k F •
          (residueAbsoluteDegreeIn F Omega tau).toAdd
  exact congrArg Multiplicative.toAdd hbase

end
end LocalClassFieldTheory
