import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Set.Finite.Range
import Mathlib.GroupTheory.Coset.Card
import Mathlib.GroupTheory.GroupAction.Basic
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.GroupTheory.SpecificGroups.Cyclic

set_option autoImplicit false

namespace CyclicCohomology

/-!
# Low-degree Herbrand quotients

This reusable implementation supplies the low-degree cyclic cohomology used
by the class-formation and local class field theory layers.
-/

noncomputable section

open scoped BigOperators

namespace ProfiniteCohomology
namespace Herbrand

universe uG uA uB uC

/-- Herbrand-quotient theory: the finite-group norm `N_G a = ∏ g, g • a`
for a multiplicative `G`-module. -/
def tateNorm (G : Type uG) (A : Type uA) [Group G] [Fintype G] [CommGroup A]
    [MulDistribMulAction G A] (a : A) : A :=
  ∏ g : G, g • a

/-- Herbrand-quotient theory: the multiplicative coboundary `a^(σ-1)`. -/
def sigmaMinusOne (G : Type uG) (A : Type uA) [Group G] [CommGroup A]
    [MulDistribMulAction G A] (σ : G) (a : A) : A :=
  σ • a * a⁻¹

/-- Herbrand-quotient theory: the fixed subgroup `A^G`. -/
def fixedSubgroup (G : Type uG) (A : Type uA) [Group G] [CommGroup A]
    [MulDistribMulAction G A] : Subgroup A where
  carrier := {a | ∀ g : G, g • a = a}
  one_mem' := by
    intro g
    exact MulDistribMulAction.smul_one g
  mul_mem' := by
    intro a b ha hb g
    rw [MulDistribMulAction.smul_mul, ha g, hb g]
  inv_mem' := by
    intro a ha g
    calc
      g • a⁻¹ = (g • a)⁻¹ := smul_inv' g a
      _ = a⁻¹ := by rw [ha g]

variable {G : Type uG} {A : Type uA} {B : Type uB} {C : Type uC}
variable [Group G] [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
variable [MulDistribMulAction G A] [MulDistribMulAction G B] [MulDistribMulAction G C]

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A `σ`-coboundary equal to `1` makes every element of the cyclic subgroup
generated by `σ` fix the point. -/
theorem smul_eq_of_mem_zpowers_of_sigmaMinusOne_eq_one
    {σ g : G} {a : A} (hg : g ∈ Subgroup.zpowers σ)
    (hσ : sigmaMinusOne G A σ a = 1) :
    g • a = a := by
  have hσa : σ • a = a := by
    exact mul_inv_eq_one.mp (by simpa [sigmaMinusOne] using hσ)
  exact smul_eq_self_of_mem_zpowers hg hσa

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- If `σ` generates `G`, then a trivial `σ`-coboundary is genuinely fixed by
all of `G`. -/
theorem fixed_of_forall_mem_zpowers_of_sigmaMinusOne_eq_one
    {σ : G} {a : A} (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ)
    (hσ : sigmaMinusOne G A σ a = 1) :
    ∀ g : G, g • a = a := by
  intro g
  exact smul_eq_of_mem_zpowers_of_sigmaMinusOne_eq_one
    (G := G) (A := A) (g := g) (hg := hgen g) hσ

omit [Group G] [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- First-isomorphism cardinality source for finite exactness calculations:
the cardinality of the source of a group homomorphism is the product of the
cardinalities of its kernel and range. -/
theorem monoidHom_card_eq_card_ker_mul_card_range
    {X : Type uA} {Y : Type uB} [Group X] [Group Y] [Finite X] (f : X →* Y) :
    Nat.card X = Nat.card (MonoidHom.ker f) * Nat.card (MonoidHom.range f) := by
  rw [← (MonoidHom.ker f).card_mul_index,
    Subgroup.index_ker]

omit [Group G] [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Cardinality source for one exact spot of a group-hom sequence.  If
`range f = ker g`, then the middle group has cardinality
`#range(f) * #range(g)`. -/
theorem monoidHom_card_eq_card_range_mul_card_range_of_exact
    {X : Type uA} {Y : Type uB} {Z : Type uC} [Group X] [Group Y] [Group Z]
    [Finite Y]
    (f : X →* Y) (g : Y →* Z)
    (hexact : MonoidHom.range f = MonoidHom.ker g) :
    Nat.card Y = Nat.card (MonoidHom.range f) * Nat.card (MonoidHom.range g) := by
  rw [monoidHom_card_eq_card_ker_mul_card_range g, ← hexact]

omit [Group G] [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- If `H ≤ K`, viewing `H` as a subgroup of `K` does not change its
cardinality. -/
theorem card_subgroupOf_eq_card
    {X : Type uA} [Group X] [Finite X] {H K : Subgroup X} (hHK : H ≤ K) :
    Nat.card (H.subgroupOf K) = Nat.card H :=
  Nat.card_congr (Subgroup.subgroupOfEquivOfLe hHK).toEquiv

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The multiplicative induced module from the trivial subgroup, represented
as functions on `G` with the right-regular action. This is the concrete model
used in the low-degree Herbrand comparison. -/
@[reducible] def rightRegularFunctionMulDistribMulAction :
    MulDistribMulAction G (G → B) where
  smul g f := fun x => f (x * g)
  one_smul := by
    intro f
    change (fun x => f (x * 1)) = f
    funext x
    rw [mul_one]
  mul_smul := by
    intro g h f
    change (fun x => f (x * (g * h))) = fun x => f ((x * g) * h)
    funext x
    rw [mul_assoc]
  smul_mul := by
    intro g f h
    funext x
    rfl
  smul_one := by
    intro g
    funext x
    rfl

/-- An equivariant homomorphism commutes with the Tate norm. -/
theorem map_tateNorm (f : A →* B)
    (hf : ∀ (g : G) (a : A), f (g • a) = g • f a) (a : A) :
    f (tateNorm G A a) = tateNorm G B (f a) := by
  simp only [tateNorm, map_prod]
  exact Finset.prod_congr rfl (fun g _hg => hf g a)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The finite-group norm is multiplicative. -/
theorem tateNorm_mul (a b : A) :
    tateNorm G A (a * b) = tateNorm G A a * tateNorm G A b := by
  calc
    tateNorm G A (a * b) = ∏ g : G, (g • a) * (g • b) := by
      unfold tateNorm
      apply Finset.prod_congr rfl
      intro g _hg
      exact MulDistribMulAction.smul_mul g a b
    _ = tateNorm G A a * tateNorm G A b := by
      simp only [tateNorm, Finset.prod_mul_distrib]

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The Tate norm of the identity is the identity. -/
@[simp]
theorem tateNorm_one : tateNorm G A 1 = 1 := by
  unfold tateNorm
  exact Finset.prod_eq_one (fun g _hg => MulDistribMulAction.smul_one g)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The finite-group norm as a multiplicative homomorphism. -/
def tateNormHom : A →* A where
  toFun := tateNorm G A
  map_one' := tateNorm_one (G := G) (A := A)
  map_mul' := tateNorm_mul (G := G) (A := A)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The Tate norm homomorphism evaluates to the Tate norm. -/
@[simp]
theorem tateNormHom_apply (a : A) :
    tateNormHom (G := G) (A := A) a = tateNorm G A a :=
  rfl

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The Tate norm of an inverse is the inverse Tate norm. -/
theorem tateNorm_inv (a : A) : tateNorm G A a⁻¹ = (tateNorm G A a)⁻¹ :=
  map_inv (tateNormHom (G := G) (A := A)) a

omit [Fintype G] [CommGroup C] [MulDistribMulAction G C] in
/-- An equivariant homomorphism commutes with the sigma-minus-one operator. -/
theorem map_sigmaMinusOne (f : A →* B)
    (hf : ∀ (g : G) (a : A), f (g • a) = g • f a) (σ : G) (a : A) :
    f (sigmaMinusOne G A σ a) = sigmaMinusOne G B σ (f a) := by
  simp [sigmaMinusOne, hf σ a]

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The multiplicative coboundary `a ↦ a^(σ-1)` is multiplicative. -/
theorem sigmaMinusOne_mul (σ : G) (a b : A) :
    sigmaMinusOne G A σ (a * b) = sigmaMinusOne G A σ a * sigmaMinusOne G A σ b := by
  simp [sigmaMinusOne, mul_comm, mul_left_comm, mul_assoc]

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The multiplicative coboundary `a ↦ a^(σ-1)` as a homomorphism. -/
def sigmaMinusOneHom (σ : G) : A →* A where
  toFun := sigmaMinusOne G A σ
  map_one' := by simp [sigmaMinusOne, MulDistribMulAction.smul_one]
  map_mul' := sigmaMinusOne_mul (G := G) (A := A) σ

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The sigma-minus-one homomorphism evaluates to the sigma-minus-one operator. -/
@[simp]
theorem sigmaMinusOneHom_apply (σ : G) (a : A) :
    sigmaMinusOneHom (G := G) (A := A) σ a = sigmaMinusOne G A σ a :=
  rfl

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Rewriting used in the cyclic-cohomology exact sequence: changing a lift
by `a' * a⁻¹` changes `a^(σ-1)` by an element of `I_G A`. -/
theorem sigmaMinusOne_mul_inv_mul (σ : G) (a a' : A) :
    sigmaMinusOne G A σ a' =
      sigmaMinusOne G A σ (a' * a⁻¹) * sigmaMinusOne G A σ a := by
  simp only [sigmaMinusOne, MulDistribMulAction.smul_mul, smul_inv', mul_inv_rev]
  simp only [inv_inv]
  symm
  calc
    σ • a' * (σ • a)⁻¹ * (a * a'⁻¹) * (σ • a * a⁻¹)
        = σ • a' * (((σ • a)⁻¹ * σ • a) * ((a * a⁻¹) * a'⁻¹)) := by
          ac_rfl
    _ = σ • a' * a'⁻¹ := by simp

/-- Herbrand-quotient theory: the norm image `N_G A`. -/
def tateNormSubgroup (G : Type uG) (A : Type uA) [Group G] [Fintype G] [CommGroup A]
    [MulDistribMulAction G A] : Subgroup A :=
  MonoidHom.range (tateNormHom (G := G) (A := A))

/-- Herbrand-quotient theory: the norm kernel `{a | N_G a = 1}`. -/
def normKernelSubgroup (G : Type uG) (A : Type uA) [Group G] [Fintype G] [CommGroup A]
    [MulDistribMulAction G A] : Subgroup A :=
  MonoidHom.ker (tateNormHom (G := G) (A := A))

/-- Herbrand-quotient theory: the augmentation image `I_G A` for a chosen `σ`. -/
def augmentationSubgroup (G : Type uG) (A : Type uA) [Group G] [CommGroup A]
    [MulDistribMulAction G A] (σ : G) : Subgroup A :=
  MonoidHom.range (sigmaMinusOneHom (G := G) (A := A) σ)

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- If `σ` generates `G`, the kernel of `a ↦ a^(σ-1)` is the fixed subgroup. -/
theorem sigmaMinusOneHom_ker_eq_fixedSubgroup
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) :
    MonoidHom.ker (sigmaMinusOneHom (G := G) (A := A) σ) = fixedSubgroup G A := by
  ext a
  constructor
  · intro ha
    exact fixed_of_forall_mem_zpowers_of_sigmaMinusOne_eq_one
      (G := G) (A := A) (σ := σ) hgen (by simpa using ha)
  · intro ha
    change sigmaMinusOne G A σ a = 1
    simp [sigmaMinusOne, ha σ]

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Finite-module source: the norm homomorphism factors the cardinality of
`A` into norm-kernel and norm-image cardinalities. -/
theorem card_eq_card_normKernelSubgroup_mul_card_tateNormSubgroup [Finite A] :
    Nat.card A = Nat.card (normKernelSubgroup G A) * Nat.card (tateNormSubgroup G A) := by
  simpa [normKernelSubgroup, tateNormSubgroup] using
    monoidHom_card_eq_card_ker_mul_card_range (tateNormHom (G := G) (A := A))

omit [Fintype G] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Finite-module source: for a cyclic generator `σ`, the coboundary
homomorphism factors the cardinality of `A` into fixed and augmentation
cardinalities. -/
theorem card_eq_card_fixedSubgroup_mul_card_augmentationSubgroup
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) [Finite A] :
    Nat.card A = Nat.card (fixedSubgroup G A) * Nat.card (augmentationSubgroup G A σ) := by
  simpa [sigmaMinusOneHom_ker_eq_fixedSubgroup (G := G) (A := A) σ hgen,
    augmentationSubgroup] using
    monoidHom_card_eq_card_ker_mul_card_range
      (sigmaMinusOneHom (G := G) (A := A) σ)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Finite-module cardinality balance behind `h(G,A)=1`: for a finite cyclic
group action, the product `#A^G · #I_G A` equals `#ker N_G · #N_G A`. -/
theorem herbrand_finite_module_cardinality_balance
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) [Finite A] :
    Nat.card (fixedSubgroup G A) * Nat.card (augmentationSubgroup G A σ) =
      Nat.card (normKernelSubgroup G A) * Nat.card (tateNormSubgroup G A) := by
  rw [← card_eq_card_fixedSubgroup_mul_card_augmentationSubgroup
      (G := G) (A := A) σ hgen,
    ← card_eq_card_normKernelSubgroup_mul_card_tateNormSubgroup (G := G) (A := A)]

/-- Herbrand-quotient theory: multiplicative model of `H⁰(G,A)=A^G/N_G A`. -/
def HerbrandH0 (G : Type uG) (A : Type uA) [Group G] [Fintype G] [CommGroup A]
    [MulDistribMulAction G A] : Type uA :=
  fixedSubgroup G A ⧸ (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)

/-- Herbrand-quotient theory: multiplicative model of
`H^{-1}(G,A) = ker(N_G)/I_G A` for a chosen generator `σ`. -/
def HerbrandHMinusOne (G : Type uG) (A : Type uA) [Group G] [Fintype G] [CommGroup A]
    [MulDistribMulAction G A] (σ : G) : Type uA :=
  normKernelSubgroup G A ⧸ (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Degree-zero Herbrand cohomology is a commutative group. -/
instance herbrandH0CommGroup : CommGroup (HerbrandH0 G A) := by
  unfold HerbrandH0
  infer_instance

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Degree-minus-one Herbrand cohomology is a commutative group. -/
instance herbrandHMinusOneCommGroup (σ : G) :
    CommGroup (HerbrandHMinusOne G A σ) := by
  unfold HerbrandHMinusOne
  infer_instance

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The sole public equivalence to the concrete quotient implementing
`H⁰(G,A)`. -/
def HerbrandH0.equiv :
    HerbrandH0 G A ≃*
      fixedSubgroup G A ⧸
        (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A) := by
  change
    (fixedSubgroup G A ⧸
        (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)) ≃*
      fixedSubgroup G A ⧸
        (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)
  exact MulEquiv.refl _

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The sole public equivalence to the concrete quotient implementing
`H⁻¹(G,A)`. -/
def HerbrandHMinusOne.equiv (σ : G) :
    HerbrandHMinusOne G A σ ≃*
      normKernelSubgroup G A ⧸
        (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A) := by
  change
    (normKernelSubgroup G A ⧸
        (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)) ≃*
      normKernelSubgroup G A ⧸
        (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)
  exact MulEquiv.refl _

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Canonical projection from fixed points to `H⁰(G,A)`. -/
def HerbrandH0.mk : fixedSubgroup G A →* HerbrandH0 G A := by
  unfold HerbrandH0
  exact QuotientGroup.mk'
    ((tateNormSubgroup G A).subgroupOf (fixedSubgroup G A))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Canonical projection from the norm kernel to `H⁻¹(G,A)`. -/
def HerbrandHMinusOne.mk (σ : G) :
    normKernelSubgroup G A →* HerbrandHMinusOne G A σ := by
  unfold HerbrandHMinusOne
  exact QuotientGroup.mk'
    ((augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The degree-zero quotient equivalence sends the canonical class to the raw quotient class. -/
@[simp]
theorem HerbrandH0.equiv_mk (a : fixedSubgroup G A) :
    HerbrandH0.equiv (G := G) (A := A) (HerbrandH0.mk a) =
      QuotientGroup.mk a := by
  rfl

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The degree-minus-one quotient equivalence sends the canonical class to the
raw quotient class. -/
@[simp]
theorem HerbrandHMinusOne.equiv_mk (σ : G) (a : normKernelSubgroup G A) :
    HerbrandHMinusOne.equiv (G := G) (A := A) σ
        (HerbrandHMinusOne.mk σ a) =
      QuotientGroup.mk a := by
  rfl

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Every degree-zero Herbrand class has a fixed-point representative. -/
theorem HerbrandH0.mk_surjective :
    Function.Surjective (HerbrandH0.mk (G := G) (A := A)) := by
  intro q
  obtain ⟨a, ha⟩ := QuotientGroup.mk'_surjective
    ((tateNormSubgroup G A).subgroupOf (fixedSubgroup G A))
    (HerbrandH0.equiv (G := G) (A := A) q)
  refine ⟨a, (HerbrandH0.equiv (G := G) (A := A)).injective ?_⟩
  rw [HerbrandH0.equiv_mk]
  exact ha

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Every degree-minus-one Herbrand class has a norm-kernel representative. -/
theorem HerbrandHMinusOne.mk_surjective (σ : G) :
    Function.Surjective (HerbrandHMinusOne.mk (G := G) (A := A) σ) := by
  intro q
  obtain ⟨a, ha⟩ := QuotientGroup.mk'_surjective
    ((augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A))
    (HerbrandHMinusOne.equiv (G := G) (A := A) σ q)
  refine ⟨a, (HerbrandHMinusOne.equiv (G := G) (A := A) σ).injective ?_⟩
  rw [HerbrandHMinusOne.equiv_mk]
  exact ha

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A fixed-point representative gives the trivial degree-zero class exactly
when it is a Tate norm. -/
@[simp]
theorem HerbrandH0.mk_eq_one_iff (a : fixedSubgroup G A) :
    HerbrandH0.mk a = 1 ↔ (a : A) ∈ tateNormSubgroup G A := by
  constructor
  · intro h
    have hraw :
        (QuotientGroup.mk a :
          fixedSubgroup G A ⧸
            (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)) = 1 := by
      simpa only [HerbrandH0.equiv_mk, map_one] using
        congrArg (HerbrandH0.equiv (G := G) (A := A)) h
    simpa only [Subgroup.mem_subgroupOf] using
      (QuotientGroup.eq_one_iff a).1 hraw
  · intro h
    apply (HerbrandH0.equiv (G := G) (A := A)).injective
    rw [HerbrandH0.equiv_mk, map_one]
    apply (QuotientGroup.eq_one_iff a).2
    simpa only [Subgroup.mem_subgroupOf] using h

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A norm-kernel representative gives the trivial degree-minus-one class
exactly when it is an augmentation. -/
@[simp]
theorem HerbrandHMinusOne.mk_eq_one_iff (σ : G)
    (a : normKernelSubgroup G A) :
    HerbrandHMinusOne.mk σ a = 1 ↔
      (a : A) ∈ augmentationSubgroup G A σ := by
  constructor
  · intro h
    have hraw :
        (QuotientGroup.mk a :
          normKernelSubgroup G A ⧸
            (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)) = 1 := by
      simpa only [HerbrandHMinusOne.equiv_mk, map_one] using
        congrArg (HerbrandHMinusOne.equiv (G := G) (A := A) σ) h
    simpa only [Subgroup.mem_subgroupOf] using
      (QuotientGroup.eq_one_iff a).1 hraw
  · intro h
    apply (HerbrandHMinusOne.equiv (G := G) (A := A) σ).injective
    rw [HerbrandHMinusOne.equiv_mk, map_one]
    apply (QuotientGroup.eq_one_iff a).2
    simpa only [Subgroup.mem_subgroupOf] using h

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Two degree-zero representatives agree exactly when their quotient is a Tate norm. -/
theorem HerbrandH0.mk_eq_mk_iff_div_mem (a b : fixedSubgroup G A) :
    HerbrandH0.mk a = HerbrandH0.mk b ↔
      (a : A) / b ∈ tateNormSubgroup G A := by
  constructor
  · intro h
    have hraw :
        (QuotientGroup.mk a :
          fixedSubgroup G A ⧸
            (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)) =
          QuotientGroup.mk b := by
      simpa only [HerbrandH0.equiv_mk] using
        congrArg (HerbrandH0.equiv (G := G) (A := A)) h
    simpa only [Subgroup.mem_subgroupOf, Subgroup.coe_div] using
      (QuotientGroup.eq_iff_div_mem).1 hraw
  · intro h
    apply (HerbrandH0.equiv (G := G) (A := A)).injective
    rw [HerbrandH0.equiv_mk, HerbrandH0.equiv_mk]
    apply (QuotientGroup.eq_iff_div_mem).2
    simpa only [Subgroup.mem_subgroupOf, Subgroup.coe_div] using h

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Two degree-minus-one representatives agree exactly when their quotient is an augmentation. -/
theorem HerbrandHMinusOne.mk_eq_mk_iff_div_mem (σ : G)
    (a b : normKernelSubgroup G A) :
    HerbrandHMinusOne.mk σ a = HerbrandHMinusOne.mk σ b ↔
      (a : A) / b ∈ augmentationSubgroup G A σ := by
  constructor
  · intro h
    have hraw :
        (QuotientGroup.mk a :
          normKernelSubgroup G A ⧸
            (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)) =
          QuotientGroup.mk b := by
      simpa only [HerbrandHMinusOne.equiv_mk] using
        congrArg (HerbrandHMinusOne.equiv (G := G) (A := A) σ) h
    simpa only [Subgroup.mem_subgroupOf, Subgroup.coe_div] using
      (QuotientGroup.eq_iff_div_mem).1 hraw
  · intro h
    apply (HerbrandHMinusOne.equiv (G := G) (A := A) σ).injective
    rw [HerbrandHMinusOne.equiv_mk, HerbrandHMinusOne.equiv_mk]
    apply (QuotientGroup.eq_iff_div_mem).2
    simpa only [Subgroup.mem_subgroupOf, Subgroup.coe_div] using h

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Two degree-zero representatives agree exactly when the inverse-times-second
ratio is a Tate norm. -/
theorem HerbrandH0.mk_eq_mk_iff_inv_mul_mem (a b : fixedSubgroup G A) :
    HerbrandH0.mk a = HerbrandH0.mk b ↔
      (a : A)⁻¹ * b ∈ tateNormSubgroup G A := by
  rw [HerbrandH0.mk_eq_mk_iff_div_mem]
  constructor
  · intro h
    have hinv := (tateNormSubgroup G A).inv_mem h
    simpa [div_eq_mul_inv, mul_comm] using hinv
  · intro h
    have hinv := (tateNormSubgroup G A).inv_mem h
    simpa [div_eq_mul_inv, mul_comm] using hinv

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Two degree-minus-one representatives agree exactly when the
inverse-times-second ratio is an augmentation. -/
theorem HerbrandHMinusOne.mk_eq_mk_iff_inv_mul_mem (σ : G)
    (a b : normKernelSubgroup G A) :
    HerbrandHMinusOne.mk σ a = HerbrandHMinusOne.mk σ b ↔
      (a : A)⁻¹ * b ∈ augmentationSubgroup G A σ := by
  rw [HerbrandHMinusOne.mk_eq_mk_iff_div_mem]
  constructor
  · intro h
    have hinv := (augmentationSubgroup G A σ).inv_mem h
    simpa [div_eq_mul_inv, mul_comm] using hinv
  · intro h
    have hinv := (augmentationSubgroup G A σ).inv_mem h
    simpa [div_eq_mul_inv, mul_comm] using hinv

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Eliminate a degree-zero Herbrand class through an arbitrary fixed-point
representative and the canonical class map. -/
protected theorem HerbrandH0.inductionOn
    {motive : HerbrandH0 G A → Prop} (q : HerbrandH0 G A)
    (h : ∀ a : fixedSubgroup G A, motive (HerbrandH0.mk a)) : motive q := by
  obtain ⟨a, rfl⟩ := HerbrandH0.mk_surjective (G := G) (A := A) q
  exact h a

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Eliminate a degree-minus-one Herbrand class through an arbitrary
norm-kernel representative and the canonical class map. -/
protected theorem HerbrandHMinusOne.inductionOn (σ : G)
    {motive : HerbrandHMinusOne G A σ → Prop}
    (q : HerbrandHMinusOne G A σ)
    (h : ∀ a : normKernelSubgroup G A,
      motive (HerbrandHMinusOne.mk σ a)) : motive q := by
  obtain ⟨a, rfl⟩ :=
    HerbrandHMinusOne.mk_surjective (G := G) (A := A) σ q
  exact h a

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Evaluate a function on `H⁰(G,A)` from a representative-level function
which is invariant under equality of canonical quotient classes.  This is the
non-homomorphic elimination API; clients never need the underlying quotient
relation. -/
noncomputable def HerbrandH0.liftOn {M : Sort*}
    (q : HerbrandH0 G A) (f : fixedSubgroup G A → M)
    (_h : ∀ a b, HerbrandH0.mk a = HerbrandH0.mk b → f a = f b) : M :=
  f (Classical.choose (HerbrandH0.mk_surjective (G := G) (A := A) q))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Eliminating a canonical degree-zero class evaluates the representative-level function. -/
@[simp]
theorem HerbrandH0.liftOn_mk {M : Sort*}
    (f : fixedSubgroup G A → M)
    (h : ∀ a b, HerbrandH0.mk a = HerbrandH0.mk b → f a = f b)
    (a : fixedSubgroup G A) :
    HerbrandH0.liftOn (HerbrandH0.mk a) f h = f a := by
  unfold HerbrandH0.liftOn
  apply h
  exact Classical.choose_spec
    (HerbrandH0.mk_surjective (G := G) (A := A) (HerbrandH0.mk a))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Evaluate a function on `H⁻¹(G,A)` from a representative-level
function which is invariant under equality of canonical quotient classes. -/
noncomputable def HerbrandHMinusOne.liftOn {M : Sort*} (σ : G)
    (q : HerbrandHMinusOne G A σ) (f : normKernelSubgroup G A → M)
    (_h : ∀ a b,
      HerbrandHMinusOne.mk σ a = HerbrandHMinusOne.mk σ b → f a = f b) : M :=
  f (Classical.choose
    (HerbrandHMinusOne.mk_surjective (G := G) (A := A) σ q))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Eliminating a canonical degree-minus-one class evaluates the representative-level function. -/
@[simp]
theorem HerbrandHMinusOne.liftOn_mk {M : Sort*} (σ : G)
    (f : normKernelSubgroup G A → M)
    (h : ∀ a b,
      HerbrandHMinusOne.mk σ a = HerbrandHMinusOne.mk σ b → f a = f b)
    (a : normKernelSubgroup G A) :
    HerbrandHMinusOne.liftOn σ (HerbrandHMinusOne.mk σ a) f h = f a := by
  unfold HerbrandHMinusOne.liftOn
  apply h
  exact Classical.choose_spec
    (HerbrandHMinusOne.mk_surjective (G := G) (A := A) σ
      (HerbrandHMinusOne.mk σ a))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Descend a homomorphism on fixed points through `H⁰(G,A)`. -/
def HerbrandH0.lift {M : Type*} [Group M]
    (f : fixedSubgroup G A →* M)
    (h : (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A) ≤ f.ker) :
    HerbrandH0 G A →* M := by
  unfold HerbrandH0
  exact QuotientGroup.lift
    ((tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)) f h

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Descend a homomorphism on the norm kernel through `H⁻¹(G,A)`. -/
def HerbrandHMinusOne.lift {M : Type*} [Group M] (σ : G)
    (f : normKernelSubgroup G A →* M)
    (h : (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A) ≤
      f.ker) : HerbrandHMinusOne G A σ →* M := by
  unfold HerbrandHMinusOne
  exact QuotientGroup.lift
    ((augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)) f h

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A homomorphism descended through degree-zero Herbrand cohomology agrees on representatives. -/
@[simp]
theorem HerbrandH0.lift_mk {M : Type*} [Group M]
    (f : fixedSubgroup G A →* M)
    (h : (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A) ≤ f.ker)
    (a : fixedSubgroup G A) : HerbrandH0.lift f h (HerbrandH0.mk a) = f a := by
  rfl

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A homomorphism descended through degree-minus-one Herbrand cohomology agrees
on representatives. -/
@[simp]
theorem HerbrandHMinusOne.lift_mk {M : Type*} [Group M] (σ : G)
    (f : normKernelSubgroup G A →* M)
    (h : (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A) ≤
      f.ker) (a : normKernelSubgroup G A) :
    HerbrandHMinusOne.lift σ f h (HerbrandHMinusOne.mk σ a) = f a := by
  rfl

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Degree-zero Herbrand cohomology is finite when the coefficient group is finite. -/
noncomputable instance herbrandH0FiniteOfFinite [Finite A] :
    Finite (HerbrandH0 G A) := by
  exact Finite.of_equiv
    (fixedSubgroup G A ⧸
      (tateNormSubgroup G A).subgroupOf (fixedSubgroup G A))
    (HerbrandH0.equiv (G := G) (A := A)).symm.toEquiv

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Degree-minus-one Herbrand cohomology is finite when the coefficient group is finite. -/
noncomputable instance herbrandHMinusOneFiniteOfFinite (σ : G) [Finite A] :
    Finite (HerbrandHMinusOne G A σ) := by
  exact Finite.of_equiv
    (normKernelSubgroup G A ⧸
      (augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A))
    (HerbrandHMinusOne.equiv (G := G) (A := A) σ).symm.toEquiv

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Fixed subgroup of the right-regular multiplicative induced module. -/
abbrev rightRegularFunctionFixedSubgroup : Subgroup (G → B) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact fixedSubgroup G (G → B)

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Norm image subgroup of the right-regular multiplicative induced module. -/
abbrev rightRegularFunctionTateNormSubgroup : Subgroup (G → B) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact tateNormSubgroup G (G → B)

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- `H⁰` of the right-regular multiplicative induced module. -/
def rightRegularFunctionHerbrandH0 := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact HerbrandH0 G (G → B)

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Degree-zero Herbrand cohomology of right-regular functions is a commutative group. -/
noncomputable instance rightRegularFunctionHerbrandH0CommGroup :
    CommGroup (rightRegularFunctionHerbrandH0 (G := G) (B := B)) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  change CommGroup (HerbrandH0 G (G → B))
  infer_instance

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Norm-kernel subgroup of the right-regular multiplicative induced module. -/
abbrev rightRegularFunctionNormKernelSubgroup : Subgroup (G → B) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact normKernelSubgroup G (G → B)

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Augmentation subgroup of the right-regular multiplicative induced module. -/
abbrev rightRegularFunctionAugmentationSubgroup (σ : G) : Subgroup (G → B) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact augmentationSubgroup G (G → B) σ

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- `H^{-1}` of the right-regular multiplicative induced module. -/
def rightRegularFunctionHerbrandHMinusOne (σ : G) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact HerbrandHMinusOne G (G → B) σ

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Degree-minus-one Herbrand cohomology of right-regular functions is a commutative group. -/
noncomputable instance rightRegularFunctionHerbrandHMinusOneCommGroup (σ : G) :
    CommGroup
      (rightRegularFunctionHerbrandHMinusOne (G := G) (B := B) σ) := by
  letI := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  change CommGroup (HerbrandHMinusOne G (G → B) σ)
  infer_instance

/-- The norm of a multiplicative coboundary is trivial. This is the calculation
`N_G(b^(σ-1)) = 1` used in the low-degree cyclic-cohomology exact sequence. -/
theorem tateNorm_sigmaMinusOne_eq_one (σ : G) (a : A) :
    tateNorm G A (sigmaMinusOne G A σ a) = 1 := by
  have hshift : (∏ g : G, (g * σ) • a) = ∏ g : G, g • a := by
    exact Fintype.prod_equiv (Equiv.mulRight σ)
      (fun g : G => (g * σ) • a) (fun g : G => g • a) (by intro g; rfl)
  calc
    tateNorm G A (sigmaMinusOne G A σ a) = ∏ g : G, ((g * σ) • a) * (g • a)⁻¹ := by
      unfold tateNorm sigmaMinusOne
      apply Finset.prod_congr rfl
      intro g _hg
      calc
        g • (σ • a * a⁻¹) = g • (σ • a) * g • a⁻¹ :=
          MulDistribMulAction.smul_mul g (σ • a) a⁻¹
        _ = (g * σ) • a * (g • a)⁻¹ := by
          rw [← SemigroupAction.mul_smul, smul_inv']
    _ = (∏ g : G, (g * σ) • a) * ∏ g : G, (g • a)⁻¹ := by
      exact Finset.prod_mul_distrib
    _ = 1 := by
      rw [hshift, Finset.prod_inv_distrib, mul_inv_cancel]

/-- The augmentation image lies in the norm kernel. -/
theorem augmentationSubgroup_le_normKernelSubgroup (σ : G) :
    augmentationSubgroup G A σ ≤ normKernelSubgroup G A := by
  intro a ha
  rcases ha with ⟨b, rfl⟩
  exact tateNorm_sigmaMinusOne_eq_one (G := G) (A := A) σ b

/-- The norm is fixed by every group element, placing `N_G b` in `A^G` in the
low-degree cyclic-cohomology exact sequence. -/
theorem smul_tateNorm_eq (h : G) (a : A) :
    h • tateNorm G A a = tateNorm G A a := by
  have hmap : h • (∏ g : G, g • a) = ∏ g : G, h • (g • a) := by
    exact map_prod (MulDistribMulAction.toMonoidHom A h) (fun g : G => g • a) Finset.univ
  have hshift : (∏ g : G, (h * g) • a) = ∏ g : G, g • a := by
    exact Fintype.prod_equiv (Equiv.mulLeft h)
      (fun g : G => (h * g) • a) (fun g : G => g • a) (by intro g; rfl)
  calc
    h • tateNorm G A a = ∏ g : G, h • (g • a) := by
      simpa [tateNorm] using hmap
    _ = ∏ g : G, (h * g) • a := by
      apply Finset.prod_congr rfl
      intro g _hg
      exact (SemigroupAction.mul_smul h g a).symm
    _ = tateNorm G A a := by
      simpa [tateNorm] using hshift

/-- The norm image lies in the fixed subgroup, as in Herbrand-quotient theory. -/
theorem tateNormSubgroup_le_fixedSubgroup :
    tateNormSubgroup G A ≤ fixedSubgroup G A := by
  intro a ha g
  rcases ha with ⟨b, rfl⟩
  exact smul_tateNorm_eq (G := G) (A := A) g b

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A quotient-level criterion for vanishing of `H⁰`: if every fixed point is
a norm, then the low-degree Herbrand `H⁰` quotient is a subsingleton. -/
theorem herbrandH0_subsingleton_of_fixed_le_tateNormSubgroup
    (h : fixedSubgroup G A ≤ tateNormSubgroup G A) :
    Subsingleton (HerbrandH0 G A) := by
  refine ⟨fun q r => ?_⟩
  have hq : q = 1 := by
    refine HerbrandH0.inductionOn (motive := fun z => z = 1) q ?_
    intro a
    apply (HerbrandH0.mk_eq_one_iff (G := G) (A := A) a).2
    exact h a.2
  have hr : r = 1 := by
    refine HerbrandH0.inductionOn (motive := fun z => z = 1) r ?_
    intro a
    apply (HerbrandH0.mk_eq_one_iff (G := G) (A := A) a).2
    exact h a.2
  rw [hq, hr]

/-- Degree-zero Herbrand cohomology is trivial exactly when every fixed
element is a Tate norm. -/
theorem herbrandH0_subsingleton_iff_fixed_le_tateNormSubgroup :
    Subsingleton (HerbrandH0 G A) ↔
      fixedSubgroup G A ≤ tateNormSubgroup G A := by
  constructor
  · intro h a ha
    apply (HerbrandH0.mk_eq_one_iff (G := G) (A := A) ⟨a, ha⟩).1
    exact h.elim _ _
  · exact herbrandH0_subsingleton_of_fixed_le_tateNormSubgroup
      (G := G) (A := A)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- A quotient-level criterion for vanishing of `H^{-1}`: if every norm-kernel
element is an augmentation element, then the low-degree Herbrand `H^{-1}`
quotient is a subsingleton. -/
theorem herbrandHMinusOne_subsingleton_of_normKernel_le_augmentationSubgroup
    (σ : G) (h : normKernelSubgroup G A ≤ augmentationSubgroup G A σ) :
    Subsingleton (HerbrandHMinusOne G A σ) := by
  refine ⟨fun q r => ?_⟩
  have hq : q = 1 := by
    refine HerbrandHMinusOne.inductionOn σ
      (motive := fun z => z = 1) q ?_
    intro a
    apply (HerbrandHMinusOne.mk_eq_one_iff (G := G) (A := A) σ a).2
    exact h a.2
  have hr : r = 1 := by
    refine HerbrandHMinusOne.inductionOn σ
      (motive := fun z => z = 1) r ?_
    intro a
    apply (HerbrandHMinusOne.mk_eq_one_iff (G := G) (A := A) σ a).2
    exact h a.2
  rw [hq, hr]

/-- Degree-minus-one Herbrand cohomology is trivial exactly when every
norm-kernel element is an augmentation element. -/
theorem herbrandHMinusOne_subsingleton_iff_normKernel_le_augmentationSubgroup
    (σ : G) :
    Subsingleton (HerbrandHMinusOne G A σ) ↔
      normKernelSubgroup G A ≤ augmentationSubgroup G A σ := by
  constructor
  · intro h a ha
    apply (HerbrandHMinusOne.mk_eq_one_iff (G := G) (A := A) σ ⟨a, ha⟩).1
    exact h.elim _ _
  · exact herbrandHMinusOne_subsingleton_of_normKernel_le_augmentationSubgroup
      (G := G) (A := A) σ

omit [Fintype G] [CommGroup C] [MulDistribMulAction G C] in
/-- The inverse of an equivariant multiplicative equivalence is equivariant. -/
theorem mulEquiv_symm_commutes_smul
    (e : A ≃* B)
    (he : ∀ (g : G) (a : A), e (g • a) = g • e a) :
    ∀ (g : G) (b : B), e.symm (g • b) = g • e.symm b := by
  intro g b
  apply e.injective
  calc
    e (e.symm (g • b)) = g • b := e.apply_symm_apply (g • b)
    _ = g • e (e.symm b) := by rw [e.apply_symm_apply]
    _ = e (g • e.symm b) := (he g (e.symm b)).symm

omit [CommGroup C] [MulDistribMulAction G C] in
/-- Transport the `H⁰` vanishing source `A^G ≤ N_G A` across an equivariant
multiplicative equivalence. -/
theorem fixed_le_tateNormSubgroup_of_mulEquiv
    (e : A ≃* B)
    (he : ∀ (g : G) (a : A), e (g • a) = g • e a)
    (hB : fixedSubgroup G B ≤ tateNormSubgroup G B) :
    fixedSubgroup G A ≤ tateNormSubgroup G A := by
  intro a ha
  have hea : e a ∈ fixedSubgroup G B := by
    intro g
    rw [← he g a, ha g]
  rcases hB hea with ⟨b, hb⟩
  refine ⟨e.symm b, ?_⟩
  apply e.injective
  calc
    e (tateNorm G A (e.symm b)) =
        tateNorm G B (e (e.symm b)) :=
      map_tateNorm (G := G) (A := A) (B := B) e.toMonoidHom
        (fun g a => by simpa using he g a) (e.symm b)
    _ = tateNorm G B b := by rw [e.apply_symm_apply]
    _ = e a := hb

omit [CommGroup C] [MulDistribMulAction G C] in
/-- Transport the `H^{-1}` vanishing source `ker N_G ≤ I_G A` across an
equivariant multiplicative equivalence. -/
theorem normKernel_le_augmentationSubgroup_of_mulEquiv
    (e : A ≃* B)
    (he : ∀ (g : G) (a : A), e (g • a) = g • e a)
    (σ : G) (hB : normKernelSubgroup G B ≤ augmentationSubgroup G B σ) :
    normKernelSubgroup G A ≤ augmentationSubgroup G A σ := by
  intro a ha
  have haNorm : tateNorm G A a = 1 := by
    simpa [normKernelSubgroup] using ha
  have hea : e a ∈ normKernelSubgroup G B := by
    change tateNorm G B (e a) = 1
    calc
      tateNorm G B (e a) = e (tateNorm G A a) :=
        (map_tateNorm (G := G) (A := A) (B := B) e.toMonoidHom
          (fun g a => by simpa using he g a) a).symm
      _ = e 1 := by rw [haNorm]
      _ = 1 := by simp
  rcases hB hea with ⟨b, hb⟩
  refine ⟨e.symm b, ?_⟩
  apply e.injective
  calc
    e (sigmaMinusOne G A σ (e.symm b)) =
        sigmaMinusOne G B σ (e (e.symm b)) :=
      map_sigmaMinusOne (G := G) (A := A) (B := B) e.toMonoidHom
        (fun g a => by simpa using he g a) σ (e.symm b)
    _ = sigmaMinusOne G B σ b := by rw [e.apply_symm_apply]
    _ = e a := hb

omit [CommGroup C] [MulDistribMulAction G C] in
/-- Transport low-degree `H⁰` triviality across an equivariant multiplicative
equivalence. -/
theorem herbrandH0_subsingleton_of_mulEquiv
    (e : A ≃* B)
    (he : ∀ (g : G) (a : A), e (g • a) = g • e a)
    (hB : fixedSubgroup G B ≤ tateNormSubgroup G B) :
    Subsingleton (HerbrandH0 G A) :=
  herbrandH0_subsingleton_of_fixed_le_tateNormSubgroup
    (G := G) (A := A)
    (fixed_le_tateNormSubgroup_of_mulEquiv (G := G) (A := A) (B := B) e he hB)

omit [CommGroup C] [MulDistribMulAction G C] in
/-- Transport low-degree `H^{-1}` triviality across an equivariant
multiplicative equivalence. -/
theorem herbrandHMinusOne_subsingleton_of_mulEquiv
    (e : A ≃* B)
    (he : ∀ (g : G) (a : A), e (g • a) = g • e a)
    (σ : G) (hB : normKernelSubgroup G B ≤ augmentationSubgroup G B σ) :
    Subsingleton (HerbrandHMinusOne G A σ) :=
  herbrandHMinusOne_subsingleton_of_normKernel_le_augmentationSubgroup
    (G := G) (A := A) σ
    (normKernel_le_augmentationSubgroup_of_mulEquiv
      (G := G) (A := A) (B := B) e he σ hB)

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Membership in the right-regular norm kernel is the single product
condition `∏ g, f g = 1`. -/
theorem rightRegularFunction_mem_normKernelSubgroup_iff (f : G → B) :
    f ∈ rightRegularFunctionNormKernelSubgroup (G := G) (B := B) ↔
      (∏ g : G, f g) = 1 := by
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  have hnorm (x : G) : tateNorm G (G → B) f x = ∏ g : G, f g := by
    calc
      tateNorm G (G → B) f x = ∏ g : G, f (x * g) := by
        unfold tateNorm
        let ev : (G → B) →* B := {
          toFun q := q x
          map_one' := rfl
          map_mul' := by
            intro q r
            rfl
        }
        calc
          ((∏ c : G, c • f) : G → B) x = ev (∏ c : G, c • f) := rfl
          _ = ∏ c : G, ev (c • f) := by rw [map_prod]
          _ = ∏ c : G, f (x * c) := by
            refine Finset.prod_congr rfl ?_
            intro c _hc
            change (c • f) x = f (x * c)
            rfl
      _ = ∏ g : G, f g := by
        exact Fintype.prod_equiv (Equiv.mulLeft x)
          (fun g : G => f (x * g)) (fun g : G => f g) (by intro g; rfl)
  constructor
  · intro hf
    change tateNorm G (G → B) f = 1 at hf
    have hx := congrArg (fun q : G → B => q 1) hf
    calc
      (∏ g : G, f g) = tateNorm G (G → B) f 1 := (hnorm 1).symm
      _ = 1 := by simpa using hx
  · intro hf
    change tateNorm G (G → B) f = 1
    funext x
    calc
      tateNorm G (G → B) f x = ∏ g : G, f g := hnorm x
      _ = 1 := hf

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The partial primitive along the cyclic powers of `σ`.  This is the
candidate used to solve `b (x * σ) * (b x)⁻¹ = f x` on the right-regular
induced module. -/
def rightRegularCyclicPartialProduct (σ : G) (f : G → B) (i : ℕ) : B :=
  (Finset.range i).prod (fun k => f (σ ^ k))

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The partial primitive starts at `1`. -/
theorem rightRegularCyclicPartialProduct_zero (σ : G) (f : G → B) :
    rightRegularCyclicPartialProduct (G := G) (B := B) σ f 0 = 1 := by
  simp [rightRegularCyclicPartialProduct]

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Successor step for the cyclic partial primitive. -/
theorem rightRegularCyclicPartialProduct_succ (σ : G) (f : G → B) (i : ℕ) :
    rightRegularCyclicPartialProduct (G := G) (B := B) σ f (i + 1) =
      rightRegularCyclicPartialProduct (G := G) (B := B) σ f i * f (σ ^ i) := by
  simp [rightRegularCyclicPartialProduct, Finset.prod_range_succ]

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The successor step is the desired coboundary equation away from the
wrap-around point. -/
theorem rightRegularCyclicPartialProduct_succ_mul_inv
    (σ : G) (f : G → B) (i : ℕ) :
    rightRegularCyclicPartialProduct (G := G) (B := B) σ f (i + 1) *
        (rightRegularCyclicPartialProduct (G := G) (B := B) σ f i)⁻¹ =
      f (σ ^ i) := by
  rw [rightRegularCyclicPartialProduct_succ]
  simp [mul_comm, mul_assoc]

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The product-one condition gives the wrap-around coboundary equation for
the cyclic partial primitive. -/
theorem rightRegularCyclicPartialProduct_wrap_mul_inv_of_eq_one
    (σ : G) (f : G → B) {n : ℕ} (hn : 0 < n)
    (hprod : rightRegularCyclicPartialProduct (G := G) (B := B) σ f n = 1) :
    rightRegularCyclicPartialProduct (G := G) (B := B) σ f 0 *
        (rightRegularCyclicPartialProduct (G := G) (B := B) σ f (n - 1))⁻¹ =
      f (σ ^ (n - 1)) := by
  cases n with
  | zero => cases hn
  | succ n =>
      have hlast :
          rightRegularCyclicPartialProduct (G := G) (B := B) σ f n * f (σ ^ n) = 1 := by
        simpa [rightRegularCyclicPartialProduct_succ] using hprod
      have hinv :
          (rightRegularCyclicPartialProduct (G := G) (B := B) σ f n)⁻¹ = f (σ ^ n) :=
        (mul_eq_one_iff_inv_eq).1 hlast
      simpa [rightRegularCyclicPartialProduct, hinv]

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The canonical `ZMod |G|` index of a group element with respect to a chosen
cyclic generator. -/
noncomputable def rightRegularCyclicIndex
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (x : G) :
    ZMod (Fintype.card G) :=
  Classical.choose (IsCyclic.unique_zpow_zmod (a := σ) hgen x)

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The cyclic index represents the original group element. -/
theorem rightRegularCyclicIndex_spec
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (x : G) :
    x = σ ^ (rightRegularCyclicIndex (G := G) σ hgen x).val := by
  simpa [rightRegularCyclicIndex] using
    (Classical.choose_spec (IsCyclic.unique_zpow_zmod (a := σ) hgen x)).1

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- If a concrete `ZMod |G|` representative is known, the cyclic index chooser
returns it. -/
theorem rightRegularCyclicIndex_eq_of_repr
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ)
    {x : G} {m : ZMod (Fintype.card G)} (hm : x = σ ^ m.val) :
    rightRegularCyclicIndex (G := G) σ hgen x = m := by
  exact ((Classical.choose_spec (IsCyclic.unique_zpow_zmod (a := σ) hgen x)).2 m hm).symm

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- On natural powers in the standard range, the cyclic index has the expected
value. -/
theorem rightRegularCyclicIndex_val_pow_of_lt
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ)
    {i : ℕ} (hi : i < Fintype.card G) :
    (rightRegularCyclicIndex (G := G) σ hgen (σ ^ i)).val = i := by
  have hidx :
      rightRegularCyclicIndex (G := G) σ hgen (σ ^ i) =
        (i : ZMod (Fintype.card G)) := by
    apply rightRegularCyclicIndex_eq_of_repr (G := G) σ hgen
    simp [ZMod.val_natCast_of_lt hi]
  rw [hidx, ZMod.val_natCast_of_lt hi]

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The group-element-indexed primitive candidate obtained from the cyclic
partial products. -/
noncomputable def rightRegularCyclicPrimitive
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (f : G → B) : G → B :=
  fun x =>
    rightRegularCyclicPartialProduct (G := G) (B := B) σ f
      (rightRegularCyclicIndex (G := G) σ hgen x).val

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Away from the wrap-around index, the cyclic primitive solves the
right-regular coboundary equation. -/
theorem rightRegularCyclicPrimitive_mul_sigma_mul_inv_of_index_succ_lt
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (f : G → B) (x : G)
    (hix : (rightRegularCyclicIndex (G := G) σ hgen x).val + 1 < Fintype.card G) :
    rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f (x * σ) *
        (rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f x)⁻¹ =
      f x := by
  let i := (rightRegularCyclicIndex (G := G) σ hgen x).val
  have hi : i + 1 < Fintype.card G := by
    simpa [i] using hix
  have hx : x = σ ^ i := by
    simpa [i] using rightRegularCyclicIndex_spec (G := G) σ hgen x
  have hxσ : x * σ = σ ^ (i + 1) := by
    calc
      x * σ = σ ^ i * σ := by rw [hx]
      _ = σ ^ (i + 1) := (pow_succ σ i).symm
  have hidx_xσ :
      (rightRegularCyclicIndex (G := G) σ hgen (x * σ)).val = i + 1 := by
    rw [hxσ]
    exact rightRegularCyclicIndex_val_pow_of_lt (G := G) σ hgen hi
  change rightRegularCyclicPartialProduct (G := G) (B := B) σ f
        (rightRegularCyclicIndex (G := G) σ hgen (x * σ)).val *
      (rightRegularCyclicPartialProduct (G := G) (B := B) σ f
        (rightRegularCyclicIndex (G := G) σ hgen x).val)⁻¹ = f x
  rw [hidx_xσ, show (rightRegularCyclicIndex (G := G) σ hgen x).val = i by rfl, hx]
  exact rightRegularCyclicPartialProduct_succ_mul_inv (G := G) (B := B) σ f i

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- At the wrap-around index, the product-one condition makes the cyclic
primitive solve the right-regular coboundary equation. -/
theorem rightRegularCyclicPrimitive_mul_sigma_mul_inv_of_index_eq_card_sub_one
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (f : G → B) (x : G)
    (hix : (rightRegularCyclicIndex (G := G) σ hgen x).val = Fintype.card G - 1)
    (hprod :
      rightRegularCyclicPartialProduct (G := G) (B := B) σ f (Fintype.card G) = 1) :
    rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f (x * σ) *
        (rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f x)⁻¹ =
      f x := by
  have hcard_pos : 0 < Fintype.card G := Fintype.card_pos
  let i := (rightRegularCyclicIndex (G := G) σ hgen x).val
  have hi : i = Fintype.card G - 1 := by
    simpa [i] using hix
  have hx : x = σ ^ i := by
    simpa [i] using rightRegularCyclicIndex_spec (G := G) σ hgen x
  have horder : orderOf σ = Fintype.card G := by
    simpa [Nat.card_eq_fintype_card] using
      orderOf_eq_card_of_forall_mem_zpowers (g := σ) hgen
  have hpow_card : σ ^ Fintype.card G = 1 := by
    rw [← horder]
    exact pow_orderOf_eq_one σ
  have hxσ : x * σ = 1 := by
    calc
      x * σ = σ ^ i * σ := by rw [hx]
      _ = σ ^ (i + 1) := (pow_succ σ i).symm
      _ = σ ^ Fintype.card G := by
        rw [hi, Nat.sub_add_cancel (Nat.succ_le_of_lt hcard_pos)]
      _ = 1 := hpow_card
  have hidx_xσ :
      (rightRegularCyclicIndex (G := G) σ hgen (x * σ)).val = 0 := by
    have hidx :
        rightRegularCyclicIndex (G := G) σ hgen (x * σ) =
          (0 : ZMod (Fintype.card G)) := by
      apply rightRegularCyclicIndex_eq_of_repr (G := G) σ hgen
      simp [hxσ]
    rw [hidx]
    simp
  have hwrap :
      rightRegularCyclicPartialProduct (G := G) (B := B) σ f 0 *
          (rightRegularCyclicPartialProduct (G := G) (B := B) σ f
            (Fintype.card G - 1))⁻¹ =
        f (σ ^ (Fintype.card G - 1)) :=
    rightRegularCyclicPartialProduct_wrap_mul_inv_of_eq_one
      (G := G) (B := B) σ f hcard_pos hprod
  change rightRegularCyclicPartialProduct (G := G) (B := B) σ f
        (rightRegularCyclicIndex (G := G) σ hgen (x * σ)).val *
      (rightRegularCyclicPartialProduct (G := G) (B := B) σ f
        (rightRegularCyclicIndex (G := G) σ hgen x).val)⁻¹ = f x
  rw [hidx_xσ, hix, hx, hi]
  exact hwrap

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- If the cyclic partial product over a full period is `1`, the group-indexed
cyclic primitive solves the right-regular coboundary equation at every point. -/
theorem rightRegularCyclicPrimitive_mul_sigma_mul_inv_of_partialProduct_eq_one
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) (f : G → B)
    (hprod :
      rightRegularCyclicPartialProduct (G := G) (B := B) σ f (Fintype.card G) = 1)
    (x : G) :
    rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f (x * σ) *
        (rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f x)⁻¹ =
      f x := by
  have hcard_pos : 0 < Fintype.card G := Fintype.card_pos
  have : NeZero (Fintype.card G) := ⟨hcard_pos.ne'⟩
  let i := (rightRegularCyclicIndex (G := G) σ hgen x).val
  have hi_lt : i < Fintype.card G := by
    simpa [i] using ZMod.val_lt (rightRegularCyclicIndex (G := G) σ hgen x)
  by_cases hsucc : i + 1 < Fintype.card G
  · exact rightRegularCyclicPrimitive_mul_sigma_mul_inv_of_index_succ_lt
      (G := G) (B := B) σ hgen f x (by simpa [i] using hsucc)
  · have hsucc_le : i + 1 ≤ Fintype.card G := Nat.succ_le_of_lt hi_lt
    have hcard_le : Fintype.card G ≤ i + 1 := le_of_not_gt hsucc
    have hsucc_eq : i + 1 = Fintype.card G := le_antisymm hsucc_le hcard_le
    have hlast : i = Fintype.card G - 1 := by
      rw [← hsucc_eq]
      simp
    exact rightRegularCyclicPrimitive_mul_sigma_mul_inv_of_index_eq_card_sub_one
      (G := G) (B := B) σ hgen f x (by simpa [i] using hlast) hprod

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- A right-regular norm-kernel element has product `1` along one full cyclic
enumeration by a generator. -/
theorem rightRegularFunction_prod_powers_eq_one_of_mem_normKernel
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ)
    {f : G → B}
    (hf : f ∈ rightRegularFunctionNormKernelSubgroup (G := G) (B := B)) :
    (Finset.range (Nat.card G)).prod (fun i => f (σ ^ i)) = 1 := by
  classical
  have hprod : (∏ g : G, f g) = 1 :=
    (rightRegularFunction_mem_normKernelSubgroup_iff (G := G) (B := B) f).1 hf
  have hcard : orderOf σ = Nat.card G :=
    orderOf_eq_card_of_forall_mem_zpowers (g := σ) hgen
  have hinj : Set.InjOn (fun i : ℕ => σ ^ i) (Finset.range (Nat.card G) : Set ℕ) := by
    intro i hi j hj hij
    have hmod : i ≡ j [MOD orderOf σ] := (pow_eq_pow_iff_modEq (x := σ)).1 hij
    rw [hcard] at hmod
    exact Nat.ModEq.eq_of_lt_of_lt hmod (by simpa using hi) (by simpa using hj)
  have himage :
      Finset.image (fun i : ℕ => σ ^ i) (Finset.range (Nat.card G)) = Finset.univ :=
    IsCyclic.image_range_card (a := σ) hgen
  calc
    (Finset.range (Nat.card G)).prod (fun i => f (σ ^ i)) =
        (Finset.image (fun i : ℕ => σ ^ i) (Finset.range (Nat.card G))).prod
          (fun x => f x) := by
      exact (Finset.prod_image (s := Finset.range (Nat.card G))
        (g := fun i : ℕ => σ ^ i) (f := f) hinj).symm
    _ = ∏ x : G, f x := by
      rw [himage]
    _ = 1 := hprod

omit [Fintype G] [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Membership in the right-regular augmentation subgroup is the pointwise
difference equation `b (x * σ) * (b x)⁻¹ = f x`. -/
theorem rightRegularFunction_mem_augmentationSubgroup_iff
    (σ : G) (f : G → B) :
    f ∈ rightRegularFunctionAugmentationSubgroup (G := G) (B := B) σ ↔
      ∃ b : G → B, ∀ x : G, b (x * σ) * (b x)⁻¹ = f x := by
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  constructor
  · intro hf
    change f ∈ augmentationSubgroup G (G → B) σ at hf
    rcases hf with ⟨b, hb⟩
    refine ⟨b, ?_⟩
    intro x
    have hx := congrArg (fun q : G → B => q x) hb
    change b (x * σ) * (b x)⁻¹ = f x at hx
    exact hx
  · rintro ⟨b, hb⟩
    change f ∈ augmentationSubgroup G (G → B) σ
    refine ⟨b, ?_⟩
    funext x
    change b (x * σ) * (b x)⁻¹ = f x
    exact hb x

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Concrete `H^{-1}` source for the right-regular multiplicative induced
module: every norm-kernel element is an augmentation element. -/
theorem rightRegularFunction_normKernel_le_augmentationSubgroup
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) :
    rightRegularFunctionNormKernelSubgroup (G := G) (B := B) ≤
      rightRegularFunctionAugmentationSubgroup (G := G) (B := B) σ := by
  intro f hf
  have hprod_nat :
      (Finset.range (Nat.card G)).prod (fun i => f (σ ^ i)) = 1 :=
    rightRegularFunction_prod_powers_eq_one_of_mem_normKernel
      (G := G) (B := B) σ hgen hf
  have hprod :
      rightRegularCyclicPartialProduct (G := G) (B := B) σ f (Fintype.card G) = 1 := by
    simpa [rightRegularCyclicPartialProduct, Nat.card_eq_fintype_card] using hprod_nat
  rw [rightRegularFunction_mem_augmentationSubgroup_iff (G := G) (B := B) σ f]
  refine ⟨rightRegularCyclicPrimitive (G := G) (B := B) σ hgen f, ?_⟩
  intro x
  exact rightRegularCyclicPrimitive_mul_sigma_mul_inv_of_partialProduct_eq_one
    (G := G) (B := B) σ hgen f hprod x

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The `H^{-1}` quotient of the right-regular multiplicative induced module
is trivial for a cyclic group generated by `σ`. -/
theorem rightRegularFunction_herbrandHMinusOne_subsingleton
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) :
    Subsingleton (rightRegularFunctionHerbrandHMinusOne (G := G) (B := B) σ) := by
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact herbrandHMinusOne_subsingleton_of_normKernel_le_augmentationSubgroup
    (G := G) (A := G → B) σ
    (rightRegularFunction_normKernel_le_augmentationSubgroup
      (G := G) (B := B) σ hgen)

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Concrete `H⁰` source for induced modules: for the right-regular
multiplicative induced module `G → B`, every fixed point is a norm. -/
theorem rightRegularFunction_fixed_le_tateNormSubgroup :
    rightRegularFunctionFixedSubgroup (G := G) (B := B) ≤
      rightRegularFunctionTateNormSubgroup (G := G) (B := B) := by
  classical
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  intro f hf
  change f ∈ fixedSubgroup G (G → B) at hf
  change f ∈ tateNormSubgroup G (G → B)
  let d : G → B := fun y => if y = 1 then f 1 else 1
  refine ⟨d, ?_⟩
  funext x
  have hfixed_x : f x = f 1 := by
    have hx := congrArg (fun q : G → B => q 1) (hf x)
    change f (1 * x) = f 1 at hx
    simpa using hx
  calc
    tateNorm G (G → B) d x = ∏ g : G, d (x * g) := by
      unfold tateNorm
      let ev : (G → B) →* B := {
        toFun q := q x
        map_one' := rfl
        map_mul' := by
          intro q r
          rfl
      }
      calc
        ((∏ c : G, c • d) : G → B) x = ev (∏ c : G, c • d) := rfl
        _ = ∏ c : G, ev (c • d) := by rw [map_prod]
        _ = ∏ c : G, d (x * c) := by
          refine Finset.prod_congr rfl ?_
          intro c _hc
          change (c • d) x = d (x * c)
          rfl
    _ = f 1 := by
      calc
        (∏ g : G, d (x * g)) = d (x * x⁻¹) := by
          refine Finset.prod_eq_single (s := Finset.univ) x⁻¹ ?_ ?_
          · intro g _hg hg
            have hxg : x * g ≠ 1 := by
              intro hxg_one
              apply hg
              calc
                g = 1 * g := by simp
                _ = (x⁻¹ * x) * g := by simp
                _ = x⁻¹ * (x * g) := by rw [mul_assoc]
                _ = x⁻¹ * 1 := by rw [hxg_one]
                _ = x⁻¹ := by simp
            simp [d, hxg]
          · intro hxinv
            simp at hxinv
        _ = f 1 := by simp [d]
    _ = f x := hfixed_x.symm

omit [CommGroup A] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- The `H⁰` quotient of the right-regular multiplicative induced module is
trivial. This is the degree-zero half of the low-degree Herbrand comparison. -/
theorem rightRegularFunction_herbrandH0_subsingleton :
    Subsingleton (rightRegularFunctionHerbrandH0 (G := G) (B := B)) := by
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact herbrandH0_subsingleton_of_fixed_le_tateNormSubgroup
    (G := G) (A := G → B) (rightRegularFunction_fixed_le_tateNormSubgroup
      (G := G) (B := B))

omit [CommGroup C] [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Transport `H⁰` vanishing from the right-regular trivial-subgroup model
along an explicit multiplicative equivalence. -/
theorem herbrandH0_subsingleton_of_equiv_rightRegularFunction
    (e : A ≃* (G → B))
    (he : ∀ (g : G) (a : A) (x : G), e (g • a) x = e a (x * g)) :
    Subsingleton (HerbrandH0 G A) := by
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact herbrandH0_subsingleton_of_mulEquiv
    (G := G) (A := A) (B := G → B) e
    (by
      intro g a
      funext x
      change e (g • a) x = e a (x * g)
      exact he g a x)
    (rightRegularFunction_fixed_le_tateNormSubgroup (G := G) (B := B))

omit [CommGroup C] [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Transport `H^{-1}` vanishing from the right-regular trivial-subgroup model
along an explicit multiplicative equivalence. -/
theorem herbrandHMinusOne_subsingleton_of_equiv_rightRegularFunction
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ)
    (e : A ≃* (G → B))
    (he : ∀ (g : G) (a : A) (x : G), e (g • a) x = e a (x * g)) :
    Subsingleton (HerbrandHMinusOne G A σ) := by
  let := rightRegularFunctionMulDistribMulAction (G := G) (B := B)
  exact herbrandHMinusOne_subsingleton_of_mulEquiv
    (G := G) (A := A) (B := G → B) e
    (by
      intro g a
      funext x
      change e (g • a) x = e a (x * g)
      exact he g a x)
    σ
    (rightRegularFunction_normKernel_le_augmentationSubgroup
      (G := G) (B := B) σ hgen)

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- A distributive action on an additive group induces a multiplicative action
on its `Multiplicative` wrapper. -/
@[reducible] def multiplicativeMulDistribMulActionOfDistribMulAction
    (G : Type uG) (M : Type uA) [Group G] [AddCommGroup M]
    [DistribMulAction G M] :
    MulDistribMulAction G (Multiplicative M) where
  smul g m := Multiplicative.ofAdd (g • Multiplicative.toAdd m)
  one_smul := by
    intro m
    change Multiplicative.ofAdd (1 • Multiplicative.toAdd m) =
      Multiplicative.ofAdd (Multiplicative.toAdd m)
    rw [one_smul]
  mul_smul := by
    intro g h m
    change Multiplicative.ofAdd ((g * h) • Multiplicative.toAdd m) =
      Multiplicative.ofAdd (g • h • Multiplicative.toAdd m)
    rw [mul_smul]
  smul_mul := by
    intro g m n
    change Multiplicative.ofAdd (g • Multiplicative.toAdd (m * n)) =
      Multiplicative.ofAdd
        (g • Multiplicative.toAdd m + g • Multiplicative.toAdd n)
    rw [show Multiplicative.toAdd (m * n) =
        Multiplicative.toAdd m + Multiplicative.toAdd n from rfl]
    rw [smul_add]
  smul_one := by
    intro g
    change Multiplicative.ofAdd (g • (0 : M)) = Multiplicative.ofAdd (0 : M)
    rw [smul_zero]

omit [Group G] [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Pointwise conversion between a multiplicative wrapper on additive
functions and functions into the multiplicative wrapper. -/
def multiplicativeFunctionMulEquiv
    (G : Type uG) (D : Type uB) [AddCommGroup D] :
    Multiplicative (G → D) ≃* (G → Multiplicative D) where
  toFun f := fun x => Multiplicative.ofAdd (Multiplicative.toAdd f x)
  invFun f := Multiplicative.ofAdd (fun x => Multiplicative.toAdd (f x))
  left_inv := by
    intro f
    rfl
  right_inv := by
    intro f
    funext x
    rfl
  map_mul' := by
    intro f h
    funext x
    rfl

omit [Group G] [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Convert an additive equivalence with a function space into the
multiplicative right-regular function model used by the Herbrand quotient API. -/
def mulEquivRightRegularFunctionOfAddEquiv
    (G : Type uG) {M : Type uA} {D : Type uB}
    [AddCommGroup M] [AddCommGroup D] (e : M ≃+ (G → D)) :
    Multiplicative M ≃* (G → Multiplicative D) where
  toFun m := fun x => Multiplicative.ofAdd (e (Multiplicative.toAdd m) x)
  invFun f := Multiplicative.ofAdd (e.symm (fun x => Multiplicative.toAdd (f x)))
  left_inv := by
    intro m
    change Multiplicative.ofAdd
        (e.symm (e (Multiplicative.toAdd m))) =
      Multiplicative.ofAdd (Multiplicative.toAdd m)
    exact congrArg Multiplicative.ofAdd (e.left_inv (Multiplicative.toAdd m))
  right_inv := by
    intro f
    funext x
    change Multiplicative.ofAdd
        (e (e.symm (fun y : G => Multiplicative.toAdd (f y))) x) =
      Multiplicative.ofAdd (Multiplicative.toAdd (f x))
    exact congrArg Multiplicative.ofAdd
      (congrArg (fun q : G → D => q x)
        (e.right_inv (fun y : G => Multiplicative.toAdd (f y))))
  map_mul' := by
    intro m n
    funext x
    change Multiplicative.ofAdd (e (Multiplicative.toAdd (m * n)) x) =
      Multiplicative.ofAdd
        (e (Multiplicative.toAdd m) x + e (Multiplicative.toAdd n) x)
    rw [show Multiplicative.toAdd (m * n) =
        Multiplicative.toAdd m + Multiplicative.toAdd n from rfl]
    exact congrArg Multiplicative.ofAdd
      (congrArg (fun q : G → D => q x)
        (e.map_add (Multiplicative.toAdd m) (Multiplicative.toAdd n)))

omit [Fintype G] [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- Equivariance of `mulEquivRightRegularFunctionOfAddEquiv`, assuming the
input additive equivalence is right-regular equivariant pointwise. -/
theorem mulEquivRightRegularFunctionOfAddEquiv_commutes
    {M : Type uA} {D : Type uB}
    [AddCommGroup M] [DistribMulAction G M] [AddCommGroup D]
    (e : M ≃+ (G → D))
    (he : ∀ (g : G) (m : M) (x : G), e (g • m) x = e m (x * g))
    (g : G) (m : Multiplicative M) (x : G) :
    letI := multiplicativeMulDistribMulActionOfDistribMulAction G M
    mulEquivRightRegularFunctionOfAddEquiv G e (g • m) x =
      mulEquivRightRegularFunctionOfAddEquiv G e m (x * g) := by
  change Multiplicative.ofAdd (e (g • Multiplicative.toAdd m) x) =
    Multiplicative.ofAdd (e (Multiplicative.toAdd m) (x * g))
  exact congrArg Multiplicative.ofAdd (he g (Multiplicative.toAdd m) x)

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- `H⁰` vanishing for a multiplicative wrapper transported from an additive
right-regular equivalence. -/
theorem herbrandH0_subsingleton_of_addEquiv_rightRegularFunction
    {M : Type uA} {D : Type uB}
    [AddCommGroup M] [DistribMulAction G M] [AddCommGroup D]
    (e : M ≃+ (G → D))
    (he : ∀ (g : G) (m : M) (x : G), e (g • m) x = e m (x * g)) :
    letI := multiplicativeMulDistribMulActionOfDistribMulAction G M
    Subsingleton (HerbrandH0 G (Multiplicative M)) := by
  let := multiplicativeMulDistribMulActionOfDistribMulAction G M
  let : MulDistribMulAction G (Multiplicative D) := {
    smul _ d := d
    one_smul := by
      intro d
      rfl
    mul_smul := by
      intro _ _ d
      rfl
    smul_mul := by
      intro _ d e
      rfl
    smul_one := by
      intro _
      rfl
  }
  exact herbrandH0_subsingleton_of_equiv_rightRegularFunction
    (G := G) (A := Multiplicative M) (B := Multiplicative D)
    (mulEquivRightRegularFunctionOfAddEquiv G e)
    (by
      intro g m x
      exact mulEquivRightRegularFunctionOfAddEquiv_commutes
        (G := G) e he g m x)

omit [CommGroup A] [CommGroup B] [CommGroup C]
    [MulDistribMulAction G A] [MulDistribMulAction G B]
    [MulDistribMulAction G C] in
/-- `H^{-1}` vanishing for a multiplicative wrapper transported from an
additive right-regular equivalence. -/
theorem herbrandHMinusOne_subsingleton_of_addEquiv_rightRegularFunction
    {M : Type uA} {D : Type uB}
    [AddCommGroup M] [DistribMulAction G M] [AddCommGroup D]
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ)
    (e : M ≃+ (G → D))
    (he : ∀ (g : G) (m : M) (x : G), e (g • m) x = e m (x * g)) :
    letI := multiplicativeMulDistribMulActionOfDistribMulAction G M
    Subsingleton (HerbrandHMinusOne G (Multiplicative M) σ) := by
  let := multiplicativeMulDistribMulActionOfDistribMulAction G M
  let : MulDistribMulAction G (Multiplicative D) := {
    smul _ d := d
    one_smul := by
      intro d
      rfl
    mul_smul := by
      intro _ _ d
      rfl
    smul_mul := by
      intro _ d e
      rfl
    smul_one := by
      intro _
      rfl
  }
  exact herbrandHMinusOne_subsingleton_of_equiv_rightRegularFunction
    (G := G) (A := Multiplicative M) (B := Multiplicative D)
    σ hgen (mulEquivRightRegularFunctionOfAddEquiv G e)
    (by
      intro g m x
      exact mulEquivRightRegularFunctionOfAddEquiv_commutes
        (G := G) e he g m x)

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Quotient-cardinality source for `H⁰(G,A)=A^G/N_G A`. -/
theorem card_fixedSubgroup_eq_card_herbrandH0_mul_card_tateNormSubgroup [Finite A] :
    Nat.card (fixedSubgroup G A) =
      Nat.card (HerbrandH0 G A) * Nat.card (tateNormSubgroup G A) := by
  simpa [HerbrandH0,
    card_subgroupOf_eq_card (tateNormSubgroup_le_fixedSubgroup (G := G) (A := A))] using
    (Subgroup.card_eq_card_quotient_mul_card_subgroup
      ((tateNormSubgroup G A).subgroupOf (fixedSubgroup G A)))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- Quotient-cardinality source for
`H^{-1}(G,A)=ker(N_G)/I_G A`. -/
theorem card_normKernelSubgroup_eq_card_herbrandHMinusOne_mul_card_augmentationSubgroup
    (σ : G) [Finite A] :
    Nat.card (normKernelSubgroup G A) =
      Nat.card (HerbrandHMinusOne G A σ) *
        Nat.card (augmentationSubgroup G A σ) := by
  simpa [HerbrandHMinusOne,
    card_subgroupOf_eq_card (augmentationSubgroup_le_normKernelSubgroup (G := G) (A := A) σ)] using
    (Subgroup.card_eq_card_quotient_mul_card_subgroup
      ((augmentationSubgroup G A σ).subgroupOf (normKernelSubgroup G A)))

omit [CommGroup B] [CommGroup C]
    [MulDistribMulAction G B] [MulDistribMulAction G C] in
/-- The two low-degree Herbrand quotients of a finite cyclic module have equal
cardinality, the finite-module source for Herbrand-quotient multiplicativity. -/
theorem herbrand_finite_module_card_eq
    (σ : G) (hgen : ∀ g : G, g ∈ Subgroup.zpowers σ) [Finite A] :
    Nat.card (HerbrandH0 G A) = Nat.card (HerbrandHMinusOne G A σ) := by
  have h0 := card_fixedSubgroup_eq_card_herbrandH0_mul_card_tateNormSubgroup
    (G := G) (A := A)
  have hm := card_normKernelSubgroup_eq_card_herbrandHMinusOne_mul_card_augmentationSubgroup
    (G := G) (A := A) σ
  have hbal := herbrand_finite_module_cardinality_balance
    (G := G) (A := A) σ hgen
  rw [h0, hm] at hbal
  have hfactor :
      Nat.card (HerbrandH0 G A) *
          (Nat.card (tateNormSubgroup G A) * Nat.card (augmentationSubgroup G A σ)) =
        Nat.card (HerbrandHMinusOne G A σ) *
          (Nat.card (tateNormSubgroup G A) * Nat.card (augmentationSubgroup G A σ)) := by
    calc
      Nat.card (HerbrandH0 G A) *
          (Nat.card (tateNormSubgroup G A) * Nat.card (augmentationSubgroup G A σ))
          =
          (Nat.card (HerbrandH0 G A) * Nat.card (tateNormSubgroup G A)) *
            Nat.card (augmentationSubgroup G A σ) := by
            ac_rfl
      _ = (Nat.card (HerbrandHMinusOne G A σ) *
            Nat.card (augmentationSubgroup G A σ)) *
            Nat.card (tateNormSubgroup G A) := hbal
      _ = Nat.card (HerbrandHMinusOne G A σ) *
          (Nat.card (tateNormSubgroup G A) * Nat.card (augmentationSubgroup G A σ)) := by
            ac_rfl
  have hNpos : 0 < Nat.card (tateNormSubgroup G A) :=
    Finite.card_pos (α := tateNormSubgroup G A)
  have hIpos : 0 < Nat.card (augmentationSubgroup G A σ) :=
    Finite.card_pos (α := augmentationSubgroup G A σ)
  exact Nat.mul_right_cancel (Nat.mul_pos hNpos hIpos) hfactor

end Herbrand
end ProfiniteCohomology

end
end CyclicCohomology
