import GaloisCohomology.Kummer.Abstract.KummerAbelianAssembly
import GaloisCohomology.Cyclic.IntegralRepUniverse
import GaloisCohomology.Cyclic.NormKernelVanishing

set_option autoImplicit false

namespace KummerTheory

open CyclicCohomology

/-!
# finite abelian Kummer theory, the finite abelian Kummer decomposition: the exact Delta

For an equivariant additive operator `wp`, the construction defines
`Delta = wp(A_L) ∩ A_K`.  Here fixed modules are represented as ambient
additive subgroups.  The finite abelian assembly supplies finitely many
elements in `wp⁻¹(Delta)` generating `L`; the reverse fixing inclusion uses
the construction datum that the kernel of `wp` is generated by its distinguished
element `xi`.
-/

noncomputable section

variable {G : IntegralRepGroupType} [Group G] [TopologicalSpace G]

/-- Ambient coefficient elements fixed pointwise by a closed abstract field
subgroup. -/
def ambientFixedAddSubgroup (A : Rep ℤ G) (H : ClosedSubgroup G) :
    AddSubgroup A.V := by
  exact
    { carrier := {a | ∀ h : H.toSubgroup, A.ρ h.1 a = a}
      zero_mem' := by simp
      add_mem' := by
        intro a b ha hb h
        rw [map_add, ha h, hb h]
      neg_mem' := by
        intro a ha h
        rw [map_neg, ha h] }

/-- Membership in the ambient fixed subgroup is equivalent to invariance under every
subgroup element. -/
@[simp]
theorem mem_ambientFixedAddSubgroup_iff
    (A : Rep ℤ G) (H : ClosedSubgroup G) (a : A.V) :
    a ∈ ambientFixedAddSubgroup A H ↔
      ∀ h : H.toSubgroup, A.ρ h.1 a = a :=
  Iff.rfl

/-- The `Delta = wp(A_L) ∩ A_K`, as an additive subgroup of the
ambient coefficient module. -/
def kummerDeltaAddSubgroup
    (A : Rep ℤ G) (wp : A ⟶ A) (K L : ClosedSubgroup G) :
    AddSubgroup A.V :=
  (ambientFixedAddSubgroup A L).map
      (AddMonoidHomClass.toAddMonoidHom wp.hom) ⊓
    ambientFixedAddSubgroup A K

/-- The radical set `wp⁻¹(Delta)` in the additive abstract model. -/
def kummerRadicalAddSubgroup
    (A : Rep ℤ G) (wp : A ⟶ A) (K L : ClosedSubgroup G) :
    AddSubgroup A.V :=
  (kummerDeltaAddSubgroup A wp K L).comap
    (AddMonoidHomClass.toAddMonoidHom wp.hom)

/-- The Kummer radical consists of fixed elements annihilated by the Kummer exponent. -/
@[simp]
theorem mem_kummerRadicalAddSubgroup_iff
    (A : Rep ℤ G) (wp : A ⟶ A) (K L : ClosedSubgroup G) (a : A.V) :
    a ∈ kummerRadicalAddSubgroup A wp K L ↔
      wp.hom a ∈ kummerDeltaAddSubgroup A wp K L :=
  Iff.rfl

/-- If `ker(wp)` is generated by the `G_K`-fixed element `xi`, every member
of `wp⁻¹(wp(A_L) ∩ A_K)` is fixed by `G_L`.  Only the inclusion
`ker(wp) ≤ ℤ xi` is needed for this direction. -/
theorem kummerRadical_fixed_of_ker_le_zmultiples
    (A : Rep ℤ G) (wp : A ⟶ A) (K L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.toSubgroup)
    (xi : A.V)
    (hxi_fixed : ∀ k : K.toSubgroup, A.ρ k.1 xi = xi)
    (hker : AddMonoidHom.ker (AddMonoidHomClass.toAddMonoidHom wp.hom) ≤
      AddSubgroup.zmultiples xi)
    {a : A.V} (ha : a ∈ kummerRadicalAddSubgroup A wp K L)
    (l : L.toSubgroup) :
    A.ρ l.1 a = a := by
  have haDelta : wp.hom a ∈ kummerDeltaAddSubgroup A wp K L := ha
  have haImage : wp.hom a ∈
      (ambientFixedAddSubgroup A L).map
        (AddMonoidHomClass.toAddMonoidHom wp.hom) :=
    haDelta.1
  obtain ⟨b, hb_fixed, hba⟩ := haImage
  have hba' : wp.hom b = wp.hom a := hba
  have hd_ker : a - b ∈
      AddMonoidHom.ker (AddMonoidHomClass.toAddMonoidHom wp.hom) := by
    rw [AddMonoidHom.mem_ker]
    change wp.hom (a - b) = 0
    rw [map_sub, ← hba', sub_self]
  obtain ⟨z, hz⟩ := AddSubgroup.mem_zmultiples_iff.mp (hker hd_ker)
  have hd_fixed : A.ρ l.1 (a - b) = a - b := by
    rw [← hz, map_zsmul, hxi_fixed ⟨l, hLK l.property⟩]
  have hb : A.ρ l.1 b = b :=
    (mem_ambientFixedAddSubgroup_iff A L b).1 hb_fixed l
  calc
    A.ρ l.1 a = A.ρ l.1 ((a - b) + b) := by rw [sub_add_cancel]
    _ = A.ρ l.1 (a - b) + A.ρ l.1 b := by rw [map_add]
    _ = (a - b) + b := by rw [hd_fixed, hb]
    _ = a := sub_add_cancel a b

/-- Exact finite-abelian Delta endpoint of the finite abelian Kummer decomposition:
`L = K(wp⁻¹(wp(A_L) ∩ A_K))`.

The cyclic factors, their radical generators, and the inclusion of those
generators in `wp⁻¹(Delta)` are constructed in the proof.  The only
additional operator datum beyond the finite assembly is the kernel
generation condition. -/
theorem finiteAbelian_kummerRadical_fixingSubgroup_eq
    [IsTopologicalGroup G]
    (A : Rep ℤ G) (hAxiom : SatisfiesCyclicNormKernelVanishing A)
    (hcontinuous : IsContinuousDiscreteRepresentation A)
    (K L : ClosedSubgroup G) (hLK : L.toSubgroup ≤ K.toSubgroup)
    [hnormal : (extensionSubgroup (G := G) K L hLK).Normal]
    [hfinite : Finite (K.toSubgroup ⧸ extensionSubgroup (G := G) K L hLK)]
    [IsMulCommutative
      (K.toSubgroup ⧸ extensionSubgroup (G := G) K L hLK)]
    (wp : A ⟶ A) (n : ℕ+) (xi : A.V)
    (hxi_order : addOrderOf xi = (n : ℕ))
    (hxi_kernel : wp.hom xi = 0)
    (hxi_fixed : ∀ k : K.toSubgroup, A.ρ k.1 xi = xi)
    (hker : AddMonoidHom.ker (AddMonoidHomClass.toAddMonoidHom wp.hom) ≤
      AddSubgroup.zmultiples xi)
    (hexponent :
      ∀ q : K.toSubgroup ⧸ extensionSubgroup (G := G) K L hLK,
        q ^ (n : ℕ) = 1) :
    closedSetFixingSubgroup A hcontinuous K
      (kummerRadicalAddSubgroup A wp K L : Set A.V) = L := by
  obtain ⟨S, _hSfinite, hwp_fixed, hgenerate⟩ :=
    finiteAbelian_globalOperator_generators
      A hAxiom hcontinuous K L hLK wp n xi hxi_order hxi_kernel hxi_fixed
        hexponent
  have hSpreimage : S ⊆ (kummerRadicalAddSubgroup A wp K L : Set A.V) := by
    intro a ha
    change a ∈ kummerRadicalAddSubgroup A wp K L
    apply (mem_kummerRadicalAddSubgroup_iff A wp K L a).2
    constructor
    · refine ⟨a, ?_, rfl⟩
      rw [← hgenerate]
      intro l
      exact (mem_closedSetFixingSubgroup_iff A hcontinuous K S l.1).1
        l.property |>.2 a ha
    · exact hwp_fixed a ha
  ext sigma
  change sigma ∈ closedSetFixingSubgroup A hcontinuous K
      (kummerRadicalAddSubgroup A wp K L : Set A.V) ↔ sigma ∈ L
  constructor
  · intro hsigma
    have hdata :=
      (mem_closedSetFixingSubgroup_iff A hcontinuous K
        (kummerRadicalAddSubgroup A wp K L : Set A.V) sigma).1 hsigma
    have hsigmaS : sigma ∈ closedSetFixingSubgroup A hcontinuous K S :=
      (mem_closedSetFixingSubgroup_iff A hcontinuous K S sigma).2
        ⟨hdata.1, fun a ha => hdata.2 a (hSpreimage ha)⟩
    rwa [hgenerate] at hsigmaS
  · intro hsigmaL
    apply (mem_closedSetFixingSubgroup_iff A hcontinuous K
      (kummerRadicalAddSubgroup A wp K L : Set A.V) sigma).2
    refine ⟨hLK hsigmaL, ?_⟩
    intro a ha
    exact kummerRadical_fixed_of_ker_le_zmultiples
      A wp K L hLK xi hxi_fixed hker ha ⟨sigma, hsigmaL⟩

end
end KummerTheory
