import Mathlib.GroupTheory.FiniteAbelian.Duality
import GaloisCohomology.Kummer.Concrete.FiniteCharacterEquiv

set_option autoImplicit false

/-!
# finite actual-field form

Let `L/K` be a finite abelian Galois extension whose Galois group is killed by
`n`, and suppose that `K` contains a primitive `n`-th root of unity.  This file
proves that `L` is generated over `K` by all nonzero `beta : L` such that
`beta ^ n` belongs to `K`.

The proof uses finite-abelian character separation and the finite Kummer
character isomorphism.  It is the finite `n`-th-power, actual-field form of
the Kummer generation theorem; it is not the general abstract-module or infinite statement.
-/

noncomputable section

namespace KummerTheory

open scoped IsMulCommutative

section FiniteKummerGeneration

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- All nonzero elements of `L` whose `n`-th power comes from `K`. -/
def finiteKummerRootSet (n : ℕ+) : Set L :=
  {beta | beta ≠ 0 ∧
    ∃ a : Kˣ, beta ^ (n : ℕ) = algebraMap K L (a : K)}

/-- A primitive `n`-th root in `K` implies the field-level hypothesis that
all `n`-th roots of unity occurring in `L` come from `K`. -/
theorem nthRootsOfUnityInBase_of_primitiveRoots
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty) :
    NthRootsOfUnityInBase (K := K) (L := L) n := by
  let : NeZero (n : ℕ) := ⟨n.ne_zero⟩
  intro u hu
  let eta : rootsOfUnity (n : ℕ) L := ⟨u, hu⟩
  let e : rootsOfUnity (n : ℕ) K ≃* rootsOfUnity (n : ℕ) L :=
    rootsOfUnityEquivOfPrimitiveRoots (algebraMap K L).injective hmu
  refine ⟨(e.symm eta : rootsOfUnity (n : ℕ) K).1, ?_⟩
  apply Units.ext
  exact rootsOfUnityEquivOfPrimitiveRoots_symm_apply
    (algebraMap K L).injective hmu eta

/-- Finite actual-field version of The Kummer generation theorem.

An abelian Galois extension of exponent dividing `n`, over a field containing
the `n`-th roots of unity, is generated by the elements whose `n`-th powers
belong to the base field. -/
theorem finiteKummerRootSet_adjoin_eq_top
    [FiniteDimensional K L] [IsGalois K L] [IsMulCommutative Gal(L/K)]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (hexponent : ∀ sigma : Gal(L/K), sigma ^ (n : ℕ) = 1) :
    IntermediateField.adjoin K (finiteKummerRootSet (K := K) (L := L) n) = ⊤ := by
  let D := chosenFiniteKummerRadicalDatum (K := K) (L := L) n
  let hbase : NthRootsOfUnityInBase (K := K) (L := L) n :=
    nthRootsOfUnityInBase_of_primitiveRoots (K := K) (L := L) n hmu
  let hfixed : ∀ sigma : Gal(L/K), ∀ u : Lˣ,
      u ^ (n : ℕ) = 1 → sigma • u = u :=
    nthRootsOfUnity_fixed (K := K) (L := L) n hbase
  let E : IntermediateField K L :=
    IntermediateField.adjoin K (finiteKummerRootSet (K := K) (L := L) n)
  apply IsGalois.intermediateFieldEquivSubgroup.injective
  rw [map_top, eq_top_iff]
  intro sigma hsigma
  have hsigma_eq_one : sigma = 1 := by
    by_contra hsigma_ne
    let : NeZero (n : ℕ) := ⟨n.ne_zero⟩
    obtain ⟨zeta, hzeta⟩ := hmu
    have hzeta_primitive : IsPrimitiveRoot zeta (n : ℕ) :=
      (mem_primitiveRoots n.pos).1 hzeta
    let : HasEnoughRootsOfUnity K (n : ℕ) :=
      { prim := ⟨zeta, hzeta_primitive⟩
        cyc := rootsOfUnity.isCyclic K (n : ℕ) }
    have hexponent_dvd : Monoid.exponent Gal(L/K) ∣ (n : ℕ) :=
      Monoid.exponent_dvd_of_forall_pow_eq_one (fun tau => by
        simpa only using hexponent tau)
    let : HasEnoughRootsOfUnity K (Monoid.exponent Gal(L/K)) :=
      HasEnoughRootsOfUnity.of_dvd K hexponent_dvd
    obtain ⟨phi, hphi⟩ :=
      CommGroup.exists_apply_ne_one_of_hasEnoughRootsOfUnity Gal(L/K) K hsigma_ne
    let chi : Gal(L/K) →* nthRootsSubgroup L (n : ℕ) :=
      { toFun := fun tau =>
          ⟨Units.map (algebraMap K L).toMonoidHom (phi tau), by
            calc
              (Units.map (algebraMap K L).toMonoidHom (phi tau)) ^ (n : ℕ) =
                  Units.map (algebraMap K L).toMonoidHom ((phi tau) ^ (n : ℕ)) :=
                (map_pow (Units.map (algebraMap K L).toMonoidHom)
                  (phi tau) (n : ℕ)).symm
              _ = Units.map (algebraMap K L).toMonoidHom (phi (tau ^ (n : ℕ))) := by
                exact congrArg (Units.map (algebraMap K L).toMonoidHom)
                  (map_pow phi tau (n : ℕ)).symm
              _ = 1 := by rw [hexponent tau, map_one, map_one]⟩
        map_one' := by
          apply Subtype.ext
          simp
        map_mul' := by
          intro sigma tau
          apply Subtype.ext
          simp }
    have hchi_sigma : chi sigma ≠ 1 := by
      intro hchi
      have hmap : Units.map (algebraMap K L).toMonoidHom (phi sigma) = 1 := by
        simpa [chi] using congrArg Subtype.val hchi
      apply hphi
      apply (Units.map_injective (f := (algebraMap K L).toMonoidHom)
        (algebraMap K L).injective)
      simpa using hmap
    obtain ⟨q, hq⟩ :=
      finiteKummerQuotientCharacter_surjective (K := K) (L := L) n hbase chi
    obtain ⟨delta, rfl⟩ := D.radicalQuotientMk_surjective q
    have hroot_mem : (D.root delta : L) ∈
        finiteKummerRootSet (K := K) (L := L) n := by
      refine ⟨(D.root delta).ne_zero, delta.1, ?_⟩
      exact congrArg Units.val (D.root_pow_eq_map delta)
    have hroot_fixed_val : sigma (D.root delta : L) = D.root delta :=
      hsigma ⟨D.root delta,
        IntermediateField.subset_adjoin K
          (finiteKummerRootSet (K := K) (L := L) n) hroot_mem⟩
    have hroot_fixed : sigma • D.root delta = D.root delta := by
      apply Units.ext
      exact hroot_fixed_val
    have hkummer_sigma : D.kummerCharacterWithoutSection hfixed delta sigma = 1 := by
      apply Subtype.ext
      change D.rootCharacter delta hfixed sigma = 1
      rw [D.rootCharacter_apply]
      change rootQuotient (K := K) (L := L) (D.root delta) sigma = 1
      exact (rootQuotient_eq_one_iff (K := K) (L := L) (D.root delta) sigma).2
        hroot_fixed
    have hchi_eq : D.kummerCharacterWithoutSection hfixed delta = chi := by
      rw [← D.quotientKummerCharacterWithoutSection_mk delta hfixed]
      exact hq
    apply hchi_sigma
    rw [← hchi_eq]
    exact hkummer_sigma
  rw [hsigma_eq_one]
  exact one_mem _

end FiniteKummerGeneration

end KummerTheory
