import GaloisCohomology.Kummer.Concrete.FiniteGeneration

set_option autoImplicit false

/-!
# infinite actual-field form

For an arbitrary Galois extension `Ω/K`, each element of `Ω` lies in a
finite Galois intermediate field.  If the full Galois group is abelian and
killed by `n`, restriction gives the same two properties at that finite
stage.  The finite actual-field case of the Kummer generation theorem then shows that the
element belongs to the field generated by the global `n`-th radicals.

This is the actual-field `n`-th-power case.  It does not claim the general
abstract-operator statement of the Kummer generation theorem.
-/

noncomputable section

namespace KummerTheory

open scoped IsMulCommutative

variable {K Ω : Type*} [Field K] [Field Ω] [Algebra K Ω]

/-- The Kummer generation theorem for a possibly infinite actual-field
Galois extension and the `n`-th-power operator.

The finite-stage abelian and exponent hypotheses are derived through the
surjective restriction map; they are not supplied as extra assumptions. -/
theorem kummerRootSet_adjoin_eq_top
    [IsGalois K Ω] [IsMulCommutative Gal(Ω/K)]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (hexponent : ∀ σ : Gal(Ω/K), σ ^ (n : ℕ) = 1) :
    IntermediateField.adjoin K (finiteKummerRootSet (K := K) (L := Ω) n) = ⊤ := by
  let U : IntermediateField K Ω :=
    IntermediateField.adjoin K (finiteKummerRootSet (K := K) (L := Ω) n)
  apply top_unique
  intro x _
  let E : FiniteGaloisIntermediateField K Ω :=
    FiniteGaloisIntermediateField.adjoin K {x}
  let res : Gal(Ω/K) →* Gal(E/K) := AlgEquiv.restrictNormalHom E
  have hres_surjective : Function.Surjective res :=
    AlgEquiv.restrictNormalHom_surjective Ω
  let : IsMulCommutative Gal(E/K) :=
    { is_comm := ⟨fun σ τ => by
        obtain ⟨σ', rfl⟩ := hres_surjective σ
        obtain ⟨τ', rfl⟩ := hres_surjective τ
        rw [← map_mul, mul_comm σ' τ', map_mul]⟩ }
  have hE_exponent : ∀ σ : Gal(E/K), σ ^ (n : ℕ) = 1 := by
    intro σ
    obtain ⟨σ', rfl⟩ := hres_surjective σ
    rw [← map_pow, hexponent σ', map_one]
  have hE_generation :
      IntermediateField.adjoin K (finiteKummerRootSet (K := K) (L := E) n) = ⊤ :=
    finiteKummerRootSet_adjoin_eq_top
      (K := K) (L := E) n hmu hE_exponent
  have hroot_subset : finiteKummerRootSet (K := K) (L := E) n ⊆ U.comap E.val := by
    intro β hβ
    change (β : Ω) ∈ U
    apply IntermediateField.subset_adjoin K
      (finiteKummerRootSet (K := K) (L := Ω) n)
    refine ⟨?_, ?_⟩
    · exact (map_ne_zero E.val).2 hβ.1
    · obtain ⟨a, ha⟩ := hβ.2
      refine ⟨a, ?_⟩
      simpa using congrArg E.val ha
  have htop_le : (⊤ : IntermediateField K E) ≤ U.comap E.val := by
    rw [← hE_generation]
    exact IntermediateField.adjoin_le_iff.mpr hroot_subset
  let xE : E :=
    ⟨x, FiniteGaloisIntermediateField.subset_adjoin K {x} (Set.mem_singleton x)⟩
  have hxE : xE ∈ U.comap E.val := htop_le (Set.mem_univ xE)
  exact hxE

end KummerTheory
