import GaloisCohomology.Kummer.Concrete.FiniteSupport
import GaloisCohomology.Kummer.Concrete.RestrictedFinite

set_option autoImplicit false

/-!
# infinite inverse inclusion

Any radical appearing in `K(√[n]{Δ})` uses only finitely many of the
adjoined roots.  The corresponding admissible finite-support subgroup
`Δ₀ ≤ Δ` gives a finite Galois Kummer stage.  Applying the finite inverse
theorem at that stage shows that the original radical already belongs to
`Δ₀`, hence to `Δ`.
-/

noncomputable section

namespace KummerTheory

variable {K Omega : Type*} [Field K] [Field Omega] [Algebra K Omega]

section FiniteSupportField

variable (n : ℕ+) (Delta : KummerSubgroup K n) (T : Finset Omega)
  (hT : (T : Set Omega) ⊆
    kummerRootSet (K := K) (Omega := Omega) n Delta.1)

/-- The finite field generated by the selected radical roots. -/
def finiteSupportField : IntermediateField K Omega :=
  IntermediateField.adjoin K (T : Set Omega)

/-- The admissible finite-support subgroup has all of its prescribed roots
in the field generated by `T`. -/
theorem admissibleFiniteSupportSubgroup_le_finiteKummerRadicalSubgroup :
    (admissibleFiniteSupportSubgroup
      (K := K) (Omega := Omega) n Delta T hT).1 ≤
      finiteKummerRadicalSubgroup
        (K := K) (L := finiteSupportField (K := K) T) n := by
  apply sup_le
  · intro a ha
    obtain ⟨b, hb⟩ := (mem_unitNthPowersSubgroup_iff n).1 ha
    refine ⟨Units.map
      (algebraMap K (finiteSupportField (K := K) T)).toMonoidHom b, ?_⟩
    rw [← map_pow, hb]
  · rw [chosenFiniteSupportCoefficientSubgroup, Subgroup.closure_le]
    intro a ha
    change a ∈ chosenFiniteSupportCoefficientSet
      (K := K) (Omega := Omega) n Delta.1 T hT at ha
    classical
    rw [chosenFiniteSupportCoefficientSet] at ha
    obtain ⟨root, _, rfl⟩ := Finset.mem_image.1 ha
    let rootL : finiteSupportField (K := K) T :=
      ⟨root.1, IntermediateField.subset_adjoin K (T : Set Omega) root.property⟩
    have hroot_ne : rootL ≠ 0 := by
      intro hzero
      apply kummerRootSet_ne_zero n Delta.1 (hT root.property)
      exact congrArg Subtype.val hzero
    refine ⟨Units.mk0 rootL hroot_ne, ?_⟩
    apply Units.ext
    apply Subtype.ext
    exact chosenFiniteSupportCoefficient_pow n Delta.1 T hT root

/-- A finite set of integral radical roots generates a finite-dimensional
extension. -/
theorem finiteSupportField_finiteDimensional :
    ((T : Set Omega) ⊆
      kummerRootSet (K := K) (Omega := Omega) n Delta.1) →
      FiniteDimensional K (finiteSupportField (K := K) T) := by
  intro hT'
  apply IntermediateField.finiteDimensional_adjoin
  intro root hroot
  apply IsIntegral.of_pow n.pos
  obtain ⟨a, ha⟩ := hT' hroot
  rw [ha]
  exact isIntegral_algebraMap

/-- Every global root belonging to the finite-support subgroup already lies
in the field generated by `T`.  The ratio with a root in that field is an
`n`-th root of unity and hence lies in `K`. -/
theorem kummerRootSet_admissibleFiniteSupport_subset
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) :
    kummerRootSet (K := K) (Omega := Omega) n
        (admissibleFiniteSupportSubgroup
          (K := K) (Omega := Omega) n Delta T hT).1 ≤
      finiteSupportField (K := K) T := by
  intro beta hbeta
  let Delta0 := admissibleFiniteSupportSubgroup
    (K := K) (Omega := Omega) n Delta T hT
  let L0 := finiteSupportField (K := K) T
  have hbeta_ne : beta ≠ 0 :=
    kummerRootSet_ne_zero n Delta0.1 hbeta
  obtain ⟨a, hbeta_pow⟩ := hbeta
  have ha_radical : a.1 ∈ finiteKummerRadicalSubgroup (K := K) (L := L0) n :=
    admissibleFiniteSupportSubgroup_le_finiteKummerRadicalSubgroup n Delta T hT a.property
  obtain ⟨gamma, hgamma_pow⟩ := ha_radical
  let gammaOmega : Omegaˣ := Units.map L0.val.toMonoidHom gamma
  let betaUnit : Omegaˣ := Units.mk0 beta hbeta_ne
  have hbetaUnit_pow : betaUnit ^ (n : ℕ) =
      Units.map (algebraMap K Omega).toMonoidHom a.1 := by
    apply Units.ext
    exact hbeta_pow
  have hgammaOmega_pow : gammaOmega ^ (n : ℕ) =
      Units.map (algebraMap K Omega).toMonoidHom a.1 := by
    apply Units.ext
    exact congrArg L0.val (congrArg Units.val hgamma_pow)
  have hratio_pow : (betaUnit / gammaOmega) ^ (n : ℕ) = 1 := by
    rw [div_pow, hbetaUnit_pow, hgammaOmega_pow]
    exact div_self' _
  let hbase : NthRootsOfUnityInBase (K := K) (L := Omega) n :=
    nthRootsOfUnityInBase_of_primitiveRoots
      (K := K) (L := Omega) n hmu
  obtain ⟨zeta, hzeta⟩ := hbase (betaUnit / gammaOmega) hratio_pow
  have hbeta_eq : betaUnit =
      Units.map (algebraMap K Omega).toMonoidHom zeta * gammaOmega := by
    rw [hzeta]
    exact (div_mul_cancel betaUnit gammaOmega).symm
  have hbeta_val := congrArg Units.val hbeta_eq
  change (betaUnit : Omega) ∈ L0
  rw [hbeta_val]
  exact L0.mul_mem (L0.algebraMap_mem (zeta : K)) gamma.1.property

/-- The full radical extension attached to the finite-support subgroup is
exactly the field generated by the selected roots. -/
theorem kummerRadicalExtension_admissibleFiniteSupport_eq
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) :
    kummerRadicalExtension (K := K) (Omega := Omega) n
        (admissibleFiniteSupportSubgroup
          (K := K) (Omega := Omega) n Delta T hT).1 =
      finiteSupportField (K := K) T := by
  apply le_antisymm
  · exact IntermediateField.adjoin_le_iff.mpr
      (kummerRootSet_admissibleFiniteSupport_subset n Delta T hT hmu)
  · apply IntermediateField.adjoin_le_iff.mpr
    intro root hroot
    apply IntermediateField.subset_adjoin K
    exact finiteSupportRoot_pow_from_admissibleSubgroup n Delta T hT ⟨root, hroot⟩

/-- Over a separable closure, the finite-support field is Galois. -/
theorem finiteSupportField_isGalois
    [IsSepClosure K Omega]
    (hT' : (T : Set Omega) ⊆
      kummerRootSet (K := K) (Omega := Omega) n Delta.1)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) :
    IsGalois K (finiteSupportField (K := K) T) := by
  rw [← kummerRadicalExtension_admissibleFiniteSupport_eq n Delta T hT' hmu]
  exact kummerRadicalExtension_isGalois n
    (admissibleFiniteSupportSubgroup
      (K := K) (Omega := Omega) n Delta T hT').1

/-- The internal Kummer root set of the finite-support subgroup generates
the finite-support field. -/
theorem finiteSupportField_internalRoots_adjoin_eq_top :
    IntermediateField.adjoin K
      (kummerRootSet
        (K := K) (Omega := finiteSupportField (K := K) T) n
        (admissibleFiniteSupportSubgroup
          (K := K) (Omega := Omega) n Delta T hT).1) = ⊤ := by
  let L0 := finiteSupportField (K := K) T
  let R : IntermediateField K L0 := IntermediateField.adjoin K
    (kummerRootSet (K := K) (Omega := L0) n
      (admissibleFiniteSupportSubgroup
        (K := K) (Omega := Omega) n Delta T hT).1)
  apply top_unique
  intro x _
  have hall : ∀ y : Omega, ∀ hy : y ∈ L0, (⟨y, hy⟩ : L0) ∈ R := by
    intro y hy
    change y ∈ IntermediateField.adjoin K (T : Set Omega) at hy
    induction hy using IntermediateField.adjoin_induction with
    | mem root hroot =>
        apply IntermediateField.subset_adjoin K
        obtain ⟨a, ha⟩ :=
          finiteSupportRoot_pow_from_admissibleSubgroup n Delta T hT ⟨root, hroot⟩
        refine ⟨a, ?_⟩
        apply Subtype.ext
        exact ha
    | algebraMap a => exact R.algebraMap_mem a
    | add x y hx hy ihx ihy => exact R.add_mem ihx ihy
    | inv x hx ihx => exact R.inv_mem ihx
    | mul x y hx hy ihx ihy => exact R.mul_mem ihx ihy
  exact hall x.1 x.property

end FiniteSupportField

section InfiniteInverse

variable [IsSepClosure K Omega]

/-- **the Kummer correspondence, inverse inclusion for an arbitrary admissible
subgroup.**  Any base-field radical in `K(√[n]{Delta})` is already in
`Delta`.  The root is first descended to a finite-support Kummer stage,
where the finite inverse theorem applies. -/
theorem finiteKummerRadicalSubgroup_kummerRadicalExtension_le
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n) :
    finiteKummerRadicalSubgroup
        (K := K)
        (L := kummerRadicalExtension
          (K := K) (Omega := Omega) n Delta.1) n ≤
      Delta.1 := by
  intro a ha
  let E := kummerRadicalExtension
    (K := K) (Omega := Omega) n Delta.1
  obtain ⟨betaE, hbetaE_pow⟩ := ha
  let beta : Omega := (betaE.1 : Omega)
  have hbeta_mem : beta ∈ E := betaE.1.property
  obtain ⟨T, hT, hbetaT, hDelta0, _, _⟩ :=
    exists_admissibleFiniteKummerSupport n Delta hbeta_mem
  let L0 := finiteSupportField (K := K) T
  let Delta0 := admissibleFiniteSupportSubgroup
    (K := K) (Omega := Omega) n Delta T hT
  let betaL0 : L0 := ⟨beta, hbetaT⟩
  have hbeta_ne : beta ≠ 0 := by
    intro hzero
    apply betaE.ne_zero
    apply Subtype.ext
    exact hzero
  have hbetaL0_ne : betaL0 ≠ 0 := by
    intro hzero
    apply hbeta_ne
    exact congrArg Subtype.val hzero
  have haL0 : a ∈ finiteKummerRadicalSubgroup (K := K) (L := L0) n := by
    refine ⟨Units.mk0 betaL0 hbetaL0_ne, ?_⟩
    apply Units.ext
    apply Subtype.ext
    have hpowOmega := congrArg E.val (congrArg Units.val hbetaE_pow)
    change beta ^ (n : ℕ) = algebraMap K Omega (a : K)
    simpa [beta, E] using hpowOmega
  let : FiniteDimensional K L0 :=
    finiteSupportField_finiteDimensional n Delta T hT
  let : IsGalois K L0 :=
    finiteSupportField_isGalois n Delta T hT hmu
  have hradical :
      finiteKummerRadicalSubgroup (K := K) (L := L0) n = Delta0.1 :=
    finiteKummerRadicalSubgroup_eq_of_adjoin
      (K := K) (L := L0) n hmu Delta0
      (admissibleFiniteSupportSubgroup_le_finiteKummerRadicalSubgroup n Delta T hT)
      (finiteSupportField_internalRoots_adjoin_eq_top n Delta T hT)
  apply hDelta0
  rw [← hradical]
  exact haL0

/-- **the Kummer correspondence, subgroup round trip.**  Under the standard
characteristic and roots-of-unity hypotheses, adjoining all prescribed
radicals and then taking the actual radical subgroup recovers `Delta`. -/
theorem finiteKummerRadicalSubgroup_kummerRadicalExtension_eq
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n) :
    finiteKummerRadicalSubgroup
        (K := K)
        (L := kummerRadicalExtension
          (K := K) (Omega := Omega) n Delta.1) n =
      Delta.1 := by
  apply le_antisymm
  · exact finiteKummerRadicalSubgroup_kummerRadicalExtension_le
      n hmu Delta
  · exact le_finiteKummerRadicalSubgroup_kummerRadicalExtension
      n hn Delta.1

end InfiniteInverse

end KummerTheory
