import GaloisCohomology.Kummer.Concrete.FiniteDualSeparation
import GaloisCohomology.Kummer.Concrete.RadicalExtension

set_option autoImplicit false

/-!
# finite restricted Kummer pairing

Let `Delta ≤ Kˣ` contain `Kˣ^n`, and suppose every element of `Delta` has
an `n`-th root in a finite Galois extension `L/K`.  This file restricts the
actual finite Kummer character to

`Delta / Kˣ^n → Hom(Gal(L/K), μₙ(L))`.

The exact kernel theorem for the actual radical subgroup proves this
restricted map injective.  We then transpose the pairing.  If `L` is
generated by the roots belonging to `Delta`, the transpose is injective
because an automorphism in its kernel fixes every generator.

No character-surjectivity or lattice-correspondence conclusion is assumed.
-/

noncomputable section

namespace KummerTheory

section RestrictedFiniteKummer

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- The copy of `Kˣ^n` inside an admissible subgroup `Delta`. -/
def restrictedNthPowersSubgroup
    (n : ℕ+) (Delta : KummerSubgroup K n) : Subgroup Delta.1 :=
  (unitNthPowersSubgroup K n).comap Delta.1.subtype

/-- Restricted power-subgroup membership is characterized by an `n`th-power
witness in the restricted group. -/
@[simp] theorem mem_restrictedNthPowersSubgroup_iff
    (n : ℕ+) (Delta : KummerSubgroup K n) {a : Delta.1} :
    a ∈ restrictedNthPowersSubgroup n Delta ↔
      ∃ b : Kˣ, b ^ (n : ℕ) = a.1 :=
  Iff.rfl

/-- The subgroup-side quotient `Delta / Kˣ^n` from the Kummer correspondence. -/
def RestrictedRadicalQuotient
    (n : ℕ+) (Delta : KummerSubgroup K n) :=
  Delta.1 ⧸ restrictedNthPowersSubgroup n Delta

/-- The commutative group structure on the named restricted radical
quotient. -/
instance restrictedRadicalQuotient_commGroupInstance
    (n : ℕ+) (Delta : KummerSubgroup K n) :
    CommGroup (RestrictedRadicalQuotient n Delta) := by
  change CommGroup (Delta.1 ⧸ restrictedNthPowersSubgroup n Delta)
  infer_instance

/-- Comparison with the group-library presentation of the restricted
radical quotient. -/
def restrictedRadicalQuotientMulEquiv
    (n : ℕ+) (Delta : KummerSubgroup K n) :
    RestrictedRadicalQuotient n Delta ≃*
      (Delta.1 ⧸ restrictedNthPowersSubgroup n Delta) :=
  MulEquiv.refl _

/-- The canonical projection to the named restricted radical quotient. -/
def restrictedRadicalQuotientMk
    (n : ℕ+) (Delta : KummerSubgroup K n) :
    Delta.1 →* RestrictedRadicalQuotient n Delta :=
  QuotientGroup.mk' (restrictedNthPowersSubgroup n Delta)

/-- A restricted radical class is trivial exactly when its representative is a
restricted `n`th power. -/
@[simp]
theorem restrictedRadicalQuotientMk_eq_one_iff
    (n : ℕ+) (Delta : KummerSubgroup K n) (a : Delta.1) :
    restrictedRadicalQuotientMk n Delta a = 1 ↔
      a ∈ restrictedNthPowersSubgroup n Delta := by
  change
    (QuotientGroup.mk' (restrictedNthPowersSubgroup n Delta)) a = 1 ↔ _
  exact QuotientGroup.eq_one_iff a

/-- Equality in the restricted radical quotient is characterized by a restricted power ratio. -/
@[simp]
theorem restrictedRadicalQuotientMk_eq_iff
    (n : ℕ+) (Delta : KummerSubgroup K n) (a b : Delta.1) :
    restrictedRadicalQuotientMk n Delta a =
        restrictedRadicalQuotientMk n Delta b ↔
      a / b ∈ restrictedNthPowersSubgroup n Delta := by
  change
    (QuotientGroup.mk' (restrictedNthPowersSubgroup n Delta)) a =
        (QuotientGroup.mk' (restrictedNthPowersSubgroup n Delta)) b ↔ _
  exact QuotientGroup.eq_iff_div_mem

/-- Every restricted radical class has a representative in `Delta`. -/
theorem restrictedRadicalQuotientMk_surjective
    (n : ℕ+) (Delta : KummerSubgroup K n) :
    Function.Surjective (restrictedRadicalQuotientMk n Delta) := by
  change Function.Surjective
    (QuotientGroup.mk' (restrictedNthPowersSubgroup n Delta))
  exact QuotientGroup.mk'_surjective _

/-- Eliminate a restricted radical quotient through canonical
representatives. -/
theorem restrictedRadicalQuotient_inductionOn
    (n : ℕ+) (Delta : KummerSubgroup K n)
    {motive : RestrictedRadicalQuotient n Delta → Prop}
    (q : RestrictedRadicalQuotient n Delta)
    (mk : ∀ a : Delta.1,
      motive (restrictedRadicalQuotientMk n Delta a)) :
    motive q := by
  exact QuotientGroup.induction_on' q mk

/-- Descend a homomorphism through the named restricted radical quotient. -/
def restrictedRadicalQuotientLift {M : Type*} [Group M]
    (n : ℕ+) (Delta : KummerSubgroup K n) (f : Delta.1 →* M)
    (hf : restrictedNthPowersSubgroup n Delta ≤ MonoidHom.ker f) :
    RestrictedRadicalQuotient n Delta →* M :=
  (QuotientGroup.lift (restrictedNthPowersSubgroup n Delta) f hf).comp
    (restrictedRadicalQuotientMulEquiv n Delta).toMonoidHom

/-- The restricted radical lift evaluates on quotient representatives by the chosen lift. -/
@[simp]
theorem restrictedRadicalQuotientLift_mk {M : Type*} [Group M]
    (n : ℕ+) (Delta : KummerSubgroup K n) (f : Delta.1 →* M)
    (hf : restrictedNthPowersSubgroup n Delta ≤ MonoidHom.ker f)
    (a : Delta.1) :
    restrictedRadicalQuotientLift n Delta f hf
        (restrictedRadicalQuotientMk n Delta a) = f a :=
  rfl

/-- The field-level fixed-roots hypothesis supplied by a primitive root in
the base field. -/
theorem restrictedKummerFixed
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty) :
    ∀ sigma : Gal(L/K), ∀ u : Lˣ,
      u ^ (n : ℕ) = 1 → sigma • u = u :=
  nthRootsOfUnity_fixed (K := K) (L := L) n
    (nthRootsOfUnityInBase_of_primitiveRoots (K := K) (L := L) n hmu)

/-- Include the specified subgroup into the actual radical subgroup of
`L/K`. -/
def restrictedRadicalInclusion
    (n : ℕ+) (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n) :
    Delta.1 →* (chosenFiniteKummerRadicalDatum (K := K) (L := L) n).carrier :=
  Subgroup.inclusion hDelta

/-- The Kummer character restricted from the actual radical subgroup to
the prescribed subgroup `Delta`. -/
def restrictedSubgroupKummerCharacter
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n) :
    Delta.1 →* (Gal(L/K) →* nthRootsSubgroup L (n : ℕ)) :=
  ((chosenFiniteKummerRadicalDatum (K := K) (L := L) n).kummerCharacterWithoutSection
    (restrictedKummerFixed n hmu)).comp
      (restrictedRadicalInclusion n Delta hDelta)

/-- The restricted subgroup character has exactly the expected kernel `Kˣ^n`.
This is inherited from the exact kernel theorem on the actual radical
subgroup; it is not an additional hypothesis. -/
theorem ker_restrictedSubgroupKummerCharacter
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n) :
    MonoidHom.ker (restrictedSubgroupKummerCharacter n hmu Delta hDelta) =
      restrictedNthPowersSubgroup n Delta := by
  let D := chosenFiniteKummerRadicalDatum (K := K) (L := L) n
  let hfixed := restrictedKummerFixed (K := K) (L := L) n hmu
  apply le_antisymm
  · intro a ha
    have hinc : restrictedRadicalInclusion n Delta hDelta a ∈
        MonoidHom.ker (D.kummerCharacterWithoutSection hfixed) := by
      simpa [restrictedSubgroupKummerCharacter, D, hfixed] using ha
    have hpowers : restrictedRadicalInclusion n Delta hDelta a ∈
        D.ambientNthPowersSubgroup := by
      rw [← D.ker_kummerCharacterWithoutSection_eq_ambientNthPowers hfixed]
      exact hinc
    exact (mem_restrictedNthPowersSubgroup_iff n Delta).2
      ((D.mem_ambientNthPowersSubgroup_iff).1 hpowers)
  · intro a ha
    have hpowers : restrictedRadicalInclusion n Delta hDelta a ∈
        D.ambientNthPowersSubgroup :=
      (D.mem_ambientNthPowersSubgroup_iff).2
        ((mem_restrictedNthPowersSubgroup_iff n Delta).1 ha)
    have hker : restrictedRadicalInclusion n Delta hDelta a ∈
        MonoidHom.ker (D.kummerCharacterWithoutSection hfixed) := by
      rw [D.ker_kummerCharacterWithoutSection_eq_ambientNthPowers hfixed]
      exact hpowers
    simpa [restrictedSubgroupKummerCharacter, D, hfixed] using hker

/-- The restricted character descended to `Delta / Kˣ^n`. -/
def restrictedQuotientKummerCharacter
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n) :
    RestrictedRadicalQuotient n Delta →*
      (Gal(L/K) →* nthRootsSubgroup L (n : ℕ)) :=
  restrictedRadicalQuotientLift n Delta
    (restrictedSubgroupKummerCharacter n hmu Delta hDelta)
    (by rw [ker_restrictedSubgroupKummerCharacter n hmu Delta hDelta])

/-- The restricted Kummer character is computed on a quotient representative by
its root character. -/
@[simp] theorem restrictedQuotientKummerCharacter_mk
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (a : Delta.1) :
    restrictedQuotientKummerCharacter n hmu Delta hDelta
        (restrictedRadicalQuotientMk n Delta a) =
      restrictedSubgroupKummerCharacter n hmu Delta hDelta a :=
  rfl

/-- Exactness of the subgroup-level kernel makes the restricted quotient character
injective. -/
theorem restrictedQuotientKummerCharacter_injective
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n) :
    Function.Injective (restrictedQuotientKummerCharacter n hmu Delta hDelta) := by
  intro q r hqr
  revert hqr
  refine restrictedRadicalQuotient_inductionOn
    (motive := fun q =>
      restrictedQuotientKummerCharacter n hmu Delta hDelta q =
          restrictedQuotientKummerCharacter n hmu Delta hDelta r →
        q = r)
    n Delta q ?_
  intro a
  refine restrictedRadicalQuotient_inductionOn
    (motive := fun r =>
      restrictedQuotientKummerCharacter n hmu Delta hDelta
          (restrictedRadicalQuotientMk n Delta a) =
          restrictedQuotientKummerCharacter n hmu Delta hDelta r →
        restrictedRadicalQuotientMk n Delta a = r)
    n Delta r ?_
  intro b hab
  apply (restrictedRadicalQuotientMk_eq_iff n Delta a b).2
  rw [← ker_restrictedSubgroupKummerCharacter n hmu Delta hDelta]
  have hab' :
      restrictedSubgroupKummerCharacter n hmu Delta hDelta a =
        restrictedSubgroupKummerCharacter n hmu Delta hDelta b := by
    exact hab
  rw [MonoidHom.mem_ker, map_div, hab']
  exact div_self' (restrictedSubgroupKummerCharacter n hmu Delta hDelta b)

/-- Transpose the restricted Kummer pairing by evaluation. -/
def restrictedKummerTranspose
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n) :
    Gal(L/K) →*
      (RestrictedRadicalQuotient n Delta →* nthRootsSubgroup L (n : ℕ)) where
  toFun sigma :=
    { toFun := fun q => restrictedQuotientKummerCharacter n hmu Delta hDelta q sigma
      map_one' := by simp
      map_mul' := by
        intro q r
        exact congrArg (fun chi : Gal(L/K) →* nthRootsSubgroup L (n : ℕ) => chi sigma)
          (map_mul (restrictedQuotientKummerCharacter n hmu Delta hDelta) q r) }
  map_one' := by
    apply MonoidHom.ext
    intro q
    exact map_one (restrictedQuotientKummerCharacter n hmu Delta hDelta q)
  map_mul' := by
    intro sigma tau
    apply MonoidHom.ext
    intro q
    exact map_mul (restrictedQuotientKummerCharacter n hmu Delta hDelta q) sigma tau

/-- The restricted Kummer transpose evaluates a radical class against the
corresponding character. -/
@[simp] theorem restrictedKummerTranspose_apply
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (sigma : Gal(L/K)) (q : RestrictedRadicalQuotient n Delta) :
    restrictedKummerTranspose n hmu Delta hDelta sigma q =
      restrictedQuotientKummerCharacter n hmu Delta hDelta q sigma :=
  rfl

/-- If the transposed character of `sigma` is trivial, then `sigma` fixes
every actual `n`-th root belonging to `Delta`.  Independence of the root
choice follows from the fact that all `n`-th roots of unity lie in `K`. -/
theorem restrictedKummerTranspose_fixes_root
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (sigma : Gal(L/K))
    (hsigma : restrictedKummerTranspose n hmu Delta hDelta sigma = 1)
    {beta : L}
    (hbeta : beta ∈ kummerRootSet (K := K) (Omega := L) n Delta.1) :
    sigma beta = beta := by
  let D := chosenFiniteKummerRadicalDatum (K := K) (L := L) n
  let hfixed := restrictedKummerFixed (K := K) (L := L) n hmu
  have hbetaNe : beta ≠ 0 := kummerRootSet_ne_zero n Delta.1 hbeta
  obtain ⟨a, ha⟩ := hbeta
  let aD : D.carrier := restrictedRadicalInclusion n Delta hDelta a
  let betaUnit : Lˣ := Units.mk0 beta hbetaNe
  have hbetaPow : betaUnit ^ (n : ℕ) =
      Units.map (algebraMap K L).toMonoidHom aD.1 := by
    apply Units.ext
    exact ha
  let q : RestrictedRadicalQuotient n Delta :=
    restrictedRadicalQuotientMk n Delta a
  have hvalue : restrictedQuotientKummerCharacter n hmu Delta hDelta q sigma = 1 := by
    have happ := congrArg
      (fun chi : RestrictedRadicalQuotient n Delta →* nthRootsSubgroup L (n : ℕ) =>
        chi q) hsigma
    exact happ
  have hraw : restrictedSubgroupKummerCharacter n hmu Delta hDelta a sigma = 1 := by
    exact hvalue
  have hchosen : D.rootCharacterToMuWithoutSection aD hfixed sigma = 1 := by
    change D.rootCharacterToMuWithoutSection aD hfixed sigma = 1 at hraw
    exact hraw
  have hchosenVal : D.rootCocycle aD sigma = 1 := by
    have hval := congrArg Subtype.val hchosen
    simpa [RadicalDatum.rootCharacterToMuWithoutSection_apply,
      RadicalDatum.rootCharacter_apply] using hval
  have hquotient : rootQuotient (K := K) (L := L) betaUnit sigma = 1 := by
    rw [D.rootQuotient_eq_rootCocycle_of_same_pow hfixed aD hbetaPow sigma]
    exact hchosenVal
  have hunit : sigma • betaUnit = betaUnit :=
    (rootQuotient_eq_one_iff (K := K) (L := L) betaUnit sigma).1 hquotient
  exact congrArg Units.val hunit

/-- If the roots attached to `Delta` generate `L`, the transposed restricted
Kummer pairing is nondegenerate on the Galois side. -/
theorem restrictedKummerTranspose_injective_of_adjoin
    [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (hgenerate : IntermediateField.adjoin K
      (kummerRootSet (K := K) (Omega := L) n Delta.1) = ⊤) :
    Function.Injective (restrictedKummerTranspose n hmu Delta hDelta) := by
  intro sigma tau hsigmaTau
  apply div_eq_one.mp
  let rho : Gal(L/K) := sigma / tau
  have hrhoTranspose : restrictedKummerTranspose n hmu Delta hDelta rho = 1 := by
    rw [show rho = sigma / tau from rfl, map_div, hsigmaTau]
    exact div_self' (restrictedKummerTranspose n hmu Delta hDelta tau)
  have hrho : rho = 1 := by
    apply AlgEquiv.ext
    intro x
    change rho x = x
    have hx : x ∈ IntermediateField.adjoin K
        (kummerRootSet (K := K) (Omega := L) n Delta.1) := by
      rw [hgenerate]
      exact IntermediateField.mem_top
    induction hx using IntermediateField.adjoin_induction with
    | mem x hx =>
        exact restrictedKummerTranspose_fixes_root n hmu Delta hDelta rho
          hrhoTranspose hx
    | algebraMap x =>
        exact rho.commutes x
    | add x y hx hy ihx ihy =>
        rw [map_add, ihx, ihy]
    | inv x hx ihx =>
        rw [map_inv₀, ihx]
    | mul x y hx hy ihx ihy =>
        rw [map_mul, ihx, ihy]
  exact hrho

/-- The subgroup quotient `Delta / Kˣ^n` is killed by `n`. -/
theorem restrictedRadicalQuotient_pow_eq_one
    (n : ℕ+) (Delta : KummerSubgroup K n)
    (q : RestrictedRadicalQuotient n Delta) :
    q ^ (n : ℕ) = 1 := by
  refine restrictedRadicalQuotient_inductionOn
    (motive := fun q => q ^ (n : ℕ) = 1) n Delta q ?_
  intro a
  rw [← map_pow]
  exact (restrictedRadicalQuotientMk_eq_one_iff
    n Delta (a ^ (n : ℕ))).2
      ((mem_restrictedNthPowersSubgroup_iff n Delta).2 ⟨a.1, rfl⟩)

/-- At a finite stage, injectivity of the restricted character and of its
transpose force equality of the two finite cardinalities.  Finite abelian
duality then upgrades the restricted character to a surjection. -/
theorem restrictedQuotientKummerCharacter_surjective_of_adjoin
    [FiniteDimensional K L] [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (hgenerate : IntermediateField.adjoin K
      (kummerRootSet (K := K) (Omega := L) n Delta.1) = ⊤) :
    Function.Surjective (restrictedQuotientKummerCharacter n hmu Delta hDelta) := by
  let G := Gal(L/K)
  let R := RestrictedRadicalQuotient n Delta
  let M := nthRootsSubgroup L (n : ℕ)
  let f : R →* (G →* M) := restrictedQuotientKummerCharacter n hmu Delta hDelta
  let t : G →* (R →* M) := restrictedKummerTranspose n hmu Delta hDelta
  have hf : Function.Injective f :=
    restrictedQuotientKummerCharacter_injective n hmu Delta hDelta
  have ht : Function.Injective t :=
    restrictedKummerTranspose_injective_of_adjoin n hmu Delta hDelta hgenerate
  let : IsMulCommutative G :=
    { is_comm := ⟨fun sigma tau => by
        apply ht
        rw [map_mul, map_mul]
        exact mul_comm (t sigma) (t tau)⟩ }
  let _ : CommGroup G :=
    CommGroup.mk (fun a b => IsMulCommutative.is_comm.comm a b)
  let : NeZero (n : ℕ) := ⟨n.ne_zero⟩
  let : Finite (G →* M) :=
    Finite.of_injective
      (fun chi : G →* M => (chi : G → M)) DFunLike.coe_injective
  let : Finite R := Finite.of_injective f hf
  let : Finite (R →* M) :=
    Finite.of_injective
      (fun chi : R →* M => (chi : R → M)) DFunLike.coe_injective
  have hRExponent : ∀ r : R, r ^ (n : ℕ) = 1 :=
    restrictedRadicalQuotient_pow_eq_one n Delta
  have hGExponent : ∀ sigma : G, sigma ^ (n : ℕ) = 1 := by
    intro sigma
    apply ht
    rw [map_pow, map_one]
    apply MonoidHom.ext
    intro r
    apply Subtype.ext
    exact (t sigma r).2
  obtain ⟨dualG⟩ := finiteNthRootsCharacterDuality
    (G := G) (K := K) (L := L) n hmu hGExponent
  obtain ⟨dualR⟩ := finiteNthRootsCharacterDuality
    (G := R) (K := K) (L := L) n hmu hRExponent
  let : Fintype G := Fintype.ofFinite G
  let : Fintype R := Fintype.ofFinite R
  let : Fintype (G →* M) := Fintype.ofFinite (G →* M)
  have hcardRG : Fintype.card R ≤ Fintype.card G :=
    Fintype.card_le_of_injective
      (fun r : R => dualG (f r)) (dualG.injective.comp hf)
  have hcardGR : Fintype.card G ≤ Fintype.card R :=
    Fintype.card_le_of_injective
      (fun sigma : G => dualR (t sigma)) (dualR.injective.comp ht)
  have hcardRHomG : Fintype.card R = Fintype.card (G →* M) := by
    calc
      Fintype.card R = Fintype.card G := Nat.le_antisymm hcardRG hcardGR
      _ = Fintype.card (G →* M) := (Fintype.card_congr dualG.toEquiv).symm
  exact hf.surjective_of_finite (Fintype.equivOfCardEq hcardRHomG)

/-- The finite restricted Kummer character equivalence obtained from the
two nondegeneracy statements and finite duality. -/
def restrictedKummerCharacterMulEquivOfAdjoin
    [FiniteDimensional K L] [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (hgenerate : IntermediateField.adjoin K
      (kummerRootSet (K := K) (Omega := L) n Delta.1) = ⊤) :
    RestrictedRadicalQuotient n Delta ≃*
      (Gal(L/K) →* nthRootsSubgroup L (n : ℕ)) :=
  MulEquiv.ofBijective (restrictedQuotientKummerCharacter n hmu Delta hDelta)
    ⟨restrictedQuotientKummerCharacter_injective n hmu Delta hDelta,
      restrictedQuotientKummerCharacter_surjective_of_adjoin
        n hmu Delta hDelta hgenerate⟩

/-- Finite inverse endpoint of the Kummer correspondence.

If `L` is generated by the roots attached to `Delta`, then no additional
base-field radical appears in `L`: the actual radical subgroup of `L/K` is
exactly `Delta`.  Surjectivity of the restricted pairing supplies a
`Delta`-class with the same character as an arbitrary actual radical;
the exact kernel theorem says that the two representatives differ by an
ambient `n`-th power, which already belongs to `Delta`. -/
theorem finiteKummerRadicalSubgroup_eq_of_adjoin
    [FiniteDimensional K L] [IsGalois K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (Delta : KummerSubgroup K n)
    (hDelta : Delta.1 ≤ finiteKummerRadicalSubgroup (K := K) (L := L) n)
    (hgenerate : IntermediateField.adjoin K
      (kummerRootSet (K := K) (Omega := L) n Delta.1) = ⊤) :
    finiteKummerRadicalSubgroup (K := K) (L := L) n = Delta.1 := by
  apply le_antisymm
  · intro a ha
    let D := chosenFiniteKummerRadicalDatum (K := K) (L := L) n
    let hfixed := restrictedKummerFixed (K := K) (L := L) n hmu
    let aD : D.carrier := ⟨a, ha⟩
    let qa : D.RadicalQuotient :=
      D.radicalQuotientMk aD
    obtain ⟨q, hq⟩ :=
      restrictedQuotientKummerCharacter_surjective_of_adjoin
        n hmu Delta hDelta hgenerate
        (D.quotientKummerCharacterWithoutSection hfixed qa)
    obtain ⟨delta, rfl⟩ :=
      restrictedRadicalQuotientMk_surjective n Delta q
    let deltaD : D.carrier := restrictedRadicalInclusion n Delta hDelta delta
    have hcharacters : D.kummerCharacterWithoutSection hfixed deltaD =
        D.kummerCharacterWithoutSection hfixed aD := by
      change D.kummerCharacterWithoutSection hfixed deltaD =
        D.kummerCharacterWithoutSection hfixed aD at hq
      exact hq
    have hclasses :
        D.radicalQuotientMk deltaD = D.radicalQuotientMk aD := by
      apply D.quotientKummerCharacterWithoutSection_injective hfixed
      simpa using hcharacters
    have hdiv : deltaD / aD ∈ D.ambientNthPowersSubgroup :=
      (D.radicalQuotientMk_eq_iff deltaD aD).1 hclasses
    obtain ⟨b, hb⟩ := (D.mem_ambientNthPowersSubgroup_iff).1 hdiv
    have hbDelta : b ^ (n : ℕ) ∈ Delta.1 :=
      Delta.2 ((mem_unitNthPowersSubgroup_iff n).2 ⟨b, rfl⟩)
    have hdeltaDiv : delta.1 / b ^ (n : ℕ) ∈ Delta.1 :=
      div_mem delta.2 hbDelta
    have hdeltaD_coe : (deltaD : Kˣ) = delta.1 := by
      exact Subgroup.coe_inclusion hDelta delta
    have haD_coe : (aD : Kˣ) = a := rfl
    have hb' : b ^ (n : ℕ) = delta.1 / a := by
      calc
        b ^ (n : ℕ) = (deltaD / aD : D.carrier) := hb
        _ = (deltaD : Kˣ) / (aD : Kˣ) := rfl
        _ = delta.1 / a := by rw [hdeltaD_coe, haD_coe]
    have haeq : a = delta.1 / b ^ (n : ℕ) := by
      rw [hb']
      exact (div_div_self' delta.1 a).symm
    rw [haeq]
    exact hdeltaDiv
  · exact hDelta

end RestrictedFiniteKummer

end KummerTheory
