import GaloisCohomology.Kummer.Concrete.LocalMaximalKummerExtension

set_option autoImplicit false

/-!
# Simple Kummer extensions

This file exposes the chosen singleton-radical construction used in
Kummer theory.  For `b : Kˣ`, it chooses an embedded field
`K(ⁿ√b)` inside the separable closure and proves that, when `K` contains
the `n`-th roots of unity, this is a finite cyclic Galois extension.
-/

noncomputable section

namespace KummerTheory

variable (K : Type) [Field K]

/-- A chosen `n`-th root of `b` in the separable closure. -/
noncomputable def chosenSimpleKummerRoot
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    SeparableClosure K :=
  Classical.choose
    (exists_kummerRootSet
      (K := K) (Omega := SeparableClosure K) n hnK
      (maximalKummerSubgroup K n).1
      (⟨b, by simp [maximalKummerSubgroup]⟩ :
        (maximalKummerSubgroup K n).1))

/-- The chosen root belongs to the maximal Kummer root set. -/
theorem chosenSimpleKummerRoot_mem
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    chosenSimpleKummerRoot K n hnK b ∈
      kummerRootSet (K := K) (Omega := SeparableClosure K) n
        (maximalKummerSubgroup K n).1 :=
  (Classical.choose_spec
    (exists_kummerRootSet
      (K := K) (Omega := SeparableClosure K) n hnK
      (maximalKummerSubgroup K n).1
      (⟨b, by simp [maximalKummerSubgroup]⟩ :
        (maximalKummerSubgroup K n).1))).1

/-- The chosen element is an actual `n`-th root of `b`. -/
theorem chosenSimpleKummerRoot_pow
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    chosenSimpleKummerRoot K n hnK b ^ (n : ℕ) =
      algebraMap K (SeparableClosure K) (b : K) :=
  (Classical.choose_spec
    (exists_kummerRootSet
      (K := K) (Omega := SeparableClosure K) n hnK
      (maximalKummerSubgroup K n).1
      (⟨b, by simp [maximalKummerSubgroup]⟩ :
        (maximalKummerSubgroup K n).1))).2

/-- The simple Kummer extension generated by the chosen root of `b`. -/
def chosenSimpleKummerExtension
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    IntermediateField K (SeparableClosure K) :=
  IntermediateField.adjoin K {chosenSimpleKummerRoot K n hnK b}

/-- The simple extension generated by one chosen radical is contained in the
extension generated by all radicals of the maximal Kummer subgroup. -/
theorem chosenSimpleKummerExtension_le_maximalKummerExtension
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    chosenSimpleKummerExtension K n hnK b ≤
      kummerRadicalExtension
        (K := K) (Omega := SeparableClosure K) n
          (maximalKummerSubgroup K n).1 := by
  rw [chosenSimpleKummerExtension]
  apply IntermediateField.adjoin_le_iff.mpr
  intro beta hbeta
  have hbeta' : beta = chosenSimpleKummerRoot K n hnK b :=
    Set.mem_singleton_iff.mp hbeta
  subst beta
  rw [kummerRadicalExtension]
  exact IntermediateField.subset_adjoin K _
    (chosenSimpleKummerRoot_mem K n hnK b)

/-- The chosen radical as a unit of `K(ⁿ√b)`. -/
noncomputable def chosenSimpleKummerRootUnit
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    (chosenSimpleKummerExtension K n hnK b)ˣ :=
  Units.mk0
    ⟨chosenSimpleKummerRoot K n hnK b,
      IntermediateField.subset_adjoin K
        {chosenSimpleKummerRoot K n hnK b}
        (Set.mem_singleton (chosenSimpleKummerRoot K n hnK b))⟩
    (by
      intro hzero
      apply kummerRootSet_ne_zero
        (K := K) (Omega := SeparableClosure K) n
        (maximalKummerSubgroup K n).1
        (chosenSimpleKummerRoot_mem K n hnK b)
      exact congrArg Subtype.val hzero)

/-- The radical still has `n`-th power `b` in the simple extension. -/
@[simp]
theorem chosenSimpleKummerRootUnit_pow
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    chosenSimpleKummerRootUnit K n hnK b ^ (n : ℕ) =
      Units.map
        (algebraMap K (chosenSimpleKummerExtension K n hnK b)).toMonoidHom b := by
  apply Units.ext
  apply Subtype.ext
  exact chosenSimpleKummerRoot_pow K n hnK b

/-- The chosen radical generates the whole simple extension. -/
theorem chosenSimpleKummerExtension_adjoin_root_eq_top
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    let E := chosenSimpleKummerExtension K n hnK b
    IntermediateField.adjoin K
      {((chosenSimpleKummerRootUnit K n hnK b : Eˣ) : E)} = ⊤ := by
  let E := chosenSimpleKummerExtension K n hnK b
  let beta : E := (chosenSimpleKummerRootUnit K n hnK b : Eˣ)
  let R : IntermediateField K E :=
    IntermediateField.adjoin K {beta}
  change R = ⊤
  apply top_unique
  intro x _
  have hall : ∀ y : SeparableClosure K, ∀ hy : y ∈ E,
      (⟨y, hy⟩ : E) ∈ R := by
    intro y hy
    change y ∈ IntermediateField.adjoin K
      {chosenSimpleKummerRoot K n hnK b} at hy
    induction hy using IntermediateField.adjoin_induction with
    | mem y hy =>
        have hy' : y = chosenSimpleKummerRoot K n hnK b :=
          Set.mem_singleton_iff.mp hy
        subst y
        apply IntermediateField.subset_adjoin K
        rw [Set.mem_singleton_iff]
        apply Subtype.ext
        rfl
    | algebraMap a => exact R.algebraMap_mem a
    | add x y hx hy ihx ihy => exact R.add_mem ihx ihy
    | inv x hx ihx => exact R.inv_mem ihx
    | mul x y hx hy ihx ihy => exact R.mul_mem ihx ihy
  exact hall x.1 x.property

/-- The extension generated by the chosen simple Kummer root is finite-dimensional. -/
theorem chosenSimpleKummerExtension_finiteDimensional
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ) :
    FiniteDimensional K (chosenSimpleKummerExtension K n hnK b) := by
  apply IntermediateField.finiteDimensional_adjoin
  intro x hx
  have hx' : x = chosenSimpleKummerRoot K n hnK b :=
    Set.mem_singleton_iff.mp hx
  subst x
  apply IsIntegral.of_pow n.pos
  rw [chosenSimpleKummerRoot_pow K n hnK b]
  exact isIntegral_algebraMap

/-- If `K` contains `μₙ`, then `K(ⁿ√b) / K` is abelian Galois. -/
theorem chosenSimpleKummerExtension_isAbelianGalois
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (b : Kˣ) :
    IsAbelianGalois K (chosenSimpleKummerExtension K n hnK b) := by
  classical
  let Delta := maximalKummerSubgroup K n
  let beta := chosenSimpleKummerRoot K n hnK b
  let T : Finset (SeparableClosure K) := {beta}
  have hT : (T : Set (SeparableClosure K)) ⊆
      kummerRootSet (K := K) (Omega := SeparableClosure K) n Delta.1 := by
    intro x hx
    have hx' : x = beta := by simpa [T] using hx
    subst x
    simpa [Delta, beta] using chosenSimpleKummerRoot_mem K n hnK b
  let Delta0 := admissibleFiniteSupportSubgroup
    (K := K) (Omega := SeparableClosure K) n Delta T hT
  have hAbelian : IsAbelianGalois K
      (kummerRadicalExtension
        (K := K) (Omega := SeparableClosure K) n Delta0.1) :=
    kummerRadicalExtension_isAbelianGalois
      (K := K) (Omega := SeparableClosure K) n hmu Delta0.1
  have hfield := kummerRadicalExtension_admissibleFiniteSupport_eq
    (K := K) (Omega := SeparableClosure K) n Delta T hT hmu
  rw [hfield] at hAbelian
  change IsAbelianGalois K
    (IntermediateField.adjoin K (T : Set (SeparableClosure K))) at hAbelian
  have hTset : (T : Set (SeparableClosure K)) =
      {chosenSimpleKummerRoot K n hnK b} := by
    ext x
    simp [T, beta]
  rw [hTset] at hAbelian
  exact hAbelian

/-- Every Galois root quotient of the chosen radical is an `n`-th root
of unity. -/
theorem chosenSimpleKummer_rootQuotient_mem
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ)
    (sigma : Gal((chosenSimpleKummerExtension K n hnK b)/K)) :
    rootQuotient
        (K := K) (L := chosenSimpleKummerExtension K n hnK b)
        (chosenSimpleKummerRootUnit K n hnK b) sigma ∈
      nthRootsSubgroup (chosenSimpleKummerExtension K n hnK b) (n : ℕ) := by
  apply rootQuotient_mem_nthRootsSubgroup_of_pow_fixed
  intro tau
  rw [chosenSimpleKummerRootUnit_pow K n hnK b]
  exact RadicalDatum.smul_algebraMap_unit
    (K := K) (L := chosenSimpleKummerExtension K n hnK b) tau b

/-- The root quotient of the chosen radical is a character of the
Galois group. -/
noncomputable def chosenSimpleKummerRootCharacter
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (b : Kˣ) :
    Gal((chosenSimpleKummerExtension K n hnK b)/K) →*
      nthRootsSubgroup (chosenSimpleKummerExtension K n hnK b) (n : ℕ) :=
  let E := chosenSimpleKummerExtension K n hnK b
  let : MulDistribMulAction Gal(E/K) Eˣ :=
    AlgEquiv.instMulDistribMulActionUnits
  let D :=
    chosenFiniteKummerRadicalDatum (K := K) (L := E) n
  let delta : D.carrier :=
    ⟨b, chosenSimpleKummerRootUnit K n hnK b,
      chosenSimpleKummerRootUnit_pow K n hnK b⟩
  let hfixed :
      ∀ sigma : Gal(E/K), ∀ u : Eˣ,
        u ^ (n : ℕ) = 1 →
          Units.map sigma.toMonoidHom u = u :=
    nthRootsOfUnity_fixed (K := K) (L := E) n
      (nthRootsOfUnityInBase_of_primitiveRoots
        (K := K) (L := E) n hmu)
  D.rootCharacterToMuWithoutSection delta hfixed

/-- The character attached to the chosen Kummer root agrees with the root
quotient of the chosen generator. -/
@[simp]
theorem chosenSimpleKummerRootCharacter_apply
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (b : Kˣ)
    (sigma : Gal((chosenSimpleKummerExtension K n hnK b)/K)) :
    chosenSimpleKummerRootCharacter K n hnK hmu b sigma =
      ⟨rootQuotient
          (K := K) (L := chosenSimpleKummerExtension K n hnK b)
          (chosenSimpleKummerRootUnit K n hnK b) sigma,
        chosenSimpleKummer_rootQuotient_mem K n hnK b sigma⟩ := by
  let E := chosenSimpleKummerExtension K n hnK b
  let _ : MulDistribMulAction Gal(E/K) Eˣ :=
    AlgEquiv.instMulDistribMulActionUnits
  let D :=
    chosenFiniteKummerRadicalDatum (K := K) (L := E) n
  let delta : D.carrier :=
    ⟨b, chosenSimpleKummerRootUnit K n hnK b,
      chosenSimpleKummerRootUnit_pow K n hnK b⟩
  let hfixed :
      ∀ tau : Gal(E/K), ∀ u : Eˣ,
        u ^ (n : ℕ) = 1 →
          Units.map tau.toMonoidHom u = u :=
    nthRootsOfUnity_fixed (K := K) (L := E) n
      (nthRootsOfUnityInBase_of_primitiveRoots
        (K := K) (L := E) n hmu)
  apply Subtype.ext
  change
    D.rootCharacter delta hfixed sigma =
      rootQuotient
        (K := K) (L := E)
        (chosenSimpleKummerRootUnit K n hnK b) sigma
  exact
    (D.rootCharacter_eq_of_same_pow hfixed delta
      (chosenSimpleKummerRootUnit_pow K n hnK b) sigma).symm

/-- A Galois automorphism fixes the chosen radical exactly when it is the
identity. -/
theorem chosenSimpleKummerRootQuotient_eq_one_iff
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0) (b : Kˣ)
    (sigma : Gal((chosenSimpleKummerExtension K n hnK b)/K)) :
    rootQuotient
        (K := K) (L := chosenSimpleKummerExtension K n hnK b)
        (chosenSimpleKummerRootUnit K n hnK b) sigma = 1 ↔
      sigma = 1 := by
  constructor
  · intro hquot
    have hfix := (rootQuotient_eq_one_iff
      (K := K) (L := chosenSimpleKummerExtension K n hnK b)
      (chosenSimpleKummerRootUnit K n hnK b) sigma).1 hquot
    apply AlgEquiv.coe_toAlgHom_injective
    apply IntermediateField.adjoin_algHom_ext K
    intro beta hbeta
    have hbeta' : beta = chosenSimpleKummerRoot K n hnK b :=
      Set.mem_singleton_iff.mp hbeta
    subst beta
    have hval := congrArg Units.val hfix
    change
      sigma
          (chosenSimpleKummerRootUnit K n hnK b :
            chosenSimpleKummerExtension K n hnK b) =
        (1 : Gal((chosenSimpleKummerExtension K n hnK b)/K))
          (chosenSimpleKummerRootUnit K n hnK b :
            chosenSimpleKummerExtension K n hnK b)
    exact hval
  · rintro rfl
    exact rootQuotient_one
      (K := K) (L := chosenSimpleKummerExtension K n hnK b)
      (chosenSimpleKummerRootUnit K n hnK b)

/-- Evaluation on the generating radical separates all automorphisms. -/
theorem chosenSimpleKummerRootCharacter_injective
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (b : Kˣ) :
    Function.Injective
      (chosenSimpleKummerRootCharacter K n hnK hmu b) := by
  intro sigma tau hst
  apply div_eq_one.mp
  apply
    (chosenSimpleKummerRootQuotient_eq_one_iff
      K n hnK b (sigma / tau)).1
  have hchar :
      chosenSimpleKummerRootCharacter K n hnK hmu b (sigma / tau) = 1 := by
    rw [map_div, hst]
    exact div_self' _
  rw [chosenSimpleKummerRootCharacter_apply K n hnK hmu b] at hchar
  exact congrArg Subtype.val hchar

/-- The Galois group of a simple Kummer extension is cyclic. -/
theorem chosenSimpleKummerExtension_isCyclic
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (b : Kˣ) :
    IsCyclic Gal((chosenSimpleKummerExtension K n hnK b)/K) := by
  let : IsAbelianGalois K (chosenSimpleKummerExtension K n hnK b) :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  exact
    isCyclic_of_injective
      (chosenSimpleKummerRootCharacter K n hnK hmu b)
      (chosenSimpleKummerRootCharacter_injective K n hnK hmu b)

/-- Every automorphism of a simple Kummer extension has exponent
dividing `n`. -/
theorem chosenSimpleKummerExtension_galois_pow_eq_one
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (b : Kˣ)
    (sigma : Gal((chosenSimpleKummerExtension K n hnK b)/K)) :
    sigma ^ (n : ℕ) = 1 := by
  apply chosenSimpleKummerRootCharacter_injective K n hnK hmu b
  rw [map_pow, map_one]
  apply Subtype.ext
  exact (chosenSimpleKummerRootCharacter K n hnK hmu b sigma).property

end KummerTheory
