import ClassFieldTheory.LubinTate.FiniteLevel.LevelValuation
import ValuedFieldTheory.Ramification.HilbertRamification.RamificationNumber
import ValuedFieldTheory.Ramification.HilbertRamification.RealLowerGroups
import ValuedFieldTheory.Valuation.DiscreteValuationField.AddVal

set_option autoImplicit false

/-!
# Lower ramification groups of standard Lubin--Tate levels

This file places the genuine real lower ramification filtration on a standard
Lubin--Tate level.  Since the integral closure is generated by the primitive
Lubin--Tate uniformizer, membership at a natural index is detected by the
displacement of that one element.
-/

noncomputable section

universe u v

namespace LubinTate

open LocalFieldTheory.DiscreteValuationField
open RamificationTheory.HilbertRamification.Higher
open ValuationTheory.DiscreteValuationField

variable {K : Type u} [Field K]

/-- The actual real lower ramification group of a standard Lubin--Tate
level, formed using its integral-closure valuation. -/
noncomputable def standardLubinTateRealLowerRamificationGroup
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K))
    (n : ℕ) (s : ℝ) :
    Subgroup Gal((standardLubinTateLevelField hπ n) / K) :=
  lowerRamificationGroup
    (base := F.toCompleteDVF.toDVF)
    (target := (standardLubinTateLevelCompleteDVF hπ n).toDVF)
    (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension hπ n)
    s

noncomputable local instance
    standardLubinTateLevelField_finiteDimensional_forLowerRamification
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    FiniteDimensional K (standardLubinTateLevelField hπ n) :=
  standardLubinTateLevelField_finiteDimensional hπ n

noncomputable local instance
    standardLubinTateLevelField_isGalois_forLowerRamification
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsGalois K (standardLubinTateLevelField hπ n) :=
  standardLubinTateLevelField_isGalois hπ n

/-- At a natural lower index, an automorphism belongs to the lower
ramification group exactly when its displacement of the primitive
Lubin--Tate uniformizer has additive valuation at least `i + 1`. -/
theorem mem_standardLubinTateRealLowerRamificationGroup_nat_iff_primitivePoint
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K))
    (n i : ℕ)
    (σ : Gal((standardLubinTateLevelField hπ n) / K)) :
    σ ∈ standardLubinTateRealLowerRamificationGroup hπ n (i : ℝ) ↔
      ((i + 1 : ℕ) : ℕ∞) ≤
        IsDiscreteValuationRing.addVal
          (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
          (valuationSubringAutOfUniqueExtension
              (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
                hπ n)
              σ (standardLubinTatePrimitivePointInteger hπ n) -
            standardLubinTatePrimitivePointInteger hπ n) := by
  change
    σ ∈ lowerRamificationGroup
        (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
          hπ n) (i : ℝ) ↔ _
  constructor
  · intro hσ
    have hall :=
      (mem_lowerRamificationGroup_nat_iff
        (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
          hπ n)
        i σ).mp hσ
    exact
      (IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge
        (valuationSubringAutOfUniqueExtension
            (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
              hπ n)
            σ (standardLubinTatePrimitivePointInteger hπ n) -
          standardLubinTatePrimitivePointInteger hπ n)
        (i + 1)).mp
        (hall (standardLubinTatePrimitivePointInteger hπ n))
  · intro hdisplacement
    apply
      (mem_lowerRamificationGroup_nat_iff
        (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
          hπ n)
        i σ).mpr
    intro z
    apply
      valuationSubringAutOfUniqueExtension_sub_mem_of_mem_adjoin
        (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
          hπ n)
    · exact
        (IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge
          (valuationSubringAutOfUniqueExtension
              (standardLubinTateLevelCompleteDVF_hasUniqueDVFValuationExtension
                hπ n)
              σ (standardLubinTatePrimitivePointInteger hπ n) -
            standardLubinTatePrimitivePointInteger hπ n)
          (i + 1)).mpr hdisplacement
    · exact
        (standardLubinTatePrimitivePointInteger_adjoin_eq_top hπ n).symm.le
          (show z ∈
              (⊤ : Subalgebra F.valuationSubring
                (standardLubinTateLevelCompleteDVF hπ n).valuationSubring) from
            by simp)

/-- At a nonnegative real lower index, the standard lower group is already
the group at the natural-number ceiling of that index. -/
theorem standardLubinTateRealLowerRamificationGroup_eq_natCeil
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K))
    (n : ℕ) (s : ℝ) (hs : 0 ≤ s) :
    standardLubinTateRealLowerRamificationGroup hπ n s =
      standardLubinTateRealLowerRamificationGroup
        hπ n (⌈s⌉₊ : ℝ) := by
  have hexponent :
      realRamificationExponent s =
        realRamificationExponent (⌈s⌉₊ : ℝ) := by
    rw [realRamificationExponent_nat]
    unfold realRamificationExponent
    rw [Int.ceil_toNat, Nat.ceil_add_one hs]
  have hideal :
      realRamificationIdeal
          (standardLubinTateLevelCompleteDVF hπ n).toDVF s =
        realRamificationIdeal
          (standardLubinTateLevelCompleteDVF hπ n).toDVF
          (⌈s⌉₊ : ℝ) := by
    unfold realRamificationIdeal
    rw [hexponent]
  unfold standardLubinTateRealLowerRamificationGroup
  ext σ
  change
    (∀ a, _ ∈
      realRamificationIdeal
        (standardLubinTateLevelCompleteDVF hπ n).toDVF s) ↔
      ∀ a, _ ∈
        realRamificationIdeal
          (standardLubinTateLevelCompleteDVF hπ n).toDVF
          (⌈s⌉₊ : ℝ)
  rw [hideal]

end LubinTate

end
