import ClassFieldTheory.LubinTate.FiniteLevel.PrimitiveEisenstein
import Mathlib.FieldTheory.IsSepClosed
import Mathlib.RingTheory.Polynomial.GaussLemma
import Mathlib.SetTheory.Cardinal.Finite

set_option autoImplicit false

/-!
# Primitive roots and standard Lubin--Tate level fields

For a local field `F` with uniformizer `π`, this file maps the primitive
division polynomial from the valuation ring to the fraction field.  Gauss's
lemma transfers its Eisenstein irreducibility to the field.  We also prove
separability directly, choose a root in `SeparableClosure K`, and identify
the degree of the simple extension generated by that root.

The separability argument works in both mixed and equal characteristic.  It
uses the identity

`(f^[n])'(0) = π ^ n`

for `f(X) = X ^ q + π * X`, together with the fact that `q - 1` is nonzero
in the base field.
-/

noncomputable section

open scoped Polynomial

universe u v

namespace LubinTate

open LocalFieldTheory.DiscreteValuationField

variable {K : Type u} [Field K]

/-- The derivative of the standard polynomial at zero is its linear
coefficient. -/
@[simp]
theorem standardLubinTatePolynomial_derivative_eval_zero
    (F : LocalField.{u, v} K) (π : F.valuationSubring) :
    (standardLubinTatePolynomial F π).derivative.eval 0 = π := by
  simp [standardLubinTatePolynomial, Polynomial.derivative_pow,
    Nat.sub_ne_zero_of_lt
      (Finite.one_lt_card : 1 < Nat.card F.residueField)]

/-- The derivative at zero of the `n`-fold standard iterate is `π ^ n`. -/
@[simp]
theorem standardLubinTatePolynomialIterate_derivative_eval_zero
    (F : LocalField.{u, v} K) (π : F.valuationSubring) (n : ℕ) :
    (standardLubinTatePolynomialIterate F π n).derivative.eval 0 =
      π ^ n := by
  induction n with
  | zero =>
      simp [standardLubinTatePolynomialIterate]
  | succ n ih =>
      rw [standardLubinTatePolynomialIterate_succ,
        Polynomial.derivative_comp, Polynomial.eval_mul, ih,
        Polynomial.eval_comp,
        standardLubinTatePolynomialIterate_eval_zero,
        standardLubinTatePolynomial_derivative_eval_zero]
      simp [pow_succ]

/-- The primitive division polynomial after extending coefficients from the
valuation ring to the base field. -/
noncomputable def standardLubinTatePrimitivePolynomialOverField
    (F : LocalField.{u, v} K) (π : F.valuationSubring) (n : ℕ) :
    Polynomial K :=
  (standardLubinTatePrimitivePolynomial F π n).map
    (algebraMap F.valuationSubring K)

/-- The field-valued primitive polynomial has the expected formula. -/
theorem standardLubinTatePrimitivePolynomialOverField_formula
    (F : LocalField.{u, v} K) (π : F.valuationSubring) (n : ℕ) :
    standardLubinTatePrimitivePolynomialOverField F π n =
      (standardLubinTatePolynomialIterate F π n).map
          (algebraMap F.valuationSubring K) ^
        (Nat.card F.residueField - 1) +
      Polynomial.C (π : K) := by
  simp [standardLubinTatePrimitivePolynomialOverField,
    standardLubinTatePrimitivePolynomial]

/-- The field-valued primitive polynomial is monic. -/
theorem standardLubinTatePrimitivePolynomialOverField_monic
    (F : LocalField.{u, v} K) (π : F.valuationSubring) (n : ℕ) :
    (standardLubinTatePrimitivePolynomialOverField F π n).Monic :=
  (standardLubinTatePrimitivePolynomial_monic F π n).map _

/-- The field-valued primitive polynomial has degree
`(q - 1) * q ^ n`. -/
theorem standardLubinTatePrimitivePolynomialOverField_natDegree
    (F : LocalField.{u, v} K) (π : F.valuationSubring) (n : ℕ) :
    (standardLubinTatePrimitivePolynomialOverField F π n).natDegree =
      (Nat.card F.residueField - 1) *
        Nat.card F.residueField ^ n := by
  rw [standardLubinTatePrimitivePolynomialOverField,
    (standardLubinTatePrimitivePolynomial_monic F π n).natDegree_map,
    standardLubinTatePrimitivePolynomial_natDegree]

/-- Gauss's lemma transfers Eisenstein irreducibility from the valuation
ring to the base field. -/
theorem standardLubinTatePrimitivePolynomialOverField_irreducible
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Irreducible (standardLubinTatePrimitivePolynomialOverField F π n) := by
  let : IsFractionRing F.valuationSubring K :=
    F.toCompleteDVF.toDVF.valuationSubring_isFractionRing
  let : IsIntegrallyClosed F.valuationSubring :=
    F.toCompleteDVF.toDVF.valuationSubring_isIntegrallyClosed
  exact
    (standardLubinTatePrimitivePolynomial_monic F π n).irreducible_iff_irreducible_map_fraction_map.mp
      (standardLubinTatePrimitivePolynomial_irreducible hπ n)

/-- The natural number `q - 1` is nonzero in the local field. -/
theorem residueFieldNatCard_sub_one_cast_ne_zero
    (F : LocalField.{u, v} K) :
    ((Nat.card F.residueField - 1 : ℕ) : K) ≠ 0 := by
  have hcard :
      (Nat.card F.residueField : F.residueField) = 0 := by
    let := Fintype.ofFinite F.residueField
    rw [Nat.card_eq_fintype_card, Nat.cast_card_eq_zero]
  have hres :
      ((Nat.card F.residueField - 1 : ℕ) : F.residueField) ≠ 0 := by
    rw [Nat.cast_sub
      (Nat.le_of_lt
        (Finite.one_lt_card : 1 < Nat.card F.residueField)), hcard]
    simp
  intro hfield
  have hvaluation :
      ((Nat.card F.residueField - 1 : ℕ) : F.valuationSubring) = 0 := by
    apply Subtype.ext
    simpa using hfield
  have hreszero :
      ((Nat.card F.residueField - 1 : ℕ) : F.residueField) = 0 := by
    simpa using congrArg F.residueMap hvaluation
  exact hres hreszero

/-- The field-valued primitive polynomial has nonzero derivative. -/
theorem standardLubinTatePrimitivePolynomialOverField_derivative_ne_zero
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTatePrimitivePolynomialOverField F π n).derivative ≠ 0 := by
  let A :=
    (standardLubinTatePolynomialIterate F π n).map
      (algebraMap F.valuationSubring K)
  have hAmonic : A.Monic :=
    (standardLubinTatePolynomialIterate_monic F π n).map _
  have hAderivativeAtZero :
      A.derivative.eval 0 = (π : K) ^ n := by
    calc
      A.derivative.eval 0 =
          algebraMap F.valuationSubring K
            ((standardLubinTatePolynomialIterate F π n).derivative.eval 0) := by
        dsimp [A]
        rw [Polynomial.derivative_map, Polynomial.eval_zero_map,
          Algebra.algebraMap_ofSubsemiring_apply]
      _ = (π : K) ^ n := by
        rw [standardLubinTatePolynomialIterate_derivative_eval_zero,
          map_pow]
        rfl
  have hAderivative : A.derivative ≠ 0 := by
    intro hzero
    apply pow_ne_zero n hπ.ne_zero
    calc
      (π : K) ^ n = A.derivative.eval 0 :=
        hAderivativeAtZero.symm
      _ = 0 := by rw [hzero, Polynomial.eval_zero]
  rw [standardLubinTatePrimitivePolynomialOverField_formula]
  change
    (A ^ (Nat.card F.residueField - 1) +
      Polynomial.C (π : K)).derivative ≠ 0
  rw [Polynomial.derivative_add, Polynomial.derivative_pow,
    Polynomial.derivative_C, add_zero]
  exact mul_ne_zero
    (mul_ne_zero
      (Polynomial.C_ne_zero.mpr
        (residueFieldNatCard_sub_one_cast_ne_zero F))
      (pow_ne_zero _ hAmonic.ne_zero))
    hAderivative

/-- The field-valued primitive polynomial is separable. -/
theorem standardLubinTatePrimitivePolynomialOverField_separable
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTatePrimitivePolynomialOverField F π n).Separable :=
  (Polynomial.separable_iff_derivative_ne_zero
    (standardLubinTatePrimitivePolynomialOverField_irreducible hπ n)).2
      (standardLubinTatePrimitivePolynomialOverField_derivative_ne_zero hπ n)

/-- The primitive polynomial has a root in the chosen separable closure. -/
theorem exists_standardLubinTatePrimitivePolynomialOverField_root
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    ∃ x : SeparableClosure K,
      ((standardLubinTatePrimitivePolynomialOverField F π n).map
        (algebraMap K (SeparableClosure K))).IsRoot x := by
  let ι := algebraMap K (SeparableClosure K)
  let Q := standardLubinTatePrimitivePolynomialOverField F π n
  have hnat : 0 < (Q.map ι).natDegree := by
    rw [Polynomial.natDegree_map_eq_of_injective ι.injective,
      standardLubinTatePrimitivePolynomialOverField_natDegree]
    exact Nat.mul_pos
      (Nat.sub_pos_of_lt
        (Finite.one_lt_card : 1 < Nat.card F.residueField))
      (Nat.pow_pos Nat.card_pos)
  have hdegree : (Q.map ι).degree ≠ 0 :=
    ne_of_gt (Polynomial.natDegree_pos_iff_degree_pos.mp hnat)
  have hseparable : (Q.map ι).Separable :=
    (standardLubinTatePrimitivePolynomialOverField_separable hπ n).map
  exact IsSepClosed.exists_root (Q.map ι) hdegree hseparable

/-- A chosen primitive level-`n+1` root in `SeparableClosure K`. -/
noncomputable def chosenStandardLubinTatePrimitiveRoot
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    SeparableClosure K :=
  Classical.choose
    (exists_standardLubinTatePrimitivePolynomialOverField_root hπ n)

/-- The chosen primitive element is a root of the field-valued primitive
polynomial. -/
theorem chosenStandardLubinTatePrimitiveRoot_isRoot
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    ((standardLubinTatePrimitivePolynomialOverField F π n).map
      (algebraMap K (SeparableClosure K))).IsRoot
        (chosenStandardLubinTatePrimitiveRoot hπ n) :=
  Classical.choose_spec
    (exists_standardLubinTatePrimitivePolynomialOverField_root hπ n)

/-- The chosen primitive root is integral over the base field. -/
theorem chosenStandardLubinTatePrimitiveRoot_isIntegral
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsIntegral K (chosenStandardLubinTatePrimitiveRoot hπ n) := by
  refine
    ⟨standardLubinTatePrimitivePolynomialOverField F π n,
      standardLubinTatePrimitivePolynomialOverField_monic F π n, ?_⟩
  simpa [Polynomial.IsRoot, Polynomial.eval_map] using
    (chosenStandardLubinTatePrimitiveRoot_isRoot hπ n)

/-- The field-valued primitive polynomial is the minimal polynomial of the
chosen root. -/
theorem standardLubinTatePrimitivePolynomialOverField_eq_minpoly
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    standardLubinTatePrimitivePolynomialOverField F π n =
      minpoly K (chosenStandardLubinTatePrimitiveRoot hπ n) := by
  apply minpoly.eq_of_irreducible_of_monic
    (standardLubinTatePrimitivePolynomialOverField_irreducible hπ n)
    _
    (standardLubinTatePrimitivePolynomialOverField_monic F π n)
  rw [Polynomial.aeval_def]
  simpa [Polynomial.IsRoot, Polynomial.eval_map] using
    (chosenStandardLubinTatePrimitiveRoot_isRoot hπ n)

/-- The simple extension generated by the chosen primitive root. -/
@[reducible]
noncomputable def standardLubinTateLevelField
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IntermediateField K (SeparableClosure K) :=
  IntermediateField.adjoin K
    {chosenStandardLubinTatePrimitiveRoot hπ n}

/-- Every standard Lubin--Tate level field is finite-dimensional over the
base field. -/
theorem standardLubinTateLevelField_finiteDimensional
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    FiniteDimensional K (standardLubinTateLevelField hπ n) :=
  IntermediateField.adjoin.finiteDimensional
    (chosenStandardLubinTatePrimitiveRoot_isIntegral hπ n)

/-- The standard primitive level-`n+1` extension has degree
`(q - 1) * q ^ n`. -/
theorem standardLubinTateLevelField_finrank
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Module.finrank K (standardLubinTateLevelField hπ n) =
      (Nat.card F.residueField - 1) *
        Nat.card F.residueField ^ n := by
  change Module.finrank K
      (IntermediateField.adjoin K
        {chosenStandardLubinTatePrimitiveRoot hπ n}) = _
  rw [IntermediateField.adjoin.finrank
      (chosenStandardLubinTatePrimitiveRoot_isIntegral hπ n),
    ← standardLubinTatePrimitivePolynomialOverField_eq_minpoly hπ n,
    standardLubinTatePrimitivePolynomialOverField_natDegree]

end LubinTate

end
