import ClassFieldTheory.LubinTate.FiniteLevel.PrimitiveTorsion
import ValuedFieldTheory.LocalField.DiscreteValuationField.RamificationAddVal
import ValuedFieldTheory.Valuation.DiscreteValuationField.AddVal
import ValuedFieldTheory.Valuation.DiscreteValuationField.FiniteIntegralClosure
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.RingTheory.Discriminant
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral

set_option autoImplicit false

/-!
# Uniformizers in standard Lubin--Tate level fields

Let `F` be a local field, let `π` be a chosen uniformizer, and let
`Lₙ = K(λₙ)` be the simple extension generated by a chosen root of the
standard primitive division polynomial.  This file puts the integral-closure
complete discrete valuation on `Lₙ` and proves that `λₙ` is a uniformizer.

The valuation calculation uses the actual Eisenstein polynomial.  Its
constant coefficient has target additive valuation equal to the ramification
index, while every nonconstant lower term lies one step deeper in the target
maximal-ideal filtration.  Comparing with the leading term and the
fundamental identity forces the normalized additive valuation of `λₙ` to be
one.
-/

noncomputable section

open scoped Polynomial

universe u v w x

namespace LubinTate

open LocalFieldTheory.DiscreteValuationField
open LocalFieldTheory.DiscreteValuationField.ValuedExtension
open ValuationTheory.DiscreteValuationField
open ValuationTheory.DiscreteValuationField.ValuedExtension

variable {K : Type u} [Field K]

private theorem
    isIntegral_mem_adjoin_of_powerBasis_minpoly_isEisensteinAt
    {R K' L : Type*} [CommRing R] [IsDomain R]
    [IsDiscreteValuationRing R] [Field K'] [Field L]
    [Algebra R K'] [Algebra K' L] [Algebra R L]
    [IsScalarTower R K' L] [IsFractionRing R K']
    [FiniteDimensional K' L] [Algebra.IsSeparable K' L]
    (B : PowerBasis K' L) (pi : R) (hpi : Irreducible pi)
    (hBint : IsIntegral R B.gen)
    (hei : (minpoly R B.gen).IsEisensteinAt
      (Ideal.span ({pi} : Set R)))
    {z : L} (hzint : IsIntegral R z) :
    z ∈ Algebra.adjoin R ({B.gen} : Set L) := by
  have hdiscInt :
      IsIntegral R (Algebra.discr K' B.basis) :=
    Algebra.discr_isIntegral K' (fun i => by
      simpa using hBint.pow (i : ℕ))
  obtain ⟨d, hd⟩ :=
    IsIntegrallyClosed.isIntegral_iff.mp hdiscInt
  have hd0 : d ≠ 0 := by
    intro hd0
    have hdisc0 : Algebra.discr K' B.basis ≠ 0 :=
      Algebra.discr_not_zero_of_basis K' B.basis
    apply hdisc0
    rw [← hd, hd0, map_zero]
  obtain ⟨m, unit, hdu⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hd0 hpi
  have H :=
    Algebra.discr_mul_isIntegral_mem_adjoin K' hBint hzint
  rw [← hd, hdu, map_mul, map_pow] at H
  have Hpow :
      pi ^ m • z ∈ Algebra.adjoin R ({B.gen} : Set L) := by
    have HR :
        ((↑unit : R) * pi ^ m) • z ∈
          Algebra.adjoin R ({B.gen} : Set L) := by
      rw [← IsScalarTower.algebraMap_smul K']
      simpa [map_mul, map_pow] using H
    have Hu :=
      Subalgebra.smul_mem
        (Algebra.adjoin R ({B.gen} : Set L)) HR (↑(unit⁻¹) : R)
    simpa [smul_smul, ← mul_assoc] using Hu
  exact mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
    (UniqueFactorizationMonoid.irreducible_iff_prime.mp hpi)
    hBint hzint Hpow hei

private theorem
    integralClosure_adjoin_eq_top_of_powerBasis_minpoly_isEisensteinAt
    {R K' L A : Type*} [CommRing R] [IsDomain R]
    [IsDiscreteValuationRing R] [Field K'] [Field L] [CommRing A]
    [Algebra R K'] [Algebra K' L] [Algebra R L]
    [Algebra R A] [Algebra A L]
    [IsScalarTower R K' L] [IsScalarTower R A L]
    [IsFractionRing R K'] [FiniteDimensional K' L]
    [Algebra.IsSeparable K' L] [IsIntegralClosure A R L]
    (B : PowerBasis K' L) (pi : R) (hpi : Irreducible pi)
    (a : A) (ha : algebraMap A L a = B.gen)
    (hmap_injective : Function.Injective (algebraMap A L))
    (hBint : IsIntegral R B.gen)
    (hei : (minpoly R B.gen).IsEisensteinAt
      (Ideal.span ({pi} : Set R))) :
    Algebra.adjoin R ({a} : Set A) = ⊤ := by
  apply top_unique
  intro z _hz
  let j : A →ₐ[R] L := IsScalarTower.toAlgHom R A L
  have hzint : IsIntegral R (j z) :=
    IsIntegralClosure.isIntegral_iff.mpr ⟨z, rfl⟩
  have hzfield :
      j z ∈ Algebra.adjoin R ({B.gen} : Set L) :=
    isIntegral_mem_adjoin_of_powerBasis_minpoly_isEisensteinAt
      B pi hpi hBint hei hzint
  have hmap :
      (Algebra.adjoin R ({a} : Set A)).map j =
        Algebra.adjoin R ({B.gen} : Set L) := by
    rw [AlgHom.map_adjoin_singleton]
    congr 2
  rw [← hmap] at hzfield
  rcases hzfield with ⟨y, hy, hyz⟩
  have hya : y = z := hmap_injective hyz
  exact hya ▸ hy

/-- The canonical power basis of the simple standard Lubin--Tate level
extension. -/
noncomputable def standardLubinTateLevelPowerBasis
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    PowerBasis K (standardLubinTateLevelField hπ n) :=
  IntermediateField.adjoin.powerBasis
    (chosenStandardLubinTatePrimitiveRoot_isIntegral hπ n)

/-- The chosen primitive root, regarded as an element of its standard level
field. -/
noncomputable def standardLubinTateLevelGenerator
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    standardLubinTateLevelField hπ n :=
  (standardLubinTateLevelPowerBasis hπ n).gen

/-- The level-field generator is the chosen primitive root after inclusion
into the separable closure. -/
@[simp]
theorem standardLubinTateLevelGenerator_coe
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    ((standardLubinTateLevelGenerator hπ n :
        standardLubinTateLevelField hπ n) : SeparableClosure K) =
      chosenStandardLubinTatePrimitiveRoot hπ n := by
  simp [standardLubinTateLevelGenerator,
    standardLubinTateLevelPowerBasis,
    IntermediateField.adjoin.powerBasis_gen]

/-- The minimal polynomial of the level-field generator is the standard
primitive division polynomial over the base field. -/
theorem standardLubinTateLevelPowerBasis_minpoly
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    minpoly K (standardLubinTateLevelPowerBasis hπ n).gen =
      standardLubinTatePrimitivePolynomialOverField F π n := by
  change
    minpoly K
        (IntermediateField.adjoin.powerBasis
          (chosenStandardLubinTatePrimitiveRoot_isIntegral hπ n)).gen =
      standardLubinTatePrimitivePolynomialOverField F π n
  rw [IntermediateField.adjoin.powerBasis_gen,
    IntermediateField.minpoly_gen,
    ← standardLubinTatePrimitivePolynomialOverField_eq_minpoly hπ n]

/-- The integral primitive polynomial annihilates the level-field
generator. -/
theorem standardLubinTateLevelGenerator_aeval_primitivePolynomial
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Polynomial.aeval (standardLubinTateLevelGenerator hπ n)
        (standardLubinTatePrimitivePolynomial F π n) = 0 := by
  let Q := standardLubinTatePrimitivePolynomial F π n
  calc
    Polynomial.aeval (standardLubinTateLevelGenerator hπ n) Q =
        Polynomial.aeval (standardLubinTateLevelGenerator hπ n)
          (Q.map (algebraMap F.valuationSubring K)) := by
            symm
            exact Polynomial.aeval_map_algebraMap K
              (standardLubinTateLevelGenerator hπ n) Q
    _ = Polynomial.aeval (standardLubinTateLevelGenerator hπ n)
        (minpoly K (standardLubinTateLevelPowerBasis hπ n).gen) := by
          rw [standardLubinTateLevelPowerBasis_minpoly hπ n]
          rfl
    _ = 0 :=
      minpoly.aeval K (standardLubinTateLevelPowerBasis hπ n).gen

noncomputable local instance
    standardLubinTateLevelField_finiteDimensionalInstance
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    FiniteDimensional K (standardLubinTateLevelField hπ n) :=
  standardLubinTateLevelField_finiteDimensional hπ n

local instance standardLubinTateLevelField_isSeparableInstance
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Algebra.IsSeparable K (standardLubinTateLevelField hπ n) :=
  (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable
      (F := K) (E := SeparableClosure K)).2
    (Algebra.IsSeparable.isSeparable K
      (chosenStandardLubinTatePrimitiveRoot hπ n))

private theorem standardLubinTateLevelCompleteDVFData_exists
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    ∃ target : CompleteDVF.{u, 0} (standardLubinTateLevelField hπ n),
      ∃ hExt : F.toCompleteDVF.valuation.HasExtension target.valuation,
        letI : F.toCompleteDVF.valuation.HasExtension target.valuation := hExt
        IsIntegralClosure target.valuationSubring F.valuationSubring
            (standardLubinTateLevelField hπ n) ∧
          degree F.toCompleteDVF.toDVF target.toDVF =
            ramificationIndex F.toCompleteDVF.toDVF target.toDVF *
              residueDegree F.toCompleteDVF.toDVF target.toDVF := by
  exact
    exists_integralClosure_standard_fundamental_identity
      (K := K) (L := standardLubinTateLevelField hπ n)
      F.toCompleteDVF

/-- The complete discrete valuation on a standard Lubin--Tate level field
selected from its actual integral closure over the base valuation ring. -/
noncomputable def standardLubinTateLevelCompleteDVF
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    CompleteDVF.{u, 0} (standardLubinTateLevelField hπ n) :=
  Classical.choose (standardLubinTateLevelCompleteDVFData_exists hπ n)

/-- The chosen level valuation extends the given base valuation. -/
theorem standardLubinTateLevelCompleteDVF_hasExtension
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    F.toCompleteDVF.valuation.HasExtension
      (standardLubinTateLevelCompleteDVF hπ n).valuation :=
  Classical.choose
    (Classical.choose_spec
      (standardLubinTateLevelCompleteDVFData_exists hπ n))

noncomputable instance
    standardLubinTateLevelCompleteDVF_hasExtensionInstance
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    F.toCompleteDVF.valuation.HasExtension
      (standardLubinTateLevelCompleteDVF hπ n).valuation :=
  standardLubinTateLevelCompleteDVF_hasExtension hπ n

local instance standardLubinTateLevelValuationSubring_isScalarTower
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsScalarTower F.valuationSubring
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
      (standardLubinTateLevelField hπ n) :=
  IsScalarTower.of_algebraMap_eq' rfl

/-- The target valuation ring is the actual integral closure of the base
valuation ring in the standard level field. -/
theorem standardLubinTateLevelCompleteDVF_isIntegralClosure
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsIntegralClosure
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
      F.valuationSubring (standardLubinTateLevelField hπ n) :=
  (Classical.choose_spec
    (Classical.choose_spec
      (standardLubinTateLevelCompleteDVFData_exists hπ n))).1

/-- The chosen integral-closure valuation satisfies the fundamental identity
at the standard Lubin--Tate level. -/
theorem standardLubinTateLevelCompleteDVF_fundamentalIdentity
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    degree F.toCompleteDVF.toDVF
        (standardLubinTateLevelCompleteDVF hπ n).toDVF =
      ramificationIndex F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF *
        residueDegree F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF :=
  (Classical.choose_spec
    (Classical.choose_spec
      (standardLubinTateLevelCompleteDVFData_exists hπ n))).2

noncomputable instance
    standardLubinTateLevelValuationSubring_moduleFinite
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Module.Finite F.valuationSubring
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring := by
  let : IsIntegralClosure
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
      F.valuationSubring (standardLubinTateLevelField hπ n) :=
    standardLubinTateLevelCompleteDVF_isIntegralClosure hπ n
  let : IsFractionRing F.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) F.toCompleteDVF
  let : IsIntegrallyClosed F.valuationSubring :=
    base_valuationSubring_isIntegrallyClosed (K := K) F.toCompleteDVF
  let : IsNoetherianRing F.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) F.toCompleteDVF
  exact IsIntegralClosure.finite F.valuationSubring K
    (standardLubinTateLevelField hπ n)
    (standardLubinTateLevelCompleteDVF hπ n).valuationSubring

/-- The chosen complete-DVF structure is a local-field structure: its
residue field is finite over the finite residue field of `F`. -/
noncomputable def standardLubinTateLevelLocalField
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    LocalField.{u, 0} (standardLubinTateLevelField hπ n) := by
  let target := standardLubinTateLevelCompleteDVF hπ n
  letI : FiniteDimensional F.residueField target.residueField :=
    residueField_finiteDimensional_of_moduleFinite F.toCompleteDVF target
  letI : Finite target.residueField :=
    Module.finite_of_finite F.residueField
  exact { toCompleteDVF := target }

/-- The level generator is integral over the base valuation ring, witnessed
by the genuine integral primitive division polynomial. -/
theorem standardLubinTateLevelGenerator_isIntegral_over_valuationSubring
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsIntegral F.valuationSubring
      (standardLubinTateLevelGenerator hπ n) :=
  ⟨standardLubinTatePrimitivePolynomial F π n,
    standardLubinTatePrimitivePolynomial_monic F π n,
    standardLubinTateLevelGenerator_aeval_primitivePolynomial hπ n⟩

/-- The integral minimal polynomial of the primitive level generator is the
standard primitive division polynomial. -/
theorem standardLubinTatePrimitivePoint_minpoly
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    minpoly F.valuationSubring
        (standardLubinTateLevelPowerBasis hπ n).gen =
      standardLubinTatePrimitivePolynomial F π n := by
  have hgen :
      IsIntegral F.valuationSubring
        (standardLubinTateLevelPowerBasis hπ n).gen := by
    simpa only [standardLubinTateLevelGenerator] using
      standardLubinTateLevelGenerator_isIntegral_over_valuationSubring
        hπ n
  apply Polynomial.map_injective
    (algebraMap F.valuationSubring K)
    (fun x y h => Subtype.ext h)
  rw [← minpoly.isIntegrallyClosed_eq_field_fractions' K
      hgen,
    standardLubinTateLevelPowerBasis_minpoly hπ n]
  rfl

/-- The chosen primitive root belongs to the selected integral-closure
valuation ring. -/
theorem standardLubinTateLevelGenerator_mem_valuationSubring
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    standardLubinTateLevelGenerator hπ n ∈
      (standardLubinTateLevelCompleteDVF hπ n).valuation.valuationSubring := by
  let : IsIntegralClosure
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
      F.valuationSubring (standardLubinTateLevelField hπ n) :=
    standardLubinTateLevelCompleteDVF_isIntegralClosure hπ n
  rcases
      (IsIntegralClosure.isIntegral_iff
        (A := (standardLubinTateLevelCompleteDVF hπ n).valuationSubring)
        (R := F.valuationSubring)
        (B := standardLubinTateLevelField hπ n)).1
        (standardLubinTateLevelGenerator_isIntegral_over_valuationSubring
          hπ n) with
    ⟨z, hz⟩
  change
    (standardLubinTateLevelCompleteDVF hπ n).valuation
        (standardLubinTateLevelGenerator hπ n) ≤ 1
  rw [← hz]
  exact z.property

/-- The primitive division point as an element of the chosen level valuation
ring. -/
noncomputable def standardLubinTatePrimitivePointInteger
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTateLevelCompleteDVF hπ n).valuationSubring :=
  ⟨standardLubinTateLevelGenerator hπ n,
    standardLubinTateLevelGenerator_mem_valuationSubring hπ n⟩

/-- The valuation-ring primitive point has the chosen level generator as its
underlying field element. -/
@[simp]
theorem standardLubinTatePrimitivePointInteger_coe
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTatePrimitivePointInteger hπ n :
      standardLubinTateLevelField hπ n) =
        standardLubinTateLevelGenerator hπ n :=
  rfl

/-- The primitive Lubin--Tate point generates the entire integral-closure
valuation ring over the base valuation ring. -/
theorem standardLubinTatePrimitivePointInteger_adjoin_eq_top
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Algebra.adjoin F.valuationSubring
        ({standardLubinTatePrimitivePointInteger hπ n} :
          Set
            (standardLubinTateLevelCompleteDVF hπ n).valuationSubring) =
      ⊤ := by
  let : FiniteDimensional K (standardLubinTateLevelField hπ n) :=
    standardLubinTateLevelField_finiteDimensional hπ n
  let : IsScalarTower F.valuationSubring
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
      (standardLubinTateLevelField hπ n) :=
    IsScalarTower.of_algebraMap_eq' rfl
  let : IsIntegralClosure
      (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
      F.valuationSubring (standardLubinTateLevelField hπ n) :=
    standardLubinTateLevelCompleteDVF_isIntegralClosure hπ n
  have hπIrreducible : Irreducible π :=
    (IsDiscreteValuationRing.irreducible_iff_uniformizer π).2
      (F.toCompleteDVF.maximalIdeal_eq_span_uniformizer hπ)
  apply
    integralClosure_adjoin_eq_top_of_powerBasis_minpoly_isEisensteinAt
      (standardLubinTateLevelPowerBasis hπ n)
      π hπIrreducible
      (standardLubinTatePrimitivePointInteger hπ n)
      (by rfl)
      (fun x y h => Subtype.ext h)
      (standardLubinTateLevelGenerator_isIntegral_over_valuationSubring
        hπ n)
  rw [standardLubinTatePrimitivePoint_minpoly hπ n]
  rw [← F.toCompleteDVF.maximalIdeal_eq_span_uniformizer hπ]
  exact standardLubinTatePrimitivePolynomial_isEisensteinAt hπ n

private noncomputable def
    standardLubinTatePrimitivePointIntegerToSeparableClosure
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTateLevelCompleteDVF hπ n).valuationSubring →+*
      SeparableClosure K :=
  (standardLubinTateLevelField hπ n).val.toRingHom.comp
    (standardLubinTateLevelCompleteDVF hπ n).valuation.valuationSubring.subtype

private theorem
    standardLubinTatePrimitivePointIntegerToSeparableClosure_injective
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Function.Injective
      (standardLubinTatePrimitivePointIntegerToSeparableClosure hπ n) := by
  intro a b hab
  change
    (standardLubinTateLevelField hπ n).val
        (a : standardLubinTateLevelField hπ n) =
      (standardLubinTateLevelField hπ n).val
        (b : standardLubinTateLevelField hπ n) at hab
  apply Subtype.ext
  exact (standardLubinTateLevelField hπ n).val.injective hab

private theorem
    standardLubinTatePrimitivePointIntegerToSeparableClosure_comp_integerMap
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTatePrimitivePointIntegerToSeparableClosure hπ n).comp
        (integerMap F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF) =
      (algebraMap K (SeparableClosure K)).comp
        (algebraMap F.valuationSubring K) := by
  apply RingHom.ext
  intro a
  change
    ((standardLubinTateLevelField hπ n).val
      (((integerMap F.toCompleteDVF.toDVF
        (standardLubinTateLevelCompleteDVF hπ n).toDVF) a :
          (standardLubinTateLevelCompleteDVF hπ n).valuationSubring) :
        standardLubinTateLevelField hπ n)) =
      algebraMap K (SeparableClosure K)
        (algebraMap F.valuationSubring K a)
  rw [integerMap_apply]
  exact (standardLubinTateLevelField hπ n).val.commutes
    (algebraMap F.valuationSubring K a)

private theorem
    standardLubinTatePrimitivePointIntegerToSeparableClosure_apply
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    standardLubinTatePrimitivePointIntegerToSeparableClosure hπ n
        (standardLubinTatePrimitivePointInteger hπ n) =
      chosenStandardLubinTatePrimitiveRoot hπ n := by
  change
    ((standardLubinTateLevelGenerator hπ n :
      standardLubinTateLevelField hπ n) : SeparableClosure K) =
        chosenStandardLubinTatePrimitiveRoot hπ n
  exact standardLubinTateLevelGenerator_coe hπ n

private theorem polynomial_eval₂_mem_ideal_of_coeff_mem
    {R S : Type*} [CommSemiring R] [CommSemiring S]
    (f : R →+* S) (I : Ideal S) (P : Polynomial R) (z : S)
    (hcoeff : ∀ i, f (P.coeff i) ∈ I) :
    P.eval₂ f z ∈ I := by
  rw [Polynomial.eval₂_eq_sum_range]
  exact Ideal.sum_mem _ fun i _ =>
    Ideal.mul_mem_right (z ^ i) I (hcoeff i)

/-- The integral primitive polynomial annihilates the primitive point in the
valuation ring of the standard finite level. -/
theorem standardLubinTatePrimitivePointInteger_aeval
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Polynomial.aeval (standardLubinTatePrimitivePointInteger hπ n)
        (standardLubinTatePrimitivePolynomial F π n) = 0 := by
  let target := standardLubinTateLevelCompleteDVF hπ n
  let i : target.valuationSubring →ₐ[F.valuationSubring]
      standardLubinTateLevelField hπ n :=
    IsScalarTower.toAlgHom F.valuationSubring target.valuationSubring
      (standardLubinTateLevelField hπ n)
  apply Subtype.ext
  change
    i (Polynomial.aeval (standardLubinTatePrimitivePointInteger hπ n)
      (standardLubinTatePrimitivePolynomial F π n)) = i 0
  rw [← Polynomial.aeval_algHom_apply (f := i), map_zero]
  simpa [i] using
    standardLubinTateLevelGenerator_aeval_primitivePolynomial hπ n

private theorem
    standardLubinTatePrimitivePointInteger_addVal_and_ramificationIndex
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsDiscreteValuationRing.addVal
        (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
        (standardLubinTatePrimitivePointInteger hπ n) = 1 ∧
      ramificationIndex F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF =
        degree F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF := by
  let base := F.toCompleteDVF
  let target := standardLubinTateLevelCompleteDVF hπ n
  let Q := standardLubinTatePrimitivePolynomial F π n
  let d :=
    (Nat.card F.residueField - 1) * Nat.card F.residueField ^ n
  let e := ramificationIndex base.toDVF target.toDVF
  let f := residueDegree base.toDVF target.toDVF
  let p := base.maximalIdeal
  let P := target.maximalIdeal
  let j := integerMap base.toDVF target.toDVF
  let lambda := standardLubinTatePrimitivePointInteger hπ n
  let R := Q - Polynomial.X ^ d
  have hdpos : 0 < d := by
    dsimp [d]
    exact Nat.mul_pos
      (Nat.sub_pos_of_lt
        (Finite.one_lt_card : 1 < Nat.card F.residueField))
      (Nat.pow_pos Nat.card_pos)
  have hdne : d ≠ 0 := Nat.ne_of_gt hdpos
  have hdegree : degree base.toDVF target.toDVF = d := by
    simpa [base, target, d, degree] using
      standardLubinTateLevelField_finrank hπ n
  have hfund : d = e * f := by
    calc
      d = degree base.toDVF target.toDVF := hdegree.symm
      _ = e * f := by
        simpa [base, target, e, f] using
          standardLubinTateLevelCompleteDVF_fundamentalIdentity hπ n
  have he_ne : e ≠ 0 := by
    intro he
    apply hdne
    rw [hfund, he, zero_mul]
  have hf_ne : f ≠ 0 := by
    intro hf
    apply hdne
    rw [hfund, hf, mul_zero]
  have hele : e ≤ d := by
    rw [hfund]
    exact Nat.le_mul_of_pos_right e (Nat.pos_of_ne_zero hf_ne)
  have hRmap : R.map F.residueMap = 0 := by
    change
      (standardLubinTatePrimitivePolynomial F π n -
        Polynomial.X ^ d).map F.residueMap = 0
    rw [Polynomial.map_sub,
      standardLubinTatePrimitivePolynomial_map_residue hπ n,
      Polynomial.map_pow, Polynomial.map_X, sub_self]
  have hRcoeff (i : ℕ) : R.coeff i ∈ p := by
    apply (base.residue_eq_zero_iff (R.coeff i)).1
    simpa [base, p] using
      congrArg (fun S : Polynomial F.residueField => S.coeff i) hRmap
  have hR_eval_mem_map :
      R.eval₂ j lambda ∈ Ideal.map j p :=
    polynomial_eval₂_mem_ideal_of_coeff_mem j (Ideal.map j p) R lambda
      (fun i => Ideal.mem_map_of_mem j (hRcoeff i))
  have hmap :
      Ideal.map j p = P ^ e := by
    simpa [base, target, p, P, j, e] using
      maximalIdeal_map_eq_target_maximalIdeal_pow_ramificationIndex
        base target
  have hR_eval_mem_pow : R.eval₂ j lambda ∈ P ^ e := by
    rw [← hmap]
    exact hR_eval_mem_map
  have hR_eval_mem_P : R.eval₂ j lambda ∈ P :=
    by
      simpa only [pow_one] using
        Ideal.pow_le_pow_right (Nat.pos_of_ne_zero he_ne)
          hR_eval_mem_pow
  have hroot : Q.eval₂ j lambda = 0 := by
    simpa only [Polynomial.aeval_def, Q, j, lambda, base, target,
      integerMap] using
      standardLubinTatePrimitivePointInteger_aeval hπ n
  have hQdecomp : Q = Polynomial.X ^ d + R := by
    calc
      Q = (Q - Polynomial.X ^ d) + Polynomial.X ^ d :=
        (sub_add_cancel Q (Polynomial.X ^ d)).symm
      _ = Polynomial.X ^ d + R := by
        rw [add_comm]
  have hrootDecomp : lambda ^ d + R.eval₂ j lambda = 0 := by
    rw [hQdecomp, Polynomial.eval₂_add, Polynomial.eval₂_pow,
      Polynomial.eval₂_X] at hroot
    exact hroot
  have hlambdaPowMem : lambda ^ d ∈ P := by
    have heq : lambda ^ d = -(R.eval₂ j lambda) :=
      eq_neg_of_add_eq_zero_left hrootDecomp
    rw [heq]
    exact P.neg_mem hR_eval_mem_P
  have hPprime : P.IsPrime :=
    (IsLocalRing.maximalIdeal.isMaximal target.valuationSubring).isPrime
  have hlambdaMem : lambda ∈ P :=
    hPprime.mem_of_pow_mem d hlambdaPowMem
  have hdivCoeff (i : ℕ) : (R.divX.coeff i) ∈ p := by
    rw [Polynomial.coeff_divX]
    exact hRcoeff (i + 1)
  let tail := R.divX.eval₂ j lambda
  have htail_mem_map : tail ∈ Ideal.map j p :=
    polynomial_eval₂_mem_ideal_of_coeff_mem j (Ideal.map j p) R.divX
      lambda (fun i => Ideal.mem_map_of_mem j (hdivCoeff i))
  have htail_mem_pow : tail ∈ P ^ e := by
    rw [← hmap]
    exact htail_mem_map
  have hlambdaTailMem : lambda * tail ∈ P ^ (e + 1) := by
    rw [pow_succ]
    have hmul :
        tail * lambda ∈ P ^ e * P :=
      Ideal.mul_mem_mul htail_mem_pow hlambdaMem
    rwa [mul_comm tail lambda] at hmul
  have hRcoeffZero : R.coeff 0 = π := by
    change
      (standardLubinTatePrimitivePolynomial F π n -
        Polynomial.X ^ d).coeff 0 = π
    rw [Polynomial.coeff_sub,
      standardLubinTatePrimitivePolynomial_coeff_zero]
    simp only [Polynomial.coeff_X_pow, if_neg hdne.symm, sub_zero]
  have hpiIrreducible : Irreducible π := by
    exact
      (IsDiscreteValuationRing.irreducible_iff_uniformizer π).2
        (base.maximalIdeal_eq_span_uniformizer hπ)
  have hconst :
      IsDiscreteValuationRing.addVal target.valuationSubring
          (j (R.coeff 0)) = (e : ℕ∞) := by
    rw [hRcoeffZero]
    exact addVal_integerMap_eq_ramificationIndex_of_irreducible base target
      hpiIrreducible
  have hR_eval :
      R.eval₂ j lambda = j (R.coeff 0) + lambda * tail := by
    have h :=
      congrArg (Polynomial.eval₂ j lambda)
        (Polynomial.X_mul_divX_add R)
    rw [Polynomial.eval₂_add, Polynomial.eval₂_mul,
      Polynomial.eval₂_X, Polynomial.eval₂_C] at h
    calc
      R.eval₂ j lambda = lambda * tail + j (R.coeff 0) := by
        simpa [tail] using h.symm
      _ = j (R.coeff 0) + lambda * tail :=
        add_comm _ _
  have htailVal :
      ((e + 1 : ℕ) : ℕ∞) ≤
        IsDiscreteValuationRing.addVal target.valuationSubring
          (lambda * tail) :=
    (IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge
      (lambda * tail) (e + 1)).1 hlambdaTailMem
  have heCastLt :
      (e : ℕ∞) <
        IsDiscreteValuationRing.addVal target.valuationSubring
          (lambda * tail) := by
    exact
      (show (e : ℕ∞) < ((e + 1 : ℕ) : ℕ∞) by
        exact_mod_cast Nat.lt_succ_self e).trans_le htailVal
  have hdistinct :
      IsDiscreteValuationRing.addVal target.valuationSubring
          (j (R.coeff 0)) ≠
        IsDiscreteValuationRing.addVal target.valuationSubring
          (lambda * tail) := by
    rw [hconst]
    exact ne_of_lt heCastLt
  have hRval :
      IsDiscreteValuationRing.addVal target.valuationSubring
          (R.eval₂ j lambda) = (e : ℕ∞) := by
    rw [hR_eval,
      (IsDiscreteValuationRing.addVal target.valuationSubring).map_add_of_distinct_val
        hdistinct,
      hconst, min_eq_left]
    exact heCastLt.le
  have hpowEq :
      lambda ^ d = -(R.eval₂ j lambda) :=
    eq_neg_of_add_eq_zero_left hrootDecomp
  have hmul :
      (d : ℕ∞) *
          IsDiscreteValuationRing.addVal target.valuationSubring lambda =
        (e : ℕ∞) := by
    calc
      (d : ℕ∞) *
          IsDiscreteValuationRing.addVal target.valuationSubring lambda =
          d • IsDiscreteValuationRing.addVal
            target.valuationSubring lambda := by
              rw [nsmul_eq_mul]
      _ = IsDiscreteValuationRing.addVal target.valuationSubring
          (lambda ^ d) := by
            symm
            exact IsDiscreteValuationRing.addVal_pow lambda d
      _ = IsDiscreteValuationRing.addVal target.valuationSubring
          (-(R.eval₂ j lambda)) := by rw [hpowEq]
      _ = IsDiscreteValuationRing.addVal target.valuationSubring
          (R.eval₂ j lambda) :=
        (IsDiscreteValuationRing.addVal target.valuationSubring).map_neg _
      _ = (e : ℕ∞) := hRval
  have honele :
      1 ≤ IsDiscreteValuationRing.addVal target.valuationSubring lambda := by
    simpa using
      (IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_addVal_ge
        lambda 1).1
        (by simpa only [pow_one] using hlambdaMem)
  have hdcoe : (d : ℕ∞) ≠ 0 := by
    exact_mod_cast hdne
  have hmul_le :
      (d : ℕ∞) *
          IsDiscreteValuationRing.addVal target.valuationSubring lambda ≤
        (d : ℕ∞) * 1 := by
    rw [hmul]
    have hcast : (e : ℕ∞) ≤ (d : ℕ∞) := by
      exact_mod_cast hele
    simpa using hcast
  have hvle :
      IsDiscreteValuationRing.addVal target.valuationSubring lambda ≤ 1 :=
    (ENat.mul_le_mul_left_iff hdcoe (ENat.natCast_ne_top d)).1 hmul_le
  have hlambdaVal :
      IsDiscreteValuationRing.addVal target.valuationSubring lambda = 1 :=
    le_antisymm hvle honele
  have hed : e = d := by
    rw [hlambdaVal, mul_one] at hmul
    exact_mod_cast hmul.symm
  have heramDegree :
      ramificationIndex F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF =
        degree F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF := by
    simpa [base, target, e] using hed.trans hdegree.symm
  exact ⟨hlambdaVal, heramDegree⟩

/-- The chosen primitive division point has normalized additive valuation one
in the integral-closure valuation ring. -/
theorem standardLubinTatePrimitivePointInteger_addVal
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsDiscreteValuationRing.addVal
        (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
        (standardLubinTatePrimitivePointInteger hπ n) = 1 :=
  (standardLubinTatePrimitivePointInteger_addVal_and_ramificationIndex
    hπ n).1

/-- The standard finite Lubin--Tate level is totally ramified: its
ramification index equals its field degree. -/
theorem standardLubinTateLevel_ramificationIndex_eq_degree
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    ramificationIndex F.toCompleteDVF.toDVF
        (standardLubinTateLevelCompleteDVF hπ n).toDVF =
      degree F.toCompleteDVF.toDVF
        (standardLubinTateLevelCompleteDVF hπ n).toDVF :=
  (standardLubinTatePrimitivePointInteger_addVal_and_ramificationIndex
    hπ n).2

/-- The image of any base-field uniformizer in a standard finite level has
additive valuation equal to the degree of that level.  The uniformizer used
here need not be the parameter defining the Lubin--Tate level. -/
theorem standardLubinTateUniformizerInteger_map_addVal
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K))
    {ϖ : F.valuationSubring}
    (hϖ : F.toCompleteDVF.valuation.IsUniformizer (ϖ : K))
    (n : ℕ) :
    IsDiscreteValuationRing.addVal
        (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
        (integerMap F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF ϖ) =
      (((Nat.card F.residueField - 1) *
        Nat.card F.residueField ^ n : ℕ) : ℕ∞) := by
  let target := standardLubinTateLevelCompleteDVF hπ n
  have hϖIrreducible : Irreducible ϖ := by
    exact
      (IsDiscreteValuationRing.irreducible_iff_uniformizer ϖ).2
        (F.toCompleteDVF.maximalIdeal_eq_span_uniformizer hϖ)
  have hdegree :
      degree F.toCompleteDVF.toDVF target.toDVF =
        (Nat.card F.residueField - 1) *
          Nat.card F.residueField ^ n := by
    simpa [target, degree] using
      standardLubinTateLevelField_finrank hπ n
  calc
    IsDiscreteValuationRing.addVal target.valuationSubring
        (integerMap F.toCompleteDVF.toDVF target.toDVF ϖ) =
        (ramificationIndex F.toCompleteDVF.toDVF target.toDVF : ℕ∞) :=
      addVal_integerMap_eq_ramificationIndex_of_irreducible
        F.toCompleteDVF target
        hϖIrreducible
    _ = (degree F.toCompleteDVF.toDVF target.toDVF : ℕ∞) := by
      rw [standardLubinTateLevel_ramificationIndex_eq_degree hπ n]
    _ = (((Nat.card F.residueField - 1) *
        Nat.card F.residueField ^ n : ℕ) : ℕ∞) := by
      exact_mod_cast hdegree

/-- The image of the parameter uniformizer has additive valuation equal to
the standard finite-level degree. -/
theorem standardLubinTateBaseUniformizerInteger_map_addVal
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    IsDiscreteValuationRing.addVal
        (standardLubinTateLevelCompleteDVF hπ n).valuationSubring
        (integerMap F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF π) =
      (((Nat.card F.residueField - 1) *
        Nat.card F.residueField ^ n : ℕ) : ℕ∞) :=
  standardLubinTateUniformizerInteger_map_addVal hπ hπ n

/-- The primitive point is irreducible in the integral-closure valuation
ring. -/
theorem standardLubinTatePrimitivePointInteger_irreducible
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Irreducible (standardLubinTatePrimitivePointInteger hπ n) := by
  let target := standardLubinTateLevelCompleteDVF hπ n
  let lambda := standardLubinTatePrimitivePointInteger hπ n
  obtain ⟨varpi, hvarpi⟩ :=
    IsDiscreteValuationRing.exists_irreducible target.valuationSubring
  have hval :
      IsDiscreteValuationRing.addVal target.valuationSubring lambda =
        IsDiscreteValuationRing.addVal target.valuationSubring varpi := by
    rw [standardLubinTatePrimitivePointInteger_addVal hπ n,
      IsDiscreteValuationRing.addVal_uniformizer hvarpi]
  exact
    ((IsDiscreteValuationRing.addVal_eq_iff_associated lambda varpi).1 hval).symm.irreducible
      hvarpi

/-- The chosen primitive division point is a uniformizer of the standard
Lubin--Tate level field with its integral-closure valuation. -/
theorem standardLubinTatePrimitivePoint_isUniformizer
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    (standardLubinTateLevelCompleteDVF hπ n).valuation.IsUniformizer
      (standardLubinTatePrimitivePointInteger hπ n :
        standardLubinTateLevelField hπ n) := by
  exact Valuation.isUniformizer_of_maximalIdeal_eq_span
    (v := (standardLubinTateLevelCompleteDVF hπ n).valuation)
    (standardLubinTatePrimitivePointInteger_irreducible hπ n).maximalIdeal_eq

/-- Evaluation in the chosen target valuation ring records that the primitive
level-`n + 1` point is killed by the level-`n + 1` standard iterate. -/
theorem standardLubinTatePrimitivePointInteger_iterate_succ_eq_zero
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ) :
    Polynomial.eval₂
        (integerMap F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF)
        (standardLubinTatePrimitivePointInteger hπ n)
        (standardLubinTatePolynomialIterate F π (n + 1)) = 0 := by
  apply
    standardLubinTatePrimitivePointIntegerToSeparableClosure_injective
      hπ n
  rw [map_zero, Polynomial.hom_eval₂,
    standardLubinTatePrimitivePointIntegerToSeparableClosure_comp_integerMap
      hπ n,
    standardLubinTatePrimitivePointIntegerToSeparableClosure_apply hπ n]
  simpa only [
    standardLubinTatePolynomialIterateOverSeparableClosure_eval] using
      chosenStandardLubinTatePrimitiveRoot_iterate_succ_eq_zero hπ n

/-- No iterate of index at most `n` already kills the primitive
level-`n + 1` point, now expressed inside the chosen target valuation ring. -/
theorem standardLubinTatePrimitivePointInteger_iterate_ne_zero_of_le
    {F : LocalField.{u, v} K} {π : F.valuationSubring}
    (hπ : F.toCompleteDVF.valuation.IsUniformizer (π : K)) (n : ℕ)
    {r : ℕ} (hr : r ≤ n) :
    Polynomial.eval₂
        (integerMap F.toCompleteDVF.toDVF
          (standardLubinTateLevelCompleteDVF hπ n).toDVF)
        (standardLubinTatePrimitivePointInteger hπ n)
        (standardLubinTatePolynomialIterate F π r) ≠ 0 := by
  intro hzero
  have hzeroMap :=
    congrArg
      (standardLubinTatePrimitivePointIntegerToSeparableClosure hπ n)
      hzero
  rw [map_zero, Polynomial.hom_eval₂,
    standardLubinTatePrimitivePointIntegerToSeparableClosure_comp_integerMap
      hπ n,
    standardLubinTatePrimitivePointIntegerToSeparableClosure_apply hπ n]
      at hzeroMap
  have hzeroSeparable :
      (standardLubinTatePolynomialIterateOverSeparableClosure F π r).eval
          (chosenStandardLubinTatePrimitiveRoot hπ n) = 0 := by
    simpa only [
      standardLubinTatePolynomialIterateOverSeparableClosure_eval] using
        hzeroMap
  have hnzero :
      (standardLubinTatePolynomialIterateOverSeparableClosure F π n).eval
          (chosenStandardLubinTatePrimitiveRoot hπ n) = 0 := by
    calc
      (standardLubinTatePolynomialIterateOverSeparableClosure F π n).eval
          (chosenStandardLubinTatePrimitiveRoot hπ n) =
          (standardLubinTatePolynomialIterateOverSeparableClosure
            F π ((n - r) + r)).eval
              (chosenStandardLubinTatePrimitiveRoot hπ n) := by
                rw [Nat.sub_add_cancel hr]
      _ =
          (standardLubinTatePolynomialIterateOverSeparableClosure
            F π (n - r)).eval
              ((standardLubinTatePolynomialIterateOverSeparableClosure
                F π r).eval
                  (chosenStandardLubinTatePrimitiveRoot hπ n)) :=
        standardLubinTatePolynomialIterateOverSeparableClosure_eval_add
          F π (n - r) r
            (chosenStandardLubinTatePrimitiveRoot hπ n)
      _ =
          (standardLubinTatePolynomialIterateOverSeparableClosure
            F π (n - r)).eval 0 := by
              rw [hzeroSeparable]
      _ = 0 := by
        rw [standardLubinTatePolynomialIterateOverSeparableClosure,
          Polynomial.eval_zero_map,
          standardLubinTatePolynomialIterate_eval_zero, map_zero]
  exact chosenStandardLubinTatePrimitiveRoot_iterate_ne_zero hπ n hnzero

end LubinTate

end
