import ProCGroups.GolodShafarevich.WeightedFiniteCriterion
import ProCGroups.ProP.CountableRelatorFiniteWitness
import ProCGroups.ProP.Presentation.FiniteGeneration
import ProCGroups.ProC.InverseLimits.Limits
import Mathlib.Algebra.BigOperators.Fin

set_option autoImplicit false

/-!
# Countable deep relations preserve a strict Golod--Shafarevich budget

If the final quotient were finite, its open, finitely generated relation
subgroup would already be generated by one finite prefix. The weighted
finite-presentation inequality then contradicts the prefix budget.
-/

namespace ClassFieldTower.ProP

open ProCGroups ProCGroups.Presentations

noncomputable section

universe u

private theorem range_addCases_prefix
    {F : Type u} {r N : ℕ} (a : Fin r → F) (f : ℕ → F) :
    Set.range (Fin.addCases a (fun i : Fin N => f i)) =
      Set.range a ∪ f '' (Finset.range N : Set ℕ) := by
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    refine Fin.addCases ?_ ?_ i
    · intro j
      exact Or.inl ⟨j, by simp⟩
    · intro j
      exact Or.inr ⟨j, by simp, by simp⟩
  · rintro (⟨i, rfl⟩ | ⟨n, hn, rfl⟩)
    · exact ⟨Fin.castAdd N i, by simp⟩
    · refine ⟨Fin.natAdd r ⟨n, by simpa using hn⟩, ?_⟩
      exact Fin.addCases_right _

namespace FiniteProPPresentation

variable {p d r : ℕ} [Fact p.Prime]
variable {sourceData :
  FreeProC.EpimorphicallyFreeProCGroupOnConvergingSetData.{u, u}
    (FiniteGroupClass.pGroup p)}
variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]

/-- Adding a countable family of displayed deep relators preserves infinitude
when every finite prefix has a nonpositive weighted GS polynomial. -/
theorem infinite_quotient_of_countable_relator_budget
    (P : FiniteProPPresentation p d r sourceData G)
    (ν₀ : Fin r → ℕ)
    (hν₀ : ∀ i, P.RelatorZassenhausDepthAtLeast (ν₀ i) i)
    (f : ℕ → sourceData.carrier) (ν : ℕ → ℕ)
    (hν : ∀ n, ZassenhausDepthAtLeast p (ν n) (f n))
    {t : ℝ} (ht0 : 0 ≤ t) (ht1 : t < 1)
    (hbudget : ∀ N, 1 - (d : ℝ) * t +
      (∑ i : Fin r, t ^ ν₀ i) + (∑ i : Fin N, t ^ ν i) ≤ 0) :
    Infinite (sourceData.carrier ⧸
      closedNormalClosure (Set.range P.relator ∪ Set.range f)) := by
  classical
  let K := closedNormalClosure (Set.range P.relator ∪ Set.range f)
  let Q := sourceData.carrier ⧸ K
  by_contra hfinite
  let : Finite Q := Finite.of_not_infinite hfinite
  have hKclosed : IsClosed (K : Set sourceData.carrier) :=
    closedNormalClosure_isClosed _
  let : IsClosed (K : Set sourceData.carrier) := hKclosed
  have hsource : ProC.HasPGroupOpenNormalBasis p sourceData.carrier :=
    sourceData.isEpimorphicallyFree.hasOpenNormalBasisInClass
  obtain ⟨N, hN⟩ :=
    exists_finitePrefix_eq_closedNormalClosure_of_finite_quotient hsource
      P.source_topologicallyFinitelyGenerated (Set.range P.relator) f
  let rel : Fin (r + N) → sourceData.carrier :=
    Fin.addCases P.relator (fun i : Fin N => f i)
  let depth : Fin (r + N) → ℕ :=
    Fin.addCases ν₀ (fun i : Fin N => ν i)
  have hrange : Set.range rel =
      Set.range P.relator ∪ f '' (Finset.range N : Set ℕ) :=
    range_addCases_prefix P.relator f
  have htarget : ProC.HasPGroupOpenNormalBasis p Q :=
    ProC.quotient_closedNormalSubgroup
      (FiniteGroupClass.pGroup_formation p).isomClosed
      (FiniteGroupClass.pGroup_formation p).quotientClosed hsource K hKclosed
  let π : sourceData.carrier →ₜ* Q :=
    { toMonoidHom := QuotientGroup.mk' K
      continuous_toFun := QuotientGroup.continuous_mk }
  let P' : FiniteProPPresentation p d (r + N) sourceData Q :=
    { basisCard := P.basisCard
      relator := rel
      isPresentation := ⟨P.isPresentation.freeSource, htarget, π,
        QuotientGroup.mk'_surjective K, by
          change (QuotientGroup.mk' K).ker = _
          rw [QuotientGroup.ker_mk', hrange, hN]⟩ }
  have hdepth : ∀ i, P'.RelatorZassenhausDepthAtLeast (depth i) i := by
    intro i
    refine Fin.addCases ?_ ?_ i
    · intro j
      simpa [P', depth, rel, RelatorZassenhausDepthAtLeast] using hν₀ j
    · intro j
      simpa [P', depth, rel, RelatorZassenhausDepthAtLeast] using hν j
  have hpos := P'.finite_gsPolynomial_pos depth hdepth ht0 ht1
  have hsum : (∑ i : Fin (r + N), t ^ depth i) =
      (∑ i : Fin r, t ^ ν₀ i) + (∑ i : Fin N, t ^ ν i) := by
    rw [Fin.sum_univ_add]
    simp [depth]
  rw [hsum, ← add_assoc] at hpos
  exact (not_lt_of_ge (hbudget N)) hpos

end FiniteProPPresentation

end

end ClassFieldTower.ProP
