import ClassFieldTheory.GlobalClassFieldTheory.Reciprocity.RationalCyclotomicPrincipalProduct
import ClassFieldTheory.AlgebraicNumberTheory.Idele.Extension.InfiniteOnePlaceBaseNorm
import Mathlib.NumberTheory.NumberField.CMField
import Mathlib.RingTheory.RootsOfUnity.Complex

set_option autoImplicit false

/-!
# The rational cyclotomic complexification

This module realizes the quadratic complexification as the fourth-root
cyclotomic field and proves the rational principal-idele Artin formula.
-/

open scoped BigOperators Classical IsMulCommutative NumberField
open NumberField IsDedekindDomain
open IdeleGroup

noncomputable section

namespace GlobalClassFieldTheory
namespace Reciprocity

/-- The rational prime used to realize the quadratic complexification
as the fourth-root cyclotomic field. -/
def rationalComplexificationPrime : Nat.Primes :=
  ⟨2, Nat.prime_two⟩

/-- The cyclotomic level `4` used for the rational complexification. -/
abbrev rationalComplexificationCyclotomicOrder : ℕ+ :=
  ⟨rationalComplexificationPrime.1 ^ 2,
    pow_pos rationalComplexificationPrime.2.pos 2⟩

local instance rationalComplexificationPrimeFact :
    Fact rationalComplexificationPrime.1.Prime :=
  ⟨rationalComplexificationPrime.2⟩

local instance rationalComplexificationPrimeSquareNeZero :
    NeZero (rationalComplexificationPrime.1 ^ 2) :=
  ⟨pow_ne_zero 2 rationalComplexificationPrime.2.ne_zero⟩

/-- The actual rational cyclotomic field generated by fourth roots of
unity, inside the rational cyclotomic closure. -/
abbrev rationalComplexificationCyclotomicField :
    IntermediateField ℚ KummerTheory.rationalCyclotomicField :=
  KummerTheory.rationalCyclotomicLevel
    rationalComplexificationCyclotomicOrder

noncomputable instance
    rationalComplexificationCyclotomicField_isCyclotomicFour :
    IsCyclotomicExtension {4} ℚ
      rationalComplexificationCyclotomicField := by
  change
    IsCyclotomicExtension
      {(rationalComplexificationCyclotomicOrder : ℕ)} ℚ
      rationalComplexificationCyclotomicField
  exact
    KummerTheory.rationalCyclotomicLevel_isCyclotomicExtension
      rationalComplexificationCyclotomicOrder

noncomputable instance
    rationalComplexificationCyclotomicField_isCMField :
    NumberField.IsCMField rationalComplexificationCyclotomicField := by
  apply IsCyclotomicExtension.Rat.isCMField
    rationalComplexificationCyclotomicField
    (S := {4})
  exact
    ⟨4, Set.mem_singleton 4, by norm_num⟩

noncomputable local instance
    rationalComplexificationCyclotomicField_finiteDimensional :
    FiniteDimensional ℚ rationalComplexificationCyclotomicField :=
  rationalCyclotomicPrincipalPrimeLevelFiniteDimensional
    rationalComplexificationCyclotomicOrder

noncomputable local instance
    rationalComplexificationCyclotomicField_numberField :
    NumberField rationalComplexificationCyclotomicField :=
  KummerTheory.rationalCyclotomicLevel_numberField
    rationalComplexificationCyclotomicOrder

noncomputable local instance
    rationalComplexificationCyclotomicField_isAbelianGalois :
    IsAbelianGalois ℚ rationalComplexificationCyclotomicField :=
  rationalCyclotomicPrincipalPrimeLevelIsAbelianGalois
    rationalComplexificationCyclotomicOrder

/-- The complex number `I` is a primitive fourth root of unity. -/
theorem complexI_isPrimitiveRoot_four :
    IsPrimitiveRoot Complex.I 4 := by
  convert Complex.isPrimitiveRoot_exp 4 (by norm_num) using 1
  calc
    Complex.I =
        Complex.exp ((Real.pi : ℂ) / 2 * Complex.I) :=
      Complex.exp_pi_div_two_mul_I.symm
    _ = Complex.exp
        (2 * (Real.pi : ℂ) * Complex.I / (4 : ℂ)) := by
      congr 1
      ring

/-- The concrete fourth-root cyclotomic field inside `ℂ`.

It is defined by adjoining all fourth roots of unity, so it is
independent of a choice between `I` and `-I` and is visibly preserved
by complex conjugation. -/
def complexFourthRootField :
    IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ
    {z : ℂ |
      ∃ n ∈ ({4} : Set ℕ), n ≠ 0 ∧ z ^ n = 1}

noncomputable instance complexFourthRootField_isCyclotomic :
    IsCyclotomicExtension {4} ℚ complexFourthRootField := by
  apply
    IntermediateField.isCyclotomicExtension_adjoin_of_exists_isPrimitiveRoot
      ({4} : Set ℕ) ℚ ℂ
  intro n hn _hn0
  rw [Set.mem_singleton_iff] at hn
  subst n
  exact ⟨Complex.I, complexI_isPrimitiveRoot_four⟩

noncomputable instance complexFourthRootField_finiteDimensional :
    FiniteDimensional ℚ complexFourthRootField :=
  IsCyclotomicExtension.finiteDimensional
    ({4} : Set ℕ) ℚ complexFourthRootField

noncomputable instance complexFourthRootField_numberField :
    NumberField complexFourthRootField :=
  IsCyclotomicExtension.numberField
    ({4} : Set ℕ) ℚ complexFourthRootField

/-- Identification of the abstract rational fourth-root cyclotomic
field used by the rational product formula with its concrete copy in
`ℂ`. -/
noncomputable def rationalComplexificationComplexEquiv :
    rationalComplexificationCyclotomicField ≃ₐ[ℚ]
      complexFourthRootField :=
  IsCyclotomicExtension.algEquiv
    ({4} : Set ℕ) ℚ
    rationalComplexificationCyclotomicField
    complexFourthRootField

/-- The concrete fourth-root field is stable under complex
conjugation. -/
theorem complexFourthRootField_map_complexConjugation :
    complexFourthRootField.map
        (Complex.conjAe.restrictScalars ℚ).toAlgHom =
      complexFourthRootField := by
  rw [complexFourthRootField, IntermediateField.adjoin_map]
  congr 1
  ext z
  constructor
  · rintro ⟨x, ⟨n, hn, hn0, hx⟩, rfl⟩
    refine ⟨n, hn, hn0, ?_⟩
    rw [← map_pow, hx, map_one]
  · intro hz
    refine ⟨star z, ?_, ?_⟩
    rcases hz with ⟨n, hn, hn0, hz⟩
    refine ⟨n, hn, hn0, ?_⟩
    rw [← star_pow, hz, star_one]
    change star (star z) = z
    exact star_star z

/-- The chosen infinite place of the rational complexification is
ramified over the unique real place of `ℚ`. -/
theorem rationalComplexification_chosenInfinitePlace_isRamified :
    (chosenInfinitePlaceAbove
      (L := rationalComplexificationCyclotomicField)
      Rat.infinitePlace).IsRamified ℚ := by
  rw [InfinitePlace.isRamified_iff,
    chosenInfinitePlaceAbove_comap
      (L := rationalComplexificationCyclotomicField)
      Rat.infinitePlace]
  exact
    ⟨IsTotallyComplex.isComplex _, Rat.isReal_infinitePlace⟩

/-- The rational fourth-root cyclotomic field has Galois group of order two. -/
theorem
    rationalComplexification_galoisGroup_card :
    Nat.card
        (rationalComplexificationCyclotomicField ≃ₐ[ℚ]
          rationalComplexificationCyclotomicField) =
      2 := by
  calc
    Nat.card
          (rationalComplexificationCyclotomicField ≃ₐ[ℚ]
            rationalComplexificationCyclotomicField) =
        Module.finrank ℚ rationalComplexificationCyclotomicField :=
      IsGalois.card_aut_eq_finrank
        ℚ rationalComplexificationCyclotomicField
    _ =
        (rationalComplexificationCyclotomicOrder : ℕ).totient := by
      exact
        IsCyclotomicExtension.finrank
          rationalComplexificationCyclotomicField
          (Polynomial.cyclotomic.irreducible_rat (by
            change 0 < 2 ^ 2
            norm_num))
    _ = 2 := by
      change (2 ^ 2).totient = 2
      rw [Nat.totient_prime_pow Nat.prime_two (by norm_num : 0 < 2)]
      norm_num

/-- The real coordinate of the infinite component of a rational principal
idele is the original rational number. -/
theorem
    rationalPrincipalInfiniteComponent_realCoordinate
    (x : ℚˣ) :
    InfinitePlace.Completion.ringEquivRealOfIsReal
        Rat.isReal_infinitePlace
        ((IdeleGroup.infiniteComponent
          Rat.infinitePlace
          (IdeleGroup.principalIdele ℚ x) :
            Rat.infinitePlace.Completionˣ) :
          Rat.infinitePlace.Completion) =
      (x : ℚ) := by
  rw [InfinitePlace.Completion.ringEquivRealOfIsReal_apply]
  rw [IdeleGroup.infiniteComponent_principalIdele]
  rw [InfinitePlace.Completion.extensionEmbeddingOfIsReal_coe]
  simp only [WithAbs.equiv_apply, eq_ratCast]

/-- A rational principal idele with positive numerator has trivial
infinite Artin factor in the rational complexification. -/
theorem
    rationalComplexificationPrincipalInfiniteArtin_eq_one_of_num_pos
    (x : ℚˣ) (hx : 0 < (x : ℚ).num) :
    chosenInfinitePlaceArtinMonoidHom
        (K := ℚ)
        (L := rationalComplexificationCyclotomicField)
        Rat.infinitePlace
        (IdeleGroup.infiniteComponent
          Rat.infinitePlace
          (IdeleGroup.principalIdele ℚ x)) =
      1 := by
  apply
    chosenInfinitePlaceArtinMonoidHom_eq_one_of_real_pos
      (K := ℚ)
      (L := rationalComplexificationCyclotomicField)
      Rat.infinitePlace Rat.isReal_infinitePlace
  rw [rationalPrincipalInfiniteComponent_realCoordinate]
  exact_mod_cast Rat.num_pos.mp hx

/-- A rational principal idele with negative numerator has nontrivial
infinite Artin factor in the rational complexification. -/
theorem
    rationalComplexificationPrincipalInfiniteArtin_ne_one_of_num_neg
    (x : ℚˣ) (hx : (x : ℚ).num < 0) :
    chosenInfinitePlaceArtinMonoidHom
        (K := ℚ)
        (L := rationalComplexificationCyclotomicField)
        Rat.infinitePlace
        (IdeleGroup.infiniteComponent
          Rat.infinitePlace
          (IdeleGroup.principalIdele ℚ x)) ≠
      1 := by
  let E := rationalComplexificationCyclotomicField
  let v := Rat.infinitePlace
  let w := chosenInfinitePlaceAbove (L := E) v
  have hw :
      w.comap (algebraMap ℚ E) = v :=
    chosenInfinitePlaceAbove_comap (L := E) v
  let : w.1.LiesOver v.1 :=
    ⟨congrArg (fun q : InfinitePlace ℚ => q.1) hw⟩
  intro htrivial
  have hnorm :
      IdeleGroup.infiniteComponent v
          (IdeleGroup.principalIdele ℚ x) ∈
        infiniteTensorNormSubgroup
          (K := ℚ) (L := E) v := by
    rw [← chosenInfinitePlaceArtinMonoidHom_ker
      (K := ℚ) (L := E) v]
    exact htrivial
  rw [infiniteTensorNormSubgroup_eq_localNormSubgroup
    (K := ℚ) (L := E) v w hw] at hnorm
  obtain ⟨z, hz⟩ := hnorm
  have hpositive :=
    infinitePlace_normUnits_real_complex_pos
      (K := ℚ) v w hw
      Rat.isReal_infinitePlace
      rationalComplexification_chosenInfinitePlace_isRamified.isComplex
      z
  rw [hz] at hpositive
  rw [rationalPrincipalInfiniteComponent_realCoordinate] at hpositive
  have hxReal : (((x : ℚ) : ℝ) ≤ 0) := by
    exact_mod_cast (Rat.num_neg.mp hx).le
  exact (not_lt_of_ge hxReal) hpositive

/-- The cyclotomic character of the rational fourth-root field. -/
private noncomputable def rationalComplexificationCharacter :
    (rationalComplexificationCyclotomicField ≃ₐ[ℚ]
        rationalComplexificationCyclotomicField) ≃*
      (ZMod (rationalComplexificationPrime.1 ^ 2))ˣ :=
  IsCyclotomicExtension.Rat.galEquivZMod
    (rationalComplexificationPrime.1 ^ 2)
    rationalComplexificationCyclotomicField
    (hK :=
      KummerTheory.rationalCyclotomicLevel_isCyclotomicExtension
        rationalComplexificationCyclotomicOrder)

private theorem rationalComplexificationCharacter_apply
    (σ : rationalComplexificationCyclotomicField ≃ₐ[ℚ]
      rationalComplexificationCyclotomicField) :
    rationalComplexificationCharacter σ =
      IsCyclotomicExtension.Rat.galEquivZMod
        (rationalComplexificationPrime.1 ^ 2)
        rationalComplexificationCyclotomicField
        (hK :=
          KummerTheory.rationalCyclotomicLevel_isCyclotomicExtension
            rationalComplexificationCyclotomicOrder) σ :=
  rfl

/-- The finite-place Artin product of a rational principal idele in
the fourth-root character is its rational sign unit. -/
private theorem rationalComplexificationFiniteArtin_character
    (x : ℚˣ) :
    rationalComplexificationCharacter
        (∏ᶠ v : HeightOneSpectrum (𝓞 ℚ),
          chosenFinitePlaceArtinMonoidHom
            (K := ℚ)
            (L := rationalComplexificationCyclotomicField)
            v
            (IdeleGroup.finiteComponent v
              (IdeleGroup.principalIdele ℚ x))) =
      Units.map (PadicInt.toZModPow 2).toMonoidHom
        (rationalSignPadicUnit x rationalComplexificationPrime) := by
  have hmap :=
    MonoidHom.map_finprod
      rationalComplexificationCharacter.toMonoidHom
      (finitePlaceArtinFactors_hasFiniteMulSupport
        (K := ℚ)
        (L := rationalComplexificationCyclotomicField)
        (IdeleGroup.principalIdele ℚ x))
  calc
    rationalComplexificationCharacter
          (∏ᶠ v : HeightOneSpectrum (𝓞 ℚ),
            chosenFinitePlaceArtinMonoidHom
              (K := ℚ)
              (L := rationalComplexificationCyclotomicField)
              v
              (IdeleGroup.finiteComponent v
                (IdeleGroup.principalIdele ℚ x))) =
        ∏ᶠ v : HeightOneSpectrum (𝓞 ℚ),
          rationalComplexificationCharacter
            (chosenFinitePlaceArtinMonoidHom
              (K := ℚ)
              (L := rationalComplexificationCyclotomicField)
              v
              (IdeleGroup.finiteComponent v
                (IdeleGroup.principalIdele ℚ x))) :=
      hmap
    _ = _ := by
      rw [← rationalCyclotomicPrincipalFinitePlaceProduct_eq_sign
        rationalComplexificationPrime 2 x]
      apply finprod_congr
      intro v
      rw [rationalComplexificationCharacter_apply]

/-- A group of order two has a unique nonidentity automorphism. -/
private theorem rationalComplexification_existsUnique_nontrivial :
    ∃! σ :
      rationalComplexificationCyclotomicField ≃ₐ[ℚ]
        rationalComplexificationCyclotomicField,
      σ ≠ 1 := by
  rw [← Nat.card_eq_two_iff' (1 :
    rationalComplexificationCyclotomicField ≃ₐ[ℚ]
      rationalComplexificationCyclotomicField)]
  exact rationalComplexification_galoisGroup_card

private theorem rationalComplexification_signCharacter_ne_one_of_num_neg
    (x : ℚˣ) (hx : (x : ℚ).num < 0) :
    Units.map (PadicInt.toZModPow 2).toMonoidHom
        (rationalSignPadicUnit x rationalComplexificationPrime) ≠
      1 := by
  intro h
  have hval := congrArg Units.val h
  rw [rationalSignPadicUnit_toZModPow_val] at hval
  rw [Int.sign_eq_neg_one_of_neg hx] at hval
  norm_num [rationalComplexificationPrime] at hval
  exact (by decide : (-1 : ZMod (2 ^ 2)) ≠ 1) hval

private theorem rationalComplexification_signCharacter_eq_one_of_num_pos
    (x : ℚˣ) (hx : 0 < (x : ℚ).num) :
    Units.map (PadicInt.toZModPow 2).toMonoidHom
        (rationalSignPadicUnit x rationalComplexificationPrime) =
      1 := by
  apply Units.ext
  rw [rationalSignPadicUnit_toZModPow_val]
  rw [Int.sign_eq_one_of_pos hx]
  norm_num

/-- The chosen global Artin product for the actual rational
complexification is trivial on every rational principal idele. -/
@[simp]
theorem rationalComplexificationGlobalArtin_principalIdele
    (x : ℚˣ) :
    globalArtinMonoidHom
        (K := ℚ)
        (L := rationalComplexificationCyclotomicField)
        (IdeleGroup.principalIdele ℚ x) =
      1 := by
  rw [globalArtinMonoidHom_apply, Fintype.prod_unique]
  let u :=
    IdeleGroup.infiniteComponent
      Rat.infinitePlace
      (IdeleGroup.principalIdele ℚ x)
  let infiniteFactor :=
    chosenInfinitePlaceArtinMonoidHom
      (K := ℚ)
      (L := rationalComplexificationCyclotomicField)
      Rat.infinitePlace u
  let finiteFactor :=
    ∏ᶠ v : HeightOneSpectrum (𝓞 ℚ),
      chosenFinitePlaceArtinMonoidHom
        (K := ℚ)
        (L := rationalComplexificationCyclotomicField)
        v
        (IdeleGroup.finiteComponent v
          (IdeleGroup.principalIdele ℚ x))
  change infiniteFactor * finiteFactor = 1
  let character :=
    rationalComplexificationCharacter
  have hfiniteCharacter :
      character finiteFactor =
        Units.map (PadicInt.toZModPow 2).toMonoidHom
          (rationalSignPadicUnit x rationalComplexificationPrime) := by
    simpa only [character, finiteFactor] using
      rationalComplexificationFiniteArtin_character x
  have hnum : (x : ℚ).num ≠ 0 :=
    Rat.num_ne_zero.mpr x.ne_zero
  have hunique :=
    rationalComplexification_existsUnique_nontrivial
  rcases lt_or_gt_of_ne hnum with hnegative | hpositive
  · have hinfinite : infiniteFactor ≠ 1 := by
      simpa only [infiniteFactor, u] using
        rationalComplexificationPrincipalInfiniteArtin_ne_one_of_num_neg
          x hnegative
    have hsign :
        Units.map (PadicInt.toZModPow 2).toMonoidHom
            (rationalSignPadicUnit x rationalComplexificationPrime) ≠
          1 :=
      rationalComplexification_signCharacter_ne_one_of_num_neg
        x hnegative
    have hfinite : finiteFactor ≠ 1 := by
      intro h
      apply hsign
      rw [← hfiniteCharacter, h, map_one]
    have heq : infiniteFactor = finiteFactor :=
      hunique.unique hinfinite hfinite
    have hinvNe : finiteFactor⁻¹ ≠ 1 :=
      inv_ne_one.mpr hfinite
    have hinvEq : finiteFactor⁻¹ = finiteFactor :=
      hunique.unique hinvNe hfinite
    calc
      infiniteFactor * finiteFactor =
          finiteFactor⁻¹ * finiteFactor := by
        rw [heq, hinvEq]
      _ = 1 := inv_mul_cancel finiteFactor
  · have hinfinite : infiniteFactor = 1 := by
      simpa only [infiniteFactor, u] using
        rationalComplexificationPrincipalInfiniteArtin_eq_one_of_num_pos
          x hpositive
    have hsign :
        Units.map (PadicInt.toZModPow 2).toMonoidHom
            (rationalSignPadicUnit x rationalComplexificationPrime) =
          1 :=
      rationalComplexification_signCharacter_eq_one_of_num_pos
        x hpositive
    have hfinite : finiteFactor = 1 := by
      apply character.injective
      rw [hfiniteCharacter, hsign, map_one]
    rw [hinfinite, hfinite, mul_one]

end Reciprocity
end GlobalClassFieldTheory
