import Mathlib.RingTheory.AdicCompletion.Functoriality

set_option autoImplicit false

namespace ValuationTheory

/-!
# Adic completeness and positive powers of an ideal

This file contains small generic source lemmas used to pass from completeness
for a positive power `I ^ n` back to completeness for `I`.
-/

noncomputable section

namespace DiscreteValuationField

variable {R : Type*} [CommRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]
variable {N : Type*} [AddCommGroup N] [Module R N]

/-- Adic completeness is preserved by a linear equivalence of modules over the
same base ring and with respect to the same ideal. -/
theorem isAdicComplete_of_linearEquiv
    (I : Ideal R) (e : M ≃ₗ[R] N) [IsAdicComplete I M] :
    IsAdicComplete I N := by
  refine AdicCompletion.of_bijective_iff.mp ?_
  constructor
  · intro x y hxy
    have hpre :
        e.symm x = e.symm y := by
      apply (AdicCompletion.of_bijective I M).1
      apply (AdicCompletion.congr I e).injective
      simpa [AdicCompletion.congr_apply, AdicCompletion.map_of] using hxy
    exact e.symm.injective hpre
  · intro y
    obtain ⟨m, hm⟩ :=
      (AdicCompletion.of_bijective I M).2
        ((AdicCompletion.congr I e).symm y)
    refine ⟨e m, ?_⟩
    calc
      AdicCompletion.of I N (e m) =
          AdicCompletion.congr I e (AdicCompletion.of I M m) := by
        simp [AdicCompletion.congr_apply, AdicCompletion.map_of]
      _ = AdicCompletion.congr I e
          ((AdicCompletion.congr I e).symm y) := by
        rw [hm]
      _ = y := (AdicCompletion.congr I e).apply_symm_apply y

/-- Membership in a power of the extended ideal is the same as membership in
the corresponding base-adic submodule after restricting scalars. -/
theorem mem_map_algebraMap_pow_iff_mem_pow_smul_top
    {S : Type*} [CommRing S] [Algebra R S] (I : Ideal R)
    (n : ℕ) {x : S} :
    x ∈ (I.map (algebraMap R S)) ^ n ↔
      x ∈ I ^ n • (⊤ : Submodule R S) := by
  rw [Ideal.smul_top_eq_map, Ideal.map_pow]
  rfl

/-- The same scalar-restriction comparison as a submodule-membership statement. -/
theorem mem_map_algebraMap_pow_smul_top_iff
    {S : Type*} [CommRing S] [Algebra R S] (I : Ideal R)
    (n : ℕ) {x : S} :
    x ∈ ((I.map (algebraMap R S)) ^ n • ⊤ : Submodule S S) ↔
      x ∈ I ^ n • (⊤ : Submodule R S) := by
  simpa only [smul_eq_mul, Ideal.mul_top] using
    (mem_map_algebraMap_pow_iff_mem_pow_smul_top
      (R := R) (S := S) I n (x := x))

/-- Congruence modulo powers of an extended ideal is unchanged after
restricting scalars to the base ring. -/
theorem smodEq_map_algebraMap_pow_smul_top_iff
    {S : Type*} [CommRing S] [Algebra R S] (I : Ideal R)
    {x y : S} (n : ℕ) :
    x ≡ y [SMOD ((I.map (algebraMap R S)) ^ n • ⊤ : Submodule S S)] ↔
      x ≡ y [SMOD (I ^ n • ⊤ : Submodule R S)] := by
  rw [SModEq.sub_mem, SModEq.sub_mem]
  exact mem_map_algebraMap_pow_smul_top_iff (I := I) n

/-- Restricting scalars along an algebra map does not change precompleteness
for the ideal generated by the base ideal. -/
theorem isPrecomplete_map_algebraMap_iff
    {S : Type*} [CommRing S] [Algebra R S] (I : Ideal R) :
    IsPrecomplete (I.map (algebraMap R S)) S ↔ IsPrecomplete I S := by
  constructor
  · intro h
    refine ⟨fun f hf => ?_⟩
    have hfS :
        ∀ {m n : ℕ}, m ≤ n →
          f m ≡ f n
            [SMOD ((I.map (algebraMap R S)) ^ m • ⊤ : Submodule S S)] := by
      intro m n hmn
      exact (smodEq_map_algebraMap_pow_smul_top_iff (I := I) m).mpr (hf hmn)
    obtain ⟨L, hL⟩ := IsPrecomplete.prec h hfS
    refine ⟨L, fun n => ?_⟩
    exact (smodEq_map_algebraMap_pow_smul_top_iff (I := I) n).mp (hL n)
  · intro h
    refine ⟨fun f hf => ?_⟩
    have hfR :
        ∀ {m n : ℕ}, m ≤ n →
          f m ≡ f n [SMOD (I ^ m • ⊤ : Submodule R S)] := by
      intro m n hmn
      exact (smodEq_map_algebraMap_pow_smul_top_iff (I := I) m).mp (hf hmn)
    obtain ⟨L, hL⟩ := IsPrecomplete.prec h hfR
    refine ⟨L, fun n => ?_⟩
    exact (smodEq_map_algebraMap_pow_smul_top_iff (I := I) n).mpr (hL n)

/-- Restricting scalars along an algebra map does not change adic
completeness for the ideal generated by the base ideal. -/
theorem isAdicComplete_map_algebraMap_iff
    {S : Type*} [CommRing S] [Algebra R S] (I : Ideal R) :
    IsAdicComplete (I.map (algebraMap R S)) S ↔ IsAdicComplete I S := by
  constructor
  · intro h
    exact
      { toIsHausdorff := IsHausdorff.map_algebraMap_iff.mp h.toIsHausdorff
        toIsPrecomplete := (isPrecomplete_map_algebraMap_iff
          (R := R) (S := S) I).mp h.toIsPrecomplete }
  · intro h
    exact
      { toIsHausdorff := IsHausdorff.map_algebraMap_iff.mpr h.toIsHausdorff
        toIsPrecomplete := (isPrecomplete_map_algebraMap_iff
          (R := R) (S := S) I).mpr h.toIsPrecomplete }

/-- Adic completeness is preserved by transporting the ring and ideal across a
ring equivalence. -/
theorem isAdicComplete_map_ringEquiv
    {S : Type*} [CommRing S] (I : Ideal R) (e : R ≃+* S)
    [IsAdicComplete I R] :
    IsAdicComplete (I.map (e : R →+* S)) S := by
  let : Algebra R S := (e : R →+* S).toAlgebra
  let lin : R ≃ₗ[R] S :=
    { toFun := e
      invFun := e.symm
      left_inv := fun x => e.symm_apply_apply x
      right_inv := fun x => e.apply_symm_apply x
      map_add' := fun x y => e.map_add x y
      map_smul' := fun a x => by
        change e (a * x) = e a * e x
        exact e.map_mul a x }
  have hS : IsAdicComplete I S :=
    isAdicComplete_of_linearEquiv (I := I) lin
  simpa only [RingHom.algebraMap_toAlgebra] using
    (isAdicComplete_map_algebraMap_iff (R := R) (S := S) I).2 hS

/-- If a module is Hausdorff for an ideal, then it is Hausdorff for every
positive power of that ideal. -/
theorem isHausdorff_pow_of_isHausdorff
    (I : Ideal R) {n : ℕ} (hn : 0 < n)
    [IsHausdorff I M] :
    IsHausdorff (I ^ n) M := by
  refine ⟨fun x hx => IsHausdorff.haus
    (inferInstance : IsHausdorff I M) x ?_⟩
  intro k
  have hle : k ≤ n * k := by
    simpa using Nat.mul_le_mul_right k (Nat.succ_le_of_lt hn)
  apply SModEq.mono (Submodule.pow_smul_top_le I M hle)
  simpa [pow_mul] using hx k

/-- If a module is precomplete for an ideal, then it is precomplete for every
positive power of that ideal. -/
theorem isPrecomplete_pow_of_isPrecomplete
    (I : Ideal R) {n : ℕ} (hn : 0 < n)
    [IsPrecomplete I M] :
    IsPrecomplete (I ^ n) M := by
  refine ⟨fun f hf => ?_⟩
  have hfI :
      ∀ {m k : ℕ}, m ≤ k →
        f m ≡ f k [SMOD (I ^ m • ⊤ : Submodule R M)] := by
    intro m k hmk
    have hle : m ≤ n * m := by
      simpa using Nat.mul_le_mul_right m (Nat.succ_le_of_lt hn)
    apply SModEq.mono (Submodule.pow_smul_top_le I M hle)
    simpa [pow_mul] using hf hmk
  obtain ⟨L, hL⟩ :=
    IsPrecomplete.prec (I := I) (M := M)
      (inferInstance : IsPrecomplete I M) hfI
  refine ⟨L, fun m => ?_⟩
  have hmle : m ≤ n * m := by
    simpa using Nat.mul_le_mul_right m (Nat.succ_le_of_lt hn)
  have hstep :
      f m ≡ f (n * m)
        [SMOD ((I ^ n) ^ m • ⊤ : Submodule R M)] :=
    hf hmle
  have hlimit :
      f (n * m) ≡ L
        [SMOD ((I ^ n) ^ m • ⊤ : Submodule R M)] := by
    simpa [pow_mul] using hL (n * m)
  exact hstep.trans hlimit

/-- If a module is complete for an ideal, then it is complete for every
positive power of that ideal. -/
theorem isAdicComplete_pow_of_isAdicComplete
    (I : Ideal R) {n : ℕ} (hn : 0 < n)
    [IsAdicComplete I M] :
    IsAdicComplete (I ^ n) M where
  toIsHausdorff := isHausdorff_pow_of_isHausdorff (M := M) I hn
  toIsPrecomplete := isPrecomplete_pow_of_isPrecomplete (M := M) I hn

/-- If a module is Hausdorff for a positive power of an ideal, then it is
Hausdorff for the ideal itself. -/
theorem isHausdorff_of_isHausdorff_pow
    (I : Ideal R) {n : ℕ} (_hn : 0 < n)
    [IsHausdorff (I ^ n) M] :
    IsHausdorff I M := by
  refine ⟨fun x hx => IsHausdorff.haus
    (inferInstance : IsHausdorff (I ^ n) M) x ?_⟩
  intro k
  simpa [pow_mul] using hx (n * k)

/-- If a module is precomplete for a positive power of an ideal, then it is
precomplete for the ideal itself. -/
theorem isPrecomplete_of_isPrecomplete_pow
    (I : Ideal R) {n : ℕ} (hn : 0 < n)
    [IsPrecomplete (I ^ n) M] :
    IsPrecomplete I M := by
  refine ⟨fun f hf => ?_⟩
  have hsub :
      ∀ {a b : ℕ}, a ≤ b →
        f (n * a) ≡ f (n * b)
          [SMOD ((I ^ n) ^ a • ⊤ : Submodule R M)] := by
    intro a b hab
    have hle : n * a ≤ n * b := Nat.mul_le_mul_left n hab
    simpa [pow_mul] using hf hle
  obtain ⟨L, hL⟩ :=
    IsPrecomplete.prec (I := I ^ n) (M := M)
      (inferInstance : IsPrecomplete (I ^ n) M)
      (f := fun k => f (n * k)) hsub
  refine ⟨L, fun m => ?_⟩
  have hm : m ≤ n * m := by
    simpa using Nat.mul_le_mul_right m (Nat.succ_le_of_lt hn)
  have hfm : f m ≡ f (n * m)
      [SMOD (I ^ m • ⊤ : Submodule R M)] :=
    hf hm
  have htail : f (n * m) ≡ L
      [SMOD (I ^ m • ⊤ : Submodule R M)] := by
    apply SModEq.mono (Submodule.pow_smul_top_le I M hm)
    simpa [pow_mul] using hL m
  exact hfm.trans htail

/-- If a module is complete for a positive power of an ideal, then it is
complete for the ideal itself. -/
theorem isAdicComplete_of_isAdicComplete_pow
    (I : Ideal R) {n : ℕ} (hn : 0 < n)
    [IsAdicComplete (I ^ n) M] :
    IsAdicComplete I M where
  toIsHausdorff := isHausdorff_of_isHausdorff_pow (M := M) I hn
  toIsPrecomplete := isPrecomplete_of_isPrecomplete_pow (M := M) I hn

/-- Adic completeness is unchanged when two ideals define cofinal power
filtrations.  The hypotheses `I ≤ J` and `J ^ n ≤ I`, with `n > 0`,
are the asymmetric form convenient for finite integral extensions: the
extended base ideal lies in the maximal ideal upstairs, while a positive
power of that maximal ideal lies back in the extended ideal. -/
theorem isAdicComplete_of_le_of_pow_le
    (I J : Ideal R) {n : ℕ} (hn : 0 < n)
    (hIJ : I ≤ J) (hJI : J ^ n ≤ I)
    [IsAdicComplete I M] :
    IsAdicComplete J M := by
  have hpow : ∀ k : ℕ, J ^ (n * k) • (⊤ : Submodule R M) ≤
      I ^ k • (⊤ : Submodule R M) := by
    intro k
    simpa only [pow_mul] using
      Submodule.smul_mono (Ideal.pow_right_mono hJI k) le_rfl
  refine
    { toIsHausdorff := ?_
      toIsPrecomplete := ?_ }
  · refine ⟨fun x hx ↦ IsHausdorff.haus
      (inferInstance : IsHausdorff I M) x (fun k ↦ ?_)⟩
    exact SModEq.mono (hpow k) (hx (n * k))
  · refine ⟨fun f hf ↦ ?_⟩
    have hsubsequence :
        ∀ {a b : ℕ}, a ≤ b →
          f (n * a) ≡ f (n * b)
            [SMOD (I ^ a • ⊤ : Submodule R M)] := by
      intro a b hab
      exact SModEq.mono (hpow a) (hf (Nat.mul_le_mul_left n hab))
    obtain ⟨L, hL⟩ := IsPrecomplete.prec
      (inferInstance : IsPrecomplete I M) hsubsequence
    refine ⟨L, fun k ↦ ?_⟩
    have hk : k ≤ n * k := by
      simpa [Nat.mul_comm] using
        Nat.mul_le_mul_right k (Nat.succ_le_of_lt hn)
    have htail : f (n * k) ≡ L
        [SMOD (J ^ k • ⊤ : Submodule R M)] :=
      SModEq.mono
        (Submodule.smul_mono (Ideal.pow_right_mono hIJ k) le_rfl)
        (hL k)
    exact (hf hk).trans htail

end DiscreteValuationField

end

end ValuationTheory
