import ValuedFieldTheory.Valuation.DiscreteValuationField.FiniteExtension.Core
import Mathlib.RingTheory.Valuation.Discrete.IsDiscreteValuationRing

set_option autoImplicit false

namespace ValuationTheory

/-!
# Finite integral closures over complete DVFs

This file provides record-free theorems for the integral closure
of a complete-DVF valuation ring in a finite separable field extension.
-/

noncomputable section

universe u v w

namespace DiscreteValuationField
namespace ValuedExtension

open DiscreteValuationField.Valuation

variable {K : Type u} {L : Type w} [Field K] [Field L]
variable [Algebra K L] [FiniteDimensional K L]

/- The algebra map from the base valuation ring into the integral
closure is injective. -/
omit [FiniteDimensional K L] in
/-- The algebra map into a finite integral closure is injective. -/
theorem CanonicalIntegralClosure.algebraMap_injective
    (base : CompleteDVF.{u, v} K) :
    Function.Injective
      (algebraMap base.valuationSubring
        (integralClosure base.valuationSubring L)) := by
  intro x y hxy
  apply Subtype.ext
  apply FaithfulSMul.algebraMap_injective K L
  exact
    congrArg
      (fun z : integralClosure base.valuationSubring L => (z : L)) hxy

/- The integral closure is faithful as a module over the base valuation
ring. -/
omit [FiniteDimensional K L] in
/-- Scalar multiplication on a finite integral closure is faithful. -/
theorem CanonicalIntegralClosure.faithfulSMul
    (base : CompleteDVF.{u, v} K) :
    FaithfulSMul base.valuationSubring
      (integralClosure base.valuationSubring L) :=
  (faithfulSMul_iff_algebraMap_injective base.valuationSubring
    (integralClosure base.valuationSubring L)).mpr
    (CanonicalIntegralClosure.algebraMap_injective (K := K) (L := L) base)

/-- In a finite separable extension of a complete DVF, the actual integral
closure is complete for the ideal generated by the base maximal ideal. -/
theorem integralClosure_base_maximal_map_isAdicComplete_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    IsAdicComplete
      (base.maximalIdeal.map
        (algebraMap base.valuationSubring
          (integralClosure base.valuationSubring L)))
      (integralClosure base.valuationSubring L) := by
  let : IsNoetherianRing base.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) base
  let : IsFractionRing base.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsIntegrallyClosed base.valuationSubring :=
    base_valuationSubring_isIntegrallyClosed (K := K) base
  let : Module.Finite base.valuationSubring
      (integralClosure base.valuationSubring L) :=
    IsIntegralClosure.finite base.valuationSubring K L
      (integralClosure base.valuationSubring L)
  have : IsAdicComplete base.maximalIdeal base.valuationSubring :=
    base.isAdicComplete
  have hcomplete :
      IsAdicComplete base.maximalIdeal
        (integralClosure base.valuationSubring L) :=
    ValuationTheory.DiscreteValuationField.isAdicComplete_of_moduleFinite
      (I := base.maximalIdeal)
  exact
    (isAdicComplete_map_algebraMap_iff
      (I := base.maximalIdeal)
      (S := integralClosure base.valuationSubring L)).mpr hcomplete

/-- In a finite separable extension of a complete DVF, the actual integral
closure of the base valuation ring is Henselian along the ideal generated by
the base maximal ideal.

This is independent of any pre-existing `Extension` record.  It is the
source-producing input used before canonical ramification and residue
invariants have been packaged. -/
theorem integralClosure_henselianRing_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    HenselianRing (integralClosure base.valuationSubring L)
      (base.maximalIdeal.map
        (algebraMap base.valuationSubring
          (integralClosure base.valuationSubring L))) := by
  let :
      IsAdicComplete
        (base.maximalIdeal.map
          (algebraMap base.valuationSubring
            (integralClosure base.valuationSubring L)))
        (integralClosure base.valuationSubring L) :=
    integralClosure_base_maximal_map_isAdicComplete_of_finite_separable
      (K := K) (L := L) base
  infer_instance

/-- In a finite separable extension of a complete DVF, the residue fiber of the
actual integral closure over the base maximal ideal has at most one prime.

The proof combines finite Artinian residue fibers with Henselian idempotent
lifting from `integralClosure_henselianRing_of_finite_separable`. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    Subsingleton
      (PrimeSpectrum
        (base.maximalIdeal.Fiber (integralClosure base.valuationSubring L))) := by
  let B := integralClosure base.valuationSubring L
  let : IsNoetherianRing base.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) base
  let : IsFractionRing base.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsIntegrallyClosed base.valuationSubring :=
    base_valuationSubring_isIntegrallyClosed (K := K) base
  let : Module.Finite base.valuationSubring B :=
    IsIntegralClosure.finite base.valuationSubring K L B
  let : Algebra.QuasiFinite base.valuationSubring B := by
    infer_instance
  let : IsArtinianRing (base.maximalIdeal.Fiber B) := by
    infer_instance
  refine primeSpectrum_subsingleton_of_isArtinianRing_of_idempotents_trivial ?_
  intro e he
  let : HenselianRing B
      (base.maximalIdeal.map (algebraMap base.valuationSubring B)) :=
    integralClosure_henselianRing_of_finite_separable (K := K) (L := L) base
  let : HenselianRing B
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          B →ₐ[base.valuationSubring] base.maximalIdeal.Fiber B) :
          B →+* base.maximalIdeal.Fiber B)) := by
    rw [maximalIdeal_fiber_includeRight_ker_eq_maximalIdeal_map
      (R := base.valuationSubring) (S := B)]
    infer_instance
  let φ : B →+* base.maximalIdeal.Fiber B :=
    (Algebra.TensorProduct.includeRight :
      B →ₐ[base.valuationSubring] base.maximalIdeal.Fiber B)
  have hsurj : Function.Surjective φ := by
    simpa [φ] using
      (maximalIdeal_fiber_includeRight_surjective
        (R := base.valuationSubring) (S := B))
  rcases exists_idempotent_lift_of_surjective_henselianRing_ker
      φ hsurj e he with
    ⟨b, hbidem, hbmap⟩
  let : IsDomain B := by
    change IsDomain (integralClosure base.valuationSubring L)
    infer_instance
  rcases IsIdempotentElem.iff_eq_zero_or_one.mp hbidem with rfl | rfl
  · left
    rw [← hbmap]
    simp [φ]
  · right
    rw [← hbmap]
    exact (Algebra.TensorProduct.includeRight :
      B →ₐ[base.valuationSubring] base.maximalIdeal.Fiber B).map_one

/-- In a finite separable extension of a complete DVF, the actual integral
closure of the base valuation ring is local.

This is the record-free localness form of the Henselian finite-extension
frontier.  It uses the residue-fiber singleton theorem above and integral
lies-over, without assuming a chosen target
valuation ring. -/
theorem integralClosure_isLocalRing_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    IsLocalRing (integralClosure base.valuationSubring L) := by
  let B := integralClosure base.valuationSubring L
  let : Algebra.IsIntegral base.valuationSubring B := by
    change Algebra.IsIntegral base.valuationSubring
      (integralClosure base.valuationSubring L)
    infer_instance
  let : FaithfulSMul base.valuationSubring B :=
    CanonicalIntegralClosure.faithfulSMul (K := K) (L := L) base
  have hNonempty :
      Nonempty (Ideal.primesOver base.maximalIdeal B) := by
    rcases Ideal.exists_maximal_ideal_liesOver_of_isIntegral
        (S := B) base.maximalIdeal with
      ⟨P, hPmax, hPover⟩
    exact ⟨⟨P, hPmax.isPrime, hPover⟩⟩
  let : Subsingleton (PrimeSpectrum (base.maximalIdeal.Fiber B)) :=
    integralClosure_base_maximal_fiber_subsingleton_of_finite_separable
      (K := K) (L := L) base
  have hPrimeSub :
      Subsingleton (Ideal.primesOver base.maximalIdeal B) := by
    constructor
    intro P Q
    let e := PrimeSpectrum.primesOverOrderIsoFiber
      base.valuationSubring B base.maximalIdeal
    exact e.injective (Subsingleton.elim (e P) (e Q))
  rcases hNonempty with ⟨P⟩
  have hPrimesSingleton :
      Ideal.primesOver base.maximalIdeal B = {P.1} := by
    let : Subsingleton (Ideal.primesOver base.maximalIdeal B) := hPrimeSub
    refine Set.eq_singleton_iff_unique_mem.mpr ⟨P.2, ?_⟩
    intro Q hQ
    exact congrArg Subtype.val
      (Subsingleton.elim
        (⟨Q, hQ⟩ : Ideal.primesOver base.maximalIdeal B) P)
  have hPmem : P.1 ∈ Ideal.primesOver base.maximalIdeal B := P.2
  let : Nonempty (MaximalSpectrum B) :=
    ⟨⟨P.1, Ideal.isMaximal_of_mem_primesOver hPmem⟩⟩
  have hMaxSub : Subsingleton (MaximalSpectrum B) := by
    constructor
    intro M N
    apply MaximalSpectrum.ext
    have hMcomap :
        (M.asIdeal.comap (algebraMap base.valuationSubring B)) =
          base.maximalIdeal :=
      IsLocalRing.eq_maximalIdeal
        (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
          (R := base.valuationSubring) (S := B) M.asIdeal)
    have hNcomap :
        (N.asIdeal.comap (algebraMap base.valuationSubring B)) =
          base.maximalIdeal :=
      IsLocalRing.eq_maximalIdeal
        (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
          (R := base.valuationSubring) (S := B) N.asIdeal)
    have hMmem :
        M.asIdeal ∈ Ideal.primesOver base.maximalIdeal B :=
      ⟨M.isMaximal.isPrime, ⟨hMcomap.symm⟩⟩
    have hNmem :
        N.asIdeal ∈ Ideal.primesOver base.maximalIdeal B :=
      ⟨N.isMaximal.isPrime, ⟨hNcomap.symm⟩⟩
    have hMeq : M.asIdeal = P.1 := by
      simpa [hPrimesSingleton] using hMmem
    have hNeq : N.asIdeal = P.1 := by
      simpa [hPrimesSingleton] using hNmem
    exact hMeq.trans hNeq.symm
  exact IsLocalRing.of_singleton_maximalSpectrum

/-- The maximal ideal of the integral closure, using the finite
separable localness theorem above. -/
noncomputable def CanonicalIntegralClosure.maximalIdeal
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    Ideal (integralClosure base.valuationSubring L) :=
  letI : IsLocalRing (integralClosure base.valuationSubring L) :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  IsLocalRing.maximalIdeal (integralClosure base.valuationSubring L)

/-- In the actual integral closure, the ideal generated by the base maximal
ideal is contained in the upstairs maximal ideal. -/
theorem integralClosure_base_maximal_map_le_maximalIdeal_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    base.maximalIdeal.map
        (algebraMap base.valuationSubring
          (integralClosure base.valuationSubring L)) ≤
      CanonicalIntegralClosure.maximalIdeal (K := K) (L := L) base := by
  let B := integralClosure base.valuationSubring L
  let : IsLocalRing B :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  change
    base.maximalIdeal.map (algebraMap base.valuationSubring B) ≤
      IsLocalRing.maximalIdeal B
  let : Algebra.IsIntegral base.valuationSubring B := by
    change Algebra.IsIntegral base.valuationSubring
      (integralClosure base.valuationSubring L)
    infer_instance
  have hlocal : IsLocalHom (algebraMap base.valuationSubring B) :=
    (algebraMap_isIntegral_iff.mpr
      (show Algebra.IsIntegral base.valuationSubring B from inferInstance)
    ).isLocalHom
      (CanonicalIntegralClosure.algebraMap_injective (K := K) (L := L) base)
  exact
    ((IsLocalRing.local_hom_TFAE
      (algebraMap base.valuationSubring B)).out 0 2).mp hlocal

/- In the actual integral closure, the ideal generated by the base maximal
ideal is nonzero. -/
omit [FiniteDimensional K L] in
/-- In a finite separable extension, the image of the base maximal ideal is nonzero. -/
theorem integralClosure_base_maximal_map_ne_bot_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    base.maximalIdeal.map
      (algebraMap base.valuationSubring
        (integralClosure base.valuationSubring L)) ≠ ⊥ := by
  intro hbot
  exact base.maximalIdeal_ne_bot
    ((Ideal.map_eq_bot_iff_of_injective
      (CanonicalIntegralClosure.algebraMap_injective (K := K) (L := L) base)).1
      hbot)

/- In a finite separable extension of a complete DVF, the actual integral
closure of the base valuation ring is not a field. -/
omit [FiniteDimensional K L] in
/-- The integral closure in a nontrivial finite separable extension is not a field. -/
theorem integralClosure_not_isField_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ¬ IsField (integralClosure base.valuationSubring L) := by
  let B := integralClosure base.valuationSubring L
  let : Algebra.IsIntegral base.valuationSubring B := by
    change Algebra.IsIntegral base.valuationSubring
      (integralClosure base.valuationSubring L)
    infer_instance
  let : FaithfulSMul base.valuationSubring B :=
    CanonicalIntegralClosure.faithfulSMul (K := K) (L := L) base
  intro hB
  have hbase : IsField base.valuationSubring :=
    isField_of_isIntegral_of_isField
      (R := base.valuationSubring) (S := B)
      (FaithfulSMul.algebraMap_injective base.valuationSubring B) hB
  exact IsDiscreteValuationRing.not_isField base.valuationSubring hbase

/-- In a finite separable extension of a complete DVF, the actual integral
closure of the base valuation ring is a DVR. -/
theorem integralClosure_isDiscreteValuationRing_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    IsDiscreteValuationRing (integralClosure base.valuationSubring L) := by
  let : IsLocalRing (integralClosure base.valuationSubring L) :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  let : IsFractionRing base.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsDomain (integralClosure base.valuationSubring L) := by
    infer_instance
  let : IsDedekindDomain (integralClosure base.valuationSubring L) := by
    exact integralClosure.isDedekindDomain base.valuationSubring K L
  let : IsNoetherianRing (integralClosure base.valuationSubring L) := by
    exact integralClosure.isNoetherianRing (A := base.valuationSubring) (K := K) L
  have hnot :
      ¬ IsField (integralClosure base.valuationSubring L) :=
    integralClosure_not_isField_of_finite_separable
      (K := K) (L := L) base
  exact
    ((IsDiscreteValuationRing.TFAE
      (integralClosure base.valuationSubring L) hnot).out 2 0).mp
      (show IsDedekindDomain (integralClosure base.valuationSubring L) from
        inferInstance)

/-- In the actual integral closure, the ideal generated by the base maximal
ideal is a power of the upstairs maximal ideal. -/
theorem exists_integralClosure_base_maximal_map_eq_maximalIdeal_pow
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ n : ℕ,
      base.maximalIdeal.map
          (algebraMap base.valuationSubring
            (integralClosure base.valuationSubring L)) =
        CanonicalIntegralClosure.maximalIdeal (K := K) (L := L) base ^ n := by
  let B := integralClosure base.valuationSubring L
  let : IsLocalRing B :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  change
    ∃ n : ℕ,
      base.maximalIdeal.map (algebraMap base.valuationSubring B) =
        IsLocalRing.maximalIdeal B ^ n
  let : IsDomain B := by
    change IsDomain (integralClosure base.valuationSubring L)
    infer_instance
  let : IsDiscreteValuationRing B :=
    integralClosure_isDiscreteValuationRing_of_finite_separable
      (K := K) (L := L) base
  have hI :
      base.maximalIdeal.map
          (algebraMap base.valuationSubring B) ≠ ⊥ :=
    integralClosure_base_maximal_map_ne_bot_of_finite_separable
      (K := K) (L := L) base
  obtain ⟨pi, hpi⟩ := IsDiscreteValuationRing.exists_irreducible B
  obtain ⟨n, hn⟩ :=
    IsDiscreteValuationRing.ideal_eq_span_pow_irreducible hI hpi
  refine ⟨n, ?_⟩
  rw [hn, ← Ideal.span_singleton_pow, ← hpi.maximalIdeal_eq]

/-- In the actual integral closure, the ideal generated by the base maximal
ideal is a positive power of the upstairs maximal ideal. -/
theorem exists_integralClosure_base_maximal_map_eq_maximalIdeal_pow_pos
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ n : ℕ,
      0 < n ∧
        base.maximalIdeal.map
            (algebraMap base.valuationSubring
              (integralClosure base.valuationSubring L)) =
          CanonicalIntegralClosure.maximalIdeal (K := K) (L := L) base ^ n := by
  let B := integralClosure base.valuationSubring L
  let : IsLocalRing B :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  change
    ∃ n : ℕ,
      0 < n ∧
        base.maximalIdeal.map (algebraMap base.valuationSubring B) =
          IsLocalRing.maximalIdeal B ^ n
  obtain ⟨n, hn⟩ :=
    exists_integralClosure_base_maximal_map_eq_maximalIdeal_pow
      (K := K) (L := L) base
  refine ⟨n, ?_, hn⟩
  by_contra hnot
  have hn0 : n = 0 := Nat.eq_zero_of_not_pos hnot
  have htop :
      base.maximalIdeal.map (algebraMap base.valuationSubring B) = ⊤ := by
    simpa [hn0] using hn
  have hle :
      base.maximalIdeal.map (algebraMap base.valuationSubring B) ≤
        IsLocalRing.maximalIdeal B :=
    integralClosure_base_maximal_map_le_maximalIdeal_of_finite_separable
      (K := K) (L := L) base
  have htop_le : (⊤ : Ideal B) ≤ IsLocalRing.maximalIdeal B := by
    simpa [htop] using hle
  exact
    (IsLocalRing.maximalIdeal.isMaximal B).ne_top
      (top_le_iff.mp htop_le)

/-- In a finite separable extension of a complete DVF, the actual integral
closure is complete for its own maximal ideal. -/
theorem integralClosure_maximalIdeal_isAdicComplete_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    IsAdicComplete
      (CanonicalIntegralClosure.maximalIdeal (K := K) (L := L) base)
      (integralClosure base.valuationSubring L) := by
  let B := integralClosure base.valuationSubring L
  let : IsLocalRing B :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  change IsAdicComplete (IsLocalRing.maximalIdeal B) B
  obtain ⟨n, hnpos, hn⟩ :=
    exists_integralClosure_base_maximal_map_eq_maximalIdeal_pow_pos
      (K := K) (L := L) base
  have hmap :
      IsAdicComplete
        (base.maximalIdeal.map (algebraMap base.valuationSubring B)) B :=
    integralClosure_base_maximal_map_isAdicComplete_of_finite_separable
      (K := K) (L := L) base
  let :
      IsAdicComplete ((IsLocalRing.maximalIdeal B) ^ n) B := by
    have hn' :
        base.maximalIdeal.map (algebraMap base.valuationSubring B) =
          IsLocalRing.maximalIdeal B ^ n := by
      simpa [CanonicalIntegralClosure.maximalIdeal] using hn
    simpa [hn'] using hmap
  exact
    isAdicComplete_of_isAdicComplete_pow
      (M := B) (IsLocalRing.maximalIdeal B) hnpos

/-- A packaged rank-one discrete valuation coming from the actual integral
closure, together with its valuation-subring comparison. -/
theorem exists_integralClosure_standard_rankOneDiscrete_valuation
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ ΓL : Type,
      ∃ _ : LinearOrderedCommGroupWithZero ΓL,
        ∃ vL : _root_.Valuation L ΓL,
          ∃ _ : vL.IsRankOneDiscrete,
            ∃ _ : (integralClosure base.valuationSubring L) ≃+*
              vL.valuationSubring,
              True := by
  let B := integralClosure base.valuationSubring L
  let : IsLocalRing B :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  let : IsDomain B := by
    change IsDomain (integralClosure base.valuationSubring L)
    infer_instance
  let : IsDiscreteValuationRing B :=
    integralClosure_isDiscreteValuationRing_of_finite_separable
      (K := K) (L := L) base
  let : IsFractionRing B L := by
    change IsFractionRing (integralClosure base.valuationSubring L) L
    exact integralClosure.isFractionRing_of_finite_extension K L
  let vL := (IsDiscreteValuationRing.maximalIdeal B).valuation L
  refine ⟨_, inferInstance, vL, inferInstance, ?_, trivial⟩
  exact IsDiscreteValuationRing.equivValuationSubring (A := B) (K := L)

/-- The actual integral closure supplies a rank-one discrete standard adic
valuation, its own maximal-ideal adic completeness, and the comparison of
that valuation ring with the actual integral closure. -/
theorem exists_integralClosure_standard_complete_valuation_data
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ ΓL : Type,
      ∃ _ : LinearOrderedCommGroupWithZero ΓL,
        ∃ vL : _root_.Valuation L ΓL,
          ∃ _ : vL.IsRankOneDiscrete,
            IsAdicComplete
              (CanonicalIntegralClosure.maximalIdeal (K := K) (L := L) base)
              (integralClosure base.valuationSubring L) ∧
              ∃ _ : (integralClosure base.valuationSubring L) ≃+*
                vL.valuationSubring,
                True := by
  obtain ⟨ΓL, hΓL, vL, hvdisc, hev, _⟩ :=
    exists_integralClosure_standard_rankOneDiscrete_valuation
      (K := K) (L := L) base
  let : LinearOrderedCommGroupWithZero ΓL := hΓL
  refine ⟨ΓL, inferInstance, vL, hvdisc, ?_, hev, trivial⟩
  exact integralClosure_maximalIdeal_isAdicComplete_of_finite_separable
    (K := K) (L := L) base

/-- The actual integral closure supplies a complete-DVF target whose valuation
subring is ring-equivalent to the actual integral closure. -/
theorem exists_integralClosure_standard_completeDVF
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ target : CompleteDVF.{w, 0} L,
      (∀ z : L,
        z ∈ target.valuation.valuationSubring ↔
          z ∈ (integralClosure base.valuationSubring L).toSubring) ∧
          ∃ _ : (integralClosure base.valuationSubring L) ≃+*
            target.valuationSubring,
            True := by
  let B := integralClosure base.valuationSubring L
  let : IsLocalRing B :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  let : IsDomain B := by
    change IsDomain (integralClosure base.valuationSubring L)
    infer_instance
  let : IsDiscreteValuationRing B :=
    integralClosure_isDiscreteValuationRing_of_finite_separable
      (K := K) (L := L) base
  let : IsFractionRing B L := by
    change IsFractionRing (integralClosure base.valuationSubring L) L
    exact integralClosure.isFractionRing_of_finite_extension K L
  let vL := (IsDiscreteValuationRing.maximalIdeal B).valuation L
  let e : B ≃+* vL.valuationSubring :=
    IsDiscreteValuationRing.equivValuationSubring (A := B) (K := L)
  let : Algebra B vL.valuationSubring := e.toRingHom.toAlgebra
  let eLin : B ≃ₗ[B] vL.valuationSubring :=
    { toFun := e
      invFun := e.symm
      left_inv := e.left_inv
      right_inv := e.right_inv
      map_add' := e.map_add
      map_smul' := by
        intro r x
        change e (r * x) = (algebraMap B vL.valuationSubring r) * e x
        simp [RingHom.algebraMap_toAlgebra] }
  have :
      IsAdicComplete (IsLocalRing.maximalIdeal B) B :=
    integralClosure_maximalIdeal_isAdicComplete_of_finite_separable
      (K := K) (L := L) base
  have hcompleteAsB :
      IsAdicComplete (IsLocalRing.maximalIdeal B) vL.valuationSubring :=
    isAdicComplete_of_linearEquiv
      (M := B) (N := vL.valuationSubring)
      (IsLocalRing.maximalIdeal B) eLin
  have hcompleteMap :
      IsAdicComplete
        ((IsLocalRing.maximalIdeal B).map
          (algebraMap B vL.valuationSubring))
        vL.valuationSubring :=
    (isAdicComplete_map_algebraMap_iff
      (I := IsLocalRing.maximalIdeal B)
      (S := vL.valuationSubring)).2 hcompleteAsB
  have hmem (x : B) :
      algebraMap B vL.valuationSubring x ∈
          IsLocalRing.maximalIdeal vL.valuationSubring ↔
        x ∈ IsLocalRing.maximalIdeal B := by
    simp only [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
    constructor
    · intro hx hunit
      exact hx (hunit.map (algebraMap B vL.valuationSubring))
    · intro hx hunit
      apply hx
      have hpre := hunit.map e.symm.toRingHom
      simpa [RingHom.algebraMap_toAlgebra] using hpre
  have hmapMax :
      (IsLocalRing.maximalIdeal B).map
          (algebraMap B vL.valuationSubring) =
        IsLocalRing.maximalIdeal vL.valuationSubring := by
    apply le_antisymm
    · rw [Ideal.map_le_iff_le_comap]
      intro x hx
      exact (hmem x).2 hx
    · intro y hy
      have hx :
          e.symm y ∈ IsLocalRing.maximalIdeal B := by
        apply (hmem (e.symm y)).1
        simpa [RingHom.algebraMap_toAlgebra] using hy
      have hmap :=
        Ideal.mem_map_of_mem (algebraMap B vL.valuationSubring) hx
      simpa [RingHom.algebraMap_toAlgebra] using hmap
  have hcompletev :
      IsAdicComplete
        (IsLocalRing.maximalIdeal vL.valuationSubring)
        vL.valuationSubring := by
    simpa [hmapMax] using hcompleteMap
  have hmapSub :
      Subring.map (algebraMap B L) ⊤ =
        vL.valuationSubring.toSubring :=
    IsDiscreteValuationRing.map_algebraMap_eq_valuationSubring
      (A := B) (K := L)
  have hmemStandard (z : L) :
      z ∈ vL.valuationSubring ↔ z ∈ B.toSubring := by
    constructor
    · intro hz
      have hzmap :
          z ∈ Subring.map (algebraMap B L) ⊤ := by
        simpa [hmapSub] using hz
      rcases hzmap with ⟨b, _hbtop, hb⟩
      rw [← hb]
      exact b.2
    · intro hz
      have hzmap :
          z ∈ Subring.map (algebraMap B L) ⊤ :=
        ⟨⟨z, hz⟩, trivial, rfl⟩
      simpa [hmapSub] using hzmap
  let : Valuation.IsCompleteDiscrete vL :=
    { isRankOneDiscrete := inferInstance
      isAdicComplete := hcompletev }
  let target : CompleteDVF.{w, 0} L :=
    { ValueGroup := WithZero (Multiplicative ℤ)
      instValueGroup := inferInstance
      valuation := vL
      instCompleteDiscrete := inferInstance }
  refine ⟨target, ?_, e, trivial⟩
  intro z
  exact hmemStandard z

/-- The standard complete-DVF target supplied by the actual integral closure,
together with its valuation-extension property, integral-closure comparison,
and the fundamental ramification identity. -/
theorem exists_integralClosure_standard_fundamental_identity
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ target : CompleteDVF.{w, 0} L,
      ∃ hExt : base.valuation.HasExtension target.valuation,
        letI : base.valuation.HasExtension target.valuation := hExt
        IsIntegralClosure target.valuationSubring
          base.valuationSubring L ∧
          ValuedExtension.degree base.toDVF target.toDVF =
            ValuedExtension.ramificationIndex base.toDVF target.toDVF *
              ValuedExtension.residueDegree base.toDVF target.toDVF := by
  obtain ⟨target, hmem, _hequiv⟩ :=
    exists_integralClosure_standard_completeDVF
      (K := K) (L := L) base
  have hExt : base.valuation.HasExtension target.valuation := by
    apply _root_.Valuation.HasExtension.ofComapInteger
    ext a
    change
      algebraMap K L a ∈ target.valuation.valuationSubring ↔
        a ∈ base.valuation.valuationSubring
    rw [hmem]
    exact algebraMap_mem_integralClosure_valuationSubring_iff
      (L := L) base.valuation a
  refine ⟨target, hExt, ?_⟩
  let : base.valuation.HasExtension target.valuation := hExt
  have hIntegralClosure :
      IsIntegralClosure target.valuationSubring
        base.valuationSubring L := by
    refine
      { algebraMap_injective := ?_
        isIntegral_iff := ?_ }
    · intro x y hxy
      exact Subtype.ext hxy
    · intro z
      constructor
      · intro hz
        have hzmem :
            z ∈ (integralClosure base.valuationSubring L).toSubring := hz
        exact ⟨⟨z, (hmem z).2 hzmem⟩, rfl⟩
      · rintro ⟨y, rfl⟩
        exact (hmem (y : L)).1 y.2
  refine ⟨hIntegralClosure, ?_⟩
  let :
      IsIntegralClosure target.valuationSubring
        base.valuationSubring L := hIntegralClosure
  let : IsScalarTower base.valuationSubring
      target.valuationSubring L := by
    apply IsScalarTower.of_algebraMap_eq
    intro x
    rfl
  exact isDefectless_of_isIntegralClosure
    (K := K) (L := L) base target

/-- In a finite separable extension of a complete DVF, the actual integral
closure of the base valuation ring is a valuation ring. -/
theorem integralClosure_valuationRing_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ValuationRing (integralClosure base.valuationSubring L) := by
  let : IsLocalRing (integralClosure base.valuationSubring L) :=
    integralClosure_isLocalRing_of_finite_separable (K := K) (L := L) base
  let : IsFractionRing base.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsDomain (integralClosure base.valuationSubring L) := by
    infer_instance
  let : IsDedekindDomain (integralClosure base.valuationSubring L) := by
    exact integralClosure.isDedekindDomain base.valuationSubring K L
  let : IsNoetherianRing (integralClosure base.valuationSubring L) := by
    exact integralClosure.isNoetherianRing (A := base.valuationSubring) (K := K) L
  exact
    ((tfae_of_isNoetherianRing_of_isLocalRing_of_isDomain
      (integralClosure base.valuationSubring L)).out 2 1).mp
      (show IsDedekindDomain (integralClosure base.valuationSubring L) from
        inferInstance)

/-- Record-free valuative dichotomy for the integral closure in a finite
separable extension of a complete DVF. -/
theorem CanonicalIntegralClosure.mem_or_inv_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∀ z : L,
      z ∈ (integralClosure base.valuationSubring L).toSubring ∨
        z⁻¹ ∈ (integralClosure base.valuationSubring L).toSubring := by
  let B := integralClosure base.valuationSubring L
  let : ValuationRing B :=
    integralClosure_valuationRing_of_finite_separable (K := K) (L := L) base
  let : IsFractionRing base.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsFractionRing B L := by
    change IsFractionRing (integralClosure base.valuationSubring L) L
    exact integralClosure.isFractionRing_of_finite_extension K L
  intro z
  rcases ValuationRing.isInteger_or_isInteger (R := B) (K := L) z with
    hz | hz
  · left
    rcases hz with ⟨y, hy⟩
    rw [← hy]
    exact y.2
  · right
    rcases hz with ⟨y, hy⟩
    rw [← hy]
    exact y.2

/-- In a finite separable extension of a complete DVF, the integral
closure itself supplies a valuation subring whose canonical valuation extends
the base valuation.

This is the record-free source used before a `CompleteDVF` target has been
chosen. -/
theorem exists_integralClosure_valuationSubring_of_finite_separable
    (base : CompleteDVF.{u, v} K)
    [Algebra.IsSeparable K L] :
    ∃ B : ValuationSubring L,
      ∃ hExt : base.valuation.HasExtension B.valuation,
        letI : base.valuation.HasExtension B.valuation := hExt
        B.toSubring = (integralClosure base.valuationSubring L).toSubring ∧
          IsIntegralClosure B base.valuationSubring L := by
  exact
    exists_integralClosure_valuationSubring_isIntegralClosure_of_forall_mem_or_inv
      (L := L) base.valuation
      (CanonicalIntegralClosure.mem_or_inv_of_finite_separable
        (K := K) (L := L) base)

end ValuedExtension
end DiscreteValuationField

end

end ValuationTheory
