import ValuedFieldTheory.Valuation.DiscreteValuationField.Extensions
import ValuedFieldTheory.Valuation.DiscreteValuationField.HenselianFinite
import Mathlib.RingTheory.DedekindDomain.IntegralClosure
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.Ideal.GoingUp
import Mathlib.RingTheory.QuasiFinite.Basic
import Mathlib.RingTheory.Spectrum.Prime.Topology
import Mathlib.RingTheory.TensorProduct.Quotient
import Mathlib.RingTheory.Valuation.Integral
import Mathlib.LinearAlgebra.TensorProduct.RightExactness

set_option autoImplicit false

namespace ValuationTheory

/-!
# Integral closures of valuation rings

This module uses the actual mathlib integral closure
`integralClosure base.toDVF.valuationSubring L`.  It does not introduce a replacement
structure.
-/

noncomputable section

universe u v w x

namespace DiscreteValuationField
namespace ValuedExtension

/-- An Artinian ring whose idempotents are all trivial has at most one prime.

This is the topological/idempotent bridge used in the Henselian frontier:
in an Artinian ring, `Spec` is discrete, so a hypothetical singleton clopen
separating two primes is represented by an idempotent. -/
theorem primeSpectrum_subsingleton_of_isArtinianRing_of_idempotents_trivial
    {A : Type u} [CommRing A] [IsArtinianRing A]
    (hidempotent : ∀ e : A, IsIdempotentElem e → e = 0 ∨ e = 1) :
    Subsingleton (PrimeSpectrum A) := by
  constructor
  intro P Q
  by_contra hPQ
  have hclopen : IsClopen ({P} : Set (PrimeSpectrum A)) :=
    isClopen_discrete {P}
  rcases PrimeSpectrum.exists_idempotent_basicOpen_eq_of_isClopen hclopen with
    ⟨e, heidem, heopen⟩
  rcases hidempotent e heidem with rfl | rfl
  · have hPmem :
        P ∈ (PrimeSpectrum.basicOpen (0 : A) : Set (PrimeSpectrum A)) := by
      rw [← heopen]
      exact Set.mem_singleton P
    simp at hPmem
  · have hQmem : Q ∈ ({P} : Set (PrimeSpectrum A)) := by
      rw [heopen]
      simp
    exact hPQ hQmem.symm

/-- Over a local base ring, the canonical map from an algebra to the fiber over
the maximal ideal is surjective. -/
theorem maximalIdeal_fiber_includeRight_surjective
    {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S]
    [Algebra R S] :
    Function.Surjective
      (Algebra.TensorProduct.includeRight :
        S →ₐ[R] (IsLocalRing.maximalIdeal R).Fiber S) := by
  intro x
  rcases Ideal.Fiber.exists_smul_eq_one_tmul
      (p := IsLocalRing.maximalIdeal R) (S := S) x with
    ⟨r, hr, s, hs⟩
  have hrunit : IsUnit r := by
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] at hr
    exact Classical.not_not.mp hr
  rcases hrunit with ⟨u, rfl⟩
  refine ⟨(↑u⁻¹ : R) • s, ?_⟩
  have hs' := congrArg (fun y =>
      (↑u⁻¹ : R) • y) hs
  simpa [Algebra.TensorProduct.includeRight_apply, smul_smul,
    Units.inv_mul, one_smul] using hs'.symm

/-- Over a local base ring, the kernel of the canonical map from an algebra to
the fiber over the maximal ideal is the ideal generated by the maximal ideal of
the base.

This is the Ideal.Fiber form of the residue-field tensor kernel calculation:
S -> (maximalIdeal R).Fiber S has kernel maximalIdeal R * S. -/
theorem maximalIdeal_fiber_includeRight_ker_eq_maximalIdeal_map
    {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S]
    [Algebra R S] :
    RingHom.ker ((Algebra.TensorProduct.includeRight :
      S →ₐ[R] (IsLocalRing.maximalIdeal R).Fiber S) :
        S →+* (IsLocalRing.maximalIdeal R).Fiber S) =
      (IsLocalRing.maximalIdeal R).map (algebraMap R S) := by
  let I := (IsLocalRing.maximalIdeal R).map (algebraMap R S)
  let e : (IsLocalRing.maximalIdeal R).Fiber S ≃ₐ[R] S ⧸ I :=
    (Algebra.TensorProduct.congr (.symm <| .ofBijective _
      (Ideal.bijective_algebraMap_quotient_residueField
        (IsLocalRing.maximalIdeal R))) .refl).trans <|
    (Algebra.TensorProduct.comm _ _ _).trans
    ((Algebra.TensorProduct.quotIdealMapEquivTensorQuot S
      (IsLocalRing.maximalIdeal R)).symm.restrictScalars _)
  have he_apply (s : S) :
      e ((Algebra.TensorProduct.includeRight :
        S →ₐ[R] (IsLocalRing.maximalIdeal R).Fiber S) s) =
        Ideal.Quotient.mk I s := by
    simpa [e, I, Algebra.TensorProduct.includeRight_apply] using
      (Algebra.TensorProduct.quotIdealMapEquivTensorQuot_symm_tmul
        (B := S) (I := IsLocalRing.maximalIdeal R) s (1 : R))
  ext s
  constructor
  · intro hs
    have hq :
        e ((Algebra.TensorProduct.includeRight :
          S →ₐ[R] (IsLocalRing.maximalIdeal R).Fiber S) s) = 0 := by
      simpa using congrArg e hs
    rw [he_apply s] at hq
    simpa [I, Ideal.Quotient.eq_zero_iff_mem] using hq
  · intro hs
    change (Algebra.TensorProduct.includeRight :
      S →ₐ[R] (IsLocalRing.maximalIdeal R).Fiber S) s = 0
    apply e.injective
    rw [he_apply s, map_zero]
    simpa [I, Ideal.Quotient.eq_zero_iff_mem] using hs

/-- For a local ring `R`, the kernel of `S → κ(R) ⊗[R] S` is the ideal of
`S` generated by the maximal ideal of `R`.

This is the local-residue-field tensor form of the kernel computation needed
for the Henselian finite-extension frontier. -/
theorem residueField_tensor_includeRight_ker_eq_maximalIdeal_map
    {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S]
    [Algebra R S] :
    RingHom.ker ((Algebra.TensorProduct.includeRight :
      S →ₐ[R] TensorProduct R (IsLocalRing.ResidueField R) S) :
        S →+* TensorProduct R (IsLocalRing.ResidueField R) S) =
      (IsLocalRing.maximalIdeal R).map (algebraMap R S) := by
  let k := IsLocalRing.ResidueField R
  let f : R →ₐ[R] k := Algebra.ofId R k
  let F : TensorProduct R R S →ₐ[R] TensorProduct R k S :=
    Algebra.TensorProduct.map f (AlgHom.id R S)
  let inc : R →+* TensorProduct R R S :=
    (Algebra.TensorProduct.includeLeft :
      R →ₐ[R] TensorProduct R R S).toRingHom
  let lid : TensorProduct R R S →+* S :=
    (Algebra.TensorProduct.lid R S).toRingEquiv.toRingHom
  have hf_eq : (f : R →+* k) = IsLocalRing.residue R := by
    change algebraMap R k = IsLocalRing.residue R
    dsimp only [k]
    exact IsLocalRing.ResidueField.algebraMap_eq R
  have hf : Function.Surjective f := by
    change Function.Surjective (algebraMap R k)
    rw [IsLocalRing.ResidueField.algebraMap_eq]
    exact IsLocalRing.residue_surjective
  have hkerf :
      RingHom.ker f = IsLocalRing.maximalIdeal R := by
    rw [AlgHom.ker_coe, hf_eq]
    exact IsLocalRing.ker_residue
  have hkerF :
      RingHom.ker F =
        (RingHom.ker f).map
          (Algebra.TensorProduct.includeLeft :
            R →ₐ[R] TensorProduct R R S) :=
    Algebra.TensorProduct.rTensor_ker (R := R) (A := R) (B := k)
      (C := S) f hf
  have hcomp :
      ∀ x : S,
        F ((Algebra.TensorProduct.lid R S).symm x) =
          (Algebra.TensorProduct.includeRight :
            S →ₐ[R] TensorProduct R k S) x := by
    intro x
    simp [F, Algebra.TensorProduct.lid_symm_apply,
      Algebra.TensorProduct.includeRight_apply]
  have hmap_lid :
      ((RingHom.ker f).map inc).map lid =
        (RingHom.ker f).map (algebraMap R S) := by
    calc
      ((RingHom.ker f).map inc).map lid =
          (RingHom.ker f).map (lid.comp inc) := by
            exact Ideal.map_map inc lid
              (I := RingHom.ker f)
      _ = (RingHom.ker f).map (algebraMap R S) := by
        congr 1
        ext r
        simp [inc, lid, Algebra.TensorProduct.includeLeft_apply,
          Algebra.smul_def]
  ext x
  rw [RingHom.mem_ker]
  change
    (Algebra.TensorProduct.includeRight :
      S →ₐ[R] TensorProduct R k S) x = 0 ↔
        x ∈ (IsLocalRing.maximalIdeal R).map (algebraMap R S)
  rw [← hcomp x]
  change (Algebra.TensorProduct.lid R S).symm x ∈
      RingHom.ker F ↔
    x ∈ (IsLocalRing.maximalIdeal R).map (algebraMap R S)
  rw [hkerF, hkerf]
  change (Algebra.TensorProduct.lid R S).symm x ∈
      (IsLocalRing.maximalIdeal R).map inc ↔
    x ∈ (IsLocalRing.maximalIdeal R).map (algebraMap R S)
  have hmap_lid_m :
      ((IsLocalRing.maximalIdeal R).map inc).map lid =
        (IsLocalRing.maximalIdeal R).map (algebraMap R S) := by
    simpa [hkerf] using hmap_lid
  constructor
  · intro hx
    have hxmap :
        lid
            ((Algebra.TensorProduct.lid R S).symm x) ∈
          ((IsLocalRing.maximalIdeal R).map inc).map lid :=
      Ideal.mem_map_of_mem lid hx
    have hxmap' : x ∈ ((IsLocalRing.maximalIdeal R).map inc).map lid := by
      simpa [lid] using hxmap
    simpa [hmap_lid_m] using hxmap'
  · intro hx
    have hxmap : x ∈ ((IsLocalRing.maximalIdeal R).map inc).map lid := by
      simpa [hmap_lid_m] using hx
    rw [Ideal.mem_map_iff_of_surjective
      lid
      (Algebra.TensorProduct.lid R S).surjective] at hxmap
    rcases hxmap with ⟨y, hy, hyx⟩
    simpa [inc, lid, ← hyx] using hy

variable {K : Type u} {L : Type w} [Field K] [Field L]
variable [Algebra K L] [FiniteDimensional K L]
variable (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
variable [base.valuation.HasExtension target.valuation]

omit [FiniteDimensional K L] in
/-- Every element integral over the base valuation ring lies in any valuation
ring extending the base valuation.  This is the construction-level inclusion
from the actual integral closure into an extension valuation ring. -/
theorem integralClosure_mem_target_valuationSubring_of_hasExtension
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    (z : integralClosure base.toDVF.valuationSubring L) :
    (z : L) ∈ target.valuation.valuationSubring := by
  have hz_base : IsIntegral base.toDVF.valuationSubring (z : L) :=
    z.2
  have hz_target : IsIntegral target.toDVF.valuationSubring (z : L) :=
    IsIntegral.tower_top (A := target.toDVF.valuationSubring) hz_base
  exact Valuation.Integers.mem_of_integral
    (Valuation.valuationSubring.integers (v := target.valuation)) hz_target

/-- The canonical map from the actual integral closure of the base valuation
ring in `L` to any valuation ring extending the base valuation. -/
def integralClosureToTargetValuationSubringOfHasExtension
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    integralClosure base.toDVF.valuationSubring L →+* target.toDVF.valuationSubring where
  toFun z :=
    ⟨(z : L),
      integralClosure_mem_target_valuationSubring_of_hasExtension
        (K := K) (L := L) base target z⟩
  map_zero' := by ext; simp
  map_one' := by ext; simp
  map_add' z₁ z₂ := by ext; simp
  map_mul' z₁ z₂ := by ext; simp

omit [FiniteDimensional K L] in
/-- The map from the integral closure to the target valuation ring uses the ambient inclusion. -/
@[simp] theorem integralClosureToTargetValuationSubringOfHasExtension_apply
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    (z : integralClosure base.toDVF.valuationSubring L) :
    ((integralClosureToTargetValuationSubringOfHasExtension
      (K := K) (L := L) base target z : target.toDVF.valuationSubring) : L) = z :=
  rfl

omit [FiniteDimensional K L] in
/-- The canonical map from the integral closure to an extension valuation ring
is injective. -/
theorem integralClosureToTargetValuationSubringOfHasExtension_injective
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    Function.Injective
      (integralClosureToTargetValuationSubringOfHasExtension
        (K := K) (L := L) base target) := by
  intro z₁ z₂ hz
  apply Subtype.ext
  exact congrArg (fun z : target.toDVF.valuationSubring => (z : L)) hz

omit [FiniteDimensional K L] in
/-- Under module-finiteness of the extension valuation ring over the base
valuation ring, every target valuation-ring element is integral over the base
valuation ring. -/
theorem target_valuationSubring_mem_integralClosure_of_moduleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    (z : target.toDVF.valuationSubring) :
    (z : L) ∈ integralClosure base.toDVF.valuationSubring L := by
  have hz_target : IsIntegral base.toDVF.valuationSubring z :=
    IsIntegral.of_finite base.toDVF.valuationSubring z
  have hz_L : IsIntegral base.toDVF.valuationSubring
      (algebraMap target.toDVF.valuationSubring L z) :=
    hz_target.map
      (IsScalarTower.toAlgHom base.toDVF.valuationSubring target.toDVF.valuationSubring L)
  rw [mem_integralClosure_iff]
  simpa using hz_L

/-- The canonical map from a finite extension valuation ring into the actual
integral closure of the base valuation ring. -/
def targetValuationSubringToIntegralClosureOfModuleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    target.toDVF.valuationSubring →+* integralClosure base.toDVF.valuationSubring L where
  toFun z :=
    ⟨(z : L),
      target_valuationSubring_mem_integralClosure_of_moduleFinite
        (K := K) (L := L) base target z⟩
  map_zero' := by ext; simp
  map_one' := by ext; simp
  map_add' z₁ z₂ := by ext; simp
  map_mul' z₁ z₂ := by ext; simp

omit [FiniteDimensional K L] in
/-- The inverse map sends a target integer to its integral-closure representative. -/
@[simp] theorem targetValuationSubringToIntegralClosureOfModuleFinite_apply
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    (z : target.toDVF.valuationSubring) :
    ((targetValuationSubringToIntegralClosureOfModuleFinite
      (K := K) (L := L) base target z :
        integralClosure base.toDVF.valuationSubring L) : L) = z :=
  rfl

omit [FiniteDimensional K L] in
/-- Under module-finiteness, the canonical map from the integral closure to the
extension valuation ring is surjective. -/
theorem integralClosureToTargetValuationSubringOfHasExtension_surjective_of_moduleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    Function.Surjective
      (integralClosureToTargetValuationSubringOfHasExtension
        (K := K) (L := L) base target) := by
  intro z
  refine ⟨targetValuationSubringToIntegralClosureOfModuleFinite
    (K := K) (L := L) base target z, ?_⟩
  ext
  rfl

omit [FiniteDimensional K L] in
/-- Under module-finiteness, the canonical map from the integral closure to the
extension valuation ring is bijective. -/
theorem integralClosureToTargetValuationSubringOfHasExtension_bijective_of_moduleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    Function.Bijective
      (integralClosureToTargetValuationSubringOfHasExtension
        (K := K) (L := L) base target) :=
  ⟨integralClosureToTargetValuationSubringOfHasExtension_injective
      (K := K) (L := L) base target,
    integralClosureToTargetValuationSubringOfHasExtension_surjective_of_moduleFinite
      (K := K) (L := L) base target⟩

/-- If the extension valuation ring is finite over the base valuation ring,
then it is canonically ring-equivalent to the actual integral closure of the
base valuation ring in the extension field. -/
noncomputable def integralClosureRingEquivTargetValuationSubringOfModuleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    integralClosure base.toDVF.valuationSubring L ≃+* target.toDVF.valuationSubring :=
  RingEquiv.ofBijective
    (integralClosureToTargetValuationSubringOfHasExtension
      (K := K) (L := L) base target)
    (integralClosureToTargetValuationSubringOfHasExtension_bijective_of_moduleFinite
      (K := K) (L := L) base target)

omit [FiniteDimensional K L] in
/-- The finite integral-closure ring equivalence evaluates by the canonical inclusion. -/
@[simp] theorem integralClosureRingEquivTargetValuationSubringOfModuleFinite_apply
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    (z : integralClosure base.toDVF.valuationSubring L) :
    (integralClosureRingEquivTargetValuationSubringOfModuleFinite
      (K := K) (L := L) base target z :
        target.toDVF.valuationSubring) =
      integralClosureToTargetValuationSubringOfHasExtension
        (K := K) (L := L) base target z :=
  rfl

/-- Algebra-equivalence form of
`integralClosureRingEquivTargetValuationSubringOfModuleFinite`. -/
noncomputable def integralClosureAlgEquivTargetValuationSubringOfModuleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    integralClosure base.toDVF.valuationSubring L ≃ₐ[base.toDVF.valuationSubring]
      target.toDVF.valuationSubring :=
  AlgEquiv.ofRingEquiv
    (f := integralClosureRingEquivTargetValuationSubringOfModuleFinite
      (K := K) (L := L) base target)
    (by
      intro x
      ext
      exact (IsScalarTower.algebraMap_apply
        base.toDVF.valuationSubring target.toDVF.valuationSubring L x).symm)

omit [FiniteDimensional K L] in
/-- The finite integral-closure algebra equivalence evaluates by the canonical inclusion. -/
@[simp] theorem integralClosureAlgEquivTargetValuationSubringOfModuleFinite_apply
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    (z : integralClosure base.toDVF.valuationSubring L) :
    (integralClosureAlgEquivTargetValuationSubringOfModuleFinite
      (K := K) (L := L) base target z :
        target.toDVF.valuationSubring) =
      integralClosureToTargetValuationSubringOfHasExtension
        (K := K) (L := L) base target z :=
  integralClosureRingEquivTargetValuationSubringOfModuleFinite_apply
    (K := K) (L := L) base target z

omit [FiniteDimensional K L] in
/-- If the extension valuation ring is finite over the base valuation ring,
then it is the integral closure of the base valuation ring in the extension
field. -/
theorem target_valuationSubring_isIntegralClosure_of_moduleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L := by
  refine
    { algebraMap_injective := Subtype.coe_injective
      isIntegral_iff := ?_ }
  intro x
  constructor
  · intro hx
    refine ⟨integralClosureToTargetValuationSubringOfHasExtension
      (K := K) (L := L) base target ⟨x, hx⟩, ?_⟩
    rfl
  · rintro ⟨y, rfl⟩
    exact target_valuationSubring_mem_integralClosure_of_moduleFinite
      (K := K) (L := L) base target y

omit [FiniteDimensional K L] in
/-- Ambient-context version of
`target_valuationSubring_isIntegralClosure_of_moduleFinite`. -/
theorem target_valuationSubring_isIntegralClosure_of_moduleFinite'
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L :=
  target_valuationSubring_isIntegralClosure_of_moduleFinite
    (K := K) (L := L) base target

/-- The valuation ring of a complete DVF is a fraction ring inside the field. -/
theorem base_valuationSubring_isFractionRing (base : CompleteDVF.{u, v} K) :
    IsFractionRing base.toDVF.valuationSubring K :=
  (Valuation.valuationSubring.integers (v := base.valuation)).isFractionRing

/-- The valuation ring of a complete DVF is integrally closed. -/
theorem base_valuationSubring_isIntegrallyClosed
    (base : CompleteDVF.{u, v} K) :
    IsIntegrallyClosed base.toDVF.valuationSubring := by
  exact inferInstanceAs (IsIntegrallyClosed base.valuation.valuationSubring)

/-- The valuation ring of a complete DVF is Noetherian. -/
theorem base_valuationSubring_isNoetherianRing
    (base : CompleteDVF.{u, v} K) :
    IsNoetherianRing base.toDVF.valuationSubring := by
  have : IsDiscreteValuationRing base.toDVF.valuationSubring :=
    base.valuationSubring_isDiscreteValuationRing
  infer_instance

/-- If a chosen extension valuation ring is already proved to be the integral
closure of the base valuation ring in a finite separable field extension, then
it is finite over the base valuation ring. -/
theorem moduleFinite_target_valuationSubring_of_isIntegralClosure
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Algebra.IsSeparable K L]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    [IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L] :
    Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsIntegrallyClosed base.toDVF.valuationSubring :=
    base_valuationSubring_isIntegrallyClosed (K := K) base
  let : IsNoetherianRing base.toDVF.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) base
  exact IsIntegralClosure.finite base.toDVF.valuationSubring K L target.toDVF.valuationSubring

/-- Ambient-context version of
`moduleFinite_target_valuationSubring_of_isIntegralClosure`. -/
theorem moduleFinite_target_valuationSubring_of_isIntegralClosure'
    [Algebra.IsSeparable K L]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    [IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L] :
    Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring :=
  moduleFinite_target_valuationSubring_of_isIntegralClosure
    (K := K) (L := L) base target

/-- For finite separable field extensions with a chosen valuation extension,
being the integral closure is equivalent to being finite as a module over the
base valuation ring. -/
theorem target_valuationSubring_isIntegralClosure_iff_moduleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Algebra.IsSeparable K L]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L ↔
      Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring := by
  constructor
  · intro hIntegralClosure
    let :
        IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L :=
      hIntegralClosure
    exact moduleFinite_target_valuationSubring_of_isIntegralClosure
      (K := K) (L := L) base target
  · intro hFinite
    let : Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring :=
      hFinite
    exact target_valuationSubring_isIntegralClosure_of_moduleFinite
      (K := K) (L := L) base target

/-- Ambient-context version of
`target_valuationSubring_isIntegralClosure_iff_moduleFinite`. -/
theorem target_valuationSubring_isIntegralClosure_iff_moduleFinite'
    [Algebra.IsSeparable K L]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L] :
    IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L ↔
      Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring :=
  target_valuationSubring_isIntegralClosure_iff_moduleFinite
    (K := K) (L := L) base target

omit [FiniteDimensional K L] in
/-- The target maximal ideal lies over the base maximal ideal for an actual
extension of valuations.  This is the prime-theoretic input for replacing
certificate-style choices of a prime above the base maximal ideal. -/
theorem target_maximalIdeal_liesOver_base_maximal_of_hasExtension
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation] :
    target.maximalIdeal.LiesOver base.maximalIdeal := by
  exact inferInstanceAs
    ((IsLocalRing.maximalIdeal target.valuation.valuationSubring).LiesOver
      (IsLocalRing.maximalIdeal base.valuation.valuationSubring))

omit [FiniteDimensional K L] in
/-- In an integral local valued extension, every prime of the target valuation
ring lying over the base maximal ideal is the target maximal ideal. -/
theorem target_primeOver_eq_maximalIdeal_of_isIntegral
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Algebra.IsIntegral base.toDVF.valuationSubring target.toDVF.valuationSubring]
    {P : Ideal target.toDVF.valuationSubring}
    (hP : P ∈ Ideal.primesOver base.maximalIdeal target.toDVF.valuationSubring) :
    P = target.maximalIdeal :=
  IsLocalRing.eq_maximalIdeal (Ideal.isMaximal_of_mem_primesOver hP)

omit [FiniteDimensional K L] in
/-- Integral local valued extensions have a unique prime above the base
maximal ideal: the target maximal ideal. -/
theorem target_primesOver_base_maximal_eq_singleton_of_isIntegral
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Algebra.IsIntegral base.toDVF.valuationSubring target.toDVF.valuationSubring] :
    Ideal.primesOver base.maximalIdeal target.toDVF.valuationSubring =
      {target.maximalIdeal} := by
  refine Set.eq_singleton_iff_unique_mem.mpr ⟨?_, ?_⟩
  · exact
      ⟨(IsLocalRing.maximalIdeal.isMaximal target.toDVF.valuationSubring).isPrime,
        target_maximalIdeal_liesOver_base_maximal_of_hasExtension
          (K := K) (L := L) base target⟩
  · intro P hP
    exact target_primeOver_eq_maximalIdeal_of_isIntegral
      (K := K) (L := L) base target hP

omit [FiniteDimensional K L] in
/-- Module-finite local valued extensions have a unique prime above the base
maximal ideal. -/
theorem target_primesOver_base_maximal_eq_singleton_of_moduleFinite
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [Module.Finite base.toDVF.valuationSubring target.toDVF.valuationSubring] :
    Ideal.primesOver base.maximalIdeal target.toDVF.valuationSubring =
      {target.maximalIdeal} := by
  let : Algebra.IsIntegral base.toDVF.valuationSubring target.toDVF.valuationSubring :=
    Algebra.IsIntegral.of_finite base.toDVF.valuationSubring target.toDVF.valuationSubring
  exact target_primesOver_base_maximal_eq_singleton_of_isIntegral
    (K := K) (L := L) base target

omit [FiniteDimensional K L] in
/-- If the target valuation ring has already been identified as the integral
closure of the base valuation ring in the field extension, then the prime over
the base maximal ideal is unique. -/
theorem target_primesOver_base_maximal_eq_singleton_of_isIntegralClosure
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    [IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L] :
    Ideal.primesOver base.maximalIdeal target.toDVF.valuationSubring =
      {target.maximalIdeal} := by
  let : Algebra.IsIntegral base.toDVF.valuationSubring target.toDVF.valuationSubring :=
    IsIntegralClosure.isIntegral_algebra base.toDVF.valuationSubring L
  exact target_primesOver_base_maximal_eq_singleton_of_isIntegral
    (K := K) (L := L) base target

omit [FiniteDimensional K L] in
/-- If the chosen extension valuation ring is the actual integral closure of
the base valuation ring in `L`, then the actual integral closure satisfies the
valuation-ring dichotomy.  This is the bridge from an integral-closure
identification to the `hval` input used by the finite-separable uniqueness API. -/
theorem integralClosure_mem_or_inv_of_target_valuationSubring_isIntegralClosure
    (base : CompleteDVF.{u, v} K) (target : CompleteDVF.{w, x} L)
    [base.valuation.HasExtension target.valuation]
    [IsScalarTower base.toDVF.valuationSubring target.toDVF.valuationSubring L]
    [IsIntegralClosure target.toDVF.valuationSubring base.toDVF.valuationSubring L] :
    ∀ z : L,
      z ∈ (integralClosure base.toDVF.valuationSubring L).toSubring ∨
        z⁻¹ ∈ (integralClosure base.toDVF.valuationSubring L).toSubring := by
  intro z
  rcases target.valuation.valuationSubring.mem_or_inv_mem z with hz | hz
  · left
    exact
      (show IsIntegral base.toDVF.valuationSubring z from
        (IsIntegralClosure.isIntegral_iff
          (A := target.toDVF.valuationSubring) (R := base.toDVF.valuationSubring)
          (B := L)).2 ⟨⟨z, hz⟩, rfl⟩)
  · right
    exact
      (show IsIntegral base.toDVF.valuationSubring z⁻¹ from
        (IsIntegralClosure.isIntegral_iff
          (A := target.toDVF.valuationSubring) (R := base.toDVF.valuationSubring)
          (B := L)).2 ⟨⟨z⁻¹, hz⟩, rfl⟩)

/-- The actual integral closure of the base valuation ring in the extension
field. -/
abbrev integralClosureIntegers (base : CompleteDVF.{u, v} K)
    (_target : CompleteDVF.{w, x} L) : Type _ :=
  integralClosure base.toDVF.valuationSubring L

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- The actual integral closure is an `IsIntegralClosure`. -/
theorem integralClosure_isIntegralClosure :
    IsIntegralClosure (integralClosureIntegers base target) base.toDVF.valuationSubring L := by
  exact inferInstanceAs
    (IsIntegralClosure (integralClosure base.toDVF.valuationSubring L)
      base.toDVF.valuationSubring L)

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- The actual integral closure is integral over the base valuation ring. -/
theorem integralClosure_isIntegral :
    Algebra.IsIntegral base.toDVF.valuationSubring (integralClosureIntegers base target) := by
  exact inferInstanceAs
    (Algebra.IsIntegral base.toDVF.valuationSubring
      (integralClosure base.toDVF.valuationSubring L))

omit [base.valuation.HasExtension target.valuation] in
/-- The algebra map from the base valuation ring into the actual integral
closure is injective. -/
theorem integralClosure_algebraMap_injective :
    Function.Injective
      (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)) := by
  intro x y hxy
  apply Subtype.ext
  apply FaithfulSMul.algebraMap_injective K L
  exact congrArg (fun z : (integralClosureIntegers base target) => (z : L)) hxy

omit [base.valuation.HasExtension target.valuation] in
/-- The actual integral closure is faithful over the base valuation ring. -/
theorem integralClosure_faithfulSMul :
    FaithfulSMul base.toDVF.valuationSubring (integralClosureIntegers base target) :=
  (faithfulSMul_iff_algebraMap_injective
    base.toDVF.valuationSubring (integralClosureIntegers base target)).mpr
    (integralClosure_algebraMap_injective base target)

omit [base.valuation.HasExtension target.valuation] in
/-- In a finite separable field extension, the actual integral closure is
module-finite over the base valuation ring. -/
theorem moduleFinite_integralClosureIntegers
    [Algebra.IsSeparable K L] :
    Module.Finite base.toDVF.valuationSubring (integralClosureIntegers base target) := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsIntegrallyClosed base.toDVF.valuationSubring :=
    base_valuationSubring_isIntegrallyClosed (K := K) base
  let : IsNoetherianRing base.toDVF.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) base
  exact
    (show Module.Finite base.toDVF.valuationSubring
        (integralClosure base.toDVF.valuationSubring L) from
      IsIntegralClosure.finite base.toDVF.valuationSubring K L
        (integralClosure base.toDVF.valuationSubring L))

omit [base.valuation.HasExtension target.valuation] in
/-- In a finite separable field extension, the actual integral closure is
quasi-finite over the base valuation ring. -/
theorem integralClosure_quasiFinite
    [Algebra.IsSeparable K L] :
    Algebra.QuasiFinite base.toDVF.valuationSubring (integralClosureIntegers base target) := by
  let : Module.Finite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (moduleFinite_integralClosureIntegers base target)
  infer_instance

omit [base.valuation.HasExtension target.valuation] in
/-- The residue fiber of the finite actual integral closure over the base
maximal ideal is Artinian. -/
theorem integralClosure_base_maximal_fiber_isArtinianRing
    [Algebra.IsSeparable K L] :
    IsArtinianRing (base.maximalIdeal.Fiber (integralClosureIntegers base target)) := by
  let : Algebra.QuasiFinite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_quasiFinite base target)
  infer_instance

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- For the actual integral closure, the kernel of the residue-fiber
includeRight map is the ideal generated by the base maximal ideal. -/
theorem integralClosure_base_maximal_fiber_includeRight_ker_eq_maximalIdeal_map
     :
    RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) =
      base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)) := by
  simpa using
    (maximalIdeal_fiber_includeRight_ker_eq_maximalIdeal_map
      (R := base.toDVF.valuationSubring) (S := (integralClosureIntegers base target)))

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- Idempotents in the actual integral closure in the extension field are
trivial.

This keeps the Henselian frontier focused on lifting idempotents out of the
finite residue fiber: once an idempotent has lifted to the actual integral
closure, domainhood inside the field forces it to be `0` or `1`. -/
theorem integralClosure_idempotent_eq_zero_or_one
    (e : (integralClosureIntegers base target))
    (he : IsIdempotentElem e) :
    e = 0 ∨ e = 1 := by
  let : IsDomain (integralClosureIntegers base target) := by
    exact inferInstanceAs
      (IsDomain (integralClosure base.toDVF.valuationSubring L))
  exact IsIdempotentElem.iff_eq_zero_or_one.mp he

omit [base.valuation.HasExtension target.valuation] in
/-- If every idempotent of the residue fiber over the base maximal ideal lifts
to an idempotent of the actual integral closure, then that fiber has at most
one prime.

This packages the topological Artinian-fiber/idempotent argument in the form
needed by the Henselian finite-extension proof. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift
    [Algebra.IsSeparable K L]
    (hlift :
      ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
        IsIdempotentElem e →
          ∃ b : (integralClosureIntegers base target),
            IsIdempotentElem b ∧
              Algebra.TensorProduct.includeRight b = e) :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  let : IsArtinianRing
      (base.maximalIdeal.Fiber (integralClosureIntegers base target)) :=
    (integralClosure_base_maximal_fiber_isArtinianRing base target)
  refine primeSpectrum_subsingleton_of_isArtinianRing_of_idempotents_trivial ?_
  intro e he
  rcases hlift e he with ⟨b, hbidem, hbmap⟩
  rcases (integralClosure_idempotent_eq_zero_or_one base target) b hbidem with rfl | rfl
  · left
    rw [← hbmap]
    simp
  · right
    rw [← hbmap]
    exact (Algebra.TensorProduct.includeRight :
      (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
        base.maximalIdeal.Fiber (integralClosureIntegers base target)).map_one

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- Henselian-kernel form of idempotent lifting for the residue fiber of the
actual integral closure.

The remaining Henselian finite-extension work can now focus on proving that
the `includeRight` map to the finite residue fiber is surjective and has
Henselian kernel; the idempotent lifting itself is supplied by Hensel's lemma
for `X^2 - X`. -/
theorem
integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_surjective_henselianRing_ker
    (hsurj :
      Function.Surjective
        (Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
      IsIdempotentElem e →
        ∃ b : (integralClosureIntegers base target),
          IsIdempotentElem b ∧
            Algebra.TensorProduct.includeRight b = e := by
  intro e he
  let φ : (integralClosureIntegers base target) →+*
      base.maximalIdeal.Fiber (integralClosureIntegers base target) :=
    (Algebra.TensorProduct.includeRight :
      (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
        base.maximalIdeal.Fiber (integralClosureIntegers base target))
  have hsurjφ : Function.Surjective φ := by
    simpa [φ] using hsurj
  rcases exists_idempotent_lift_of_surjective_henselianRing_ker
      φ hsurjφ e he with
    ⟨b, hbidem, hbmap⟩
  exact ⟨b, hbidem, by simpa [φ] using hbmap⟩

omit [base.valuation.HasExtension target.valuation] in
/-- If the residue-fiber `includeRight` map has Henselian kernel and is
surjective, then the fiber has at most one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_includeRight_surjective_henselianRing_ker
    [Algebra.IsSeparable K L]
    (hsurj :
      Function.Surjective
        (Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  refine
    (integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift base target) ?_
  exact (
integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_surjective_henselianRing_ker
    base target) hsurj

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- Henselian-kernel idempotent lifting for the residue fiber of the actual
integral closure.

The `includeRight` map is automatically surjective because the base valuation
ring is local. -/
theorem integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_henselianRing_ker
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
      IsIdempotentElem e →
        ∃ b : (integralClosureIntegers base target),
          IsIdempotentElem b ∧
            Algebra.TensorProduct.includeRight b = e := by
  refine (
integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_surjective_henselianRing_ker
    base target) ?_
  simpa using
    (maximalIdeal_fiber_includeRight_surjective
      (R := base.toDVF.valuationSubring) (S := (integralClosureIntegers base target)))

omit [base.valuation.HasExtension target.valuation] in
/-- If the `includeRight` map to the residue fiber has Henselian kernel, then
the fiber has at most one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_includeRight_henselianRing_ker
    [Algebra.IsSeparable K L]
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  refine
    (integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift base target) ?_
  exact
    (integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_henselianRing_ker
      base target)

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- Idempotent lifting from the natural Henselian-pair ideal
`base.maximalIdeal.map` in the actual integral closure.

The generic kernel computation identifies this ideal with the kernel of the
residue-fiber includeRight map. -/
theorem integralClosure_base_maximal_fiber_idempotents_lift_of_henselianRing_maximalIdeal_map
    [HenselianRing (integralClosureIntegers base target)
      (base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)))] :
    ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
      IsIdempotentElem e →
        ∃ b : (integralClosureIntegers base target),
          IsIdempotentElem b ∧
            Algebra.TensorProduct.includeRight b = e := by
  let : HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
    rw [(integralClosure_base_maximal_fiber_includeRight_ker_eq_maximalIdeal_map base target)]
    infer_instance
  exact
    (integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_henselianRing_ker
      base target)

omit [base.valuation.HasExtension target.valuation] in
/-- If the ideal generated by the base maximal ideal is Henselian in the actual
integral closure, then the residue fiber has at most one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_henselianRing_maximalIdeal_map
    [Algebra.IsSeparable K L]
    [HenselianRing (integralClosureIntegers base target)
      (base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)))] :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  let : HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
    rw [(integralClosure_base_maximal_fiber_includeRight_ker_eq_maximalIdeal_map base target)]
    infer_instance
  exact
    (integralClosure_base_maximal_fiber_subsingleton_of_includeRight_henselianRing_ker base target)



omit [base.valuation.HasExtension target.valuation] in
/-- In a finite separable extension of complete DVFs, the natural ideal generated
by the base maximal ideal is Henselian in the actual integral closure.

This packages the finite-module completeness theorem together with the
comparison between I-adic and I.map-adic completeness. -/
theorem integralClosure_base_maximal_map_henselianRing
    [Algebra.IsSeparable K L] :
    HenselianRing (integralClosureIntegers base target)
      (base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target))) := by
  let : IsNoetherianRing base.toDVF.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) base
  let : Module.Finite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (moduleFinite_integralClosureIntegers base target)
  have : IsAdicComplete base.maximalIdeal base.toDVF.valuationSubring :=
    base.isAdicComplete
  have hcomplete : IsAdicComplete base.maximalIdeal (integralClosureIntegers base target) :=
    ValuationTheory.DiscreteValuationField.isAdicComplete_of_moduleFinite
      (I := base.maximalIdeal)
  have hmapComplete :
      IsAdicComplete
        (base.maximalIdeal.map
          (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)))
        (integralClosureIntegers base target) :=
    (isAdicComplete_map_algebraMap_iff
      (I := base.maximalIdeal) (S := (integralClosureIntegers base target))).mpr hcomplete
  have := hmapComplete
  infer_instance

omit [base.valuation.HasExtension target.valuation] in
/-- In a finite separable field extension, there are only finitely many primes
of the actual integral closure above the base maximal ideal. -/
theorem integralClosure_primesOver_base_maximal_finite
    [Algebra.IsSeparable K L] :
    (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)).Finite := by
  let : Algebra.QuasiFinite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_quasiFinite base target)
  exact Algebra.QuasiFinite.finite_primesOver
    (S := (integralClosureIntegers base target)) base.maximalIdeal

omit [base.valuation.HasExtension target.valuation] in
/-- The actual integral closure has at least one prime above the base maximal
ideal. -/
theorem integralClosure_primesOver_base_maximal_nonempty
     :
    Nonempty (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) := by
  let : Algebra.IsIntegral base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_isIntegral base target)
  let : FaithfulSMul base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_faithfulSMul base target)
  rcases Ideal.exists_maximal_ideal_liesOver_of_isIntegral
      (S := (integralClosureIntegers base target)) base.maximalIdeal with
    ⟨P, hPmax, hPover⟩
  exact ⟨⟨P, hPmax.isPrime, hPover⟩⟩

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- If the residue fiber over the base maximal ideal has at most one prime,
then so does the actual set of primes above the base maximal ideal. -/
theorem integralClosure_primesOver_base_maximal_subsingleton_of_fiber_subsingleton
    [Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    Subsingleton
      (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) := by
  constructor
  intro P Q
  let e := PrimeSpectrum.primesOverOrderIsoFiber
    base.toDVF.valuationSubring (integralClosureIntegers base target) base.maximalIdeal
  exact e.injective (Subsingleton.elim (e P) (e Q))

omit [base.valuation.HasExtension target.valuation] in
/-- If the residue fiber over the base maximal ideal has at most one prime,
then the primes of the actual integral closure over the base maximal ideal form
a singleton. -/
theorem integralClosure_primesOver_base_maximal_eq_singleton_of_fiber_subsingleton
    [Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    ∃ P : Ideal (integralClosureIntegers base target),
      Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target) = {P} := by
  let : Subsingleton
      (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) :=
    (integralClosure_primesOver_base_maximal_subsingleton_of_fiber_subsingleton base target)
  rcases (integralClosure_primesOver_base_maximal_nonempty base target) with ⟨P⟩
  refine ⟨P, Set.eq_singleton_iff_unique_mem.mpr ⟨P.2, ?_⟩⟩
  intro Q hQ
  exact congrArg Subtype.val
    (Subsingleton.elim
      (⟨Q, hQ⟩ :
        Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) P)

omit [base.valuation.HasExtension target.valuation] in
/-- The actual integral closure is a fraction ring for the finite field
extension. -/
theorem integralClosure_isFractionRing :
    IsFractionRing (integralClosureIntegers base target) L := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  exact
    (show IsFractionRing (integralClosure base.toDVF.valuationSubring L) L from
      integralClosure.isFractionRing_of_finite_extension K L)

omit [base.valuation.HasExtension target.valuation] in
/-- If the actual integral closure is a valuation ring, then it satisfies the
valuative dichotomy inside the extension field.

This is the local/DVR-oriented bridge for the Henselian frontier: after proving
that the finite integral closure is local, one can obtain a valuation-ring
instance and feed this theorem into the finite-separable uniqueness API. -/
theorem integralClosure_mem_or_inv_of_integralClosure_valuationRing
    [ValuationRing (integralClosureIntegers base target)] :
    ∀ z : L,
      z ∈ (integralClosure base.toDVF.valuationSubring L).toSubring ∨
        z⁻¹ ∈ (integralClosure base.toDVF.valuationSubring L).toSubring := by
  let : IsFractionRing (integralClosureIntegers base target) L :=
    (integralClosure_isFractionRing base target)
  intro z
  rcases ValuationRing.isInteger_or_isInteger
      (R := (integralClosureIntegers base target)) (K := L) z with hz | hz
  · left
    rcases hz with ⟨y, hy⟩
    rw [← hy]
    exact y.2
  · right
    rcases hz with ⟨y, hy⟩
    rw [← hy]
    exact y.2

omit [base.valuation.HasExtension target.valuation] in
/-- If the base valuation ring is used as a fraction ring for `K` and the field
extension is separable, the integral closure is Dedekind. -/
theorem integralClosure_isDedekindDomain
    [IsFractionRing base.toDVF.valuationSubring K] [Algebra.IsSeparable K L] :
    IsDedekindDomain (integralClosureIntegers base target) := by
  exact
    (show IsDedekindDomain (integralClosure base.toDVF.valuationSubring L) from
      integralClosure.isDedekindDomain base.toDVF.valuationSubring K L)

omit [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] in
/-- If the primes of the actual integral closure over the base maximal ideal
form a singleton, then the actual integral closure is local.

For integral extensions, every maximal ideal upstairs lies over a maximal ideal
downstairs.  Since the base valuation ring is local, all maximal ideals upstairs
therefore lie over `base.maximalIdeal`; the singleton hypothesis makes the
maximal spectrum upstairs a singleton. -/
theorem integralClosure_isLocalRing_of_primesOver_base_maximal_eq_singleton
    (P : Ideal (integralClosureIntegers base target))
    (hP :
      Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target) = {P}) :
    IsLocalRing (integralClosureIntegers base target) := by
  let : Algebra.IsIntegral base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_isIntegral base target)
  have hPmem : P ∈ Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target) := by
    rw [hP]
    exact Set.mem_singleton P
  let : Nonempty (MaximalSpectrum (integralClosureIntegers base target)) :=
    ⟨⟨P, Ideal.isMaximal_of_mem_primesOver hPmem⟩⟩
  have hsub :
      Subsingleton (MaximalSpectrum (integralClosureIntegers base target)) := by
    constructor
    intro M N
    apply MaximalSpectrum.ext
    have hMcomap :
        (M.asIdeal.comap
            (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target))) =
          base.maximalIdeal :=
      IsLocalRing.eq_maximalIdeal
        (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
          (R := base.toDVF.valuationSubring)
          (S := (integralClosureIntegers base target)) M.asIdeal)
    have hNcomap :
        (N.asIdeal.comap
            (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target))) =
          base.maximalIdeal :=
      IsLocalRing.eq_maximalIdeal
        (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
          (R := base.toDVF.valuationSubring)
          (S := (integralClosureIntegers base target)) N.asIdeal)
    have hMmem :
        M.asIdeal ∈ Ideal.primesOver base.maximalIdeal
          (integralClosureIntegers base target) :=
      ⟨M.isMaximal.isPrime, ⟨hMcomap.symm⟩⟩
    have hNmem :
        N.asIdeal ∈ Ideal.primesOver base.maximalIdeal
          (integralClosureIntegers base target) :=
      ⟨N.isMaximal.isPrime, ⟨hNcomap.symm⟩⟩
    have hMeq : M.asIdeal = P := by
      simpa [hP] using hMmem
    have hNeq : N.asIdeal = P := by
      simpa [hP] using hNmem
    exact hMeq.trans hNeq.symm
  exact IsLocalRing.of_singleton_maximalSpectrum

omit [base.valuation.HasExtension target.valuation] in
/-- If the residue fiber over the base maximal ideal has at most one prime,
then the actual integral closure is local. -/
theorem integralClosure_isLocalRing_of_base_maximal_fiber_subsingleton
    [Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    IsLocalRing (integralClosureIntegers base target) := by
  rcases
      (integralClosure_primesOver_base_maximal_eq_singleton_of_fiber_subsingleton
        base target) with
    ⟨P, hP⟩
  exact (integralClosure_isLocalRing_of_primesOver_base_maximal_eq_singleton base target) P hP

omit [base.valuation.HasExtension target.valuation] in
/-- Henselian-facing localness criterion via idempotent lifting in the finite
residue fiber. -/
theorem integralClosure_isLocalRing_of_base_maximal_fiber_idempotents_lift
    [Algebra.IsSeparable K L]
    (hlift :
      ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
        IsIdempotentElem e →
          ∃ b : (integralClosureIntegers base target),
            IsIdempotentElem b ∧
              Algebra.TensorProduct.includeRight b = e) :
    IsLocalRing (integralClosureIntegers base target) := by
  let : Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) :=
    (integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift base target) hlift
  exact (integralClosure_isLocalRing_of_base_maximal_fiber_subsingleton base target)

omit [base.valuation.HasExtension target.valuation] in
/-- A local actual integral closure in a finite separable extension of a complete
DVF is a valuation ring.

The Henselian frontier can therefore aim only at localness of the finite
integral closure.  Dedekind theory and mathlib's local Noetherian-domain TFAE
then turn that local integral closure into a valuation ring, giving the
valuative dichotomy needed by the finite-extension uniqueness bridge. -/
theorem integralClosure_valuationRing_of_isLocalRing
    [Algebra.IsSeparable K L]
    [IsLocalRing (integralClosureIntegers base target)] :
    ValuationRing (integralClosureIntegers base target) := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base_valuationSubring_isFractionRing (K := K) base
  let : IsIntegrallyClosed base.toDVF.valuationSubring :=
    base_valuationSubring_isIntegrallyClosed (K := K) base
  let : IsNoetherianRing base.toDVF.valuationSubring :=
    base_valuationSubring_isNoetherianRing (K := K) base
  let : IsDomain (integralClosureIntegers base target) := by
    exact inferInstanceAs
      (IsDomain (integralClosure base.toDVF.valuationSubring L))
  let : IsDedekindDomain (integralClosureIntegers base target) :=
    (integralClosure_isDedekindDomain base target)
  exact
    ((tfae_of_isNoetherianRing_of_isLocalRing_of_isDomain
      (integralClosureIntegers base target)).out 2 1).mp
      (show IsDedekindDomain (integralClosureIntegers base target) from inferInstance)

omit [base.valuation.HasExtension target.valuation] in
/-- If the actual integral closure is local, then it satisfies the valuative
dichotomy inside the extension field. -/
theorem integralClosure_mem_or_inv_of_isLocalRing
    [Algebra.IsSeparable K L]
    [IsLocalRing (integralClosureIntegers base target)] :
    ∀ z : L,
      z ∈ (integralClosure base.toDVF.valuationSubring L).toSubring ∨
        z⁻¹ ∈ (integralClosure base.toDVF.valuationSubring L).toSubring := by
  let : ValuationRing (integralClosureIntegers base target) :=
    (integralClosure_valuationRing_of_isLocalRing base target)
  exact (integralClosure_mem_or_inv_of_integralClosure_valuationRing base target)

/-- The chosen target valuation ring remains a DVR. -/
theorem target_valuationSubring_isDiscreteValuationRing
     :
    IsDiscreteValuationRing target.toDVF.valuationSubring :=
  target.valuationSubring_isDiscreteValuationRing

end ValuedExtension

namespace ValuedExtension.Henselian

variable {K : Type u} {L : Type w} [Field K] [Field L]
variable [Algebra K L] [FiniteDimensional K L]
variable (base : HenselianDVF.{u, v} K) (target : HenselianDVF.{w, x} L)
variable [base.toDVF.valuation.HasExtension target.toDVF.valuation]

/-- The actual integral closure of the base valuation ring in the extension
field, for a Henselian valued extension. -/
abbrev integralClosureIntegers (base : HenselianDVF.{u, v} K)
    (_target : HenselianDVF.{w, x} L) : Type _ :=
  integralClosure base.toDVF.valuationSubring L

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The actual integral closure is an `IsIntegralClosure`. -/
theorem integralClosure_isIntegralClosure :
    IsIntegralClosure (integralClosureIntegers base target) base.toDVF.valuationSubring L := by
  exact inferInstanceAs
    (IsIntegralClosure (integralClosure base.toDVF.valuationSubring L)
      base.toDVF.valuationSubring L)

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The actual integral closure is integral over the base valuation ring. -/
theorem integralClosure_isIntegral :
    Algebra.IsIntegral base.toDVF.valuationSubring (integralClosureIntegers base target) := by
  exact inferInstanceAs
    (Algebra.IsIntegral base.toDVF.valuationSubring
      (integralClosure base.toDVF.valuationSubring L))

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The algebra map from the base valuation ring into the actual integral
closure is injective. -/
theorem integralClosure_algebraMap_injective
     :
    Function.Injective
      (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)) := by
  intro x y hxy
  apply Subtype.ext
  apply FaithfulSMul.algebraMap_injective K L
  exact congrArg (fun z : (integralClosureIntegers base target) => (z : L)) hxy

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The actual integral closure is faithful over the base valuation ring. -/
theorem integralClosure_faithfulSMul :
    FaithfulSMul base.toDVF.valuationSubring (integralClosureIntegers base target) :=
  (faithfulSMul_iff_algebraMap_injective
    base.toDVF.valuationSubring (integralClosureIntegers base target)).mpr
    (integralClosure_algebraMap_injective base target)

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- In a finite separable field extension, the actual integral closure is
module-finite over the base Henselian valuation ring. -/
theorem moduleFinite_integralClosureIntegers
    [Algebra.IsSeparable K L] :
    Module.Finite base.toDVF.valuationSubring (integralClosureIntegers base target) := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base.toDVF.valuationSubring_isFractionRing
  let : IsIntegrallyClosed base.toDVF.valuationSubring :=
    base.toDVF.valuationSubring_isIntegrallyClosed
  let : IsNoetherianRing base.toDVF.valuationSubring :=
    base.toDVF.valuationSubring_isNoetherianRing
  exact
    (show Module.Finite base.toDVF.valuationSubring
        (integralClosure base.toDVF.valuationSubring L) from
      IsIntegralClosure.finite base.toDVF.valuationSubring K L
        (integralClosure base.toDVF.valuationSubring L))

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- In a finite separable field extension, the actual integral closure is
quasi-finite over the base Henselian valuation ring. -/
theorem integralClosure_quasiFinite
    [Algebra.IsSeparable K L] :
    Algebra.QuasiFinite base.toDVF.valuationSubring (integralClosureIntegers base target) := by
  let : Module.Finite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (moduleFinite_integralClosureIntegers base target)
  infer_instance

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The residue fiber of the finite actual integral closure over the base
maximal ideal is Artinian. -/
theorem integralClosure_base_maximal_fiber_isArtinianRing
    [Algebra.IsSeparable K L] :
    IsArtinianRing (base.maximalIdeal.Fiber (integralClosureIntegers base target)) := by
  let : Algebra.QuasiFinite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_quasiFinite base target)
  infer_instance

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- For the actual integral closure, the kernel of the residue-fiber
includeRight map is the ideal generated by the base maximal ideal. -/
theorem integralClosure_base_maximal_fiber_includeRight_ker_eq_maximalIdeal_map
     :
    RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) =
      base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)) := by
  simpa using
    (ValuedExtension.maximalIdeal_fiber_includeRight_ker_eq_maximalIdeal_map
      (R := base.toDVF.valuationSubring) (S := (integralClosureIntegers base target)))

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The ideal generated by the base maximal ideal lies in the module Jacobson
radical of the actual integral closure after restricting scalars to the base.

This is the Nakayama/Jacobson component of the desired finite-algebra
Henselian-pair transfer, specialized to the Henselian-DVF integral closure. -/
theorem integralClosure_base_maximal_map_restrictScalars_le_module_jacobson
     :
    (base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring
          (integralClosureIntegers base target))).restrictScalars
      base.toDVF.valuationSubring ≤
        Module.jacobson base.toDVF.valuationSubring (integralClosureIntegers base target) :=
  ideal_map_restrictScalars_le_module_jacobson_of_henselianRing

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- In a finite separable Henselian extension, the ideal generated by the base
maximal ideal lies in the Jacobson radical of the actual integral closure. -/
theorem integralClosure_base_maximal_map_le_jacobson_bot
    [Algebra.IsSeparable K L] :
    base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)) ≤
      Ideal.jacobson (⊥ : Ideal (integralClosureIntegers base target)) := by
  let : Module.Finite base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (moduleFinite_integralClosureIntegers base target)
  exact ideal_map_le_jacobson_bot_of_henselianRing_of_moduleFinite

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- Idempotents in the actual integral closure in the extension field are
trivial. -/
theorem integralClosure_idempotent_eq_zero_or_one
    (e : (integralClosureIntegers base target))
    (he : IsIdempotentElem e) :
    e = 0 ∨ e = 1 := by
  let : IsDomain (integralClosureIntegers base target) := by
    exact inferInstanceAs
      (IsDomain (integralClosure base.toDVF.valuationSubring L))
  exact IsIdempotentElem.iff_eq_zero_or_one.mp he

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If every idempotent of the residue fiber over the base maximal ideal lifts
to an idempotent of the actual integral closure, then that fiber has at most
one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift
    [Algebra.IsSeparable K L]
    (hlift :
      ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
        IsIdempotentElem e →
          ∃ b : (integralClosureIntegers base target),
            IsIdempotentElem b ∧
              Algebra.TensorProduct.includeRight b = e) :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  let : IsArtinianRing
      (base.maximalIdeal.Fiber (integralClosureIntegers base target)) :=
    (integralClosure_base_maximal_fiber_isArtinianRing base target)
  refine ValuedExtension.primeSpectrum_subsingleton_of_isArtinianRing_of_idempotents_trivial ?_
  intro e he
  rcases hlift e he with ⟨b, hbidem, hbmap⟩
  rcases (integralClosure_idempotent_eq_zero_or_one base target) b hbidem with rfl | rfl
  · left
    rw [← hbmap]
    simp
  · right
    rw [← hbmap]
    exact (Algebra.TensorProduct.includeRight :
      (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
        base.maximalIdeal.Fiber (integralClosureIntegers base target)).map_one

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- Henselian-kernel form of idempotent lifting for the residue fiber of the
actual integral closure. -/
theorem
integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_surjective_henselianRing_ker
    (hsurj :
      Function.Surjective
        (Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
      IsIdempotentElem e →
        ∃ b : (integralClosureIntegers base target),
          IsIdempotentElem b ∧
            Algebra.TensorProduct.includeRight b = e := by
  intro e he
  let φ : (integralClosureIntegers base target) →+*
      base.maximalIdeal.Fiber (integralClosureIntegers base target) :=
    (Algebra.TensorProduct.includeRight :
      (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
        base.maximalIdeal.Fiber (integralClosureIntegers base target))
  have hsurjφ : Function.Surjective φ := by
    simpa [φ] using hsurj
  rcases exists_idempotent_lift_of_surjective_henselianRing_ker
      φ hsurjφ e he with
    ⟨b, hbidem, hbmap⟩
  exact ⟨b, hbidem, by simpa [φ] using hbmap⟩

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the residue-fiber `includeRight` map has Henselian kernel and is
surjective, then the fiber has at most one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_includeRight_surjective_henselianRing_ker
    [Algebra.IsSeparable K L]
    (hsurj :
      Function.Surjective
        (Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  refine
    (integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift base target) ?_
  exact (
integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_surjective_henselianRing_ker
    base target) hsurj

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- Henselian-kernel idempotent lifting for the residue fiber of the actual
integral closure.  The `includeRight` map is automatically surjective because
the base valuation ring is local. -/
theorem integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_henselianRing_ker
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
      IsIdempotentElem e →
        ∃ b : (integralClosureIntegers base target),
          IsIdempotentElem b ∧
            Algebra.TensorProduct.includeRight b = e := by
  refine (
integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_surjective_henselianRing_ker
    base target) ?_
  simpa using
    (ValuedExtension.maximalIdeal_fiber_includeRight_surjective
      (R := base.toDVF.valuationSubring) (S := (integralClosureIntegers base target)))

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the `includeRight` map to the residue fiber has Henselian kernel, then
the fiber has at most one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_includeRight_henselianRing_ker
    [Algebra.IsSeparable K L]
    [HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  refine
    (integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift base target) ?_
  exact
    (integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_henselianRing_ker
      base target)

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- Idempotent lifting from the natural Henselian-pair ideal
`base.maximalIdeal.map` in the actual integral closure. -/
theorem integralClosure_base_maximal_fiber_idempotents_lift_of_henselianRing_maximalIdeal_map
    [HenselianRing (integralClosureIntegers base target)
      (base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)))] :
    ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
      IsIdempotentElem e →
        ∃ b : (integralClosureIntegers base target),
          IsIdempotentElem b ∧
            Algebra.TensorProduct.includeRight b = e := by
  let : HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
    rw [(integralClosure_base_maximal_fiber_includeRight_ker_eq_maximalIdeal_map base target)]
    infer_instance
  exact
    (integralClosure_base_maximal_fiber_idempotents_lift_of_includeRight_henselianRing_ker
      base target)

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the ideal generated by the base maximal ideal is Henselian in the actual
integral closure, then the residue fiber has at most one prime. -/
theorem integralClosure_base_maximal_fiber_subsingleton_of_henselianRing_maximalIdeal_map
    [Algebra.IsSeparable K L]
    [HenselianRing (integralClosureIntegers base target)
      (base.maximalIdeal.map
        (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target)))] :
    Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
  let : HenselianRing (integralClosureIntegers base target)
      (RingHom.ker
        ((Algebra.TensorProduct.includeRight :
          (integralClosureIntegers base target) →ₐ[base.toDVF.valuationSubring]
            base.maximalIdeal.Fiber (integralClosureIntegers base target)) :
          (integralClosureIntegers base target) →+*
            base.maximalIdeal.Fiber (integralClosureIntegers base target))) := by
    rw [(integralClosure_base_maximal_fiber_includeRight_ker_eq_maximalIdeal_map base target)]
    infer_instance
  exact
    (integralClosure_base_maximal_fiber_subsingleton_of_includeRight_henselianRing_ker base target)

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The actual integral closure has at least one prime above the base maximal
ideal. -/
theorem integralClosure_primesOver_base_maximal_nonempty
     :
    Nonempty (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) := by
  let : Algebra.IsIntegral base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_isIntegral base target)
  let : FaithfulSMul base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_faithfulSMul base target)
  rcases Ideal.exists_maximal_ideal_liesOver_of_isIntegral
      (S := (integralClosureIntegers base target)) base.maximalIdeal with
    ⟨P, hPmax, hPover⟩
  exact ⟨⟨P, hPmax.isPrime, hPover⟩⟩

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the residue fiber over the base maximal ideal has at most one prime,
then so does the actual set of primes above the base maximal ideal. -/
theorem integralClosure_primesOver_base_maximal_subsingleton_of_fiber_subsingleton
    [Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    Subsingleton
      (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) := by
  constructor
  intro P Q
  let e := PrimeSpectrum.primesOverOrderIsoFiber
    base.toDVF.valuationSubring (integralClosureIntegers base target) base.maximalIdeal
  exact e.injective (Subsingleton.elim (e P) (e Q))

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the residue fiber over the base maximal ideal has at most one prime,
then the primes of the actual integral closure over the base maximal ideal form
a singleton. -/
theorem integralClosure_primesOver_base_maximal_eq_singleton_of_fiber_subsingleton
    [Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    ∃ P : Ideal (integralClosureIntegers base target),
      Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target) = {P} := by
  let : Subsingleton
      (Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) :=
    (integralClosure_primesOver_base_maximal_subsingleton_of_fiber_subsingleton base target)
  rcases (integralClosure_primesOver_base_maximal_nonempty base target) with ⟨P⟩
  refine ⟨P, Set.eq_singleton_iff_unique_mem.mpr ⟨P.2, ?_⟩⟩
  intro Q hQ
  exact congrArg Subtype.val
    (Subsingleton.elim
      (⟨Q, hQ⟩ :
        Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target)) P)

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- The actual integral closure is a fraction ring for the finite field
extension. -/
theorem integralClosure_isFractionRing :
    IsFractionRing (integralClosureIntegers base target) L := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base.toDVF.valuationSubring_isFractionRing
  change IsFractionRing (integralClosure base.toDVF.valuationSubring L) L
  exact integralClosure.isFractionRing_of_finite_extension K L

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the actual integral closure is a valuation ring, then it satisfies the
valuative dichotomy inside the extension field. -/
theorem integralClosure_mem_or_inv_of_integralClosure_valuationRing
    [ValuationRing (integralClosureIntegers base target)] :
    ∀ z : L,
      z ∈ (integralClosure base.toDVF.valuationSubring L).toSubring ∨
        z⁻¹ ∈ (integralClosure base.toDVF.valuationSubring L).toSubring := by
  let : IsFractionRing (integralClosureIntegers base target) L :=
    (integralClosure_isFractionRing base target)
  intro z
  rcases ValuationRing.isInteger_or_isInteger
      (R := (integralClosureIntegers base target)) (K := L) z with hz | hz
  · left
    rcases hz with ⟨y, hy⟩
    rw [← hy]
    exact y.2
  · right
    rcases hz with ⟨y, hy⟩
    rw [← hy]
    exact y.2

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the base valuation ring is used as a fraction ring for `K` and the field
extension is separable, the integral closure is Dedekind. -/
theorem integralClosure_isDedekindDomain
    [IsFractionRing base.toDVF.valuationSubring K] [Algebra.IsSeparable K L] :
    IsDedekindDomain (integralClosureIntegers base target) := by
  change IsDedekindDomain (integralClosure base.toDVF.valuationSubring L)
  exact integralClosure.isDedekindDomain base.toDVF.valuationSubring K L

omit [FiniteDimensional K L]
    [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the primes of the actual integral closure over the base maximal ideal
form a singleton, then the actual integral closure is local. -/
theorem integralClosure_isLocalRing_of_primesOver_base_maximal_eq_singleton
    (P : Ideal (integralClosureIntegers base target))
    (hP :
      Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target) = {P}) :
    IsLocalRing (integralClosureIntegers base target) := by
  let : Algebra.IsIntegral base.toDVF.valuationSubring (integralClosureIntegers base target) :=
    (integralClosure_isIntegral base target)
  have hPmem : P ∈ Ideal.primesOver base.maximalIdeal (integralClosureIntegers base target) := by
    rw [hP]
    exact Set.mem_singleton P
  let : Nonempty (MaximalSpectrum (integralClosureIntegers base target)) :=
    ⟨⟨P, Ideal.isMaximal_of_mem_primesOver hPmem⟩⟩
  have hsub :
      Subsingleton (MaximalSpectrum (integralClosureIntegers base target)) := by
    constructor
    intro M N
    apply MaximalSpectrum.ext
    have hMcomap :
        (M.asIdeal.comap
            (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target))) =
          base.maximalIdeal :=
      IsLocalRing.eq_maximalIdeal
        (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
          (R := base.toDVF.valuationSubring)
          (S := (integralClosureIntegers base target)) M.asIdeal)
    have hNcomap :
        (N.asIdeal.comap
            (algebraMap base.toDVF.valuationSubring (integralClosureIntegers base target))) =
          base.maximalIdeal :=
      IsLocalRing.eq_maximalIdeal
        (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal
          (R := base.toDVF.valuationSubring)
          (S := (integralClosureIntegers base target)) N.asIdeal)
    have hMmem :
        M.asIdeal ∈ Ideal.primesOver base.maximalIdeal
          (integralClosureIntegers base target) :=
      ⟨M.isMaximal.isPrime, ⟨hMcomap.symm⟩⟩
    have hNmem :
        N.asIdeal ∈ Ideal.primesOver base.maximalIdeal
          (integralClosureIntegers base target) :=
      ⟨N.isMaximal.isPrime, ⟨hNcomap.symm⟩⟩
    have hMeq : M.asIdeal = P := by
      simpa [hP] using hMmem
    have hNeq : N.asIdeal = P := by
      simpa [hP] using hNmem
    exact hMeq.trans hNeq.symm
  exact IsLocalRing.of_singleton_maximalSpectrum

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the residue fiber over the base maximal ideal has at most one prime,
then the actual integral closure is local. -/
theorem integralClosure_isLocalRing_of_base_maximal_fiber_subsingleton
    [Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target)))] :
    IsLocalRing (integralClosureIntegers base target) := by
  rcases
      (integralClosure_primesOver_base_maximal_eq_singleton_of_fiber_subsingleton
        base target) with
    ⟨P, hP⟩
  exact (integralClosure_isLocalRing_of_primesOver_base_maximal_eq_singleton base target) P hP

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- Henselian-facing localness criterion via idempotent lifting in the finite
residue fiber. -/
theorem integralClosure_isLocalRing_of_base_maximal_fiber_idempotents_lift
    [Algebra.IsSeparable K L]
    (hlift :
      ∀ e : base.maximalIdeal.Fiber (integralClosureIntegers base target),
        IsIdempotentElem e →
          ∃ b : (integralClosureIntegers base target),
            IsIdempotentElem b ∧
              Algebra.TensorProduct.includeRight b = e) :
    IsLocalRing (integralClosureIntegers base target) := by
  let : Subsingleton
      (PrimeSpectrum (base.maximalIdeal.Fiber (integralClosureIntegers base target))) :=
    (integralClosure_base_maximal_fiber_subsingleton_of_idempotents_lift base target) hlift
  exact (integralClosure_isLocalRing_of_base_maximal_fiber_subsingleton base target)

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- A local actual integral closure in a finite separable extension of a
Henselian DVF is a valuation ring. -/
theorem integralClosure_valuationRing_of_isLocalRing
    [Algebra.IsSeparable K L]
    [IsLocalRing (integralClosureIntegers base target)] :
    ValuationRing (integralClosureIntegers base target) := by
  let : IsFractionRing base.toDVF.valuationSubring K :=
    base.toDVF.valuationSubring_isFractionRing
  let : IsIntegrallyClosed base.toDVF.valuationSubring :=
    base.toDVF.valuationSubring_isIntegrallyClosed
  let : IsNoetherianRing base.toDVF.valuationSubring :=
    base.toDVF.valuationSubring_isNoetherianRing
  let : IsDomain (integralClosureIntegers base target) := by
    change IsDomain (integralClosure base.toDVF.valuationSubring L)
    infer_instance
  let : IsDedekindDomain (integralClosureIntegers base target) :=
    (integralClosure_isDedekindDomain base target)
  exact
    ((tfae_of_isNoetherianRing_of_isLocalRing_of_isDomain
      (integralClosureIntegers base target)).out 2 1).mp
      (show IsDedekindDomain (integralClosureIntegers base target) from inferInstance)

omit [base.toDVF.valuation.HasExtension target.toDVF.valuation] in
/-- If the actual integral closure is local, then it satisfies the valuative
dichotomy inside the extension field. -/
theorem integralClosure_mem_or_inv_of_isLocalRing
    [Algebra.IsSeparable K L]
    [IsLocalRing (integralClosureIntegers base target)] :
    ∀ z : L,
      z ∈ (integralClosure base.toDVF.valuationSubring L).toSubring ∨
        z⁻¹ ∈ (integralClosure base.toDVF.valuationSubring L).toSubring := by
  let : ValuationRing (integralClosureIntegers base target) :=
    (integralClosure_valuationRing_of_isLocalRing base target)
  exact (integralClosure_mem_or_inv_of_integralClosure_valuationRing base target)

/-- The chosen Henselian target valuation ring remains a DVR. -/
theorem target_valuationSubring_isDiscreteValuationRing
     :
    IsDiscreteValuationRing target.toDVF.valuationSubring :=
  target.valuationSubring_isDiscreteValuationRing

end ValuedExtension.Henselian
end DiscreteValuationField

end

end ValuationTheory
