import ClassFieldTheory.KummerTheory.Concrete.SUnitPreparation.SUnitPowerQuotient
import GaloisCohomology.Kummer.Concrete.SUnitPreparation.PrimePowerKernelCoordinates

set_option autoImplicit false

/-!
# The full S-unit Kummer extension

Construction, finite generation, Galois structure, cardinality, and coordinates for the Kummer extension generated by all `S`-unit roots.
-/

open scoped NumberField Classical IsMulCommutative NNReal ValuativeRel
open NumberField IsDedekindDomain
open LocalFieldTheory

noncomputable section

namespace KummerTheory

variable {K : Type*} [Field K]
    [numberFieldK : NumberField K]

/-- The actual field `N = K(√[n]{Kˢ})` in a fixed separable closure. -/
def fullSUnitKummerExtension
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    (n : ℕ+)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    IntermediateField K Omega :=
  KummerTheory.kummerRadicalExtension
    (K := K) (Omega := Omega) n
    (fullSUnitKummerSubgroup (K := K) n S).1

/-- Every root used to generate the full `S`-unit Kummer extension can be
rescaled by an element of `Kˣ` to become the root of an actual `S`-unit.
The rescaling does not change the simple intermediate field that it
generates.  This is the source-producing step needed to apply the local
unramified Kummer criterion to every generator of the full extension. -/
theorem exists_sUnitRoot_adjoin_eq_of_mem_fullSUnitKummerRootSet
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    (n : ℕ+)
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    {beta : Omega}
    (hbeta :
      beta ∈
        KummerTheory.kummerRootSet
          (K := K) (Omega := Omega) n
          (fullSUnitKummerSubgroup (K := K) n S).1) :
    ∃ (u : SUnitGroup (K := K) S) (alpha : Omegaˣ),
      alpha ^ (n : ℕ) =
          Units.map (algebraMap K Omega).toMonoidHom u.1 ∧
        IntermediateField.adjoin K {(alpha : Omega)} =
          IntermediateField.adjoin K {beta} := by
  have hbetaNe : beta ≠ 0 :=
    KummerTheory.kummerRootSet_ne_zero
      n (fullSUnitKummerSubgroup (K := K) n S).1 hbeta
  obtain ⟨a, hbetaPow⟩ := hbeta
  obtain ⟨u, hu, z, hz, huz⟩ :=
    Subgroup.mem_sup.mp a.property
  obtain ⟨c, hc⟩ :=
    (KummerTheory.mem_unitNthPowersSubgroup_iff n).mp hz
  let uS : SUnitGroup (K := K) S := ⟨u, hu⟩
  let betaUnit : Omegaˣ :=
    Units.mk0 beta hbetaNe
  let cOmega : Omegaˣ :=
    Units.map (algebraMap K Omega).toMonoidHom c
  let alpha : Omegaˣ := betaUnit / cOmega
  have hbetaUnitPow :
      betaUnit ^ (n : ℕ) =
        Units.map (algebraMap K Omega).toMonoidHom a.1 := by
    apply Units.ext
    exact hbetaPow
  have hcOmegaPow :
      cOmega ^ (n : ℕ) =
        Units.map (algebraMap K Omega).toMonoidHom z := by
    dsimp only [cOmega]
    rw [← map_pow, hc]
  have hau : a.1 / z = u := by
    rw [← huz]
    simp
  have halphaPow :
      alpha ^ (n : ℕ) =
        Units.map (algebraMap K Omega).toMonoidHom u := by
    dsimp only [alpha]
    rw [div_pow, hbetaUnitPow, hcOmegaPow, ← map_div, hau]
  refine ⟨uS, alpha, halphaPow, ?_⟩
  let Rbeta := IntermediateField.adjoin K {beta}
  let Ralpha := IntermediateField.adjoin K {(alpha : Omega)}
  have halphaMem : (alpha : Omega) ∈ Rbeta := by
    have halphaVal :
        (alpha : Omega) =
          beta / algebraMap K Omega (c : K) := by
      simp [alpha, betaUnit, cOmega]
    rw [halphaVal]
    exact Rbeta.div_mem
      (IntermediateField.subset_adjoin K {beta}
        (Set.mem_singleton beta))
      (Rbeta.algebraMap_mem (c : K))
  have hrecover : alpha * cOmega = betaUnit :=
    div_mul_cancel betaUnit cOmega
  have hbetaMem : beta ∈ Ralpha := by
    have hrecoverVal :
        (alpha : Omega) *
            algebraMap K Omega (c : K) = beta := by
      simpa [betaUnit, cOmega] using
        congrArg Units.val hrecover
    rw [← hrecoverVal]
    exact Ralpha.mul_mem
      (IntermediateField.subset_adjoin K {(alpha : Omega)}
        (Set.mem_singleton (alpha : Omega)))
      (Ralpha.algebraMap_mem (c : K))
  apply le_antisymm
  · apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact halphaMem
  · apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact hbetaMem

/-- The field `N = K(√[n]{Kˢ})` is Galois over `K`. -/
theorem fullSUnitKummerExtension_isGalois
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    IsGalois K
      (fullSUnitKummerExtension (K := K) (Omega := Omega) n S) :=
  KummerTheory.kummerRadicalExtension_isGalois n
    (fullSUnitKummerSubgroup (K := K) n S).1

/-- The Galois group of `N/K` is finite. -/
theorem finite_fullSUnitKummerExtension_galois
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Finite
      Gal(fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S/K) := by
  let _ : NeZero (n : ℕ) := ⟨n.ne_zero⟩
  let E :=
    fullSUnitKummerExtension (K := K) (Omega := Omega) n S
  let Q :=
    KummerTheory.RestrictedRadicalQuotient
      n (fullSUnitKummerSubgroup (K := K) n S)
  let _ : Finite Q :=
    finite_fullSUnitRadicalQuotient (K := K) n S
  let _ : Finite (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ)) :=
    Finite.of_injective
      (fun chi : Q →* KummerTheory.nthRootsSubgroup E (n : ℕ) =>
        (chi : Q → KummerTheory.nthRootsSubgroup E (n : ℕ)))
      DFunLike.coe_injective
  let e :
      Gal(E/K) ≃*
        (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ)) :=
    KummerTheory.kummerRadicalExtensionRestrictedTransposeMulEquiv
      n hn hmu (fullSUnitKummerSubgroup (K := K) n S)
  exact Finite.of_equiv
    (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ))
    e.symm.toEquiv

/-- The extension `N = K(√[n]{Kˢ})` is finite-dimensional. -/
theorem fullSUnitKummerExtension_finiteDimensional
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    FiniteDimensional K
      (fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S) := by
  let E :=
    fullSUnitKummerExtension (K := K) (Omega := Omega) n S
  let _ : IsGalois K E :=
    fullSUnitKummerExtension_isGalois
      (K := K) (Omega := Omega) n S
  let _ : Finite Gal(E/K) :=
    finite_fullSUnitKummerExtension_galois
      (K := K) (Omega := Omega) n hn hmu S
  exact IsGalois.finiteDimensional_of_finite K E

/-- A finite set of the actual Kummer roots generates the full `S`-unit
Kummer extension.  Finiteness is obtained from Kummer duality, and the
finite root set is extracted from a primitive element of the resulting
finite separable extension. -/
theorem exists_finset_fullSUnitKummerRootSet_adjoin_eq
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    ∃ T : Finset Omega,
      (T : Set Omega) ⊆
          KummerTheory.kummerRootSet
            (K := K) (Omega := Omega) n
            (fullSUnitKummerSubgroup (K := K) n S).1 ∧
        IntermediateField.adjoin K (T : Set Omega) =
          fullSUnitKummerExtension
            (K := K) (Omega := Omega) n S := by
  let E :=
    fullSUnitKummerExtension
      (K := K) (Omega := Omega) n S
  let _ : IsGalois K E :=
    fullSUnitKummerExtension_isGalois
      (K := K) (Omega := Omega) n S
  let _ : FiniteDimensional K E :=
    fullSUnitKummerExtension_finiteDimensional
      (K := K) (Omega := Omega) n hn hmu S
  obtain ⟨theta, htheta⟩ :=
    Field.exists_primitive_element K E
  obtain ⟨T, hT, hthetaT⟩ :=
    KummerTheory.exists_finset_kummerRootSet_of_mem_kummerRadicalExtension
      n (fullSUnitKummerSubgroup (K := K) n S).1 theta.property
  refine ⟨T, hT, ?_⟩
  let R := IntermediateField.adjoin K (T : Set Omega)
  have hRE : R ≤ E := by
    apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    apply IntermediateField.subset_adjoin K
      (KummerTheory.kummerRootSet
        (K := K) (Omega := Omega) n
        (fullSUnitKummerSubgroup (K := K) n S).1)
    exact hT hx
  have hall : ∀ x : E, (x : Omega) ∈ R := by
    intro x
    have hx :
        x ∈ (⊤ : IntermediateField K E) :=
      trivial
    rw [← htheta] at hx
    induction hx using IntermediateField.adjoin_induction with
    | mem y hy =>
        have hy' : y = theta :=
          Set.mem_singleton_iff.mp hy
        subst y
        exact hthetaT
    | algebraMap a =>
        exact R.algebraMap_mem a
    | add x y hx hy ihx ihy =>
        exact R.add_mem ihx ihy
    | inv x hx ihx =>
        exact R.inv_mem ihx
    | mul x y hx hy ihx ihy =>
        exact R.mul_mem ihx ihy
  apply le_antisymm hRE
  intro x hx
  exact hall ⟨x, hx⟩

/-- The finite generating roots may be regarded as elements of the full
Kummer extension itself; internally they adjoin to the top field.  This is
the form consumed by finite inertia-restriction arguments. -/
theorem exists_finset_fullSUnitKummerExtensionRoots_adjoin_eq_top
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    let E :=
      fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S
    ∃ T : Finset E,
      (∀ x : E, x ∈ T →
        (x : Omega) ∈
          KummerTheory.kummerRootSet
            (K := K) (Omega := Omega) n
            (fullSUnitKummerSubgroup (K := K) n S).1) ∧
        IntermediateField.adjoin K (T : Set E) = ⊤ := by
  classical
  dsimp only
  let E :=
    fullSUnitKummerExtension
      (K := K) (Omega := Omega) n S
  let _ : IsGalois K E :=
    fullSUnitKummerExtension_isGalois
      (K := K) (Omega := Omega) n S
  let _ : FiniteDimensional K E :=
    fullSUnitKummerExtension_finiteDimensional
      (K := K) (Omega := Omega) n hn hmu S
  obtain ⟨theta, htheta⟩ :=
    Field.exists_primitive_element K E
  obtain ⟨T₀, hT₀, hthetaT₀⟩ :=
    KummerTheory.exists_finset_kummerRootSet_of_mem_kummerRadicalExtension
      n (fullSUnitKummerSubgroup (K := K) n S).1 theta.property
  have hT₀E :
      IntermediateField.adjoin K (T₀ : Set Omega) ≤ E := by
    apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    apply IntermediateField.subset_adjoin K
      (KummerTheory.kummerRootSet
        (K := K) (Omega := Omega) n
        (fullSUnitKummerSubgroup (K := K) n S).1)
    exact hT₀ hx
  let toE : ↥T₀ → E :=
    fun x => ⟨x.1,
      IntermediateField.subset_adjoin K
        (KummerTheory.kummerRootSet
          (K := K) (Omega := Omega) n
          (fullSUnitKummerSubgroup (K := K) n S).1)
        (hT₀ x.property)⟩
  let T : Finset E :=
    Finset.univ.image toE
  have hTroot :
      ∀ x : E, x ∈ T →
        (x : Omega) ∈
          KummerTheory.kummerRootSet
            (K := K) (Omega := Omega) n
            (fullSUnitKummerSubgroup (K := K) n S).1 := by
    intro x hx
    obtain ⟨y, _, hy⟩ :=
      Finset.mem_image.mp hx
    rw [← hy]
    exact hT₀ y.property
  refine ⟨T, hTroot, ?_⟩
  let R := IntermediateField.adjoin K (T : Set E)
  have hlift :
      ∀ (x : Omega)
        (hx :
          x ∈ IntermediateField.adjoin K (T₀ : Set Omega)),
        (⟨x, hT₀E hx⟩ : E) ∈ R := by
    intro x hx
    exact IntermediateField.adjoin_induction K
      (p := fun y hy => (⟨y, hT₀E hy⟩ : E) ∈ R)
      (fun y hy => by
        let yT : ↥T₀ := ⟨y, hy⟩
        have hyT : toE yT ∈ T := by
          apply Finset.mem_image.mpr
          exact ⟨yT, Finset.mem_univ yT, rfl⟩
        have hmem : toE yT ∈ R :=
          IntermediateField.subset_adjoin K
            (T : Set E) hyT
        simpa only [toE, yT] using hmem)
      (fun a => by
        exact R.algebraMap_mem a)
      (fun _ _ _ _ ihx ihy => by
        simpa using R.add_mem ihx ihy)
      (fun _ _ ihx => by
        convert R.inv_mem ihx using 1
        apply Subtype.ext
        rfl)
      (fun _ _ _ _ ihx ihy => by
        simpa using R.mul_mem ihx ihy)
      hx
  have hthetaR : theta ∈ R := by
    simpa using hlift theta.1 hthetaT₀
  apply top_unique
  rw [← htheta]
  apply IntermediateField.adjoin_le_iff.mpr
  intro x hx
  rw [Set.mem_singleton_iff] at hx
  subst x
  exact hthetaR

/-- The Galois group of `N/K` has cardinality `n ^ s`. -/
theorem card_fullSUnitKummerExtension_galois
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Nat.card
        Gal(fullSUnitKummerExtension
          (K := K) (Omega := Omega) n S/K) =
      (n : ℕ) ^ totalPlaceCard (K := K) S := by
  let _ : NeZero (n : ℕ) := ⟨n.ne_zero⟩
  let E :=
    fullSUnitKummerExtension (K := K) (Omega := Omega) n S
  let Q :=
    KummerTheory.RestrictedRadicalQuotient
      n (fullSUnitKummerSubgroup (K := K) n S)
  let e :
      Gal(E/K) ≃*
        (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ)) :=
    KummerTheory.kummerRadicalExtensionRestrictedTransposeMulEquiv
      n hn hmu (fullSUnitKummerSubgroup (K := K) n S)
  obtain ⟨dual⟩ :=
    KummerTheory.finiteNthRootsCharacterDuality
      (G := Q) (K := K) (L := E) n hmu
      (KummerTheory.restrictedRadicalQuotient_pow_eq_one
        n (fullSUnitKummerSubgroup (K := K) n S))
  calc
    Nat.card Gal(E/K) =
        Nat.card (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ)) :=
      Nat.card_congr e.toEquiv
    _ = Nat.card Q := Nat.card_congr dual.toEquiv
    _ = (n : ℕ) ^ totalPlaceCard (K := K) S :=
      card_fullSUnitRadicalQuotient (K := K) n S hmu

/-- Every automorphism of the full `S`-unit Kummer extension has
`n`-th power one. -/
theorem fullSUnitKummerExtension_galois_pow_eq_one
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (sigma :
      Gal(fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S/K)) :
    sigma ^ (n : ℕ) = 1 :=
  KummerTheory.kummerRadicalExtension_galois_pow_eq_one
    n hmu (fullSUnitKummerSubgroup (K := K) n S).1 sigma

/-- A chosen Kummer-duality equivalence identifies the Galois group of the full
`S`-unit extension with the actual `S`-unit quotient. -/
noncomputable def
    chosenFullSUnitKummerExtensionGaloisEquivSUnitQuotient
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Gal(fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S/K) ≃*
      SUnitGroup (K := K) S ⧸
        (powMonoidHom (n : ℕ) :
          SUnitGroup (K := K) S →*
            SUnitGroup (K := K) S).range := by
  let Q :=
    KummerTheory.RestrictedRadicalQuotient
      n (fullSUnitKummerSubgroup (K := K) n S)
  let E :=
    fullSUnitKummerExtension
      (K := K) (Omega := Omega) n S
  let e :
      Gal(E/K) ≃*
        (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ)) :=
    KummerTheory.kummerRadicalExtensionRestrictedTransposeMulEquiv
      n hn hmu (fullSUnitKummerSubgroup (K := K) n S)
  let dual :
      (Q →* KummerTheory.nthRootsSubgroup E (n : ℕ)) ≃* Q :=
    Classical.choice <|
      KummerTheory.finiteNthRootsCharacterDuality
        (G := Q) (K := K) (L := E) n hmu
        (KummerTheory.restrictedRadicalQuotient_pow_eq_one
          n (fullSUnitKummerSubgroup (K := K) n S))
  exact (e.trans dual).trans
    (sUnitNthPowerQuotientEquivFullSUnitRadicalQuotient
      (K := K) n S).symm

/-- `ZMod n` coordinates derived from the chosen duality equivalence on the Galois
group of the full `S`-unit Kummer extension. -/
noncomputable def fullSUnitKummerExtensionGaloisCoordinates
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Gal(fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S/K) ≃*
      Multiplicative (ZMod (n : ℕ)) ×
        Multiplicative
          (Fin (SUnitGroup.logRank (K := K) S) →
            ZMod (n : ℕ)) :=
  (chosenFullSUnitKummerExtensionGaloisEquivSUnitQuotient
    (K := K) (Omega := Omega) n hn hmu S).trans
      (sUnitNthPowerQuotientCoordinates
        (K := K) S n hmu)

/-- The Galois group of the full `S`-unit Kummer extension, with one
coordinate for every finite place in `S` and every infinite place.
This chosen coordinate form is consumed by the global norm-index
theorem. -/
noncomputable def fullSUnitKummerExtensionGaloisEquivPiZMod
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Gal(fullSUnitKummerExtension
        (K := K) (Omega := Omega) n S/K) ≃*
      (Fin (totalPlaceCard (K := K) S) →
        Multiplicative (ZMod (n : ℕ))) := by
  let r := SUnitGroup.logRank (K := K) S
  let eFin : Fin (r + 1) ≃
      Fin (totalPlaceCard (K := K) S) :=
    finCongr
      (totalPlaceCard_eq_sUnitLogRank_add_one
        (K := K) S).symm
  let eReindex :
      (Fin (r + 1) → Multiplicative (ZMod (n : ℕ))) ≃*
        (Fin (totalPlaceCard (K := K) S) →
          Multiplicative (ZMod (n : ℕ))) :=
    { toFun := fun f i => f (eFin.symm i)
      invFun := fun f i => f (eFin i)
      left_inv := by
        intro f
        funext i
        simp only [Equiv.symm_apply_apply]
      right_inv := by
        intro f
        funext i
        simp only [Equiv.apply_symm_apply]
      map_mul' := by
        intro f g
        rfl }
  exact
    (fullSUnitKummerExtensionGaloisCoordinates
      (K := K) (Omega := Omega) n hn hmu S).trans <|
      (multiplicativeZModProductEquivPiSucc
        (n : ℕ) r).trans eReindex

/-- With its canonical exponent-`n` module structure, the full
`S`-unit Kummer Galois group is a free `ZMod n`-module. -/
theorem fullSUnitKummerExtension_galois_moduleFree
    {Omega : Type*} [Field Omega] [Algebra K Omega]
    [IsSepClosure K Omega]
    (n : ℕ+) (hn : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    letI : IsMulCommutative
        Gal(fullSUnitKummerExtension
          (K := K) (Omega := Omega) n S/K) :=
      KummerTheory.kummerRadicalExtension_isMulCommutative
        n hmu (fullSUnitKummerSubgroup (K := K) n S).1
    letI : Module (ZMod (n : ℕ))
        (Additive
          Gal(fullSUnitKummerExtension
            (K := K) (Omega := Omega) n S/K)) :=
      additiveZModModuleOfPowEqOne (n : ℕ)
        (fullSUnitKummerExtension_galois_pow_eq_one
          (K := K) (Omega := Omega) n hmu S)
    Module.Free (ZMod (n : ℕ))
      (Additive
        Gal(fullSUnitKummerExtension
          (K := K) (Omega := Omega) n S/K)) := by
  let G :=
    Gal(fullSUnitKummerExtension
      (K := K) (Omega := Omega) n S/K)
  let _ : IsMulCommutative G :=
    KummerTheory.kummerRadicalExtension_isMulCommutative
      n hmu (fullSUnitKummerSubgroup (K := K) n S).1
  let _ : Module (ZMod (n : ℕ)) (Additive G) :=
    additiveZModModuleOfPowEqOne (n : ℕ)
      (fullSUnitKummerExtension_galois_pow_eq_one
        (K := K) (Omega := Omega) n hmu S)
  let e :
      Additive G ≃ₗ[ZMod (n : ℕ)]
        ZMod (n : ℕ) ×
          (Fin (SUnitGroup.logRank (K := K) S) →
            ZMod (n : ℕ)) :=
    additiveCoordinatesLinearEquiv (n : ℕ)
      (fullSUnitKummerExtensionGaloisCoordinates
        (K := K) (Omega := Omega) n hn hmu S)
  exact Module.Free.of_equiv e.symm

end KummerTheory
