/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.BinaryUnramifiedCompositum
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.ClassFormationPGroupH1
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.EverywhereUnramifiedBridge
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.EverywhereUnramifiedProPCompositum
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.EverywhereUnramifiedProPFiniteFamily
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.FiniteFieldUnitsIdelePrimitive
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.FiniteIdeleH2Injection
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.FrattiniClassField
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.GlobalMaximalAbelianRestriction
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.GlobalReciprocityCharacter
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.HilbertElementaryLayer
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.HilbertElementaryLayerInMaximal
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.IdeleCharacterGlobalLift
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.IdeleClassPGroupH1
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalAbelianFiniteProjection
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalEverywhereUnramifiedProP
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalEverywhereUnramifiedProPCofinality
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalEverywhereUnramifiedProPFiniteGeneration
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalEverywhereUnramifiedProPFiniteSupport
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalEverywhereUnramifiedProPGalois
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.MaximalEverywhereUnramifiedProPGroup
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.PClassGroup
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.ProfiniteIntegerFree
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.ProfiniteIntegerH2
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.UnramifiedCompositumBaseChange
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.UnramifiedExplicitBridge
import SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.UnramifiedInfinitePlaceBlockH2

set_option autoImplicit false
