import Mathlib.SetTheory.Cardinal.Finite
import ClassFieldTheory.LubinTate.EqualCharacteristic.FiniteLevel.PrimitiveIrreducible
import ClassFieldTheory.LubinTate.EqualCharacteristic.FiniteLevel.PrimitiveTorsion

set_option autoImplicit false

/-!
# The uniformizer norm identity: equal-characteristic Lubin--Tate level fields

The level-`n+1` field is the simple extension generated by a primitive
division point.  Eisenstein irreducibility identifies its minimal polynomial
with the primitive division polynomial and gives the exact degree
`(q - 1) q^n`.
-/

noncomputable section


open scoped PowerSeries LaurentSeries Polynomial

universe u v

namespace LubinTate
namespace EqualCharacteristic

open LocalFieldTheory.DiscreteValuationField

variable {K : Type u} [Field K]

/-- The explicit base embedding used to choose division roots is the
canonical algebra map of the separable closure. -/
theorem equalCharacteristicSeparableBaseHom_eq_algebraMap
    (F : LocalField.{u, v} K) :
    equalCharacteristicSeparableBaseHom F =
      algebraMap F.residueField⸨X⸩
        (SeparableClosure F.residueField⸨X⸩) := by
  ext x
  rfl

/-- The simple extension generated by the chosen primitive level-`n+1`
division point. -/
@[reducible] noncomputable def equalCharacteristicLubinTateLevelField
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    IntermediateField F.residueField⸨X⸩
      (SeparableClosure F.residueField⸨X⸩) :=
  IntermediateField.adjoin F.residueField⸨X⸩
    {chosenEqualCharacteristicLubinTatePrimitiveRoot F n}

/-- The canonical base algebra on a Lubin--Tate level field.

Naming this structure lets downstream files install the intended algebra
locally without unfolding the separable-closure construction. -/
@[reducible] noncomputable def equalCharacteristicLubinTateLevelFieldAlgebra
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    Algebra F.residueField⸨X⸩
      (equalCharacteristicLubinTateLevelField F n) := by
  change Algebra F.residueField⸨X⸩
    (IntermediateField.adjoin F.residueField⸨X⸩
      {chosenEqualCharacteristicLubinTatePrimitiveRoot F n})
  infer_instance

/-- Defines `equalCharacteristicLubinTateLevelFieldSMul`. -/
@[reducible] noncomputable def equalCharacteristicLubinTateLevelFieldSMul
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    SMul F.residueField⸨X⸩
      (equalCharacteristicLubinTateLevelField F n) := by
  change SMul F.residueField⸨X⸩
    (IntermediateField.adjoin F.residueField⸨X⸩
      {chosenEqualCharacteristicLubinTatePrimitiveRoot F n})
  infer_instance

/-- Defines `equalCharacteristicLubinTateLevelFieldModule`. -/
@[reducible] noncomputable def equalCharacteristicLubinTateLevelFieldModule
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    Module F.residueField⸨X⸩
      (equalCharacteristicLubinTateLevelField F n) := by
  change Module F.residueField⸨X⸩
    (IntermediateField.adjoin F.residueField⸨X⸩
      {chosenEqualCharacteristicLubinTatePrimitiveRoot F n})
  infer_instance

/-- The primitive division point is integral over `κ((T))`. -/
theorem chosenEqualCharacteristicLubinTatePrimitiveRoot_isIntegral
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    IsIntegral F.residueField⸨X⸩
      (chosenEqualCharacteristicLubinTatePrimitiveRoot F n) := by
  refine ⟨equalCharacteristicLubinTatePrimitivePolynomial F n,
    equalCharacteristicLubinTatePrimitivePolynomial_monic F n, ?_⟩
  rw [← equalCharacteristicSeparableBaseHom_eq_algebraMap]
  simpa [Polynomial.IsRoot, Polynomial.eval_map] using
    (chosenEqualCharacteristicLubinTatePrimitiveRoot_isRoot F n)

/-- The Eisenstein primitive polynomial is exactly the minimal polynomial
of the chosen primitive division point. -/
theorem equalCharacteristicLubinTatePrimitivePolynomial_eq_minpoly
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    equalCharacteristicLubinTatePrimitivePolynomial F n =
      minpoly F.residueField⸨X⸩
        (chosenEqualCharacteristicLubinTatePrimitiveRoot F n) := by
  apply minpoly.eq_of_irreducible_of_monic
    (equalCharacteristicLubinTatePrimitivePolynomial_irreducible F n)
    _
    (equalCharacteristicLubinTatePrimitivePolynomial_monic F n)
  rw [Polynomial.aeval_def,
    ← equalCharacteristicSeparableBaseHom_eq_algebraMap]
  simpa [Polynomial.IsRoot, Polynomial.eval_map] using
    (chosenEqualCharacteristicLubinTatePrimitiveRoot_isRoot F n)

/-- Every equal-characteristic Lubin--Tate level field is finite over the
Laurent-series base. -/
theorem equalCharacteristicLubinTateLevelField_finiteDimensional
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    FiniteDimensional F.residueField⸨X⸩
      (equalCharacteristicLubinTateLevelField F n) := by
  exact IntermediateField.adjoin.finiteDimensional
    (chosenEqualCharacteristicLubinTatePrimitiveRoot_isIntegral F n)

/-- The exact degree of the primitive level-`n+1` extension. -/
theorem equalCharacteristicLubinTateLevelField_finrank
    (F : LocalField.{u, v} K)
    [CharP K F.residueCharacteristic]
    (n : ℕ) :
    Module.finrank F.residueField⸨X⸩
        (equalCharacteristicLubinTateLevelField F n) =
      (Nat.card F.residueField - 1) *
        Nat.card F.residueField ^ n := by
  change Module.finrank F.residueField⸨X⸩
      (IntermediateField.adjoin F.residueField⸨X⸩
        {chosenEqualCharacteristicLubinTatePrimitiveRoot F n}) = _
  rw [IntermediateField.adjoin.finrank
      (chosenEqualCharacteristicLubinTatePrimitiveRoot_isIntegral F n),
    ← equalCharacteristicLubinTatePrimitivePolynomial_eq_minpoly,
    equalCharacteristicLubinTatePrimitivePolynomial_natDegree]

end EqualCharacteristic
end LubinTate
