import Mathlib.GroupTheory.PGroup
import ProCGroups.FreeProC.Basic
import ProCGroups.Topologies.TopologicallyCharacteristicSubgroups

set_option autoImplicit false

/-!
# Presentations of profinite and pro-`C` groups

This module defines closed normal closures of relators and free pro-`C` presentations, together
with their basic kernel and universal-property consequences.
-/

noncomputable section

namespace ProCGroups.Presentations

universe u

section ClosedNormalClosure

variable {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]

/-- The closed normal subgroup generated by a set of profinite relators. -/
def Subgroup.closedNormalClosure (R : Set F) : Subgroup F :=
  (Subgroup.normalClosure R).topologicalClosure

/-- The closed normal subgroup generated by a set of profinite relators. -/
abbrev closedNormalClosure (R : Set F) : Subgroup F :=
  Subgroup.closedNormalClosure R

/-- The closed normal closure of a relator set is a normal subgroup. -/
instance closedNormalClosure_normal (R : Set F) : (closedNormalClosure R).Normal := by
  dsimp [closedNormalClosure, Subgroup.closedNormalClosure]
  exact Subgroup.is_normal_topologicalClosure (Subgroup.normalClosure R)

/-- The closed normal closure of a relator set is a closed subgroup. -/
theorem closedNormalClosure_isClosed (R : Set F) :
    IsClosed ((closedNormalClosure R : Subgroup F) : Set F) := by
  exact Subgroup.isClosed_topologicalClosure _

/-- Every relator in \(R\) lies in the closed normal closure of \(R\). -/
theorem subset_closedNormalClosure (R : Set F) :
    R ⊆ closedNormalClosure R := by
  intro x hx
  exact Subgroup.le_topologicalClosure _
    (Subgroup.subset_normalClosure hx)


/--
The closed normal closure of \(R\) is contained in any closed normal subgroup that contains
\(R\).
-/
theorem closedNormalClosure_le_closed_normal
    {R : Set F} {N : Subgroup F} [N.Normal]
    (hNclosed : IsClosed (N : Set F)) (hR : R ⊆ N) :
    closedNormalClosure R ≤ N := by
  exact Subgroup.topologicalClosure_minimal _
    (Subgroup.normalClosure_le_normal hR) hNclosed

end ClosedNormalClosure

/-- A relator presentation whose source is a chosen free pro-`C` group. -/
def IsFreePresentationOf
    (C : ProCGroups.FiniteGroupClass.{u})
    {X F G : Type u} [TopologicalSpace X]
    [Group F] [Group G]
    [TopologicalSpace F] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup G]
    [CompactSpace F] [T2Space F] [TotallyDisconnectedSpace F]
    (ι : X → F) (R : Set F) : Prop :=
  ProCGroups.FreeProC.IsFreeProCGroup (C := C) ι ∧
    ProCGroups.ProC.HasOpenNormalBasisInClass C G ∧
      ∃ π : F →ₜ* G, Function.Surjective π ∧ π.toMonoidHom.ker = closedNormalClosure R

namespace IsFreePresentationOf

variable {C : ProCGroups.FiniteGroupClass.{u}}
variable {X F G : Type u} [TopologicalSpace X]
variable [Group F] [Group G]
variable [TopologicalSpace F] [TopologicalSpace G]
variable [IsTopologicalGroup F] [IsTopologicalGroup G]
variable [CompactSpace F] [T2Space F] [TotallyDisconnectedSpace F]
variable {ι : X → F} {R : Set F}

/-- The chosen quotient map recorded by a free pro-`C` presentation. -/
def π (h : IsFreePresentationOf (G := G) C ι R) : F →ₜ* G :=
  Classical.choose h.2.2

/-- The source of a free presentation is free pro-`C`. -/
theorem freeSource (h : IsFreePresentationOf (G := G) C ι R) :
    ProCGroups.FreeProC.IsFreeProCGroup (C := C) ι :=
  h.1

/-- The target of a free presentation is pro-`C`. -/
theorem targetProC (h : IsFreePresentationOf (G := G) C ι R) :
    ProCGroups.ProC.HasOpenNormalBasisInClass C G :=
  h.2.1

/-- The chosen quotient map is surjective. -/
theorem π_surjective (h : IsFreePresentationOf (G := G) C ι R) :
    Function.Surjective h.π :=
  (Classical.choose_spec h.2.2).1

/-- The kernel of the chosen quotient map is the closed normal closure of the relators. -/
theorem kernel_eq_closedNormalClosure (h : IsFreePresentationOf (G := G) C ι R) :
    h.π.toMonoidHom.ker = closedNormalClosure R :=
  (Classical.choose_spec h.2.2).2

end IsFreePresentationOf
end ProCGroups.Presentations
