import Mathlib.Topology.Algebra.ClopenNhdofOne
import Mathlib.Topology.Algebra.ContinuousMonoidHom
import Mathlib.Topology.Algebra.Nonarchimedean.Basic

set_option autoImplicit false

/-!
# Topological generation and convergent generating sets

This module defines topological generation, convergence to one, the corresponding cardinal
ranks, and the finite word-product filtration of a set.  It develops extensionality,
closed-generated-subgroup, image, quotient, and continuous-equivalence lemmas that form the
basic API for generator arguments in profinite groups.
-/

open Set
open scoped Topology Pointwise

namespace ProCGroups.Generation

universe u v

section

variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- X topologically generates G if the abstract subgroup generated by X is dense in G. -/
def TopologicallyGenerates (X : Set G) : Prop :=
  (Subgroup.closure X).topologicalClosure = ⊤

/-- A set converges to `1` when its subtype inclusion tends to `1` along the cofinite filter. -/
def ConvergesToOne (X : Set G) : Prop :=
  Filter.Tendsto (fun x : X => (x : G)) Filter.cofinite (𝓝 1)

/-- The weaker condition obtained by testing convergence only against open subgroups.

This agrees with `ConvergesToOne` for nonarchimedean groups, but is deliberately kept separate:
on a general topological group, open subgroups need not form a neighborhood basis at `1`. -/
def ConvergesToOneAlongOpenSubgroups (X : Set G) : Prop :=
  ∀ U : OpenSubgroup G, (X \ (U : Set G)).Finite

omit [IsTopologicalGroup G] in
/-- A finite set converges to `1`. -/
theorem ConvergesToOne.of_finite {X : Set G} (hX : X.Finite) :
    ConvergesToOne (G := G) X := by
  change Filter.Tendsto (fun x : X => (x : G)) Filter.cofinite (𝓝 (1 : G))
  rw [(Filter.cofinite_eq_bot_iff (α := X)).2 hX.to_subtype]
  exact Filter.tendsto_bot

omit [IsTopologicalGroup G] in
/-- Every finite set satisfies the open-subgroup convergence condition. -/
theorem ConvergesToOneAlongOpenSubgroups.of_finite {X : Set G} (hX : X.Finite) :
    ConvergesToOneAlongOpenSubgroups (G := G) X := by
  intro U
  exact hX.subset (by
    intro x hx
    exact hx.1)

omit [IsTopologicalGroup G] in
/-- Genuine convergence implies convergence when tested only on open subgroups. -/
theorem ConvergesToOne.to_alongOpenSubgroups {X : Set G}
    (hX : ConvergesToOne (G := G) X) :
    ConvergesToOneAlongOpenSubgroups (G := G) X := by
  intro U
  have hU : (U : Set G) ∈ 𝓝 (1 : G) :=
    U.isOpen.mem_nhds U.one_mem
  have heventually : ∀ᶠ x : X in Filter.cofinite, (x : G) ∈ U :=
    hX.eventually hU
  have hbad : {x : X | (x : G) ∉ U}.Finite := by
    change {x : X | (x : G) ∈ U} ∈ Filter.cofinite at heventually
    rw [Filter.mem_cofinite] at heventually
    simpa only [Set.compl_ofPred] using heventually
  have hsubset :
      X \ (U : Set G) ⊆
        (fun x : X => (x : G)) '' {x : X | (x : G) ∉ U} := by
    rintro x ⟨hxX, hxU⟩
    exact ⟨⟨x, hxX⟩, hxU, rfl⟩
  exact (hbad.image fun x : X => (x : G)).subset hsubset

omit [IsTopologicalGroup G] in
/-- In a nonarchimedean group, testing against open subgroups detects genuine convergence. -/
theorem ConvergesToOneAlongOpenSubgroups.to_convergesToOne
    [NonarchimedeanGroup G] {X : Set G}
    (hX : ConvergesToOneAlongOpenSubgroups (G := G) X) :
    ConvergesToOne (G := G) X := by
  rw [ConvergesToOne, Filter.tendsto_def]
  intro W hW
  obtain ⟨U, hUW⟩ := NonarchimedeanGroup.is_nonarchimedean W hW
  rw [Filter.mem_cofinite]
  change {x : X | (x : G) ∉ W}.Finite
  have hbadImage :
      ((fun x : X => (x : G)) '' {x : X | (x : G) ∉ U}).Finite := by
    exact (hX U).subset (by
      rintro _ ⟨x, hxU, rfl⟩
      exact ⟨x.property, hxU⟩)
  have hbadU : {x : X | (x : G) ∉ U}.Finite := by
    exact hbadImage.of_finite_image (by
      intro a _ b _ hab
      exact Subtype.ext hab)
  exact hbadU.subset (by
    intro x hxW hxU
    exact hxW (hUW hxU))

omit [IsTopologicalGroup G] in
/-- For nonarchimedean groups, the genuine and open-subgroup convergence predicates agree. -/
theorem convergesToOne_iff_alongOpenSubgroups [NonarchimedeanGroup G] {X : Set G} :
    ConvergesToOne (G := G) X ↔
      ConvergesToOneAlongOpenSubgroups (G := G) X :=
  ⟨ConvergesToOne.to_alongOpenSubgroups,
    ConvergesToOneAlongOpenSubgroups.to_convergesToOne⟩

/-- A set which topologically generates and converges to `1` in the filter sense. -/
def GeneratesAndConvergesToOne (X : Set G) : Prop :=
  TopologicallyGenerates (G := G) X ∧ ConvergesToOne (G := G) X

/-- A generating set satisfying only the weaker open-subgroup convergence condition. -/
def GeneratesAndConvergesToOneAlongOpenSubgroups (X : Set G) : Prop :=
  TopologicallyGenerates (G := G) X ∧
    ConvergesToOneAlongOpenSubgroups (G := G) X

/-- The least cardinality of a topological generating set.

The candidate set is always nonempty: `Set.univ` topologically generates every group. Thus this
definition never uses the accidental value `Cardinal.sInf ∅ = 0`. -/
noncomputable def topologicalRank
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] :
    Cardinal :=
  sInf {κ : Cardinal |
    ∃ X : Set G, TopologicallyGenerates (G := G) X ∧ Cardinal.mk X = κ}

/-- The optional least size of a generating set which also converges to `1`.

Unlike `topologicalRank`, the relevant family of cardinals can be empty, so absence is represented
by `none` instead of being silently identified with cardinal zero. -/
noncomputable def convergentGeneratorRank
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] :
    Option Cardinal := by
  classical
  exact
    if h : ∃ X : Set G, GeneratesAndConvergesToOne (G := G) X then
      some (sInf {κ : Cardinal |
        ∃ X : Set G, GeneratesAndConvergesToOne (G := G) X ∧ Cardinal.mk X = κ})
    else
      none

/-- The topological rank is bounded by the cardinality of any topological generating set. -/
theorem topologicalRank_le_mk_of_topologicallyGenerates {X : Set G}
    (hX : TopologicallyGenerates (G := G) X) :
    topologicalRank G ≤ Cardinal.mk X := by
  change sInf {κ : Cardinal |
    ∃ X : Set G, TopologicallyGenerates (G := G) X ∧ Cardinal.mk X = κ} ≤ Cardinal.mk X
  exact csInf_le' ⟨X, hX, rfl⟩

/-- In particular, an open-subgroup-convergent generating set bounds the topological rank. -/
theorem topologicalRank_le_mk_of_generatesAndConvergesToOneAlongOpenSubgroups {X : Set G}
    (hX : GeneratesAndConvergesToOneAlongOpenSubgroups (G := G) X) :
    topologicalRank G ≤ Cardinal.mk X :=
  topologicalRank_le_mk_of_topologicallyGenerates hX.1

/-- There is a topological generating set whose cardinality is exactly the topological rank. -/
theorem exists_topologicallyGenerates_card_eq_topologicalRank :
    ∃ X : Set G, TopologicallyGenerates (G := G) X ∧
      Cardinal.mk X = topologicalRank G := by
  let C : Set Cardinal := {κ : Cardinal |
    ∃ X : Set G, TopologicallyGenerates (G := G) X ∧ Cardinal.mk X = κ}
  have hC : C.Nonempty := by
    refine ⟨Cardinal.mk (Set.univ : Set G), Set.univ, ?_, rfl⟩
    have hclosure : Subgroup.closure (Set.univ : Set G) = ⊤ := by
      rw [eq_top_iff]
      intro x _
      exact Subgroup.subset_closure (Set.mem_univ x)
    rw [TopologicallyGenerates, hclosure]
    exact le_antisymm le_top (Subgroup.le_topologicalClosure _)
  simpa [topologicalRank, C] using (csInf_mem hC)

/-- A nontrivial T1 topological group has nonzero topological rank. -/
theorem topologicalRank_ne_zero [T1Space G] [Nontrivial G] :
    topologicalRank G ≠ 0 := by
  intro hzero
  obtain ⟨X, hX, hcard⟩ :=
    exists_topologicallyGenerates_card_eq_topologicalRank (G := G)
  let : IsEmpty X := Cardinal.mk_eq_zero_iff.mp (hcard.trans hzero)
  have hXempty : X = ∅ := by
    ext x
    constructor
    · intro hx
      exact isEmptyElim (⟨x, hx⟩ : X)
    · exact False.elim
  have hbotClosed : IsClosed (((⊥ : Subgroup G) : Set G)) := by
    change IsClosed ({1} : Set G)
    exact isClosed_singleton
  have hclosureBot : (⊥ : Subgroup G).topologicalClosure = ⊥ :=
    le_antisymm
      (Subgroup.topologicalClosure_minimal _ le_rfl hbotClosed)
      (Subgroup.le_topologicalClosure _)
  have hclosureEmpty : Subgroup.closure (∅ : Set G) = ⊥ := by
    apply le_antisymm
    · exact (Subgroup.closure_le (K := ⊥)).2 (Set.empty_subset _)
    · exact bot_le
  have hbotTop : (⊥ : Subgroup G) = ⊤ := by
    rw [TopologicallyGenerates, hXempty, hclosureEmpty, hclosureBot] at hX
    exact hX
  exact not_subsingleton_iff_nontrivial.mpr inferInstance
    (subsingleton_iff_bot_eq_top.mp hbotTop)

/--
Iterated products of words in \(X\), with \(\mathrm{wordProducts}(X,0)=\{1\}\) and
\(\mathrm{wordProducts}(X,n+1)=\mathrm{wordProducts}(X,n)\cdot X\).
-/
def wordProducts (X : Set G) : ℕ → Set G
  | 0 => {1}
  | n + 1 => wordProducts X n * X

/-- Topological generation is equivalently density of the abstract subgroup generated by the set. -/
theorem topologicallyGenerates_iff_dense {X : Set G} :
    TopologicallyGenerates (G := G) X ↔ Dense ((Subgroup.closure X : Subgroup G) : Set G) := by
  rw [TopologicallyGenerates, SetLike.ext'_iff, Subgroup.topologicalClosure_coe, Subgroup.coe_top,
    dense_iff_closure_eq]

/--
Continuous homomorphisms out of a topologically generated group are determined by their values
on the generating set.
-/
theorem continuousMonoidHom_ext_of_topologicallyGenerates
    {R : Type v} [Group R] [TopologicalSpace R] [T2Space R]
    {X : Set G} (hX : TopologicallyGenerates (G := G) X)
    {f g : ContinuousMonoidHom G R} (hfg : ∀ x ∈ X, f x = g x) :
    f = g := by
  let K : Subgroup G := {
    carrier := { x | f x = g x }
    one_mem' := by
      change f 1 = g 1
      rw [map_one, map_one]
    mul_mem' := by
      intro a b ha hb
      change f (a * b) = g (a * b)
      rw [map_mul, map_mul, ha, hb]
    inv_mem' := by
      intro a ha
      change f a⁻¹ = g a⁻¹
      rw [map_inv, map_inv, ha]
  }
  have hKclosed : IsClosed ((K : Subgroup G) : Set G) := by
    change IsClosed { x | f x = g x }
    exact isClosed_eq f.continuous_toFun g.continuous_toFun
  have hsub : Subgroup.closure X ≤ K := by
    rw [Subgroup.closure_le]
    intro x hx
    exact hfg x hx
  have htop : (⊤ : Subgroup G) ≤ K := by
    have hcl : (Subgroup.closure X).topologicalClosure ≤ K :=
      Subgroup.topologicalClosure_minimal _ hsub hKclosed
    rw [TopologicallyGenerates] at hX
    rw [hX] at hcl
    exact hcl
  ext x
  change x ∈ K
  exact htop trivial

/-- The closed subgroup topologically generated by a set. -/
def closedSubgroupGenerated (X : Set G) : ClosedSubgroup G where
  toSubgroup := (Subgroup.closure X).topologicalClosure
  isClosed' := Subgroup.isClosed_topologicalClosure _

/-- The canonical map from an indexed family into the closed subgroup it topologically generates. -/
def closedSubgroupGeneratedMap {A : Type v} (φ : A → G) :
    A → (closedSubgroupGenerated (G := G) (Set.range φ) : Subgroup G) :=
  fun a =>
    ⟨φ a, Subgroup.le_topologicalClosure _ (Subgroup.subset_closure ⟨a, rfl⟩)⟩

/-- The canonical indexed family topologically generates its closed generated subgroup. -/
theorem closedSubgroupGeneratedMap_topologicallyGenerates {A : Type v} (φ : A → G) :
    TopologicallyGenerates
      (G := (closedSubgroupGenerated (G := G) (Set.range φ) : Subgroup G))
      (Set.range (closedSubgroupGeneratedMap (G := G) φ)) := by
  let K : ClosedSubgroup G := closedSubgroupGenerated (G := G) (Set.range φ)
  let φK : A → (K : Subgroup G) := closedSubgroupGeneratedMap (G := G) φ
  let L : Subgroup (K : Subgroup G) := Subgroup.closure (Set.range φK)
  have hmap :
      Subgroup.map (K : Subgroup G).subtype L = Subgroup.closure (Set.range φ) := by
    refine le_antisymm ?_ ?_
    · rw [Subgroup.map_le_iff_le_comap, Subgroup.closure_le]
      rintro y ⟨a, rfl⟩
      exact Subgroup.subset_closure ⟨a, rfl⟩
    · rw [Subgroup.closure_le]
      rintro y ⟨a, rfl⟩
      change φ a ∈ Subgroup.map (K : Subgroup G).subtype L
      exact ⟨φK a, Subgroup.subset_closure ⟨a, rfl⟩, rfl⟩
  have himage :
      ((Subtype.val : ↥(K : Subgroup G) → G) ''
          ((L : Subgroup ↥(K : Subgroup G)) : Set ↥(K : Subgroup G))) =
        ((Subgroup.map (K : Subgroup G).subtype L : Subgroup G) : Set G) := by
    ext y
    constructor
    · rintro ⟨z, hz, rfl⟩
      exact ⟨z, hz, rfl⟩
    · rintro ⟨z, hz, hzy⟩
      exact ⟨z, hz, hzy⟩
  rw [topologicallyGenerates_iff_dense, dense_iff_closure_eq]
  ext y
  constructor
  · intro _
    simp only [mem_univ]
  · intro _
    change y ∈ closure ((L : Subgroup K) : Set K)
    rw [closure_subtype]
    change (y : G) ∈
      closure
        (((Subtype.val : ↥(K : Subgroup G) → G) ''
          ((L : Subgroup ↥(K : Subgroup G)) : Set ↥(K : Subgroup G))))
    rw [himage, hmap]
    change (y : G) ∈ ((Subgroup.closure (Set.range φ)).topologicalClosure : Set G)
    exact y.2

/--
Membership in a closed generated subgroup is preserved by continuous homomorphisms, after
mapping the generating set.
-/
theorem map_mem_closedSubgroupGenerated_image
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) {X : Set G} {y : G}
    (hy : y ∈ (closedSubgroupGenerated (G := G) X : Subgroup G)) :
    φ y ∈ (closedSubgroupGenerated (G := H) (φ '' X) : Subgroup H) := by
  let K : Subgroup G :=
    (closedSubgroupGenerated (G := H) (φ '' X) : Subgroup H).comap (φ : G →* H)
  have hX : X ⊆ K := by
    intro x hx
    exact Subgroup.le_topologicalClosure _ (Subgroup.subset_closure ⟨x, hx, rfl⟩)
  have hKclosed : IsClosed (K : Set G) := by
    change IsClosed {x : G | φ x ∈
      (closedSubgroupGenerated (G := H) (φ '' X) : Subgroup H)}
    exact (closedSubgroupGenerated (G := H) (φ '' X)).isClosed'.preimage φ.continuous
  exact
    (Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_le (K := K)).2 hX) hKclosed) hy

/--
Membership in a topologically generated cyclic closed subgroup is preserved by continuous
homomorphisms.
-/
theorem map_mem_closedSubgroupGenerated_singleton
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) (x : G) {y : G}
    (hy : y ∈ (closedSubgroupGenerated (G := G) ({x} : Set G) : Subgroup G)) :
    φ y ∈ (closedSubgroupGenerated (G := H) ({φ x} : Set H) : Subgroup H) := by
  simpa using
    (map_mem_closedSubgroupGenerated_image (G := G) (H := H) φ
      (X := ({x} : Set G)) hy)

/-- The distinguished element g algebraically generates its subgroup of powers. -/
theorem zpowers_subtype_topologically_generated_by_generator
    {G₀ : Type*} [Group G₀] (g : G₀) :
    let cyc : Subgroup G₀ := Subgroup.zpowers g
    let gcyc : cyc := ⟨g, Subgroup.mem_zpowers_iff.mpr ⟨1, by simp only [zpow_one]⟩⟩
    ∀ z : cyc, z ∈ Subgroup.zpowers gcyc := by
  intro cyc gcyc z
  rcases Subgroup.mem_zpowers_iff.mp z.2 with ⟨k, hk⟩
  refine Subgroup.mem_zpowers_iff.mpr ⟨k, ?_⟩
  apply Subtype.ext
  simpa [gcyc] using hk

/-- A finite discrete image of a topologically cyclic group is algebraically cyclic. -/
theorem map_mem_zpowers_of_topologicallyGenerates_singleton
    {A : Type u} [TopologicalSpace A] [Group A] [IsTopologicalGroup A]
    {B : Type v} [TopologicalSpace B] [Group B] [IsTopologicalGroup B]
    [DiscreteTopology B]
    (f : A →ₜ* B) {x a : A}
    (hxgen : TopologicallyGenerates (G := A) ({x} : Set A)) :
    f a ∈ Subgroup.zpowers (f x) := by
  have ha_closed :
      a ∈ (closedSubgroupGenerated ({x} : Set A) : Subgroup A) := by
    have htop :
        (closedSubgroupGenerated ({x} : Set A) : Subgroup A) = ⊤ := by
      change (Subgroup.closure ({x} : Set A)).topologicalClosure = ⊤
      exact hxgen
    rw [htop]
    simp only [Subgroup.mem_top]
  have hfa_closed :
      f a ∈ (closedSubgroupGenerated ({f x} : Set B) : Subgroup B) :=
    map_mem_closedSubgroupGenerated_singleton f x ha_closed
  have hclosure_eq :
      (Subgroup.closure ({f x} : Set B)).topologicalClosure =
        Subgroup.closure ({f x} : Set B) := by
    ext y
    change y ∈ closure (((Subgroup.closure ({f x} : Set B) : Subgroup B) : Set B)) ↔
      y ∈ ((Subgroup.closure ({f x} : Set B) : Subgroup B) : Set B)
    rw [closure_discrete]
  have hfa_closure :
      f a ∈ Subgroup.closure ({f x} : Set B) := by
    simpa [closedSubgroupGenerated, hclosure_eq] using hfa_closed
  simpa [Subgroup.zpowers_eq_closure] using hfa_closure

/-- MonoidHom version of map_mem_zpowers_of_topologicallyGenerates_singleton. -/
theorem monoidHom_map_mem_zpowers_of_topologicallyGenerates_singleton
    {A : Type u} [TopologicalSpace A] [Group A] [IsTopologicalGroup A]
    {B : Type v} [TopologicalSpace B] [Group B] [IsTopologicalGroup B]
    [DiscreteTopology B]
    (f : A →* B) (hf : Continuous f) {x a : A}
    (hxgen : TopologicallyGenerates (G := A) ({x} : Set A)) :
    f a ∈ Subgroup.zpowers (f x) := by
  let fcont : A →ₜ* B :=
    { toMonoidHom := f
      continuous_toFun := hf }
  have hfa :
      fcont a ∈ Subgroup.zpowers (fcont x) :=
    map_mem_zpowers_of_topologicallyGenerates_singleton
      (A := A) fcont hxgen (a := a)
  change f a ∈ Subgroup.zpowers (f x)
  exact hfa

/--
Algebraic powers of the image of \(x\) lie in the image of the closed subgroup generated by
\(x\).
-/
theorem zpowers_image_le_closedSubgroupGenerated_map
    {Q : Type u} [TopologicalSpace Q] [Group Q] [IsTopologicalGroup Q]
    {B : Type v} [Group B]
    (q : Q →* B) (x : Q) :
    Subgroup.zpowers (q x) ≤
      ((closedSubgroupGenerated ({x} : Set Q) : ClosedSubgroup Q) :
        Subgroup Q).map q := by
  intro b hb
  rcases (Subgroup.mem_zpowers_iff.mp hb) with ⟨k, rfl⟩
  refine ⟨x ^ k, ?_, by simp only [map_zpow]⟩
  have hxmem :
      x ∈ ((closedSubgroupGenerated ({x} : Set Q) : ClosedSubgroup Q) :
        Subgroup Q) := by
    change x ∈ (Subgroup.closure ({x} : Set Q)).topologicalClosure
    exact Subgroup.le_topologicalClosure _
      (Subgroup.subset_closure (by simp only [Set.mem_singleton_iff]))
  exact
    ((closedSubgroupGenerated ({x} : Set Q) : ClosedSubgroup Q) :
      Subgroup Q).zpow_mem hxmem k

/--
A dense homomorphic image of the infinite cyclic group is topologically generated by the image
of \(1\).
-/
theorem topologicallyGenerates_singleton_of_denseRange_mint
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : Multiplicative ℤ →* H) (hf : DenseRange f) :
    TopologicallyGenerates (G := H) ({f (Multiplicative.ofAdd 1)} : Set H) := by
  let g : H := f (Multiplicative.ofAdd 1)
  have hsubset :
      Set.range f ⊆
        (((Subgroup.closure ({g} : Set H)).topologicalClosure : Subgroup H) : Set H) := by
    intro y hy
    rcases hy with ⟨n, rfl⟩
    have hz : f n ∈ Subgroup.zpowers g := by
      have hEq : f n = g ^ n.toAdd := by
        simpa [g] using (MonoidHom.apply_mint (f := f) (n := n))
      rw [hEq]
      exact (Subgroup.zpowers g).zpow_mem (Subgroup.mem_zpowers g) n.toAdd
    exact Subgroup.le_topologicalClosure _
      (by simpa [g, Subgroup.zpowers_eq_closure] using hz)
  have hclosure :
      closure (Set.range f) ⊆
        (((Subgroup.closure ({g} : Set H)).topologicalClosure : Subgroup H) : Set H) :=
    closure_minimal hsubset (Subgroup.isClosed_topologicalClosure _)
  rw [TopologicallyGenerates]
  apply top_unique
  intro x _hx
  have hx' : x ∈ closure (Set.range f) := by
    rw [hf.closure_range]
    simp only [mem_univ]
  exact hclosure hx'

/-- Topological generation is unchanged by closing the generating set. -/
theorem topologicallyGenerates_closure_iff {X : Set G} :
    TopologicallyGenerates (G := G) X ↔ TopologicallyGenerates (G := G) (closure X) := by
  constructor
  · intro hX
    have hsub :
        Subgroup.closure X ≤ (Subgroup.closure (closure X)).topologicalClosure := by
      exact (Subgroup.closure_mono subset_closure).trans (Subgroup.le_topologicalClosure _)
    have hle :
        (Subgroup.closure X).topologicalClosure ≤
          (Subgroup.closure (closure X)).topologicalClosure := by
      exact Subgroup.topologicalClosure_minimal _ hsub (Subgroup.isClosed_topologicalClosure _)
    have htop : (⊤ : Subgroup G) ≤ (Subgroup.closure X).topologicalClosure := by
      rw [hX]
    exact top_unique (htop.trans hle)
  · intro hX
    have hsubset : closure X ⊆ ((Subgroup.closure X).topologicalClosure : Set G) := by
      refine closure_minimal ?_ (Subgroup.isClosed_topologicalClosure _)
      intro x hx
      exact (Subgroup.le_topologicalClosure (Subgroup.closure X)) (Subgroup.subset_closure hx)
    have hsub : Subgroup.closure (closure X) ≤ (Subgroup.closure X).topologicalClosure := by
      exact (Subgroup.closure_le (K := (Subgroup.closure X).topologicalClosure)).2 hsubset
    have hle :
        (Subgroup.closure (closure X)).topologicalClosure ≤
          (Subgroup.closure X).topologicalClosure := by
      exact Subgroup.topologicalClosure_minimal _ hsub (Subgroup.isClosed_topologicalClosure _)
    have htop : (⊤ : Subgroup G) ≤ (Subgroup.closure (closure X)).topologicalClosure := by
      rw [hX]
    exact top_unique (htop.trans hle)

/-- Adding \(1\) to a topological generating set does not change generation. -/
theorem topologicallyGenerates_insert_one_iff {X : Set G} :
    TopologicallyGenerates (G := G) (insert (1 : G) X) ↔ TopologicallyGenerates (G := G) X := by
  simp only [TopologicallyGenerates, Subgroup.closure_insert_one]

/-- Union with \(\{1\}\) does not change topological generation. -/
theorem topologicallyGenerates_union_one_iff {X : Set G} :
    TopologicallyGenerates (G := G) (X ∪ ({1} : Set G)) ↔ TopologicallyGenerates (G := G) X := by
  simpa [Set.union_singleton] using topologicallyGenerates_insert_one_iff (G := G) (X := X)

omit [TopologicalSpace G] [IsTopologicalGroup G] in
/--
Removing occurrences of 1 from a parametrized generating range does not change its abstract
subgroup closure.
-/
theorem closure_nontrivial_range_eq_closure_range
    {α : Type v} (f : α → G) :
    Subgroup.closure ({g | ∃ a, g = f a ∧ g ≠ 1} : Set G) =
      Subgroup.closure (Set.range f) := by
  apply le_antisymm
  · exact Subgroup.closure_mono (by
      rintro g ⟨a, rfl, _⟩
      exact ⟨a, rfl⟩)
  · have hrange :
        Set.range f ⊆ insert (1 : G) ({g | ∃ a, g = f a ∧ g ≠ 1} : Set G) := by
      rintro g ⟨a, rfl⟩
      by_cases h : f a = 1
      · exact Or.inl h
      · exact Or.inr ⟨a, rfl, h⟩
    refine (Subgroup.closure_mono hrange).trans ?_
    exact le_of_eq (Subgroup.closure_insert_one ({g | ∃ a, g = f a ∧ g ≠ 1} : Set G))

/-- Topological generation is monotone in the generating set. -/
theorem topologicallyGenerates_mono {X Y : Set G}
    (hX : TopologicallyGenerates (G := G) X) (hXY : X ⊆ Y) :
    TopologicallyGenerates (G := G) Y := by
  have hle :
      (Subgroup.closure X).topologicalClosure ≤ (Subgroup.closure Y).topologicalClosure := by
    exact Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_mono hXY).trans (Subgroup.le_topologicalClosure _))
      (Subgroup.isClosed_topologicalClosure _)
  have htop : (⊤ : Subgroup G) ≤ (Subgroup.closure X).topologicalClosure := by
    simpa [TopologicallyGenerates] using (show TopologicallyGenerates (G := G) X from hX)
  exact top_unique (htop.trans hle)

/-- A topological generating set may be replaced by any set whose abstract closure contains it. -/
theorem topologicallyGenerates_of_subset_closure {X Y : Set G}
    (hX : TopologicallyGenerates (G := G) X)
    (hXY : X ⊆ ((Subgroup.closure Y : Subgroup G) : Set G)) :
    TopologicallyGenerates (G := G) Y := by
  have hle : Subgroup.closure X ≤ Subgroup.closure Y :=
    (Subgroup.closure_le (K := Subgroup.closure Y)).2 hXY
  have hle' :
      (Subgroup.closure X).topologicalClosure ≤ (Subgroup.closure Y).topologicalClosure := by
    exact Subgroup.topologicalClosure_minimal _
      (hle.trans (Subgroup.le_topologicalClosure _))
      (Subgroup.isClosed_topologicalClosure _)
  have htop : (⊤ : Subgroup G) ≤ (Subgroup.closure X).topologicalClosure := by
    simpa [TopologicallyGenerates] using (show TopologicallyGenerates (G := G) X from hX)
  exact top_unique (htop.trans hle')

/-- Topological generation pushes forward along continuous surjective homomorphisms. -/
theorem topologicallyGenerates_image_of_continuousSurjective
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : G →* H) (hf : Continuous f) (hfsurj : Function.Surjective f)
    {X : Set G} (hX : TopologicallyGenerates (G := G) X) :
    TopologicallyGenerates (G := H) (f '' X) := by
  have hmap :
      (Subgroup.closure X).map f = Subgroup.closure (f '' X) := by
    simpa using MonoidHom.map_closure f X
  have htop :
      ((Subgroup.closure X).map f).topologicalClosure = ⊤ := by
    exact DenseRange.topologicalClosure_map_subgroup
      (f := f)
      (hf := hf)
      (hf' := hfsurj.denseRange)
      (by simpa [TopologicallyGenerates] using hX)
  rw [TopologicallyGenerates, ← hmap]
  exact htop

/-- Continuous-homomorphism form of push-forward for topological generation. -/
theorem topologicallyGenerates_image_of_continuousMonoidHom_surjective
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : G →ₜ* H) (hfsurj : Function.Surjective f)
    {X : Set G} (hX : TopologicallyGenerates (G := G) X) :
    TopologicallyGenerates (G := H) (f '' X) :=
  topologicallyGenerates_image_of_continuousSurjective
    (G := G) (H := H) f.toMonoidHom f.continuous_toFun hfsurj hX

omit [IsTopologicalGroup G] in
/--
A continuous homomorphism from a compact group onto a Hausdorff target is surjective as soon as
its closed range contains a topological generating set of the target.
-/
theorem continuousMonoidHom_surjective_of_topologicallyGenerates_subset_range
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [CompactSpace G] [T2Space H]
    (f : G →ₜ* H) {X : Set H} (hX : TopologicallyGenerates (G := H) X)
    (hXrange : X ⊆ ((f.toMonoidHom.range : Subgroup H) : Set H)) :
    Function.Surjective f := by
  have hrangeClosed : IsClosed (((f.toMonoidHom.range : Subgroup H) : Set H)) := by
    have himage : IsCompact (f '' (Set.univ : Set G)) :=
      isCompact_univ.image f.continuous_toFun
    have hEq :
        f '' (Set.univ : Set G) =
          ((f.toMonoidHom.range : Subgroup H) : Set H) := by
      ext y
      constructor
      · rintro ⟨x, _hx, rfl⟩
        exact ⟨x, rfl⟩
      · rintro ⟨x, rfl⟩
        exact ⟨x, trivial, rfl⟩
    exact (hEq ▸ himage).isClosed
  have hclosure_le :
      (Subgroup.closure X).topologicalClosure ≤ f.toMonoidHom.range :=
    Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_le (K := f.toMonoidHom.range)).2 hXrange) hrangeClosed
  have htop : (⊤ : Subgroup H) ≤ f.toMonoidHom.range := by
    rw [← hX]
    exact hclosure_le
  intro y
  exact htop trivial

/-- Topological generation descends to every quotient by a normal subgroup. -/
theorem topologicallyGenerates_quotient_image
    (N : Subgroup G) [N.Normal]
    {X : Set G} (hX : TopologicallyGenerates (G := G) X) :
    TopologicallyGenerates (G := G ⧸ N) ((QuotientGroup.mk' N) '' X) :=
  topologicallyGenerates_image_of_continuousSurjective
    (G := G)
    (H := G ⧸ N)
    (QuotientGroup.mk' N)
    continuous_quotient_mk'
    (QuotientGroup.mk'_surjective N)
    hX

/-- Topological generation is preserved by continuous multiplicative equivalences. -/
theorem topologicallyGenerates_continuousMulEquiv_image
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (e : G ≃ₜ* H) {X : Set G} (hX : TopologicallyGenerates (G := G) X) :
    TopologicallyGenerates (G := H) (e '' X) :=
  topologicallyGenerates_image_of_continuousSurjective
    (G := G) (H := H) e.toMonoidHom e.continuous e.surjective hX

/-- Topological generation is transported across a continuous multiplicative equivalence. -/
theorem topologicallyGenerates_continuousMulEquiv_image_iff
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (e : G ≃ₜ* H) {X : Set G} :
    TopologicallyGenerates (G := H) (e '' X) ↔ TopologicallyGenerates (G := G) X := by
  constructor
  · intro h
    have hpre :=
      topologicallyGenerates_continuousMulEquiv_image
        (G := H) (H := G) e.symm (X := e '' X) h
    have hset : e.symm '' (e '' X) = X := by
      ext x
      constructor
      · rintro ⟨y, ⟨z, hz, rfl⟩, rfl⟩
        simpa using hz
      · intro hx
        exact ⟨e x, ⟨x, hx, rfl⟩, by simp only [ContinuousMulEquiv.symm_apply_apply]⟩
    simpa [hset] using hpre
  · exact topologicallyGenerates_continuousMulEquiv_image (G := G) (H := H) e

end

end ProCGroups.Generation
