/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ProCGroups.ProP.Presentation.GeneratorRank
import ProCGroups.FiniteGeneration.Basic

set_option autoImplicit false

/-!
# Finite generation of a displayed presentation source

The actual finite free basis supplies a finite topological generating set.
No minimality assumption on the presentation is required.
-/

namespace ClassFieldTower.ProP.FiniteProPPresentation

open ProCGroups ProCGroups.FiniteGeneration

universe u

/-- The free source of any displayed finite presentation is topologically
finitely generated by its actual finite free basis. -/
theorem source_topologicallyFinitelyGenerated
    {p d r : ℕ} [Fact p.Prime]
    {sourceData : FreeProC.EpimorphicallyFreeProCGroupOnConvergingSetData.{u, u}
      (FiniteGroupClass.pGroup p)}
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] [T2Space G] [TotallyDisconnectedSpace G]
    (P : FiniteProPPresentation p d r sourceData G) :
    TopologicallyFinitelyGenerated sourceData.carrier :=
  topologicallyFinitelyGenerated_iff_exists_topologicallyGeneratedByAtMost.mpr
    ⟨d, topologicallyGeneratedByAtMost_of_topologicalRank_eq_nat
      P.source_topologicalRank_eq_nat⟩

end ClassFieldTower.ProP.FiniteProPPresentation
