import ValuedFieldTheory.Valuation.Henselian.Factorization.CoefficientMinimum
import ValuedFieldTheory.Valuation.Henselian.Factorization.WeakLimits
import ValuedFieldTheory.Valuation.Henselian.Factorization.PrincipalLimits

set_option autoImplicit false

/-!
# explicit valuation-ring Hensel statement

This file connects the chosen finite-minimum coefficient to
the displayed-factor complete-limit theorem.
-/

noncomputable section

open scoped Polynomial

namespace AlgebraicNumberTheory
namespace Valuations

/-- complete-limit factorization from coprime residual factors
and chosen lifts over a valuation ring.  The element `π` is chosen from the
finite set of coefficients of the two initial error polynomials, as in the
proof. -/
theorem henselFactorization_exists_limit_factorization_of_coprime_lifts_valuationRing
    {R : Type*} [CommRing R] [Nontrivial R] [PreValuationRing R]
    [NoZeroDivisors R]
    [IsPrecomplete (IsLocalRing.maximalIdeal R) R]
    [IsHausdorff (IsLocalRing.maximalIdeal R) R]
    {f g0 h0 : R[X]}
    {gbar hbar : (IsLocalRing.ResidueField R)[X]} {m d : ℕ}
    (hfbar : f.map (IsLocalRing.residue R) = gbar * hbar)
    (hg0map : g0.map (IsLocalRing.residue R) = gbar)
    (hh0map : h0.map (IsLocalRing.residue R) = hbar)
    (hcop : IsCoprime gbar hbar)
    (hf : f.natDegree ≤ d)
    (hg0nat : g0.natDegree = m)
    (hgbar_nat : gbar.natDegree = m)
    (hglead : gbar.leadingCoeff ≠ 0)
    (hh0deg : h0.natDegree ≤ d - m)
    (hmd : m ≤ d) :
    ∃ G H : R[X],
      G.natDegree ≤ m ∧ H.natDegree ≤ d - m ∧ f = G * H ∧
        G.map (IsLocalRing.residue R) = gbar ∧
        H.map (IsLocalRing.residue R) = hbar := by
  classical
  rcases henselFactorization_exists_bezout_lifts
      (IsLocalRing.residue R) IsLocalRing.residue_surjective
      hcop hg0map hh0map with
    ⟨a, b, hbez⟩
  let S := henselFactorization_twoPolynomialCoeffFinset
    (f - g0 * h0) (a * g0 + b * h0 - 1)
  by_cases hs : S.Nonempty
  · rcases henselFactorization_exists_pi_factor_initial_errors_of_residue_lifts_of_nonempty
      (R := R) (f := f) (g0 := g0) (h0 := h0) (a := a) (b := b)
      (gbar := gbar) (hbar := hbar)
      hfbar hg0map hh0map hbez (by simpa [S] using hs) with
      ⟨π, hπmem, hπcoeff, ⟨f1, hfactor0⟩, ⟨e, hbezFactor⟩⟩
    have hπne : π ≠ 0 :=
      henselFactorization_ne_zero_of_mem_twoPolynomialCoeffFinset hπcoeff
    exact henselFactorization_exists_limit_factorization_of_mem_span
      (π := π) hπne hπmem
      (f := f) (g0 := g0) (h0 := h0)
      (a := a) (b := b) (f1 := f1) (e := e)
      (gbar := gbar) (hbar := hbar) (m := m) (d := d)
      hf hg0map hh0map hg0nat hgbar_nat hglead hh0deg
      hfactor0 hbezFactor hmd
  · have hSempty :
        henselFactorization_twoPolynomialCoeffFinset
          (f - g0 * h0) (a * g0 + b * h0 - 1) = ∅ := by
      apply Finset.eq_empty_iff_forall_notMem.mpr
      intro x hx
      exact hs ⟨x, by simpa [S] using hx⟩
    have hzeros :=
      henselFactorization_twoPolynomialCoeffFinset_empty_iff.mp hSempty
    rcases hzeros with ⟨hfactor0, _hbez0⟩
    refine ⟨g0, h0, ?_, hh0deg, ?_, hg0map, hh0map⟩
    · simp [hg0nat]
    · exact sub_eq_zero.mp hfactor0

/-- complete-limit factorization from coprime residual factors
and chosen lifts over a valuation ring, using the principal filtration
generated by the finite-minimum element `π`. -/
theorem henselFactorization_exists_limit_factorization_of_coprime_lifts_valuationRing_principal
    {R : Type*} [CommRing R] [Nontrivial R] [PreValuationRing R]
    [NoZeroDivisors R]
    (hpre : ∀ π : R, π ≠ 0 → π ∈ IsLocalRing.maximalIdeal R →
      IsPrecomplete (Ideal.span ({π} : Set R)) R)
    (hhaus : ∀ π : R, π ≠ 0 → π ∈ IsLocalRing.maximalIdeal R →
      IsHausdorff (Ideal.span ({π} : Set R)) R)
    {f g0 h0 : R[X]}
    {gbar hbar : (IsLocalRing.ResidueField R)[X]} {m d : ℕ}
    (hfbar : f.map (IsLocalRing.residue R) = gbar * hbar)
    (hg0map : g0.map (IsLocalRing.residue R) = gbar)
    (hh0map : h0.map (IsLocalRing.residue R) = hbar)
    (hcop : IsCoprime gbar hbar)
    (hf : f.natDegree ≤ d)
    (hg0nat : g0.natDegree = m)
    (hgbar_nat : gbar.natDegree = m)
    (hglead : gbar.leadingCoeff ≠ 0)
    (hh0deg : h0.natDegree ≤ d - m)
    (hmd : m ≤ d) :
    ∃ G H : R[X],
      G.natDegree ≤ m ∧ H.natDegree ≤ d - m ∧ f = G * H ∧
        G.map (IsLocalRing.residue R) = gbar ∧
        H.map (IsLocalRing.residue R) = hbar := by
  classical
  rcases henselFactorization_exists_bezout_lifts
      (IsLocalRing.residue R) IsLocalRing.residue_surjective
      hcop hg0map hh0map with
    ⟨a, b, hbez⟩
  let S := henselFactorization_twoPolynomialCoeffFinset
    (f - g0 * h0) (a * g0 + b * h0 - 1)
  by_cases hs : S.Nonempty
  · rcases henselFactorization_exists_pi_factor_initial_errors_of_residue_lifts_of_nonempty
      (R := R) (f := f) (g0 := g0) (h0 := h0) (a := a) (b := b)
      (gbar := gbar) (hbar := hbar)
      hfbar hg0map hh0map hbez (by simpa [S] using hs) with
      ⟨π, hπmem, hπcoeff, ⟨f1, hfactor0⟩, ⟨e, hbezFactor⟩⟩
    have hπne : π ≠ 0 :=
      henselFactorization_ne_zero_of_mem_twoPolynomialCoeffFinset hπcoeff
    let : IsPrecomplete (Ideal.span ({π} : Set R)) R :=
      hpre π hπne hπmem
    let : IsHausdorff (Ideal.span ({π} : Set R)) R :=
      hhaus π hπne hπmem
    exact henselFactorization_exists_limit_factorization_of_mem_span_principal
      (π := π) hπne hπmem
      (f := f) (g0 := g0) (h0 := h0)
      (a := a) (b := b) (f1 := f1) (e := e)
      (gbar := gbar) (hbar := hbar) (m := m) (d := d)
      hf hg0map hh0map hg0nat hgbar_nat hglead hh0deg
      hfactor0 hbezFactor hmd
  · have hSempty :
        henselFactorization_twoPolynomialCoeffFinset
          (f - g0 * h0) (a * g0 + b * h0 - 1) = ∅ := by
      apply Finset.eq_empty_iff_forall_notMem.mpr
      intro x hx
      exact hs ⟨x, by simpa [S] using hx⟩
    have hzeros :=
      henselFactorization_twoPolynomialCoeffFinset_empty_iff.mp hSempty
    rcases hzeros with ⟨hfactor0, _hbez0⟩
    refine ⟨g0, h0, ?_, hh0deg, ?_, hg0map, hh0map⟩
    · simp [hg0nat]
    · exact sub_eq_zero.mp hfactor0

/-- Degree-controlled polynomial lifts of a nonzero residual
factorization.  This is the algebraic preparation shared by the maximal-ideal
and principal-adic forms of Hensel's lemma. -/
theorem henselFactorization_exists_degreeControlledLifts_of_residual_factorization
    {R : Type*} [CommRing R] [IsLocalRing R]
    {f : R[X]} {gbar hbar : (IsLocalRing.ResidueField R)[X]}
    (hprim : f.map (IsLocalRing.residue R) ≠ 0)
    (hfbar : f.map (IsLocalRing.residue R) = gbar * hbar) :
    ∃ g0 h0 : R[X],
      g0.map (IsLocalRing.residue R) = gbar ∧
        h0.map (IsLocalRing.residue R) = hbar ∧
          g0.natDegree = gbar.natDegree ∧
            h0.natDegree ≤ f.natDegree - gbar.natDegree ∧
              gbar.natDegree ≤ f.natDegree ∧
                gbar.leadingCoeff ≠ 0 := by
  have hfmap :
      (f.map (IsLocalRing.residue R)).natDegree ≤ f.natDegree :=
    henselFactorization_map_natDegree_le_of_natDegree_le
      (IsLocalRing.residue R) le_rfl
  have hgbar_ne : gbar ≠ 0 := by
    intro hgbar
    apply hprim
    rw [hfbar, hgbar, zero_mul]
  have hhbar_ne : hbar ≠ 0 := by
    intro hhbar
    apply hprim
    rw [hfbar, hhbar, mul_zero]
  have hglead : gbar.leadingCoeff ≠ 0 :=
    Polynomial.leadingCoeff_ne_zero.mpr hgbar_ne
  have hprod_degree :
      (gbar * hbar).natDegree ≤ f.natDegree := by
    simpa [hfbar] using hfmap
  have hsum :
      gbar.natDegree + hbar.natDegree ≤ f.natDegree := by
    simpa [Polynomial.natDegree_mul hgbar_ne hhbar_ne] using hprod_degree
  have hmd : gbar.natDegree ≤ f.natDegree :=
    (Nat.le_add_right gbar.natDegree hbar.natDegree).trans hsum
  have hhbar_deg :
      hbar.natDegree ≤ f.natDegree - gbar.natDegree :=
    henselFactorization_residual_right_natDegree_le
      (fbar := f.map (IsLocalRing.residue R))
      (gbar := gbar) (hbar := hbar)
      (m := gbar.natDegree) (d := f.natDegree)
      hfbar hfmap rfl hglead
  rcases henselFactorization_exists_polynomial_lift_natDegree_eq
      (IsLocalRing.residue R) IsLocalRing.residue_surjective gbar with
    ⟨g0, hg0map, hg0nat⟩
  rcases henselFactorization_exists_polynomial_lift_natDegree_eq
      (IsLocalRing.residue R) IsLocalRing.residue_surjective hbar with
    ⟨h0, hh0map, hh0nat⟩
  refine ⟨g0, h0, hg0map, hh0map, hg0nat, ?_, hmd, hglead⟩
  simpa [hh0nat] using hhbar_deg

/-- explicit residual-factor form of Hensel's lemma for a
complete separated valuation ring. -/
theorem henselFactorization_exists_limit_factorization_of_residual_factors_valuationRing
    {R : Type*} [CommRing R] [Nontrivial R] [PreValuationRing R]
    [NoZeroDivisors R]
    [IsPrecomplete (IsLocalRing.maximalIdeal R) R]
    [IsHausdorff (IsLocalRing.maximalIdeal R) R]
    {f : R[X]}
    {gbar hbar : (IsLocalRing.ResidueField R)[X]}
    (hprim : f.map (IsLocalRing.residue R) ≠ 0)
    (hfbar : f.map (IsLocalRing.residue R) = gbar * hbar)
    (hcop : IsCoprime gbar hbar) :
    ∃ G H : R[X],
      G.natDegree = gbar.natDegree ∧
        H.natDegree ≤ f.natDegree - gbar.natDegree ∧
          f = G * H ∧
            G.map (IsLocalRing.residue R) = gbar ∧
              H.map (IsLocalRing.residue R) = hbar := by
  rcases henselFactorization_exists_degreeControlledLifts_of_residual_factorization
      hprim hfbar with
    ⟨g0, h0, hg0map, hh0map, hg0nat, hh0deg, hmd, hglead⟩
  rcases henselFactorization_exists_limit_factorization_of_coprime_lifts_valuationRing
      (f := f) (g0 := g0) (h0 := h0)
      (gbar := gbar) (hbar := hbar)
      (m := gbar.natDegree) (d := f.natDegree)
      hfbar hg0map hh0map hcop le_rfl hg0nat rfl hglead hh0deg hmd with
    ⟨G, H, hGle, hHle, hfactor, hGmap, hHmap⟩
  have hGdegree : G.natDegree = gbar.natDegree :=
    henselFactorization_natDegree_eq_of_residue_eq_of_le
      (R := R) (P := G) (gbar := gbar) (m := gbar.natDegree)
      hGle hGmap rfl hglead
  exact ⟨G, H, hGdegree, hHle, hfactor, hGmap, hHmap⟩

/-- explicit residual-factor form using the principal
filtration generated by the finite-minimum element chosen in the proof. -/
theorem henselFactorization_exists_limit_factorization_of_residual_factors_valuationRing_principal
    {R : Type*} [CommRing R] [Nontrivial R] [PreValuationRing R]
    [NoZeroDivisors R]
    (hpre : ∀ π : R, π ≠ 0 → π ∈ IsLocalRing.maximalIdeal R →
      IsPrecomplete (Ideal.span ({π} : Set R)) R)
    (hhaus : ∀ π : R, π ≠ 0 → π ∈ IsLocalRing.maximalIdeal R →
      IsHausdorff (Ideal.span ({π} : Set R)) R)
    {f : R[X]}
    {gbar hbar : (IsLocalRing.ResidueField R)[X]}
    (hprim : f.map (IsLocalRing.residue R) ≠ 0)
    (hfbar : f.map (IsLocalRing.residue R) = gbar * hbar)
    (hcop : IsCoprime gbar hbar) :
    ∃ G H : R[X],
      G.natDegree = gbar.natDegree ∧
        H.natDegree ≤ f.natDegree - gbar.natDegree ∧
          f = G * H ∧
            G.map (IsLocalRing.residue R) = gbar ∧
              H.map (IsLocalRing.residue R) = hbar := by
  rcases henselFactorization_exists_degreeControlledLifts_of_residual_factorization
      hprim hfbar with
    ⟨g0, h0, hg0map, hh0map, hg0nat, hh0deg, hmd, hglead⟩
  rcases
      henselFactorization_exists_limit_factorization_of_coprime_lifts_valuationRing_principal
        (R := R) hpre hhaus
        (f := f) (g0 := g0) (h0 := h0)
        (gbar := gbar) (hbar := hbar)
        (m := gbar.natDegree) (d := f.natDegree)
        hfbar hg0map hh0map hcop le_rfl hg0nat rfl hglead hh0deg hmd with
    ⟨G, H, hGle, hHle, hfactor, hGmap, hHmap⟩
  have hGdegree : G.natDegree = gbar.natDegree :=
    henselFactorization_natDegree_eq_of_residue_eq_of_le
      (R := R) (P := G) (gbar := gbar) (m := gbar.natDegree)
      hGle hGmap rfl hglead
  exact ⟨G, H, hGdegree, hHle, hfactor, hGmap, hHmap⟩

end Valuations
end AlgebraicNumberTheory

end
