import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.Lifts
import Mathlib.RingTheory.LocalRing.ResidueField.Basic

set_option autoImplicit false

/-!
# algebraic input for Hensel's lemma

This file records the residue-polynomial data used at the start of the
proof of Hensel's lemma.  The analytic convergence step is kept separate; the
lemmas here are the initial lifts and congruences.
-/

noncomputable section

open scoped Polynomial

namespace AlgebraicNumberTheory
namespace Valuations

/-- Polynomial coefficient maps distribute over the Bezout expression used in
the Hensel input. -/
theorem henselFactorization_map_mul_add_mul
    {R k : Type*} [CommSemiring R] [CommSemiring k] (φ : R →+* k)
    (a b g h : R[X]) :
    (a * g + b * h).map φ = a.map φ * g.map φ + b.map φ * h.map φ := by
  simp [Polynomial.map_add, Polynomial.map_mul]

/-- Polynomial coefficient maps distribute over `f - g*h`, the first Hensel
congruence expression. -/
theorem henselFactorization_map_sub_mul
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (f g h : R[X]) :
    (f - g * h).map φ = f.map φ - g.map φ * h.map φ := by
  simp [Polynomial.map_sub, Polynomial.map_mul]

/-- Polynomial coefficient maps distribute over `P*F - F`, the normalized
Bezout-error expression in the Hensel correction congruence. -/
theorem henselFactorization_map_mul_sub_self
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (P F : R[X]) :
    (P * F - F).map φ = P.map φ * F.map φ - F.map φ := by
  simp [Polynomial.map_sub, Polynomial.map_mul]

/-- Polynomial coefficient maps distribute over `g*q - A`, the product
congruence used to bound the high coefficients of the quotient. -/
theorem henselFactorization_map_mul_sub
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (g q A : R[X]) :
    (g * q - A).map φ = g.map φ * q.map φ - A.map φ := by
  simp [Polynomial.map_sub, Polynomial.map_mul]

/-- Polynomial coefficient maps distribute over the Hensel correction expression
`g*q + h*p - fn`. -/
theorem henselFactorization_map_mul_add_mul_sub
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (g h q p fn : R[X]) :
    (g * q + h * p - fn).map φ =
      g.map φ * q.map φ + h.map φ * p.map φ - fn.map φ := by
  simp [Polynomial.map_sub, Polynomial.map_add, Polynomial.map_mul]

/-- If the maximal ideal is generated by `π`, then `π` is in it. -/
theorem henselFactorization_generator_mem_maximalIdeal_of_eq
    {R : Type*} [CommRing R] [IsLocalRing R] {π : R}
    (hπ : IsLocalRing.maximalIdeal R = Ideal.span ({π} : Set R)) :
    π ∈ IsLocalRing.maximalIdeal R := by
  rw [hπ]
  exact Ideal.mem_span_singleton_self π

/-- Equality with the principal ideal gives the weakened containment form used
by the recursive construction. -/
theorem henselFactorization_maximalIdeal_le_span_of_eq
    {R : Type*} [CommRing R] [IsLocalRing R] {π : R}
    (hπ : IsLocalRing.maximalIdeal R = Ideal.span ({π} : Set R)) :
    IsLocalRing.maximalIdeal R ≤ Ideal.span ({π} : Set R) := by
  simp [hπ]

/-- The two principal-maximal-ideal facts used throughout the proof of
the factorization form of Hensel's lemma. -/
theorem henselFactorization_principal_maximal_mem_le_of_eq
    {R : Type*} [CommRing R] [IsLocalRing R] {π : R}
    (hπ : IsLocalRing.maximalIdeal R = Ideal.span ({π} : Set R)) :
    π ∈ IsLocalRing.maximalIdeal R ∧
      IsLocalRing.maximalIdeal R ≤ Ideal.span ({π} : Set R) := by
  exact ⟨henselFactorization_generator_mem_maximalIdeal_of_eq hπ,
    henselFactorization_maximalIdeal_le_span_of_eq hπ⟩

/-- lift input: a residue polynomial can be lifted along a
surjective coefficient map with the same polynomial degree. -/
theorem henselFactorization_exists_polynomial_lift_degree_eq
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (hφ : Function.Surjective φ) (fbar : k[X]) :
    ∃ f : R[X], f.map φ = fbar ∧ f.degree = fbar.degree := by
  have hlifts : fbar ∈ Polynomial.lifts φ := by
    rw [Polynomial.lifts_iff_coeff_lifts]
    intro n
    exact hφ (fbar.coeff n)
  rcases Polynomial.exists_degree_eq_of_mem_lifts hlifts with
    ⟨f, hmap, hdegree⟩
  exact ⟨f, hmap, hdegree⟩

/-- lift input: a residue polynomial can be lifted along a
surjective coefficient map with the same natural degree. -/
theorem henselFactorization_exists_polynomial_lift_natDegree_eq
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (hφ : Function.Surjective φ) (fbar : k[X]) :
    ∃ f : R[X], f.map φ = fbar ∧ f.natDegree = fbar.natDegree := by
  rcases henselFactorization_exists_polynomial_lift_degree_eq φ hφ fbar with
    ⟨f, hmap, hdegree⟩
  exact ⟨f, hmap, Polynomial.natDegree_eq_of_degree_eq hdegree⟩

/-- unit-leading input: a lift with the same natural degree as
a nonzero residual polynomial has unit leading coefficient. -/
theorem henselFactorization_lift_leadingCoeff_isUnit_of_natDegree_eq
    {R : Type*} [CommRing R] [IsLocalRing R]
    {g0 : R[X]} {gbar : (IsLocalRing.ResidueField R)[X]}
    (hg0 : g0.map (IsLocalRing.residue R) = gbar)
    (hdegree : g0.natDegree = gbar.natDegree)
    (hlead : gbar.leadingCoeff ≠ 0) :
    IsUnit g0.leadingCoeff := by
  have hcoeff :=
    congrArg (fun P : (IsLocalRing.ResidueField R)[X] =>
      P.coeff gbar.natDegree) hg0
  have hres_lead :
      IsLocalRing.residue R g0.leadingCoeff = gbar.leadingCoeff := by
    change (g0.map (IsLocalRing.residue R)).coeff gbar.natDegree =
      gbar.coeff gbar.natDegree at hcoeff
    rw [Polynomial.coeff_map] at hcoeff
    change IsLocalRing.residue R (g0.coeff g0.natDegree) =
      gbar.coeff gbar.natDegree
    rw [hdegree]
    exact hcoeff
  have hres_ne : IsLocalRing.residue R g0.leadingCoeff ≠ 0 := by
    rw [hres_lead]
    exact hlead
  exact (IsLocalRing.residue_ne_zero_iff_isUnit g0.leadingCoeff).1 hres_ne

/-- unit-leading normalization: a polynomial whose leading
coefficient is a unit becomes monic after multiplying by the inverse leading
coefficient, and this normalization preserves degree. -/
theorem henselFactorization_monic_normalization_of_unit_leadingCoeff
    {R : Type*} [CommRing R] {g : R[X]} (hunit : IsUnit g.leadingCoeff) :
    ∃ u : Rˣ,
      (u : R) = g.leadingCoeff ∧
        (Polynomial.C ((u⁻¹ : Rˣ) : R) * g).Monic ∧
          (Polynomial.C ((u⁻¹ : Rˣ) : R) * g).degree = g.degree ∧
            (Polynomial.C ((u⁻¹ : Rˣ) : R) * g).natDegree = g.natDegree := by
  rcases hunit with ⟨u, hu⟩
  have hinvUnit : IsUnit (((u⁻¹ : Rˣ) : R)) := ⟨u⁻¹, rfl⟩
  refine ⟨u, hu, ?_, ?_, ?_⟩
  · exact Polynomial.monic_C_mul_of_mul_leadingCoeff_eq_one
      (p := g) (b := ((u⁻¹ : Rˣ) : R)) (Units.inv_mul_of_eq (u := u) hu)
  · exact Polynomial.degree_C_mul_of_isUnit hinvUnit g
  · exact Polynomial.natDegree_C_mul_of_isUnit hinvUnit g

/-- Bezout lift input: if the two residual factors are
coprime, then after choosing arbitrary lifts `g0`, `h0`, the Bezout
coefficients can also be lifted so that `a g0 + b h0` reduces to `1`. -/
theorem henselFactorization_exists_bezout_lifts
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    (hφ : Function.Surjective φ)
    {gbar hbar : k[X]} (hcop : IsCoprime gbar hbar)
    {g0 h0 : R[X]} (hg0 : g0.map φ = gbar) (hh0 : h0.map φ = hbar) :
    ∃ a b : R[X], (a * g0 + b * h0).map φ = 1 := by
  rcases hcop with ⟨abar, bbar, hbezout⟩
  rcases henselFactorization_exists_polynomial_lift_degree_eq φ hφ abar with
    ⟨a, ha, _⟩
  rcases henselFactorization_exists_polynomial_lift_degree_eq φ hφ bbar with
    ⟨b, hb, _⟩
  refine ⟨a, b, ?_⟩
  calc
    (a * g0 + b * h0).map φ =
        a.map φ * g0.map φ + b.map φ * h0.map φ := by
      exact henselFactorization_map_mul_add_mul φ a b g0 h0
    _ = abar * gbar + bbar * hbar := by
      rw [ha, hb, hg0, hh0]
    _ = 1 := hbezout

/-- A polynomial maps to zero iff all of its coefficients lie in the kernel of
the coefficient map.  This is the coefficientwise form used by the Hensel
correction congruences. -/
theorem henselFactorization_map_eq_zero_iff_coeff_mem_ker
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k) (P : R[X]) :
    P.map φ = 0 ↔ ∀ n : ℕ, P.coeff n ∈ RingHom.ker φ := by
  constructor
  · intro h n
    rw [RingHom.mem_ker]
    have hcoeff := congrArg (fun Q : k[X] => Q.coeff n) h
    simpa [Polynomial.coeff_map] using hcoeff
  · intro h
    ext n
    rw [Polynomial.coeff_map, Polynomial.coeff_zero]
    exact RingHom.mem_ker.mp (h n)

/-- Polynomial coefficient maps are equal iff every coefficient of the
difference lies in the kernel. -/
theorem henselFactorization_map_eq_iff_sub_coeff_mem_ker
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k) (P Q : R[X]) :
    P.map φ = Q.map φ ↔ ∀ n : ℕ, (P - Q).coeff n ∈ RingHom.ker φ := by
  rw [← sub_eq_zero, ← Polynomial.map_sub]
  exact henselFactorization_map_eq_zero_iff_coeff_mem_ker φ (P - Q)

/-- The kernel of the quotient map `R -> R/I` is exactly `I`. -/
theorem henselFactorization_mem_ker_quotient_mk_iff
    {R : Type*} [CommRing R] (I : Ideal R) (x : R) :
    x ∈ RingHom.ker (Ideal.Quotient.mk I) ↔ x ∈ I := by
  rw [RingHom.mem_ker, Ideal.Quotient.eq_zero_iff_mem]

/-- Specialization of the coefficientwise zero criterion to quotient maps:
a polynomial maps to zero in `(R/I)[X]` iff all of its coefficients lie in
`I`. -/
theorem henselFactorization_map_quotient_eq_zero_iff_coeff_mem
    {R : Type*} [CommRing R] (I : Ideal R) (P : R[X]) :
    P.map (Ideal.Quotient.mk I) = 0 ↔ ∀ n : ℕ, P.coeff n ∈ I := by
  rw [henselFactorization_map_eq_zero_iff_coeff_mem_ker]
  constructor
  · intro h n
    rw [← Ideal.Quotient.eq_zero_iff_mem]
    exact RingHom.mem_ker.mp (h n)
  · intro h n
    rw [RingHom.mem_ker]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr (h n)

/-- Coefficientwise form of
`henselFactorization_map_quotient_eq_zero_iff_coeff_mem`. -/
theorem henselFactorization_quotient_map_coeff_eq_zero_iff_coeff_mem
    {R : Type*} [CommRing R] (I : Ideal R) (P : R[X]) (n : ℕ) :
    (P.map (Ideal.Quotient.mk I)).coeff n = 0 ↔ P.coeff n ∈ I := by
  rw [Polynomial.coeff_map, Ideal.Quotient.eq_zero_iff_mem]

/-- Equality after quotienting coefficients is the same as coefficientwise
membership of the difference in the quotient ideal. -/
theorem henselFactorization_map_quotient_eq_iff_sub_coeff_mem
    {R : Type*} [CommRing R] (I : Ideal R) (P Q : R[X]) :
    P.map (Ideal.Quotient.mk I) = Q.map (Ideal.Quotient.mk I) ↔
      ∀ n : ℕ, (P - Q).coeff n ∈ I := by
  rw [henselFactorization_map_eq_iff_sub_coeff_mem_ker]
  constructor
  · intro h n
    exact (henselFactorization_mem_ker_quotient_mk_iff I _).1 (h n)
  · intro h n
    exact (henselFactorization_mem_ker_quotient_mk_iff I _).2 (h n)

/-- first congruence input: if `f` reduces to the product of
the residual factors and `g0`, `h0` lift those factors, then every coefficient
of `f - g0 h0` lies in the kernel of the coefficient map. -/
theorem henselFactorization_coeff_mem_ker_sub_mul_of_lifts
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    {f g0 h0 : R[X]} {gbar hbar : k[X]}
    (hfbar : f.map φ = gbar * hbar)
    (hg0 : g0.map φ = gbar) (hh0 : h0.map φ = hbar) :
    ∀ n : ℕ, (f - g0 * h0).coeff n ∈ RingHom.ker φ := by
  have hmap : (f - g0 * h0).map φ = 0 := by
    calc
      (f - g0 * h0).map φ = f.map φ - g0.map φ * h0.map φ := by
        exact henselFactorization_map_sub_mul φ f g0 h0
      _ = gbar * hbar - gbar * hbar := by
        rw [hfbar, hg0, hh0]
      _ = 0 := by simp
  exact (henselFactorization_map_eq_zero_iff_coeff_mem_ker φ _).1 hmap

/-- local-ring form of the first congruence input for the
residue map. -/
theorem henselFactorization_coeff_mem_maximalIdeal_sub_mul_of_residue_lifts
    {R : Type*} [CommRing R] [IsLocalRing R]
    {f g0 h0 : R[X]} {gbar hbar : (IsLocalRing.ResidueField R)[X]}
    (hfbar : f.map (IsLocalRing.residue R) = gbar * hbar)
    (hg0 : g0.map (IsLocalRing.residue R) = gbar)
    (hh0 : h0.map (IsLocalRing.residue R) = hbar) :
    ∀ n : ℕ, (f - g0 * h0).coeff n ∈ IsLocalRing.maximalIdeal R := by
  intro n
  have hker :
      (f - g0 * h0).coeff n ∈ RingHom.ker (IsLocalRing.residue R) :=
    henselFactorization_coeff_mem_ker_sub_mul_of_lifts
      (IsLocalRing.residue R) hfbar hg0 hh0 n
  rwa [IsLocalRing.ker_residue] at hker

/-- if a polynomial maps to `1`, then subtracting `1` gives
coefficients in the kernel of the coefficient map. -/
theorem henselFactorization_coeff_mem_ker_sub_one_of_map_eq_one
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    {P : R[X]} (hP : P.map φ = 1) :
    ∀ n : ℕ, (P - 1).coeff n ∈ RingHom.ker φ := by
  have hmap : (P - 1).map φ = 0 := by
    calc
      (P - 1).map φ = P.map φ - 1 := by
        simp [Polynomial.map_sub]
      _ = 0 := by
        rw [hP]
        simp
  exact (henselFactorization_map_eq_zero_iff_coeff_mem_ker φ _).1 hmap

/-- local-ring form of the lifted Bezout congruence:
`a*g0 + b*h0 ≡ 1` modulo the residue map means every coefficient of
`a*g0 + b*h0 - 1` lies in the maximal ideal. -/
theorem henselFactorization_coeff_mem_maximalIdeal_sub_one_of_bezout_lift
    {R : Type*} [CommRing R] [IsLocalRing R]
    {a b g0 h0 : R[X]}
    (hbez : (a * g0 + b * h0).map (IsLocalRing.residue R) = 1) :
    ∀ n : ℕ, (a * g0 + b * h0 - 1).coeff n ∈
      IsLocalRing.maximalIdeal R := by
  intro n
  have hker :
      (a * g0 + b * h0 - 1).coeff n ∈
        RingHom.ker (IsLocalRing.residue R) :=
    henselFactorization_coeff_mem_ker_sub_one_of_map_eq_one
      (IsLocalRing.residue R) hbez n
  rwa [IsLocalRing.ker_residue] at hker

/-- division step: division by a monic polynomial gives the
quotient and remainder used in the correction construction, with remainder
degree strictly smaller than the divisor degree. -/
theorem henselFactorization_division_by_monic_degree_lt
    {R : Type*} [CommRing R] [Nontrivial R] (F g : R[X]) (hg : g.Monic) :
    ∃ q p : R[X], F = g * q + p ∧ p.degree < g.degree := by
  refine ⟨F /ₘ g, F %ₘ g, ?_, ?_⟩
  · calc
      F = F %ₘ g + g * (F /ₘ g) := by
        exact (Polynomial.modByMonic_add_div F g).symm
      _ = g * (F /ₘ g) + F %ₘ g := by
        ring
  · exact Polynomial.degree_modByMonic_lt F hg

/-- division by a unit-leading divisor: the division step used
in the Hensel correction construction does not require the chosen lift `g0` to
be monic; a unit leading coefficient is enough. -/
theorem henselFactorization_division_by_unit_leading_degree_lt
    {R : Type*} [CommRing R] [Nontrivial R] (F g : R[X])
    (hunit : IsUnit g.leadingCoeff) :
    ∃ q p : R[X], F = g * q + p ∧ p.degree < g.degree := by
  rcases henselFactorization_monic_normalization_of_unit_leadingCoeff
    (g := g) hunit with
    ⟨u, _hu, hmonic, hdegree, _hnatDegree⟩
  rcases henselFactorization_division_by_monic_degree_lt F
    (Polynomial.C ((u⁻¹ : Rˣ) : R) * g) hmonic with
    ⟨q, p, hdiv, hpdeg⟩
  refine ⟨Polynomial.C ((u⁻¹ : Rˣ) : R) * q, p, ?_, ?_⟩
  · calc
      F = (Polynomial.C ((u⁻¹ : Rˣ) : R) * g) * q + p := hdiv
      _ = g * (Polynomial.C ((u⁻¹ : Rˣ) : R) * q) + p := by
        ring
  · rwa [hdegree] at hpdeg

/-- division by a lifted residual factor: if `g0` lifts
`gbar` with the same degree and `gbar` is nonzero in leading coefficient, then
the construction division step `F = g0 q + p`, `deg p < deg g0`, is available in the
valuation ring. -/
theorem henselFactorization_division_by_lifted_factor_degree_lt
    {R : Type*} [CommRing R] [IsLocalRing R]
    {g0 : R[X]} {gbar : (IsLocalRing.ResidueField R)[X]}
    (hg0 : g0.map (IsLocalRing.residue R) = gbar)
    (hdegree : g0.natDegree = gbar.natDegree)
    (hlead : gbar.leadingCoeff ≠ 0) (F : R[X]) :
    ∃ q p : R[X], F = g0 * q + p ∧ p.degree < g0.degree := by
  exact henselFactorization_division_by_unit_leading_degree_lt F g0
    (henselFactorization_lift_leadingCoeff_isUnit_of_natDegree_eq hg0 hdegree hlead)

/-- Algebra identity behind the Hensel correction step after the division
`b * fn = g0 * q + p`. -/
theorem henselFactorization_correction_identity_after_division
    {R : Type*} [CommSemiring R] {a b g0 h0 fn q p : R[X]}
    (hdiv : b * fn = g0 * q + p) :
    g0 * (a * fn + h0 * q) + h0 * p = (a * g0 + b * h0) * fn := by
  calc
    g0 * (a * fn + h0 * q) + h0 * p =
        a * g0 * fn + h0 * (g0 * q + p) := by
      ring
    _ = a * g0 * fn + h0 * (b * fn) := by
      rw [← hdiv]
    _ = (a * g0 + b * h0) * fn := by
      ring

/-- correction congruence after the division step.  If
`a g0 + b h0` is `1` modulo the coefficient map and `b fn = g0 q + p`, then
the divided correction still represents `fn` modulo the same kernel. -/
theorem henselFactorization_correction_congruence_after_division
    {R k : Type*} [CommRing R] [CommRing k] (φ : R →+* k)
    {a b g0 h0 fn q p : R[X]}
    (hbez : (a * g0 + b * h0).map φ = 1)
    (hdiv : b * fn = g0 * q + p) :
    ∀ n : ℕ,
      (g0 * (a * fn + h0 * q) + h0 * p - fn).coeff n ∈ RingHom.ker φ := by
  have halg :=
    henselFactorization_correction_identity_after_division
      (a := a) (h0 := h0) hdiv
  have hmap :
      (g0 * (a * fn + h0 * q) + h0 * p - fn).map φ = 0 := by
    calc
      (g0 * (a * fn + h0 * q) + h0 * p - fn).map φ =
          (((a * g0 + b * h0) * fn - fn).map φ) := by
        rw [halg]
      _ = (a * g0 + b * h0).map φ * fn.map φ - fn.map φ := by
        exact henselFactorization_map_mul_sub_self φ (a * g0 + b * h0) fn
      _ = 0 := by
        rw [hbez]
        simp
  exact (henselFactorization_map_eq_zero_iff_coeff_mem_ker φ _).1 hmap

/-- correction congruence after division, read directly
modulo the principal ideal `(π)`: if the lifted Bezout error has a displayed
`C π` factor, then the divided correction represents `fn` modulo `(π)`. -/
theorem henselFactorization_correction_congruence_span_singleton_after_division
    {R : Type*} [CommRing R] {π : R}
    {a b g0 h0 fn q p e : R[X]}
    (hbez : a * g0 + b * h0 - 1 = Polynomial.C π * e)
    (hdiv : b * fn = g0 * q + p) :
    ∀ n : ℕ,
      (g0 * (a * fn + h0 * q) + h0 * p - fn).coeff n ∈
        Ideal.span ({π} : Set R) := by
  have halg :=
    henselFactorization_correction_identity_after_division
      (a := a) (h0 := h0) hdiv
  have hfactor :
      g0 * (a * fn + h0 * q) + h0 * p - fn =
        Polynomial.C π * (e * fn) := by
    calc
      g0 * (a * fn + h0 * q) + h0 * p - fn =
          (a * g0 + b * h0 - 1) * fn := by
        rw [halg]
        ring
      _ = Polynomial.C π * (e * fn) := by
        rw [hbez]
        ring
  intro n
  rw [hfactor, Polynomial.coeff_C_mul, Ideal.mem_span_singleton]
  exact dvd_mul_right π ((e * fn).coeff n)

/-- local-ring form of the correction congruence after the
division step. -/
theorem henselFactorization_correction_mem_maximalIdeal_after_division
    {R : Type*} [CommRing R] [IsLocalRing R]
    {a b g0 h0 fn q p : R[X]}
    (hbez : (a * g0 + b * h0).map (IsLocalRing.residue R) = 1)
    (hdiv : b * fn = g0 * q + p) :
    ∀ n : ℕ,
      (g0 * (a * fn + h0 * q) + h0 * p - fn).coeff n ∈
        IsLocalRing.maximalIdeal R := by
  intro n
  have hker :
      (g0 * (a * fn + h0 * q) + h0 * p - fn).coeff n ∈
        RingHom.ker (IsLocalRing.residue R) :=
    henselFactorization_correction_congruence_after_division
      (IsLocalRing.residue R) hbez hdiv n
  rwa [IsLocalRing.ker_residue] at hker

end Valuations
end AlgebraicNumberTheory

end
