import ValuedFieldTheory.Valuation.Henselian.Factorization.Truncation

set_option autoImplicit false

/-!
# the power step in Hensel's iteration

This file contains the `π^n`-to-`π^(n+1)` step in the coefficientwise proof of
Hensel's lemma.  The preceding files produce the correction congruence modulo
the maximal ideal; here it is converted into the actual improvement of the
factorization error after the update
`g ↦ g + π^n p`, `h ↦ h + π^n q`.
-/

noncomputable section

open scoped Polynomial

namespace AlgebraicNumberTheory
namespace Valuations

/-- coefficientwise divisibility gives a polynomial factor by
the corresponding `C a` polynomial. -/
theorem henselFactorization_exists_factor_of_coeff_mem_span_singleton
    {R : Type*} [CommRing R] {a : R} {P : R[X]}
    (hP : ∀ i : ℕ, P.coeff i ∈ Ideal.span ({a} : Set R)) :
    ∃ Q : R[X], P = Polynomial.C a * Q := by
  have hdvd : ∀ i : ℕ, a ∣ P.coeff i := by
    intro i
    simpa [Ideal.mem_span_singleton] using hP i
  exact (Polynomial.C_dvd_iff_dvd_coeff a P).2 hdvd

/-- a displayed `C(π^n)` factor gives coefficientwise
membership in the principal ideal `(π^n)`. -/
theorem henselFactorization_coeff_mem_span_singleton_pow_of_factor
    {R : Type*} [CommRing R] {π : R} {n : ℕ} {P Q : R[X]}
    (hfactor : P = Polynomial.C (π ^ n) * Q) :
    ∀ i : ℕ, P.coeff i ∈ Ideal.span ({π ^ n} : Set R) := by
  intro i
  rw [hfactor, Polynomial.coeff_C_mul]
  refine Ideal.mem_span_singleton'.mpr ⟨Q.coeff i, ?_⟩
  ring

/-- a displayed `C(π^n)` factor gives coefficientwise
membership in the `n`-th power of the principal ideal `(π)`. -/
theorem henselFactorization_coeff_mem_span_pow_of_factor
    {R : Type*} [CommRing R] {π : R} {n : ℕ} {P Q : R[X]}
    (hfactor : P = Polynomial.C (π ^ n) * Q) :
    ∀ i : ℕ, P.coeff i ∈ Ideal.span ({π} : Set R) ^ n := by
  intro i
  rw [Ideal.span_singleton_pow]
  exact henselFactorization_coeff_mem_span_singleton_pow_of_factor
    (π := π) (n := n) hfactor i

/-- the principal ideal generated by an element of an ideal is
contained in that ideal. -/
theorem henselFactorization_span_singleton_le_ideal_of_mem
    {R : Type*} [CommRing R] (I : Ideal R) {π : R} (hπ : π ∈ I) :
    Ideal.span ({π} : Set R) ≤ I := by
  rw [Ideal.span_le]
  intro x hx
  have hxπ : x = π := by simpa using hx
  simpa [hxπ] using hπ

/-- local-ring form: if `π` lies in the maximal ideal, then a
displayed `C(π^n)` factor has every coefficient in `m^n`. -/
theorem henselFactorization_coeff_mem_maximalIdeal_pow_of_factor_of_mem
    {R : Type*} [CommRing R] [IsLocalRing R] {π : R} {n : ℕ} {P Q : R[X]}
    (hπ : π ∈ IsLocalRing.maximalIdeal R)
    (hfactor : P = Polynomial.C (π ^ n) * Q) :
    ∀ i : ℕ, P.coeff i ∈ IsLocalRing.maximalIdeal R ^ n := by
  intro i
  have hspan :
      P.coeff i ∈ Ideal.span ({π ^ n} : Set R) :=
    henselFactorization_coeff_mem_span_singleton_pow_of_factor
      (π := π) (n := n) hfactor i
  have hπpow : π ^ n ∈ IsLocalRing.maximalIdeal R ^ n :=
    Ideal.pow_mem_pow hπ n
  have hspan_le :
      Ideal.span ({π ^ n} : Set R) ≤ IsLocalRing.maximalIdeal R ^ n :=
    henselFactorization_span_singleton_le_ideal_of_mem
      (IsLocalRing.maximalIdeal R ^ n) hπpow
  exact hspan_le hspan

/-- multiplying a coefficient congruent to zero modulo `π`
by `π^n` puts it in `(π^(n+1))`. -/
theorem henselFactorization_span_singleton_pow_mul_mem_succ
    {R : Type*} [CommRing R] {π x : R} (n : ℕ)
    (hx : x ∈ Ideal.span ({π} : Set R)) :
    π ^ n * x ∈ Ideal.span ({π ^ (n + 1)} : Set R) := by
  rcases (Ideal.mem_span_singleton'.mp hx) with ⟨c, hc⟩
  refine Ideal.mem_span_singleton'.mpr ⟨c, ?_⟩
  rw [← hc]
  rw [pow_succ]
  ring

/-- a positive power of `π` times any coefficient is
congruent to zero modulo `π`. -/
theorem henselFactorization_pow_mul_mem_span_singleton_of_pos
    {R : Type*} [CommRing R] {π x : R} {n : ℕ} (hn : 1 ≤ n) :
    π ^ n * x ∈ Ideal.span ({π} : Set R) := by
  refine Ideal.mem_span_singleton'.mpr ⟨π ^ (n - 1) * x, ?_⟩
  have hpow : π ^ (n - 1) * π = π ^ n := by
    rw [← pow_succ, Nat.sub_add_cancel hn]
  calc
    (π ^ (n - 1) * x) * π = (π ^ (n - 1) * π) * x := by ring
    _ = π ^ n * x := by rw [hpow]

/-- the quadratic term in the Hensel update is automatically
in `(π^(n+1))` once `n ≥ 1`. -/
theorem henselFactorization_span_singleton_pow_mul_pow_mem_succ_of_pos
    {R : Type*} [CommRing R] {π x : R} {n : ℕ} (hn : 1 ≤ n) :
    π ^ n * (π ^ n * x) ∈ Ideal.span ({π ^ (n + 1)} : Set R) :=
  henselFactorization_span_singleton_pow_mul_mem_succ
    (π := π) (x := π ^ n * x) n
    (henselFactorization_pow_mul_mem_span_singleton_of_pos
      (π := π) (x := x) hn)

/-- reversing the sign of a coefficientwise congruence modulo
the principal ideal `(π)`. -/
theorem henselFactorization_correction_congruence_symm_span_singleton
    {R : Type*} [CommRing R] {π : R} {A B : R[X]}
    (hcong : ∀ i : ℕ, (A - B).coeff i ∈ Ideal.span ({π} : Set R)) :
    ∀ i : ℕ, (B - A).coeff i ∈ Ideal.span ({π} : Set R) := by
  intro i
  have hneg :
      -((A - B).coeff i) ∈ Ideal.span ({π} : Set R) :=
    (Ideal.span ({π} : Set R)).neg_mem (hcong i)
  convert hneg using 1
  simp [Polynomial.coeff_sub]

/-- the algebraic power-improvement step: if
`f - g h = π^n f_n` and the chosen correction satisfies
`g q + h p ≡ f_n mod π`, then after the update
`g ↦ g + π^n p`, `h ↦ h + π^n q`, every coefficient of the new error lies in
`(π^(n+1))`. -/
theorem henselFactorization_power_update_error_coeff_mem_span_singleton
    {R : Type*} [CommRing R] {π : R} {n : ℕ} (hn : 1 ≤ n)
    {f g h fn p q : R[X]}
    (hfactor : f - g * h = Polynomial.C (π ^ n) * fn)
    (hcorr :
      ∀ i : ℕ, (g * q + h * p - fn).coeff i ∈
        Ideal.span ({π} : Set R)) :
    ∀ i : ℕ,
      (f - (g + Polynomial.C (π ^ n) * p) *
          (h + Polynomial.C (π ^ n) * q)).coeff i ∈
        Ideal.span ({π ^ (n + 1)} : Set R) := by
  intro i
  have hsymm :
      (fn - (g * q + h * p)).coeff i ∈ Ideal.span ({π} : Set R) :=
    henselFactorization_correction_congruence_symm_span_singleton
      (π := π) (A := g * q + h * p) (B := fn) hcorr i
  have hfirst :
      π ^ n * (fn - (g * q + h * p)).coeff i ∈
        Ideal.span ({π ^ (n + 1)} : Set R) :=
    henselFactorization_span_singleton_pow_mul_mem_succ (π := π) n hsymm
  have hsecond :
      π ^ n * (π ^ n * (p * q).coeff i) ∈
        Ideal.span ({π ^ (n + 1)} : Set R) :=
    henselFactorization_span_singleton_pow_mul_pow_mem_succ_of_pos
      (π := π) (x := (p * q).coeff i) hn
  have herr :
      f - (g + Polynomial.C (π ^ n) * p) *
          (h + Polynomial.C (π ^ n) * q) =
        Polynomial.C (π ^ n) * (fn - (g * q + h * p)) -
          Polynomial.C (π ^ n) * (Polynomial.C (π ^ n) * (p * q)) := by
    have hf : f = Polynomial.C (π ^ n) * fn + g * h := by
      calc
        f = (f - g * h) + g * h := by ring
        _ = Polynomial.C (π ^ n) * fn + g * h := by rw [hfactor]
    rw [hf]
    ring
  have hcoeff :
      (f - (g + Polynomial.C (π ^ n) * p) *
          (h + Polynomial.C (π ^ n) * q)).coeff i =
        π ^ n * (fn - (g * q + h * p)).coeff i -
          π ^ n * (π ^ n * (p * q).coeff i) := by
    rw [herr]
    simp only [Polynomial.coeff_sub, Polynomial.coeff_C_mul]
  rw [hcoeff]
  exact (Ideal.span ({π ^ (n + 1)} : Set R)).sub_mem hfirst hsecond

/-- factor form of the power-improvement step. -/
theorem henselFactorization_power_update_error_factor_exists
    {R : Type*} [CommRing R] {π : R} {n : ℕ} (hn : 1 ≤ n)
    {f g h fn p q : R[X]}
    (hfactor : f - g * h = Polynomial.C (π ^ n) * fn)
    (hcorr :
      ∀ i : ℕ, (g * q + h * p - fn).coeff i ∈
        Ideal.span ({π} : Set R)) :
    ∃ fnNext : R[X],
      f - (g + Polynomial.C (π ^ n) * p) *
          (h + Polynomial.C (π ^ n) * q) =
        Polynomial.C (π ^ (n + 1)) * fnNext :=
  henselFactorization_exists_factor_of_coeff_mem_span_singleton
    (a := π ^ (n + 1))
    (P := f - (g + Polynomial.C (π ^ n) * p) *
      (h + Polynomial.C (π ^ n) * q))
    (henselFactorization_power_update_error_coeff_mem_span_singleton
      (π := π) hn hfactor hcorr)

/-- maximal-ideal correction congruence rewritten through a
principal ideal containing the maximal ideal. -/
theorem henselFactorization_correction_congruence_span_singleton_of_maximalIdeal_le
    {R : Type*} [CommRing R] [IsLocalRing R] {π : R} {A B : R[X]}
    (hπ : IsLocalRing.maximalIdeal R ≤ Ideal.span ({π} : Set R))
    (hcong : ∀ i : ℕ, (A - B).coeff i ∈ IsLocalRing.maximalIdeal R) :
    ∀ i : ℕ, (A - B).coeff i ∈ Ideal.span ({π} : Set R) := by
  intro i
  exact hπ (hcong i)

/-- explicit local-ring form of the power update.  This is
the step used in the recursive Hensel construction when the correction
congruence modulo the maximal ideal can be read modulo `(π)`. -/
theorem henselFactorization_power_update_error_factor_exists_of_maximalIdeal_correction_le
    {R : Type*} [CommRing R] [IsLocalRing R] {π : R} {n : ℕ} (hn : 1 ≤ n)
    (hπ : IsLocalRing.maximalIdeal R ≤ Ideal.span ({π} : Set R))
    {f g h fn p q : R[X]}
    (hfactor : f - g * h = Polynomial.C (π ^ n) * fn)
    (hcorr :
      ∀ i : ℕ, (g * q + h * p - fn).coeff i ∈
        IsLocalRing.maximalIdeal R) :
    ∃ fnNext : R[X],
      f - (g + Polynomial.C (π ^ n) * p) *
          (h + Polynomial.C (π ^ n) * q) =
        Polynomial.C (π ^ (n + 1)) * fnNext :=
  henselFactorization_power_update_error_factor_exists
    (π := π) hn hfactor
    (henselFactorization_correction_congruence_span_singleton_of_maximalIdeal_le
      (π := π) hπ hcorr)


end Valuations
end AlgebraicNumberTheory

end
